### ISSUE TITLE
l3keys: implement .str_... similar to .tl_...

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex3#1007]
There are already  `.tl_set:N` and `.tl_set_x:N`, similar`.str_set:N` and `.str_set_x:N` would be welcome.

```
key .code:n = \str_set:Nn \l_my_str {##1},
```
would be replaced by
```
key .str_set:N = \l_my_str,
```
For better readability and simpler ## management.

For example, when dealing with file names, strings are in general better suited than token lists.

**Comment by blefloch** [comment]
This was done in pull #1008, now merged.
