### ISSUE TITLE
Test if integer is in a range

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#1011]
I propose to add an `\int_range_if_in:nn` conditional, used as follows (for instance here I give some true cases)
```
\int_range_if_in:nnTF { [3,40) } { 15 } \TT \FF
\int_range_if_in:nnTF { 3 } { 3 } \TT \FF
\int_range_if_in:nnTF { (,40) } { -100 } \TT \FF
\int_range_if_in:nnTF { [10,) } { \c_max_int } \TT \FF
```
Namely the first argument is either a single integer (denoting an interval containing one integer), or of the form `{M,N}` where `{` is a parenthesis to denote a strict inequality or is a bracket, same for `}`, and where `M` and `N` are either integers or empty, the latter case denoting infinity.
Here is a possible implementation which you can try out by putting `\makeatletter\ExplSyntaxOn`.
```
\cs_new:Npn \@@_use_none_delimit_by_s_stop:w #1 \s_@@_stop { }
\prg_new_conditional:Npnn \int_range_if_in:nn #1#2 { p , T , F , TF }
  {
    \exp_after:wN \@@_range_if_in_auxi:w
    \int_value:w \int_eval:n {#2} \exp_after:wN ;
    \exp:w \exp_end_continue_f:w #1 , ,
    \s_@@_stop
  }
\cs_new:Npn \@@_range_if_in_auxi:w #1 ; #2#3 ,
  {
    \if_meaning:w [ #2 \else: % ]
      \if_meaning:w ( #2 \else: % )
        \@@_range_if_in_single:w #2
      \fi:
      \@@_range_if_in_auxii:w
    \fi:
    \tl_if_empty:nT {#3} { \@@_range_if_in_skip:w }
    \if_int_compare:w #1 < \int_eval:n {#3} \exp_stop_f:
      \prg_return_false:
      \exp_after:wN \@@_use_none_delimit_by_s_stop:w
    \fi:
    \exp_after:wN \@@_range_if_in_auxiii:w
    \int_value:w #1 \exp_after:wN ;
    \int_value:w \__int_eval:w
    \exp_after:wN \@@_range_if_in_inf:N \exp:w \exp_end_continue_f:w
  }
\cs_new:Npn \@@_range_if_in_auxii:w #1 \if_int_compare:w #2 <
  { #1 \reverse_if:N \if_int_compare:w #2 > }
\cs_new:Npn \@@_range_if_in_skip:w #1 \fi: { }
\cs_new:Npn \@@_range_if_in_single:w
    #1 #2 \if_int_compare:w #3 < \int_eval:n #4#5 \exp_end_continue_f:w #6 , \s_@@_stop
  {
    \fi: \fi:
    \tl_if_empty:nF {#6} { \ERROR_BAD_INPUT }
    \if_int_compare:w #3 = \int_eval:n { #1 #4 } \exp_stop_f:
      \prg_return_true:
    \else:
      \prg_return_false:
    \fi:
  }
\cs_new:Npn \@@_range_if_in_inf:N #1
  { % [ [ (
    \if_meaning:w ) #1
      \c_max_int \exp_after:wN ]
    \else:
      \if_meaning:w ] #1
        \c_max_int
      \fi:
      \exp_after:wN #1
    \fi:
  }
\cs_new:Npn \@@_range_if_in_auxiii:w #1 ; #2 ,
  {
    \exp_after:wN \@@_range_if_in_auxiv:w
    \__int_to_roman:w -0 \use_none:n #2 \s_@@_mark
    \exp_after:wN \@@_use_none_delimit_by_s_stop:w
    \if_int_compare:w #1 < #2
      \s_@@_stop \prg_return_true:
    \else:
      \s_@@_stop \prg_return_false:
    \fi:
    \@@_use_none_delimit_by_s_stop:w % check there is no unexpected junk left?
  }
\cs_new:Npn \@@_range_if_in_auxiv:w #1#2 \s_@@_mark
  { % [ (
    \tl_if_empty:nF {#2} { \ERROR_BAD_INPUT }
    \if_meaning:w ) #1 \else:
      \if_meaning:w ] #1 \else:
        \ERROR_BAD_INPUT
      \fi:
      \@@_range_if_in_auxii:w
    \fi:
  }
```

**Comment by josephwright** [comment]
I have no issue with the idea, but I wonder about the name: isn't it more `\int_if_in_range`?

**Comment by blefloch** [comment]
I agree the name doesn't read well.  I was modelling it after `\tl_if_in:nnTF` or `\clist_if_in:nnTF` where the list comes first.

Another question is my choice of "empty means infinity", and the support for a single integer.  The idea is to help support things like the font size ranges of `fd` files.  Thinking about it, I need to provide a floating point version rather than an integer version, I suppose?

**Comment by u-fischer** [comment]
Would  `\int_if_in:nnTF` work with the additional syntax for "in a set"?

    \int_if_in:nnTF { {3,15,4} } { 3 } \TT \FF

**Comment by eg9** [comment]
Agree with @josephwright about the name. Or, maybe, `\int_if_range:nnTF`?

 No problem with the empty part denoting the relevant infinity, although such tests are already doable with `\int_compare:nTF`.

A single integer doesn't really qualifies as a range. Equal bounds should definitely be supported, because one might have
```
\int_if_range:nnTF { [\l_my_A_int,\l_my_B_int] } { \l_my_C_int } \TT \FF
```
and the first two might be equal. On the contrary I don't see the need for allowing a single integer.

*Also* a floating point version is needed. For the integer version, I believe that `\int_if_in_range_p:nn` might be useful.

**Comment by blefloch** [comment]
I think the combination of your comments suggests we should actually provide a new `intset` datatype (and `fpset`) to keep track of subsets of the integers, so

    \intset_new:N \g_small_primes_intset
    \intset_gset:Nn \g_small_primes_intset { [2,8) , 11, (12, 17] }
    \intset_gremove:Nn \g_small_primes_intset { 4, 6 , [14,16] }
    \intset_show:N \g_small_primes_intset % > [2,3], 5, 7, 11, 13, 19.
    \intset_if_in:NnTF \g_small_primes_intset { 5 } { \TRUE } { \ERROR }
    \intset_map_inline:Nn \g_small_primes_intset { \iow_term:n { #1~is~prime } }
    \int_case_intset:nn { 11 }
      {
        \g_small_primes_intset { \iow_term:n {#1~is~prime} }
        { (,1], 4, 6 } { \iow_term:n { smaller~than~7 } }
      }
    \intset_if_empty:NTF \g_small_primes_intset { \ERROR } { \FALSE }
    \intset_if_full:nTF { 1, 3, [4,), 2, [- \c_max_int, 0] } { \TRUE } { \ERROR }

**Comment by eg9** [comment]
@blefloch 

This is really interesting. What would be the complexity of the transformation by `\intset_gremove`? I'm expecting quite a lot of shuffling around.

**Comment by blefloch** [comment]
For reference this was already proposed in #24 and closed (nothing much to gather from that issue).

`\intset_gremove` is O(N M) naively for a sets of N and M ranges because of TeX's inability to deal with two separate input streams.  Using toks or intarray this can be brought down to the more expected O(M+N).  I'll quickly implement the slow but dumb approach.  I'm betting that someone (Skillmon for instance?) will later speed things up.

Does it need to deal with big integers?  I tend towards no because of the large slow down.

**Comment by blefloch** [comment]
I'm having second thoughts, maybe having a whole datatype is overkill when the only applications I can think of are

- a function `\int_case_intset:nnTF` meant to distinguish various ranges of values and do different things depending on where a given argument sits within these ranges;
- condensing page lists or citation lists into ranges, which would naturally require dealing with more complicated input such as mapping `1a,1b,1c,3,4,5` to `1a-c,3-5` (or not, depending on other context).

More thoughts welcome.

**Comment by wspr** [comment]
I’m surprised by the order of the arguments — under the int module shouldn’t the first arg be the int being tested? (Esp. If there is an N variant.)

I was going to say (I change my mind by the end of this comment) that I would find this more useful out of the box if the range argument allowed multiple specifications. As mentioned in the issue #24, I think it’s a needed programming feature to say

“I’ve been given integer N and there is a some combo-range-like specification of (pages/chars/whatever) that I need to match”

E.g., Pdfpages would use something equivalent when you write “pages={-3,5,7-}“

however, I doubt we could get away with a pdfpages-like keyval argument that had to be written 

    Pages={ (,3), 5, (7,) }

So I think it is better to leave this particular function without any looping and wherever appropriate have a higher level function that handles document syntax.

**Comment by josephwright** [comment]
After discussion, this looks like the wrong level
