### ISSUE TITLE
l3keys' .initial:n is not setting \l_keys_key_str

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#1013]
When processing `.initial:n`, only `\l_keys_path_str` is set, and not `\l_keys_key_str` (perhaps others are also missing?).  This shows up in #1010 in the following MWE:
```
\ExplSyntaxOn
\keys_define:nn { my } {
  mykey .bool_set:N = \g__my_bool,
  mykey .initial:n = \c_true_bool,
}
```
The error message reads `! LaTeX3 error: Key '' accepts boolean values only.` because `\l_keys_key_str` is empty rather than containing the key name `mykey`.

**Comment by mgkurtz** [comment]
It seems like `boolean-values-only` is the only error message in `l3keys` that is called with `\l_keys_key_str`. All the other error messages (including the related `value-forbidden`) receive `\l_keys_path_str`. The full path also seems to be more helpful to me than the mere key name.

So maybe we should solve this issue by simply replacing
```
\msg_error:nnx { keys } { boolean-values-only } \l_keys_key_str
```
by
```
\msg_error:nnx { keys } { boolean-values-only } \l_keys_path_str
```
at its two occurrences in `l3keys.dtx`.
