### ISSUE TITLE
`l3basics`: Update documentation on fast conditionals

### ISSUE THREAD

**Issue by RuixiZhang42** [latex3/latex3#1020]
In https://github.com/latex3/latex3/pull/822, conditionals ending with `\prg_return_true: \else: \prg_return_false: \fi:` were further optimized by introducing 3 more private expandable macros: `\@@_T_true:w`, `\@@_F_true:w`, and `\@@_TF_true:w`. These code changes were not reflected in the documentation.

https://github.com/latex3/latex3/blob/6b1afb06dc3f301a50057b27d7e31330541d04e4/l3kernel/l3basics.dtx#L2055-L2073

1. The first line should now be `\begin{macro}[EXP]{\@@_p_true:w, \@@_T_true:w, \@@_F_true:w, \@@_TF_true:w}`.
2. The entire description at the end seems outdated. In particular, I cannot see the &ldquo;drawback&rdquo; the old comments were referring to.

       %   argument is empty.  For \enquote{fast} conditionals, |#7| has an 
       %   extra \cs[no-index]{if_\ldots{}}.  To optimize a bit further we 
       %   could replace \cs{exp_after:wN} \cs{use_ii:nnn} and similar by a 
       %   single macro similar to \cs{@@_p_true:w}.  The drawback is that if 
       %   the |T| or |F| arguments are actually missing, the recovery from 
       %   the runaway argument would not insert \cs{fi:} back, messing up 
       %   nesting of conditionals.

**Comment by Skillmon** [comment]
The drawback was referring to a potential implementation like:

```
\cs_new:Npn \@@_TF_true:w \fi: #1#2 { \fi: #1 }
```

The recovery from this would be to completely ignore the replacement text of `\@@_TF_true:w`, but only after the `\fi:` was already gobbled.

Can you look at https://github.com/latex3/latex3/pull/1021 and see whether that's fine please?

**Comment by RuixiZhang42** [comment]
@Skillmon 
> The drawback was referring to a potential implementation like:
> 
> ```
> \cs_new:Npn \@@_TF_true:w \fi: #1#2 { \fi: #1 }
> ```

Ah, I see. But then another minor question arises: Since `\@@_p_true:w` and friends simply swap the token after `\fi:` (they do not absorb branch code), there is no need for them to be `\long`, right? So `\cs_set_nopar:Npn` would be fine?

**Comment by RuixiZhang42** [comment]
@Skillmon In fact, making them explicitly non-`\long` in the code would strengthen the idea of recovering from runaway argument. (An indication that `\@@_p_true:w` and friends do not absorb any `T` or `F` branches.)

**Comment by blefloch** [comment]
@RuixiZhang42 In the past we were careful to make `_nopar` any function that could not possibly receive `\par`, but that required some thought.  For instance `\int_eval:n` should be long, because one may want to do `\int_eval:n { \tl_count:n {#1} + 3 }` where `#1` is arbitrary.  So it turns out that very few functions could be made `_nopar`.  We realized also that there is really no point in making a function `_nopar` since there is no speedup, so we decided some time ago to make everything `\long`, unless there is a good reason.  Good reasons include
- some interface functions, such as to make document commands where `\par` should be forbidden,
- functions that are defined in a tight loop, where the indirection from `\cs_set:Npn` to `\long\def` is wasteful and the primitive `\cs_set_nopar:Npn` is faster.

**Comment by dbitouze** [comment]
> We realized also that there is really no point in making a function `_nopar` since there is no speedup, so we decided some time ago to make everything `\long`, unless there is a good reason.

@blefloch I thought a good reason was that errors were easier to locate in the case of non-`\long` commands than in the case of `\long` commands.

**Comment by josephwright** [comment]
@dbitouze  In theory yes, but at the programming layer it's extremely hard to rule out a `\par` as legitimate input. Int he interface layer (`ltcmd`) we have kept that distinction, though I wonder even there if it's useful with modern editors, compilation speeds, etc. Certainly if I were re-implementing something LaTeX-like from scratch I'd probably drop it. (I think Hans more-or-less has in ConTeXt, and I wonder what Don Hoesk is doing for finl.)

**Comment by FrankMittelbach** [comment]
In my opinion it has its usage on the document level and will continue to have there, but not at the programming level (unless you are writing a command that is supposed to  be directly used at document level (with only a name change) in which case it depends on what that document level should convey).  So on the whole I wouldn't go as far as saying it should never be there (like `\outer`) but using it not on the programming level (normally) makes sense imo.

**Comment by Skillmon** [comment]
Hans has implemented a switch in LuaTeX (`\suppresslongerror`) to deactivate the error when a non-`\long` function absorbs a `\par`, and that switch is by default set to 1 in ConTeXt.
