### ISSUE TITLE
`l3int`: *a*`*`*b* cannot be “arbitrarily large” in a scaling operation

### ISSUE THREAD

**Issue by RuixiZhang42** [latex3/latex3#1022]
This issue concerns only the documentation:

https://github.com/latex3/latex3/blob/1bbc727f7bf57a6ea61da7882fd0c68b6d059706/l3kernel/l3int.dtx#L72-L76

Technically speaking, the last sentence should be:
```latex
%   $a$\texttt{*}$b$\texttt{/}$c$, for which $a$\texttt{*}$b$ may be
%   (temporarily) as large as $(2^{31}-1)^2$ in absolute value;
```

**Comment by jfbu** [comment]
When I read "arbitrarily large" I also stopped but considered it to be correct in so far as argument `a` or `b` beyond TeX bound would raise an overflow error on their own, so this error can not be considered to be a limitation of the scaling operation itself.

**Comment by blefloch** [comment]
I opted to add `(but the operands $a$, $b$, $c$ are still constrained to an absolute value at most $2^{31}-1$)` as a clarification: since the behaviour of `a*b/c` is slightly unexpected it is good to be specific about what extra possibilities it opens up and what possibilities it does not.
