### ISSUE TITLE
Please add \verytiny for very small text

### ISSUE THREAD

**Issue by johnrachwan123** [latex3/latex3#1033]

**Comment by FrankMittelbach** [comment]
Thanks for the suggestion, but providing this as part of core LaTex is not advisable. The standard size commands from `\tiny`to `\Huge` are expected to be implemented by all document classes and adding to that would only provide  a lot of disruption without much gain. Furthermore, in many cases `\tiny` is  5pt and in such cases going even smaller has few if any applications.

If you need such a small size for your document it is trivial to provide it, tailored to your actual needs, e.g.,
```
\newcommand\verytiny{\fontsize{3pt}{4pt}\selectfont}
```
Of course this only works with fonts that have such small sizes available or could be scaled down to it. For example, with the default Computer Modern, you would need to additionally load the `fix-cm` package, or use `lmodern` or some other font.
