### ISSUE TITLE
l3keys .initial does not reset within a group

### ISSUE THREAD

**Issue by Imericxu** [latex3/latex3#1034]
The expected behavior is to use the `.initial` value if the key is not set, however, the value is not reset when a command is called multiple times within a group. Maybe I’m misunderstanding its usage but I feel like that’s the expected behavior.

`expl3` version: 2021-11-22
TeX system: mactex-no-gui: 2021.0328
Engine: pdfTeX

MWE:

```{tex}
\documentclass[12pt]{article}
\usepackage{expl3}
\usepackage{xparse}

\ExplSyntaxOn
\keys_define:nn { my_keys }
  {
    var .int_set:N = \l__my_keys_var_int,
    var .initial:n = 10
  }

\NewDocumentCommand \mycommand { O{} }
  {
    \keys_set:nn { my_keys } { #1 }
    \int_use:N \l__my_keys_var_int
  }
\ExplSyntaxOff

\begin{document}
  \begingroup
    Group start

    \verb|\mycommand|: \mycommand\ (expected = 10)

    \verb|\mycommand[var=20]|: \mycommand[var=20]\ (expected = 20)

    \verb|\mycommand|: \mycommand\ (expected = 10)

    Group end
  \endgroup

  \verb|\mycommand|: \mycommand\ (expected = 10)
\end{document}
```

**Comment by Skillmon** [comment]
You're misunderstanding what `.initial:n` does. It doesn't set a value which is restored on each call of `\set_keys:nn` but it sets a starting value for your key. That is a value that is used if the key was never used. All in all `.initial:n` is the same as if you used `\keys_set:nn {<set>} {<key>=<val>}` at that spot (which you can't do inside of `\keys_define:nn`).

**Comment by Imericxu** [comment]
Oh, I see. Then to get my desired behavior, I should explicitly set all the keys in `keys:define:nn` and add `#1` after, right? Or is there a better way?

**Comment by u-fischer** [comment]
if you want your command to reset the var, use something like 

~~~~
\NewDocumentCommand \mycommand { O{} }
  {
    \keys_set:nn { my_keys } { var=10,#1 }
    \int_use:N \l__my_keys_var_int
  }
~~~~

or


~~~~
\keys_define:nn { my_keys }
  {
    var .int_set:N = \l__my_keys_var_int,
    var .initial:n = 10,
    var .default:n = 10
  }



\NewDocumentCommand \mycommand { O{} }
  {
    \keys_set:nn { my_keys } { var,#1 }
    \int_use:N \l__my_keys_var_int
  }
~~~~

**Comment by Imericxu** [comment]
Oops, I meant `\keys_set:nn` like you said. Thank you for clarifying!
