### ISSUE TITLE
l3regex: both extract and replace

### ISSUE THREAD

**Issue by lvjr** [latex3/latex3#1045]
In my package, I need to extract some tokens from the start of a token list, remove them, and do something with the matches. With `\regex_extract_once` I can not remove the whole match, while with `\regex_replace_once` I can not use the matches `seq` inside `true code` or `false code`. Therefore I had to use both of them and the code looks like this:
```latex
\regex_const:Nn \l__codehigh_comment_regex { ^ \% \% ( [\%>] ) ( [^\r]+ ) \r }
\regex_extract_once:NVNTF \l__codehigh_comment_regex \l_tmpa_tl \l_tmpa_seq
  {
    \regex_replace_once:NnN \l__codehigh_comment_regex {} \l_tmpa_tl
    \str_if_eq:enT { \seq_item:Nn \l_tmpa_seq {2} } {>}
      {
        \tl_put_right:Nx \l__codehigh_comment_tl
          { \seq_item:Nn \l_tmpa_seq {3} }
      }
  } 
  { \bool_set_true:N \l__codehigh_comment_bool }
```
The above code requires double running time for `regex`. So the feature request is: could I use the matches in `true code` and `false code` when I am using `\regex_replace_once`? For example, maybe there will be `\l_regex_match_zero_tl`, `\l_regex_match_i_tl`, `\l_regex_match_ii_tl`, ..., `\l_regex_match_ix_tl` for the function.

**Comment by blefloch** [comment]
Have you tried using the `\regex_split_...` functions?  They give you in the same sequence both the stuff that matched and the stuff between the matches.  I don't remember if there are once/all versions of these functions.

On a different note, it seems you are simply grabbing a line and running a test on that line.  Could it make sense to first split your `\l_tmpa_tl` into lines using `\seq_set_split`, then analyze the lines one by one?  That seems quicker than running a regex.

**Comment by lvjr** [comment]
Thanks for your suggestions. I will try them.

**Comment by blefloch** [comment]
I am not certain that my suggestions will suffice; please report back if they do not.
