### ISSUE TITLE
l3keys documentation improvement

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex3#1046]
In l3keys documentation, the notion of module is not really defined.

The documentation of `\keys_define:nn` reads
```
 \keys_define:nn {<module>} {<keyval list>}
...
Parses the <keyval list> and defines the keys listed there for
<module>. The <module> name is treated as a string.
In practice the
<module> should be chosen to be unique to the module in question
(unless deliberately adding keys to an existing module).
 ```
This is not really clear.

Suggestion:

- in the introduction add "a module is a named set of key--value controls"
- avoid the use `keyval` as far as possible because it refers pretty much to `l3prop`,

for example, the above documentation could read

```
 \keys_define:nn {<module name>} {<key-value list>}
...
Parses the <key-value list> and defines the keys listed there for the module
uniquely identified by <module name>. 
<module name> is treated as a string.
\cs{keys_define:nn} can be called multiple times for the same module,
adding new keys or modifying existing ones.
 ```
other changes should be necessary accordingly.

**Comment by josephwright** [comment]
I'm not sure what you mean about `keyval` - `a = a , b = b` is a `keyval`, whereas the `prop` module requires separate arguments for entries and values, and these can only be given one at a time.

**Comment by jlaurens** [comment]
`keyval` appears many times in `l3prop`, mainly as part of the command sequences, which gives a hint about the argument. For example, what is called a `keyval` here cannot always feed `\prop_set_from_keyval:Nn` because the value may be omitted here, but not for l3prop. Choosing a different name in `l3keys` would emphasize the difference.
