### ISSUE TITLE
`\clist_use:nn` seems unexpanded as well as `\clist_use:Nn`

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex3#1049]
Apparently, the new `\clist_use:nn` and `\clist_use:Nn` behave the same regarding x expansion: you must expand twice to have all the items expanded. This is specified in the documentation for `\clist_use:Nn` in a  TeXhackers note, but not for `\clist_use:nn`. Shouldn't there be such a note for `\clist_use:nn` as well ?

**Comment by josephwright** [comment]
Agreed and changed: most of the time, one doesn't really want to double-expand these uses, of course.
