### ISSUE TITLE
doc: x-type or e-type

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex3#1050]
For `\tl_sort:Nn`, `\clist_reverse:n` and `\keyval_parse:nnn`, we have in the TeXhackers note
```
...does not expand further when appearing in an x-type or e-type argument expansion.
```
in other similar situations (l3tl x 7, l3seq x 4, l3clist x 4, l3prop x 1, additions x 2) we only have
```
...does not expand further when appearing in an x-type argument expansion.
```
"or e-type" is missing.

The devil is in the details.

**Comment by blefloch** [comment]
Would it make sense to have a few macros in `l3doc` for such repeated texts?

**Comment by josephwright** [comment]
@blefloch  Probably, or we could use a single definition here for `<expansion context>`.

**Comment by FrankMittelbach** [comment]
> Would it make sense to have a few macros in `l3doc` for such repeated texts?

my experience with that is that it often hurts more than helps. By the end of the day you look at the source and and you have no clue what your abbreviation means. Or you alter the abbreviation but it only applies to 90% of the places where it got used ... 

Here nobody expected that the sentence would have need an adjustment (which explains why the older modules don't talk about e-expansion). So even if we would had the concept of abbreviations, would we have used it for a lone single sentence? On the other hand, do you expect any further change? And even if, is it clear that all places would then have the same behavior?

But I don't mind much, if you feel it makes things better/easier/more maintainable
