### ISSUE TITLE
l3keys doc: \keyval_parse:nnn

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex3#1052]
About `\keyval_parse:nnn {⟨code1⟩} {⟨code2⟩} {⟨key–value list⟩}`: it might be worth mentioning that within both `⟨code1⟩` and `⟨code2⟩` the full path of the key is also available as `\l_keys_path_str`.

**Comment by josephwright** [comment]
@jlaurens I'm not quite sure how this works out: if you are using `\keyval_parse:nnn` then you are doing your own setup, whereas if you are thinking in terms of `\l_keys_path_str` then you'd be using the version 'wrapped up' inside `\keys_set:nn`.

**Comment by Skillmon** [comment]
@jlaurens as @josephwright already wrote (but imho not really clear enough): `\keyval_parse:nnn` will *not* set `\l_keys_path_str` nor any other macro. It works by expansion only, it doesn't assign things to anything.

Inside of `\keys_set:nn` the code forwarded by it to the underlying `\keyval_parse:nnn` does the assignments.
