### ISSUE TITLE
precision in \keys_set_unknown:nnnN doc

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex3#1053]
The doc reads,
"When a ⟨root⟩ is given (`\keys_set_known:nnnN`), the key–value entries are returned relative to this point in the key tree."
we can add
"In particular, if ⟨root⟩ and ⟨module⟩ are identical, the returned keys are identical to those in the input list whereas for a void ⟨root⟩, the returned keys are the full key paths. When the input keys may contain a '/', `\keys_set_known:nnnN` should be preferred over `\keys_set_known:nnN`."

Of course, the same precision would take place for `\keys_set_filter:nnnnN`.

**Comment by josephwright** [comment]
We do not think that adding more text will clarify significantly: a user is likley to carry out their own tests before using this feature.
