### ISSUE TITLE
l3keys feat request: .key_forbidden:n and .key_required:n

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex3#1054]
l3keys already has `.value_forbidden:n` and `.value_required:n`.
For a `.choice:` key, we have 3 syntactically correct calls as illustrated below: `key=choice-a`, `key/choice-a`, `key/choice-a = VALUE`.
Both execute the same instructions.
```
\documentclass{article}
\begin{document}
\ExplSyntaxOn
\ttfamily
\keys_define:nn { mymodule } {
  key .choice:,
  key/choice-a .code:n = {
      VALUE:~\l_keys_value_tl=#1\\
      KEY:~\l_keys_key_str\\
      PATH:~\l_keys_path_str
    },
}
\begin{itemize}
\clist_map_inline:nn {
  key=choice-a,
  key/choice-a,
  key/choice-a = VALUE,
} {
  \item #1\\
  \keys_set:nn { mymodule } { #1 }
}
\end{itemize}
\ExplSyntaxOff
\end{document}
```
![Capture d’écran 2022-02-20 à 04 42 24](https://user-images.githubusercontent.com/1617871/154827594-f3392c05-5368-45ce-9d89-516a0df9e133.png)

We can see that each call gives different parameters to the `.code:n` instructions.
We can eliminate the 3rd case `key/choice-a = VALUE`, which has no real meaning, with a `key/choice-a .value_forbidden:n = true,` instruction.

Keeping `key=choice-a` and `key/choice-a` altogether adds an extra overhead for the programmer. Not very difficult though. Nevertheless, one should be allowed to forbid the standalone `key/choice-a` instruction. A `.key_forbidden:n` would help for that purpose. For the `.choices:nn` case, a similar `.key_forbidden:nn` with its variants would be welcome as well. Of course, this also concerns `.multichoice:` keys.

Once we have a `.key_forbidden:n`, why not a `.key_required:n`? This would correspond to a mandatory named argument.

**Comment by jlaurens** [comment]
`.key_required:n` is too complicated to manage because `keys_set:nn` may be called multiple times. In that case, which choice should check for the missing keys?

**Comment by josephwright** [comment]
We have discussed and at present we do not see that this would fit the model used by `l3keys`.
