### ISSUE TITLE
interface3.pdf: about variants

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex3#1061]
The documentation of `cs_generate_variant:Nn` reads

```
The \cs_generate_variant:Nn function can only be applied if the ⟨parent control sequence⟩ is already defined.
```
This is not true as shown by the example below.
```
\documentclass{article}
\begin{document}
\ExplSyntaxOn
\cs_generate_variant:Nn \My:n { V }
\cs_new:Npn \My:n #1 { #1 }
\int_set:Nn \l_tmpa_int { 123 }
\My:V \l_tmpa_int
\ExplSyntaxOff
\end{document}
```
Maybe it was "must only be applied" or something like
```
The generated variant function can only be called if the ⟨parent control sequence⟩ is already defined.
```

In that respect, my understanding is that there is no need to redefine variants after a parent has changed. Whether I am correct or not, something on that matter would certainly help.

Finally, `\prg_generate_conditional_variant:Nnn` should be mentioned at the end of `\cs_generate_variant:Nnn` documentation.

**Comment by josephwright** [comment]
You need debugging enabled to get an error here, for performance reasons:
```latex
\RequirePackage[enable-debug]{expl3}
\ExplSyntaxOn
\debug_on:n { check-declarations , deprecation , log-functions }
\ExplSyntaxOff
```

**Comment by FrankMittelbach** [comment]
I agree that should/must would be better and also to have the x-ref to and from the conditional variants
