### ISSUE TITLE
Add Lua-based color to the core `l3color` approach

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#1062]
`LuaLaTeX` doesn't color is insensible to `l3color`'s `\color_fill:n`, as shown by the following MCE.
```latex
\documentclass{article}
\usepackage{luacolor}
\paperheight=.5cm
\paperwidth=2cm
\ExplSyntaxOn
\AddToHook{shipout/background}
{%
  \put(0.5\paperwidth,-0.5\paperheight)
  {%
    \makebox[0pt][c]{
      \color_fill:n {red}
      RED?
      \color{red}
      RED!
    }
  }%
}
\ExplSyntaxOff
\begin{document}
\mbox{}
\end{document}
```
![image](https://user-images.githubusercontent.com/1032633/156005284-7d6101c3-437d-4059-812d-1015e0231011.png)

**Comment by josephwright** [comment]
Short answer: by-design. Longer answer: `luacolor` works by explicitly parsing nodes for the necessary data in an attribute. We have some code we are considering for use with LuaTeX/`l3color` but have not yet decided whether to go for this or if we do exactly how.

**Comment by josephwright** [comment]
https://github.com/latex3/latex3/pull/944

**Comment by josephwright** [comment]
https://github.com/latex3/latex3/issues/585
