### ISSUE TITLE
interface3d.pdf terminology: argument specification vs argument specifier

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex3#1066]
In the documentation of `\cs_argument_spec:N` and `\cs_replacement_spec:N`, "argument specification" means the 'p' part of a macro definition. This is not so easy to guess for the second function.

In all other places, it refers to something very different, the signature after the `:` in function names. Sometimes it is an argument specification, sometimes it is an argument specifier. The worst situation is p 61 where the `p` argument is an `<argument specification>` whereas on next line "argument specification" refers to the signature.

Personally, I would stick to "parameter specification" to denote the value of a `p` argument, and "argument specifier" for 
the signature.

**Comment by josephwright** [comment]
Agreed there is some overlap in naming. We will rename `\cs_argument_spec:N` (with appropriate deprecation) to `\cs_parameter_spec:N`  and adjust the docs in this area accordingly.
