### ISSUE TITLE
About sequence items and prop values

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex3#1067]
Would it be possible to have some place in the documentation where sequence items and prop value are discussed in greater details. In particular, what are the exact data types supported and how they are. Actually tl, str, quarks and clist pose no problem. 
Next coding pattern demonstrates how to push and pop some fp data to a sequence, but is it supported?
```
% !TeX program = lualatex
\documentclass{article}
\begin{document}
\noindent
\ExplSyntaxOn
\fp_set:Nn \l_tmpa_fp { 3.14e-3 }
\seq_push:NV \l_tmpb_seq \l_tmpa_fp
\seq_pop:NN \l_tmpb_seq \l_tmpb_fp
\fp_sub:Nn \l_tmpb_fp { 0.0031 }
\fp_use:N \l_tmpb_fp
\end{document}
```
Same problem for regex, prop, seq, int...

**Comment by josephwright** [comment]
Well, your first issue here is that at present `V`-type expansion doesn't support `fp` (as they are internally macros-with-special-structure, while their value is a simply float).

**Comment by josephwright** [comment]
The values in both cases are token lists: variables which have a `tl` representation (`int`, etc.) can be stored, those which don't (`box`, `seq`, `prop`, etc., but also at least formally `fp`) can't.

**Comment by jlaurens** [comment]
I was thinking of something more permissive like "the only types that cannot be stored in `seq` or `plist` are `box`, `coffins`?, `intarray` and `fparray`."

## simple case
The problem is to serialize and deserialized from a data type to tl. For `tl`, `str`, `quark`, `clist` and `regex` this is straightforward because they are token lists.

For registers: `int`, `dim`, `skip`, `muskip` serialization is given by `\<type>_use:N` whereas deserialization is given by `\<type>_set:Nn`.

## booleans
For bools, things are quite similar to `tl`, except that below `\seq_put_right:No` must be used, `\seq_put_right:NV` raises an error (is is a bug?).
```
\bool_set_false:N \l_tmpa_bool
\seq_clear:N \l_tmpa_seq
\seq_put_right:No \l_tmpa_seq \l_tmpa_bool
\bool_if:nTF {\seq_item:Nn \l_tmpa_seq 1} {FAILED}{EXPECTED}\\ % ⟵ direct test
\bool_set:Nn \l_tmpb_bool {\seq_item:Nn \l_tmpa_seq 1} % ⟵ affectation
\bool_if:NTF \l_tmpb_bool {FAILED}{EXPECTED}\\
\bool_set_true:N \l_tmpa_bool
\seq_clear:N \l_tmpa_seq
\seq_put_right:No \l_tmpa_seq \l_tmpa_bool
\bool_if:nTF {\seq_item:Nn \l_tmpa_seq 1} {EXPECTED}{FAILED}\\
\bool_set:Nn \l_tmpb_bool {\seq_item:Nn \l_tmpa_seq 1}
\bool_if:NTF \l_tmpb_bool {EXPECTED}{FAILED}\\
```

## `seq`
We can serialize and deserialize sequences by hand using various methods. Here is a rather simple one where we put each items one after the other and enclosed in braces.
```
\seq_set_from_clist:Nn \l_tmpa_seq {a, b, c}
\tl_clear:N \l_tmpa_tl
\seq_map_inline:Nn \l_tmpa_seq {
  \tl_put_left:Nn \l_tmpa_tl { { #1 } }
}
\seq_clear:N \l_tmpb_seq
\tl_map_inline:Nn \l_tmpa_tl {
  \seq_put_left:Nn \l_tmpb_seq #1
}
```
In fact `seq` variables already contain a token lists such that next `o` pattern works
```
\seq_set_from_clist:Nn \l_tmpa_seq {a, b, c}
\seq_put_right:No \g_tmpa_seq \l_tmpa_seq
\tl_set:Nx \l_tmpb_seq { \seq_item:Nn \g_tmpa_seq 1 }
```
This is very neat, except the `\tl_set:Nn` that could advantageously be replaced by `\seq_set_from_internal:Nn` see #1047 

## `props`
Here again, we can serialize and deserialize `props` by hand using various methods. Here is a rather simple one where we put each key value items one after the other and enclosed in braces twice.
```
\prop_set_from_keyval:Nn \l_tmpa_prop { a = A, b = B, c = C }
\tl_clear:N \l_tmpa_tl
\prop_map_inline:Nn \l_tmpa_prop {
  \tl_put_left:Nn \l_tmpa_tl { { { #1 } { #2 } } }
}
\prop_clear:N \l_tmpb_tl
\tl_map_inline:Nn \l_tmpa_tl {
  \prop_put:Noo \l_tmpb_prop { \use_i:nn #1 } { \use_ii:nn #1 } 
}
```
Here again, `prop` variables already contain a token lists such that next `o` pattern works
```
\prop_set_from_keyval:Nn \l_tmpa_prop { a = A, b = B, c = C }
\seq_put_right:No \g_tmpa_seq \l_tmpa_prop
\tl_set:Nx \l_tmpb_prop { \seq_item:Nn \g_tmpa_seq 1 }
```
Once again very neat, except the `\tl_set:Nn` that could advantageously be replaced by `\prop_set_from_internal:Nn` see #1047 

## `fp`
`fp` can be serialized using the `\fp_to_tl:N` function (`\fp_use:N` is not sufficient). Deserialization is made by `\fp_set:Nn`. Here again, `fp` are implemented as token lists such that the same `o` pattern works again
```
\fp_set:Nn \l_tmpa_fp { 3.14 }
\seq_put_right:No \g_tmpa_seq \l_tmpa_fp
\tl_set:Nx \l_tmpb_fp { \seq_item:Nn \g_tmpa_seq 1 }
```
Still very neat, except the `\tl_set:Nn` that could advantageously be replaced by `\fp_set_from_internal:Nn` see #1047 

## Conclusion
All this was presented with `seq` but it applies to `props` as well.
Finally, `seq` and `prop` support more types than expected at first glance, including the complex ones.
Moreover, officially supporting the `o` pattern for all types that have an underlying token list implementation should be very efficient because it saves serialization/deserialization for `seq`, `prop` and `fp`.
In fact #1047 also applies to `seq` and `fp`

**Comment by josephwright** [comment]
I've made a minor adjustment to `expl3.dtx` since as you observe, `fp` vars can work with `V`-type expansion. Other than that case, we already say in the docs that `V`-type expansion only works for variable types with `\<thing>_use:N` (bar boxes). I think that covers it.
