### ISSUE TITLE
feature request: R and r argument specifiers for raw content

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex3#1068]
This covers #1067 and #1047. With this feature, including `seq`, `prop` and `fp` in `seq` and `prop` is both provided, straightforward and efficient. Moreover, the coding pattern of changes to `seq`, `prop` or `fp` variables to survive the group where they are made is more consistent. This focuses on the API, implementation details are not considered.

In #1047 the use of "internal" was suggested, "raw" seems better on many respects: shorter, `r` does not conflict with the `i` roman numeral, 'r' is more legible than 'i'...

## Description of the `r` and `R` argument specifiers.

Overall description just after the **V and v** item on page 2 of interface3.pdf:

"**R and r** These mean raw content of variable. The R and r specifiers are used to get the raw content of a variable. A R argument will be a single token (similar to N); on the other hand, using r a csname is constructed first, and then the raw content is recovered. These specifiers only apply to variables supporting raw content, which `<type>` has a` \<type>_set_from_raw:Nn` function. Editing or relying on the raw content is not supported: *the format is strictly private*."

## **R and r** expansion
Functionally equivalent to the actual **V and v** because the variables supporting raw content are just token lists. Providing `\exp_args:NNNR` would help (see the group coding pattern below).

## `\<type>_set_from_raw:Nn`
The only types that support raw content are `seq`, `prop` and `fp`: `\seq_set_from_raw:Nn`, `\prop_set_from_raw:Nn` and `\fp_set_from_raw:Nn` are just synonyms of `\tl_set:Nn`. Same for the `c` variants.

The documentation could read
"
`\seq_set_from_raw:Nn ⟨seq var⟩ { ⟨raw content⟩ }`
Sets ⟨seq var⟩ to have ⟨raw content⟩. The ⟨raw content⟩ must be obtained from an `R` or `r` argument.
"

The `\<type>_set_from_raw:Nx` variants should be provided (See the first coding pattern below)

NB: The `\seq_set_from_raw:NR` variant is functionally equivalent to `\seq_set_eq:NN`

NB2: In fact all `tl` like variables could support raw content but adding a `\<type>_set_from_raw:Nn`for each of them would be counterproductive

## setter variants
Only few variants for actual functions:

- `\seq_put_left:NR`
- `\prop_put:NnR`
- `\prop_put_if_new:NnR`

and friends. No need to add a description for these variants because the overall description for **r and R** is sufficient.

## getters
For `seq` and `prop` there is no need for variants. Nevertheless, the documentation should be amended:

"19.3 Recovering items from sequences
Items can be recovered from either the left or the right of sequences. For implementa- tion reasons, the actions at the left of the sequence are faster than those acting on the right. These functions all assign the recovered material locally, i.e. setting the ⟨token list variable⟩ used with \tl_set:Nn and never \tl_gset:Nn."

we can add either

"Instead of a token list variable one can use a variable supporting raw contents, provided the data read is of the same type."

of a more explicit variation

"Instead of a token list variable one can use a `seq`, `prop` or `fp` variable, provided the data read is of the same type."

We can add this at "19.4 Recovering values from sequences with branching", "24.3 Recovering values from property lists" and "24.6 Recovering values from property lists with branching" as well.

## Coding patterns

These may be part of the documentation. 

### sequences of sequences #1067 
Setting
```
\seq_set_from_clist:Nn \l_tmpa_seq { a, b, c }
\seq_clear:N \l_tmpb_seq
\seq_put_right:NR \l_tmpb_seq \l_tmpa_seq
```
getting
```
\seq_set_from_raw:Nx \l_tmpa_seq { \seq_item:Nn \l_tmpb_seq { 1 } }
\seq_get_right:NN \l_tmpb_seq \l_tmpa_seq
```
Same for `props` and `fp`.

### groups #1047
Make a change to a sequence in a group and make the change survive the group
```
\group_begin:
...
<local changes to \l_tmpa_seq>
...
\exp_args:NNNR
\group_end:
\seq_set_from_raw:Nn \l_tmpa_seq \l_tmpa_seq 
```
Same for `props` and `fp`.

More complex patterns may benefit from `\tl_set:NR` and friends variants, picking up the good ones seems uneasy.

**Comment by josephwright** [comment]
We have discussed this, and note that the approach above isn't expansion control, which is the primary aim of arg. types. We know that serialisation, etc., is needed, and this is on our 'to do' list - see issue https://github.com/latex3/latex3/issues/332
