### ISSUE TITLE
`xparse` documentation deprecated options inside main text

### ISSUE THREAD

**Issue by a-is** [latex3/latex3#1069]
There is a typo in the documentation. The following line refers to the `g` option, which has not been declared anywhere before.
https://github.com/latex3/latex3/blob/25523bf1497a3fb3f8868bb1ce8861f6b9e0fae6/l3packages/xparse/xparse.dtx#L219

The `g` option is also found here:
https://github.com/latex3/latex3/blob/25523bf1497a3fb3f8868bb1ce8861f6b9e0fae6/l3packages/xparse/xparse.dtx#L254

**Comment by a-is** [comment]
I looked at the document and found a few more options, the description of which I did not find: `g`, `G`, `l`, `u`.

**Comment by a-is** [comment]
I found a description of these options at the end of the document. Perhaps, however, it is worth mentioning them at the beginning of the document, but the name of the issue should be different.

**Comment by PhelypeOleinik** [comment]
There are argument types `G`, `g`, `l`, and `u`, but they are deprecated, thus documented in a separate (and intentionally harder to find) section:

https://github.com/latex3/latex3/blob/25523bf1497a3fb3f8868bb1ce8861f6b9e0fae6/l3packages/xparse/xparse.dtx#L465-L490

Not sure what these two lines are trying to say though...

https://github.com/latex3/latex3/blob/25523bf1497a3fb3f8868bb1ce8861f6b9e0fae6/l3packages/xparse/xparse.dtx#L218-L219

**Comment by FrankMittelbach** [comment]
> There are argument types `G`, `g`, `l`, and `u`, but they are deprecated, thus documented in a separate (and intentionally harder to find) section:

The earlier places where the deprecated options are mentioned should  carry a remark that G etc is deprecrated (or not even mention them there) I think.

**Comment by PhelypeOleinik** [comment]
Not even mention, I'd say.

**Comment by a-is** [comment]
Perhaps I was too hasty with closing the issue. I will open it by renaming it beforehand.

**Comment by josephwright** [comment]
We'll check that the docs reflect what we actually want them to say.

**Comment by josephwright** [comment]
Docs for `xparse` need to reflect that it's now the stub for the deprecated arg. types - we should point to `usrguide(3)`.

**Comment by josephwright** [comment]
Everything has moved around here: closing.
