### ISSUE TITLE
\tl_case:nn, \str_case:Nn, and \str_if_empty:n

### ISSUE THREAD

**Issue by lvjr** [latex3/latex3#1071]
Recently I compared `tl` and `str` packages:

 - there is `\tl_case:Nn` but not  `\str_case:Nn`
 - there is `\str_case:nn` but not `\tl_case:nn`
 - there is `\tl_if_empty:n` but not `\str_if_empty:n`

Could these missing functions be added to `expl3`?

**Comment by eg9** [comment]
There is `\str_case:Vn` which serves the same purpose as the proposed `\str_case:Nn`.

There is also an inherent difference between `\str_case:Vn` and `\tl_case:Nn`, as the latter compares token list variables (with `\ifx`) and not “explicit” token lists, so `\tl_case:nn` would be “strange”. It could be implemented by setting an internal variable to the given token list and then calling `\tl_case:Nn` for this variable, but I'm not sure this is something we should add.

Indeed, I find strange that  `\str_if_empty:n(TF)` is missing.

**Comment by josephwright** [comment]
I guess `\str_if_empty:n` was missed as it doesn't matter if one uses a `tl` function here - the nature of the non-space tokens is unimportant. However, it's easy enough to add.

As @eg9 says, `\str_case:Nn` is the same as `\str_case:Vn`: again easy to add and again I'm happy to.

I'm not keen on `\tl_case:nn` for the reasons outlined.

**Comment by lvjr** [comment]
I think consistency is important. otherwise it will confuse users. In my opinion, it would be better to use `\str_if_eq:NN` inside `\str_case:Nn` function just like `tl` package.
```latex
\str_set:Nn \l_tmpa_str {\abc}
\str_set:Nn \l_tmpb_str {\abc}
\str_case:VnF \l_tmpa_str
  {
    \uvw        { UVW }
    \l_tmpb_str { TMP }
    \abc        { ABC }
  }
  { No Match }
```
The above code gives `ABC`, which shows that `\str_case:Vn` in not `\str_case:Nn`.

**Comment by blefloch** [comment]
I think `\tl_case:Nn` should be removed or renamed `\cs_case_meaning:Nn`.  It is a leftover from the old days where one had to compare macros with stored values to get any reasonable speed.

**Comment by josephwright** [comment]
> I think consistency is important. otherwise it will confuse users. In my opinion, it would be better to use `\str_if_eq:NN` inside `\str_case:Nn` function just like in `tl` package.
> 
> ```
> \str_set:Nn \l_tmpa_str {\abc}
> \str_set:Nn \l_tmpb_str {\abc}
> \str_case:VnF \l_tmpa_str
>   {
>     \uvw        { UVW }
>     \l_tmpb_str { TMP }
>     \abc        { ABC }
>   }
>   { No Match }
> ```
> 
> The above code gives `ABC`, which shows that `\str_case:Vn` in not `\str_case:Nn`.

I'm not sure what you mean here: the defined behaviour is that `\str_case:Nn` compares the value of each entry to a string. You've omitted the braces in your list of possible strings, but we do not expect to compare with the _value_ of `\l_tmpb_str`, rather those tokens as a string.

**Comment by lvjr** [comment]
>I'm not sure what you mean here: the defined behaviour is that \str_case:Nn compares the value of each entry to a string. You've omitted the braces in your list of possible strings, but we do not expect to compare with the value of \l_tmpb_str, rather those tokens as a string.

Because `\tl_case:Nn` is a shorthand command for some nesting `\tl_if_eq:NN`, therefore in my mind  `\str_case:Nn` should be a shorthand command for some nesting `\str_if_eq:NN`. That is to say, in my mind the syntax of  `\str_case:Nn` is
```latex
\str_case:Nn <test str variable> {
  <str variable case 1> {<code case 1>}
  <str variable case 2> {<code case 2>}
  <str variable case 3> {<code case 3>}
}
```

**Comment by blefloch** [comment]
We concluded \tl_case:Nn should be deprecated and renamed \cs_case_meaning:Nn, but there is already \token_case_meaning:Nn, which seems to fit the bill.  Relatedly, `\tl_if_eq:NN(TF)` is identical to `\token_if_eq_meaning:NN(TF)`.

**Comment by lvjr** [comment]
> We concluded \tl_case:Nn should be deprecated and renamed \cs_case_meaning:Nn, but there is already \token_case_meaning:Nn, which seems to fit the bill. Relatedly, `\tl_if_eq:NN(TF)`, `\cs_if_eq:NN(TF)` and `\token_if_eq_meaning:NN(TF)` have identical definitions, and probably some should be defined as copies of others with the appropriate `prg_new_eq` function.

From the view of TeX hackers, the above is totally correct. If ordinary users are not recommended to use `expl3` in their tex documents, it is a good choice to remove `\tl_case:Nn` from the documentation.

PS: Maybe I has been worrying too much. Just omit my comment. Sorry.

**Comment by josephwright** [comment]
We still need some action here?

**Comment by muzimuzhi** [comment]
> I guess `\str_if_empty:n` was missed as it doesn't matter if one uses a `tl` function here - the nature of the non-space tokens is unimportant. However, it's easy enough to add.
> 
> As @eg9 says, `\str_case:Nn` is the same as `\str_case:Vn`: again easy to add and again I'm happy to.
>
> _<sub>quoted from https://github.com/latex3/latex3/issues/1071#issuecomment-1073849645</sub>_

Still planning to add `\str_if_empty:nTF` and `\str_case:Vn`?
