### ISSUE TITLE
\tl_analysis_map_inline:nn cannot be used recursively

### ISSUE THREAD

**Issue by user202729** [latex3/latex3#1073]
Example code:

```latex
\ExplSyntaxOn
\tl_analysis_map_inline:nn {ab} {
	\tl_analysis_map_inline:nn {cd} {
		\wlog {XX #1 ##1}
	}
}
\ExplSyntaxOff
```

Logged `ac ad ab`, while expected content should be `ac ad bc bd`.

The problem here is that the macro `\__tl_analysis_map_inline_aux:nnn` is reused across all recursion levels:

https://github.com/latex3/latex3/blob/517080e23de88204b7752ac1381c676407969eb7/l3kernel/l3tl-analysis.dtx#L963-L972

(while the looping macro is correctly numbered: `\__tl_analysis_map_inline_1:wNw`, etc.)

**Comment by blefloch** [comment]
Yes, thanks, this is done completely the wrong way around, sorry.  I didn't track precisely why you get that particular result, but I see how to fix it.

**Comment by blefloch** [comment]
Bug introduced in 4ac171b1f7cb0a9e0f843941c95784d0d7e0e3b0 when the functions were made public.  There are no comments on why the indirection to `\@@_analysis_map_inline_aux:nnn` was added, but I suppose this is to prevent the code `\use_none:n ##2` (which breaks away from the mapping) from being confused by the user-provided code.  This can be solved differently, more safely.  Fix (and tests) incoming.
