### ISSUE TITLE
Feature request: Expose more internal tl-hack commands

### ISSUE THREAD

**Issue by user202729** [latex3/latex3#1076]
As far as I can see (reading source3), there are some functionalities hidden within the `\__tl_peek_analysis*` functions that are not exposed.

Sure, these are not used very frequently, but I think *it's highly nontrivial to do such things if you don't know how to* which is a good enough reason to expose them.:

* `\peek_space:TF` : similar to `\tl_if_head_is_space`, but test for the next token and return true *only if* it's explicit space token. (peek_catcode also return true on implicit space token)
* `\peek_group:TF`: (similar to `\tl_if_head_is_group`) test if next character is explicit {-category.
* `peek_group_end:TF`: test if next character is explicit }-category.
* `peek_N_type_exact:TF`: test if next character is none of the above.

Reason: 

* grabbing the whole next argument as tl is inefficient/impossible (the tests above are in constant time),
* you have to `\peek_analysis_inline`, but this one
   * is overly generic and most likely slower, and
   * removes the token and putting it back is somewhat nontrivial. (maybe `\expandafter \whattodonext #1` because `#1` o-expand to the token?)

Also

* expose `\__tl_analysis` to store the analyzed items into another token list (e.g. `\tl_analysis_set:Nn \target {... tokens...}`. It's not necessary to expose the internal \__s_tl tokens, store as list of {{1} {2} {3}}is good enough) (reason: map through and *transform* (assume the transformation is x-expandable) tokens of a token list in linear time. As far as I can see even `\tl_build_*` functions take quadratic time, just "divide by 4" because it only append to large token list 1/4 of the time?)

Also maybe also provide these (regex replacement already use them internally)

* set a TL to contain an active character (currently can char_generate and have to control expansion to expand exactly twice i.e. `\exp_args:NNo \tl_set:No \something {\char_generate:nn {} {}}`)
* set a TL to contain a space (currently char_generate does not support)
* set a TL to contain brace hack (i.e. `\iftrue { \else } \fi`, sort of, but with `{` or `}` have provided charcode) (I'd think `\char_generate_set:Nnn \target {charcode} {catcode}`)

**Comment by josephwright** [comment]
These could well be doable using the more general peek functions, so unless there is a need for high-speed working, we are better adding examples to the documentation. Depends on whether it can only be done using a `regex` peek or not.

**Comment by user202729** [comment]
In retrospect -- peek is inherently difficult, the "general" one is actually the only one you have, so it it's okay to use it as building block I think.

It would still help to have them in the documentation to e.g. give the "official recommendation" on how to do the task.

**Comment by josephwright** [comment]
I'm not sure this fits into the scope of `interface3`: it's more of a 'tricks using ...' idea. I think the general idea of `\peek_regex:n(TF)` is pretty clear.

**Comment by Skillmon** [comment]
@josephwright if it's about speed, `\peek_regex:n(TF)` is out of question...

**Comment by user202729** [comment]
Realistically, I think back when I made this feature request the actual reason is I don't know how to actually do the tasks specified...

A (self-contained) "programming in TeX and expl3" guide would be nice, but writing such a thing would take much effort.

**Comment by josephwright** [comment]
> @josephwright if it's about speed, `\peek_regex:n(TF)` is out of question...

Sure but we'd need a real use case to judge that

**Comment by josephwright** [comment]
> Realistically, I think back when I made this feature request the actual reason is I don't know how to actually do the tasks specified...
> 
> A (self-contained) "programming in TeX and expl3" guide would be nice, but writing such a thing would take much effort.

Hassle Enrico :)
