### ISSUE TITLE
Feature request \c_global_cctab

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex3#1082]
The `\c_document_cctab` is defined by l3kernel and does not consider for example babel actions.
A `\c_global_cctab` would correspond to the real table in use at the beginning of the document, once all the packages have performed their own settings. This allows to rescan tokens with the real document cctab. This is certainly possible with LuaTeX.

**Comment by josephwright** [comment]
I'd welcome the views of the rest of the team: I'd say this is 'by design' as what we really want is a predictable set of catcodes which don't change.

**Comment by jlaurens** [comment]
This is meaningful. I close this and forwards the feature to #1089
