### ISSUE TITLE
Documentation: mentions the law \tex_lowercase:D primitive in char generation part?

### ISSUE THREAD

**Issue by user202729** [latex3/latex3#1083]
\regex_replace_all is mentioned in char_generate documentation, but there are cases where it is not sufficient (what if the user want to generate a spacer/left brace/right brace/active char with a char code given in a variable)?

Using char_generate would be inconvenient (for braces: need elaborate brace hacks, for active character: need to control exact number of expansions)/impossible (for space...  actually this one is fixed recently in #(don'tcrosslink)1075).

**Comment by blefloch** [comment]
It would be useful to have a more concrete example of what you are trying to achieve and what extra feature we should provide to support your use case.  I don't think promoting `\tex_lowercase:D` is a good idea: `:D` means "do not use", after all.

**Comment by user202729** [comment]
For example in case I want to execute `\tl_set:Nn \__a { \iffalse { \else } \fi }` where the inner `}` has the char code stored somewhere e.g. `#1`.

As far as I can see the l3regex source code also use \lowercase to generate those characters?

![image](https://user-images.githubusercontent.com/25191436/162611145-04a3d024-54f4-45f9-a38d-3192c1c765ef.png)


I guess it's possible to do it by carefully controlling char_generate and brace-hack the definition as well, but it seems more messy.

**Comment by FrankMittelbach** [comment]
The fact that at the very lowest level of the expl3 code constructs like that are used  because they are necessary to provide higher-level abstractions doesn't mean that they are models for code to be used elsewhere. The whole point of expl3 is that people do not need to use such tricks. If they do that either means there is still higher-level support missing in one or the other case or people are still too much used to think in the programming structures of plain TeX.

**Comment by user202729** [comment]
It's true that it's impossible to build a tool with itself, but then I don't see the API exposed by regex being able of the thing I mentioned above either.

Anyway, in summary it would be nice if someone can do something to allow people using expl3 to do the task mentioned above

**Comment by davidcarlisle** [comment]
@user202729  

> For example in case I want to execute \tl_set:Nn \__a { \iffalse { \else } \fi } where the inner } has the char code stored somewhere e.g. #1.

to generate a `}` of a specified catcode you just need `\char_generate:nn` you can not change the catcode of `}` in `\iffalse { \else } \fi ` without changing `{` as well or the token list would not have balanced braces.

so it seems your requiement is `.... \tl_set:Nx \__a {\char_generate:nn{125}{#1}}....`

**Comment by user202729** [comment]
Okay, in retrospect the work could be done with something like...

```
\tl_set:Nx \__a {
	\noexpand \iffalse
		\char_generate:nn {65} {1}
	\noexpand \else
		\char_generate:nn {66} {2}
	\noexpand \fi
}
```

(replace noexpand etc. with exp_not:N if necessary)

It wasn't quite obvious looking at the documentation though. I'll see what could be done.

**Comment by Skillmon** [comment]
@user202729 note that your brace hack isn't well designed, better would be `\if_false: { \fi: }` and `\exp_after:wN { \if_false: } \fi:`. You're version doesn't `o`-expand to a single brace but has a trailing `\fi`.
