### ISSUE TITLE
LaTeX3 Error: Control sequence \CJKaddEncHook already defined. \csname

### ISSUE THREAD

**Issue by PerfectZyx** [latex3/latex3#1084]
Can anyone help with this problem?

  \edef\CJK@UnicodeEnc{UTF8}
  \def\CJKaddEncHook#1#2{\expandafter\def\csname xeCJK@enc@#1\endcsname{#2}}
  \def\Unicode#1#2{\@tempcnta#1\relax
    \multiply\@tempcnta 256\relax
    \advance\@tempcnta#2\relax
    \char\@tempcnta}
  \RequirePackage{CJKnumb}
  \csname xeCJK@enc@UTF8\endcsname

**Comment by PhelypeOleinik** [comment]
If I run the code you posted, I get no errors, but it's only a partial code, so I presume the error is in some code you didn't show.

Anyway, this code is not related to latex3, so you should ask/report that somewhere else.

I suggest you ask a question on https://tex.stackexchange.com with a compilable example that shows the problem.

**Comment by PerfectZyx** [comment]
> If I run the code you posted, I get no errors, but it's only a partial code, so I presume the error is in some code you didn't show.
> 
> Anyway, this code is not related to latex3, so you should ask/report that somewhere else.
> 
> I suggest you ask a question on https://tex.stackexchange.com with a compilable example that shows the problem.

Thanks for your reply. 
Since I could run it in the previous version, I thought this was the error that was triggered.

**Comment by PhelypeOleinik** [comment]
@PerfectZyx The error is reported as "LaTeX3 error" because somewhere in a package, it does `\cs_new_protected:Npn \CJKaddEncHook`, and that errors because that command already exists.  It doesn't mean it's an error _in_ LaTeX3.

**Comment by PerfectZyx** [comment]
> @PerfectZyx The error is reported as "LaTeX3 error" because somewhere in a package, it does `\cs_new_protected:Npn \CJKaddEncHook`, and that errors because that command already exists. It doesn't mean it's an error _in_ LaTeX3.

Okay, I understand, thank you very much.
