### ISSUE TITLE
Can't compile using arabtex on macos arm

### ISSUE THREAD

**Issue by ringstellung** [latex3/latex3#1086]
I have been a LaTeX user since its beginnings and among other packages
I have used Arabtex since its first release; in fact today it is
essential in my work. A few days ago I installed Mactex 2022
version under macOS ARM and found that I cannot compile any of the
files involving Arabtex, not even the sample files of the package.

In order to show the problem I have edited the small file named
`arabtex_problem.tex` which simply writes the letters of the arabic
alphabet and the corresponding transcription. When running from the
terminal the command

```
$ pdflatex arabtex_example.tex
```

the following error is displayed:

```
(/usr/local/texlive/2022/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def
! Undefined control sequence.
\a@ins ...et \a@less < \else \global \let \a@less 
                                                  \a@insert \leavevmode \bg...
l.168 <
               < ~
?
```

included in the file `arabtex_example.log` that I provide you with. The message:

```
\gdefnext { "a@puttt" \leavevmode" \arab@tail }
```

also appears inside the file `arabtex_example.err` that I also
provide.

In addition I provide the file `arabtex_example.pdf` which should be the result
of the the compilation, which has resulted when compiling with the
installation of Tex Live 2020 under Linux. I don't know if MacTex 2021
would work fine under my macOS ARM.

Everything leads me to conjecture that the error could be in the
`l3backend` package (updated now at the time of writing this). Possibly
the edition of `l3backend` has ignored essential features of the `arabtex`
package that would be indispensable for the compilation of `.tex` files
involving it.

I'm not a expert on how the latex repositories works but if this is not the right
place to create this issue I would be grateful if you could point me to the correct
place.

My thanks in advance for your work and effort

[arabtex_example.zip](https://github.com/latex3/latex3/files/8495505/arabtex_example.zip)
[arabtex_example.pdf](https://github.com/latex3/latex3/files/8495511/arabtex_example.pdf)

Setup:
- system: `macOS 12.3.1 arm`
- pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022)
- arabtex is the package with the issue

**Comment by u-fischer** [comment]
Sorry but this is the wrong place to report problems with arabtex. We are not maintaining it. 

Move `\setarab\arabtrue` behind `\begin{document}`. The command setups lots of stuff for arabic.  Beside other it changes the catcode of `<` to active, and this breaks various code in `\begin{document}` expecting to be able to use it to compare numbers.

**Comment by ringstellung** [comment]
Thank you so much, this has really help me a lot. I was not aware where was the correct place for this. We can close this issue if is not needed.
