### ISSUE TITLE
Feature request: \tl_head/tail_keep_spaces:n/N

### ISSUE THREAD

**Issue by user202729** [latex3/latex3#1092]
As mentioned in the title. These would behave identically to \tl_head/tail, except that if the head is space, \tl_head_keep_spaces returns the space and \tl_tail_keep_spaces returns the remaining content except the space.

(any objection if I implement these and make a PR? For example, could the function name be better? Currently it's consistent with e.g. \seq_split_keep_spaces)

**Comment by josephwright** [comment]
What's the use case here? Seems more likely you'd use `\tl_if_head_is_space:n(TF)` then branch accordingly.

**Comment by user202729** [comment]
After branching you need to "discard the first space and process the rest", right?

**Comment by Skillmon** [comment]
```
\exp_last_unbraced:NNo \cs_new:Npn \__user_gobble_space:w \c_space_tl {}
\cs_new:Npn \user_tl_head_keep_space:n #1
  { \tl_if_head_is_space:nTF {#1} {~} { \tl_head:n {#1} } }
\cs_new:Npn \user_tl_tail_keep_space:n #1
  {
    \tl_if_head_is_space:nTF {#1}
      { \exp_not:o { \__user_gobble_space:w #1 } }
      { \tl_tail:n {#1} }
  }
```
 doesn't seem to hard...

**Comment by user202729** [comment]
Well the point is... it isn't hard once you already know how to do it, but same thing can be said about \tl_head and \tl_tail themselves, right?

(*) if you ignore align-safety and cases such as the tail is braced group etc.

**Comment by Skillmon** [comment]
Well, `\tl_head:n` is actually not so easy (especially the implementation if `\tex_expanded:D` isn't available), but with the building blocks `\tl_head:n`, `\tl_tail:n` and `\tl_if_head_is_space:nTF` the rest is just sticking pieces together, the only part requiring a bit of knowledge is the space gobbler and `\user_tl_tail_keep_space:n`, but if you're coding in TeX for a bit this shouldn't be too far fetched either.

**Comment by user202729** [comment]
Well I still think that this is common enough to add a function. (alternatively do just `\tl_drop_first_space:n` which drops the first space, and error out if it doesn't start with the space i.e. wraps the space gobbler into a function.)

**Comment by josephwright** [comment]
> Well I still think that this is common enough to add a function. (alternatively do just `\tl_drop_first_space:n` which drops the first space, and error out if it doesn't start with the space i.e. wraps the space gobbler into a function.)

As I said earlier, I think a use case would be handy: I can't think of ever needed anything like this.

**Comment by user202729** [comment]
Wouldn't any "tree-style procedural" processing that requires preserving spaces need it?

Example https://tex.stackexchange.com/a/516931/250119  (the answer there uses a similar "space gobbler"; although instead of recursion the user could choose to write it a "procedural" way which is I think slightly more understandable. Although in that particular case map-analysis might be the fastest)

**Comment by josephwright** [comment]
@user202729  But that's the test-and-branch idea: what we usually call an 'tl action' (at one point there was a generic loop for that - it didn't really work). If you need to _know_ if there is an N-type token, a group or a space, making that clear is normally required.

**Comment by user202729** [comment]
I know, but I mean... for example if you manipulate it expandably, store the token list into X, then after you already determined X starts with a space, you want to do

* process the space
* store X ← \tl_drop_first_space:n {X} (roughly speaking) which is this operation.

**Comment by Skillmon** [comment]
@user202729 `\__etl_rm_space:w` is identically defined to the above's `\__user_gobble_space:w` (though in its setup I use a faster construct for the definition than the one above), so yes, this is `\etl_act_put_back:n` with one space removed from the start of `#1`.

**Comment by josephwright** [comment]
For the present we will document as example how this can be done - still feels rather specialised.
