### ISSUE TITLE
miktex-pdftex.exe did not succeed

### ISSUE THREAD

**Issue by dovfields** [latex3/latex3#1094]
I installed MikTex using the installer and updated all of the packages. I then tried to compile a simple test file:
"\documentclass{article}
\begin{document}
test
\end{document}"

When I do this, I get the error 
"Sorry, but C:\Users\dovfi\AppData\Local\Programs\MiKTeX\miktex\bin\x64\miktex-pdftex.exe did not succeed"

I'm attaching a zip file with all of the log files, which will hopefully help in figuring out the issue. 
[log.zip](https://github.com/latex3/latex3/files/8738997/log.zip)

**Comment by PhelypeOleinik** [comment]
The log file in `makefmt/latex` in the zip file you send contains:
```none
! LaTeX3 Error: File 'UnicodeData.txt' not found.

For immediate help type H <return>.
 ...                                              
                                                  
l.31675   }
```
which means you don't have `unicode-data` installed.  Search for `unicode-data` in the MiKTeX package manager, install it, then try again.

**Comment by u-fischer** [comment]
> which means you don't have unicode-data installed. 

The error message pops up from time to time even if unicode-data is installed. There are some issues about it in the miktex tracker.  It is unclear what happens exactly, it could be that some virus protection blocks the file. Reinstalling the unicode-data package can help. In any case it is a miktex issue and nothing that can be resolved here.
