### ISSUE TITLE
osf libertine lining figures off baseline This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022/Arch Linux) 

### ISSUE THREAD

**Issue by nonumeros** [latex3/latex3#1096]
I've got a simple document

```
\documentclass{article}
\usepackage[osf]{libertine}
\begin{document}
\input cervantes-es

es cierto 124098459

una prueba 345544543543

\end{document}
``` 

Lining figures appear completely thrown off the baseline. If I were to have `\oldstylenums{}` or `oldstylenumsf{}` then it seemed as if the layout normalized for a second. But there's still an issue, which I can't figure out yet. 

on this particular system,the output is nevertheless, more satisfactory compared to its counterpart .

Since l3backend is the new standard I thought of opening the issue here.

this is the log 

```
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022/Arch Linux) (preloaded format=latex 2022.5.26)  26 MAY 2022 16:39
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**/test1.tex
(/test1.tex
LaTeX2e <2021-11-15> patch level 1
L3 programming layer <2022-04-10>
(/usr/share/texmf-dist/tex/latex/base/article.cls
Document Class: article 2021/10/04 v1.4n Standard LaTeX document class
(/usr/share/texmf-dist/tex/latex/base/size10.clo
File: size10.clo 2021/10/04 v1.4n Standard LaTeX file (size option)
)
\c@part=\count185
\c@section=\count186
\c@subsection=\count187
\c@subsubsection=\count188
\c@paragraph=\count189
\c@subparagraph=\count190
\c@figure=\count191
\c@table=\count192
\abovecaptionskip=\skip47
\belowcaptionskip=\skip48
\bibindent=\dimen138
)
(/usr/share/texmf-dist/tex/latex/libertine/libertine.sty
Package: libertine 2020/03/26 (Bob Tennent) Supports Libertine and Biolinum fon
ts for all LaTeX engines.

(/usr/share/texmf-dist/tex/generic/iftex/ifxetex.sty
Package: ifxetex 2019/10/25 v0.7 ifxetex legacy package. Use iftex instead.

(/usr/share/texmf-dist/tex/generic/iftex/iftex.sty
Package: iftex 2022/02/03 v1.0f TeX engine tests
))
(/usr/share/texmf-dist/tex/generic/iftex/ifluatex.sty
Package: ifluatex 2019/10/25 v1.5 ifluatex legacy package. Use iftex instead.
)
(/usr/share/texmf-dist/tex/latex/xkeyval/xkeyval.sty
Package: xkeyval 2020/11/20 v2.8 package option processing (HA)

(/usr/share/texmf-dist/tex/generic/xkeyval/xkeyval.tex
(/usr/share/texmf-dist/tex/generic/xkeyval/xkvutils.tex
\XKV@toks=\toks16
\XKV@tempa@toks=\toks17

(/usr/share/texmf-dist/tex/generic/xkeyval/keyval.tex))
\XKV@depth=\count193
File: xkeyval.tex 2014/12/03 v2.7a key=value parser (HA)
))
(/usr/share/texmf-dist/tex/latex/base/textcomp.sty
Package: textcomp 2020/02/02 v2.0n Standard LaTeX package
)
(/usr/share/texmf-dist/tex/latex/base/fontenc.sty
Package: fontenc 2021/04/29 v2.0v Standard LaTeX package
)
(/usr/share/texmf-dist/tex/latex/fontaxes/fontaxes.sty
Package: fontaxes 2020/07/21 v1.0e Font selection axes
LaTeX Info: Redefining \upshape on input line 29.
LaTeX Info: Redefining \itshape on input line 31.
LaTeX Info: Redefining \slshape on input line 33.
LaTeX Info: Redefining \swshape on input line 35.
LaTeX Info: Redefining \scshape on input line 37.
LaTeX Info: Redefining \sscshape on input line 39.
LaTeX Info: Redefining \ulcshape on input line 41.
LaTeX Info: Redefining \textsw on input line 47.
LaTeX Info: Redefining \textssc on input line 48.
LaTeX Info: Redefining \textulc on input line 49.
)
LaTeX Info: Redefining \oldstylenums on input line 484.

(/usr/share/texmf-dist/tex/latex/libertine/LinLibertine_I.tex))
LaTeX Font Info:    Trying to load font information for OT1+LinuxLibertineT-TOs
F on input line 6.

(/usr/share/texmf-dist/tex/latex/libertine/OT1LinuxLibertineT-TOsF.fd
File: OT1LinuxLibertineT-TOsF.fd 2017/03/20 (autoinst) Font definitions for OT1
/LinuxLibertineT-TOsF.
)
LaTeX Font Info:    Font shape `OT1/LinuxLibertineT-TOsF/m/n' will be
(Font)              scaled to size 10.0pt on input line 6.

(/usr/share/texmf-dist/tex/latex/l3backend/l3backend-dvips.def
File: l3backend-dvips.def 2022-04-14 L3 backend support: dvips
\l__pdf_internal_box=\box50
\g__pdf_backend_object_int=\count194
\l__pdf_backend_content_box=\box51
\l__pdf_backend_model_box=\box52
\g__pdf_backend_annotation_int=\count195
\g__pdf_backend_link_int=\count196
\g__pdf_backend_link_sf_int=\count197
) (./test1.aux)
\openout1 = `test1.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 6.
LaTeX Font Info:    ... okay on input line 6.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 6.
LaTeX Font Info:    ... okay on input line 6.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 6.
LaTeX Font Info:    ... okay on input line 6.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 6.
LaTeX Font Info:    ... okay on input line 6.
LaTeX Font Info:    Checking defaults for TS1/cmr/m/n on input line 6.
LaTeX Font Info:    ... okay on input line 6.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 6.
LaTeX Font Info:    ... okay on input line 6.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 6.
LaTeX Font Info:    ... okay on input line 6.
\c@mv@tabular=\count198
\c@mv@boldtabular=\count199

(/usr/share/texmf-dist/tex/context/sample/third/cervantes-es.tex) [1

]
(./test1.aux) ) 
Here is how much of TeX's memory you used:
 1945 strings out of 478239
 38133 string characters out of 5850482
 317376 words of memory out of 5000000
 20217 multiletter control sequences out of 15000+600000
 470638 words of font info for 29 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 8191
 55i,5n,62p,191b,117s stack positions out of 5000i,500n,10000p,200000b,80000s

Output written on test1.dvi (1 page, 940 bytes).

```
![Screenshot_2022-05-26_17-06-17](https://user-images.githubusercontent.com/11535575/170584601-17c7dcca-09b6-41db-9ea3-b62d326845cf.png)

**Comment by u-fischer** [comment]
issues with libertine have nothing to do with latex3. Beside this: `[osf]`  selects old style numbers. If you want lining numbers remove this option.

**Comment by nonumeros** [comment]
How do you explain this then. What you eloquently put in one sentence, has to be one the stupidest answers you have formulated in your lifetime. Never mind

```
\documentclass{article}
\usepackage[osf]{libertine}
\begin{document}
\input cervantes-es

es cierto 124098459

una prueba 345544543543

24545435435432
\end{document}
```
![Screenshot_2022-05-26_17-30-56](https://user-images.githubusercontent.com/11535575/170587641-5c92272f-0333-4f7f-92c4-d829b896eaac.png)

**Comment by Skillmon** [comment]
And now look at this (with the `[osf]` option removed):

```tex
\documentclass{article}
\usepackage{libertine}
\begin{document}
\input cervantes-es

es cierto 124098459

una prueba 345544543543

24545435435432
\end{document}
```

![articlelibertine-1](https://user-images.githubusercontent.com/8701017/170588500-49bf326a-b514-4710-aef4-39b57fa29d19.png)


I suggest you  be more polite to people spending their free time to help you. What @u-fischer was saying is that you're not using lining figures, but old-style figures through the `osf` option of `libertine` and hence don't get lining figures.

**Comment by nonumeros** [comment]
>I suggest you be more polite to people spending their free time to help you.

How is that silly entitled stupid answer is going to help with the document.

No. I don't need to be more polite. 

But never mind. You're right. :)  Thank you. I think I may have forgot that lining figures are default.

**Comment by nonumeros** [comment]
In all fairness to @u-fischer  she can have lucid episodes every now and then. 

On tex.sx though, you'll find users such as cfr that makes you wonder about common sense. 

I tell you. One day I saw her going at it back and forth with David. And from a distance, you wouldn't know, who the stupid was. Of course, David is brilliant. But sheer stupidity prevents you from any further critical thinking.

**Comment by PhelypeOleinik** [comment]
> No. I don't need to be more polite.

Yes, you do, as much as you need critical thinking: this is an issue tracker, not a venting forum to roast people you don't like. Use it as it's meant to be used, or take your absurd lack of manners somewhere else.

**Comment by nonumeros** [comment]
@PhelypeOleinik who said I don't like @u-fischer  

I posted an issue. She closed it immediately. There's not a valid reason for either closing it or for giving a half-ass explanation. And brushing it off as always.

If I have an absurd lack of manners, you want to shove everything under the rag. 

This is just a continuation. It happened at tex.sx once when @josephwright  was a moderator there. Even though this particular user is someone who likes to stir up shit for no given  reason. So was that acceptable?

**Comment by nonumeros** [comment]
How about if I give some more details?

This particular user cfr or whatever, her name is, got really, really, really offended because I used the word «dear» as a matter of affection or friendly demeanor at the time of addressing the individual in writing.

Then she went at it, and said that the word «dear» was totally inappropriate and condescending and blah blah blah and on and on she went.

Then after reading all her fucking nonsense, I told her and rightly so:  «take off your bra elsewhere» since there was no need to stir up that kind of shit in the first place. 

Everything I had written prior and after, was deleted. 

There was no need to stir up that shit in the first place. But this user is known for that. And that's apparently acceptable.

But thank you all.
