### ISSUE TITLE
l3graphics: Increasing file size when using package functions

### ISSUE THREAD

**Issue by sergiokapone** [latex3/latex3#1098]
Noticed an interesting feature/bug. If you use the function `graphics_get_pagecount:nN` from `l3graphics` to determine the number of pages in an included file, the compiled resulting file grows in size. It would seem that this should not affect the compiled file size at all, since the compiled file is the same in content (typesetting) with or without enabling this feature.

The problem manifests itself significantly if the number of included files is large. 

For example, in my  case, my file is formed from 92 separate PDFs. When you turn on the page count function in the included files (and upload to a text file `pagecount.txt`), the compiled file differs by 4 MB. Why is that? What other information is written in the PDF?

```
    \documentclass{book}
    \usepackage{pdfpages}
    \usepackage{l3graphics}
    
    \ExplSyntaxOn
        \iow_new:N \l_my_pages_iow
        \iow_open:Nn \l_my_pages_iow { pagecount.txt }
    \AtEndDocument { \ior_close:N \l_my_pages_iow }
    \NewDocumentCommand { \countpages }{  m  }{
        \graphics_get_pagecount:nN {  #1  }  \l_total_pages_tl
        \iow_now:Nx  \l_my_pages_iow  { \l_total_pages_tl }
    }
    \ExplSyntaxOff
    
    \begin{document}
    
    \countpages{icluded.pdf} % <- when disabled, the file size is reduced
    \includepdf[pages=-, link]{icluded.pdf}
    
    
    \end{document}
```

**Comment by josephwright** [comment]
Yes all true. The way that pages are counted is engine-dependent, but in pdfTeX we use an XObject. I did toy with the idea of trying to avoid loading the PDF twice _if_ the file is also used as an image. However, that is not at all trivial: the image settings might for example want to alter the bounding box, and we will then need two XObjects. We also can't use the same trick for other backends. So on balance I decided against it: we use one XObject for page counting and a separate one for image inclusion.

Note also that `pdfpages` will do it's own thing regardless, so that is unaffected by the above.

**Comment by josephwright** [comment]
I guess I should document this.

**Comment by sergiokapone** [comment]
Thanks for the answer.  That is, it does not affect the final layout, it just annoyingly increases the volume of the resulting file, nothing more. Well, one can deal with that.

**Comment by u-fischer** [comment]
What happens if you move your `\countpage` command behind the `\includepdf`'s?

**Comment by josephwright** [comment]
@u-fischer  Shouldn't make any difference: `pdfpages` is using `pdftex.def` in the end, and that is making separate `XObjects`.

**Comment by josephwright** [comment]
I can look again at whether an optimisation is possible, but I'm wary.

**Comment by josephwright** [comment]
We can try not using `\immediate` here to see if that helps, otherwise it will be documentation-only.

**Comment by zauguin** [comment]
This has been fixed by removing the `\immediate`.
