### ISSUE TITLE
l3keys: Add 'post-actions'

### ISSUE THREAD

**Issue by josephwright** [latex3/latex3#1099]
For example to issue a message after setting a key, it would be useful to have an independent post-action property.

**Comment by josephwright** [comment]
One could do this by simply augmenting the code, which would then require it was given _after_ key creation. Or one could use a separate data store - more tricky and leads to the question of what happens if (e.g.) `.post_action:n` is given without the key actually being 'created'.

One could also all this something like `.code_put_right:n` (similar to `pgfkeys` but using `expl3` names), but I'd rather we were pushing for a real 'post action' feeling. So something like `.post_action:n` or simply `.after:n` might work.

**Comment by josephwright** [comment]
@u-fischer, @davidcarlisle, @Skillmon Your thoughts here would be welcome

**Comment by lnzspraj** [comment]
Is a symmetric `.before:n` also needed (I can't think of any use case in which a `.before:n` would be more useful than an `.after:n`)?

Separate data store doesn't sound too bad (`.after:n` behaving similar to properties like `.value_required:n`). I'd say that `\keys_set:nn` should simply do a `\cs_if_exist:cT { <after-property-prefix> <set>/<key> } { \cs:w <after-property-prefix> <set>/<key> \cs:end { <value> } }` after the key-code invocation (but inside the true branch of the key-existance test).

**Comment by FrankMittelbach** [comment]
> Is a symmetric `.before:n` also needed (I can't think of any use case in which a `.before:n` would be more useful than an `.after:n`)?

I wouldn't go for that just because of symetrical reasons. There should be compelling use cases (not artifically constructed ones) imo

**Comment by u-fischer** [comment]
> Is a symmetric `.before:n` also needed (I can't think of any use case in which a `.before:n` would be more useful than an `.after:n`)?

I wouldn't do it either. My main incentive here was to be able to add some log-message or debug message to a bool or store key (as hyperref has these messages and I don't want to drop them all when converting or to have to use `.code` everywhere).  But imho more complicated setups should be done with `.code:n`

**Comment by lnzspraj** [comment]
The `.before:n` was really just of academical nature, I'd not add it, too.

What I could also imagine instead of an `.after:n` is a `.verbose:n = <int>` property that results in log-level (>0) or terminal-level (>1) messages each time the key is used. That would cover @u-fischer's use case and is maybe more reasonable than a way to add code to a key without the code being part of the key (what `.after:n` would be). Or go for the `.code_put_right:n` solution.

**Comment by josephwright** [comment]
My reason for suggesting storing as 'internal structure' in the general code, rather than using a dedicated store, is that although `\cs_if_exist:cTF` is fast, it's going to hit ever key. In contrast, doing `<normal code> \__marker:n { post-code }` will only impact where it is used and will therefore be low cost.

**Comment by josephwright** [comment]
We could of course go for a more focussed property, such as `.log:n`, which could be implemented internally as  a post-action but which would only do one job.

**Comment by josephwright** [comment]
Just realised we already have this logged as https://github.com/latex3/latex3/issues/505 more or less - I'll close here and we can continue there ...
