### ISSUE TITLE
\peek_analysis_map_inline does not work for \exp_after:wN token

### ISSUE THREAD

**Issue by user202729** [latex3/latex3#1110]
```
%! TEX program = pdftex
\input expl3-generic.tex
\ExplSyntaxOn
\peek_analysis_map_inline:n {
	\peek_analysis_map_break:
} \exp_after:wN
\bye
```

```
! Improper alphabetic constant.
<to be read again> 
                   \exp_after:wN 
l.6 } \exp_after:wN
                   
? 
```

Looks like the cause here is `\tex_let:D #1 \scan_stop:` which will obviously break the code afterwards. (I think other tokens such as `\tl_put_right:Nn`, `\exp_not:N`,  etc. will break this code as well.)

**Comment by blefloch** [comment]
Thanks a lot for the three issues (#1109, #1110, #1113)!  That was ridiculously bad code on my part, and poor testing.  I've corrected all three, but don't hesitate to open others if you come across more.  I'm also open to more tests in this area if want to contribute in this way.
