### ISSUE TITLE
[Request] Global \NewDocumentCommand

### ISSUE THREAD

**Issue by antshar** [latex3/latex3#1116]
I've been looking for `\gdef` alternative in `xparse`, but apparently such command is missing, but I found this simple yet beautiful implementation that provides global alternatives for `\RenewDocumentCommand`, `\ProvideDocumentCommand`, etc. simultaneously:

https://tex.stackexchange.com/a/396750/213149

Can it be added to `xparse` package to ship `\GNewDocumentCommand` with it?

**Comment by josephwright** [comment]
This is a design decision: document commands are expected to be created in global scope.
