### ISSUE TITLE
[Bug] Cyrillic letters has been messed up

### ISSUE THREAD

**Issue by antshar** [latex3/latex3#1119]
After this TeX.SE [question](https://tex.stackexchange.com/q/652860/213149), @davidcarlisle helped me to figure out the issue that had happened to cyrillic letters recently. In newest build of LaTeX (namely TeXLive 2022) instead of `\cyrzh` for instance, it's now `ж`. 

So that if you're using non-unicode engines (like `pdflatex`), cyrilic letters cannot be treated normally anymore. Besides described issue in the TeX.SE question, it also makes impossible to use regex's `\w` operator for matching letters.

Can we revert that bizarre change to how it used to be in older versions (`\cyryo` instead of `ё` etc)?

**Comment by josephwright** [comment]
As @davidcarlisle has explained in comments on the linked TeX-sx question, the `tl` functions were never intended to handle 'characters' in 8-bit engines: they are based on TeX tokens. As such, they are unsuitable for mapping to non-ASCII text with 8-bit engines. At the same time, `x`-type expansion of arbitrary user input has never been supported by LaTeX2e. The fact that the previous definitions for Cyrillic with an 8-bit engine gave something usable is accidental.

There has been no change in the `expl3` code. What has changed is the approach used by LaTeX2e for UTF-8 handling with 8-bit engines. The new definition makes the bytes `\protected`, so they are safe inside `x`-type expansion, meaning that it is much _easier_ to work with UTF-8 input and 8-bit engines in general. (As mentioned in comments on the linked question, things like file names and labels need them to remain unchanged: whilst we had a way to do that without `\protected`, it required careful handling and the new approach is therefore much more 'scalable'.)

The team have previously discussed a set of mapping functions aimed at 'text'. We will explore whether this is a viable longer-term approach: there are questions about the nature of the mapping when involving e.g. combining characters.

**Comment by josephwright** [comment]
A possible approach to a text mapping:
```latex
\cs_new:Npn \text_map_function:nN #1#2
  { \exp_args:Ne \__text_map_function:nN { \text_expand:n {#1} } #2 }
\cs_new:Npn \__text_map_function:nN #1#2
  {
    \__text_map_function:Nw #2 #1
      \q__text_recursion_tail \q__text_recursion_stop
    \prg_break_point:Nn \text_map_break: { }
  }
\bool_lazy_or:nnTF
  { \sys_if_engine_luatex_p: }
  { \sys_if_engine_xetex_p: }
  {
    \cs_new:Npn \__text_map_function:Nw #1#2
      {
        \__text_if_recursion_tail_stop_do:Nn #2 { \text_map_break: }
        #1 {#2}
        \__text_map_function:Nw #1
      }
  }
  {
    \cs_new:Npn \__text_map_function:Nw #1#2
      {
        \__text_if_recursion_tail_stop_do:Nn #2 { \text_map_break: }
        \bool_lazy_and:nnTF
          { \tl_if_single_token_p:n {#2} }
          { ! \token_if_cs_p:N #2 }
          {
            \int_compare:nNnTF { `#2 } > { "80 }
              {
                \int_compare:nNnTF { `#2 } < { "E0 }
                  { \__text_map_function:NNN }
                  {
                     \int_compare:nNnTF { `#2 } < { "F0 }
                       { \__text_map_function:NNNN }
                       { \__text_map_function:NNNNN }
                  }
              }
              { \__text_map_function:Nn }
                #1 #2
          }
          { \__text_map_function:Nn #1 {#2} }
      }
    \cs_new:Npn \__text_map_function:NNN #1#2#3
      { \__text_map_function:Nn #1 {#2#3} }
    \cs_new:Npn \__text_map_function:NNNN #1#2#3#4
      { \__text_map_function:Nn #1 {#2#3#4} }
    \cs_new:Npn \__text_map_function:NNNNN #1#2#3#4#5
      { \__text_map_function:Nn #1 {#2#3#4#5} }
    \cs_new:Npn \__text_map_function:Nn #1#2
      {
        #1 {#2}
        \__text_map_function:Nw #1
      }
  }
\cs_new:Npn \text_map_break:
  { \prg_map_break:Nn \text_map_break: { } }
\cs_new:Npn \text_map_break:n
  { \prg_map_break:Nn \text_map_break: }
\cs_new_protected:Npn \text_map_inline:nn #1#2
  {
    \int_gincr:N \g__kernel_prg_map_int
    \cs_gset_protected:cpn
      { __text_map_ \int_use:N \g__kernel_prg_map_int :w } ##1 {#2}
    \exp_args:Nnc \text_map_function:nN {#1}
      { __text_map_ \int_use:N \g__kernel_prg_map_int :w }
    \prg_break_point:Nn \text_map_break:
      { \int_gdecr:N \g__kernel_prg_map_int }
  }
```
