### ISSUE TITLE
(feature request) Consider adding a file-write command?

### ISSUE THREAD

**Issue by user202729** [latex3/latex3#1121]
Currently we have ior_* functions and iow_* functions to read from and write to file respectively, but that wastes a TeX file register each.

It's not uncommon to have a case where a package only ever need to write to a file only once.

I propose adding a `\file_put:nn {⟨file name⟩} {⟨string content to be written to the file⟩}` function that does what it says (mirror `file_get:nnN`). (to reduce number of input stream... at least for the packages that actually use it -- if it's part of the kernel probability it gets used increases, I guess. and also for convenience as writing to a file only take 1 line in that case)

**Comment by josephwright** [comment]
We have scratch `ior`/`iow` streams: that is what they would usually be for. Note that other when actively open, the `\io...` functions do not consume fixed streams - they come from a reusable pool.

**Comment by user202729** [comment]
Ah never mind then. Could still add file_put for convenience though.
