### ISSUE TITLE
Add \iow_shell_open:Nn?

### ISSUE THREAD

**Issue by user202729** [latex3/latex3#1122]
As the name implies. Similar to \ior_shell_open:Nn but for writing to the process.

Actually I'm not sure if this is portable, works on my machine at least.

**Comment by josephwright** [comment]
I'm not seeing how this would work at all - what sort of thing are you imaging doing?

**Comment by user202729** [comment]
Something like https://tex.stackexchange.com/questions/508761/write-to-screen-console-but-not-to-log-file/670572#670572 , or slightly more practically, I use it to build a 2-way communication channel with Python https://github.com/user202729/pythonimmediate-tex/blob/main/tex/pythonimmediate.sty#L118 .

But yes, these 2 are the only cases where I ever needed to use it so far if I recalled correctly.
