### ISSUE TITLE
[l3prg] `\bool_const:Nn` broken when second argument is `1`

### ISSUE THREAD

**Issue by PhelypeOleinik** [latex3/latex3#1124]
When fixing issue #1055, `\bool_const:Nn` got broken when its second argument is `1`. The trivial:
```latex
\bool_const:Nn \c_smth_bool { 1 }
```
breaks with:
```
! Missing number, treated as zero.
<to be read again> 
                   \relax 
l.5 \bool_const:Nn \c_smth_bool { 1 }
                                     
?
```

The issue boils down to:
```latex
\chardef \c_smth_bool =
  \bool_if:NTF 1 \c_true_bool \c_false_bool
```
and it breaks because the `1` doesn't terminate the conditional properly, and TeX sees the `\fi` before it is done scanning the number for the `\if_bool:N` inside `\bool_if:NTF`.  TeX inserts a `\relax` there, which then ends up in the `\chardef`, essentially:
```
\chardef \c_smth_bool = \relax
```
thus the error.

**Comment by PhelypeOleinik** [comment]
Well, maybe it shouldn't be supported, but it's convenient.  And it doesn't need checking much, just these two changes:
```latex
\ExplSyntaxOn
\cs_gset:Npn \__bool_if_p:n #1
  {
    \tl_if_empty:oT { \use_none:nn #1 . }
      { \exp:w \exp_end_continue_f:w \__bool_if_p_aux:w } % added \exp:w \exp_end_continue_f:w
    \group_align_safe_begin:
    \exp_after:wN
    \group_align_safe_end:
    \exp:w \exp_end_continue_f:w % (
    \__bool_get_next:NN \use_i:nnnn #1 )
  }
\cs_gset:Npn \__bool_if_p_aux:w #1 \use_i:nnnn #2#3
  { \bool_if:NTF { #2~ } \c_true_bool \c_false_bool } % added the ~
\ExplSyntaxOff
```

**Comment by FrankMittelbach** [comment]
It means as I understand it that you promote an implementation detail to general code usage. "1" does not mean "true" and I don't think it should appear as such in higher level code. So I'm not sure I'm in favor. Granted a lowlevel error for wrong input is not great but accepting wrong input is not good either in my opinion.

**Comment by PhelypeOleinik** [comment]
I ruled it as “should be fixed” mostly because it worked before, so to avoid breakage.  Though given it remain undetected for a good amount of time, maybe it's not as serious as I thought.

Explicitly prohibiting that input would be harder/slower (I think): after the check for a single token, it would have to check if the token is numeric, and then complain.  But then, it wouldn't make sense to have a pretty error message for that, and have `\bool_if_p:n { 1=1 }` fail with a low-level TeX error as it currently does.  Too much work for too little benefit, in my opinion.

Leaving as it is, with `1` it fails with a (rather ironic) `Missing number` error and with `0` it works...  Weird, but I guess good enough for wrong input.  With the proposed fix, it does the right thing on wrong input, which is not good either.  Couldn't think of a good option yet...

**Comment by PhelypeOleinik** [comment]
@josephwright No veredict.  I suggested "fixing" because it once worked (and because some languages accept 1 and 0 as input for boolean assignments).  @FrankMittelbach didn't like the idea as it's wrong usage.  I'm not too picky on that, so it's fine if we decide to close this and leave the code as it is.

**Comment by josephwright** [comment]
OK, closing as not planned
