### ISSUE TITLE
Avoid setting paper size when \mag is not 1000

### ISSUE THREAD

**Issue by aminophen** [latex3/latex3#1138]
I think it's better to avoid setting papersize special or pdf:pagesize special when \mag is not 1000, as there are two completely different ways of employing \mag exist in the LaTeX world.

Please refer to https://github.com/latex3/graphics-def/pull/1

**Comment by aminophen** [comment]
Sorry I'm talking about l3backend-pdf.dtx on 2022-09-28

**Comment by josephwright** [comment]
I guess my feeling is there are two possibilities here. If `\mag` is not supported , then we can as you say skip it, but really this should be accompaniedI' by efforts to remove it's use entirely. On the other hand, if it is allowable then there must be a logic to how it's used, in which can what's needed is a clear spec and I can then adjust the code to support it. I'm not keen on saying 'oh, some documents use this but we just ignore them'.

**Comment by davidcarlisle** [comment]
@josephwright  I'd agree having documented setting would be better, but I suspect it needs to be for new documents where we could set it via  `\DocumentMetadata`

when I looked at this for graphics some years back it seemed hard to detect anything useful without changing a lot of existing classes.

Basically for plain tex you can go

```
\mag2000
\input story
\bye
```

or

```
\magnification2000
\input story
\bye
```

 So either scaling everything, including the media box, or just scaling the fonts and reflowing in the original size.

If you come to setting `\stockwidth` , `\pdfpagewidth`, `\special{pagesize` or whatver, you really need to know which case you are in, but all you have is that \mag is not 1000.

If we had some magification setting in the metadata we could use that and hopefully the Japanese classes could pick that up in a compatible way, but for existing code without any documented setting of \mag following the current graphcs-def files is possibly the least disruptive update path.

**Comment by u-fischer** [comment]
@josephwright I agree with David. I don't think that we can know what a document or class which changes `\mag` actually wants as a mediabox. Both options (scale it or don't scale it) seems to be sensible in some use cases.  Imho we should as with negative `\stockwidth` take this as a marker that the document or the system wants to handle it.  (And perhaps we should add a public `\pdf_pagesize_set:nn` so that they can do it in a backend independent way.)
