### ISSUE TITLE
`msg_new` called before it is defined if an engine is missing an elapsed time command

### ISSUE THREAD

**Issue by vallettaventures** [latex3/latex3#1139]
When updating Texifier's internal TeX, we noticed an issue where `msg_new` is called before it is defined in the format building stage. If this error is triggered here

https://github.com/latex3/latex3/blob/b1c82f018fd3c7c4e87c19d4fbb6a82ba2016ec6/l3kernel/l3sys.dtx#L930

then instead of the correct error message, you get a message from TeX that `msg_new` is an undefined control sequence. I believe this happens because the file that defines `msg_new` is loaded in line 77 of the `l3.ins` file, whereas the file that calls `msg_new` is called by the file included on line 73.

https://github.com/latex3/latex3/blob/b1c82f018fd3c7c4e87c19d4fbb6a82ba2016ec6/l3kernel/l3.ins#L77

Obviously this is unlikely to be an issue for anyone not developing an independent TeX engine.

**Comment by josephwright** [comment]
I think we said LaTeX now requires the elapsed time primitive, but I see the point here: I'll adjust.

**Comment by vallettaventures** [comment]
Thanks! We have added that primitive to Texifiers internal engine for the next update.
