### ISSUE TITLE
Clarify `\color_select:n` definition

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#1145]
The following MCE:
```latex
\documentclass{article}
\begin{document}
\ExplSyntaxOn
\color_set:nnn {MyVeryNiceRed} {rgb} {1,0,0}
\color_select:n {MyVeryNiceRed} Foo
\ExplSyntaxOff
\end{document}
```
works like a charm. Hence, the argument of `\color_select:n` may be a `⟨color name⟩`, which is not immediately clear from the documentation which (currently in section 35.5 “Selecting colors”) talks only about `⟨color expression⟩:`
```latex
\color_select:n {⟨color expression⟩}
```
Maybe it is worth to replace the above by:
```latex
\color_select:n {⟨color name or expression⟩}
```

**Comment by josephwright** [comment]
`MyVeryNiceRed` _is_ a colour expression: it's just it's a very short one! The rule is you have a colour optionally followed by `!<n>`, itself optionally followed by `!<color2>`, etc. So the minimum expression is just one colour name.

**Comment by dbitouze** [comment]
> `MyVeryNiceRed` _is_ a colour expression: it's just it's a very short one! The rule is you have a colour optionally followed by `!<n>`, itself optionally followed by `!<color2>`, etc. So the minimum expression is just one colour name.

This is precisely what I find not very clear: probably not everyone is aware of this. Would my proposal hurt?

**Comment by josephwright** [comment]
@dbitouze  The rule is the same as for `xcolor`, which I'm pretty sure has never said it's a colour or colour expression. I can look at including a more formal definition of a colour expression: the `xcolor` one for example is very detailed.

**Comment by dbitouze** [comment]
@josephwright In `xcolor` documentation, both `\definecolor` and `\colorlet` mention `⟨name⟩`s:
```latex
\definecolor [⟨type⟩]{⟨name⟩}{⟨model-list⟩}{⟨spec-list⟩}
\colorlet [⟨type⟩]{⟨name⟩}[⟨num model⟩]{⟨color⟩}
```
