### ISSUE TITLE
`\l_text_case_exclude_arg_tl`: why not a sequence instead of a token list?

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#1151]
`expl3` provides `\l_text_case_exclude_arg_tl`:

>The first mandatory argument of commands listed in `\l_text_case_exclude_arg_tl` is excluded from case changing. 

But I wonder why these commands are not stored as a sequence instead of a token list. It would allow us to (in a easier way) remove from this list commands that we added earlier but only temporarily.

**Comment by Skillmon** [comment]
Why is removing in a sequence easier? It's just `\tl_remove_all:Nn`, and that is way faster than `\seq_remove_all:Nn`.

Also, a sequence has the structural overhead that token lists don't have.

**Comment by u-fischer** [comment]
@dbitouze normally I would expect that temporarly added commands are added in a group, and so disappear at the end of the group  anyway.

**Comment by dbitouze** [comment]
> Why is removing in a sequence easier? It's just `\tl_remove_all:Nn`, and that is way faster than `\seq_remove_all:Nn`.

Ah, thanks!

> Also, a sequence has the structural overhead that token lists don't have.

And what is the consequence?

**Comment by dbitouze** [comment]
> @dbitouze normally I would expect that temporarly added commands are added in a group, and so disappear at the end of the group anyway.

Okay but all my attempts in an argument of the `titlesec`'s `\titleformat` command failed.

**Comment by dbitouze** [comment]
Despite the (nice!) comments of @Skillmon and @u-fischer, wouldn't a sequence be more natural than a token list for a list of commands that can be extended?

**Comment by Skillmon** [comment]
@dbitouze there is simply no advantage of a sequence here. A sequence is nice if you're mapping to it in an unexpandable context (as it is built with a structure looking like `\s__seq \__seq_item:n { <first item> } \__seq_item:n { <second item> } ...` and you can then locally redefine `\__seq_item:n` to execute your function), but the token list is accessed in an expansion context, and there looping over a token list is (minisculy) faster, and it needs lees of TeX's memory (since the additional 3 tokens per item aren't necessary if your items consist of a single token).

**Comment by FrankMittelbach** [comment]
@dbitouze perhaps one question here is more important: what is your use case for locally changing that list? I don't think that @josephwright  ever intended to have it used for that, which either means a use case was overlooked or maybe you are trying to do something that is better handled differently.

**Comment by dbitouze** [comment]
@FrankMittelbach In a class of mine, I make use of the `titlesec`'s `\titleformat` command roughly like this:
```latex
\titleformat{\section}{
  \normalfont
  \LARGE
  \bfseries
  \text_uppercase:n
}{}{1em}{
  \aldineleft\c_space_tl
}{}
```
so all the section titles are uppercased. The problem comes when one wants to use `hologo`'s `\hologo` command in these titles. If these command isn't added to `\l_text_case_exclude_arg_tl`, e.g. `\hologo{LaTeX}` fails because `LATEX` isn't a known logo.

**Comment by FrankMittelbach** [comment]
@dbitouze well and what is then the use case for wanting to take `\hologo` off that exception list again????
Set it if the package gets loaded
```
\AddToHook{package/hologo/after}{...}
```
(or better get the package updated to be "uppercase safe" eventually) but I don't see why you want or should take it off afterwards.

**Comment by u-fischer** [comment]
> or better get the package updated to be "uppercase safe" eventually

well one could try the following. But hologo is rather complicated as it supports plain too and has backend dependant code and lots of tests so it go wrong somewhere ...

~~~~

\documentclass{article}
\usepackage{hologo}
\usepackage{etoolbox}
\usepackage{hyperref}
\makeatletter
\patchcmd\hologo{\hologoRobust{#1}}{\NoCaseChange{\hologoRobust{#1}}}{}{\fail}
\makeatother
\begin{document}
\tableofcontents 
\section{\hologo{LaTeX}}

\MakeUppercase{\hologo{LaTeX}}
\end{document}
~~~~

**Comment by Skillmon** [comment]
@dbitouze please note that you're using `\text_uppercase:n` at the wrong spot in `\titleformat`. You should use it in the last argument (else it gets more than just the section title as its argument). Better would be:

```
\titleformat\section{
  \normalfont
  \LARGE
  \bfseries
}{}{1em}{
  \aldineleft\c_space_tl\text_uppercase:n
}
```

**Comment by dbitouze** [comment]
> @dbitouze well and what is then the use case for wanting to take `\hologo` off that exception list again???? Set it if the package gets loaded
> 
> ```
> \AddToHook{package/hologo/after}{...}
> ```
> 
> (or better get the package updated to be "uppercase safe" eventually) but I don't see why you want or should take it off afterwards.

I must admit I'm not sure it is necessary but I wanted to alter the default behavior as little as possible. If it is harmless, good news! :)

**Comment by dbitouze** [comment]
> @dbitouze please note that you're using `\text_uppercase:n` at the wrong spot in `\titleformat`. You should use it in the last argument (else it gets more than just the section title as its argument).

Well, that's not what I observed:

```latex
\documentclass{article}
\usepackage{titlesec,fourier-orns}
\ExplSyntaxOn
\titleformat{\section}{
  \normalfont
  \LARGE
  \bfseries
  \text_uppercase:n
}{}{1em}{
  \aldineleft\c_space_tl
}{}
\ExplSyntaxOff
\begin{document}
\section{Foo}
Bar.
\end{document}
```
![image](https://user-images.githubusercontent.com/1032633/203528179-bd21649f-fd9d-449a-936f-3bb66b87f3f9.png)

And, since the syntax is:
```latex
\titleformat{⟨command⟩}[⟨shape⟩]{⟨format⟩}{⟨label⟩}{⟨sep⟩}{⟨before-code⟩}[⟨after-code⟩]
```
I put all the format instructions, including `\text_uppercase:n`, in the `⟨format⟩` argument.

> Better would be:
> 
> ```latex
> \titleformat\section{
>   \normalfont
>   \LARGE
>   \bfseries
> }{}{1em}{
>   \aldineleft\c_space_tl\text_uppercase:n
> }
> ```
The result is the same and I do not question your statement but I'm not that convinced :)

**Comment by Skillmon** [comment]
Don't believe me, believe the manual:

> • ⟨*before-code*⟩ is code preceding the title body. The very last command can take an
argument, which is the title text.<sup>7</sup> However, with the package option explicit the title
must be given explicitly with `#1` (see below). Penalties in this argument may lead to
unexpected results.

**Comment by dbitouze** [comment]
> Don't believe me, believe the manual:

I admit I am defeated :)

**Comment by dbitouze** [comment]
> (or better get the package updated to be "uppercase safe" eventually)

Other candidates for this would be `glossaries(-extra)` and `acro`. Not sure it is worth to list all packages that would need to be “uppercase safe”.
