### ISSUE TITLE
\tl_if_head_is_space:n description

### ISSUE THREAD

**Issue by qwenger** [latex3/latex3#1153]
https://github.com/latex3/latex3/blob/main/l3kernel/l3tl.dtx#L453

Shouldn't it read "explicit token with character code **32** and category code 10"?

**Comment by qwenger** [comment]
Done. Not sure whether the date should be bumped in "updated = 2012-07-08" or not (does this line only track changes in function code or also in description?).

**Comment by josephwright** [comment]
The date is for API changes: no need for a change here
