### ISSUE TITLE
Provide an easy way for appending sequence's items to a sequence

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#1157]
AFAICS, appending sequence's items to a sequence is currently not very handy:

- either by concatenating in a temporary sequence:
```latex
\documentclass{article}
\begin{document}
\ExplSyntaxOn
\seq_new:N \l_my_sequence_one_seq
\seq_new:N \l_my_sequence_two_seq
\seq_put_left:Nn \l_my_sequence_one_seq  {foo1}
\seq_put_left:Nn \l_my_sequence_one_seq  {bar1}
\seq_put_left:Nn \l_my_sequence_two_seq  {foo2}
\seq_put_left:Nn \l_my_sequence_two_seq  {bar2}
\seq_concat:NNN \l_tmpa_seq \l_my_sequence_one_seq \l_my_sequence_two_seq
\seq_set_eq:NN \l_my_sequence_one_seq \l_tmpa_seq
\seq_show:N \l_my_sequence_one_seq
\ExplSyntaxOff
\end{document}
```
- or by mapping over sequences:
```latex
\documentclass{article}
\begin{document}
\ExplSyntaxOn
\seq_new:N \l_my_sequence_one_seq
\seq_new:N \l_my_sequence_two_seq
\seq_put_left:Nn \l_my_sequence_one_seq  {foo1}
\seq_put_left:Nn \l_my_sequence_one_seq  {bar1}
\seq_put_left:Nn \l_my_sequence_two_seq  {foo2}
\seq_put_left:Nn \l_my_sequence_two_seq  {bar2}
\seq_map_inline:Nn \l_my_sequence_two_seq {\seq_put_right:Nn \l_my_sequence_one_seq {#1}}
\seq_show:N \l_my_sequence_one_seq
\ExplSyntaxOff
\end{document}
```

It would be useful if `expl3` would provide something like:
- `\seq_put_left:NN  ⟨sequence1⟩ ⟨sequence2⟩`
- `\seq_put_right:NN ⟨sequence1⟩ ⟨sequence2⟩`

**Comment by FrankMittelbach** [comment]
```
\cs_new:Npn \seq_put_right:NN #1 #2 {
   \seq_concat:NNN \l_tmpa_seq  #1 #2
   \seq_set_eq:NN  #1 \l_tmpa_seq
}
```
That is slightly less efficient as it could be, but I'm not sure it warrants to define both commands  manually in the kernel, because you would need a huge amount of such operations to not any difference if at all.

**Comment by dbitouze** [comment]
> That is slightly less efficient as it could be, but I'm not sure it warrants to define both commands manually in the kernel, 

Concatenate lists is very common, e.g. in Python:
```python
>>> a=list(range(0, 15, 2))
>>> b=list(range(1, 15, 2))
>>> a=a+b
>>> print(a)
[0, 2, 4, 6, 8, 10, 12, 14, 1, 3, 5, 7, 9, 11, 13]
```
>because you would need a huge amount of such operations to not any difference if at all.

Which ones for instance?

**Comment by PhelypeOleinik** [comment]
> Concatenate lists is very common, e.g. in Python:
> ```python
> >>> a=list(range(0, 15, 2))
> >>> b=list(range(1, 15, 2))
> >>> a=a+b
> >>> print(a)
> [0, 2, 4, 6, 8, 10, 12, 14, 1, 3, 5, 7, 9, 11, 13]
> ```

You can do exactly the same in `expl3`:

```
\seq_set_from_clist:Nn \l_tmpa_seq { 0, 1, 2 }
\seq_set_from_clist:Nn \l_tmpb_seq { 3, 4, 5 }
\seq_concat:NNN \l_tmpa_seq \l_tmpa_seq \l_tmpb_seq
\seq_show:N \l_tmpa_seq
```

The above (hopefully; I wrote this from my phone) prints:
```
0, 1, 2, 3, 4, 5
```

**Comment by PhelypeOleinik** [comment]
This is the general behaviour in `expl3`: first evaluate input arguments, then store output arguments (there is no black-and-white distinction, but it should be clear from the intent of the function).  If the input is the same variable type as the output, you should in all cases be able to use the same in both arguments (for a more trivial example, `\int_set:Nn \l_tmpa_int { \l_tmpa_int + 1 }`).  If that doesn't work, it is likely a bug.

Would you like to make a PR with the proposed change?

**Comment by car222222** [comment]
I see that @PhelypeOleinik has also confirmed this:

Both theory (looking at the implementation code) and experiment suggest that these can be more simply achieved by simply using:
\seq_concat:NNN \l_my_sequence_one_seq 
   \l_my_sequence_one_seq \l_my_sequence_two_seq
or:
\seq_concat:NNN \l_my_sequence_one_seq 
    \l_my_sequence_two_seq \l_my_sequence_one_seq

**Comment by car222222** [comment]
@dbitouze Yes, "it is worth mentioning it in the documentation",
But only to state clearly that *all* similar l3 functions work in this way (with maybe a very occasional exception that is clearly documented).

**Comment by dbitouze** [comment]
> Would you like to make a PR with the proposed change?

@PhelypeOleinik As said by @car222222, it shouldn't be mentioned here only (and even maybe not here). I prefer let the team think about the best way to inform the readers about this feature.
