### ISSUE TITLE
cmy parsing is wrong

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex3#1158]
The current definition is 

~~~~
\cs_new:Npn \@@_parse_model_cmy:w #1 , #2 , #3 , #4 \s_@@_stop
  {
    { cmyk }
    { \@@_convert_rgb_cmyk:nnn {#1} {#2} {#3} }
  }
~~~~

which takes the arguments as rgb and tries to convert them. Correct would be to append only a 1 for the black component:

~~~~
\documentclass{article}

\begin{document}
\ExplSyntaxOn
\color_set:nnn{testA}{cmy}{0.5,0.5,1}
\color_export:nnN  {testA}{backend}\l_tmpa_tl
\tl_show:N \l_tmpa_tl % gives wrong {cmyk}{0 0 0.5 0.5}.

\cs_set:Npn \__color_parse_model_cmy:w #1 , #2 , #3 , #4 \s__color_stop
  {
    { cmyk }
    { 
      \__color_parse_number:n {#1} ~
      \__color_parse_number:n {#2} ~
      \__color_parse_number:n {#3} ~
      1.0 
    }
  }
  
\color_set:nnn{testA}{cmy}{0.5,0.5,1}
\color_export:nnN  {testA}{backend}\l_tmpa_tl
\tl_show:N \l_tmpa_tl % correct {cmyk}{0.5 0.5 1.0 1.0}.
\ExplSyntaxOff
\end{document}
~~~~

**Comment by zauguin** [comment]
> Correct would be to append only a 1 for the black component:


That wouldn't work since it e.g. converts CMY (0, 0, 0) (aka. white) to CMYK (0, 0, 0, 1) (aka. black).
I think the conversion should be `k' = min(c, m, y)` and then `c' = c-k', m' = m-k', y' = y-k'`.

**Comment by u-fischer** [comment]
oh well ;-)  Sorry I mixed up 1 and 0.  xcolor seems to set always k=0:

~~~~
\documentclass{article}

\usepackage{xcolor}

\begin{document}

\definecolor{test}{cmy}{0,0,0}\color{test}
\makeatletter \show\current@color \show\XC@current@color

\definecolor{test}{cmy}{1,0,0}\color{test}
\makeatletter \show\current@color \show\XC@current@color

\definecolor{test}{cmy}{1,1,1}\color{test}
\makeatletter \show\current@color \show\XC@current@color

\definecolor{test}{cmy}{0.5,0.5,0.5}\color{test}
\makeatletter \show\current@color \show\XC@current@color

\definecolor{test}{cmy}{0.2,0.4,0.3}\color{test}
\makeatletter \show\current@color \show\XC@current@color


\end{document}
~~~~

**Comment by muzimuzhi** [comment]
I don't know why but only with `\usepackage[cmyk]{xcolor}` or after the equivalent form `\selectcolormodel{cmyk}`, cmy colors are actually converted to cmyk colors, using the conversion function described in `xcolor` doc, sec. 6.3.2.

By default `xcolor` uses "natural" color model, whose behavior looks not that natural. In `xcolor` doc, it's documented as

> Table 1: Package options
> | Option | Description |
> |--------|-------------|
> | natural | (Default.) Keep all colors in their model, except RGB (converted to rgb), HSB (converted to hsb), and Gray (converted to gray). |

Thus it seems under "natural" model, cmy colors are directly used as cmyk by appending a 0 as k.

**Comment by u-fischer** [comment]
@muzimuzhi  Oh no, don't say that it is a xcolor bug ;-(  With the cmyk model I get the value from l3color.

**Comment by josephwright** [comment]
I've checked the `xcolor` docs - I think I have the code in `l3color` right ...

**Comment by u-fischer** [comment]
yes I think so. But xcolor doesn't get it right always ;-( sigh.
