### ISSUE TITLE
Incomplete `\ifodd`; all text was ignored after line 8755.

### ISSUE THREAD

**Issue by Witiko** [latex3/latex3#1161]
Running plain LuaTeX from current TeX Live with the input `\input expl3-generic.tex \bye` ends with the following error:

```
This is LuaTeX, Version 1.15.1 (TeX Live 2023/dev)
 restricted system commands enabled.
(./example.tex
(/usr/local/texlive/2022/texmf-dist/tex/latex/l3kernel/expl3-generic.tex
(/usr/local/texlive/2022/texmf-dist/tex/latex/l3kernel/expl3-code.tex
(/usr/local/texlive/2022/texmf-dist/tex/latex/base/ltluatex.tex)
! Incomplete \ifodd; all text was ignored after line 8755.
<inserted text>
\fi
<to be read again>
^^L
l.8757     \cs_set:Npn ^^L
                         { }
? 
```

This issue has appeared in TeX Live sometime between January 15 and January 22.

**Comment by Witiko** [comment]
@josephwright As previously discussed in https://github.com/latex3/latex3/issues/1142#issuecomment-1296900745, it may be helpful to include a simple test of loading `expl3-generic.tex` from plain TeX into the CI, so that such issues are caught before release.

**Comment by josephwright** [comment]
@Witiko  I do wonder what you are up to with plain and `expl3`: we mainly want it for 'scripting', which doesn't tend to go beyond your own system ...

**Comment by Witiko** [comment]
@josephwright The significance of expl3 as a high-level programming layer for TeX goes beyond its use in LaTeX3. The documentation of LaTeX3 suggests that this is a supported use case.

**Comment by josephwright** [comment]
@Witiko  'Supported use caes' yes, 'used in the wild' ... less so

**Comment by Witiko** [comment]
@josephwright Any idea why? Expl3 does not seem tightly tied to the LaTeX format. I don't see why it would not become a popular choice for programming in TeX unless you try to actively discourage it.

**Comment by josephwright** [comment]
@Witiko I guess because plain users want something very small and stable, and code up their own stuff, ConTeXt users have Lua, and there are very few other TeX users ...

**Comment by Witiko** [comment]
> ConTeXt users have Lua

Lua does not seem terribly convenient for macro programming though.

**Comment by josephwright** [comment]
@Witiko  ConTeXt users don't do a lot of _macro_ programming I think; anyway, I'm not saying `expl3` isn't generally useful, rather it's not generally seen in use - I've added a test to make sure loading in plain works for pdfTeX/XeTeX/LuaTeX.

**Comment by Witiko** [comment]
@josephwright Thank you, that is much appreciated.
