### ISSUE TITLE
Add \token_case_type:Nn(TF) for polymorphic programming

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1165]
With all the token conditionals like `\token_if_letter:NTF`, `\token_if_int_register:NTF`, etc. listed in `interface3.pdf`, sec. 23.5, it would be helpful to have a `\token_case_type:NnTF` with grammar like
```tex
\token_case_type:NnTF \mytoken
  {
    {macro}          {is macro}
    {int_register}   {is int register}
    {font_selection} {is font selection}
  }
  {} {false}
```
which is flatter than
```tex
\token_if_macro:NTF \mytoken
  {is macro}
  {
    \token_if_int_register:NTF \mytoken
      {is int register}
      {
        \token_if_font_selection:NTF \mytoken
         {is font selection}
         {false}
      }
  }
```

One concern: TeX doesn't has a real/serious type system hence there isn't a list of distinct token conditionals whose union covers all the possible tokens.

**Comment by josephwright** [comment]
I'm wondering about the suggested interface with the various text entries for (partial) csname creation. I don't think this 'feels' great.

**Comment by josephwright** [comment]
@FrankMittelbach Would welcome your thoughts here. @blefloch might of course have some clever idea!

**Comment by muzimuzhi** [comment]
> I'm wondering about the suggested interface with the various text entries for (partial) csname creation. I don't think this 'feels' great.

Yes it's a bit uncommon.  Currently one can already use `\bool_case:nTF` with boolean expressions in form `\token_if_xxx_p:N <token>`.

```tex
\bool_case:nTF
  {
    { \token_if_macro_p:N \mytoken }
      { is macro }
    { \token_if_int_register_p:N \mytoken }
      { is int register }
    { \token_if_font_selection_p:N \mytoken }
      { is font selection }
  }
  {} {false}
```

**Comment by FrankMittelbach** [comment]
> @FrankMittelbach Would welcome your thoughts here. @blefloch might of course have some clever idea!

I don't think I like it much, besides the fact that is most likely quite inefficient in that form (but I may be mistaken there).
