### ISSUE TITLE
Interface3.pdf: color percentage typo

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex3#1170]
On page 293, one reads
```
A trailing percentage is interpreted as implicitly followed by white, and so
red!25
```
As the ``percentage'' is what is between the two `!` characters, `white` should be replaced by `!white`

**Comment by jlaurens** [comment]
By the way, this "percentage" terminology is very specific to interface3.pdf.
In general, the `50` in `red!50!green` is just a non negative integer, whereas the percentage is `50%`, `50/100` or even `0.5`.
So strictly speaking, `50 ` is not a percentage but is ``interpreted'' as a percentage.
Notice that latex3 accepts `red!150!green`, in which the number `150` is interpreted as `100%` and not `150%`.
This feature is undocumented.

**Comment by josephwright** [comment]
> By the way, this "percentage" terminology is very specific to interface3.pdf. In general, the `50` in `red!50!green` is just a non negative integer, whereas the percentage is `50%`, `50/100` or even `0.5`. So strictly speaking, `50 ` is not a percentage but is ``interpreted'' as a percentage. Notice that latex3 accepts `red!150!green`, in which the number `150` is interpreted as `100%` and not `150%`. This feature is undocumented.

I suppose I think of `50`, `0.5` and `50%` as 'all the same': they are simply different display formats for percentage values :) On the 150 business, a percentage contribution is always in the range 0-100, so I'd say outside that things are just undefined.

**Comment by josephwright** [comment]
> By the way, this "percentage" terminology is very specific to interface3.pdf. In general, the `50` in `red!50!green` is just a non negative integer, whereas the percentage is `50%`, `50/100` or even `0.5`. So strictly speaking, `50 ` is not a percentage but is ``interpreted'' as a percentage. Notice that latex3 accepts `red!150!green`, in which the number `150` is interpreted as `100%` and not `150%`. This feature is undocumented.

There's no need for the value to be an integer as far as I know

**Comment by jlaurens** [comment]
The `xcolor` package allows `red!20.5!green` but with that same expression, latex3 color module breaks at `\ifnum`, which suggests that values must be integers. Did I miss something ?

About the percentage, this is not really a display problem, this is more an input problem. If you must input `red!25`, you cannot input `red!25%` nor `red!0.25`, even if you can definitely think that they are ``the same''. What is input is only an integer, the number of the percentage.

In essence, nothing prevents a contribution from being negative or greater than 100%.
The `xcolor` package puts explicit limits and raises an error if the arguments are not in the appropriate range.

**Comment by muzimuzhi** [comment]
> In essence, nothing prevents a contribution from being negative or greater than 100%.
> The `xcolor` package puts explicit limits and raises an error if the arguments are not in the appropriate range.

I agree with @jlaurens.
<details><summary>Example with patch and tests</summary>

```tex
\documentclass{article}
\usepackage{xpatch}

\ExplSyntaxOn
\def\testColorExpr#1{\par\noindent
  \llap{\texttt{ \tl_to_str:n {#1} }}~
  \color_group_begin:
    \color_select:n {#1} \rule{2em}{2.5ex}~
    \tl_gset_eq:NN \g_tmpa_tl \l__color_current_tl
  \color_group_end:
  \texttt{[ \tl_to_str:V \g_tmpa_tl ]}
}

\def\test{
  \testColorExpr {red!-20}
  \testColorExpr {red!50}
  \testColorExpr {red!150!}

  \testColorExpr {red!133!yellow!-42}
  \testColorExpr {red!20!yellow!50}
  \testColorExpr {red!-356!blue!255!}
}
\ExplSyntaxOff

\begin{document}
\subsection*{Before} \test

\ExplSyntaxOn
% normalize "percentage" integer to range [0, 100]
\cs_new_protected:Npn \__color_parse_loop_normalize:w #1 !
  {
    \int_compare:nNnTF {#1} < { 0 }
      { \__color_parse_loop:w 0 ! } % TODO add some error
      {
        \int_compare:nNnTF {#1} > { 100 }
          { \__color_parse_loop:w 100 ! } % TODO add some error
          { \__color_parse_loop:w #1 ! }
      }
  }

% replace uses of \__color_parse_loop:w with \__color_parse_loop_normalize:w
\xpatchcmd \__color_parse_loop_init:Nnn
  {\__color_parse_loop:w}
  {\__color_parse_loop_normalize:w}
  {}{\PatchFailed}

\xpatchcmd \__color_parse_loop:w
  { \__color_parse_loop:w }
  { \__color_parse_loop_normalize:w }
  {}{\PatchFailed}
\ExplSyntaxOff

\subsection*{After}  \test
\end{document}
```

</details>

![image](https://user-images.githubusercontent.com/6376638/217690506-9d9f60e1-3127-433c-8e8d-27c4ad21b754.png)

**Comment by josephwright** [comment]
I will look at this once some important non-code tasks are complete: this is likely to be at least a couple of weeks.

**Comment by josephwright** [comment]
OK, I've adjusted the documentation, and I can see where the issue comes with an `int` test rather than an `fp` one. However, before I change anything I'd like to ask what we all feel the right behaviour is.

You get an error from `xcolor` not because it filters out values outside `[0,100]`, but because the driver code rejects anything outside `[0,1]`. So the design at the `xcolor` level _does_ support values out-of-range. I'm wondering if to avoid adding an error but simply using `\fp_compare:nNnTF` and normalising anything out of range. (Aside: moving from `int` to `fp` comparisons, I'll avoid testing for equality as that's a known bad-idea with `fp` values.)

**Comment by muzimuzhi** [comment]
> I can see where the issue comes with an `int` test rather than an `fp` one.

my bad. I find I'm much less careful when writing code than reading/reviewing other's code. :(

> You get an error from `xcolor` not because it filters out values outside `[0,100]`, but because the driver code rejects anything outside `[0,1]`.

Ah yes.  It's done in `\c@lor@arg`, which is called by all `\c@lor@@<model>`.
```tex
\def\c@lor@arg#1{%
  \dimen@#1\p@
  \ifdim\dimen@<\z@\dimen@\maxdimen\fi
  \ifdim\dimen@>\p@
    \PackageError{color}{Argument `#1' not in range [0,1]}\@ehd
  \fi}
```

There's still a slight difference: when is that check/normalization done.  `xcolor` does the check every time a final or intermediate color is calculated.  Examples applying a mixing far outside `[0,100]` followed by a (small, near `0`) mixing inside `[0,100]` can show the difference.  For example,
- in current `l3color` `green!350!blue!20 -> {rgb}{0 3.5 -2.5}!20 -> {rgb}{0.8 1.5 0.3}`,
- if normalized only at final stage, it gives `{rgb}{0.8 1.5 0.3} ->(norm) {rgb}{0.8 1.0 0.3}`
- if normalized at intermediate stages as well, it gives `{rgb}{0 3.5 -2.5}!20 ->(norm) {rgb}{0 1.0 0}!20 -> {rgb}{0.8 1 0.8}`

**Comment by josephwright** [comment]
Should now be fixed: @muzimuzhi muzimuzhi  please take a look and I'll then release

**Comment by muzimuzhi** [comment]
Ah you chose to check the range `[0, 100]` while I though you'll check the range `[0, 1]`... . Checking against `[0, 1]` has an advantage: it also guards explicit out-of-range color values like `\color_set:nnn {myred} {rgb} {2.5, 0, 0}` and `\color_select:nn {rgb} {2.5, 0, 0}`.

**Comment by josephwright** [comment]
@muzimuzhi That would be a different check at a different point: I can certainly add but colour expressions take values in the range `[0,100]` not `[0,1]`. (There's a reason I made the error message flexible!). I'll look at the non-expression stuff as well, I'll also fix the typo.

**Comment by josephwright** [comment]
@muzimuzhi  I think the current `xcolor`/`color` message is not great, as the user input doesn't use a value in `[0,1]` in the case of an expression.

**Comment by muzimuzhi** [comment]
> I think the current `xcolor`/`color` message is not great, as the user input doesn't use a value in `[0,1]` in the case of an expression.

Agreed. Adding some context may make the error message more helpful, like `in evaluating color expression/value ``xxx''`, if the required part of expression/value is stored.

This also adds some support for separate checks for color values and expressions: better error messages. At first I thought checking for `[0,1]` is enough to cover all cases.

**Comment by josephwright** [comment]
I'm going to look to release probably today with this fix in.
