### ISSUE TITLE
l3text: case changing functions doesn't work in uptex

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1171]
Like XeTeX and LuaTeX, UpTeX is another unicode engine. But in defining some l3text case changing internals (see #1120 and #1141), uptex is not taken into consideration.

https://github.com/latex3/latex3/blob/f01907b869c3d48c5afed4f6ecd9bdadba046a8c/l3kernel/l3text.dtx#L638-L645
https://github.com/latex3/latex3/blob/f01907b869c3d48c5afed4f6ecd9bdadba046a8c/l3kernel/l3text.dtx#L698-L712

```tex
\documentclass{article}
\begin{document}
\ExplSyntaxOn
\text_uppercase:nn{}{一级标题} % some arbitrary Chinese chars
\ExplSyntaxOff
\end{document}
```
Compile the example above with `uplatex main.tex` and it throws error
```
 Arithmetic overflow.
<recently read> \__int_eval_end:

l.4 \text_uppercase:nn{}{一级标题}
```

**Comment by josephwright** [comment]
I'll adjust here. From my point of view, upTeX is 'not quite a Unicode engine' so getting things right can be interesting. (Most obviously upTeX can't use OpenType fonts, doesn't therefore have `\Umathcode`, etc., but also the handling of some chars isn't identical to that in XeTeX and LuaTeX.)

**Comment by josephwright** [comment]
Ah, I remember where the 'fun' starts here. As upTeX doesn't have `\Uchar` or an equivalent, we can only _generate_ characters in the 8-bit range in an expandable manner. (Rather, the setup to cover the entire Unicode range isn't reasonable, so the realistic limit is the 8-bit range.) That means that the aim is meant to be to cover the 8-bit range without erroring outside it: obviously I've not got that right! I'll have to work back through from `\char_generate:nn` 'forward' to make sure I have a sensible fix - my initial 'just change the conditionals' plan fell down because of the limitation here.

**Comment by josephwright** [comment]
Now I remember the other thing: when we run the tests, this all looks OK! The reason is we set `GUESS_INPUT_KANJI_ENCODING=0` as that allowed testing to give the same results as pdfTeX as far as possible.

**Comment by josephwright** [comment]
I think before making any code changes we likely need a spec here for what's expected in upTeX - it's not as simple as the other engines. I probably also need to know if I can access the result of `GUESS_INPUT_KANJI_ENCODING` from within the engine, and I suspect need to adjust the test setup a bit.

So, in the first instance, what's the expectation with non-8-bit western chars here?

**Comment by muzimuzhi** [comment]
> So, in the first instance, what's the expectation with non-8-bit western chars here?

So sorry I hardly have any use experience about upTeX. The reported problem was encountered when I tried to update testfiles for `ctex`, see https://github.com/CTeX-org/ctex-kit/pull/650. Perhaps it worth to report to and request suggestions from https://github.com/texjporg/tex-jp-build/issues?

**Comment by josephwright** [comment]
@muzimuzhi I'll do that: I would like to get a feel for the landscape before making any changes.

**Comment by josephwright** [comment]
@muzimuzhi Seems I'd missed `\Ucharcat` begin added to (u)pTeX: that might make it easier for me to sort this, but I still need to look at a few other things. Might take a couple of weeks before I can address this - I do want to be sure I don't make things worse with a change.

**Comment by muzimuzhi** [comment]
> @muzimuzhi Seems I'd missed `\Ucharcat` begin added to (u)pTeX: [...]

Just to add a link to the TeX Live Guide:

> Release History, 2020
>
> epTeX, eupTeX: New primitives `\Uchar`, `\Ucharcat`, `\current(x)spacingmode`, `\ifincsname`; revise `\fontchar??` and `\iffontchar`. For eupTeX only: `\currentcjktoken`.
> https://www.tug.org/texlive/doc/texlive-en/texlive-en.html#x1-880009.1.17

> Might take a couple of weeks before I can address this - I do want to be sure I don't make things worse with a change.

Relax. For me and partially for `ctex-kit`, I think it's in no hurry.
