### ISSUE TITLE
Shouldn't the \bool_if:NTF function be called \bool_if:VTF?

### ISSUE THREAD

**Issue by EvanAad** [latex3/latex3#1172]
The first argument is not expanded (otherwise the spec should have been x, or e, or o). Then it makes no sense for it to be a function. So it must be a variable, no?

**Comment by josephwright** [comment]
It's a variable, the same as `\bool_set:Nn` or `\tl_if_eq:NNTF` or ...

**Comment by EvanAad** [comment]
Well, shouldn't `\bool_set:Nn` be `\bool_set:Vn`?

**Comment by josephwright** [comment]
No, you can't set an `n`-type argument, only an `N`-type one

**Comment by EvanAad** [comment]
In the case of `\bool_if:NTF` the first argument isn't set, so why is it `N` instead of `V`?

**Comment by josephwright** [comment]
@EvanAad  Because it takes a boolean variable, for example `\l_my_action_bool`. That's `N`-type, and we are not converting to an expression, we are reading it directly. Indeed, we are pretty clear that the 'value' of a boolean is purely internal, only the logical state it represents has any meaning.

**Comment by josephwright** [comment]
`N` doesn't mean 'function', it means `single token'.

**Comment by EvanAad** [comment]
But if this single token is a variable, as in the case of  the first argument to `\bool_if:NTF`, shouldn't it be `V`?

**Comment by davidcarlisle** [comment]
> But if this single token is a variable, as in the case of the first argument to `\bool_if:NTF`, shouldn't it be `V`?

no, `V` means, essentially "pass the value of a variable to an `n` function argument.

Here as in definiton commands and other places you really are refering to the boolean variable with N and testing its value, you are not expanding the variable to its internal form and then passing a "boolean literal" to `\bool_if:nTF`
