### ISSUE TITLE
Provide a test for l3kernel date

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1177]
See the mirror feature request to latex2e https://github.com/latex3/latex2e/issues/1004, which suggests a new command
```tex
\IfExplAtLeastTF{<date>}{<true code>}{<false code>}
```
> It seems l3kernel need a similar test as well, especially for non-LaTeX users. But since in LaTeX there's already a helper `\@ifl@t@r`.

And there seems to be no date comparison functions in l3kernel yet.

**Comment by josephwright** [comment]
It's true there is no date comparison in `expl3`, but I am wondering about the use case here (I can see the use case at the 2e level).

**Comment by muzimuzhi** [comment]
when it's used with other formats through the generic loader `\input expl3-generic.tex`

**Comment by FrankMittelbach** [comment]
I guess it does have some use cases in 2e as well as when expl3 is used with other formats. With 2e we have the situation that the same main format can run with different expl3 code based on update sequence so if there is anything that requires to know that a certain functionality in L3 layer is corrected or a new one is added, then a query for the expl3 date can be appropriate I think.

**Comment by muzimuzhi** [comment]
It's even less useful but for the sake of completeness, perhaps a test/tester for `l3backend` date is also needed.  Currently `l3kernel` date is stored in both `\c__kernel_expl_date_tl` and `\ExplLoaderFileDate`, but `l3backend` date is never stored.

`\ExplBackendFileDate` was once introduced to hold the backend date in an intermediate commit https://github.com/latex3/latex3/commit/ea1f2cf56500e220d60dd2bf822acc7c1dba4003 of #787, but then removed in a later commit https://github.com/latex3/latex3/commit/623b465ec8c4e7a1fd79f4c55c860bd5244f064b of the same PR. There's even a little trace of its existence that has not yet been deleted.
https://github.com/latex3/latex3/blob/82d84a5b52ea1ea23e0ae77b88325d44c2ed335d/l3backend/l3backend-basics.dtx#L98-L100

Should I open a separate issue? If not I'll edit the issue title.

**Comment by josephwright** [comment]
@muzimuzhi I'm not seeing a use case for the `backend` test: the whole point of the backend code is it has no user functions, only supports `l3kernel`, etc., in places where there is a variability of definition.

**Comment by muzimuzhi** [comment]
> the whole point of the backend code is it has no user functions, only supports `l3kernel`, etc., ...

Sometimes change in backend is visible on user side, or to get the expected output a backend with some minimum date is required.  For example, issues 677, 1042, and 1085.  Of course, `l3backend` actively responds to bug reports so the window (from confirmed to fixed with new release) is narrow. "It's even less useful but for the sake of completeness ..."

**Comment by josephwright** [comment]
> Sometimes change in backend is visible on user side, or to get the expected output a backend with some minimum date is required. For example, issues 677, 1042, and 1085. Of course, `l3backend` actively responds to bug reports so the window (from confirmed to fixed with new release) is narrow. "It's even less useful but for the sake of completeness ..."

That's rather different from the use-case for checking `l3kernel`, where you might want to require some minimal version for functionality reasons.

**Comment by FrankMittelbach** [comment]
completeness is a subgoal not a main goal, meaning if you offer something just for completeness without any really useful application it clutters the code space and it makes people wonder what something is meant for. The case of different code branches to work around a bug in the backend doesn't warrant to add this command imho.

**Comment by josephwright** [comment]
I think this is covered in the 2e kernel.
