### ISSUE TITLE
Package mode of expl3 loads backend immediately

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1180]
- If `expl3` is loaded in "2ekernel" mode, backend is loaded at beginning of document.
- If `expl3` is loaded in "package" mode, backend is loaded immediately.

https://github.com/latex3/latex3/blob/ff789d060dacf2a661524d2f17f70b7a7728c5b0/l3kernel/expl3.dtx#L1484-L1486

This difference makes usable positions of `\pdf_uncompress:n` differ, because it relies on functions defined in backend file:
- in "2ekernel" mode, `\pdf_uncompress:n` is usable no earlier than hook `begindocument`, while
- in "package" mode, `\pdf_uncompress:n` is usable right after `expl3` package is loaded.

```tex
\documentclass{article}
%\usepackage{expl3}

\ExplSyntaxOn
%\AddToHook{begindocument}{
  \pdf_uncompress:
%}
\ExplSyntaxOff

\begin{document}
content
\end{document}
```
Compile example above then it throws error
```tex
! Undefined control sequence.
<argument> \__pdf_backend_compresslevel:n 
                                          {0}\__pdf_backend_compress_objects...
l.6   \pdf_uncompress:
```
Uncommenting either `\usepackage{expl3}` or `\AddToHook`-stuff resolves the error.

**Comment by u-fischer** [comment]
The backend can not be loaded by the kernel, as it is (eg with dvi based backends) not always possible to detect automatically which one is used. But some pdf functions (like the version) must be set early, that means using begindocument always can be too late. With DocumentMetadata the backend is loaded directly before documentclass.

**Comment by muzimuzhi** [comment]
> * If `expl3` is loaded in "2ekernel" mode, backend is loaded at beginning of document.
> * If `expl3` is loaded in "package" mode, backend is loaded immediately.

I should post at least one interrogative sentence: It this difference expected?

**Comment by u-fischer** [comment]
Yes. The kernel will ensure that the backend is loaded at begin document latest, but loading the package is one method to get it earlier.  Another is to use `\sys_ensure_backend:`.

**Comment by muzimuzhi** [comment]
thanks
