### ISSUE TITLE
l3benchmark: \g_benchmark_ops_fp gave strange results

### ISSUE THREAD

**Issue by lvjr** [latex3/latex3#1182]
I noticed that `\g_benchmark_ops_fp` might give strange results with the following test file:
```latex
\documentclass{article}
\usepackage{array}
\usepackage{l3benchmark}
\ExplSyntaxOn
\cs_new_protected:Npn \runtest #1 #2
  {
    #2 %% run the code first to load fonts
    \prg_replicate:nn { #1 }
      {
        \benchmark:n { #2 }
        \fp_log:N \g_benchmark_time_fp
        \fp_log:N \g_benchmark_ops_fp
      }
  }
\ExplSyntaxOff
\begin{document}

\newcommand\testcode{%
\begin{tabular}{|l|c|r|p{4em}|m{4em}|b{4em}|}
\hline
  alpha & beta    & gamma   & delta & epsilon & zeta  \\
\hline 
  eta   & theta   & iota    & kappa & lambda  & mu    \\
\hline  
  nu    & xi      & omicron & pi    & rho     & sigma \\
\hline  
  tau   & upsilon & phi     & chi   & psi     & omega \\
\hline
\end{tabular}\par
}

\runtest{20}{\testcode}

\end{document}
```
The following is part of the log file (compiled with LuaHBTeX on TeX Live 2022 on Windows 10):
```
This is LuaHBTeX, Version 1.15.0 (TeX Live 2022)  (format=lualatex 2022.11.13)  5 MAR 2023 14:53
 restricted system commands enabled.
**l3benchmark-bug.tex
(./l3benchmark-bug.tex
LaTeX2e <2022-11-01>
(d:/install/texlive/2022/texmf-dist/tex/latex/l3experimental/l3benchmark/l3benc
hmark.sty (d:/install/texlive/2022/texmf-dist/tex/latex/l3kernel/expl3.sty
Package: expl3 2022-11-02 L3 programming layer (loader) 
Package: l3benchmark 2023-01-24 L3 Experimental benchmarking
0.00239 seconds (1.34e4 ops)
> \g_benchmark_time_fp=0.002389167336856618.
> \g_benchmark_ops_fp=13365.54291953186.
0.00239 seconds (2.39e13 ops)
> \g_benchmark_time_fp=0.002388628791360294.
> \g_benchmark_ops_fp=23886287913602.94.
0.00239 seconds (2.39e13 ops)
> \g_benchmark_time_fp=0.002389167336856618.
> \g_benchmark_ops_fp=23891673368566.18.
0.00239 seconds (1.34e4 ops)
> \g_benchmark_time_fp=0.0023895263671875.
> \g_benchmark_ops_fp=13384.96416938111.
0.00239 seconds (1.34e4 ops)
> \g_benchmark_time_fp=0.002389167336856618.
> \g_benchmark_ops_fp=13378.59520753922.
0.00239 seconds (2e4 ops)
> \g_benchmark_time_fp=0.002388987821691176.
> \g_benchmark_ops_fp=20020.71176470588.
0.00239 seconds (2.39e13 ops)
> \g_benchmark_time_fp=0.002388987821691176.
> \g_benchmark_ops_fp=23889878216911.76.
0.00235 seconds (1.32e4 ops)
> \g_benchmark_time_fp=0.002351658318632393.
> \g_benchmark_ops_fp=13181.45390979787.
0.00221 seconds (1.85e4 ops)
> \g_benchmark_time_fp=0.002205343807444853.
> \g_benchmark_ops_fp=18526.8772091152.
0.00239 seconds (2.01e4 ops)
> \g_benchmark_time_fp=0.002389167336856618.
> \g_benchmark_ops_fp=20051.57904537487.
0.00235 seconds (1.97e4 ops)
> \g_benchmark_time_fp=0.002351658318632393.
> \g_benchmark_ops_fp=19717.51209349434.
0.00232 seconds (1.3e4 ops)
> \g_benchmark_time_fp=0.002320091323097153.
> \g_benchmark_ops_fp=12982.28006383056.
0.00239 seconds (2.01e4 ops)
> \g_benchmark_time_fp=0.002388808306525735.
> \g_benchmark_ops_fp=20068.19222576292.
0.00239 seconds (2.01e4 ops)
> \g_benchmark_time_fp=0.002388808306525735.
> \g_benchmark_ops_fp=20087.79964366792.
0.00239 seconds (2.01e4 ops)
> \g_benchmark_time_fp=0.002388808306525735.
> \g_benchmark_ops_fp=20087.79964366792.
0.00239 seconds (2.39e13 ops)
> \g_benchmark_time_fp=0.002389167336856618.
> \g_benchmark_ops_fp=23891673368566.18.
0.00239 seconds (2.39e13 ops)
> \g_benchmark_time_fp=0.002388987821691176.
> \g_benchmark_ops_fp=23889878216911.76.
0.00232 seconds (2.32e13 ops)
> \g_benchmark_time_fp=0.002318739891052246.
> \g_benchmark_ops_fp=23187398910522.46.
0.00239 seconds (2e4 ops)
> \g_benchmark_time_fp=0.002389167336856618.
> \g_benchmark_ops_fp=20012.49229575563.
0.00235 seconds (1.97e4 ops)
> \g_benchmark_time_fp=0.002351330172631049.
> \g_benchmark_ops_fp=19734.01344479604.
```
While the results of `\g_benchmark_time_fp` were more or less stable, those of `\g_benchmark_ops_fp` jumped randomly between `e4` and `e13` numbers. I am aware of tha fact that those ops are estimated results, but `e4` and `e13` make quite a huge difference.

**Comment by josephwright** [comment]
Looks platform-specific: I see it on Windows but not macOS.

**Comment by muzimuzhi** [comment]
Seems not reproducible on GitHub Actions' all three latest runners, see multiline warnings in Annotations area of this workflow run https://github.com/muzimuzhi/hello-github-actions/actions/runs/4339326896.

**Comment by lvjr** [comment]
@muzimuzhi On Windows you can find these lines in the output:
```
7.69e-4 seconds (3.98e3 ops)
7.78e-4 seconds (7.78e12 ops)
7.63e-4 seconds (2.74e3 ops)
```

**Comment by muzimuzhi** [comment]
Sometimes `\g_benchmark_time_fp` is 0, smaller than 1e-16, hence 
- in `\__benchmark_measure_op:`, `\g__benchmark_one_op_fp` is set to 1e-16
- in `\benchmark_silent:n`, `\g_benchmark_ops_fp` is set to the magnitude of 1e12.
https://github.com/latex3/latex3/blob/ff789d060dacf2a661524d2f17f70b7a7728c5b0/l3experimental/l3benchmark/l3benchmark.dtx#L400-L416
https://github.com/latex3/latex3/blob/ff789d060dacf2a661524d2f17f70b7a7728c5b0/l3experimental/l3benchmark/l3benchmark.dtx#L323-L329

**Comment by josephwright** [comment]
Indeed. If you look at the values, the timing for the problematic cases is always showing as zero. Presumably we are sometimes hitting a platform-dependent piece of code in the part that acquires the times. The best I can think of is to alter the floor for timing: something like `2e-7` looks to be as fast as one operation ever is on my system. Sound reasonable?

**Comment by Skillmon** [comment]
@josephwright `\benchmark:n{\prg_do_nothing:}` hits 2e-8 for me (and my machine isn't particularly fast), and the notion of `op` is documented as an arbitrary operation, moreover PCs don't exactly tend to get slower, so 2e-7 sounds biggish to me.

**Comment by Skillmon** [comment]
Also, mandatory Paulo citation:

> TeX benchmarks are like air conditioners: they don't work as expected when you open Windows. :)

**Comment by josephwright** [comment]
> `\benchmark:n{\prg_do_nothing:}`

Fair enough: I'm really just trying to adjust order of magnitude

**Comment by lvjr** [comment]
>TeX benchmarks are like air conditioners: they don't work as expected when you open Windows. :)

I think expl3 needs ~~air conditioners~~ regression tests on Windows.

**Comment by muzimuzhi** [comment]
@Skillmon Do you happen to know where is the origin of that citation? It's so fun that I'd like to quote it in my channel.

@lvjr BTW since `\benchmark:n {<code>}` already runs `<code>` enough times to reach the time limit `\g_benchmark_time_fp` (in seconds), I think for more accurate amortized measurement, instead of running a test for 20 times, you can run a test for only one time, but with a larger time limit.

**Comment by josephwright** [comment]
I guess everyone is happy enough with the proposed fix?

**Comment by muzimuzhi** [comment]
@clerkma told me that the 64-bit binaries on Windows delivered in texlive 2023 don't reproduce the problem. Could any Windows users double check this?

**Comment by lvjr** [comment]
I don't have TeX Live pretest. But I could reproduce the problem with MiKTeX 64bit LuaHBTeX on Windows.

**Comment by josephwright** [comment]
I see the issue with TL'23 on Windows (VM) updated to today using the stock 64-bit binaries.
