### ISSUE TITLE
Rename l3coffins?

### ISSUE THREAD

**Issue by jfbu** [latex3/latex3#1184]
I know raising this as an issue may be a bit unusual. I do not do this out of boredom or to create a stir.

Renaming all macros from this module looks at this time to be a low-impact change:

```
$ cd /usr/local/texlive/2022/texmf-dist/tex/latex
$ grep -r -l coffin
skrapport/skrapport.cls
tasks/tasks.sty
sdaps/sdapsarray.sty
sdaps/sdapsclassic.cls
sdaps/sdapsbase.sty
exsheets/exsheets_headings.def
skdoc/skdoc.cls
emoji/emoji-table.def
twemojis/twemojis.sty
abspos/abspos.sty
l3experimental/xcoffins/xcoffins.sty
l3experimental/l3draw/l3draw.sty
l3kernel/expl3-code.tex
l3kernel/l3doc.cls
pdfoverlay/pdfoverlay.sty
ducksay/ducksay.code.v2.tex
latexbug/latexbug.sty
circledtext/circledtext.sty
```

(the two emoji entries are false positive).  Thus only a handful of non-LaTeX3 owned projects.  And usage in the wild directly by end-users looks unlikely.  Attention that my TeX-installation is perhaps not complete, I perhaps do not have university templates or other such things.

I invite you to consider the matter.  Boxes with handles can be surely named othewise.  To remain in the joking spirit, for example `bankerbox`. Or, `ebox` for "enhanced box". (I drop my copyright on "e" prefix). Or `lbox` for "latex box". Or `bbox` for "beautiful", "better", etc....

**Comment by josephwright** [comment]
What's the motivation? We have a long history in this being called 'coffins', there's not really a better name, etc.

**Comment by jfbu** [comment]
English isn't my mother tongue so I can't know for sure what the term `coffin` conveys but I did check through dictionaries when opening this issue.  The direct translation to French is `cercueil` and I wouldn't like to have to encounter this word on a systematic basis in any computer language.  It is heavy in meaning for a human being, and feels like an intrusion here.

**Comment by josephwright** [comment]
In _programming_ terms, I agree it's unusual, but then most programming languages don't have typesetting to worry about in the first place. The name is to some extend a 'bit of fun', but it's memorable: a 'box with handles'. Other possibles

- `casket` - used originally for decorative boxes, but now mainly used for ... coffins
- `container` - probably too generic
- `node` - inspired by `pgf`, one could use this but I think it's not ideal (to me a node is a single point)

**Comment by FrankMittelbach** [comment]
This name exists since 2010 and there is even a published talk about it.  You also talk in English, for example, about "something being burried deep down in the code" which is a similar kind of reference. The TeX world is full of humor, sometimes a bit morbid or slippery, just think about the AmSTeX book being called "The Joy of TeX" or "The LaTeX Companion" which when spoken sound like "the latex companion". I see no reason to change the name.
