### ISSUE TITLE
Specify the `\long`/not `\long` property of the values of keys at the `\keys_define`'s level?

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#1190]
Suppose I'd like:

- some keys, the values of which should _not_ be `\long`, 
- some other keys, the values of which should be `\long`. 

In the following MCE, both values of the keys:

- either should _not_ be long (case where the argument specifier of `\MyModuleSetup` is `m`),
- or should be long (case where the argument specifier of `\MyModuleSetup` is `+m`).

```latex
\documentclass{article}
\ExplSyntaxOn
\keys_define:nn { mymodule }
{
  key-should-not-be-long .tl_set:N = \l__mymodule_should_not_be_long_tl ,
  key-should-be-long     .tl_set:N = \l__mymodule_should_be_long_tl ,
}
% \DeclareDocumentCommand \MyModuleSetup { m }
\DeclareDocumentCommand \MyModuleSetup { +m }
{
  \keys_set:nn { mymodule } { #1 }
  \AddToHook{begindocument}{%
    \l__mymodule_should_not_be_long_tl
    \par
    \l__mymodule_should_be_long_tl
  }
}
\ExplSyntaxOff
\MyModuleSetup{
  key-should-not-be-long = { Once upon a time,     ... },
  key-should-be-long     = { Once upon a time,\par ... },
}
\begin{document}
\end{document}
```
Wouldn't it be possible to specify the `\long`/not `\long` property of the values of keys at the `\keys_define`'s level?

**Comment by josephwright** [comment]
The `.tl_set:N` property is simply a wrapper around `\tl_set:Nn`, which like almost all code-level functions is `\long`.  We could add a property to disallow `\par` inside the argument to such keys, but I'm not seeing a clear use case. Here, I'm not sure quite what error you'd be picking up. (One can argue about the utility of TeX's `\long` approach at all (Hans has for example disabled it in ConTeXt).)

**Comment by dbitouze** [comment]
In fact, I'm note sure as well :) The question comes to my mind after Ulrike's answer [here](https://tex.stackexchange.com/q/682244/18401) where you can see I need values of keys to be `\long` (hence TeX's `\long` approach is useful at least in this case).

**Comment by muzimuzhi** [comment]
An emulation using `.code:n` property
```tex
\documentclass{article}

\ExplSyntaxOn
\keys_define:nn { mymodule }
  {
    key       .tl_set:N = \l__mymodule_tl
  , key~short .code:n   = { \tl_set:No \l__mymodule_tl { \use_nopar:n {#1} } }
  }

\cs_new_nopar:Nn \use_nopar:n { #1 }

\DeclareDocumentCommand \MyModuleSetup { +m }
{
  \keys_set:nn { mymodule } { #1 }
  \AddToHook{enddocument}{%
    \begin{center}
      \l__mymodule_tl
    \end{center}
  }
}
\ExplSyntaxOff

\begin{document}
\MyModuleSetup{
  key = {val}
, key = {val\par}
, key short = {val2}
, key short = {val2\par}
}

Once upon a time, ...
\end{document}
```
Since `key short` now accepts only short values, using `key short = {val2\par}` throws an error
```
Runaway argument?
{val2
! Paragraph ended before \use_nopar:n was complete.
<to be read again> 
                   \par 
l.29 }
```

**Comment by josephwright** [comment]
@Skillmon  Back with what I asked earlier: do you have use cases? It's not that hard to implement (I'd favour a separate property as that fits the `l3keys` model), but I'm not really sure it's worth it.

**Comment by Skillmon** [comment]
@josephwright got no good use case either, only some hypothetical (for instance collecting contents that will be used in a horizontal context), but I have no real-world example.

**Comment by FrankMittelbach** [comment]
While I'm known to lean towards distinguishing between long and not long  where it makes sense because that catches errors earlier than later, I can't really see this here: it only makes the interface more complex without compelling use cases. So my vote is to just keep it as it is and always accept `\par` on this level.
