### ISSUE TITLE
\MakeUppercase now is incompatible with previous versions

### ISSUE THREAD

**Issue by amalokostov** [latex3/latex3#1193]
## Brief outline of the bug
In old versions of MikTeX (including MikTeX produced by Basic installer basic-miktex-22.10-x64.exe, version 10/17/2022, without updates, so it reports that it is "MikTeX 22.10") \MakeUppercase ignores the command \noexpand, so, for example
\MakeUppercase{$\noexpand\sinn(x)$}
gives error message that \sinn is undefined.

If I install basic-miktex-22.10-x64.exe, version 10/17/2022  and install all possible updates (so MikTeX reports that it is "MikTeX 23.1"), \noexpand is not ignored here, so there is no error message. 

What is wrong? How can I fix it so that the code works in both MikTeXs and gives the same output? 

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

\usepackage[russian,english]{babel}

\begin{document}

\MakeUppercase{$\noexpand\sinn(x)$}

\end{document}
```

Thank you so much.

PS. I submit two log-files for MikTeX 22.10 and 23.1.

## Log file (required) and possibly PDF file  

[test2_MikTeX22_10.log](https://github.com/latex3/latex2e/files/11181240/test2_MikTeX22_10.log)
[test2_MikTeX23_1.log](https://github.com/latex3/latex2e/files/11181241/test2_MikTeX23_1.log)

**Comment by josephwright** [comment]
I've moved the issue to the latex3 repo as any change will be entirely here. A very simple change to the math mode expander would remove `\noexpand` from the input if inside math mode, and give the same behaviour as for text mode in this instance:
```latex
\documentclass{article}
\ExplSyntaxOn
\cs_gset:Npn \__text_expand_math_N_type:NN #1#2
  {
    \__text_if_s_recursion_tail_stop_do:Nn #2
      { \__text_expand_end:w }
    %%%% ADDED
    \token_if_eq_meaning:NNF #2 \exp_not:N
      { \__text_expand_store:n {#2} }
    %%%%
    \token_if_eq_meaning:NNTF #2 #1
      { \__text_expand_loop:w }
      { \__text_expand_math_loop:Nw #1 }
  }
\ExplSyntaxOff
\newcommand*\foo{foo}
\begin{document}
\MakeUppercase{\noexpand\foo~$\noexpand\sin(x)$}
\end{document}
```
That leaves the question of any `\noexpand` hidden inside a group in math mode, and more generally whether we should look again at expanding math content. Thoughts welcome.

**Comment by josephwright** [comment]
> I am sorry but I don't see a fundamental difference between using \noexpand in latex.ltx or article.cls by you or by your colleagues and in my own style file by me. The only difference is that you set the rules of the game and I follow them, so when you change them I should ask you "Have the rules of the game changed?".

In say `latex.ltx`, you'll find `\noexpand` used directly inside an `\edef`, so `\edef\wibble{...\noexpand\UnsafeToken...}` or similar, or in a context where the coder is absolutely sure an `\edef` will apply at some stage. You won't find one being used to apply to user input tokens, where `\protect` with its variable behaviour is what we would use.

**Comment by josephwright** [comment]
@davidcarlisle  Yes, I think it's that or we iterate over all of math mode input to ensure it's checked for `\noexpand`: easy enough, and most of the time less cycles than are needed for text, but would be a change so I'd like to be sure we have an agreed position

**Comment by amalokostov** [comment]
Dear @josephwright , thank you for your idea about modifying \MakeUppercase, but I need to learn this new programming language before this :-)

About expanding \noexpand: I think that if a TeX programmer writes \noexpand he knows why it does this. In my case, the reason was that \MakeUppercase expanded commands including "translation" of them into uppercase. This was several years ago. So I inserted my command into math mode and wrote \noexpand. And of course there was \edef at the very end. And of course this was not related to some mathematical formulas. And of course it was used in the style file, not in LaTeX document.

As for me \MakeUppercase should not expand commands at all. If I write 
\def\aaaa{bbbb}
\uppercase{bbbb\aaaa}
and obtain BBBBbbbb, this should be OK, so I should take this rule of the game into account and write my code taking this into account. I can use \uppercasetext@ from AmS-TeX if I need upper case only outside the math mode. But it is my personal opinion. Other people  may have other opinions. So the reason for my initial question was the change of the rules.

Many thanks to all participants.

Yours,
Andrei Malokostov

**Comment by josephwright** [comment]
I've decided to filter out `\noexpand` here as whilst it's questionable, I can see an argument for removing the token even in math mode.
