### ISSUE TITLE
Why not `\seq_set_from_clist:Nn ⟨seq var⟩ {⟨comma-list⟩}`?

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#1200]
Consider:

1. `\seq_const_from_clist:Nn ⟨seq var⟩ {⟨comma-list⟩}`
2. `\seq_set_from_clist:Nn ⟨seq var⟩ {⟨comma-list⟩}`

`latex3` provides the former but not the latter. Why?

**Comment by muzimuzhi** [comment]
`\seq_set_from_clist:Nn` _is_ provided, see line 105
https://github.com/latex3/latex3/blob/8239118af6788a6a78e079516afff0f0e7e29bd3/l3kernel/l3seq.dtx#L101-L115

**Comment by FrankMittelbach** [comment]
Also documented in interface3 on page 145. However we could do a bit of normalizing here and always use `<seq var>` not `<sequence>` as some of them do.

**Comment by dbitouze** [comment]
Ooops, sorry for the noise! I guess I wouldn't have been noisy if, instead of:
```latex
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
\seq_set_from_clist:NN          \seq_set_from_clist:NN ⟨sequence⟩ ⟨comma-list⟩
\seq_set_from_clist:(cN|Nc|cc)
\seq_set_from_clist:Nn
\seq_set_from_clist:cn
\seq_gset_from_clist:NN
\seq_gset_from_clist:(cN|Nc|cc)
\seq_gset_from_clist:Nn
\seq_gset_from_clist:cn
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```
this would have been documented as:
```latex
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
\seq_set_from_clist:NN          \seq_set_from_clist:NN ⟨sequence⟩ ⟨comma-list⟩
\seq_set_from_clist:(cN|Nc|cc)
\seq_gset_from_clist:NN
\seq_gset_from_clist:(cN|Nc|cc)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
\seq_set_from_clist:Nn          \seq_set_from_clist:Nn ⟨sequence⟩ {⟨comma-list⟩}
\seq_set_from_clist:cn
\seq_gset_from_clist:Nn
\seq_gset_from_clist:cn
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```
@FrankMittelbach +1 for `⟨seq var⟩` vs `⟨sequence⟩`.

**Comment by dbitouze** [comment]
@FrankMittelbach About `⟨seq var⟩` vs `⟨sequence⟩`, the same happens in the chapter devoted to comma separated lists: `⟨⟨clist var⟩` vs `⟨comma list⟩`.
