### ISSUE TITLE
generating protected/expandable predicates in expl3

### ISSUE THREAD

**Issue by alceu-frigeri** [latex3/latex3#1202]
working on an expl3 package, I got a request to make 'expl3 predicate functions' either expandable or protected (https://github.com/alceu-frigeri/starray/issues/1).

specifically, I got stuck at:
```
\documentclass{article}
\RequirePackage{expl3}
\ExplSyntaxOn

\prg_new_protected_conditional:Npnn \__starray_if_free:n #1 {T, F, TF}
  {
    \prop_if_exist:cTF {#1}
      { \prg_return_false: }
      { \prg_return_true: }
  }
%\prg_generate_conditional_variant:Nnn \__starray_if_free:n {e} {T, F, TF}

\prg_new_protected_conditional:Npnn \starray_new:n #1 {T, F, TF}
  {
    \__starray_if_free:nTF {\l__starray_prefix_tl #1 _def_prop}
      {
%        \__starray_new:e {#1 }
%        \__starray_base_new:ee {#1}{#1} % TODO: might be incomplete !!!
        \prg_return_true:
      }
      { \prg_return_false: }
  }

\ExplSyntaxOff

\begin{document}
 this ~  is ~ just ~ a  ~ test 
\end{document}
```

IF I replace {T, F, TF} by {p, T, F, TF} latex complains, for example, 
``` Predicate '\starray_if_free_p:n' must be expandable.```

As I understood (from interface3.pdf), given that \prop_if_exist:cTF is fully expandable, I thought that, at least ```\__starray_if_free_p:n``` would also be.

What I missing here (expandability) or what can be done ?

BTW, I think 'this is the better place' to post this question, but I have also post the same one at stackexchange https://tex.stackexchange.com/questions/685809/generating-protected-expandable-predicates-in-expl3

**Comment by muzimuzhi** [comment]
Only conditionals defined through `\prg_new_conditional:Npnn` can have `p` condition.

Compare doc for `\prg_new_conditional:Npnn`

> The conditionals created are depended on the comma-separated list of `⟨conditions⟩`, which should be one or more of `p`, `T`, `F` and `TF`.

and `\prg_new_protected_conditional:Npnn`

> The conditionals created are depended on the comma-separated list of `⟨conditions⟩`, which should be one or more of `T`, `F` and `TF` (not `p`).

**Comment by alceu-frigeri** [comment]
Ok. thanks.... I feared that, I mean, a macro/function, to be expandable, all it's code must also be expandable... 
which means, in my case, basically, none is... therefore, nothing much to be done, except 'removing the ill-declarations' (the predicate parts).

**Comment by alceu-frigeri** [comment]
@muzimuzhi 
kind of replying your comment (at stackexchage)...
the 'original question' was (directed at me...)
```latex
\documentclass{article}
\usepackage{starray}
\ExplSyntaxOn
\bool_if:nTF { \starray_new_p:n {myfoo} }
  { \message { TRUE } }
  { \message { FALSE } }

\bool_if:nTF { \starray_new_p:n {myfoo} }
  { \message { TRUE } }
  { \message { FALSE } }
\ExplSyntaxOff
```
the reason it fails, obviously, is because at its core, \starray_new:n (which is called by the conditional) isn't expandable (because it makes use, besides others, of \prop_new and friends)...
From there, I tried to see if there would be a way to 'protect' this construction, using \prg_new_protected_conditional,
but as you just pointed out: I can't because the code isn't expandable, and, well, back to square one.

so, given that the code isn't expandable, there isn't any workaround that would allow one to create a conditional.
fair enough ;)

**Comment by muzimuzhi** [comment]
Unless l3kernel introduces a non-expandable boolean expression parser (and non-expandable variants of boolean functions) I guess.

**Comment by josephwright** [comment]
Predicates can't be implemented without requiring expandability without a total change of structure. Moreover, the expandable/protected split doesn't just apply here: we try to be clear that everything either needs to be protected or fully expandable. As such, there's nothing to be done here at the `expl3` level.
