### ISSUE TITLE
Why no `\color_gset_eq:nn` and `\prg_gset_eq_conditional:NNn`

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1212]
Each of all `set_eq` functions have a `gset_eq` cousin, except for `\color_set_eq:nn` and `\prg_set_eq_conditional:NNn`.

Additions: Currently both of them act locally.
https://github.com/latex3/latex3/blob/139c10f8930315b7c27f8000fea839d7e9ef72fb/l3kernel/l3color.dtx#L1862-L1883
https://github.com/latex3/latex3/blob/139c10f8930315b7c27f8000fea839d7e9ef72fb/l3kernel/l3basics.dtx#L2173-L2174

**Comment by josephwright** [comment]
Colors are local-only constructs; I think on conditionals, it's largely because they are normally set-once-and-unchanged, so there is a low need.

**Comment by u-fischer** [comment]
For colors one really has to decide if the color structure should be global or local  (we discussed that in various places, I lean towards global). Having both (as offered by xcolor) is simply a pain.

**Comment by muzimuzhi** [comment]
> Colors are local-only constructs

I think I'm persuaded by the fact there's no `\color_new:<arg spec>` thing which always acts globally.

For conditionals, there already exist `\prg_new_conditional:Nnn` and `\prg_gset_conditional:Nnn` (and the `Npnn` variants), so adding a `\prg_set_eq_conditional:NNn` at least does no harm.
