### ISSUE TITLE
Dimension too large when re-using the output of re-entrant \dim_to_decimal_in_in:n for \maxdimen

### ISSUE THREAD

**Issue by jfbu** [latex3/latex3#1217]
Using code merged at 874675019ceedbb0 I obtain

```
! Dimension too large.
<to be read again> 
                   \relax 
l.6\the\dimexpr \converttoin{\maxdimen} in\relax
                                                 
? X
```

with this input:

```latex
\documentclass{article}
\ExplSyntaxOn
\newcommand\converttoin[1]{\dim_to_decimal_in_in:n{#1}}
\ExplSyntaxOff
\begin{document}
\the\dimexpr \converttoin{\maxdimen} in\relax
\end{document} 
```

Steps to reproduce:

- make sure your local checkout of this repo contains commit 874675019ceedbb0
- cd to l3kernel and issue `l3build install`
- check that your user texmf was updated
- issue `fmtutil-user --byfmt pdflatex` to rebuild format in your home "texlive/2023" or similar tree
- execute `pdflatex` on above file.

The rationale here is mainly to signal that some documentation is lacking.  I understand that re-entrant only means that if one starts from some input expressed in "in" unit, the output in "in" will represent the same dimension from TeX point of view.  Here my input `\maxdimen` is not of the type `<decimal>in` so the observed behaviour is not contradicting the current description, only pointing to some missing caveats innocent end-users may need to be informed of.

Package [texdimens](https://github.com/jfbu/texdimens/tree/master/texdimens) provides a macro [texdimenindown](https://github.com/jfbu/texdimens/tree/master/texdimens#texdimenindowndim-expr) with description
> Produces a decimal (with up to five decimal places) D such that Din represents the dimension exactly if possible. If not possible it will be largest representable dimension smaller than the original one.

Example:
```latex
\documentclass{article}
\usepackage{texdimens}
\begin{document}
``\texdimenindown{\maxdimen}in'' is parsed by \TeX{} into
\number\dimexpr \texdimenindown{\maxdimen} in\relax sp.
\end{document} 
```

![Capture d’écran 2023-05-22 à 09 17 34](https://github.com/latex3/latex3/assets/2589111/4e3b9182-b030-43ef-92b2-c8607663baf6)

Relates #954

**Comment by jfbu** [comment]
Right above https://github.com/jfbu/texdimens/tree/master/texdimens#macros-of-this-package-full-list there is a table with maximal attainable dimensions in TeX, according to unit used.

**Comment by josephwright** [comment]
I've added some docs, and used your table to provide the info. Does that cover it?

**Comment by jfbu** [comment]
@josephwright I must read more closely context of https://github.com/latex3/latex3/commit/7e7131f1c7fd488d5222ef18782b3fe7bda859ef  but I am troubled by 
> An input value equal to \cs{c_max_dim} in any other units will result in an overflow

I don't know if the algorithm matches exactly the one I implemented at texdimens which picked at some point a mid-point, but if it does then only the `dd`, `nc` and `in` units are such that they reproduce the behaviour leading to overflow I reported in this ticket.
> 2. For `dd`, `nc` and `in`, it turns out that `\texdimen<uu>{X}` chooses
   the "up" approximant for `X` equal to or very near `\maxdimen` (check
   the respective macro documentations),
   i.e. the output `D` is such that `Duu` is the first virtually
   attainable dimension beyond `\maxdimen`. Hence `Duu` will trigger on
   use a "Dimension too large error".  With the other units for which
   `\maxdimen` is not attainable exactly, `\texdimen<uu>{\maxdimen}`
   output is by luck the "down" approximant.
https://github.com/jfbu/texdimens/blob/3fd1190e51c766505e3992de1631578a47e80d23/texdimens/README.md?plain=1#L260-L267


Also, the sentence before the table looks slightly misleading, these are the maximal inputs when one uses only 5 decimal places.  If one allows more decimal places in input then (as the complete table at my site explains) one can input higher decimals.  But perhaps again I am missing exact context.

**Comment by josephwright** [comment]
I've refined the docs in 9c713ff3d3e69a68c3bf9c29bae6086f901125dd. I'm happy to aim for precision here but also note that in use `\maxdimen` isn't the main target: as such I think there's a balance to be struck!

**Comment by jfbu** [comment]
ok there is a typo `two` in place of `to` near top of commit, and as per my remark I see I confused two things: the problem here with `\maxdimen` and the input of a dimension in a given unit, and your documentation commit is about the latter not the former, i.e. it does not address really the present issue, but something else, hence my confusion (and the fact that I am doing sort of four things at once on my computer only one being TeX related...)

**Comment by jfbu** [comment]
> An input value equal to \cs{c_max_dim} in any other units
%   will result in an overflow, as it will convert to an internal value
%   (in \texttt{sp}) which is too large.

is really confusing to me in light of the subsequent explanations which focus on inputs in various units.  If that sentence is to be understood as: convert `\maxdimen` to a given unit, then attempt to use it, then probably (if the LaTeX3 algorithm is the same as texdimens "mid-point" one) it is wrong because it then refers to the issue I reported with `in` and (at least with texdimens algorithm) only `in`, `nc` and `dd` are problematic here for that `\maxdimen` thing.

```latex
\documentclass{article}
\ExplSyntaxOn
%\newcommand\converttoin[1]{\dim_to_decimal_in_in:n{#1}}
\newcommand\converttocm[1]{\dim_to_decimal_in_cm:n{#1}}
\ExplSyntaxOff
\usepackage{texdimens}
\begin{document}
\the\dimexpr \converttocm{\maxdimen}cm\relax
\end{document}
```
compiles without Dimension too large.

besides the sentence seems to say that if one uses `\maxdimen` as input, one causes an error, which is never the case with any unit.  It is only that output may not be usable.

**Comment by josephwright** [comment]
Any further refinement needed?

**Comment by jfbu** [comment]
> Any further refinement needed?

Well I am uncertain about the TeXhackers note about `\dim_to_decimal_in_bp:n` which says 
> The implementation of this functions is re-entrant: the result of \dim_to_decimal_in_bp:n { <n>bp }
will be the value ⟨n⟩.

It is not clear to me what `⟨n⟩` means but I skipped the earlier explanations.  Maybe it is a decimal with up to four of five places?.  But notice that `72.26998pt` and `72.26997pt` are the same TeX dimension so this is not true for `pt` unit.  Ah here is for bp: notice that `71.99999bp` and `71.99998bp` are the same TeX dimension.  So, but perhaps I misread, this sentence appears to say something wrong.  Let me read it again for double-check.  It seems I did read what I read.

I see a typo above: "functions" should be singular.

For me - re-entrant in this context means that `⟨n⟩ bp` and `\dim_to_decimal_in_bp:n { <n>bp } bp` are for TeX the same dimension, once parsed by it into an integer multiple of sp unit according to its rules.

Later I read
> Expressed in different units, the maximum allowable input value to five decimal places is...

Then `input value` should be a plural, because each unit will have its "maximal input value", and we have stopped referring to ` \c_max_dim` here.  It may be worthwile to make clear to  reader that the dimensions in this list are distinct except that dd, mm, cm share the same attainable dimension  (which is 1sp less than TeX max dimen).

I also feel the documentation of `\dim_to_decimal_in_unit:nn` does leave out too much to interpretation, but was the implementation actually modified in the merged PR (I did not re-check)?  It is still marked as dating back to 2014.  Perhaps it has not changed. (no time now)

Sorry for nitpicking but  you asked... generally speaking in the past when I was interacting with TeX users it appeared to me that the understanding of TeX dimensions was not precise enough, which has lead to confusion in some discussions, and it would be good for LaTeX3 reference manual to be as precise as possible and leave nothing to interpretation.

**Comment by josephwright** [comment]
> > Any further refinement needed?
> 
> Well I am uncertain about the TeXhackers note about `\dim_to_decimal_in_bp:n` which says
> 
> > The implementation of this functions is re-entrant: the result of `\dim_to_decimal_in_bp:n { <n>bp }`
> > will be the value ⟨n⟩.
> 
> It is not clear to me what `⟨n⟩` means but I skipped the earlier explanations. Maybe it is a decimal with up to four of five places?. But notice that `72.26998pt` and `72.26997pt` are the same TeX dimension so this is not true for `pt` unit. Ah here is for bp: notice that `71.99999bp` and `71.99998bp` are the same TeX dimension. So, but perhaps I misread, this sentence appears to say something wrong. Let me read it again for double-check. It seems I did read what I read.
> 
> I see a typo above: "functions" should be singular.
> 
> For me - re-entrant in this context means that `⟨n⟩ bp` and `\dim_to_decimal_in_bp:n { <n>bp } bp` are for TeX the same dimension, once parsed by it into an integer multiple of sp unit according to its rules.

I've adjusted again

**Comment by RuixiZhang42** [comment]
A few comments for `l3skip`:
- Lines 494 and 513: `... to four or five decimal` should be `... to at most five decimal`.
- Line 528: A `bp` is missing, should be `{ \dim_to_decimal_in_bp:n { <x>bp } bp }`.
- Line 557: should be plural `the maximum allowable input values to five decimal places are\\`.
- Lines 562 and 563: swap these two for alphabetical ordering of the &ldquo;bad&rdquo; units.
- Lines 572&ndash;578:
```latex
%   \begin{texnote}
%      The implementation of these functions is re-entrant: the result of
%      \begin{verbatim}
%        \dim_compare:nNnTF
%          { <x><unit> } =
%            { \dim_to_decimal_in_<unit>:n { <x><unit> } <unit> }
%      \end{verbatim}
%      will be logically \texttt{true}. The decimal representations may
%      differ provided they produce the same \TeX{} dimension.
%   \end{texnote}
```
- Line 590: Missing an `updated = 2023-05-20` for `\dim_to_decimal_in_unit:nn`.
- Line 609: I think the word `hence` is inappropriate here. May I suggest changing it to `for instance`?
- Lines 611&ndash;613:
```latex
%     \dim_compare:nNnTF
%       { 1bp } =
%         { \dim_to_decimal_in_unit:nn { 1bp } { 1mm } mm }
```
- Line 1760: typo `eeasy`.
- Add a line between 1831 and 1832, explaining that the support for `nd` and `nc` were dropped. This will do: `The units |nd| and |nc| are not available in XeTeX and (u)pTeX, so they are not supported by \pkg{expl3}.`
- I wrote ``` ``<quote>'' ``` in my original implementation. There are still 4 such instances that you may want to rewrite as `\enquote{<quote>}`.

**Comment by josephwright** [comment]
@jfbu  Hopefully the suggestions by @RuixiZhang42 address your concerns.

**Comment by jfbu** [comment]
> @jfbu Hopefully the suggestions by @RuixiZhang42 address your concerns.

Yes, they do appear to address the concerns I expressed and more... maybe I wll find a way to express more concerns in future, but that will prove harder...

**Comment by RuixiZhang42** [comment]
@josephwright The following sentence is missing a &ldquo;to&rdquo;:
https://github.com/latex3/latex3/blob/e92a0f05836167ddea8bd97e6c542e9b3168afd6/l3kernel/l3skip.dtx#L494
and also missing this one:
https://github.com/latex3/latex3/blob/e92a0f05836167ddea8bd97e6c542e9b3168afd6/l3kernel/l3skip.dtx#L513
`The result is rounded by \TeX{} to at most five decimal places.`
