### ISSUE TITLE
l3debug source code is not seen in any l3kernel docs

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1222]
Recent commits led me to the source file [`l3debug.dtx`](https://github.com/latex3/latex3/blob/main/l3kernel/l3debug.dtx). It provides `l3debug.def` which is loaded by `\sys_load_debug:`, which is now auto used by `\debug_on:n` and `\debug_off:n` starting from commit 1ec8adb (Integrate \sys_load_debug: into \debug_on: (fixes #<span></span>980), 2023-05-23).

The user commands provided (actually redefined) by `l3debug.def` is documented in `interface3.pdf` as a subsection under l3basics package. But source code of `l3debug.dtx` is neither part of `source3.pdf` nor in its own `l3debug.pdf`.

**Comment by josephwright** [comment]
Actually, probably do have time

**Comment by josephwright** [comment]
@muzimuzhi  Does the change I've pushed address this?

**Comment by muzimuzhi** [comment]
Yes.

Just one follow-up question: `l3debug` documents several internal functions in `documentation` environment, which doesn't seem to be the conversion here.  Looks like they should be moved to corresponding positions in `implementation` environment.
https://github.com/latex3/latex3/blob/50b07ee1d274e1e9071caf5e5cf166711774ac0b/l3kernel/l3debug.dtx#L50-L60
