### ISSUE TITLE
Extend handling of breathing marks when case changing Greek

### ISSUE THREAD

**Issue by josephwright** [latex3/latex3#1228]
As detailed in https://github.com/latex3/latex2e/issues/987#issuecomment-1570309342 and alluded to in https://unicode-org.atlassian.net/browse/ICU-12845#icft=ICU-12845, breathing marks need special treatment when case changing modern Greek. It seems the ICU reference implementation is lacking in this area, so the correct algorithm for upper casing is

- Examine the first grapheme after a word boundary
- If there is a breathing mark on a vowel followed by a grapheme which takes a diaeresis, case change the first grapheme with no breath mark, and case change the second to include a diaeresis
- Otherwise, if there is a breathing mark, case change and retain it

We already have code to handle the first grapheme, so this will be doable by extending the current approach.

**Comment by gmilde** [comment]
IMO, the ticket ICU-12845 cannot serve as a solid base for LaTeX's
upcasing mechanism:

ICU-12845 describes different rules for upcasing Greek words with breathings
but unfortunately without references/examples that underpin the claim that

> "ICU-5456 Uppercase formatting option results in accented capital letters -
> Invalid for Greek may have removed too many accents when uppercasing Greek.

The [Unicode FAQ](http://www.unicode.org/faq/greek.html#7) refers to a [detailed, scholarly analysis](https://opoudjis.net/unicode/unicode.html) by Nick Nicholas which conforms with the rules from ICU-5456 but not the "corrections" from ICU-12845

Some points:

* ICU-12845 does not cite the source of its examples.
  Where is a precedence case for the example ῥόδον → ῬΟΔΟΝ?
  Is it actually from a source that drops other diacritics in all-caps or taken from a source that follows the alternative typographical tradition of keeping diacritics?
  We know that

  > The behaviour of All Capitals in Greek has not always been the same: in
  > the Renaissance, and in the French typographical tradition up to the 19th
  > century, all capital words retained their diacritics, with accents over
  > the letter rather than to its left. Very occasionally a disambiguating
  > accent will appear in the all caps text of a comic strip or newspaper
  > headline. […]
  > -- https://opoudjis.net/unicode/unicode_gkbkgd.html#titlecase

* The example Πάτερ ἡμῶν ὁ ἐν τοῖς οὐρανοῖς → ΠΑΤΕΡ ἨΜΩΝ Ὁ ἘΝ ΤΟΙΣ ὈΥΡΑΝΟΙΣ
  contradicts the "results […] reviewed and approved by a Greek linguist"
  in https://icu.unicode.org/design/case/greek-upper:

  > Ἐπειδὴ ἡ ἀναγνώριση → ΕΠΕΙΔΗ Η ΑΝΑΓΝΩΡΙΣΗ

  Maybe this is why it put a question mark after "retain initial
  breathers?".

  It also introduces a new rule for capitalization of diphthongs (or
  contains an an error) when converting οὐρανοῖς → ὈΥΡΑΝΟΙΣ:

  According to the rule
  
  > The breathing is placed on the initial vowel, or on the second letter of
  > an initial diphthong. (In fact, whether the breathing goes on the first or
  > second of two vowels in a row is diagnostic of whether the two vowels
  > count as a single syllable or not.) 
  > -- https://opoudjis.net/unicode/unicode_gkbkgd.html#polytonic

  the conversion οὐρανοῖς → ὈΥΡΑΝΟΙΣ would add a syllable
  to the all-caps word: /uː.ra.nós/ → /o.u.ra.nós/

* ICU-12845 does not detail the handling of combined breathing + accent as in ἄνθρωπος. Traditional  behaviour in LaTeX drops both, as indicated in the following example (based on Yannis Haralambous ["From Unicode to Typography, a Case Study: the Greek Script", 1998.](https://hal.science/hal-02101618)).

  >  Greek differs from Latin in that it capitalises letters with diacritics differently, depending on whether the entire word is in capitals  (whereupon diacritics are eliminated), or the initial is capitalised only, as in the first word in a sentence or in a title (whereupon the diacritics are retained, although they appear to the left of the letter rather than above it.) 
  Thus, polytonic ἄνθρωπος capitalises to ΑΝΘΡΩΠΟΣ, but in titlecase to Ἄνθρωπος; monotonic άνθρωπος capitalises to ΑΝΘΡΩΠΟΣ and Άνθρωπος.
  -- Nick Nicholas https://opoudjis.net/unicode/unicode_gkbkgd.html#titlecase

  An exception is the polytonic spelling of the word "or": However the example in https://icu.unicode.org/design/case/greek-upper don't keep the breathing but the  accent (converting it from varia to oxia):
νομικοῦ ἢ διεθνοῦς → ΝΟΜΙΚΟΥ Ή ΔΙΕΘΝΟΥΣ.

The conversion ἀυπνία → ΑΫΠΝΙΑ makes only sense when we can agree to drop all breathings in all-caps.
The rationale is that the diaeresis is required for disambiguation (rsp. as a pronunciation hint) in absence of other markers of the hiatus (break up of a diphthong grapheme).
If LaTeX would (agaist previous praxis) follow ICU-12845 and go with a typograhical style that keeps breathings on all-caps, there would be no reason to make an extension for diphthongs.

**Comment by josephwright** [comment]
@gmilde  All understood. What's tricky for me is that the ICU comments suggest *something* is not right with handling of breathing marks, but the detail is clearly more complicated.

**Comment by josephwright** [comment]
@gmilde  OK, as I've got the code sorted I will make the change here just for the _dialytika_ aspect, and see if we get feedback.
