### ISSUE TITLE
Applied to a title, `\MakeTitlecase` does not what its name suggests.

### ISSUE THREAD

**Issue by gmilde** [latex3/latex3#1232]
The new `\MakeTitlecase` does what the "usrguide" says (if read carefully) but not what the name suggests.

According to the Wikipedia, in [titlecase](https://en.wikipedia.org/wiki/Title_case) "… all words are capitalized, except for minor words […]. There are different rules for which words are major, hence capitalized. As an example, a headline might be written like this: 'The Quick Brown Fox Jumps over the Lazy Dog'.

"In text processing, title case usually involves the capitalization of all words irrespective of their part of speech. This simplified variant of title case is also known as [start case](https://en.wikipedia.org/wiki/Letter_case#Case_styles) or initial caps."
For example in Python, the command `"Punch and Judy go to the cinema.".title()` results in `'Punch And Judy Go To The Cinema.'`.

In LaTeX, `\MakeTitlecase` produces what is also known as [Sentence case](https://en.wikipedia.org/wiki/Sentence_case). The text `\MakeTitlecase{Punch and Judy go to the cinema.}` is printed as
`Punch and judy go to the cinema.`.

(I stumbled across this testing `\CaseSwitch`, where to my surprise `\MakeTitlecase{This is \CaseSwitch{unchanged}{grEAT}{smALL}{speCIAL} text.}` prints `This is smALL text.`.)

**Comment by josephwright** [comment]
The language here is taken from Unicode: 'sentence case' and Python\wikipedia's use of 'titlecase' both have editorial/language elements that the Unicode version does not. Informally, Unicode titlecasing is converting the first grapheme to uppercase, then converting the remaining to lowercase. (It's more tricky than that, which is why there is a Unicode definition in the first place).

The point is that like \MakeUppercase`, `\MakeTitlecase` doesn't do any word splitting: it's about the input as a whole. Any more complex processing would be 'one level up'.

**Comment by gmilde** [comment]
The Unicode Standard defines titlecase in section  [Section 5.18, Case Mappings](https://www.unicode.org/versions/latest/ch05.pdf#G21180) the [FAQ](https://unicode.org/faq/casemap_charprop.html#4) and one in the [glossary](https://www.unicode.org/glossary/#titlecase). While Unicode mappings only work on a character level, the definition speaks of "the first letter of a _word_". The glossary points to its own use of Titlecase (with terms consisting of more than one word written as, e.g., [Case Mapping](https://www.unicode.org/glossary/#case_mapping).

I agree that the documentation is explicit that `\MakeTitleCase` turns only the first character of the _input_ to titlecase. However, the link to "the definition given by the Unicode Consortium" could become more helpful if
* moved to a footnote explaining the "broadly" in "(broadly) uppercase",
* accompagnied by a URL or hyperlink.

Suggestion:
~~~
|\MakeTitlecase| converts the first character of the input to (broadly) uppercase%
\footnote{see the \href{https://unicode.org/faq/casemap_charprop.html#4}{definition given by the Unicode Consortium}},
and the rest of the input to lowercase.
~~~

As-is, `\MakeTitlecase` cannot be used to, e.g., set titles in titlecase.
Given that LaTeX is a powerful typesetting engine with some knowledge of words (used in hyphenation) a "significant enhancement over the TEX primitives" would be a titlecasing function that includes the more complex processing. It is a pity, that the function name `MakeTitlecase` is now already spent for the lower level function.

Using `\MakeTitlecase` instead of `\makeuppercase` or `\MakeUppercase` in the definition of functions for "titlecase" in bibtex, biblatex and the like helps with cases like the serbian LJ ligature and Greek diacritics.

Searching for "latex MakeTitlecase" turns up
https://tex.stackexchange.com/questions/34796/capitalizing-strings-ignoring-closed-class-words
It seems not too difficult to implement word-level titlecasing.
I don't know the quality of  the [titlecaps](https://ctan.org/pkg/titlecaps) package but it may be worth a link or useful for inspiration.

The function `\MakeSentenceCase` seems to exist in biblatex https://tex.stackexchange.com/questions/22980/sentence-case-for-titles-in-biblatex.

**Comment by josephwright** [comment]
I've been thinking about loading the data needed to do proper word-boundary detection, which would then allow a word-by-word treatment in case changing. That would have some advantages (as the case part then doesn't need to deal with word boundaries in such a complex way), and would allow 'real' titlecasing.

I think that would likely be an acceptable change to a 2e command, as we could say it's fixing an issue. I'd need a bit of time to set it all up, but that would be doable for the Fall 2023 LaTeX2e cycle. Thoughts?

**Comment by josephwright** [comment]
I've looked at word boundary handling, and at least as a first step plan to go with the simpler 'just the spaces' approach: I think I can have that done very shortly.

**Comment by moewew** [comment]
It always struck me as odd that LaTeX's titlecase implemented my interpretation of sentence case.

At the moment, though, `biblatex`'s `\MakeSentenceCase` uses `text_titlecase` under the hood, so please give us a heads-up and ample time to prepare a fix if the behaviour of `text_titlecase` and friends is going to be changed (I'm not sure if that is the current plan here. Initially I didn't think it would be. But I'm not sure how to understand the comment "I think that would likely be an acceptable change to a 2e command, as we could say it's fixing an issue.")

That said, I'd warmly welcome an implementation of an actual title-casing macro (I presume it would have to allow for user customisation as to which words count as "minor words" and possibly some ad-hoc modification).

**Comment by josephwright** [comment]
@moewew  Notes. Keeping the current behaviour in a new name is pretty trivial if I can pull of my current plan: it might need a bit of refinement over time.

**Comment by josephwright** [comment]
Current plan is I see what's workable and then we discuss it :)

**Comment by josephwright** [comment]
I almost have a fix in hand here: later today I suspect. My suggestion is

- Document that at present only spaces and groups are treated as word boundaries, but that is likely to be refined over time
- Adjust `\text_titlecase:n(n)` to act on a per-word basis 
- Introduce `\text_sentencecase:n(n)` to do what current `\text_titlecase:n(n)` does
- Document that refinement to `\text_sentencecase:n(n)` is likely over time

Thoughts?

**Comment by FrankMittelbach** [comment]
> * Document that refinement to `\text_sentencecase:n(n)` is likely over time

what would be the likely refinement here?

**Comment by josephwright** [comment]
> > * Document that refinement to `\text_sentencecase:n(n)` is likely over time
> 
> what would be the likely refinement here?

For 'sentence' case, it's about what counts as the start of a sentence. As @moewew points out, there's also the question with 'title' case of 'ignored' words, which probably then links to word boundary detection.

**Comment by josephwright** [comment]
Looking at that again, I realise that I'm better using a different tack to fix the issue than I originally imagined. It's pretty easy to re-work the code to do an 'outer' loop that splits at spaces, then we have 'words' which can be handled one-at-a-time. Providing titlecase exceptions is then easy, and all I have to arrange is that sentence case does different things for the first word to other words.

Still should have a PR sorted this week.

**Comment by moewew** [comment]
Sounds sensible.

As I said, we currently use `\text_titlecase:n` for sentence case in `biblatex`, so once the interface is fixed please give us some time to prepare a new release (we will probably also need to release Biber, so this might be a few weeks) before you send off the new version to CTAN.

**Comment by josephwright** [comment]
@moewew  My current plan is to get a PR sorted, mark as draft to prevent a mess up, then see what everyone thinks (To be fair, it's always me doing the merges, but ...)

**Comment by josephwright** [comment]
@gmilde Take a look at the PR? I hope this addresses things

**Comment by samuelsaari** [comment]
Is this implemented yet? Which command should I use?

**Comment by josephwright** [comment]
> Is this implemented yet? Which command should I use?

Yes, as noted it was implemented over a year ago: `\text_titlecase_all:nn` at the code level - we are going to make some changes to `\MakeTitlecase` for the 2025-06-01 LaTeX release, these are already in the `dev` code which went to CTAN yesterday.
