### ISSUE TITLE
Cannot use xelatex after updating texlive

### ISSUE THREAD

**Issue by ACGNnsj** [latex3/latex3#1233]
The error is 'Mismatched LaTeX support files detected. \ExplLoaderFileDate{expl3.sty}}'.
I tried to regenerate 'xelatex.fmt' by 'fmtutil-sys --all' and 'mktexfmt xelatex', but both of them didn't work.
The 'xelatex.fmt' file in TEXMFSYSVAR is still the old one.

**Comment by u-fischer** [comment]
typically this means that there is another format somewhere. Run

~~~~
kpsewhich --all --engine=xetex xelatex.fmt
~~~~

to get a list of the locations where you have formats.

**Comment by ACGNnsj** [comment]
Quite strange that this command cannot find 'xelatex.fmt' now, although it still lies in TEXMFSYSVAR.
```ps1
kpsewhich --all --engine=xetex xelatex.fmt
NativeCommandExitException: Program "kpsewhich.exe" ended with non-zero exit code: 1.
```

**Comment by u-fischer** [comment]
works fine for me (in windows, both in cmd and powershell) and I just updated texlive.  But if kpsewhich is broken you should write to the texlive mailing list. That is not a latex issue.

**Comment by ACGNnsj** [comment]
Thank anyway. I finally resolved this by 'tlmgr install —reinstall xetex'.
