### ISSUE TITLE
l3fp: taking abs of tuple blows up badly

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#1238]
In `l3fp` code, an invalid operation like `\fp_show:n { abs((1,2)) }`, which attempts to take the absolute value of a tuple, should produce an error and then evaluate to `nan`.  However, for `abs` (and not `sin`, for instance) the initial error is produced but the error recovery is completely wrong.

**Comment by muzimuzhi** [comment]
Need a changelog entry? Note the fix for this issue is already released in https://github.com/latex3/latex3/releases/tag/2023-06-30.
