### ISSUE TITLE
\DeclareUppercaseMapping - inconsistent behavior

### ISSUE THREAD

**Issue by jbezos** [latex3/latex3#1239]
Some languages may require in some contexts a specific tag with an `x` extension, for several reasons. However, if I set the locale in `\DeclareUppercaseMapping`, the mapping is not always recognized.
```tex
\documentclass{article}

\DeclareUppercaseMapping[la-x-medieval]{`c}{X}
\DeclareUppercaseMapping[la-x-new]{`c}{X}

\begin{document}

\def\BCPdata#1{la-x-medieval}

\MakeUppercase{cu} (ok, it prints XV)

\def\BCPdata#1{la-x-new}

\MakeUppercase{cu} (must be XU, but prints CU)

\end{document}
```
I wonder if the fact `la-x-medieval` has some predefined values is relevant here, but I think the behavior has to be consistent.

**Comment by josephwright** [comment]
I see where the issue is, and it does related to what is pre-declared. I'll need to think a bit about a solution.

**Comment by josephwright** [comment]
aken a look and before making any changes I think we need to be clear on what the expectation is for a range of scenarios. The current code is designed around the pre-declared case-changing excpetions, and therefore has basically three possible outcomes in terms of BCP47 code

- It receives a known `x` one and uses that, e.g. `la-x-medieval`
- It receives a BCP47 code starting with a known language, and it uses that, e.g. `el-GR` uses `el`
- It receives an unknown code, and passes all of the code bar any trailing `x`, e.g. `la-x-new` uses `la`

This is all done at the start of the routine, the idea being that we don't want to decompose the BCP47 string for each letter, we just want to do it once. When I wrote that code, there were only the pre-defined exceptions to worry about, so the fact it had some limitations made sense. But that doesn't really work so well once you have user-defined exceptions too.

There are various possible approaches, and I welcome thoughts on what should happen.

**Comment by jbezos** [comment]
I wonder if a certain combination can be made ‘known’ somehow, so that it’s up to `\BCPdada{casing}` returning only valid known tags. In other words, if the only known combination for Ancient Greek is `grc`, then `\BCPdata{casing}` returns always `grc`, even if the actual tag is, say, `grc-Grek-und-x-ionic`.

**Comment by jbezos** [comment]
No fix yet?

**Comment by josephwright** [comment]
@jbezos  I'm going to raise with team as a whole

**Comment by josephwright** [comment]
I think I have a plan - perhaps early next week.

**Comment by josephwright** [comment]
@jbezos  Now fixed: will be sorted in next `expl3` release

**Comment by jbezos** [comment]
👍 I’ll test it.
