### ISSUE TITLE
\peek_analysis_map_inline does not work with active character token = implicit param character

### ISSUE THREAD

**Issue by user202729** [latex3/latex3#1241]
Edit: actually it seems this is fixed in a relatively new version.

--

```tex
\ExplSyntaxOn
\catcode `?\active
\let ? #
\peek_analysis_map_inline:n{\peek_analysis_map_break:}?
\stop
```

Error message:

```
! Illegal parameter number in definition of \__tl_tmp:w.
<to be read again> 
                   }
l.4 \peek_analysis_map_inline:n{\peek_analysis_map_break:}?
                                                           
? 
```

**Comment by josephwright** [comment]
Dupe of https://github.com/latex3/latex3/issues/1109 I think

**Comment by user202729** [comment]
This is slightly different (for one, the error message is different), but the version I'm having on my machine is not the newest version either, so this may be something fixed in newest version (looks like the relevant parts of code has been changed).

**Comment by muzimuzhi** [comment]
> so this may be something fixed in newest version (looks like the relevant parts of code has been changed).

I can confirm the problem reported in current issue doesn't reproduce with l3kernel 2023-06-30.
