### ISSUE TITLE
\tl_analysis: (feature request/performance) Avoid polluting the hash table by only disable active character

### ISSUE THREAD

**Issue by user202729** [latex3/latex3#1243]
As mentioned in https://github.com/latex3/latex3/issues/938 , the implementation of \tl_analysis and \peek_analysis function pollutes the hash table in some Unicode engine implementation by explicitly setting the active character to undefined.

While that handling of begin-group character and end-group character is very hard to avoid, the case of the token being "safe" should be easy to handle (in fact it's already handled in peek_analysis, just not in tl_analysis).

https://github.com/latex3/latex3/blob/170ab28ab51f2c908372682f15949f372dd82a08/l3kernel/l3tl-analysis.dtx#L740

Here I believe it's only necessary to disable the active character if `#1` itself is an active token. To check it the `\lowercase` trick in the peek_analysis case can be used (lowercase `#1` itself and check if the result has meaning = undefined)

So something like ``<special handle pTeX where `#1 ≥ 256> ; \lccode `#1=32 \lowercase{\ifx #1}\undefined \aux \fi \use_none:n #1`` with `\def aux \fi \use_none:n #1 {\fi \let #1 \undefined}`. Not sure about the performance (seems to be roughly the same, `\lccode+\lowercase+\let` with the `\let` omitted if the character is not active, might be faster)

**Comment by blefloch** [comment]
I did basically what you suggested, thanks!  Does this mean that the hash table problem is completely done, so I can remove the comment on lines 180-181?
```
% ^^A todo: ask LuaTeX list for an \ifx\undefined <active char>
% ^^A which does not add the <active char> in memory.
```

**Comment by user202729** [comment]
It's been a long time I can't really remember what's going on, but if I recalled correctly the handling of begin-group character and end-group character still use up the hash table entry...

That issue is most likely minor though. (since it's likely the only possible char code is `{` and `}`)
