### ISSUE TITLE
missing luatex and ptex primitives from l3names.dtx

### ISSUE THREAD

**Issue by mbertucci47** [latex3/latex3#1248]
After seeing #1245 I decided to check if [`l3names.dtx`](https://github.com/latex3/latex3/blob/main/l3kernel/l3names.dtx) was missing any other primitives in the expl3 `\tex_<name>:D` form. From luatex I found it's missing
```tex
\boundary
\compoundhyphenmode
\deferred
\eTeXVersion % distinct from \eTeXversion
\eTeXminorversion
\exhyphenchar
\fixupboxesmode
\glet
\glyphdimensionsmode
\gtoksapp
\gtokspre
\mathflattenmode
\mathitalicsmode
\mathrulesmode
\mathrulethicknessmode
\protrusionboundary
\Uleft
\Umiddle
\Uright
\variablefam
\wordboundary
\xtoksapp
\xtokspre
```
and from ptex,
```tex
\ptexfontname
\ptextracingfonts
\tojis
```
I have no idea if `l3names.dtx` is attempting to have the complete list of available primitives. For example, I can see reasons for not having `\tex_glet:D`. If any or all of the list above should be added, I'm happy to make a PR (or leave it to y'all if that's easier).

**Comment by josephwright** [comment]
Broadly we aim for the full set of primitives, but there are a small number that are missed out as e.g. they are deprecated. `\eTeXVersion` would be a 'no' as it doesn't match anything for e-TeX itself, so it's not 'right', same for `\eTeXminorversion` (I think these are 'LuaTeX-like' versions of real eTeX primitives.)

From memory, last time we did a sweep `\xtoksapp`, etc., were experimental so we skipped them: a check on the status will be needed before adding them.

Happy to accept a PR.
