### ISSUE TITLE
Document that TeX ignores ~ at the start of a line

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#125]
We should mention in the `expl3` documentation that spaces `~` are ignored at the start of a line, but not at the end of a line.  Thus,

```
\tl_show:n { ~
  }
\tl_show:n {
  ~ }
```

show a space, then nothing. [Kids, don't imitate this crazy indentation style at home!]  In particular, this comes up when defining messages, where spaces should be put at the end of the line, not the start (well, `\` also works in the case of messages).

**Comment by josephwright** [comment]
As with https://github.com/latex3/svn-mirror/issues/46, a future item
