### ISSUE TITLE
expl3 documentation bugs

### ISSUE THREAD

**Issue by cdonovick** [latex3/latex3#1252]
In section 3.2 (Formal naming syntax) of the expl3 documentation (expl3.pdf retrieved from https://ctan.org/pkg/l3kernel?lang=en, I don't know where in the source this  document is located), their are some "bugs" in the specification of private variables and functions.

First the naming syntax is defined as:

```
    \<module>_<description>:<arg-spec>
    \<scope>_<module>_<description>_<type>
```

Next in 3.2.1 we have the following statements:

> To allow clear separation of these two cases, the following convention is used. Private functions should be defined with \_\_ added to the beginning of the module name. Thus
> ```
>     \module_foo:nnn
> ```
> is a public function which should be documented while
> ```
>     \__module_foo:nnn
> ```
> is private to the module, and should not be used outside of that module. **In the same way**, private variables should use **two \_\_** at the start of the module name, such that
> ```
>     \l_module_foo_tl
> ```
> is a public variable and
> ```
>    \l__module_foo_tl
> ```
> is private.

First, private variables do not use two \_\_ they use two \_ (i.e. one \_\_).  

Second, the access specifiers (public/private) for variables and function are not specified in the same way. Only one \_ is added module name in the case of variables. The second \_ is the separator between `<scope>` and `<module>`. 

It would be more precise to say in something along the lines of: 

> Private variables should use \_\_ instead of  \_, to separate `<scope>` and `<module>`, such that  
> ```
>     \l_module_foo_tl
> ```
> is a public variable and
> ```
>    \l__module_foo_tl
> ```
> is private.

Finally, I think it would be appropriate to include the access specifier in the syntax.  E.g.:

```
<function name> := \<private function name> 
                 | \<public function name>
<private function name> := __<module>_<description>:<arg-spec>
<public function name> := <module>_<description>:<arg-spec>

<variable name> := \<private variable name> 
                 | \<public variable name>
<private variable name> := <scope>__<module>_<description>_<type>
<public variable name> := <scope>_<module>_<description>_<type>
```

**Comment by josephwright** [comment]
I think perhaps the fact that we have an 'elided' `_` in the variable case is perhaps hiding the pattern that the team hope is clear: if the module name is preceded by two `_` characters, the entity referred to is private. That's true for both functions and variables. I'll see if other feel that is a reasonable way to express things before making any changes (I see that @muzimuzhi has already addressed one part for us).

**Comment by cdonovick** [comment]
The pattern is clear from the examples, but the language used to describe this pattern is imprecise. As someone with a background in programming languages, I expect a bit more rigor from a section titled "Formal naming syntax".  If the section was, for example, labeled "Naming conventions", I would be less pedantic in my comments.

**Comment by pablgonz** [comment]
Hello, I think that these lines of the documentation should be updated (taking advantage of this request):

https://github.com/muzimuzhi/latex3/blob/fedd9a9de989bf4a4156e1dae5e3f0f677520fa7/l3kernel/expl3.dtx#L337

and

https://github.com/muzimuzhi/latex3/blob/fedd9a9de989bf4a4156e1dae5e3f0f677520fa7/l3kernel/expl3.dtx#L857

**Comment by pablgonz** [comment]
@josephwright ` \tn{@ifpackageloaded}`

**Comment by pablgonz** [comment]
@josephwright From `ltnew34` 

```
\IfPackageLoadedTF {⟨package⟩} {⟨true⟩}{⟨false⟩}
```

**Comment by josephwright** [comment]
@cdonovick  I've re-worked the text here to try to be more precise on how this works, e.g. that private interfaces are always `__<module>` but that to avoid three `_` in a row we combine with the separator part for variables.

**Comment by car222222** [comment]
The new text is a much better description and justification, but it is probably still insufficiently formal for this section.

**Comment by cdonovick** [comment]
I think it is much improved.   Although, I  agree with car and think it is formally inaccurate.  The statement "In private [...] variables, two `_` characters are added to the start of the module name." remains false. 

In my mind, the best way to avoid ambiguity would be to add the access specifiers to the grammar.  With the access specifiers in the grammar we need not worry too much about the wording that describes it.  The grammar can act as the formal description, and the prose can explain the grammar to humans.

**Comment by cdonovick** [comment]
I realize the resulting grammar is not totally elegant; it would be nice to be able to factor the access specifier into a single grammatical element e.g.
 ```
<function name> := \<access modifier><module>_<description>:<arg-spec>
<variable name> := \<scope>_<access modifier><module>_<description>_<type>
    
<access modifer> := <public> | <private>
<private> := __
<public> := \epsilon
```

However, design decisions were made for human reasons which is entirely reasonable (three `_` would be ugly), but makes such a factorization impossible.  This unfortunately means that some verbosity is called for either in the grammar or in the prose.

**Comment by FrankMittelbach** [comment]
> I think it is much improved. Although, I agree with car and think it is formally inaccurate. The statement "In private [...] variables, two `_` characters are added to the start of the module name." remains false.

One could say something like:  "To denote a private function or a private variable (of the module) two _ characters are used in front of the module name, e.g., ... examples..."

**Comment by josephwright** [comment]
Looking back, we seem to have done this: I'll close.
