### ISSUE TITLE
l3doc: Too narrow syntax block caused by long variant list(s)

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1258]
`texdoc interface3` 2023-06-30, on page 208,
![image](https://github.com/latex3/latex3/assets/6376638/a3621078-bf55-4893-ae13-4605c2602fab)

Excerpted example
```tex
\documentclass{l3doc}
\begin{document}

\begin{function}[updated = 2012-07-09]
  {
    \prop_put:Nnn,  \prop_put:NnV,  \prop_put:Nno,  \prop_put:Nne, \prop_put:Nnx,
    \prop_put:NVn,  \prop_put:NVV,  \prop_put:NVx,  \prop_put:Nvx,
    \prop_put:Non,  \prop_put:Noo,  \prop_put:Nxx,
    \prop_put:cnn,  \prop_put:cnV,  \prop_put:cno,  \prop_put:cne, \prop_put:cnx,
    \prop_put:cVn,  \prop_put:cVV,  \prop_put:cVx,  \prop_put:cvx,
    \prop_put:con,  \prop_put:coo,  \prop_put:cxx,
    \prop_gput:Nnn, \prop_gput:NnV, \prop_gput:Nno, \prop_gput:Nne, \prop_gput:Nnx,
    \prop_gput:NVn, \prop_gput:NVV, \prop_gput:NVx, \prop_gput:Nvx,
    \prop_gput:Non, \prop_gput:Noo, \prop_gput:Nxx,
    \prop_gput:cnn, \prop_gput:cnV, \prop_gput:cno, \prop_gput:cne, \prop_gput:cnx,
    \prop_gput:cVn, \prop_gput:cVV, \prop_gput:cVx, \prop_gput:cvx,
    \prop_gput:con, \prop_gput:coo, \prop_gput:cxx
  }
  \begin{syntax}
    \cs{prop_put:Nnn} \meta{property list} \Arg{key} \Arg{value}
  \end{syntax}
  Adds an entry to the \meta{property list} which may be accessed
  using the \meta{key} and which has \meta{value}. If the \meta{key}
  is already present in the \meta{property list}, the existing entry
  is overwritten by the new \meta{value}. Both the \meta{key} and
  \meta{value} may contain any \meta{balanced text}. The \meta{key} is
  stored after processing with \cs{tl_to_str:n}, meaning that category
  codes are ignored.
\end{function}

\end{document}
```

One simple solution is to typeset syntax block in a new paragraph, when the space for it is narrow enough.  If possible, variant list(s) could be typeset smarter, like
```
\prop_put:Nnn
\prop_put:(NnV|Nno|...) % all variants starting with N
\prop_put:(cnV|cno|...) % all variants starting with c
```

**Comment by davidcarlisle** [comment]
Something like this?

```
\cs_new_protected:Npn \__codedoc_typeset_variant_list:nN #1#2
  {
    \\
    \__codedoc_typeset_aux:n { \__codedoc_get_function_name:n {#1} }
    :
    \int_compare:nTF { \seq_count:N \g__codedoc_variants_seq == 1 }
      { \seq_use:Nn \g__codedoc_variants_seq { } }
      {
        \parbox[t]{.4\columnwidth}{\raggedright\textrm(
          \seq_use:Nn \g__codedoc_variants_seq { \textrm|\nolinebreak[2]}
        \textrm)
        \par
        \ifnum\prevgraf=1
        \setbox0\lastbox
        \nointerlineskip
        \hbox{\unhbox0\unskip\unskip}
        \fi}
      }
    \bool_if:NT #2 { \__codedoc_typeset_TF: }
    \__codedoc_typeset_expandability:
  }
```

![image](https://github.com/latex3/latex3/assets/1268738/23f1f998-47a4-47ed-b0dc-de329cdc9790)

**Comment by FrankMittelbach** [comment]
looks fine to me (perhaps with a bit more L3 layer style in the coding sinse the rest is in expl3)

**Comment by davidcarlisle** [comment]
On Tue, 8 Aug 2023 at 09:29, Frank Mittelbach ***@***.***>
wrote:

>  a bit more L3 layer style in the coding sinse the rest is in expl3)
>
> —
>

I thought someone might say that:-)
yes at  least the numeric test should be l3. it may as well be a 2e \parbox
I think as it's all basically a 2e tabular if I read the code right.
David

**Comment by dbitouze** [comment]
> Something like this?
> 
> [...]
> 
> ![image](https://user-images.githubusercontent.com/1268738/259033137-23f1f998-47a4-47ed-b0dc-de329cdc9790.png)

Having the `|` vertically aligned would be easier to read.

**Comment by davidcarlisle** [comment]
> Having the | vertically aligned would be easier to read.
Yes, I was going to move the `(` outside the parbox so it wraps ionside the box then as its monospace and in almost? all cases there will be the same number of arguments in the signature (ie all 3 here) things will line up

![image](https://github.com/latex3/latex3/assets/1268738/c815b5be-4060-4479-a401-57f7e0947b29)

**Comment by josephwright** [comment]
Looks good to me: @davidcarlisle you going to make the change?

**Comment by davidcarlisle** [comment]
Yes I'll make a PR if I get a moment
