### ISSUE TITLE
Adding \MakeUppercase to sectional macros give an error

### ISSUE THREAD

**Issue by daleif** [latex3/latex3#1260]
If one ends a sectional styling by \MakeUppercase then the current kernel crash

```
\documentclass[a4paper]{article}
\begin{document}
\makeatletter
\newcommand\Test{\@startsection {section}{1}{\z@}%
{-3.5ex \@plus -1ex \@minus -.2ex}%
{2.3ex \@plus.2ex}%
{\normalfont\Large\bfseries\MakeUppercase}}
\makeatother
\Test{ABC}
\end{document}
```

Error:

```
Bad character code (10000).
\char_value_catcode:n ..._eval:n {#1}\exp_stop_f: 
                                                  
l.10 \Test{ABC}
```

**Comment by josephwright** [comment]
Should be sorted by c1c24f9944ead998b15178f5f418269f5ea2d38c, at the cost that we can't case change implicit chars at all :(

**Comment by josephwright** [comment]
@daleif Working again now?

**Comment by josephwright** [comment]
@zauguin  The issue is that something like `\setbox \@tempboxa ...` has an implicit char, so if that is 'fed' to the case code, and we try to case change implicit chars, things go wrong. I wonder about looking for `\setbox` in input and handling specially.

**Comment by davidcarlisle** [comment]
@josephwright  I wonder how much relies on box allocations being \chardef rather than say \mathchardef (which we already use in luatex for large enough allocations)

**Comment by daleif** [comment]
Your update before your vacation seemed to work just fine. I got no more errors.
