### ISSUE TITLE
Doc: typo in Chapter 60 (l3token implementation)

### ISSUE THREAD

**Issue by RadioNoiseE** [latex3/latex3#1261]
There's a
```tex
%    \end{macrocode}
```
missing on page 870 (l3token implementation, chap. 60)
![image](https://github.com/latex3/latex3/assets/86350742/a78c41f0-b92c-4bf0-b769-db5483b22e6f)

**Comment by zepinglee** [comment]
@RadioNoiseE Just curious. Did you print out the whole `source3.pdf`?

**Comment by RadioNoiseE** [comment]
(Yes, for taking it to school)
