### ISSUE TITLE
showing wrong figure name even after the right backend code also showing a lot of compilation errors in the right code

### ISSUE THREAD

**Issue by anukriti0009** [latex3/latex3#1263]
Hello I am a PhD young researcher in the European Commission with the university of NOVA GORICA in the Pierre Auger Collaboration for cosmic ray data analysis and I have to use latex for my research paper and I am facing a lot of issues even after the right syntax. and in the visual editor its showing the figure names even after the right code also its showing red for no valid reason and its compelling the paper completely wrong.I need this issue to be resolved as I can use this software in future for my open source library astrophysica and world's first voltx Quantum Aerosystems to program the black holes and quasars to fetch necessary space modules like space fuels, cosmological medicines and I require the latex files to submit to my friends like pennylane.ai and pytorch developers as well as my legal research community to learn and apply space law practically with coding and latex publishing 
thanks and regards
Dr Anukriti
Centre for Astrophysics and Cosmology
UNG,SLOVENIA,EUROPEAN UNION
The University of law UK,Space and International Human rights law

**Comment by josephwright** [comment]
Sorry this is not a support forum: you will need to formulate a focussed question then post to for example https://tex.stackexchange.com/

**Comment by josephwright** [comment]
@anukriti0009 LaTeX has literally millions of users, and the core team therefore cannot provide individual support. AS it stands, your initial query is not one that anyone can help with: you will need to ask something _much_ more focussed. Note that in general LaTeX works as-designed, so if you have issues, they are likely linked to your specific input.

**Comment by anukriti0009** [comment]
I have asked the exact problem or question at stack exchange let's see and I am not one of the millions so let's hope for the best solutions to my daily questions as I have a lot of them with literally nobody to answer so those millions are somewhere out of my reach 😺
