### ISSUE TITLE
Problem with \fp_eval:n

### ISSUE THREAD

**Issue by F-Matthias** [latex3/latex3#1264]
## Brief outline of the bug

\fp_eval:n gives an error with certain computations.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\begin{document}
\ExplSyntaxOn
\fp_eval:n
  {
    0.8 / 10.00000000009%does not work
    %8 / 10.00000000009%does not work
    %80 / 10.00000000009%does not work
    %800 / 10.00000000009%does not work
    %8 / 10.000000000099%works
  }
\ExplSyntaxOff
\end{document}
```

## Log file (required) and possibly PDF file  

[bug.log](https://github.com/latex3/latex2e/files/12579608/bug.log)

**Comment by josephwright** [comment]
@muzimuzhi Thanks for tracking that down: I'd started last night but had not found that specific function.

**Comment by muzimuzhi** [comment]
With the help of `unravel` package, I compared full logs of `\unravel{\fp_eval:n { 8 / 10.0000000009 }}` (10+9e-11, doesn't work) and `\unravel{\fp_eval:n { 8 / 10.000000009 }}` (10+9e-10, works).

By finding the birth of problematic input `;+0` in the reversed order, `\__fp_div_significand_v:NN` was uncovered with not too high effort at step 1842 for 10+9e-11 case and step 1820 for 10+9e-10 case, respectively. (It did take me some time to choose the appropriate control group and to understand sources of different internal intermediate representations.)

```tex
\documentclass{article}

  \usepackage{unravel}
  \unravelsetup{max-action=1000, max-input=1000, max-output=1000}
  \long\def\beginunravel#1\endunravel{\unravel{#1}}
  \def\endunravel{}

\begin{document}
\ExplSyntaxOn

\beginunravel
\fp_eval:n { 8 / 10.00000000009 }
\endunravel
\par

% \beginunravel
% \fp_eval:n { 8 / 10.0000000009 }
% \endunravel
% \par

\ExplSyntaxOff
\end{document}
```

**Comment by josephwright** [comment]
I'm not sure there is a fix for `\__fp_div_significand_iv:wwnnnnnnn` as I don't think you can avoid the outcome being a zero; I will likely write a faster version of the patch (I have to try a few things). Of course, if Bruno has a better idea at some point ...

**Comment by muzimuzhi** [comment]
I think I was thinking about "doubling the single-digit zero before `\__fp_div_significand_v:NN` gets expanded" at that time.

**Comment by josephwright** [comment]
@blefloch I wonder if you have any time to see if there is a better fix than the one suggested? I don't see one, but you are the master of these things.

**Comment by blefloch** [comment]
@josephwright That sounds pretty bad and hard to fix.  I will try to look.  Wednesday at best.

**Comment by blefloch** [comment]
Actually `\@@_div_significand_iv:wwnnnnnnn` is often wrong.  It receives an integer 0≤P≤35, a 17-digit remainder E, and the 16-digit divisor Z.  Its goal is to figure out the sign of 2E-PZ.  The calculation in `\@@_div_significand_iv:wwnnnnnnn` is quite wrong: for instance  the `200000 + 2*#5 - #1*#9` part of the code is meant to compute the lowest digits of 2E-PZ, shifted by 200000 to try and ensure that it consists of 6 digits and that we correctly pick up the coefficient of 10000 when the `_v:NN` auxiliary picks up two digits.  But `#1` is P and `#9` is the last four digits of the divisor, and that can reach 349965.  Probably changing 200000 by 500000 and correspondingly 199980 by 499950 and 20 by 50 in this function would fix it.  It would be good to find a case where rounding gets messed up by this mistake.

**Comment by blefloch** [comment]
It would be helpful if someone could confirm that 8000000854999998 / 1000000099999999, correctly rounded to 16 digits, should give 8.000000055000001, whereas current l3fp gives 8.000000055.  I'll commit a fix and that test shortly.

**Comment by blefloch** [comment]
For the record, the code could
- blow up whenever the result of `200000+2*#5-#1*#9` would be a single digit, which can only happen if P≥21, which requires the divisor to be between 0.1 and 0.17 and some further fine-tuning, overall happening for less than 1/20000 of inputs, or
- give wrong result in rare cases where the remainder 2E-PZ is very small, which seems to occur around one in every billion inputs at most since it requires the `-20 + 2*#2#3 - #1*#6#7 + ...` portion of the code to give something close enough to zero to be affected by the wrong code computing subleading corrections.

**Comment by FrankMittelbach** [comment]
For the record: the are people paying money for lottery tickets with worse chances ;-)

**Comment by car222222** [comment]
But those people at least get to know about the (extremely unlikely) event when they do win!

Rather than just having to sort out a puzzling, and probably deeply buried, mess down the road:-(.

**Comment by blefloch** [comment]
Just to make sure that my previous comments were clear: the bug is gone.  I was just analyzing when it used to occur, and whether it was likely that it had led to wrong results in some documents.  So it's more like cancelling the lottery.

**Comment by F-Matthias** [comment]
> It would be helpful if someone could confirm that 8000000854999998 / 1000000099999999, correctly rounded to 16 digits, should give 8.000000055000001, whereas current l3fp gives 8.000000055. I'll commit a fix and that test shortly.

I can confirm that this is correct. The new release successfully fixes this bug.

**Comment by FrankMittelbach** [comment]
> Just to make sure that my previous comments were clear: the bug is gone. I was just analyzing when it used to occur, and whether it was likely that it had led to wrong results in some documents. So it's more like cancelling the lottery.

and I was just trying to be funny when making my comment (and I see one person reacted with a LOL emoji)
