### ISSUE TITLE
l3benchmark: `\int_gincr:N \g_tmpa_int` took too long in GitHub Actions

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1289]
In four days, CI failed twice on the same l3benchmark test, the first test case in `m3benchmark001.lvt`:
https://github.com/latex3/latex3/blob/15b5556f41276225b19c697724ea8041ee63d637/l3experimental/l3benchmark/testfiles/m3benchmark001.lvt#L41-L49

Here `\int_gincr:N \g_tmpa_int` is expected to take less than `5e-5` seconds (see line 46), but it indeed took longer on GitHub Actions' ubuntu-20.04 runner image:
- `\g_benchmark_time_fp=9.1552734375e-5` (almost 1 times slower) in run https://github.com/latex3/latex3/actions/runs/6546492081/job/17777056391#step:5:703 and
- `\g_benchmark_time_fp=3.204345703125e-4` (5 times slower) in run https://github.com/latex3/latex3/actions/runs/6585419096/job/17891777531#step:5:712

Unlike #1274, this time the test took longer on GitHub Actions' runner than expected, hence is hard to reproduce locally. Testing on my PC with pdflatex, it took `0 seconds (0 ops)` most of the time (80%+), and for the rest cases `1.53e-5 seconds (x ops)` where x is in range [60, 69], and mostly in range [64, 65].

```tex
\documentclass{article}
\usepackage{l3benchmark}

\begin{document}
content

\ExplSyntaxOn
\int_gzero:N \g_tmpa_int
\benchmark_once:n { \int_gincr:N \g_tmpa_int }
\int_log:N \g_tmpa_int    % Check the code was done only once
\fp_compare:nTF { \g_benchmark_time_fp < 5e-5 }  % Check it took 0 to 3 scaled seconds
  {  }
  { \ERROR \fp_show:N \g_benchmark_time_fp \fp_show:N \g_benchmark_ops_fp }
\fp_compare:nTF { \g_benchmark_time_fp > 0 }
  { \ERROR }
  {  }
\ExplSyntaxOff
\end{document}
```

Maybe testing for `\g_benchmark_ops_fp` is more stable, since the time took for one operation (currently `\int_gadd:Nn \g__benchmark_duration_int { 0 }`) is evaluated every time.

I suggest to first add `\fp_show:N \g_benchmark_ops_fp` to the false branch of `\fp_compare:nTF` (line 48 in the snippet), then wait for the next slow run.

**Comment by josephwright** [comment]
I personally would drop this test, as we can't have a predictable outcome.

**Comment by muzimuzhi** [comment]
We can't even assume that in the same LaTeX run and in near context, `\int_gincr:N \g_tmpa_int`  (the one used in `m3benchmark001.lvt`) would take about the same time as `\int_gadd:Nn \g__benchmark_duration_int { 0 }` (the one used to compute per-operation time), at least not 10x longer?

**Comment by muzimuzhi** [comment]
https://github.com/latex3/latex3/commit/b455c4b0fcd16c575fd2dddd97cc7e5f53009fd0 Dropped the whole `m3benchmark001.lvt` which consists of 3 tests.

Maybe the last two tests, or just the last one, can be restored. The last one actually tests `\benchmark_tic: ... \benchmark_toc:` functionality with an artificial time duration (1.2s), thus is totally deterministic.

**Comment by muzimuzhi** [comment]
> this entire test file has been the bane of my life ...

Including the second test (for `\benchmark:n`) in it?
