### ISSUE TITLE
immmediate help while i am doing presentation for now...

### ISSUE THREAD

**Issue by anukriti0009** [latex3/latex3#1294]
my file..https://www.overleaf.com/project/64fa51d0874f60ba283eb8d8
is suddenly gone when i am about to publish my paper with vandana mam...and sergeui vorobyev..with prof samo stanic and shobha man to present my paper with eic accelerator and start up indian i hace creatyed the fork of latex.into my astrophysila to improve and buikd upon the circuits ...so i have collaborated on stackoverechange .....so..please help me with ..with fixing the issue...i ahve to sharde the paper with peennylane too...hel,p me..

**Comment by anukriti0009** [comment]
help me...fix this...help me....helop me....fix this.....dont ignore meee/e////////i am a ung student 
imprs immediate submission i am a theoritical astrophysics..i out my theory unto it..

**Comment by josephwright** [comment]
This is not a support forum, it is for reporting specific issues with `expl3`. Even on a support forum such as TeX StackExchange, you would need to provide a clear example of your issue. As it stands, there is no way anyone will be able to help you with whatever issue you have. (I am entirely unclear from you post - note that your Overleaf link is non-functional to us.)

**Comment by Skillmon** [comment]
If this is about lost files on Overleaf you should contact Overleaf's support (on their homepage there is a button "Help" in the top right, then click on "Contact Us" to get a form where you can reach support with a link to your lost project). Chances are they can restore your stuff.

But a short advice: Don't threaten people just because they don't help you immediately, be it volunteers or some support of a company. Things like

> help me otherwise i am putting international criomnal case upon for you fir this ban sudden banning and stealing my knowledge and my paper..

will not help you or your case in any way, on the contrary, people might be unwilling to help you!

**Comment by Skillmon** [comment]
Btw. you were told that this isn't a support forum at least once already: https://github.com/latex3/latex3/issues/1263#issuecomment-1708957864

**Comment by anukriti0009** [comment]
Immediately what do you mean -'j have to show my project to Ursula von den
leywn Joe being Vandana Niranjan prime of india and President of slovwjia
also..also I am working as defense xohnswl at international criminal court
it's nit a threat 😳  .. it's a case file give my pape back I work with
imprs max Planck

advocate Dr anukriti

**Comment by davidcarlisle** [comment]
@anukriti0009  If you have a problem with your overleaf project contact overleaf support, we have no access or control over that. I'm deleting this issue as it is unrelated to this latex3 bug tracker
