### ISSUE TITLE
l3fp: variable losts its value if used as vars of \fp_set_function:nnn 

### ISSUE THREAD

**Issue by Sophanatprime** [latex3/latex3#1298]
When I use the `\fp_set_function:nnn` to define a function and use a variable that has been set value as a parameter, the value of this variable will be lost. This problem only occurs when `\fp_set_variable:nn` is executed before `\fp_set_function:nnn`. Here is a MWE:

```tex
\documentclass{article}
\begin{document}
\ExplSyntaxOn

\fp_new_variable:n { E }
\fp_new_function:n { PS }
\fp_set_variable:nn { E } { 2 }
\fp_set_function:nnn { PS } { E } { E^E }
\fp_to_tl:n { E**2 + PS(3) }

\ExplSyntaxOff
\end{document}
```

The expected output is: `31`, and the actual output is: `((E)ˆ(2))+(27)`.

I've found that `\cs_undefine:c` is `\global`, so even if it is used in a group, the value will still be clear.
https://github.com/latex3/latex3/blob/2eebe69a42db66364efe7008185cdfe32da22c30/l3kernel/l3fp-symbolic.dtx#L553-L557

https://github.com/latex3/latex3/blob/2eebe69a42db66364efe7008185cdfe32da22c30/l3kernel/l3fp-functions.dtx#L166-L187

Is this intended or not?

**Comment by josephwright** [comment]
`\cs_undefine:N` is deliberately global, but I think that the approach here is therefore wrong for clearing.
