### ISSUE TITLE
Fp variable using symbolic fp-var can't be shown

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1301]
In other words, the [example](https://github.com/latex3/latex3/blob/9ffa1890a187212c1f78f5d6c2ea59ecc33323af/l3kernel/l3fp.dtx#L661-L686) in section "Symbolic expression" doesn't compile.

```tex
\documentclass{article}
\ExplSyntaxOn
\fp_new_variable:n { A }
\fp_set:Nn \l_tmpb_fp { 1 * sin(A) + 3**2 }
\fp_show:n { \l_tmpb_fp } % works
\fp_show:N \l_tmpb_fp     % errors
\ExplSyntaxOff

\begin{document}
\end{document}
```

Expected
https://github.com/latex3/latex3/blob/9ffa1890a187212c1f78f5d6c2ea59ecc33323af/l3kernel/l3fp.dtx#L677-L681

Actual
```tex
! LaTeX Error: Variable '\l_tmpb_fp' is not a valid fp.

For immediate help type H <return>.
 ...                                              
                                                  
l.6 \fp_show:N \l_tmpb_fp
                         

This is a coding error.

The variable '\l_tmpb_fp' with value

    \s__fp_symbolic \__fp_symbolic_chk:w \__fp_types_binary:Nww \__fp_+_o:ww
    ,{\s__fp_symbolic \__fp_symbolic_chk:w \__fp_types_binary:Nww \__fp_*_o:ww
    ,{\s__fp \__fp_chk:w 10{1}{1000}{0000}{0000}{0000};\s__fp_symbolic
    \__fp_symbolic_chk:w \__fp_types_unary:NNw \__fp_sin_o:w \use_i:nn
    ,{\s__fp_symbolic \__fp_symbolic_chk:w \__fp_variable_o:w A,{};};};\s__fp
    \__fp_chk:w 10{1}{9000}{0000}{0000}{0000};};

should be a fp variable, but it does not have the correct internal structure:

    \s__fp \__fp_chk:w ???;
```

Looks like some `\fp_show:N` internals are failed to be overwritten.

_Update:_ After a quick search, I questioned whether this support was ever implemented.

**Comment by josephwright** [comment]
> _Update:_ After a quick search, I questioned whether this support was ever implemented.

Don't think it was ...

**Comment by josephwright** [comment]
@muzimuzhi You fancy fixing this one?

**Comment by muzimuzhi** [comment]
Haven't digged into (and still a bit afraid of complex l3fp implementations). Will have a look tomorrow.
