### ISSUE TITLE
l3sys: sys_if_platform_windows seems to not reliably work on windows

### ISSUE THREAD

**Issue by Jazzpirate** [latex3/latex3#1303]
Tried to debug something on a colleagues windows (11) laptop, and ultimately discovered that `\sys_if_platform_windows` returned false even though it's a windows machine. I can't reproduce it on my own machine, where it works, unfortunately. Tried it subsequently in both powershell and `cmd`, hoping that it might be related to the shell (apparently powershell uses `$null` as a memory hole instead of `NUL:`), but it worked in neither.

Issue occured with `pdflatex` from a recently updated TeXLive 2023 with the latex3 kernel in the version from 2023/10/10.

If you have any questions, I'll gladly ask said colleague to answer here directly.

**Comment by Jazzpirate** [comment]
I told them to join this conversation.
To translate (please @josephwright correct me if I'm wrong):
That would entail running the following and ideally adding the log file:
```
\documentclass{article}
\begin{document}
\ExplSyntaxOn
\begingroup\tracingall
\sys_if_platform_windows:TF{\message{TRUE}}{\message{FALSE}}
\endgroup
\end{document}
```
...although I'm almost sure that the actual checks for `nul:` and `/dev/null` that determine the platform occur in expl3-code.tex and define the conditional accordingly - meaning the interesting stuff has happened during initex already...?

**Comment by u-fischer** [comment]
what do you get from `\c_sys_platform_str`?

**Comment by Jazzpirate** [comment]
My current suspicion would be:
IF powershell does not recognize `nul:` (which I currently can't check because I don't have a windows machine at hand, but can confirm later) AND said colleague updated texlive using `tlmgr` in powershell AND `tlmgr` calls initex in the same shell THEN that would explain the problem

**Comment by josephwright** [comment]
@Jazzpirate  I think if you are updating in Powershell, you are expecting to get `unix` not `windows` as the shell knows e.g. `ls` out-of-the-box.

**Comment by josephwright** [comment]
PowerShell doesn't know `nul:`

**Comment by Jazzpirate** [comment]
Not entirely sure I follow... windows is heavily pushing powershell as the default shell since Windows 10. I think you're saying the purpose of `\sys_if_platform_*` is more to check for common shell commands? That seems... dangerous. Since initex freezes the platform string, and there's basically no guarantee that a user would use the same shell elsewhere (e.g. a TeX IDE might use cmd instead...) that would make its semantics more like `sys_if_shell_when_having_ran_initex` :D

I use it heavily in sTeX to know how to handle absolute file paths (i.e. `X:\foo\bar` vs. `/foo/bar`)... should I use something else?

**Comment by josephwright** [comment]
> I use it heavily in sTeX to know how to handle absolute file paths (i.e. `X:\foo\bar` vs. `/foo/bar`)... should I use something else?

You should always be using `/`, as Windows has supported them internally for many many years. Also, I don't think you should ever be using absolute paths.

**Comment by josephwright** [comment]
@davidcarlisle points out that if you use shell escape from a TeX run in PowerShell, the shell you get is `cmd`

**Comment by Jazzpirate** [comment]
There are technical reasons why I need to use absolute file paths, mainly related to "where are a users modules" and remaining independent of their local file system (sTeX basically adds its own notion of "packages", which are highly modular, interrelated and numerous - and referenced via file paths relative to some "archive" directory. It's very un-TeX-like, really, but unfortunately necessary for system-interoperability-reasons). 
Absolute file paths are provided by users via various means, and windows users expect to use backslashes (naturally, the first thing sTeX does is replace them by forward-slashes, but it needs to know that it needs to do that).

> I think the number of people using PowerShell is very small

I'm not sure that's true; as mentioned, since Windows 10, which is already 8 years old now, windows has been pushing powershell to be the primary shell users use directly. If someone wants to update their texlive distro, it's likely that if they google how to do that and learn they have to use a shell, they will end up using powershell ;)

Either way, it might be worth thinking about whether "if_platform_windows" is an adequate command name if it is not actually intended to check for whether the platform is windows

**Comment by davidcarlisle** [comment]
> Absolute file paths are provided by users via various means, and windows users expect to use backslashes 

windows _tex_ users would not be expecting backslashes as they introduce tex commands and all pc tex systems going back to pre-windows emtex and sbtex have used / for all file handling. I strongly recommend that you review that design.


But anyway returning to the original issue, if the platform test is returning the wrong result that would be a bug but we would need a reproducible test case I think.

**Comment by josephwright** [comment]
>  windows users expect to use backslashes

Yes, comes up from time to time, and we tend to tell them not to do that in TeX as `\user` is then an undefined control sequence

> > I think the number of people using PowerShell is very small
> 
> I'm not sure that's true; as mentioned, since Windows 10, which is already 8 years old now, windows has been pushing powershell to be the primary shell users use directly.

Like I say, I suspect most users are updating via the GUI. Certainly, the official TL instructions 

> If someone wants to update their texlive distro, it's likely that if they google how to do that and learn they have to use a shell, they will end up using powershell ;)

For me at least, searching for  `windows command line` gives a link to `cmd.exe` (as I'd expect and have been using since it was `command.com`).

**Comment by Jazzpirate** [comment]
> windows _tex_ users would not be expecting backslashes as they introduce tex commands

In TeX that is true - but the absolut file paths I'm talking about come from e.g. environment variables (some of which a user has no control over, like HOME or PWD) ;)

> But anyway returning to the original issue, if the platform test is returning the wrong result that would be a bug but we would need a reproducible test case I think.

The reproducible test case would be the `\file_if_exist:nTF { nul: }{...}{...}` when being run in powershell, which does not adequately indicate the platform being windows.

For my issues, that means I can't rely on `sys_if_platform_windows` to deal with file paths, which is fine, I can work around it.

 I think the remaining issue would be:
 1.  the name of the macro, or a disclaimer in the documentation what is actually happening there, and
 2. If shell-escape escapes to `cmd`, then using powershell to update TeXLive (or run initex otherwise) becomes even more critical. Not sure how to address that problem at all, but I don't use shell-escae either way...

**Comment by u-fischer** [comment]
I can't reproduce your issue. When I run your document I always get `is windows: TRUE nul: exists Platform: windows platform str: windows`,  regardless of powershell or not. 

Last time this popped up, it was a problem with the binaries: https://github.com/latex3/latex3/issues/867. So are you sure that your colleague is using a current texlive?

**Comment by josephwright** [comment]
Same for me: on my Win10 VM I get the right outcome from both `cmd` and PowerShell.

**Comment by Jazzpirate** [comment]
> I can't reproduce your issue. When I run your document I always get `is windows: TRUE nul: exists Platform: windows platform str: windows`, regardless of powershell or not.

That's interesting - @josephwright earlier confirmed that powershell doesn't know `nul:`...? We'll have to wait for my colleague to chime in then...

(By the way, I'm **not saying this is a good idea**, but if it turns out to be a powershell issue, one way to actually check the platform, since shell-escape always yields cmd, would be to check `\sys_get_shell:nnN { kpsewhich ~ -var-value~PWD }` vs. `\sys_get_shell:nnN { kpsewhich ~ -expand-var~\c_percent_str CD\c_percent_str }`) xD

**Comment by davidcarlisle** [comment]
@Jazzpirate  I don't understand the powershell issues as even if you launch from a powershell then if you shell-escape from tex you end up in a cmd shell (as far as I understand) so, as the use case for the test is to determine what commands you can use in shell-escape  windows==cmd and powershell is not involved. at all, similarly the file handling is directly handled by kpathsea library and so is not affected by what shell you launched tex from.

**Comment by davidcarlisle** [comment]
> In TeX that is true - but the absolut file paths I'm talking about come from e.g. environment variables (some of which a user has no control over, like HOME or PWD) ;)

tex distributions provide for example `texosquery` to query the environment in standardised ways retunrning normalised path separators defaulting to /

**Comment by Jazzpirate** [comment]
> tex distributions provide for example `texosquery` to query the environment in standardised ways returning normalised path separators defaulting to /

true, but as far as I know, calling texosquery within TeX requires the shell-escape-flag, right? Calling kpsewhich does not (by default, or on overleaf, arxiv or springer, where shell-escape would be a no-go).

>  I don't understand the powershell issues as even if you launch from a powershell then if you shell-escape from tex you end up in a cmd shell (as far as I understand)

If `sys_if_platform_windows` returns false if a user updated tex using powershell, and shell-escape uses `cmd`, then there would be a discrepancy - the former would indicate unix-style commands to be available, whereas `cmd` would provide windows-style commands. That is, if powershell *is* the issue, which Ulrike indicates isn't the case after all.

Regarding my use case (which surfaced the problem in the first place), suffice it to say that I was under the impression that `sys_if_platform_windows` is a reliable way to determine how I need to handle certain *absolute* file paths I obtain from environment variables and from reading certain files generated by other software in an OS-dependent manner. IFF `sys_if_platform_windows` returns false on windows if a shell such as powershell is used (which apparently is currently not entirely clear is the cause of the issue), then that means that mechanism doesn't work and I potentially have to do something else. 

The remaining question is then whether that is a bug or intended behaviour (again: if the shell is the actual issue) - it seemed obvious to me that it *would* be a bug if that *were* the case, but I would suggest we wait for my colleague to check and report
(he only works half-time, so we probably won't hear from them until tomorrow though)

**Comment by Jazzpirate** [comment]
> The remaining question is then

Sorry, that sentence fragment was supposed to still be part of the preceding "IFF".

> Up to now nothing is actually known. You heard from someone that it fails

Correction: I verified on their machine that it fails and managed to narrow the error down to `sys_if_platform_windows` consistently returning `false`; that part is not speculation. Regarding powershell, I interpreted joseph's comment that `nul:` is not recognized by powershell as confirmation that that is the problem. If that caused confusion, I apologize.

**Comment by josephwright** [comment]
> Correction: I verified on their machine that it fails and managed to narrow the error down to `sys_if_platform_windows` consistently returning `false`

OK, can you copy-paste the start of the `.log` which shoes the engine build, etc.?

**Comment by Jazzpirate** [comment]
Well, not anymore; as mentioned, they work part time and will likely not read anything until tomorrow. I've notified them of this issue existing (which I made after we identified the cause, they went home and I went to lunch) and I expect them to reply as soon as they're back online.

**Comment by davidcarlisle** [comment]
> true, but as far as I know, calling texosquery within TeX requires the shell-escape-flag, right? Calling kpsewhich does not (by default, or on overleaf, arxiv or springer, where shell-escape would be a no-go).

no, like kpsewhich it it has a version allowed by the default restricted shell escape in the default texlive texmf.cnf

> If sys_if_platform_windows returns false if a user updated tex using powershell, 

although that seems to be a guess that can't be reproduced. The shell from which you ran the install or update can't really affect tex run time behaviour.  It seems more likely that they are using the binary build in the issue linked above where it was returning false all the time, which was not a latex issue at all.

**Comment by Jazzpirate** [comment]
> no, like kpsewhich it it has a version allowed by the default restricted shell escape in the default texlive texmf.cnf

That is extremely good to know, thank you! :)

> although that seems to be a guess that can't be reproduced. The shell from which you ran the install or update can't really affect tex run time behaviour. It seems more likely that they are using the binary build in the issue linked above where it was returning false all the time, which was not a latex issue at all.

I did check their versions of TeXLive and latex3, and they are 2023 and 2023/10/10, respectively, so they updated fairly recently (as I told them to not too long ago). Of course, I can't exclude that something went horribly wrong with the update, and something got tangled up with old binaries from 2021, but to figure that out we'll need to wait for them :-/

**Comment by josephwright** [comment]
Just double-checked by rebuilding my Win10 format from PowerShell:
```
This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./test.tex
LaTeX2e <2023-06-01> patch level 1
L3 programming layer <2023-10-10>
(c:/texlive/2023/texmf-dist/tex/latex/base/article.cls
Document Class: article 2023/05/17 v1.4n Standard LaTeX document class
(c:/texlive/2023/texmf-dist/tex/latex/base/size10.clo))
(c:/texlive/2023/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def)
(./test.aux) is windows: TRUE nul: exists Platform: windows
platform str: windows [1{c:/texlive/2023/texmf-var/fonts/map/pdftex/updmap/pdft
ex.map}] (./test.aux) )<c:/texlive/2023/texmf-dist/fonts/type1/public/amsfonts/
cm/cmr10.pfb>
Output written on test.pdf (1 page, 14536 bytes).
Transcript written on test.log.
```

**Comment by rappatoni** [comment]
Hi, I am the colleage to whom @Jazzpirate is referring.  I have run the code (see attached log file).

I have indeed been updating texlive using tlmgr from powershell. The GUI never worked for me ("Back end gone. Last command: version") .

[test.log](https://github.com/latex3/latex3/files/13169930/test.log)

**Comment by u-fischer** [comment]
> Hi, I am the colleage to whom @Jazzpirate is referring. I have run the code (see attached log file).

Well the log says "windows" everywhere, so the platform is correctly detected.

**Comment by Jazzpirate** [comment]
:O Am I going crazy? Did we not test this this morning?

I'm very sorry. I will close this issue for now. @rappatoni let's look at this again tomorrow, since will bug me forever if we don't figure this out -.-

**Comment by Jazzpirate** [comment]
For future reference, what apparently solved the problem in the mean time was 1. (possibly) deleting a directory `c:\dev\null` which apparently existed and 2. running `tlmgr update --all` once more, or as I would guess rather, the subsequent initex run. My best guess is that either 1. or something else went wrong during the last update attempt and the next one this afternoon fixed it.

Sorry again and thanks anyway
