### ISSUE TITLE
Private `\l__keys_unused_clist` is used both as tl and as clist

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1315]
Being used like a tl var, `\l__keys_unused_clist` is
- created by `\tl_new:N`
   https://github.com/latex3/latex3/blob/352528c2015c59e5da256f6ccd0718ebe038a60e/l3kernel/l3keys.dtx#L1665
- set to store the `o`-type expansion of itself (see [`\keys_set_known:nnN`](https://github.com/latex3/latex3/blob/352528c2015c59e5da256f6ccd0718ebe038a60e/l3kernel/l3keys.dtx#L2813-L2831) and [`\keys_set_filter:nnnN`](https://github.com/latex3/latex3/blob/352528c2015c59e5da256f6ccd0718ebe038a60e/l3kernel/l3keys.dtx#L2890-L2909))
- and its value (got by an `o`-type expansion) is stored in a user-provided tl var (line 2829)
  https://github.com/latex3/latex3/blob/352528c2015c59e5da256f6ccd0718ebe038a60e/l3kernel/l3keys.dtx#L2825-L2831

Being used like a clist var, it is appended by [`\clist_put_right:Ne`](https://github.com/latex3/latex3/blob/352528c2015c59e5da256f6ccd0718ebe038a60e/l3kernel/l3keys.dtx#L3263-L3318) and cleared by `\clist_clear:N` (line 2827, see above).

Since `\l__keys_unused_clist` is extended one key-value pair at a time, it seems it suffices to use a tl var.

**Comment by josephwright** [comment]
If we only use `tl` ops, we have to hand-code the clist-put-right, no?

**Comment by muzimuzhi** [comment]
We have to hand-code the comma part, but not the clist senitization part (since key-value pairs to be appended are already senitized).

For the comma part, we will need to do something like
```tex
% prepend each key-value pair with a comma
\tl_put_right:Ne \l__keys_unused_clist { , \l_keys_path_str = { \l_keys_value_tl } }
% drop the leading comma
\tl_set:Ne <user-provided tl var> { \tl_tail:N \l__keys_unused_clist }
```

I find the bigger picture is that, for now there's no data type designed for `<keyval list>`, probably precompiled. I'll open a separate issue for this topic.

**Comment by Skillmon** [comment]
@josephwright not really, one could just do `\tl_put_right:Nn \l__keys_unused_tl { , #1={#2} }` for each key=value pair. And if the leading comma is not wanted, on the final assignment to the user provided `tl` do a `\tl_if_empty:NTF \l__keys_unused_tl { \tl_clear:N #1 } { \exp_args:NNo \tl_set:No #1 { \exp_after:wN \use_none:n \l__keys_unused_tl } }`. No need to put any hand-programmed stuff there.

**Comment by Skillmon** [comment]
@muzimuzhi beat me by a few seconds it seems... Note that you're fully expanding the value in `e`-expansion there, should be `\exp_not:o \l_keys_value_tl`.

**Comment by muzimuzhi** [comment]
@Skillmon Corrected, thanks!

**Comment by Skillmon** [comment]
Also, depending on how big we expect the unused key list to grow, `\tl_build_...` might be used as well.

**Comment by josephwright** [comment]
> Also, depending on how big we expect the unused key list to grow, `\tl_build_...` might be used as well.

I think realistically unlikely: `tl-build` is for the order of 1000s of tokens upward

**Comment by josephwright** [comment]
> @josephwright not really, one could just do `\tl_put_right:Nn \l__keys_unused_tl { , #1={#2} }` for each key=value pair. And if the leading comma is not wanted, on the final assignment to the user provided `tl` do a `\tl_if_empty:NTF \l__keys_unused_tl { \tl_clear:N #1 } { \exp_args:NNo \tl_set:No #1 { \exp_after:wN \use_none:n \l__keys_unused_tl } }`. No need to put any hand-programmed stuff there.

That's still hand-programmed compared to `\clist_put_right:Ne`

**Comment by FrankMittelbach** [comment]
Is that really a time critical part? I think if we build a clist we might as well call it a clist not a tl and use the clist commands unless this is executed so often that we want to gain some performance

**Comment by josephwright** [comment]
@FrankMittelbach  I'd say no, not once you look at all the key processing, etc. I'll adjust

**Comment by josephwright** [comment]
Tightened up to use `clist` functions in most places, the kernel-level one where we likely need the performance.
