### ISSUE TITLE
Interface3 documentation: \c_true_bool not in the bool data type section

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex3#1330]
There is no mention of `\c_true_bool` or `\c_false_bool` in the bool data type section.

Maybe in the documentation of `\bool_if:nTF`, replace
```
a series of predicates or boolean variables
```
by
```
a series of predicates, boolean variables, \cs{c_true_bool} or \cs{c_false_bool}
```

**Comment by josephwright** [comment]
The current source has
```latex
% \section{The boolean data type}
%
% This section describes a boolean data type which is closely
% connected to conditional processing as sometimes you want to
% execute some code depending on the value of a switch
% (\emph{e.g.},~draft/final) and other times you perhaps want to use it as a
% predicate function in an \cs{if_predicate:w} test. The problem of the
% primitive \cs{if_false:} and \cs{if_true:} tokens is that it is not
% always safe to pass them around as they may interfere with scanning
% for termination of primitive conditional processing. Therefore, we
% employ two canonical booleans: \cs{c_true_bool} or
% \cs{c_false_bool}. Besides preventing problems as described above, it
% also allows us to implement a simple boolean parser supporting the
% logical operations And, Or, Not, \emph{etc.}\ which can then be used on
% both the boolean type and predicate functions.
```
and they are then covered in the constants section - I am not sure what is missing.

**Comment by muzimuzhi** [comment]
Perhaps it wasn't expressed clearly enough, that both built-in and user-defined constants are variables of the corresponding data type.
https://github.com/latex3/latex3/blob/7c6a7126e16faa204cc20d76f2f1e996812a9ce9/l3kernel/doc/source3body.tex#L290-L297

**Comment by jlaurens** [comment]
My first problem is that `\cs{c_true_bool}` or `\cs{c_false_bool}` are "two canonical booleans", they are not "two boolean variables". Some people reading the doc are not that fluent in English and won't fill the gap easily.

**Comment by muzimuzhi** [comment]
@jlaurens Would "two canonical boolean constants" a bit better? I confess I deduced that they are constants directly from their naming `\c_<name>_<type>` and just skipped word "canonical".

https://github.com/latex3/latex3/blob/5d922c3a0b753cfaa9aa0cc3322a6d9ae02ed64e/l3kernel/l3prg.dtx#L232-L234

**Comment by jlaurens** [comment]
That's correct.

My second problem is how can people understand that `\cs{c_true_bool}` and `\cs{c_false_bool}` can be part of boolean expressions. It is said that variables are part of boolean expressions and normally, available variables are well identified within a section because they appear in the margin. I find `\cs{c_true_bool}` and `\cs{c_false_bool}` too hidden in the text. This is why a mention in \cs{bool_if:nTF} would certainly help.

BTW, many people learning L3 are not real computer programming experts, and they are confused about "constants that are variables which are not variable".

**Comment by car222222** [comment]
I sympathise with them:

they are confused about "constants that are variables which are not variable". 

Maybe it is common in software to have "constant variables"? 

But I did find this statement, from IBM (so maybe very old-fashioned:-) :

"A constant is a named data item with a predefined value, while a variable is a named data item whose value can change during the course of program execution."

**Comment by muzimuzhi** [comment]
> It is said that variables are part of boolean expressions and normally, available variables are well identified within a section because they appear in the margin. I find `\cs{c_true_bool}` and `\cs{c_false_bool}` too hidden in the text.

`\c_true_bool` and `\c_false_bool` _are_ documented in section 9.2.1 "Constant and scratch booleans" in `interface3.pdf` (2023-11-09).

From another aspect, unlike other data types, `bool` data type
- is not introduced in a separate chapter
- is documented as part of chap. 9 for `l3prg` module, in Part III "Programming Flow", rather than in Part IV "Data types".

Perhaps the `bool` docs can be split to a new chapter in Part IV.

**Comment by jlaurens** [comment]
Sorry,  I forgot to check the date and was referring to an obsolete  interface3. This is one of the problems having many local TeX distributions!!!
