### ISSUE TITLE
\bool_to_str:n returns letters, not strings

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1331]
Although it's a documented behavior, having `\bool_to_str:N` and `\bool_to_str:n` acting like `\bool_to_tl:(N|n)` is still a bit wired.

They were added in commit 7b0e5ff2 (Gh1010 doc (#<span></span>1014), 2021-11-01), in response to #1010.

https://github.com/latex3/latex3/blob/5d922c3a0b753cfaa9aa0cc3322a6d9ae02ed64e/l3kernel/l3prg.dtx#L333-L341
https://github.com/latex3/latex3/blob/5d922c3a0b753cfaa9aa0cc3322a6d9ae02ed64e/l3kernel/l3prg.dtx#L1050-L1067

**Comment by josephwright** [comment]
@muzimuzhi  You want to take this one or should I?

**Comment by muzimuzhi** [comment]
Apart from fixing `\bool_to_str:(n|N)` to return real strings, are `\bool_to_tl:(n|N)` needed, to play the current role of `\bool_to_str:n`?

**Comment by josephwright** [comment]
> Apart from fixing `\bool_to_str:(n|N)` to return real strings, are `\bool_to_tl:(n|N)` needed, to play the current role of `\bool_to_str:n`?

Unless there is a clear use case, I think not
