### ISSUE TITLE
\tl_if_head_eq_meaning:nN(TF) and friends: need either oN variant or NN version

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1332]
Among the six expandable conditionals documented in `interface3.pdf` (2023-11-09), sec. 15.3.1 "Testing the first token",
- `\tl_if_head_eq_catcode:nN(TF)` has `o` variants
- `\tl_if_head_eq_charcode:nN(TF)` has `f` variants
- `\tl_if_head_eq_meaning:nN(TF)` has no variants
- `\tl_if_head_is_group:n(TF)`, `\tl_if_head_is_N_type:n(TF)`, and `\tl_if_head_is_space:n(TF)` all have no variant

When the token list is stored in a tl-var, one naturally wants either `o` variants or `N`/`NN` versions.

**Comment by josephwright** [comment]
All true: we are not ar present aiming to round out `o` or `f`-typ variants comprehensively

**Comment by josephwright** [comment]
Note that `\tl_if_head_eq_catcode:oN(TF)` seems to be entirely unused, whilst for most purposes `e`-type expansion is clearer than `f`-type. So if the request here is for variants across-the-board, they really should all be `e`-type.

**Comment by josephwright** [comment]
Alternatively, if you are after storage then really `V`-type is preferred in most cases - Id mainly use `o`-type for _very_ tioght loops or if I'm doing something like `{ \use_none:n #1 }`.

**Comment by josephwright** [comment]
96a159e27d20391d96a162efd5cd5fe09024bc82 adds `V`- and `e`-type variants consistently for `\tl_if_head_eq_<test>:nN(TF)` - does that cover this?

**Comment by muzimuzhi** [comment]
> * `\tl_if_head_is_group:n(TF)`, `\tl_if_head_is_N_type:n(TF)`, and `\tl_if_head_is_space:n(TF)` all have no variant

Are these remaining three functions worth having such variants too, for consistency?

**Comment by josephwright** [comment]
> > * `\tl_if_head_is_group:n(TF)`, `\tl_if_head_is_N_type:n(TF)`, and `\tl_if_head_is_space:n(TF)` all have no variant
> 
> Are these remaining three functions worth having such variants too, for consistency?

That I know of, this set is only _ever_ used directly with an `n`-type argument.

**Comment by FrankMittelbach** [comment]
It is always our position that variants are all there (implicitly) and that if the kernel doesn't provide them a package could declare them, so as long as we don't have *any* usage in the wild I think it is fine not to burn csanmes unnecessarily. yes, some level of consistency is good, but  where the line is is difficult to say ... for now I gues I would go without as those are more specialized functions.

**Comment by muzimuzhi** [comment]
> > > * `\tl_if_head_is_group:n(TF)`, `\tl_if_head_is_N_type:n(TF)`, and `\tl_if_head_is_space:n(TF)` all have no variant
> > 
> > 
> > Are these remaining three functions worth having such variants too, for consistency?
> 
> That I know of, this set is only _ever_ used directly with an `n`-type argument.

my bad

**Comment by josephwright** [comment]
@muzimuzhi  It's a fair question: it's likely over time we'll add more of these, but each 'round' we want to check for real-world use cases.

**Comment by FrankMittelbach** [comment]
Once or several times? Because once is always a judgment call I would say (and under speed consideration not using the variant is also faster)

**Comment by josephwright** [comment]
> Once or several times? Because once is always a judgment call I would say (and under speed consideration not using the variant is also faster)

I can only see them used that way once

**Comment by FrankMittelbach** [comment]
then I would live as it is -- with core functions even tiny speed gains do not hurt.
