### ISSUE TITLE
What are the states of deprecated functions documented in interface3?

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1333]
In `interface3.pdf` (2023-11-09), there are nine functions documented under section titles "Deprecated functions".

- `l3str`, sec. 17.11, `\str_foldcase:n`
- `l3token`, sec. 24.8,
  - `\char_lowercase:N`, `\char_uppercase:N`, `\char_titlecase:N`, `\char_foldcase:N`
  - `\char_str_(lower|upper|title|fold)case:N`

How officially are they deprecated? Are they "less" deprecated than those listed in `l3deprecation.dtx` but not removed and all `x`-type variants (`x`-type variants are not documented now)?

**Comment by josephwright** [comment]
No, it's just we've had a bit of variation in thinking about whether to remove deprecated functions from `interface3` entirely

**Comment by muzimuzhi** [comment]
Hmm a candidates for deprecation status.

Searching in `.dtx` files, I find there're several "Deprecated functions" subsections in implementation parts, under which the functions are neither deprecated, nor known to users (after all they are not documented now).

```
$ grep -rn 'Deprecated functions' l3kernel/*.dtx
l3kernel/l3file.dtx:2549:% \subsection{Deprecated functions}
l3kernel/l3keys.dtx:3596:% \subsection{Deprecated functions}
l3kernel/l3pdf.dtx:525:% \subsection{Deprecated functions}
l3kernel/l3str.dtx:858:% \section{Deprecated functions}
l3kernel/l3token.dtx:1222:% \section{Deprecated functions}
```

I understand they might be in a situation that "to be deprecated or not to be, that is a question". But it's takes more efforts for undocumented (old) interfaces to have non-core new users.

These functions and key properties are
- `l3file.dtx`: `\iow_shipout_x:Nn`
- `l3keys.dtx`: `.str_set_x:N`, `.str_gset_x:N`, `.tl_set_x:N`, `.tl_gset_x:N`
- `l3pdf.dtx`: `\pdf_object_new:nn`, `\pdf_object_write:nn`

Too many stages for soft deprecations. 🦆

**Comment by josephwright** [comment]
The `x` ones are covered by the generic 'deprecate `x`-type variants' entry in `l3obsolete` (or that was the intention); I thought we covered the PDF ones when we removed them.

**Comment by josephwright** [comment]
@muzimuzhi  This clearer?

**Comment by muzimuzhi** [comment]
Found more problems. For the ones I'm not sure about hence not fixed by #1337

- `\char_(lower|upper|fold)case:N` and `str` variants are doubly defined in both `l3token.dtx` and `l3deprecation.dtx`.
  109e9be84c311a78fb2d548d999ad4085acd1bce only added them to `l3deprecation.dtx` and didn't remove the original definitions in `l3token.dtx`
- `\char_titlecase:N` and `\char_str_titlecase:N` are almost not deprecated.
  They are defined (only once) in `l3token.dtx`, not listed in `l3obsolete.txt`, and never mentioned in `CHANGELOG.md`

**Comment by josephwright** [comment]
@m

**Comment by josephwright** [comment]
@muzimuzhi Also corrected
