### ISSUE TITLE
l3deprecation entry for \char_to_utfviii_bytes:n

### ISSUE THREAD

**Issue by mbertucci47** [latex3/latex3#1346]
The entry for `\char_to_utfviii_bytes:n` in l3deprecations.dtx reads
```tex
\__kernel_patch_deprecation:nnNNpn { 2022-10-09 } { [ \codepoint_generate:n ] }
\cs_gset:Npn \char_to_utfviii_bytes:n { \__kernel_codepoint_to_bytes:n }
```
but as far as I can tell, there is no `\codepoint_generate:n` command, only `\codepoint_generate:nn`. Additionally, it's unclear what the square brackets around `\codepoint_generate:n` are supposed to mean. As written, I think the resulting debug message does not tell the user how they should replace `\char_to_utfviii_bytes:n` in their code.

**Comment by josephwright** [comment]
The square brackets mean this is 'editorial': there is no direct replacement, rather the programmer will need to look at the stuff in the `[...]` and read up on it. 

I'll fix the typo.
