### ISSUE TITLE
Some deprecated functions are not defined in `l3deprecation.dtx`

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1347]
This is a follow-up to #1333.

I feel like every deprecated function needs to be defined in `l3deprecation.dtx` so that with `\debug_on:n { deprecation }` it will throw a one-time error. But some deprecated functions and key properties are still defined in their corresponding `l3<module>.dtx` files.

- `\iow_shipout_x:Nn` and variants are defined in `l3file.dtx`
- `.str_(g)set_x:N`, `.tl_(g)set_x:N` and variants are defined in `l3keys.dtx`
- `\pdf_object_new:nn` and `\pdf_object_write:nn` are defined in `l3pdf.dtx`

**Comment by josephwright** [comment]
Feel free to move in a PR ...

**Comment by josephwright** [comment]
Is the move OK? The key properties are a little tricky to cover ...

**Comment by FrankMittelbach** [comment]
asking whom? I guess if the test suite is happy then yes, why do you have concerns?

**Comment by josephwright** [comment]
> asking whom? I guess if the test suite is happy then yes, why do you have concerns?

@FrankMittelbach  I was asking @muzimuzhi  :)

**Comment by josephwright** [comment]
I think we are done here
