### ISSUE TITLE
Assertion functions to validate variable contents

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1350]
Package writers may use such functions like `\str_assert:N(TF)` and `\fp_assert:N(TF)` to check if contents of variables match their type signatures, at entrances of package commands or when debugging.

Currently `\<module>_log:N` and `\<module>_show:N` already apply such checks, in some sort. See #1301 for `\fp_show:N` and #1344 for `\str_show:N`.
https://github.com/latex3/latex3/blob/ad0e6b16d9ddbc9d35573a96c2b1637495ace08f/l3kernel/l3fp-assign.dtx#L171-L180
https://github.com/latex3/latex3/blob/ad0e6b16d9ddbc9d35573a96c2b1637495ace08f/l3kernel/l3str.dtx#L2168-L2172

**Comment by josephwright** [comment]
I'm wondering about the motivation here: only code at the kernel level should be making `fp` or `str` data 'raw'.
