### ISSUE TITLE
New `l3str` functions that take strings, not token lists?

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1351]
Currently quite many `l3str` functions always do `\tl_to_str:n` conversion to their `n`-type arguments, for instance `\str_set:Nn` and `\str_put_left:Nn`, but sometimes the passed `n` arguments are already known to be strings, thus `\tl_to_str:n` becomes a source of inefficiency.

In such cases, `l3kernel` used `\cs_set_nopar:Npe` in replacement of `\str_set:Ne` to gain some speed.
https://github.com/latex3/latex3/blob/ad0e6b16d9ddbc9d35573a96c2b1637495ace08f/l3kernel/l3keys.dtx#L1813-L1826
```
$ grep -rn '\\cs_set_nopar:Npe \\l_[a-z@_]\+_str' l3kernel/*.dtx
l3kernel/l3keys.dtx:1822:    \cs_set_nopar:Npe \l_@@_property_str { \@@_trim_spaces:n { #1 } }
l3kernel/l3keys.dtx:1835:    \cs_set_nopar:Npe \l_keys_path_str
l3kernel/l3keys.dtx:1842:    \cs_set_nopar:Npe \l_keys_path_str { \l_keys_path_str . #1 }
l3kernel/l3keys.dtx:1849:    \cs_set_nopar:Npe \l_@@_property_str { . #1 }
l3kernel/l3keys.dtx:1850:    \cs_set_nopar:Npe \l_keys_path_str
l3kernel/l3unicode.dtx:1007:      \cs_set_nopar:Npe \l_@@_tmpa_str
```

A set of new functions named as `\str_set_raw:Nn` would help.

`\str_put_left_raw:Nn` could in addition treat it's `#1` an indeed string variable, hence not prevent further expansion on its content, as discussed in https://github.com/latex3/latex3/pull/1349#discussion_r1404818644.

**Comment by josephwright** [comment]
The performance gain here is very small: I don't think adding for general use is really necessary.

**Comment by josephwright** [comment]
We feel the performance gain is not worth it at present.
