### ISSUE TITLE
Document that file hex dump, mdfive hash, size, and timestampt functions return string

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1358]
These functions can be classified in two kinds:
- for `\file_mdfive_hash:n` and friends, only documentation adaption is needed.
- for `\file_get_mdfive_hash:nN(TF)` and friends, currently the `N`-type arguments are documented as `<tl var>`, not `<str var>`.

**Comment by josephwright** [comment]
@muzimuzhi  Fancy making a PR?

**Comment by josephwright** [comment]
>     * for `\file_get_mdfive_hash:nN(TF)` and friends, currently the `N`-type arguments are documented as `<tl var>`, not `<str var>`.

No, it needs to be a `tl`: we return `\q_no_value` if the file is not found. I can document that the material is otherwise equal to a string.

**Comment by josephwright** [comment]
I wonder if this could be covered by a general statement at the start of the section on file functions.

**Comment by FrankMittelbach** [comment]
> I wonder if this could be covered by a general statement at the start of the section on file functions

isn't that generally the case (not just for file functions)? When we return something into a variable we expect that to be a tl even if it is structurally of a more complex type (most of the time) but there is alway the quark return

**Comment by FrankMittelbach** [comment]
exactly and that happens in other places too, and in each case we have to say we return in a TL because we just don't know

**Comment by josephwright** [comment]
> exactly and that happens in other places too, and in each case we have to say we return in a TL because we just don't know

Sure, I meant the bit about the return value being 'other' - do we need to document for every `file` function or would a general statement cover it.

**Comment by FrankMittelbach** [comment]
I think a general statement in the early beginning is enough, the rest is covered by the fact that we say `<tl var>`in the syntax.

**Comment by josephwright** [comment]
I've re-ordered and added something - hopefully this is enough.
