### ISSUE TITLE
Why no `\c_empty_str`?

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1361]
Found when editing [#1360](https://github.com/latex3/latex3/issues/1360#issuecomment-1843319147).

Each of modules `tl`, `seq`, `clist`, and `box` provides function `\<module>_if_empty:NTF` and constant `\c_empty_<module>`, but `str` module provides only the corresponding function, no constant.

`\c_empty_str` ships with its type info, hence is syntactically different from `\c_empty_tl`.

[Searching for `\c_empty_str`](https://github.com/search?q=repo%3Alatex3%2Flatex3+%5Cc_empty_str&type=commits) in current repository on GitHub, `\c_empty_str` was mentioned only once in full message of commit a5398ff8 (l3doc: Change how module name is guessed, 2016-08-18).

**Comment by josephwright** [comment]
Feel free to make a PR ...
