### ISSUE TITLE
A feature providing all the `\l_mypkg_tmpa_⟨whatever⟩` and `\g_mypkg_tmpa_⟨whatever⟩` scratch `⟨whatever⟩`s?

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#1364]
Using `expl3`'s `\l_tmpa_⟨whatever⟩` and `\g_tmpa_⟨whatever⟩` scratch `⟨whatever⟩`s is risky: they may be overwritten by other non-kernel code.

For the author of a `mypkg` package, it would be handy if `\ProvidesPackage{mypkg}` would automatically provide all the `\l_mypkg_tmpa_⟨whatever⟩` and `\g_mypkg_tmpa_⟨whatever⟩` scratch `⟨whatever⟩`s. This would save the author having to explicitly declare each of them with :

```latex
\⟨whatever⟩_new:N \l_mypkg_tmpa_⟨whatever⟩
\⟨whatever⟩_new:N \g_mypkg_tmpa_⟨whatever⟩
```

Of course, the same feature request applies for `\ProvidesClass`.

**Comment by josephwright** [comment]
> And, for instance in `siunitx.sty`, I see `\dim_new:N \l__siunitx_tmp_dim`, and that is precisely what I'd like to avoid having to do.

@davidcarlisle 's point is that we can't know in general is a generic scratch `<thing>` is appropriate. For example, in `siunitx` I need only one `dim` but no `muskip`, etc., and have more focussed storage too. All of that needs insight into the code.

**Comment by dbitouze** [comment]
Sorry, I still don't understand. 

I understand that not all the scratch `⟨whatever⟩`s would be useful (and used) but would they be harmful? 

About the storage, there are currently 17 modules in `expl3` that provide scratch variables, hence my FR would create 4 × 17 = 68 of them: is it so critical? If so, one could imagine to let the author choose the `⟨type⟩`s for which scratch variables are needed.

**Comment by u-fischer** [comment]
well at first tmp-variables should be internal, so you would need something like `\l__mypkg_tmpa_tl`.  
Technically I don't think it would work: It would break existing packages which contains already declarations like `\tl_new:N    \l__tag_tmpa_tl`.  And it wouldn't work with packages whose names contain numbers or hyphens. 

But beside this I too think it is a waste of csnames. While nearly in all packages I declare some temporary variables I never needed a full set, e.g. I rarely need a int or a box.  You wouldn't want to provide a full set of scratch variables e.g. for indentfirst.
Do not underestimate the number of packages of a document. A simple `\documentclass{beamer}` already loads nearly 100 packages!

**Comment by davidcarlisle** [comment]
> About the storage, there are currently 17 modules 

but you suggested that each l3 package should have a dozen or so variables defined one for each typel and in the end a better number indication might be the current number of ctan packages so a thousand modules and a document loading a few tens of modules.

historically latex uses have had `tmpa` variables which was designed to be a generic name shared between packages, for package-specific variables I don't really see why you would often need `tmp` in other programming language,s variables normally have names related to what they are storing, not just get called `tmp_var`

**Comment by dbitouze** [comment]
@u-fischer Okay but this could be supplied only on request, and only for `⟨type⟩`s needed. For instance: `\ProvideScratchVariables[tl,seq]{mypkg}`.

**Comment by dbitouze** [comment]
@davidcarlisle 

> but you suggested that each l3 package should have a dozen or so variables defined

Okay, only on request, and only for requested `⟨type⟩`s :smile:

>I don't really see why you would often need `tmp`

But, as I told above, such temporary variables are widely used.

**Comment by pablgonz** [comment]
Just as a comment on this, I think a note of good practice in the documentation of `expl3` or `useguide3` regarding `\l_tmpa_⟨whatever⟩` variables and the use of this in code for public packages would suffice.

A different approach might be to add some code to `debug_on:n` to accept `debug_on:n { scratch }` and warn the programmer if he has any of these variables in code that will be public.

**Comment by FrankMittelbach** [comment]
I think we have notes on avoiding globally available scratch variables, but  I don't mind making that more prominent in interface3 stating that they are there for historical reasons and that programming should use private scratch packages  (or adding it if it isn't there). 

As to the idea of offering a huge bunch of them per package or class this is not going to happen. It would clutter the name space and it would nearly never be necessary (and if then only for a fraction of them). Asking the programmer to properly define them is not a hard burden and it is much more useful then relying on  a lot of implicit rules.
Besides, it is usually better if you use private registers to give themsensible names that give the reader a clue what they might hold rather than using `\l__mypkg_tmpa_tl` and if a package reuses a register a lot of different things then it can just declare a scratch variable with whatever name.
