### ISSUE TITLE
`\tl_if_eq:VnT(F)` doesn't exist?

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#1365]
Current version of `interface3.pdf` reads on page 114: `\tl_if_eq:(nV|ne|Vn|en|ee)TF`. But the compilation of the following MCE:
```latex
\documentclass{article}
\begin{document}
\ExplSyntaxOn
\tl_set:Nn \tl_tmpa_tl {a}
\tl_if_eq:VnT {\tl_tmpa_tl} {a} {True}
\ExplSyntaxOff
\end{document}
```
gives an error:
```
! Undefined control sequence.
l.5 \tl_if_eq:VnT
                  {\tl_tmpa_tl} {a} {True}
```

**Comment by josephwright** [comment]
> \tl_if_eq:VnT {\tl_tmpa_tl} {a} {True}

Should be `\l_if_eq:BnT. \l_tmpa_tl` without the braces, of course ;)

**Comment by pablgonz** [comment]
> > \tl_if_eq:VnT {\tl_tmpa_tl} {a} {True}
> 
> Should be `\l_if_eq:BnT. \l_tmpa_tl` without the braces, of course ;)

`B` variant :D
