### ISSUE TITLE
Check that all documented functions are defined, including variants

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1366]
To avoid flaws similar to
- #1365
- #1272

One idea is to extend `l3doc` to do the checks when typesetting documentation, perhaps optionally.

The inverse checking, ensuring all implemented user/public functions and variables are documented, may also be useful. But this direction may rely on that all public names are "documented" inside `l3doc`'s `implementation` environment.

Loosely related to #1354.

**Comment by josephwright** [comment]
We have the `cmdcheck` target but it's always been a bit fragile  (I see at the moment it needs fixing), and  I do 't think checks variants. Moreover, I'm not sure the balance of effort _versus_ outcome is there:: mistakes in adding variants, etc.,  are rare, and I'm not really sure we need to check for this all of the time.

**Comment by josephwright** [comment]
Looking back, I'm pretty sure you are after `cmdcherck`: it's just we don't advertise it and it likely needs a bit more work to report better (and skip special cases).
