### ISSUE TITLE
Document `l3doc` class option `check`

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1369]
It's used by `l3kernel` target `cmdcheck`, see #1366. Resolving #1366 might modify effects of this class option, so just a reminder.

If set, check info is written to `\jobname.cmds`, whose content consists of three lists:
```tex
--
Functions both documented and defined:
(In order of being documented)
--
> \ExplSyntaxOn
> \ExplSyntaxOff
> ...
--
Functions documented but not defined:
--
! \ProvidesExplPackage
! \ProvidesExplClass
! ...
--
Functions defined but not documented:
--
? \token_to_meaning:c
? \token_to_str:c
? ...
```

**Comment by josephwright** [comment]
The `check` option is really one just for the team - I'm not sure why we'd document it

**Comment by muzimuzhi** [comment]
The whole `l3doc` class is more or less "just for the team", so I think some more documentation won't make it more attractive to "outer" users.

**Comment by josephwright** [comment]
Working on it

**Comment by josephwright** [comment]
I've added all the options, and I guess one could argue for the `check` option being useful more widely - honestly I'm more suspicious of `checktest` and the associated mark-up.

**Comment by muzimuzhi** [comment]
thanks

**Comment by muzimuzhi** [comment]
Is it on purpose that class option `stdmodule` is provided but not documented in b0e717494fb216aea8d8be6d20ecd826f7063d68? Or maybe it will be totally replaced by `kernel=false`?
https://github.com/latex3/latex3/blob/81a05242750c63148e03ee19fbb2cf74854cd76a/l3kernel/l3doc.dtx#L1453-L1454

**Comment by josephwright** [comment]
> Is it on purpose that class option `stdmodule` is provided but not documented in [b0e7174](https://github.com/latex3/latex3/commit/b0e717494fb216aea8d8be6d20ecd826f7063d68)? Because it can be totally replaced by `kernel=false`?

Yes - I'm aiming to move more completely to keyval options so we have `kernel = true|false` rather than a second name.
