### ISSUE TITLE
Problem with 'ocgx2' package

### ISSUE THREAD

**Issue by matteofg** [latex3/latex3#1373]
Below a mwe:
```
\DocumentMetadata{testphase=new-or-1}

\documentclass{book}
\usepackage{hyperref}
\usepackage[ocgcolorlinks]{ocgx2}

\begin{document}
\tableofcontents
\chapter{Chapter}
Hello world
\end{document}
```
If the following conditions are simultaneously present in the source code:

1. `\DocumentMetadata` command;
2. `ocgx2` package with `ocgcolorlinks` option;
3. `\tableofcontents` command;
4. sectioning command (e.g. `\chapter`)

then composition crashes with the following error:
```
(./emc.toc
! Undefined control sequence.
\pdf_object_new:nn ...__keys_backend_object_new:n 
                                                  {#1}
l.1 ...hapter}{\numberline {1}Chapter}{3}{chapter.1}
                                                  %
```
The problem is independent of
- the composition engine (pdfTeX; luaTeX; etc.);
- the tagging testphase (new; phase-I; etc.);
- the document class (article; book; memoir; etc.)

Finally, the problem arose from the latest updates.

**Comment by josephwright** [comment]
This is a bug in some of the code for deprecated functions: we've got an incorrect internal module marker.
