### ISSUE TITLE
l3draw: wrong depth if baseline is specified by user

### ISSUE THREAD

**Issue by viccie30** [latex3/latex3#1400]
This line:
https://github.com/latex3/latex3/blob/e25ebe2b3a6c225b94c8cb2a49b576d09abe24f8/l3experimental/l3draw/l3draw-scopes.dtx#L213
should contain a minus instead of a plus, like this line:
https://github.com/latex3/latex3/blob/e25ebe2b3a6c225b94c8cb2a49b576d09abe24f8/l3experimental/l3draw/l3draw-scopes.dtx#L195.

With the current code the depth is calculated incorrectly. 

With this TeX code:
```tex
\documentclass{minimal}
\usepackage{l3draw}
\begin{document}
\ExplSyntaxOn
\para_raw_noindent:

\hbox_overlap_right:n { \vrule width \textwidth height 1pt depth 0pt }

\draw_begin:
\draw_path_circle:nn { 10pt, 10pt } { 20pt }
\draw_path_use_clear:n { stroke }
\draw_end:
\box_set_to_last:N \l_tmpa_box
\box_log:Nnn \l_tmpa_box { 1 } { 1 }
\box_use_drop:N \l_tmpa_box

\draw_begin:
\draw_baseline:n { 5pt }
\draw_path_circle:nn { 10pt, 10pt } { 20pt }
\draw_path_use_clear:n { stroke }
\draw_end:
\box_set_to_last:N \l_tmpb_box
\box_log:Nnn \l_tmpb_box { 1 } { 1 }
\box_use_drop:N \l_tmpb_box

\para_raw_end:
\ExplSyntaxOff
\end{document}
```
the visual output looks OK at first glance, but the log reveals that the depth of `\l_tmpb_box` is too large:
```
> \box13=
\hbox(40.4+0.0)x40.4
.\glue 10.2
.etc.

! OK.
<argument> \l_tmpa_box 
                       
l.14 \box_log:Nnn \l_tmpa_box { 1 } { 1 }
                                         



> \box14=
\hbox(35.2+15.2)x40.4
.\glue 10.2
.etc.

! OK.
<argument> \l_tmpb_box 
                       
l.23 \box_log:Nnn \l_tmpb_box { 1 } { 1 }
                                         
```

**Comment by viccie30** [comment]
Thanks for the quick fix and a happy New Year!

**Comment by muzimuzhi** [comment]
> the visual output looks OK at first glance, but the log reveals that the depth of `\l_tmpb_box` is too large:
> 
> ```
> > \box13=
> \hbox(40.4+0.0)x40.4
> ...
>
> > \box14=
> \hbox(35.2+15.2)x40.4
> ...
> ```

Not depth, but height of `\box14` is too large. The permalinks to code lines and actual fix are all about box height.

**Comment by viccie30** [comment]
My apologies, you are exactly right @muzimuzhi! Luckily both @josephwright and me made the same mistake everywhere, so it looks like the solution is correct, even if the bug report was wrong.
