### ISSUE TITLE
Class option `kernel` is used as if its default is `false`

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1403]
Since class option `kernel` was introduced in commit 82eb9889 (Make l3doc aware of "kernel" prefix, 2017-12-05), it had been one of the default class options.
https://github.com/latex3/latex3/blob/583c2a9c01a500ebb8b48aee18c1d3714197fdc0/l3kernel/l3doc.dtx#L1498
https://github.com/latex3/latex3/blob/ec2ca2fedcc5c427d462adafaa77c181ef253c26/l3kernel/l3doc.dtx#L1466-L1467

But according to how it's used in `latex3/latex3` and `latex3/latex2e` repositories, the `kernel` option seems to be off by default.

```
rg --no-heading '\\documentclass.*kernel.*\{l3doc\}' /path/to/latex3 | wc -l
      64
rg --no-heading '\\documentclass.*kernel.*\{l3doc\}' /path/to/latex2e | wc -l
       0
```

**Comment by blefloch** [comment]
I confirm it was initially meant to be off by default.

**Comment by josephwright** [comment]
I've changed the standard setting here: I can't see that we want people to have to opt-in to checking, etc.
