### ISSUE TITLE
luatex85 \pdfglyphtounicode with dvilualatex bug

### ISSUE THREAD

**Issue by lstonys** [latex3/latex3#1406]
`\pdfglyphtounicode` from `\usepackage{luatex85}` raises error  with dvilualatex engine. This command used in newtxmath, newpxmath, and some other packages.  If it can't work in DVI mode then could be defined as gobbled in luatex85.

MWE:
```
\documentclass{article}
\usepackage{luatex85}
%\usepackage[varvw]{newtxmath}
\makeatletter
\ifx\pdfglyphtounicode\@undefined \else 
\pdfgentounicode=1
\pdfglyphtounicode{nPerp}{2AEB 2215}% .. .. 
\fi
\makeatother
\begin{document}
foo
\end{document}
```

ERROR:
```
! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.9 \pdfglyphtounicode
                    {nPerp}{2AEB 2215}% .. ..
? 
```

**Comment by davidcarlisle** [comment]
luatex85 package is maintained at https://github.com/josephwright/luatex85

**Comment by josephwright** [comment]
The `luatex85` package is for _transitional_ support for LuaTeX users, and it's from several years ago - I'd not expect to see it at all in an at-all-recent source.

**Comment by josephwright** [comment]
(Not a latex3 issue, and as the other repo is not a team one, I can't transfer)

**Comment by lstonys** [comment]
ok, I will open the issue in luatex85 repo.

**Comment by FrankMittelbach** [comment]
True @joseph, but as we all know preambles get copied forever ... (e.g., people still add `\usepackage{textcomp}` all over the place and people may also just try to reprocess an old source. So I think it wouldn't hurt to gobble the declarations in that case, not doing that will not educate people to take it out.

**Comment by josephwright** [comment]
@FrankMittelbach  Sure, but the point is not about end users, it's that the package code has had _years_ to be updated and should not be using `\pdfglyphtounicode` with LuaTeX in the first place.

**Comment by davidcarlisle** [comment]
@lstonys 

> ok, I will open the issue in luatex85 repo.

I think it would be better to raise as an issue on newtxmath (I don't think luatex85 can do much as as far as I can see luatex does not support this in dvi mode)

**Comment by u-fischer** [comment]
> as far as I can see luatex does not support this in dvi mode

I wonder if we can do something about that so that it does something sensible (like pdftex does in dvi mode). I did fall over that in latex-lab once too, there is changes entry `do not load glyphtounicode with dvilualatex`.  (We load there some additional glyph-to-unicode definitions for math).
