### ISSUE TITLE
Add `\tl_lowercase:nn` and deprecate (non-expandable) `\tl_to_lowercase:n`

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#141]
Contrarily to all `\<type>_to_<thing>` functions, `\tl_to_lowercase:n` and `\tl_to_uppercase:n`, wrappers around the corresponding TeX primitives, are not expandable.  It would be better to provide `\tl_lowercase:nn`, analogous to `\tl_rescan:nn`, with a first argument to hold the setup.

```
\cs_new_protected:Npn \tl_lowercase:nn #1#2
  { \group_begin: #1 \tex_lowercase:D { \group_end: #2 } }
```

Later, we can deprecate `\tl_to_lowercase:n`, and even later, rename `\tl_expandable_lowercase:n` to `\tl_to_lowercase:n`.  Similarly for upper case.

**Comment by josephwright** [comment]
As agreed at TUG2015, do the deprecation and ask for real use cases looking forward. Talk to Ulrike Fischer.

**Comment by josephwright** [comment]
Progress update: most of the use cases will be removed from `expl3` this week although a second round will be needed later to get rid of some `\tex_lowercase:D` that might go in favour of `\char_generate:nn` but at present are awkward (mainly due to XeTeX).

**Comment by josephwright** [comment]
This was done a while ago.
