### ISSUE TITLE
Old deprecated commands should not be simply defined as empty macros

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#1413]
If someone has old code that uses deprecated commands, it should somehow blow up rather than giving wrong results:  for instance, `\int_show:n { \c_one + 3 }` used to show 4 and now shows 3, with no indication that there was any problem in the code.  A variant of this just bit me when revisiting somewhat old code.

A couple of years back we used to define deprecated commands to be `\outer`, I think we should bring that back to avoid wasteful bug chases.

**Comment by josephwright** [comment]
Hmm, something must have gone wrong here as those commands were _supposed_ to be removed entirely. I suspect in the shift to have everything in the format, with deprecation handled separately, this got messed up. (The blame here shows you as the author of the current code, but that would be with a different load approach.)

**Comment by josephwright** [comment]
Easiest would be to just zap entirely all of the removed commands, leaving just those that are deprecated-but-never-will-be-removed.

**Comment by blefloch** [comment]
I think the point of keeping them in the sources is that turning on the debugging option `\debug_on:n { deprecation }` makes them outer.  Maybe the simplest would be to make them all expand to the same `\ERROR`-like macro.

**Comment by josephwright** [comment]
> I think the point of keeping them in the sources is that turning on the debugging option `\debug_on:n { deprecation }` makes them outer. Maybe the simplest would be to make them all expand to the same `\ERROR`-like macro.

Sure but the one you point to is one we explicitly said was removed ...

**Comment by josephwright** [comment]
My suggestion is we remove this code block entirely - leaving only the functions deprecated since we said no more removals at all. OK?

**Comment by blefloch** [comment]
That is a good solution, yes.  It's unlikely that an undefined function would lead to working-but-wrong code, contrarily to an `\empty` function, which does accidentally lead to that, as noted above.
