### ISSUE TITLE
Name of author: 'LaTeX Project team' vs 'LaTeX Project' vs 'LaTeX Team'

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1425]
On title pages, LaTeX2e documents tend to use 'LaTeX Project team' (e.g., `texdoc usrguide`) while LaTeX3 documents tend to use 'The LaTeX Project' (e.g., `texdoc interface3`).

https://github.com/latex3/latex3/blob/a413a695aa8425292eecd7fc72f68c09d4a2470b/l3kernel/l3doc.dtx#L4675-L4679

Notes in experimental files in current repo use phrase "(the) LaTeX Project Team".
https://github.com/latex3/latex3/blob/a413a695aa8425292eecd7fc72f68c09d4a2470b/l3trial/l3kernel-extras/l3kernel-extras.dtx#L25-L32

In `build.lua` files in current repo, `uploadconfig.author` is set to a third name, `"The LaTeX Team"`.
```
$ rg --no-heading -F 'author ' -B 1 -g '*.lua'
l3backend/build.lua-72-uploadconfig = {
l3backend/build.lua:73:  author      = "The LaTeX Team",
--
l3packages/build.lua-13-uploadconfig = {
l3packages/build.lua:14:  author      = "The LaTeX Team",
--
l3kernel/build.lua-64-uploadconfig = {
l3kernel/build.lua:65:  author      = "The LaTeX Team",
--
l3experimental/build.lua-13-uploadconfig = {
l3experimental/build.lua:14:  author      = "The LaTeX Team",
```

Does each of these three names subtlety different from each other?

**Comment by car222222** [comment]
It seems very unlikely that any distinction between these three is intended.

**Comment by FrankMittelbach** [comment]
Different times and different first authors and then copy-paste basically. We changed from LaTeX3 XXX to LaTeX Project (team) at some point because LaTeX3 got integrated into LaTeX as the L3 programming layer, but in each repo new files added typocally started out. So no, they all mean the LaTeX Project Team or LaTeX team as in  people listed at https://www.latex-project.org/about/team/

**Comment by josephwright** [comment]
Does anything actually need doing here? It's at least in part as I tend to put 'The LaTeX Project' and did most of the L3 tidying!

**Comment by FrankMittelbach** [comment]
If we want to make a sweep over the sources we can of course do that and then normalize to "LaTeX Project" and "LaTeX project team", basically dropping the 3 if found and changing "LaTeX team" to "LaTeX Project team".

But it shouldn't be done everywhere I guess, eg not in old l3news files for example. Anyway, nothing that realy "needs" doing I would say and it could be cleaned up whenever we touch a file for some other reason.

**Comment by FrankMittelbach** [comment]
no idea --- probably
