### ISSUE TITLE
documentation: peeking ahead

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex3#1429]
The doc says (Released 2023-12-08)

> As peeking ahead does not skip spaces the predefined tests include both a space-respecting and space-skipping version.

If my understanding is correct, skipping spaces is done via `\peek_remove_spaces:n` which is separate and there is only one version of each predefined test. The above sentence seems inappropriate.

Instead, some precision about the gathering of multiple spaces into one token would certainly help. For example, you cannot test for 2 successive spaces with a construct like
```
  \peek_catcode_remove:NTF \c_space_token
    {
      T
      \peek_catcode_remove:NTF \c_space_token
        { T } { F }
    } { F }~~
```

**Comment by josephwright** [comment]
This was missed 

> For example, you cannot test for 2 successive spaces with a construct like

That's not a limitation of `peek`, rather TeX has tokenized as a single space: you'd need to use one of the 'tricks' to create two spaces here.

**Comment by jlaurens** [comment]
This was just an example of a  reminder that many consecutive space characters give only one token. The exact meaning of "Spaces are respected by the test"  would be more precise.

**Comment by josephwright** [comment]
Better?

**Comment by blefloch** [comment]
Just a historical note: we used to have `\peek_catcode_ignore_spaces:N`, `\peek_catcode_remove_ignore_spaces:N` (now listed in `doc/l3obsolete.txt`), so the sentence probably dates from back then.

**Comment by josephwright** [comment]
> Just a historical note: we used to have `\peek_catcode_ignore_spaces:N`, `\peek_catcode_remove_ignore_spaces:N` (now listed in `doc/l3obsolete.txt`), so the sentence probably dates from back then.

Yes, it does: I think it was simply missed when I adjusted the text
