### ISSUE TITLE
Document `\bgroup` versus `\group_begin:` 

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex3#1433]
In the `\group_begin:` documentation, a short TeXhackers note explaining how `\group_begin:` is different from `\bgroup` and `\begingroup` may help.

**Comment by muzimuzhi** [comment]
Like
```tex
This is the \TeX{} primitive \cs{begingroup}.
```
? The corresponding "expl3 name" of `\bgroup`, the implicit `{` character, is `\c_group_begin_token`.

Documenting the difference between `\begingroup` and `\bgroup` is helpful, but maybe a bit beyond the scope of `interface.pdf`.
