### ISSUE TITLE
`\c_catcode_active_tl` documentation.

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex3#1436]
The documentation of `\c_catcode_active_tl` reads
```
A token list containing an active token.
```
Instead, something like this is more appropriate
```
A token list |e| and |x|-expanding to an active token.
```
Peeking ahead an active character would become a piece of cake.

**Comment by josephwright** [comment]
I wonder if we should deprecate here in favour of using an internal version: the current structure is rather low-level and I think proper docs would be therefore problematic.

Thoughts?

**Comment by josephwright** [comment]
Pinging the rest of the team :)
