### ISSUE TITLE
documentation \char_set_active_eq:NN

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex3#1437]
For `\char_set_active_eq:NN` after
```
to be equivalent to that of the ⟨function⟩
```
insert
```
at the time \cs[no-index]{char_set_active_eq:NN} is called.
```
And the same holds for `\char_set_active_eq:nN`.

**Comment by josephwright** [comment]
What other interpretation does the current text leave open?

**Comment by jlaurens** [comment]
at the time the active character is executed, 
BTW, source2e.pdf explicitly insists on the fact that `\obeylines` must be called *after* `\obeyedline` has been defined (and the like for tab and space related commands).

**Comment by josephwright** [comment]
Whilst I feel it's already clear (and the same as `\cs_set_eq::NN`, etc.), I have adjusted.
