### ISSUE TITLE
Documentation: \if:w.

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex3#1438]
The documentation is misleading. The usage reads
```
\if:w ⟨token1 ⟩ ⟨token2 ⟩ ⟨true code ⟩ \else: ⟨false code ⟩ \fi:
```
This is not always correct if one of the tokens is a command or is active.
This partly describes the situation *after* the expansion that occurs after `\if`, so it is not really the usage. Instead of
```
These conditionals expand any following tokens until two unexpandable tokens are left.
```
next sentence would be more appropriate.
```
These conditionals expand any following tokens until the two unexpandable tokens \meta{token_1} and \meta{token_2} are left.
```

**Comment by car222222** [comment]
Looks good!
