### ISSUE TITLE
What is exactly a category code regime?

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex3#1439]
I did not find any reference to a category code regime in the TeXbook.
It seems like a `cctab` from which `^^M` is excluded.
In particular, when `\ExplSyntaxOff` reverts to the document category code regime, it leaves the `^^M` catcode untouched.

**Comment by davidcarlisle** [comment]
It's just the set of current catcode vaues.  ExplSyntaxOff doesn't revert `^^M` as it only reverts things that are changed by ExplSyntaxOn, and neither touch the catcode of character 13.

**Comment by davidcarlisle** [comment]
note "regime" here is also the name used in the luatex manual for a set of catcode values see for example section 2.5.1  but it's used mostly as a standard English phrase for the current set of values not something requiring a formal definition.

**Comment by jlaurens** [comment]
Thanks for this general purpose explanation, but I was more interested in the *exactly* part.
