### ISSUE TITLE
Multiply-defined label for `\__kernel_chk_cs_exist:N`

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1447]
As of https://github.com/latex3/latex3/commit/148ecbefa7985930ee30abae483373a4f1b02bc3, two labels are multiply-defined in building documentations in this repo, see [workflow run 7843449355](https://github.com/latex3/latex3/actions/runs/7843449355/job/21403801322).

```
LaTeX Warning: Label `sec:l3keys:subdivision' multiply defined.

LaTeX Warning: Label `doc/function////kernel/chk/cs/exist:N' multiply defined.
```

The first will be resolved by #1445. Cause of the second, label for `\__kernel_chk_cs_exist:N`, is because it is documented both in `l3kernel-functions.dtx` and `l3debug.dtx`, in implementation parts.

As there're other `\__kernel_...` functions only documented in `l3debug.dtx`, e.g., `\__kernel_chk_var_scope:NN`, I think `\__kernel_chk_cs_exist:N` can be dropped from `l3kernel-functions.dtx`.

But in general cases, or if the intension is to list all `\__kernel_...` in `l3kernel-functions.dtx`, perhaps `l3doc` can provide a way to disable auto labeling, but still create index entries.

**Comment by blefloch** [comment]
I think all of the documentations of `\__kernel_...` functions and `\?__kernel_...` variables should be moved to `l3kernel-functions.dtx`.  Do you have time to do a pull request for that please?

**Comment by muzimuzhi** [comment]
I'm on it.
