### ISSUE TITLE
Undefined control sequence \__tl_peek_analysis_normal:N

### ISSUE THREAD

**Issue by Sophanatprime** [latex3/latex3#1461]
`\__tl_peek_analysis_normal:N` is used but is never been defined:
```tex
\documentclass{article}
\begin{document}

\ExplSyntaxOn
\group_begin:

\char_set_catcode_group_begin:N [
\char_set_catcode_active:N \{
\cs_set_eq:NN { \c_group_begin_token

\peek_analysis_map_inline:n [ \peek_analysis_map_break: } {

\group_end:
\ExplSyntaxOff

\end{document}
```
gets 
```tex
! Undefined control sequence.
<recently read> \__tl_peek_analysis_normal:N 
                                             
l.11 ...p_inline:n [ \peek_analysis_map_break: } {
```

**Comment by muzimuzhi** [comment]
It seems `\__tl_peek_analysis_normal:N` was replaced by `\__tl_peek_analysis_exp:N` in commit 24f71889 (Fix how peek analysis deals with normal tokens (fix #<span></span>1109) (fix #<span></span>1110), 2022-10-03). @blefloch 

I know nothing about peek implementation, but a simple replacement seems to work.

```tex
\documentclass{article}
\ExplSyntaxOn
\cs_undefine:N \__tl_peek_analysis_retest:

\cs_new_protected:Npn \__tl_peek_analysis_retest:
  {
    \if_meaning:w \l__tl_analysis_token \scan_stop:
      % \exp_after:wN \__tl_peek_analysis_normal:N
      \exp_after:wN \__tl_peek_analysis_exp:N
    \else:
      \exp_after:wN \__tl_peek_analysis_next:
    \fi:
  }
\ExplSyntaxOff

\begin{document}

\ExplSyntaxOn
\group_begin:

\char_set_catcode_group_begin:N [
\char_set_catcode_active:N \{
\cs_set_eq:NN { \c_group_begin_token

\peek_analysis_map_inline:n [ \peek_analysis_map_break: } {

\group_end:
\ExplSyntaxOff

\end{document}
```

**Comment by blefloch** [comment]
Thanks a lot for finding that.  It's a pretty blatant bug from October 2022!  I'll fix it, probably tonight, because I want to read that code a bit more carefully and see if there are other bouts of stupidity lurking there.

**Comment by josephwright** [comment]
@blefloch  Should I hold off on the release until then? Or would it be better to get the `prop` fix out right now and perhaps have a second one for this in a day or two?

**Comment by blefloch** [comment]
I'm on it right now if the baby doesn't wake up unexpectedly.

**Comment by josephwright** [comment]
@blefloch OK I'll wait for a commit :) Don't worry about the tag step - I'll wait until you are sorted before releasing

**Comment by blefloch** [comment]
@josephwright Since the prop business in the other issue seems to be a user error, I think we are good to go for a release.
