### ISSUE TITLE
Non-declared variable is not created when `check-declarations` is on

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1465]
```tex
\documentclass{article}
\ExplSyntaxOn
\debug_on:n { check-declarations }

\bool_set_eq:NN \l_tmpa_bool \l_undefined_bool
\cs_if_exist:NF \l_undefined_bool \ERROR
\ExplSyntaxOff

\begin{document}
\end{document}
```

The first error message thrown by `\bool_set_eq:NN` ends with
```
LaTeX will create the variable and continue.
```
but `\l_undefined_bool` is not got defined.

<details><summary>Full error messages</summary>
<p>

```
! LaTeX Error: The variable \l_undefined_bool has not been declared on line 5.

For immediate help type H <return>.
 ...                                              
                                                  
l.5 \bool_set_eq:NN \l_tmpa_bool \l_undefined_bool
                                                  

This is a coding error.

Checking is active, and you have tried do so something like:
  \tl_set:Nn \l_undefined_bool { ... }
without first having:
  \tl_new:N \l_undefined_bool

LaTeX will create the variable and continue.


! Undefined control sequence.
<argument> \ERROR 
                  
l.6 \cs_if_exist:NF \l_undefined_bool \ERROR
                                            
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.
```

</p>
</details>

**Comment by josephwright** [comment]
That's correct: with checking active, this needs fixing and `expl3` knows it should not attempt to set/create the variable.

**Comment by muzimuzhi** [comment]
> ... and `expl3` knows it should not attempt to set/create the variable.

If that's the expected code behavior, I think the last line of error message
```
LaTeX will create the variable and continue.
```
should be improved, cause the variable really won't be created by LaTeX.
https://github.com/latex3/latex3/blob/ac4b252d588659421e969bdb7274f7e5b215d8b3/l3kernel/l3debug.dtx#L1455-L1465

**Comment by josephwright** [comment]
@muzimuzhi  Hmm, I thought we simply skipped but I see you are right in general - I'll see if I can fix today

**Comment by muzimuzhi** [comment]
Agreed.

Also the second and third arg. of `\tl_concat:NNN` cases.

**Comment by car222222** [comment]
I assume that should be: set_eq cases 
(i.e., for all, or most?, types].

**Comment by josephwright** [comment]
Does the new phrasing sort it?

**Comment by muzimuzhi** [comment]
Yes, I think so. I'm even OK with just "LaTeX will continue."

**Comment by josephwright** [comment]
Cool - I'll close then.
