### ISSUE TITLE
Feature / Documentation  request: V and v argument specifiers also for Property Lists

### ISSUE THREAD

**Issue by alceu-frigeri** [latex3/latex3#1466]
After my recent snafu (#1460) and the realization that the following Coding Pattern Code, isn't officially supported:
```latex
\cs_new:Npn \put_cmd:Nnn #1#2#3 {
  \prop_put:Nnn #1 {#2} {#3}
}

\cs_generate_variant:Nn \put_cmd:Nnn {NnV}

\cs_new:Npn \get_cmd:NnN #1#2#3 {
  \prop_get:NnN #1 {#2} #3
}

\prop_new:N \some_prop
\prop_new:N \another_prop
\prop_new:N \x_prop

....
\put_cmd:NnV \some_prop {a-key} \another_prop
....
\get_cmd:NnN \some_prop {a-key} \x_prop
...
\put_cmd:NnV \some_prop {a-key} \x_prop
```

I understand that, by the interface3 documentation, the V-Type expansion isn't supported in the case of Property lists, even though it is in the case of sequences and token lists in general. 
But I would like to ask that to be the case: property lists to also be an officially supported V-type, or, at least, have an (as efficient) alternative (like the R-type suggestion #1068),... and not having to resort to the, rather slow and cumbersome, pattern of
```latex
  \cs_generate_variant:Nn \put_cmd:Nnn {Nne, Nnx}

....
\put_cmd:Nne \some_prop {a-key} {\prop_to_keyval:N \another_prop}
....
\tl_new:N \temp_tl

\get_cmd:NnN \some_prop {a-key} \temp_tl
\prop_put_from_keyval:No \x_prop \temp_tl  % or alike
...
\put_cmd:NnN \some_prop {a-key} {\prop_to_keyval:N \x_prop}
```

From the internal structure of a property list (I know, this isn't a good argument...) sequences and property lists aren't that different. Both are (at the end) specialized token lists. Sequences have a set of scan codes (`\s__seq`) and an item 'in place function' `\__seq_item:n`, whilst a property list has `\s__prop` and `\__prop_chk:w`, `\__prop_pair:wn` respectively, I mean, unless there is the plan to radically change a property list internal as to no longer follow this pattern (and no longer being sort of a token list), I don't really see a reason for it not being an official V-type possible variable (as sequences already are).

Specially because, the above code pattern comes really handy in many scenarios, allowing for a really flexible data representation model, whereas one can store sequences and property lists as 'keys' in a property list, and go from there.

This relates directly with #500 (from where I originally got the idea :) of this codding pattern) and, somewhat to #1068 (which would be kind of alternative) ... and somewhat to #332 (though, then, more in line with #1067)

What worries me the most, the package starray (https://github.com/alceu-frigeri/starray, which is used by https://github.com/alceu-frigeri/ufrgscca (a local theses theme)) makes extensive use of this code pattern, heck the whole idea of it is to store and recover data using a notation like var[index-1].field-a[index-a].field-b[index-b] ...

**Comment by josephwright** [comment]
There's no single value to a `prop` or ` seq`, which is why they are not supported by `V`-type. If/when we sort out serialisation, that will be something that needs to be applied explicitly: I can't image it working as an argument type.

**Comment by josephwright** [comment]
Note that we _have_ changed the internal structure of `prop` data recently, or rather extended it as for larger structures using one macro under-the-hood is not good for performance.

**Comment by Skillmon** [comment]
Sequences are not `V`-type legal, this is also using an implementation detail. The rule is anything that has an `_use:N` accessor and isn't a box, a sequence doesn't have that (`\seq_use:Nn` is not `:N`). From `expl3.pdf`:

> Can be applied to variables which have a `\⟨var⟩_use:N` function (other than boxes), and which therefore deliver a single “value”

A sequence doesn't deliver a single value.

**Comment by alceu-frigeri** [comment]
> There's no single value to a `prop` or ` seq`, which is why they are not supported by `V`-type. If/when we sort out serialisation, that will be something that needs to be applied explicitly: I can't image it working as an argument type.

I understand (sort of), but, per the interface3.pdf, page 4, sequences do are supported (well sequence, fp, int, dim, clist, str, token lists, among a few others)... and if it is the case that a property list internals has to change to support bit sets, I think that would also be the case for big sequences, which are already supported (per documentation).

My use case (I have check it out) already triggered the 'linked property list variant', and so far, everything is working as before.
:/

from interface3.pdf:
![image](https://github.com/latex3/latex3/assets/104397676/b0a371e6-0a31-4b13-a209-0fd6372f8e5d)

**Comment by josephwright** [comment]
The entry for `seq` was a copy-paste mistake - the same list without the split is in `expl3.dtx` and has been for two decades (before `V` existed): I've corrected for the next release.

**Comment by josephwright** [comment]
> Sequences are not `V`-type legal, this is also using an implementation detail. The rule is anything that has an `_use:N` accessor and isn't a box, a sequence doesn't have that (`\seq_use:Nn` is not `:N`). From `expl3.pdf`:

Reminds me we likely should look again at `\box_use:N` - it's more `\box_typeset:N` or similar (@car222222 - comments?).

**Comment by alceu-frigeri** [comment]
fine. understood. so I will enjoy the bug/feature while it lasts... and see what can be done (perhaps rolling back my packages to plain LaTeX then).

**Comment by car222222** [comment]
Re \box_use . . . 
Interesting point, but best discussed elsewhere.

I have been reviewing the “meanings” of _use, _get, _item etc.
