### ISSUE TITLE
`l3opacity`: `\opacity_stroke:n` and `\opactiy_fill:n` not working and/or leading to broken PDF

### ISSUE THREAD

**Issue by jasperhabicht** [latex3/latex3#1472]
Consider the following two MWEs:

MWE A:
```
\DocumentMetadata{}
\documentclass{standalone}
\usepackage{l3draw, l3opacity}
\begin{document}
\ExplSyntaxOn
\draw_begin:
	
\draw_linewidth:n { 4pt }
\opacity_fill:n { 0.5 }
\opacity_stroke:n { 0.5 }
\draw_path_circle:nn { 0cm , 0cm } { 2cm }
\draw_path_use_clear:n { stroke , fill }
	
\draw_end:
\ExplSyntaxOff
\end{document}
```

MWE B:
```
\DocumentMetadata{}
\documentclass{standalone}
\usepackage{l3draw, l3opacity}
\begin{document}
\ExplSyntaxOn
\draw_begin:

\draw_linewidth:n { 4pt }
\opacity_stroke:n { 0.5 }
\draw_path_circle:nn { 0cm , 0cm } { 2cm }
\draw_path_use_clear:n { stroke }

\draw_end:
\ExplSyntaxOff
\end{document}
```

Compiled with pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) (l3draw 2023-05-11, l3opacity 2023-05-11):
MWE A produces a PDF where fill and stroke have both an opacity of 0.5. Everything seems to be ok.
MWE B, however, produces a PDF with a stroke that has no opacity.

Compiled with pdfTeX, Version 3.141592653-2.6-1.40.25 (MiKTeX 24.1) (l3draw 2024-01-04, l3opacity 2024-01-04):
MWE A produces a PDF where the fill has an opacity of 0.5, but the stroke has no opacity. PDF cannot be opened by Acrobat Reader. 
MWE B produces a PDF with a stroke with no opacty. PDF is broken as well.

The bugs do not appear if `\opacity_select:n` is used instead of `\opacity_stroke:n` and `\opactiy_fill:n`. In this case, the PDFs seem to be fine.

**Comment by muzimuzhi** [comment]
The problem of broken PDF can be fixed by initializing two internal token variables (in `l3backend-opacity.dtx` or as a workaround after backend driver is loaded).

```tex
\tl_set:Nn \l__opacity_backend_fill_tl { 1 }
\tl_set:Nn \l__opacity_backend_stroke_tl { 1 }
```

**Comment by josephwright** [comment]
@muzimuzhi Was just working on something else, but I had a feeling where was a missing init step - you want to fix?

**Comment by jasperhabicht** [comment]
> ```
> \tl_set:Nn \l__opacity_backend_fill_tl { 1 }
> \tl_set:Nn \l__opacity_backend_stroke_tl { 1 }
> ```

Nice, that indeed solves the problem of the broken PDF. But the stroke is still not transparent, if I am not mistaken.

**Comment by muzimuzhi** [comment]
> But in MWE B the stroke is still not transparent, if I am not mistaken.

Yes, I'm digging.

**Comment by muzimuzhi** [comment]
Ah ha, a typo:
```diff
--- a/l3backend/l3backend-opacity.dtx
+++ b/l3backend/l3backend-opacity.dtx
@@ -237,7 +237,7 @@
           { opacity.fill #1 }
           { << /ca ~ #1 >> }
         \pdfmanagement_add:nnn { Page / Resources / ExtGState }
-          { opacity.stroke #1 }
+          { opacity.stroke #2 }
           { << /CA ~ #2 >> }
 %<*dvipdfmx|xetex>
         \__kernel_backend_literal_pdf:n
```

**Comment by josephwright** [comment]
@muzimuzhi  You want to fix in a PR or should I just do it directly?

**Comment by muzimuzhi** [comment]
> Looking back, I'm wondering why I use a `tl` here - I'll probably change ;)

Because `str` functions are slower? (I didn't check `l3color`.) Or perhaps you want to use `fp` instead.

> @muzimuzhi You want to fix in a PR or should I just do it directly?

Considering the possible re-typing, you can do it directly.

**Comment by josephwright** [comment]
> > Looking back, I'm wondering why I use a `tl` here - I'll probably change ;)
> 
> Because `str` functions are slower? (I didn't check `l3color`.) Or perhaps you want to use `fp` instead.

Should really be an `fp`, yes - but as we don't do maths, I see why I did it this way now. I'll fix shortly.

**Comment by muzimuzhi** [comment]
@josephwright Currently `m3opacity001.tlg` is partially broken since a `\DocumentMetadata{}` is missing in `m3opacity001.lvt`.
https://github.com/latex3/latex3/blob/b492b56be976754e02b6c9b5af0ffeb0fecc15f7/l3experimental/l3opacity/testfiles/m3opacity001.tlg#L4-L19

Have a work about `\DocumentMetadata{}` in `l3opacity`'s doc.
