### ISSUE TITLE
Status of `./l3packages/l3doc` directory

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1476]
Changed by b688d3d6cf9a16ed5af96012e646b9ccd86e5b47, the [`./l3packages/README.md`](https://github.com/latex3/latex3/blob/main/l3packages/README.md) is now titled

> `l3packages`: Higher-level LaTeX3 Concepts (Deprecated)

without any mention to `l3doc`.

```
l3packages/l3doc
├── build.lua
├── examples
│   ├── basics.dtx
│   ├── build.lua
│   ├── indexing.dtx
│   └── testing.dtx
└── testfiles
    ├── basics.lvt
    └── basics.tlg

3 directories, 7 files
```

What's the status of directory `./l3packages/l3doc`?

**Comment by josephwright** [comment]
It's never gone to CTAN so 'indeterminate' I'd say. I'll move to `l3trial` for the present: seems a better location.
