### ISSUE TITLE
l3doc conflict with `ProvidesExplFile`

### ISSUE THREAD

**Issue by Qinka** [latex3/latex3#1478]
If we add `\providesexplfile` at the beginning of doctex file. The macrocode will ignore new lines.
```latex
% \iffalse
\ProvidesExplFile{test.dtx}{2024/02/28}{0.1.0}{abc}
\documentclass{l3doc}
  \usepackage{amssymb}
  \usepackage{hyperref}
  \usepackage{metalogo}
  \usepackage[normalem]{ulem}
  \usepackage{xeCJK}

  \EnableCrossrefs
  \CodelineIndex
  \RecordChanges
\begin{document}
  \DocInput{\jobname.dtx}
\end{document}
% \fi
% \begin{documentation}
%   \begin{function}{abcd}
%     \begin{syntax}
%       \cs{abcd}\marg{abcd}
%     \end{syntax}
%     Hello world
%   \end{function}
% \end{documentation}
%
% \begin{implementation}
% Hello world
%    \begin{macrocode}
abcd
abcd
abcd
%    \end{macrocode}
% Hello world
% \begin{macro}{\g_asdas_asd}
%    \begin{macrocode}
abcd
abcd
abcd
%    \end{macrocode}
% \end{macro}
% \end{implementation}
```

![图片](https://github.com/latex3/latex3/assets/9249996/4fa73ebe-4e32-44ca-81d0-5041d26468ec)

**Comment by josephwright** [comment]
Well yes: with `\ProvidesExplFile` you are auto-activing `\ExplSyntaxOn`. I suspect you are trying to achieve something that is non-obvious: what's the aim here?

**Comment by Qinka** [comment]
I wrote my own template by referring to someone else's template, then the original version had a `\ProvideFile` in it then in my own latex 3 template, I added the `\ProvideExplFile`. 

The original version uses `\GetFileInfo` to get the version and other information.

I guess I'm not using it right?

**Comment by muzimuzhi** [comment]
Moving `\ProvidesExplFile` behind `\end{document}` should work.

Also if it's a document class, you can use `\ProvidesExplClass`.

**Comment by davidcarlisle** [comment]
I agree that this is probably unsupported use, on the other hand `doc.sty` does use `\obeylines` in `macrocode` and assumes (falsely here) that that will cause line ends to be honoured.

It's almost enough just to reset endlinechar in `\obeylines`

```
\ProvidesExplFile{test.dtx}{2024/02/28}{0.1.0}{abc}
\documentclass{l3doc}
\NewCommandCopy\oldobeylines\obeylines
\renewcommand\obeylines{\endlinechar=13\relax\oldobeylines}
```


but there is a space coming through that I dont have time to trace this morning, so the first `abcd` is out of alignment

![image](https://github.com/latex3/latex3/assets/1268738/4ea7352f-f847-4dc3-adbc-c912c55ffb82)

**Comment by josephwright** [comment]
`\ProvidesExpl...` are intended for files where `expl3` syntax should be on: that's not true here as it's a document. `\ProvidesFile` is really for config files or similar: I wouldn't use it to 'version' a document.

**Comment by josephwright** [comment]
@davidcarlisle  You suggesting a change somewhere?

**Comment by davidcarlisle** [comment]
@josephwright  not necessarily, but `doc` or even the latex 2e kernel could  make `\obeylines` set `\endlinechar`  to `^^M` so that lines do actually get obeyed, if we want to support that packages in general (and `\ExplSyntaxOn` in particular) might locally have changed `\endlinechar`
