### ISSUE TITLE
New function `\fp_if_eq:NN(TF)`

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1499]
`\fp_if_eq:NN(TF)` can be implemented with `\if_meaning:w` hence fast, the same as `\cs_if_eq:NN(TF)`.

Pros: It will speed up comparison of two floating-point variables, hence speed up for example `\draw_transform_matrix_absolute:nnnn` in `l3draw`.
https://github.com/latex3/latex3/blob/3b901d0e778f9ec93c03daf6d68ee97ab5668a7e/l3experimental/l3draw/l3draw-transforms.dtx#L135-L150

Cons: It may break the convention that for data types other than `tl` and `str`, only one of `\<type>_compare:nNn(TF)` and `\<type>_if_eq:(nn|NN)(TF)` are provided, but not both. For `fp` we already have `\fp_compare:nNn(TF)`.

**Comment by josephwright** [comment]
I think not a good idea - in general one should not test floating point equality and I suspect that in the referenced ones we likely should re-visit how things are done).

**Comment by muzimuzhi** [comment]
> in general one should not test floating point equality

True. Obviously I forgot that.
