### ISSUE TITLE
\box_scale:Nnn documentation contains wrong data type

### ISSUE THREAD

**Issue by T-F-S** [latex3/latex3#1502]
The `\box_scale:Nnn` documentation inside `interface3.pdf` says

![grafik](https://github.com/latex3/latex3/assets/7982989/6dc97ada-e06b-4cc6-a791-560840ad8614)

I think, `integer expressions` has to be replaced by `floating-point expressions` which makes sense and is also consistent with the implementation:

```latex
\cs_new_protected:Npn \__box_scale:NnnN #1#2#3#4
  {
    #4 #1
      {
        \fp_set:Nn \l__box_scale_x_fp {#2}
        \fp_set:Nn \l__box_scale_y_fp {#3}
        \__box_scale:N #1
      }
  }
```

**Comment by muzimuzhi** [comment]
Other functions documented in sec. 35.13 "Affine transformations" for box resizing, autosizing and rotation share a similar issue.

**Comment by josephwright** [comment]
@muzimuzhi  I'm not sure I follow: the other functions do require a dimension not an fp

**Comment by muzimuzhi** [comment]
Ah, only box autosizing and rotation functions (accept `<fp expr>`). Resizing functions don't.

`\box_autosize_...` shared internal:
https://github.com/latex3/latex3/blob/c795d95b96de05128ede60fa6379475aeb4bab5e/l3kernel/l3box.dtx#L2295-L2306

`\box_rotate:Nn`
https://github.com/latex3/latex3/blob/c795d95b96de05128ede60fa6379475aeb4bab5e/l3kernel/l3box.dtx#L1800-L1815

Example
```tex
\documentclass{article}

\begin{document}
\ExplSyntaxOn
\hbox_set:Nn \l_tmpa_box { foo }

\box_autosize_to_wd_and_ht:Nnn \l_tmpa_box { sin(50) } { cos(30) }
\box_resize_to_ht:Nn \l_tmpa_box { max(10, \box_ht:N \l_tmpa_box) } % errors
\box_rotate:Nn \l_tmpa_box { pi }
\ExplSyntaxOff
\end{document}
```

**Comment by josephwright** [comment]
@muzimuzhi  Sure, but they intention is they are supplied with dimensions, hence the docs. We could I guess add `\dim_eval:n` here to ensure that - the internal use of `\fp_eval:n` is to work out the scaling factors not to let the user omit units, etc.

**Comment by muzimuzhi** [comment]
@josephwright Maybe the doc of `\box_rotate:Nn <box> {<angle>}` can be improved to mention that `<angle>` accepts an `<fp expr>`, and implementation of autosizing functions can be robusitified with `\dim_to_fp:n`, like how resizing internals are implemented.
https://github.com/latex3/latex3/blob/c795d95b96de05128ede60fa6379475aeb4bab5e/l3kernel/l3box.dtx#L2125-L2144
