### ISSUE TITLE
`l3backend`: `dvips` driver for `draw` does not properly handle scoped boxes/coffins

### ISSUE THREAD

**Issue by jasperhabicht** [latex3/latex3#1504]
It seems that the PS code generated by the `l3draw` driver/backend for `dvips` is not correct so that a stack underflow error occurs when boxes or coffins are scoped inside a `l3draw` environment. No error occurs if the box/coffin is not scoped.

Consider the following MWE (also see [this issue on TeX.SX](https://tex.stackexchange.com/q/712655/47927) where some ideas regarding the reason for this issue have been mentioned already):

```
\documentclass[border=10pt]{standalone}
\usepackage{l3draw}

\begin{document}
    \ExplSyntaxOn
    \draw_begin:
    
        \draw_path_circle:nn { 0cm , 0cm } { 1cm }
        \draw_path_use_clear:n { stroke }
        
        \draw_scope_begin:
        \hbox_set:Nn \l_tmpa_box {foo}
        \draw_box_use:N \l_tmpa_box
        \draw_scope_end:
    
    \draw_end:
    \ExplSyntaxOff    
\end{document}
```

Steps
 1. run `latex` to produce a DVI file;
 2. run `dvips` to produce PS file;
 3. run Acrobat Distiller or some other software parsing the PS file.

**Comment by josephwright** [comment]
Drat: I had hoped to avoid having to manually save/restore stuff as this more-or-less relies on internals of how `dvips` sets things up. But I can't think of another way around this other than using the approach `pgf` does - I guess I'll need to adjust.

**Comment by davidcarlisle** [comment]
Not sure how safe it is but ...

```
\cs_set_protected:Npn \__draw_backend_scope_begin:
{ \__draw_backend_literal:n {
    @endspecial ~ save ~ @beginspecial } }
\cs_set_protected:Npn \__draw_backend_scope_end:
  { \__draw_backend_literal:n { @endspecial ~ restore ~ @beginspecial} }
```

produces

![image](https://github.com/latex3/latex3/assets/1268738/8ae3bd30-b691-4862-b703-3427df86e108)


dvisvgm also manages to understand this dvips syntax enough and the resultibg svg looks like

![image](https://github.com/latex3/latex3/assets/1268738/3a5623d8-98c1-4959-8878-33556afdbc06)

**Comment by josephwright** [comment]
@davidcarlisle  Your idea and my original approach to the box insertion share a common issue. By issuing `@endspecial`, a scope is closed. That means that if a user has a setting before the box, e.g. a transformation or colour change, it would not apply after the box. For example, before the change I've commited,
```latex
\documentclass[border=10pt]{standalone}
\usepackage{l3draw}
\begin{document}
\ExplSyntaxOn
  \draw_begin:
    \color_select:n { red }
    \draw_path_circle:nn { 0cm , 0cm } { 1cm }
    \draw_path_use_clear:n { stroke }
    \hbox_set:Nn \l_tmpa_box {foo}
    \draw_box_use:N \l_tmpa_box
    \draw_path_circle:nn { 0cm , 0cm } { 2cm }
    \draw_path_use_clear:n { stroke }
  \draw_end:
\ExplSyntaxOff    
\end{document}
```
gives the wrong result with `dvips`. So I think a change is needed: I'll make some more notes in the sources and add a test or two.

**Comment by davidcarlisle** [comment]
I saw as I posted that you'd just done a checkin saving and restoring explicitly (which looks cleaner anyway than relying on dvips output quite so much). but I'm surprised it closes a scope if  used as suggested. The idea was you'd end up with

```
@beginspecial % from dvips
@endspecial,   % from the \special content
save                % from the \special content
@beginspecial % from the \special content
@endspecial,  % from dvips
```

so the save is in the outer context and the two empty scopes do nothing, then you do the same wtih restore so following text should be in the original scope.

**Comment by josephwright** [comment]
I meant that if you end up with for example
```
@beginspecial % from start-of-picture
1.0 0.0 0.0 TeXcolorrgb % from a color
@endspecial,   % from the \special content
save                % from the \special content
@beginspecial % from the \special content
...                      % Content here
@endspecial,  % from dvips
```
then the content will come out black not red. As a concrete example, using `dvips` try
```latex
\documentclass{article}
\usepackage{l3draw}
\begin{document}
\ExplSyntaxOn
\cs_set_protected:Npn \__draw_backend_scope_begin:
{ \__draw_backend_literal:n {
    @endspecial ~ save ~ @beginspecial } }
\cs_set_protected:Npn \__draw_backend_scope_end:
  { \__draw_backend_literal:n { @endspecial ~ restore ~ @beginspecial} }
\draw_begin:
  \color_select:n { red }
  \draw_scope_begin:
  \draw_scope_end:
  \draw_path_moveto:n { 0cm, 0cm }
  \draw_path_lineto:n { 10cm, 0cm }
  \draw_path_moveto:n { 5cm, 0cm }
  \draw_path_lineto:n { 5cm , 5cm }
  \draw_path_use_clear:n { stroke }
\draw_end:
\ExplSyntaxOff    
\end{document}
```
with and without the lines commented. (You also see the line thickness revert to the one not set by `l3draw`.)

**Comment by josephwright** [comment]
@davidcarlisle  BTW, `dvips` doesn't add `@beginspecial` automatically, that comes from the `\draw_begin:` implementation.

**Comment by davidcarlisle** [comment]
ah if you get stuf between the begin and end that would be bad:, agreed:-)
