### ISSUE TITLE
`\prop_put_if_new:Nnn` vs `\prop_put_if_not_in:Nnn`

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1511]
Would `\prop_(g)put_if_not_in:Nnn` be easier to understand than the current `\prop_(g)put_if_new:Nnn`?

We have `\<type>_if_in:Nn(TF)` and all other occurrences of "new" in l3kernel function names are verb-like: `new`, `new_conditional`, `(g)clear_new`, `(g)zero_new`.

**Comment by FrankMittelbach** [comment]
My initial reaction would be yes, it seems easier to understand as I wouldn't perceive a "key" as an object and it also fits better with `\prop_if_in:NnTF`.

**Comment by josephwright** [comment]
Make a PR?
