### ISSUE TITLE
visible spaces in l3sys-query results

### ISSUE THREAD

**Issue by davidcarlisle** [latex3/latex3#1529]
l3sys-query reads the result of the shell query with catcode 12 space so that multiple spaces can be detected,  but it should probably use normal spaces in the returned result so they print as space. 

Currently spaces show as visible space for both `ls` and `pwd`

![image](https://github.com/latex3/latex3/assets/1268738/ec915088-298a-4213-8100-b62bcd221e46)

A suggested fix is

![image](https://github.com/latex3/latex3/assets/1268738/2ac307c5-d96e-46fa-9334-8b34662cc210)

```
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage{l3sys-query}

\ExplSyntaxOn
\cs_set_protected:Npn \__sys_get_query_auxii:nnnN #1#2#3#4
{
    \sys_if_shell:T
      {
        \sys_get_shell:nnN
          { l3sys-query~#1 #2 #3 }
          {
            \int_step_inline:nnn { 0 } { `a - 1 }
              { \char_set_catcode_other:n {##1} }
            \int_step_inline:nnn { `Z + 1 } { 127 }
              { \char_set_catcode_other:n {##1} }
            \tex_endlinechar:D 13 \scan_stop:
          }
        \l__sys_tmp_tl
        \tl_if_empty:NF \l__sys_tmp_tl
          {
            \exp_after:wN \__sys_get_query:Nw \exp_after:wN #4
            \l__sys_tmp_tl \q_stop
            \tl_replace_all:Nen #4 {\char_generate:nn{32}{12} } {~}
          }
      }
    }

\ExplSyntaxOff
\begin{document}

\QueryWorkingDirectory\result

X \texttt{\result}

\QueryFiles{*.tex}{A \texttt{#1}\par}


\bigskip

\ExplSyntaxOn
\long\def\q#1{
  \sys_split_query:nnN {ls}{#1}\l_tmp_seq
 \seq_map_inline:Nn \l_tmp_seq
}
\ExplSyntaxOff

\q{*.tex}{B \texttt{#1}\par}

\end{document}
```

This could be optimised  a bit to avoid the inline `\char_generate:nn{32}{12}` but would require some re-arrangement to get a literal catcode 12 space at that point and possibly not worth it as the time for a single char_generate will be negligable compared to the cost of the shell call itself.

**Comment by davidcarlisle** [comment]
if we do want to optimise I guess simplest is to wrap in a `\tex_lowercase:D` (as done elsewhere in this code) but guard `\`Z+1`  from being lowercased by replacing it by  `91`

**Comment by josephwright** [comment]
Do we want catcode 10 here, or would catcode 13 be more appropriate?

**Comment by josephwright** [comment]
I suggest making the change in `\@@_get_query:Nw ` - it's short so would be easy to `e`-type expand and include the literal  space as you suggest.

**Comment by davidcarlisle** [comment]
I did wonder, maybe catcode 13, then you could easily get visible spaces if you wanted without having to tl_replace them all again.

**Comment by josephwright** [comment]
Indeed: I think that's safe and also handy - I'll make the change and document the catcode setup.

**Comment by josephwright** [comment]
Sorted - I've also corrected and documented the rest of the catcode setup.
