### ISSUE TITLE
support of CMYK colors in dvisvgm backend

### ISSUE THREAD

**Issue by mgieseki** [latex3/latex3#1538]
I'm not sure if this is the correct place to ask or if it belongs to TikZ. Please let me know if it's the latter.

As of [dvisvgm 3.3](https://github.com/mgieseki/dvisvgm/releases/tag/3.3) the conversion of CMYK colors to RGB has been modified so that they are now more similar to those shown by Ghostscript and several PDF viewers. When using the dvips backend, the colors can be processed accordingly because the DVI file contains `color` specials. The dvisvgm backend, on the other hand, sometimes creates literal SVG fragments with the color hard-coded as RGB hex values. In this case, the CMYK to RGB conversion takes place in a LaTeX (or TikZ) package and dvisvgm can't apply its color interpolation.

Here's an example:

```latex
\documentclass[dvisvgm]{standalone}
\usepackage[cmyk]{xcolor}
\usepackage{tikz}
\definecolor{mycolor}{cmyk}{1, 0, 1, 0} 
\begin{document}
\begin{tikzpicture}
  \fill[mycolor] circle(2);
\end{tikzpicture}
\end{document}
```

The resulting SVG graphics created with dvips (left) and dvisvgm backend:

![cmyktest-ps](https://github.com/latex3/latex3/assets/3620467/57a9783e-22e0-4761-980a-7139f6c986e3) ![cmyktest](https://github.com/latex3/latex3/assets/3620467/3131db74-b719-4d8b-b7c0-2ad908df1684)

Here are the corresponding DVI snippets:

```asm
xxx: 'color push cmyk 1 0 1 0'
xxx: 'ps:: 56.69362 0.0 moveto '
xxx: 'ps:: 56.69362 31.31142 31.31142 56.69362 0.0 56.69362 curveto '
xxx: 'ps:: -31.31142 56.69362 -56.69362 31.31142 -56.69362 0.0 curveto '
xxx: 'ps:: -56.69362 -31.31142 -31.31142 -56.69362 0.0 -56.69362 curveto '
xxx: 'ps:: 31.31142 -56.69362 56.69362 -31.31142 56.69362 0.0 curveto '
xxx: 'ps:: closepath '
```

```asm
xxx: 'dvisvgm:raw <g stroke="#0f0" fill="#0f0">{?nl} '
xxx: 'dvisvgm:raw <path d=" '
xxx: 'dvisvgm:raw M 56.90549 0.0 C 56.90549 31.42844 31.42844 56.90549 0.0 56.90549 ... '
xxx: 'dvisvgm:raw " stroke="none"/>{?nl} '
xxx: 'dvisvgm:raw </g>{?nl} '
```

It would be great if the dvisvgm backend could create `color` specials too, e.g. something like this:
```asm
xxx: 'color push cmyk 1 0 1 0'
xxx: 'dvisvgm:raw <g stroke="{?color}" fill="{?color}">{?nl} '
```

To apply different stroke and fill colors, the SVG elements could also be split into several specials:
```asm
xxx: 'color push cmyk 1 0 1 0'
xxx: 'dvisvgm:raw <g stroke="{?color}"'
xxx: 'color pop'
xxx: 'color push cmyk 1 0 1 0'
xxx: 'dvisvgm:raw fill="{?color}">{?nl} '
```

**Comment by u-fischer** [comment]
In your example the code is clearly from the  tikz backend driver, the relevant code is in pgfsys-common-svg.def and pgfsys-dvisvgm.def. 

So you should make for this a feature request at the pgf/tikz repo.

But I checked also the l3draw code, and it applies to the stroke color a conversion:

~~~~
\documentclass[dvisvgm]{article}
\usepackage{l3draw}

\begin{document}\showoutput
\ExplSyntaxOn
%temporary bug fix
\cs_set_eq:NN\__color_backend_cmyk:w\__color_backend_stroke_cmyk:w

\color_set:nnn{mycolor}{cmyk}{1, 0, 1, 0}
\tl_set:Nn\l_color_fixed_model_tl{cmyk}

\draw_begin:
\draw_path_moveto:n { 0cm , 0cm }
\draw_path_lineto:n { 1cm , 1cm }
\draw_path_lineto:n { 2cm , 1cm }
\draw_path_lineto:n { 3cm , 0.5cm }
\draw_path_lineto:n { 3cm , 0cm }
\color_stroke:n { mycolor }
\color_fill:n { mycolor }
\draw_path_use_clear:n { fill , stroke }
\draw_end:
\ExplSyntaxOff
\end{document}
~~~~

This shows these specials:

~~~~
.......\special{dvisvgm:raw <g stroke="rgb(-0%,-100%,-0%)">{?nl}}
.......\special{color push cmyk 1.0 0.0 1.0 0.0}
~~~~


I assume that is wrong for your use case too and the stroke color should be set differently?

**Comment by josephwright** [comment]
Is there an (easy) way to detect the version of `dvisvgm` within the output? We need to allow for older and newer versions, at least for a transition.

**Comment by mgieseki** [comment]
> In your example the code is clearly from the tikz backend driver, the relevant code is in pgfsys-common-svg.def and pgfsys-dvisvgm.def.
> So you should make for this a feature request at the pgf/tikz repo.

Thank you for the fast reply and the helpful information. I'll post a feature request there too.

> ```
> .......\special{dvisvgm:raw <g stroke="rgb(-0%,-100%,-0%)">{?nl}}
> .......\special{color push cmyk 1.0 0.0 1.0 0.0}
> ```
> 
> I assume that is wrong for your use case too and the stroke color should be set differently?

Yes, right. Since there's no information about the intended CYMK color space, dvisvgm can't do the conversion here either.


> Is there an (easy) way to detect the version of `dvisvgm` within the output? We need to allow for older and newer versions, at least for a transition.

What output do you refer to exactly? dvisvgm adds a comment to the generated SVG files with version information.
However, I think, it's not necessary to handle the older dvisvgm releases differently. The `{?color}` macro has already been available since version 0.7.1. It just used a different conversion function for CMYK colors resulting in different RGB hex values. The suggested mixture of `color` and `dvisvgm:raw` specials should work with both the previous and latest versions.

**Comment by mgieseki** [comment]
Indeed. I've made a note to extend the explanations of the macros. Usually it only becomes apparent in cases like this that the initially added information is too brief. So thanks for the feedback.

**Comment by mgieseki** [comment]
Ok, I see. Wouldn't it be possible to switch the stroke/fill color using classic `color` specials? I guess, the backend knows the two colors as they are currently hard-coded in the SVG attributes. I would have thought you could set them with `color` specials instead of directly writing the attribute values even if that's somewhat cumbersome:
```asm
xxx: 'color push cmyk 0 1 1 0'
xxx: 'dvisvgm:raw <g stroke="{?color}"'
xxx: 'color pop'
xxx: 'color push cmyk 1 0 1 0'
xxx: 'dvisvgm:raw fill="{?color}">{?nl} '
```
But maybe it's more complex and this color swapping would break the current usage of the stack.
Of course, I could also add a separate stack for the stroke color in one of the next updates.

**Comment by josephwright** [comment]
@mgieseki  That approach occurred to me to: I'm going to see how well it works in practice.

**Comment by josephwright** [comment]
Taking a look, seems we stick with current approach for other models and just adjust CMYK.

**Comment by josephwright** [comment]
I think this is done ...
