### ISSUE TITLE
char_generate:nn creates new text input level now?

### ISSUE THREAD

**Issue by user202729** [latex3/latex3#1540]
Consider the following code.

```
\documentclass{article}
\begin{document}

\ExplSyntaxOn
\errorcontextlines=15
\def\f{\expandafter \expandafter \expandafter\f \char_generate:nn{32}{12} }
\f
\ExplSyntaxOff

\end{document}
```

In LuaLaTeX:

```
! TeX capacity exceeded, sorry [text input levels=15].
```

in PDFLaTeX and XeLaTeX:

```
! TeX capacity exceeded, sorry [input stack size=10000].
```

I think this was not the case in previous versions.

I'm not sure if this is LuaLaTeX regression or latex3 regression (probably the former), but LaTeX3 can workaround it by expanding something "over" the resulting token as follows:

```
\documentclass{article}
\usepackage{etoolbox}
\begin{document}

\ExplSyntaxOn
\errorcontextlines=15
\patchcmd\__char_generate_aux:nnw {
	\exp_after:wN \exp_end: \tex_Ucharcat:D #1 \exp_stop_f: #2 \exp_stop_f:
} {
	\exp_after:wN
		\exp_after:wN
	\exp_after:wN
		\exp_end:
	\exp_after:wN
		\exp_after:wN
	\tex_Ucharcat:D #1 \exp_stop_f: #2 \exp_stop_f:
		\empty
} {\typeout{success}} {\errmessage{failure}}
\def\f{\expandafter \expandafter \expandafter\f \char_generate:nn{32}{12} }
\f
\ExplSyntaxOff

\end{document}
```

Performance is worse though. Or maybe `token.create()` could be better?

**Comment by josephwright** [comment]
I'm not sure what you are after here: this is an error condition ...

**Comment by josephwright** [comment]
(I get the same error in TL'20 final, so at least the past five years LuaTeX/`expl3` code.)

**Comment by muzimuzhi** [comment]
`\char_generate:nn` was added on 2015-09-09. Using LuaLaTeX, Overleaf's TL2015 image raised the same error
```
! TeX capacity exceeded, sorry [text input levels=15].
```

**Comment by josephwright** [comment]
@muzimuzhi  Thanks - I could I guess have check with my older TL installs, but I didn't feel it was needed

**Comment by user202729** [comment]
Looks like the behavior has been there since forever though.

The actual issue is that the input stack does not unwind correctly when it is a text input level. The following example (where `\f` repeatly spits out and then immediately gobble up the token) does not give an error in PDFLaTeX, but gives an error in LuaLaTeX:
```
\documentclass{article}
\begin{document}

\ExplSyntaxOn
\errorcontextlines=15
\count0=1000000
\def\f#1{
	\advance\count0 by -1\relax
	\int_compare:nNnF {\count0}={0} {
		\expandafter \expandafter \expandafter\f \char_generate:nn{65}{12}
	}
}
\f A
\ExplSyntaxOff

\end{document}
```
See also my question https://tex.stackexchange.com/q/640922/250119

**Comment by josephwright** [comment]
Looks to me that this is an engine issue

**Comment by user202729** [comment]
If I edit the definition to always use `put_next` then it works without problem.

```lua
	luacmd('tex_Ucharcat:D', function()
		local charcode = scan_int()
		local catcode = scan_int()
		put_next(token_create(charcode, catcode)) -- or token_new, I think the difference is just the latter creates frozen version of tokens...?
	end, 'global')
```

Thought?

I haven't benchmarked, in the original source code there's a remark that we selectively use sprint() or cprint() depends on whether catcode is 10.

**Comment by josephwright** [comment]
@zauguin This is your area ...

**Comment by muzimuzhi** [comment]
Current emulation of `\tex_Ucharcat:D` in luatex
https://github.com/latex3/latex3/blob/fe1015d6020fde3b93a2489b0200d8e7d5a74dbe/l3kernel/l3names.dtx#L1485-L1502

**Comment by zauguin** [comment]
> If I edit the definition to always use `put_next` then it works without problem.
> 
> ```lua
> 	luacmd('tex_Ucharcat:D', function()
> 		local charcode = scan_int()
> 		local catcode = scan_int()
> 		put_next(token_create(charcode, catcode)) -- or token_new, I think the difference is just the latter creates frozen version of tokens...?
> 	end, 'global')
> ```
> 
> Thought?
> 
> I haven't benchmarked, in the original source code there's a remark that we selectively use sprint() or cprint() depends on whether catcode is 10.

We tried that originally but was roughly 20% slower. If we need to work around this otherwise to avoid consuming text input levels it might be worth it, but we need some benchmarks for this.
