### ISSUE TITLE
(Not a bug) \tl_gset:Nx is no longer directly mapped to \xdef?

### ISSUE THREAD

**Issue by user202729** [latex3/latex3#1541]
Instead, now it is \exp_args:NNx \tl_gset:Nn. Is this change intentional?

**Comment by josephwright** [comment]
Can I ask what the context is here? I'm wondering if we've missed something?

**Comment by muzimuzhi** [comment]
> PR #1271

More specifically, the change took place in 4cca6b1d (Define x-type variants using \cs_generate_variant:Nn, 2023-09-27).

**Comment by user202729** [comment]
> Can I ask what the context is here? I'm wondering if we've missed something?

Nothing much, just notice that one of my internal libraries (relying on some internal implementation detail) break because of this change.
