### ISSUE TITLE
Tag 2024-05-08 not merged into main branch

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1547]
https://github.com/latex3/latex3/releases/tag/2024-05-08

**Comment by josephwright** [comment]
I don't follow: for me the tag is showing as even with `main`.

**Comment by muzimuzhi** [comment]
For what I saw they are not even:
- the HEAD of `main` (https://github.com/latex3/latex3/tree/main) was 17783884 (Merge tag '2024-04-11-dev', 2024-04-29) but
- tag `2024-05-08` (https://github.com/latex3/latex3/releases/tag/2024-05-08) was on ed92a677 (Step release tag, 2024-05-08)

**Comment by josephwright** [comment]
Oh, forgot to push `main` ...
