### ISSUE TITLE
l3backend-dvips.pro not found by kpsewhich despite being present

### ISSUE THREAD

**Issue by d125q** [latex3/latex3#1548]
As of [yesterday’s update](https://github.com/latex3/latex3/releases/tag/2024-05-08), `dvips` began failing:
```
dvips: ! Couldn't find header file: l3backend-dvips.pro
```

I can see
```
$TEXMFDIST/tex/latex/l3backend/l3backend-dvips.pro
$TEXMFDIST/tex/latex-dev/l3backend/l3backend-dvips.pro
```
and they are also present in the `ls-R`.

However, `kpsewhich -a l3backend-dvips.pro` doesn’t find anything, even though `kpsewhich -a l3backend-dvips.def` and others work.

**Comment by josephwright** [comment]
OK, I see what is up I think: I'll recreate the relevant zip files and upload to CTAN

**Comment by u-fischer** [comment]
the path is different, currently (before the update) the file is in `c:/texlive/2024/texmf-dist/dvips/l3backend/l3backend-dvips.pro`

**Comment by josephwright** [comment]
@u-fischer  There was an oversight in the build script, so the `.pro` file is missing from the TDS zip. As soon as CTAN is back up, I'll re-upload.

**Comment by josephwright** [comment]
Fix uploaded to CTAN
