### ISSUE TITLE
`\GetDocumentCommandArgSpec` and friends cannot handle optimized m-type cmds and envs

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1550]
```tex
\documentclass{article}
\usepackage{xparse}

\DeclareDocumentCommand { \null } { } { }
\GetDocumentCommandArgSpec { \null } \ShowCommand { \ArgumentSpecification }

\begin{document}
\end{document}
```

gives
```
> \ArgumentSpecification=macro:
->\null code .
<argument> \ArgumentSpecification 
```
while since `\null` takes no arguments the `\ArgumentSpecification` here should be an empty macro.

Example is adapted from tests in `xparse009.lvt`.

https://github.com/latex3/latex3/blob/2e6909e5374f85062d8309836a3eb7301d2c5fca/l3packages/xparse/testfiles/xparse009.lvt#L17-L34

**Comment by josephwright** [comment]
True but this is there for dealing with older code anyway - I agree we should address but it's not a high priority.
