### ISSUE TITLE
Loading 'expl3.sty' aborted when I compile documentation using xelatex

### ISSUE THREAD

**Issue by zousiyu1995** [latex3/latex3#1552]
My latex toolchain is TeX Live 2024 and I have updated all packages to the latest. When I use `xelatex` to compile my tex file, the xelatex stops because of an error. Here is the error log,

```shell
! LaTeX Error: Mismatched LaTeX support files detected.
(LaTeX)        Loading 'expl3.sty' aborted!
(LaTeX)        
(LaTeX)        The L3 programming layer in the LaTeX format
(LaTeX)        is dated 2024-05-08, but in your TeX tree the files require
(LaTeX)        at least 2024-05-27.

For immediate help type H <return>.
 ...                                              
                                                  
l.78      \ExplLoaderFileDate{expl3.sty}}
                                         %
? 
! Emergency stop.
 ...                                              
                                                  
l.78      \ExplLoaderFileDate{expl3.sty}}
                                         %

The most likely causes are:
 - A recent format generation failed;
 - A stray format file in the user tree which needs to be removed or rebuilt;
 - You are running a manually installed version of expl3.sty
   which is incompatible with the version in LaTeX.

LaTeX will abort loading the incompatible support files but this may lead to
later errors. Please ensure that your LaTeX format is correctly regenerated.
```

As suggested by the log, I tried to regenerate or rebuild the format. However, the manager told me that no appropriate script or program found: fmtutil.

![image](https://github.com/latex3/latex3/assets/7608449/5e01fceb-d0f5-46c3-8dfc-ea2aea863926)

![image](https://github.com/latex3/latex3/assets/7608449/d6fd2e05-909b-4a11-bb91-d01b08bce6db)

**Comment by u-fischer** [comment]
You could try to rebuilt the format on the command line with `fmtutil-sys --byfmt xelatex`, but generally this sounds like a problem with your texlive installation and you should report that on the texlive mailing list. 

(I can't reproduce your problem, I just tried to rebuilt the formats in the texlive shell and it worked without problems).

**Comment by zousiyu1995** [comment]
> You could try to rebuilt the format on the command line with `fmtutil-sys --byfmt xelatex`, but generally this sounds like a problem with your texlive installation and you should report that on the texlive mailing list.
> 
> (I can't reproduce your problem, I just tried to rebuilt the formats in the texlive shell and it worked without problems).

Thank you for your suggestion. I will check this again and report to texlive group.
