### ISSUE TITLE
 Minor formatting in `l3prop`, `l3keys` and `l3int` doc

### ISSUE THREAD

**Issue by pablgonz** [latex3/latex3#1553]
Hello, some minor formatting things in the documentation:

In `l3prop` syntax need indent:
- `\prop_set_from_keyval:Nn`:
https://github.com/latex3/latex3/blob/993224921aa662b6dc788bfbc87f7a0d729fd7db/l3kernel/l3prop.dtx#L183-L189
- `\prop_const_from_keyval:Nn`:
https://github.com/latex3/latex3/blob/993224921aa662b6dc788bfbc87f7a0d729fd7db/l3kernel/l3prop.dtx#L207-L213
- `\prop_const_linked_from_keyval:Nn`:
https://github.com/latex3/latex3/blob/993224921aa662b6dc788bfbc87f7a0d729fd7db/l3kernel/l3prop.dtx#L226-L232
- `\prop_put_from_keyval:Nn`:
https://github.com/latex3/latex3/blob/993224921aa662b6dc788bfbc87f7a0d729fd7db/l3kernel/l3prop.dtx#L349-L355

In `l3keys` some `%` in example not need:
https://github.com/latex3/latex3/blob/993224921aa662b6dc788bfbc87f7a0d729fd7db/l3kernel/l3keys.dtx#L652-L653

In `l3int`, There are two **TeX hackers** note that say more or less the same thing:
https://github.com/latex3/latex3/blob/993224921aa662b6dc788bfbc87f7a0d729fd7db/l3kernel/l3int.dtx#L103-L117
and
https://github.com/latex3/latex3/blob/993224921aa662b6dc788bfbc87f7a0d729fd7db/l3kernel/l3int.dtx#L128-L141

And the last one, in `source3.pdf` from `l3kernel-dev`, pag 1515, you see some _white spaces_:

![imagen](https://github.com/latex3/latex3/assets/2289461/74d032f2-c413-44eb-a45d-00db063900c9)

**Comment by muzimuzhi** [comment]
Should be addressed in c04340ff (Fix typos (see #<span></span>1553), 2024-06-21) and 727c6876 (Drop a note, 2024-06-21).
