### ISSUE TITLE
Changed behavior of `\text_titlecase:n` on text with beginning space

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1562]
Original report: https://github.com/cgnieder/xsim/issues/127

Before l3kernel [2023-10-23](https://github.com/latex3/latex3/blob/develop/l3kernel/CHANGELOG.md#2023-10-23), `\text_titlecase:n {~foo~bar}` expands to `␣Foo␣bar`, i.e., the word right after leading space(s) is treated as the first word hence title-cased.

Since l3kernel 2023-10-23, `\text_titlecase:n` is deprecated and since then `\text_titlecase:n {~foo~bar}` expands to `␣foo␣bar`, i.e., the word right after leading space(s) is not title-cased any more.

This new behavior is inherited from `\text_titlecase_first:n`
https://github.com/latex3/latex3/blob/90bed66c868583929d582dc53c206486e9e8b5b7/l3kernel/l3deprecation.dtx#L471-L473

https://github.com/latex3/latex3/compare/2023-10-10...2023-10-23

```tex
\documentclass{article}
\begin{document}

\def\mytext{foo bar}

\ExplSyntaxOn
[\text_titlecase:n { foo~bar }] \space
[\text_titlecase:n {~foo~bar }]
\ExplSyntaxOff

\end{document}
```

**Comment by josephwright** [comment]
The change was by-design, so I'm not sure what I can say here other than 'fix your input'.

**Comment by muzimuzhi** [comment]
For non-deprecated functions, maybe polish doc of `\text_titlecase_first:n`?

**Comment by josephwright** [comment]
I've added a minor tweak - if you feel we need a bit more, please make a PR :)

**Comment by muzimuzhi** [comment]
Doc is clearer than before, more or less. Thank you.
