### ISSUE TITLE
Mention quarks and scan marks in naming convention

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1565]
Quarks (`\q_...`) and scan marks (`\s_...`) are special constants, but the `\q_` and `\s_` prefixes are not listed in the language's naming scheme, see `texdoc expl3` (this opens `interface3.pdf` in recent `texdoc`), sec. 1.1 "Naming functions and variables" and `texdoc expl3.pdf`, sec. 3 "The naming scheme".

The incomplete naming scheme may make third-party LaTeX3 tokenizers harder to run perfectly, see https://github.com/jlelong/vscode-latex-basics/pull/94 for an example.

**Comment by josephwright** [comment]
Do you want to make a PR or do you want me to do something?

**Comment by muzimuzhi** [comment]
I'll make a PR.
