### ISSUE TITLE
Documentation of \file_if_exist:nTF

### ISSUE THREAD

**Issue by fpantigny** [latex3/latex3#1573]
In the current version of `interface3.pdf` (Released 2024-07-20), the documentation for `\file_if_exist:nTF` is:

> Tests if _⟨file name⟩_ is found in the path as detailed for `\file_if_exist:nTF`.

It seems to be a recursive documentation :-)

**Comment by muzimuzhi** [comment]
My fault, see https://github.com/latex3/latex3/pull/1427#discussion_r1468817448. I'll provide a PR.
