### ISSUE TITLE
Should `bitset` and `clist` support `V`-type expansion?

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1575]
`interface3.pdf` says `V`-type expansion can be applied to `bitset` and `clist` variables, but `expl3.pdf` says no, because they both don't have a `\<var>_use:N` function.

- `interface3.pdf` (2024-07-20), sec. 1.1 Naming functions and variables, page 4
  https://github.com/latex3/latex3/blob/5ada012ff4c9acd53e9b9814c8a860a84d84b73c/l3kernel/doc/source3body.tex#L305-L320
- `expl3.pdf` (2024-07-20), sec. 4 Expansion control, page 10
  https://github.com/latex3/latex3/blob/5ada012ff4c9acd53e9b9814c8a860a84d84b73c/l3kernel/expl3.dtx#L650-L656

The code behavior is that they both can be `V`-expanded, though that relies on their current implementation.

I think for `clist` a new `\clist_use:N <clist var>` which can be used as a quicker version of `\clist_use:Nn <clist var> {,}` (a `,`<sub>12</sub>) is useful. A `\bitset_use:N`, which if defined would do exactly the same as `\bitset_to_bit:N`, seems less desired.

It's arguable whether a `clist` or `bitset` delivers a single value, which was the reason used to reject `prop` and `seq` in https://github.com/latex3/latex3/issues/1466#issuecomment-1953156467. Considering `clist` and `bitset` do both have more unified serialisation forms than `prop` and `seq`, maybe the `\<var>_use:N` restriction can be relaxed or modified.

**Comment by muzimuzhi** [comment]
In `interface3.pdf`/`source3body.tex`,
- `clist` was one of the original members of the list, see 1a7615ef (Doc e-type at start of interfaces3, and new variable types (fixes #<span></span>528) [ci-skip], 2019-02-10)
- `bitset` was added to the list in e1ab799d (Add bitset to the lists of variabe types, 2023-11-16), when `bitset` was moved to l3kernel.

**Comment by josephwright** [comment]
Easy to adjust - just need a decision from the team as a whole.

**Comment by davidcarlisle** [comment]
I think probably I'd add the V here it doesn't really have any cost and arguably makes things more consistent and especially for clist would probably get used

**Comment by josephwright** [comment]
We decided on balance this does make sense - will be in the next release
