### ISSUE TITLE
Why \coffin_set_eq:NN checks existence of its 1st arg, not the 2nd

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1580]
https://github.com/latex3/latex3/blob/9b624e6c3ec069d7f1ad74c12b2daacba5a12ebe/l3kernel/l3coffins.dtx#L867-L890

Since the `coffin` module was first added to this repo (see a9caf7ed9ea2094a6662db3c424dea8270fe0e68), `\coffin_(g)set_eq:NN` had checked the existence of its `#1`, instead of the `#2`, before doing real works. Why?

Currently, if `#2` is an undefined control sequence, then `\coffin_(g)set_eq:NN` raises several low-level errors, starting from a helpful "Undefined control sequence.". But if `#2` is a non-coffin box register, then `\coffin_(g)set_eq:NN` sets `#1` to a fake coffin with broken inner structures without errors.

```tex
\documentclass{article}

\begin{document}
\ExplSyntaxOn
% #1 is undefined => error "Undefined coffin '\my_undefined'"
\coffin_set_eq:NN \my_undefined \l_tmpa_coffin
% #1 is not a coffin var => error "Undefined coffin '\my_undefined'"
\coffin_set_eq:NN \l_tmpa_box \l_tmpa_coffin

% #2 is a plain box register =>
% no error but #1 is set to a fake conffin with broken inner structures
\coffin_set_eq:NN \l_tmpa_coffin \l_tmpa_box

% #2 is undefined =>
% several low-level errors starting with "Undefined control sequence."
\coffin_set_eq:NN \l_tmpb_coffin \my_undefined
\ExplSyntaxOff
\end{document}
```

**Comment by josephwright** [comment]
Probably I messed up: feel free to submit a PR :)

**Comment by muzimuzhi** [comment]
A follow-up question: should the existence check be done (directly or indirectly) in most `coffin` functions?

Currently `\coffin_clear:N`, `\hcoffin_set:N(n|w)`, `\vcoffin_set:Nn(n|w)`, `\coffin_set_eq:NN`, `\coffin_set_horizontal_pole:Nnn`, `\coffin_set_vertical_pole:Nnn` (and their global versions), `\coffin_(show|log):N`, and `\coffin_(show|log)_structure:N` all do existence checks before real operations.

Other functions that do coffin affine transformations, join and use coffins, and provide coffin diagnostics do not.

**Comment by FrankMittelbach** [comment]
it's an interesting question. Normally we do not make runtime tests for values, not even sure we should do it for registers unless we are running in debug/checking mode. After all it slows down processing to check for programming errors that aren't something that (normally) can only be detected at runtime.

**Comment by jasperhabicht** [comment]
Maybe rather something for `debug`?

**Comment by josephwright** [comment]
We have a check because:
```latex
% \begin{macro}{\@@_if_exist:NT}
%   Several of the higher-level coffin functions would give multiple
%   errors if the coffin does not exist. So a wrapper is provided to deal
%   with this correctly, issuing an error on erroneous use.
```
I'll correct the code.

**Comment by josephwright** [comment]
On the performance question, coffins are relatively slow, so the thinking was this is a reasonable addition to something that will be not-fast even without it.

**Comment by muzimuzhi** [comment]
> We have a check because:
> 
> ```
> % \begin{macro}{\@@_if_exist:NT}
> %   Several of the higher-level coffin functions would give multiple
> %   errors if the coffin does not exist. So a wrapper is provided to deal
> %   with this correctly, issuing an error on erroneous use.
> ```

So maybe other coffin functions (listed in https://github.com/latex3/latex3/issues/1580#issuecomment-2307969117) need this check too.

**Comment by josephwright** [comment]
> A follow-up question: which `coffin` functions need do the existence check?
> 
> Currently `\coffin_clear:N`, `\hcoffin_set:N(n|w)`, `\vcoffin_set:Nn(n|w)`, `\coffin_set_eq:NN`, `\coffin_set_horizontal_pole:Nnn`, `\coffin_set_vertical_pole:Nnn` (and their global versions), `\coffin_(show|log):N`, and `\coffin_(show|log)_structure:N` all do existence checks before real operations.
> 
> Other functions that do coffin affine transformations, join and use coffins, and provide coffin diagnostics do not.

I checked over the list of places using the internal sanity check, and those are all now correct; I did not add any new ones as it will worry @FrankMittelbach  :) (More seriously, the check is mainly applied _via_ internal paths, the _set_eq_ case is unusual in that the test is applied directly.)
