### ISSUE TITLE
`\fp_if_nan:nTF` throws error when evaluating non-math strings

### ISSUE THREAD

**Issue by jasperhabicht** [latex3/latex3#1582]
`\fp_if_nan:nTF` throws an error when evaluating strings that can't be parsed as mathematical expression. 

I would expect that it evaluates such strings as `nan` and thus returns `true`. This also was the behaviour upto recently, if I am not mistaken.

```
\documentclass{article}
\begin{document}
\ExplSyntaxOn
    \fp_if_nan:nTF { x } { Y } { N }
\ExplSyntaxOff
\end{document}
```

---

If the current behavior is indeed the expected behaviour, I think it would be nice to have a command to test whether a token list is a floating point expression or not.

**Comment by muzimuzhi** [comment]
`\fp_if_nan:nTF` was added in [l3kernel 2019-08-25](https://github.com/latex3/latex3/blob/develop/l3kernel/CHANGELOG.md#2019-08-25). Testing on overleaf.com, TeX Live images from 2019 to 2024 all give the same error
```
<argument> \LaTeX3 error: 
                           Unknown fp word x.
```
so I think current behavior is expected.
```tex
\documentclass{article}
\ifdefined\ExplSyntaxOn\else \usepackage{expl3} \fi
\begin{document}
\fmtname, \fmtversion
\ExplSyntaxOn
    \fp_if_nan:nTF { x } { Y } { N }
\ExplSyntaxOff
\end{document}
```
