### ISSUE TITLE
Feature request:  \use_i_ii:nn 

### ISSUE THREAD

**Issue by daleif** [latex3/latex3#1584]
With a definition like this

```
\cs_new:Npn \use_i_ii:nn #1#2 { #1#2 }
```

It is needed for an example like this

```
\documentclass[a4paper]{article}
\usepackage{tabularx,array}

\newcolumntype{K}{@{}p{2cm}}
\newcolumntype{Y}{>{\raggedright\arraybackslash}X@{}}

\ExplSyntaxOn

\cs_new:Npn \_cv_map_dual:nn #1#2 { #1 & #2 \\ }
\seq_clear:N \l_tmpa_seq
\seq_put_right:Nn \l_tmpa_seq { {1}{A} }
\seq_put_right:Nn \l_tmpa_seq { {2}{B} }
\seq_put_right:Nn \l_tmpa_seq { {3}{C} }

\cs_new:Npn \use_i_ii:nn #1#2 { #1#2 }


\NewDocumentCommand\Foo{}
{
  \subsection*{Foo}
  \noindent
  \begin{tabularx}{\textwidth}{K Y}
    % \seq_map_inline:Nn \l_tmpa_seq { \_cv_map_dual:nn ##1 }
    \seq_map_tokens:Nn \l_tmpa_seq { \use_i_ii:nn \_cv_map_dual:nn }
  \end{tabularx}
}
\ExplSyntaxOff

\NewDocumentCommand\Bar{}
{
  \subsection*{Bar}
  \noindent
  \begin{tabularx}{\textwidth}{K Y}
    1 & A \\
  \end{tabularx}
}

\begin{document}

\noindent\hrule

\Foo

\Foo

\noindent\hrule


\Bar

\Bar
\end{document}
```

As we need to shed the outer braces in order for `\_cv_map_dual:nn` to access the inner data.

`\seq_map_inline:Nn` cannot be used in this case as it generate a blank line in the table.

**Comment by muzimuzhi** [comment]
5f81164a (Add \use_i_ii:nn, 2024-08-28) added it.

**Comment by davidcarlisle** [comment]
Note the requested function is already available under the name `\use:nn`

**Comment by daleif** [comment]
@muzimuzhi by name `\exp_last_unbraced:Nn` would make more sence when reading the code. Though not defined by default.

**Comment by FrankMittelbach** [comment]
> Note the requested function is already available under the name `\use:nn`

which is why I'm against adding it. It is clear that you have to indicate which arguments you use if there is a selection, but `\use:nnn` is way better than `\use_i_ii_iii:nnn` etc thus I would suggest to stick with `\use:nn` and the like whenever *all* arguments are to be used. I know I'm a little late to that discussion but I think we should consider undoing that.

**Comment by davidcarlisle** [comment]
@FrankMittelbach  Joseph has already reverted it at 46db34df2b988f5c07872ea749f7629f93f8f29f

**Comment by FrankMittelbach** [comment]
ah, haven't seen that in my still to read 500 messages.

**Comment by car222222** [comment]
I am not surveillance we did get a message about this: it is not mentioned within this issue/PR, AFAICS.
