### ISSUE TITLE
`\seq_map_break:` does not works with `\seq_map_pairwise_function`

### ISSUE THREAD

**Issue by ealprr** [latex3/latex3#1587]
Hello!

I would like to report that `\seq_map_pairwise_function` throws an error when using `\seq_map_break:` (or `\seq_map_break:n`):

```
Runaway argument?
\__seq_map_pairwise_function:Nnnwnn \mybreak:nn \__seq_item:n {1}\__seq_item:n \ETC.
! File ended while scanning use of \prg_map_break:Nn.
<inserted text>
```

Can be reproduced with:

```tex
\documentclass{article}
\begin{document}
\seq_set_from_clist:Nn \l_tmpa_seq {1,2,3}
\seq_set_from_clist:Nn \l_tmpb_seq {1,2,3}
\cs_new:Npn \mybreak:nn #1 #2
  { \seq_map_break: }
\seq_map_pairwise_function:NNN \l_tmpa_seq \l_tmpb_seq \mybreak:nn
\ExplSyntaxOff
\end{document}
```

```
LaTeX2e <2024-06-01> patch level 2
L3 programming layer <2024-07-20>
```

This is not documented and I check for regression test, but it seems that this use case is not tested.

If anybody has an idea to workaround this issue, I would be grateful.

Thanks in advance for any help!

**Comment by muzimuzhi** [comment]
Looks like this is a leftover of 47198ff1 (Breaking away from mappings: nestable \\\<type\>_map_break:n., 2012-06-29) committed 12 years ago, at the time `\seq_map_pairwise_function:NNN` was called `\seq_mapthread_function:NNN` and lived in `l3candidates.dtx`.

**Comment by ealprr** [comment]
Thank you for the very quick fix!

**Comment by muzimuzhi** [comment]
BTW I've checked that the structure `\prg_break_point:Nn \<type>_map_break: {<ending code>}` is contained in every map function.
