### ISSUE TITLE
Feature request: \sys_if_engine_unicode: 

### ISSUE THREAD

**Issue by daleif** [latex3/latex3#1595]
Would be nice to have a check for unicode engines, aka can I load `fontspec` or not. Similar to `\iftutex` from `iftex`, though `\sys_if_engine_unicode:` would perhaps be more general?

One can use 
```
\bool_if:nTF { \sys_if_engine_luatex_p: || \sys_if_engine_xetex_p:  } ...
```
 but that seems a bit clunky

**Comment by josephwright** [comment]
A few obvious questions

- What is the feeling about this vs the existing 'lazy' approach?
- If we want to go for it, is the underlying test just 'LuaTeX/XeTeX' or is it something else?
- Do we like the proposed name?

**Comment by muzimuzhi** [comment]
According to the l3kernel README,

> The existence of the primitive `\Umathcode` is used as the marker for Unicode support.

https://github.com/latex3/latex3/blob/e591f0850706acbf06f619b0566b3f9c2333da1e/l3kernel/README.md?plain=1#L66-L75

**Comment by muzimuzhi** [comment]
Can be defined statically (just a draft):
```diff
diff --git a/l3kernel/l3sys.dtx b/l3kernel/l3sys.dtx
index 0fcfa9f9..1144abb9 100644
--- a/l3kernel/l3sys.dtx
+++ b/l3kernel/l3sys.dtx
@@ -510,6 +510,11 @@
     \@@_const:nn { sys_if_engine_ #1 }
       { \str_if_eq_p:Vn \c_sys_engine_str {#1} }
   }
+\@@_const:nn { sys_if_engine_unicode }
+  {
+    \bool_lazy_or:nnTF
+      { \sys_if_engine_luatex_p: } { \sys_if_engine_xetex_p: }
+  }
 %    \end{macrocode}
 % \end{variable}
 % \end{macro}
```

> According to the l3kernel README,
> 
> > The existence of the primitive `\Umathcode` is used as the marker for Unicode support.

BTW It seems it's the LaTeX2e which uses `\Umathcode` as the marker, but the l3kernel always uses
```tex
\bool_lazy_or:nnTF { \sys_if_engine_luatex_p: } { \sys_if_engine_xetex_p: }
```
as the marker. For example in `l3kernel/l3unicode.dtx`:
https://github.com/latex3/latex3/blob/e591f0850706acbf06f619b0566b3f9c2333da1e/l3kernel/l3unicode.dtx#L165-L167

**Comment by josephwright** [comment]
We've decided on `opentype` for the name - that's the fundamental idea.
