### ISSUE TITLE
Why is there no `v`-variant of `\tl_if_blank:n`?

### ISSUE THREAD

**Issue by mikkelee** [latex3/latex3#1603]
Is the lack of a `v`-variant of `\tl_if_blank:n` an intentional omission? It current has `e`, `V`, and `o`.

I would use it to check token list variables with generated names (eg. checking multiple variables in a loop), and considered the `c`-variant of `\tl_if_empty:N` — but that has different semantics (`is_blank` allows spaces vs. `is_empty` meaning completely empty).

**Comment by josephwright** [comment]
Whilst we've added a number of 'handy' variants, we don't cover all cases - there are a _lot_ of possible variants when you look at functions with many args. This is one reason that `\cs_generate_variant:Nn` can be applied multiple times.

**Comment by mikkelee** [comment]
Thanks for the swift reply. Does that mean it would be okay to generate my own variant in a CTAN package?

**Comment by josephwright** [comment]
@mikkelee  Yes, a very common pattern

**Comment by mikkelee** [comment]
Okay thanks again! :)

**Comment by FrankMittelbach** [comment]
I think that is properly documented in interface3 as the approach. 

As said it is impossible to predefine all possible variants of all commands so we only define very common ones and any package can add to that pool. The interface is designed to nothing if the variant already exist so several packages and provide the same if they need it. Once in a while we augment the set of predefined ones if some appear to be common enough, but that doesn't hurt code that has them already defined.

**Comment by mikkelee** [comment]
Yeah, I should probably go over the early chapters of interface3.pdf again. I mostly just search through it...

I'll close this, have a great weekend! :)
