### ISSUE TITLE
How stream variables should be suffixed?

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#1605]
In the chapter 12 (“The `l3file` module: File and I/O operations”) of the `interface3.pdf` documentation, the sole example of how to suffix stream variables is:
```latex
\ior_get:NN \l_my_stream \l_tmpa_tl
```
This sounds like one should suffix stream variables with `_stream`.

But, in Section “12.1.5 Constant input–output streams, and variables”, the scratch input and output stream variables are suffixed `_ior` and `_iow`:
```latex
\g_tmpa_ior
\g_tmpb_ior

\g_tmpa_iow
\g_tmpb_iow
```
Hence my question: how stream variables should be suffixed?

**Comment by muzimuzhi** [comment]
> ```
> \ior_get:NN \l_my_stream \l_tmpa_tl
> ```

Should be `\l_my_ior` here.
