### ISSUE TITLE
Why not provide `\hbox_overlap_center_to_wd:nn {⟨dim expr⟩} {⟨contents⟩}` and `\hbox_overlap_left_to_wd:nn {⟨dim expr⟩} {⟨contents⟩}`?

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#1609]
AFAICS:

1. `\makebox[\c_zero_dim][l]` ⟺ `\hbox_overlap_right:n`
2. `\makebox[\c_zero_dim][c]` ⟺  `\hbox_overlap_center:n`
3. `\makebox[\c_zero_dim][r]` ⟺ `\hbox_overlap_left:n` 
4. `\makebox[⟨dim expr⟩][l] {⟨contents⟩}` ⟺ `\hbox_to_wd:nn {⟨dim expr⟩} {⟨contents⟩}`

Indeed:
```latex
\documentclass{article}
\begin{document}
\ExplSyntaxOn
\begin{enumerate}
\item
  \begin{itemize}
  \item \fbox{\makebox[\c_zero_dim][l]{contents}}
  \item \fbox{\hbox_overlap_right:n {contents}}
  \end{itemize}
\item
  \begin{itemize}
  \item \fbox{\makebox[\c_zero_dim][c]{contents}}
  \item \fbox{\hbox_overlap_center:n {contents}}
  \end{itemize}
\item
  \begin{itemize}
  \item \fbox{\hbox_overlap_left:n {contents}}
  \item \fbox{\makebox[\c_zero_dim][r]{contents}}
  \end{itemize}
\item
  \begin{itemize}
  \item \fbox{\makebox[5cm][l]{contents}}
  \item \fbox{\hbox_to_wd:nn {5cm} {contents}}
  \end{itemize}
\end{enumerate}
\ExplSyntaxOff
\end{document}
```
But:

5. `\makebox[⟨dim expr⟩][c]` ⟺ ??
5. `\makebox[⟨dim expr⟩][r]` ⟺ ??

Why not provide (something like)  `\hbox_overlap_center_to_wd:nn {⟨dim expr⟩} {⟨contents⟩}` and `\hbox_overlap_left_to_wd:nn {⟨dim expr⟩} {⟨contents⟩}`?

**Comment by josephwright** [comment]
See the as-yet experimental `xbox` code (on GitHub, not released)
