### ISSUE TITLE
`\bool_if:nTF` and `\bool_if:cTF` are provided. `\bool_lazy_and:nnTF` is provided but `\bool_lazy_and:ccTF` isn't: why?

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#1624]
Though not documented, `\bool_if:cTF` is provided in addition to `\bool_if:nTF`. But, though `\bool_lazy_and:nnTF` is provided, `\bool_lazy_and:ccTF` isn't provided:

```latex
\documentclass{article}
\begin{document}
\ExplSyntaxOn
\bool_if:nTF {\g_tmpa_bool} {true} {false}\par
\bool_lazy_and:nnTF {\g_tmpa_bool} {\g_tmpb_bool} {true} {false}\par
%
\bool_if:cTF {g_tmpa_bool} {true} {false}\par
\bool_lazy_and:ccTF {g_tmpa_bool} {g_tmpb_bool} {true} {false}
\ExplSyntaxOff
\end{document}
```
and the same applies to other similar commands.

Is there a reason for these shortcomings?

**Comment by u-fischer** [comment]
`\bool_if:cTF`  is not an addition to `\bool_if:nTF` but to `\bool_if:NTF` and there it is also documented.

**Comment by dbitouze** [comment]
Ooops, sorry!

**Comment by FrankMittelbach** [comment]
\bool_if:cTF is documented (on pages 68 in interface3)
