### ISSUE TITLE
`\keys_precompile:nnN` fails for keys using `\l_keys_path_str` etc.

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1632]
Currently `\keys_precompile:nnN` cannot be used to precompile a key whose code uses one or more of `\l_keys_path_str`, `\l_keys_key_str`, and `\l_keys_value_tl`. These variables are commonly used in defining the `unknown` key (which is used as a handler for unknown keys).

```tex
\documentclass{article}
\ExplSyntaxOn
\keys_define:nn { module } { key .code:n = \l_keys_key_str }
\keys_precompile:nnN { module } { key } \l_tmpa_tl
\tl_show:N \l_tmpa_tl
\ExplSyntaxOff

\begin{document}
\end{document}
```

```
> \l_tmpa_tl=\l_keys_key_str .
<recently read> }
```

This limitation needs to be documented.

Alternatively, there can be a new key property so that if set for a key, `\keys_precompile:nnN` will collect assignments like `\str_set:Nn \l_keys_path_str {...}` right before collecting the code of that key.

```tex
\keys_define:nn { module }
  {
    key .code:n      = { \l_keys_key_str = \l_keys_value_tl },
    % or taking a boolean value?
    key .used_vars:n = { \l_keys_key_str , \l_keys_value_tl }
  }
```
then `\keys_precompile:nnN { module } { key=val } \l_tmpa_tl` will be equivalent to
```tex
\tl_set:Nn \l_tmpa_tl
  {
    % assignments of used vars
    \str_set:Nn \l_keys_key_str { key }
    \tl_set:Nn \l_keys_value_tl { val }
    % code of the key
    \l_keys_key_str = \l_keys_value_tl
  }
```

**Comment by fpantigny** [comment]
Is it `\keys_digest:nnN` (in the title of this post) or `\keys_precompile:nnN`?

**Comment by josephwright** [comment]
@fpantigny  I've updated the title and body text - 'digest' was an earlier name suggestion.

**Comment by car222222** [comment]
But not a good one: "digest" sounds as if you are either eating it or summarising it!

**Comment by josephwright** [comment]
> But not a good one: "digest" sounds as if you are either eating it or summarising it!

Which we talked about and went for the current version :)

**Comment by muzimuzhi** [comment]
I updated title and body again (sorry for splitting email threads), to totally avoid use of the "digest" word.

If needed, the section title "Digesting keys" in interface3.pdf may also be updated, to for example "Precompiling keys".

**Comment by josephwright** [comment]
I think this is a doc thing - they values are right at the point that precompiling happens, so if you use the values at that point, all is OK.

**Comment by josephwright** [comment]
> > I've added a note - it's a bit more general as something like
> > ```
> > \keys_define:nn { module } { key .tl_set:N = \l__mymodule_tmp_tl }
> > \keys_precompile:nnN { module } { key = \l_some_tl } \l_tmpa_tl
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > would have an issue also.
> 
> Sorry but I don't see any issue in your example: both `\l_tmpa_tl` and direct use of `\keys_set:nn { module } { key = \l_some_tl }` execute
> 
> \tl_set:Nn \l__mymodule_tmp_tl { \l_some_tl }

True, but if if we assume the value is then used, the outcome if precompiled will be unpredictable in the sense it depends on `\l_some_tl` when we use the precompilation, not when we do it.

**Comment by muzimuzhi** [comment]
> @muzimuzhi Does the text I've added help?

The "will not work correctly" in sentence "This means that any key setting which simply stores variable names, rather than variable values, will not work correctly." might be too strong. Depending on use cases, even using your example may the precompiling give expected behavior.

Also we may need a general name to denote variables like `\l_keys_path_str`, instead of listing all of them, as I just found there are also `\l_keys_choice_tl` and `\l_keys_choice_int` (for choice keys). How about "self-referential variables"?

**Comment by cfr42** [comment]
> Also we may need a general name to denote variables like `\l_keys_path_str`, instead of listing all of them, as I just found there are also `\l_keys_choice_tl` and `\l_keys_choice_int` (for choice keys). How about "self-referential variables"?

Please, don't call them that! A self-referential variable would be a variable which referred to itself. These don't. They expand to values which are determined at the point of use. That has nothing to do with self-reference.

**Comment by josephwright** [comment]
'key status variables'?

**Comment by cfr42** [comment]
> 'key status variables'?

much more logical :-)

**Comment by josephwright** [comment]
OK to close with the doc improvements?

**Comment by muzimuzhi** [comment]
I don't see any change newer than d19a7284 (Add a note re. key precompilation, 2024-12-09).

**Comment by josephwright** [comment]
@muzimuzhi  See now :)

**Comment by muzimuzhi** [comment]
> The "will not work correctly" in sentence "This means that any key setting which simply stores variable names, rather than variable values, will not work correctly." might be too strong.
https://github.com/latex3/latex3/issues/1632#issuecomment-2529669881

If "will not work correctly" is accepted, I'm OK to close with the current doc improvements.
