### ISSUE TITLE
l3color argument expansion order leading to invalid PDF values

### ISSUE THREAD

**Issue by davidcarlisle** [latex3/latex3#1640]
```
\DocumentMetadata{lang=en,uncompress}

\documentclass{article}

\begin{document}
{
\ExplSyntaxOn

%\tracingall

{\color_select:nn{gray}{\fp_eval:n{rand()}} XX}


{\exp_args:Nne\color_select:nn{gray}{\fp_eval:n{rand()}} XX}

}

\end{document}
```

In the first example, where the color value is not pre-expanded somewhere in the number trimming a spurious `.0` gets added and the value is presented to the backend with two `.`  with a call such as `...{gray}{0.8152919743063377.0}`

This works in some PDF readers and not others but is certainly an invalid PDF number literal.

I'm not sure if this is an error in the number normalisation, or whether the color commands should always fully expand before processing (so implicitly make `:nn` work as `:ee` here)

**Comment by u-fischer** [comment]
The appended `.0` happens also without fp:

~~~
\DocumentMetadata{lang=en,uncompress}
\documentclass{article}
\begin{document}
{
\ExplSyntaxOn
\def\blub{0.1} \color_select:nn{gray}{\blub} XX
}
\end{document}
~~~

gives `0.1.0 g 0.1.0 G` in the pdf.

**Comment by davidcarlisle** [comment]
@u-fischer  ah thanks, I should change the issue title then

**Comment by josephwright** [comment]
OK, the source is easy to find: we currently take input as-is and split on commas, then normalise the values if they don't contain an explicit `.`. That's straight-forward to adjust if we want to expand up-front. However, that then raises the question of whether to treat the input as tuples and auto-apply the `fp` code - thoughts?

**Comment by Skillmon** [comment]
> However, that then raises the question of whether to treat the input as tuples and auto-apply the `fp` code - thoughts?

Sounds like a biggish slowdown. I'd be in favour of expanding and then normalising instead.

**Comment by josephwright** [comment]
> > However, that then raises the question of whether to treat the input as tuples and auto-apply the `fp` code - thoughts?
> 
> Sounds like a biggish slowdown. I'd be in favour of expanding and then normalising instead.

Yes, definitely slower but then using an fp for box rotation is too, and we allowed it there.

**Comment by josephwright** [comment]
I'm not saying 'we must do this',  I'm saying 'it's not out of the question' - I can see the speed argument particularly as colour pops up a lot more than box operations (or 'drawing' ...).

**Comment by josephwright** [comment]
Also, it's not too hard to add `\fpeval` as a user if we simply go for `e`-type expansion: the change is a lot more straight-forward too :)

**Comment by davidcarlisle** [comment]
I think I'd just expand first and require the caller to use fp_eval for fp operations.
that does I guess mean that the color components can be hidden behind a macro so

```
\def\blub{1,0,0}   \color_select:nn{rgb}{\blub}
```

is red, but I think that's OK as long as it's documented that way.

**Comment by muzimuzhi** [comment]
The current implementations of `\__color__parse_model_(gray|rgb|cmyk):w` also drop extra values needed by current model, and add 0s for missing values. As there is no `fp` function to count items in a tuple yet, "treat(ing) the input as tuples and auto-apply the `fp` code" may need some post-processing validation.

**Comment by josephwright** [comment]
@muzimuzhi Any change here will be an 'insert' into the current flow - i.e. the existing normalisation would still apply.

**Comment by muzimuzhi** [comment]
Considering consistency, we need to fully expand all other `value(s)` arguments of l3color functions:
- `#3` of `\color_set:nnn`
- `#2` of `\color_fill:nn` and `\color_stroke:nn`
- `#2` of `\color_math:nnn`
- `#2` of `\color_export:nnnN`

**Comment by josephwright** [comment]
I've adjusted to expand at the common internal

**Comment by josephwright** [comment]
I think here we are done.
