### ISSUE TITLE
Documentation should clarify that keys created with ".bool_set:N" can be empty

### ISSUE THREAD

**Issue by Derek61** [latex3/latex3#1641]
The documentation states that `.bool_set:N` "[d]efines ⟨key⟩to set ⟨boolean variable⟩to ⟨value⟩(which must be either “true” or
“false”)." However, it appears that it's okay to provide no value to the key, in which case the value defaults to "true".  This behavior isn't clear from the documentation. For example:

```
\begin{filecontents}[overwrite]{bpkg.sty}
\ProvidesExplPackage {bpkg} {2024/12/22} {1.0} {Commands for bpkg.}
\DeclareKeys [bpkg]
  {
    checked .bool_set:N = \checked
  }
\ProcessKeyOptions [bpkg]
\bool_log:N \checked
\endinput
\end{filecontents}

\documentclass{article}
\usepackage[checked]{bpkg}
\begin{document}
This is a document.
\end{document}
```
Running this produces
```
...
Package: bpkg 2024/12/22 v1.0 Commands for bpkg.
> \checked=true.
...
```
in the log file, even though there's no value provided to the `checked` option.

I would probably change the documentation to read

> ...[d]efines ⟨key⟩to set ⟨boolean variable⟩to ⟨value⟩, which must be “true”, “false”, or omitted. If ⟨value⟩ is omitted, it defaults to "true".

**Comment by josephwright** [comment]
Thanks - fixed
