### ISSUE TITLE
Docs of `\seq_set_split:Nnn` and `\seq_set_split_keep_spaces:Nnn` on empty delimiter

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1649]
The docs of `\seq_(g)set_split:Nnn` and `\seq_(g)set_split_keep_spaces:Nnn` both say

> If the ⟨delimiter⟩ is empty, the ⟨token list⟩ is split into ⟨items⟩ as a ⟨token list⟩.

which is a bit confusing to me.

(c225a9d8 (Change \seq_set_split:Nnn when the "separator" argument is empty. Fixes #55., 2011-11-23) added this sentence.)

First, the second "⟨token list⟩" can be just the plain text "token list". For example rewrite it to "the ⟨token list⟩ is split into ⟨items⟩ as splitting a token list into items".

Then, it needs to be mentioned that `\seq_(g)set_split_keep_spaces:Nnn` cannot keep spaces if the delimiter is empty.

**Comment by josephwright** [comment]
Better?

**Comment by muzimuzhi** [comment]
Yes. Thanks.
