### ISSUE TITLE
Various problems with g_file_current_name_tl

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#168]
The variable `\g_file_current_name_tl` is meant to contain the current file name.  There is code to set the right name when reading a file with `\file_input:n` (and when closing it, get back to the old name).  Four problems:
- The initial value in package mode is the value of `\@currname` in effect when our `tl` is defined, namely `expl3`.
- When loading an `expl3`-based package (or another package) the value of our `tl` is not updated.  We need to add code to `\RequirePackage` (probably that can be combined with what we already do to setup the `\ExplSyntaxOn/Off` correctly), and `\LoadClass`.
- The value is not updated either when using `\input` or `\include`, but I don't think we should alter this, just document it (well, unless there is a convenient low-level macro we could touch?).
- The initial value, `\@currname`, does not include the extension.  In contrast, when reading a file with `\file_input:n`, the name contains the extension.

Some of that probably also applies to our file list.

**Comment by josephwright** [comment]
This should now all be fixed.
