### ISSUE TITLE
Implement floating point formatting

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#173]
For typesetting floating points, SIunitx is great.  For writing to a file, terminal, or log, with a given precision, padding, etc, nothing is available.  Something like the following could be implemented:

```
\RequirePackage{expl3,l3format}
\ExplSyntaxOn
\iow_term:x { \format_fp:nn { digits = 5 , sign = + } { pi + 2e3 } }
% => +2003.14159
\iow_term:x { \format_fp:nn { scientific = {*10^}, digits = 5 } { pi + 2e3 } }
% => 2.0031*10^3
```

Note that this requires some expandable key-value parsing.  This could be done by providing a function to turn a list of key--value pairs into a prop-like structure and providing a minimal set of functions to map through such prop-like structures.  I have code for that.

**Comment by josephwright** [comment]
I'm almost certainly going to have everything in `siunitx` expandable for v3.1 (see https://github.com/josephwright/siunitx/issues/346): in the re-write, the other parts are already expandable ...

**Comment by josephwright** [comment]
@blefloch  Yes, I meant that. One can do expandable keyval processing, but it's painful. I was imagining that only the processing would need to be expandable: set up for things like spacing is likely OK without that. (Or at least, that's how I imagine it.)

**Comment by blefloch** [comment]
For applications where one wants a string as output, floating point formatting has actually been implemented in `l3str-format` a while ago.  The examples above can be done as follows, except for the replacement of the exponent marker by `*10^`: this customization is not available.
```
\RequirePackage{l3str-format}
\ExplSyntaxOn
\iow_term:n { \fp_format:nn { pi + 2e3 } { +.5f } } % => +2003.14159
\iow_term:n { \fp_format:nn { pi + 2e3 } { .4e } } % => 2.0031e3
```
