### ISSUE TITLE
Rely less on string comparisons

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#174]
String comparisons are comparatively slow in LuaTeX since they require passing arguments to the Lua side (escaping the string to a Lua string and parsing the resulting Lua program).  Quite a few low-level kernel functions use string comparisons but could be implemented differently, hence be faster.

Main offenders: quark tests (for which it would be better to test with delimited arguments anyways), some tl functions, `token_if_macro/...` tests, some fp internals.

**Comment by josephwright** [comment]
Do we need to worry about this? Functionality-wise, we are OK, and speed doesn't really show up ...
