### ISSUE TITLE
Active characters

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#19]
Here is a partial idea for what could be done to active characters.

```
\group_begin:
\tex_catcode:D `\~=13\tex_relax:D
\prg_stepwise_inline:nnnn {0} {255} {1} {
     \tex_lccode:D `\~ = #1\relax
     \tex_lowercase:D { \cs_new:Npx ~ { \exp_not:N \active_char:N \token_to_str:N ~ } }
}
\group_end:

\cs_new:Npn \active_char:N #1 { 
      \cs_if_exist:cTF { active_ \l_active_state_tl _ \token_to_str:N #1 : } {
            \use:c { active_ \l_active_state_tl _ \token_to_str:N #1 : }
      } {
            \use:c { active_ \l_active_state_tl :N } #1
      }
}
\tl_new:Npn \l_active_state_tl {string}
\cs_new:Npn \active_string:N #1 { \token_to_str:N #1 }
\cs_new:cpn {active_string_^:} {\sp}
\cs_new:cpn {active_string_&:} {&}
```

And packages such as listings which makes characters active in a specific environment should define `\active_listings:N` (or each one of the character-specific commands), and the environment should change `\l_active_state_tl` to `listings`, and change catcodes, of course, but would not need to redefine active characters each time.

For instance, this makes it easy to have otherwise active characters inside a `\label`: just change `\l_active_state_tl` to `string` before putting the user-given code into the `\csname` construction. Similarly, each time a length/number is needed, we get `.`, digits and (possibly active??) letters to expand to themselves (with catcode 12), suitable for a length.

For tables, I would have preferred to make `&` into an active character `\let` to be an implicit character of catcode 4 over the whole document, but tables are completely another story, and I think we can live without `\halign` and the corresponding constraint on the catcode of `&`.

**Comment by josephwright** [comment]
Find use cases

**Comment by wspr** [comment]
Bringing this back to life: this is like a poor man's catcodetable scheme, right? I actually think that active characters have a degree of utility in creating light-weight markup — consider what we do with `\MakeShortVerb\|` and so on.

So I think from a document perspective having an interface to do this is probably a good idea. Other approaches I've seen in the distant past around this revolved around using a stack to push/pop active meanings, but I don't see as an advantage there.

One wrinkle is that if we provide a "special" interface for setting active character meanings we should disable or at least check for an attempt to overwrite the fundamental definitions using more primitive commands. Not sure if that should be a `check` related functionality or something built into `\cs_set` or the xparse functions.

**Comment by josephwright** [comment]
@wspr  First step is to have a fixed set of actives of course: that's often part of the issue. I do see your point about `|` for short verbatim but that's a rather specialised use (in the sum total of LaTeX documents, actually printing code is relatively rare), but also wonder if there is a need to turn it on-and-off ... I guess tables?
