### ISSUE TITLE
\ior_map_inline:Nn \undefined {} — works?

### ISSUE THREAD

**Issue by wspr** [latex3/latex3#194]
I suspect it would be a good idea to at the very least check if the first argument to `\ior_map_inline:Nn` actually exists; currently the following is simply a no-op:

```
\ior_map_inline:Nn \undefined {}
```

This makes spotting typos more difficult since the code you're expecting simply doesn't execute.
It's worth noting that a control sequence that's incorrect but does exist causes other errors:

```
\ior_map_inline:Nn \LaTeX {}
```

I'm not saying we need to do anything at all about that type of thing at this stage.

 I'd consider going one step further and perform additional diagnostics (to the point of checking whether the stream is open?) but I'm not so sure that's actually worth the hassle.

**Comment by blefloch** [comment]
This comes from `\ior_if_eof:NTF` treating undefined control sequences as closed streams.  Perhaps we should change that too?  (But the test is deliberate, so first we need to track down why it was put in.)

**Comment by blefloch** [comment]
The test for `\ior_if_eof:NTF` seems to date back from early 2011, see for instance the file [l3io.dtx](https://github.com/latex3/latex3/blob/3ac0fae5b58b326f4f9a016378deefa8e7ba8f5a/l3kernel/l3io.dtx) from that time, where streams were closed by undefining them.
```
\cs_new_protected_nopar:Npn \iow_close:N #1
  {
    \cs_if_exist:NT #1
      {
        \int_compare:nNnF #1 = \c_minus_one
          {
            \tex_immediate:D \tex_closeout:D #1
            \prop_gdel:NV \g_iow_streams_prop #1
            \cs_gundefine:N #1
          }
      }
  }
```
In that context, it made sense to have a `\cs_if_exist:NTF` test in `\ior_if_eof:NTF` (code documentation from that time: "As the pool model means that closed streams are undefined control sequences, the test has two parts.").

Later on (sept 2011), I see a git commit message (from commit `17fe4db22949e546d5e21f6640e953b60f84b89d`)

> Re-introduce \io(r|w)_new:(N|c) functions
>
> At this stage, these reserve a name but are not _required_ for use.
> After an announcement on LaTeX-L and a suitable time for code
> changes elsewhere (for example notes2bib and chemnum), the \..._open
> functions should be altered to require an named stream.

I haven't checked when exactly the `\ior_open:N` functions were altered, but by the time (commit `b3b45ae86e` in 2012) `l3io` and `l3file` were merged, these functions required a stream to have been declared with `\ior_new:N`.  We should have changed `\ior_if_eof:NTF` at the time.  I'll do it now.
