### ISSUE TITLE
Making boolean expressions more resilient

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#217]
Code such as

```
\bool_if:nTF
  {
    \token_if_eq_charcode_p:NN + #1 ||
    \token_if_eq_charcode_p:NN - #1
  }
```

(where `#1` is an N-type argument) is dangerous: it breaks if `#1` is a parenthesis, because such a parenthesis is seen as part of the syntax for a boolean expression.  Currently, the only way for a programmer to avoid such problems is to make sure that any user-provided argument is hidden in braces, so the programmer must write one of

```
    \token_if_eq_charcode_p:NN + {#1}
    \use:n { \token_if_eq_charcode_p:NN + #1 }
```

The first approach looks like the programmer made an error and passed an n-type argument instead of an N-type.  The second approach works, but I find it odd-looking.

I think it is impossible to change LaTeX3 to get the syntax without braces to work without losing lazy evaluation.  To take an extreme example, compare

```
! ( \c_false_bool && \test_p: ) && \test_p:NNN ( \c_true_bool )
! ( \c_false_bool && \test_p:N ) && \test_p:NN ( \c_true_bool )
```

The only difference is the number of arguments of the various `\test_p:` functions.  After seeing `\c_false_bool &&`, we must skip to the first `)` or second `)` depending on the line, but they cannot be distinguished without evaluating `\test_p:` vs `\test_p:N`, which is forbidden by lazy evaluation.

Options:
1. Make all predicates wrap their computation in braces (just tweak `\prg_new_conditional`).  Instead of jumping to the closing `)`, f-expand predicates even when their value is not needed; braces let us `\use_none:n`.  Drawback: lazy evaluation will only work for predicates, and any other function will be evaluated.  For a concrete example, say you have a clist of booleans, then `\int_compare_p:n { 1 <= #1 <= 10 } && \clist_item:Nn \l_your_clist {#1}` will expand `\clist_item:Nn` regardless of the outcome of the first test.
2. Allow the user to put braces around a single predicate, just like the second syntax above (`\use:n { ... }`) but without `\use:n`.  This is trivial to implement.  Drawback: the incorrect use `! { \test_p: &&
   \test_p: }` will be treated perhaps confusingly as `! \test_p: && \test_p:`.
3. Allow the user to use braces as replacement for parentheses, even surrounding a boolean expression.  This would be like option 2, but without its drawback.  Unfortunately, the only implementation I can think of is expensive.
4. Somewhat tongue in cheek (but this approach is not sooo slow, and I can't see a case where it would break): to mop out arguments of predicates that cannot change the outcome of the boolean expression, look at the signature of the predicates, and remove one argument per letter in the predicate's signature.

I favour option 2 as it is trivial to implement, but option 1 might be better if we are ready to lose lazy evaluation for non-predicates, since it completely removes the gotcha of having to remember
to put braces around dangerous user input.  It may be possible to mix options 1 and 2, letting the user include braces around non-predicates to allow lazy evaluation.

**Comment by wspr** [comment]
> I favour option 2 as it is trivial to implement, but option 1 might be better if we are ready to lose lazy evaluation for non-predicates, 

Lazy evaluation is a neat trick but I wonder if we actually lose much by dropping it. It occurs to me (maybe I'm wrong) that the chain of logic that would lead to *requiring* lazy evaluation would make for harder-to-read code. 

Does anyone have an example where having lazy evaluation is actually easy/better/etc.?

**Comment by josephwright** [comment]
I guess the reason for it is currently one can do
```
\bool_if:nTF
  {
    \cs_if_defined_p:N \foo && ...
  }
```
where subsequent tests can be ones which fail badly if the test token is not defined. However, it's likely that such cases will be risky anyway (probably assuming a particular type of token).

I'd be happy to accept a slight inconvenience here in return for not worrying about 'dangerous' tokens. It's much easier to document 'evaluation always takes place on all parts' than 'evaluation is lazy but be careful about ...'.

If we do make a change, do we keep `&&`/`||` or deprecate in favour of `&`/`|`?

**Comment by wspr** [comment]
> If we do make a change, do we keep &&/|| or deprecate in favour of &/|?

I personally prefer the doubled versions, but only because they match Matlab syntax, and also because they "stand out" a little more. I'm not sure what Morten's original reasoning was for choosing them...

**Comment by josephwright** [comment]
If you look up logic operations for C-like languages, Bash, _etc._ you'll find that the doubled versions are normally 'logical operators' in some way and lead to lazy evaluation. See for example http://blog.dmbcllc.com/vs-and-vs-whats-the-difference/.

**Comment by josephwright** [comment]
Perhaps we might also consider at the same time as any change making `&` something less risky inside the code environment: there's no real reason for requiring it to be catcode-4.

**Comment by blefloch** [comment]
@josephwright I've made your last comment here into a new issue discussing more broadly the fate of a few catcodes.

About deprecating `&&` in favor of `&`, it's not easy at all code-wise to accept both in the transition period.  It's actually easier to switch completely to `and` and `or`, which also allows us to define `xor` if we want.

About dropping lazy evaluation, I don't like it but I have no argument.  This should certainly be discussed on LaTeX-L beforehand.

**Comment by josephwright** [comment]
@blefloch  The `&&` business is not essential: we can happily leave alone. (We are still talking boolean logic rather than bitwise so it's quite reasonable.)

On the lazy evaluation, I think we'd all *like* to keep it but the problem is it seems to mean we have a non-fixable issue that quite we can't just ignore: people will fall in to this trap. (I know about it which is why the code that triggered the discussion is written in a defensive manner, but that's not a general approach.)

**Comment by blefloch** [comment]
An example of legitimate use of lazy evaluation from the `expl3-generic.tex` loader:

      \bool_if:nTF
        {
             \cs_if_exist_p:N  \pdftex_pdfoutput:D
          && \int_compare_p:nNn \pdftex_pdfoutput:D > \c_zero
        }
        { pdfmode }
        { dvips }

**Comment by josephwright** [comment]
@blefloch  Indeed, that had occurred to me. I think it's relatively rare, though, as we say variables should exist globally. This one might be regarded as an outlier as a result.

**Comment by blefloch** [comment]
Fair enough.  Do you have time to raise the question on LaTeX-L, or are more internal discussions needed?

**Comment by josephwright** [comment]
I'll raise on LaTeX-L: there may be arguments we've missed.

**Comment by blefloch** [comment]
Comment, just to keep track of things.  We've added a bunch of predicates to `l3candidates`, and the current plan is to rename them to `\bool_lazy_all_p:n`, `\bool_lazy_and_p:nn`, `\bool_lazy_any_p:n`, `\bool_lazy_or_p:nn`, and add the corresponding `TF` conditionals.  After some time (or not), expressions will be made non-lazy.
