### ISSUE TITLE
Catcodes in code environment

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#225]
In another issue, Joseph raises the question of whether to keep `&` special in a code environment.  To recapitulate, here are the catcodes in code (I've restricted myself to the 0-127 range).

It is impossible to change the following: `\` is escape, `{` and `}` are begin/end group, `#` is macro parameter, `%` is comment, `^^M` is end of line (needed so that comments end at the end of a line in the file), `:`, `_` and letters are letters, `^^I` and space are ignored, `~` is a space.

The following may be worth discussing: `$` is math toggle, `&` is alignment tab, `^` is superscript, `^^L` is active and is an outer macro, and `^^?` is invalid.  When `expl3` is loaded on top of LaTeX2e, all characters from `^^A` to `^^_` except those mentioned above are invalid.  When `expl3` is loaded on top of plain TeX, `^^A` is a subscript, `^^K` is a superscript.  I haven't tested with ConTeXt.

The following are "other".  In order of how crucial it is that they remain "other": `0123456789` for macro parameters, `.+-*/()` for integer/dimension expressions, ``"`'`` for integers in diverse bases, `,` (comma) for comma lists, `<=>` for comparisons (adding a few `\token_to_str:N` fixes that without interface changes), `[]` to use LaTeX2e macros that expect optional arguments, `|` for arrays, `;` for TikZ, `!?@` no reason to keep them "other".

**Comment by josephwright** [comment]
To be clear, I wasn't thinking about going over-the-top on defensive code. I was primarily thinking that as we won't want to use `&` directly at the code level for alignments (if we even use the `\halign` primitive for tables in a future format), we probably don't need what is a tricky catcode to apply inside boolean expressions.

**Comment by wspr** [comment]
> !?@ no reason to keep them "other".

In fact making @ letter would aid writing code that relies on 2e things. 

And !? being letters might open us up to "interesting" macro names. Whether that's a good thing or a bad thing could be up for discussion :-)

**Comment by josephwright** [comment]
We've discussed extending the range of letters before: I thought that was clearly out? (ConTeXt uses `!` keyval stuff but I don't think we are planning anything like their key approach.)

**Comment by wspr** [comment]
I may have forgotten the discussion :-) Keeping them as "others" is totally fine -- I think I would agree we don't really want names like \foo_if_bar?:n and so on. 

But what about @? Are we happy writing \ExplSyntaxOn\makeatletter where necessary?

**Comment by josephwright** [comment]
I'd say `@` should be left alone. For LaTeX2 where you might be hacking internals you need `@` as a letter, but for 'pure' `expl3` code you don't. If we force `@` to be a letter in all cases then we risk keeping 'old' names in generic code 'because it's easier' and failing to address the problem of them being documented in different places (if at all).

**Comment by wspr** [comment]
Good argument! I would be very happy for this to be the considered official stance on the matter.

**Comment by tail-reversion** [comment]
Whenever I’m using expl3, I don’t use the following special characters: `&$_^`, instead, I use the predefined constant tokens: `\c_alignment_token`, &c., possibly wrapped in a command. When working with 2e code, I may use the math toggle commands `\(\)` and `\[\]`.

**Comment by wspr** [comment]
What is the scope of this issue now? Should we consider making & an other? I'm of a mind to leave the others. Even & I would be worried about whether it had been used somewhere with its regular catcode inside a code section.

**Comment by josephwright** [comment]
Lots of people are building tables using `expl3` ...

**Comment by car222222** [comment]
That is because there are no instructions for doing document-layer things (or even design-layer things) ‘within expl3’.  So tell them that there are no guarantees that anything other than the programming layer stuff (with some name changes or synonyms) will survive much longer!

Of course, this does not apply if they are actually doing LaTeX, 2e, design/document layer stuff and only using expl3 stuff for programming (which means no boxes:-).

**Comment by wspr** [comment]
I guess we all agree we can't change any catcode settings as they currently are, to avoid spectacular breakage. I note that \ExplSyntaxOn ensures that catcodes of `&` and `|` are set appropriately for boolean expressions, but not `!`:

```
\documentclass{article}
\usepackage{expl3}
\begin{document}
\catcode`\&=11
\catcode`\|=11
\catcode`\!=12 % 11 breaks
\ExplSyntaxOn
\bool_set_true:N \l_tmpa_bool
\bool_set_true:N \l_tmpb_bool
\bool_if:nTF{ !\l_tmpa_bool && \l_tmpb_bool }{T}{F}
\ExplSyntaxOff
\end{document}
```

Any objections to safeguarding `!`, adding some documentation around this behaviour of special characters, and closing this issue? Note that comparisons with `<=>` also break if their catcodes are changes — I guess they should be added to ExplSyntax too?

**Comment by blefloch** [comment]
Relatedly we could try using catcode tables (cctab) for `\ExplSyntaxOn`, with special handling to preserve the catcode of `@` (at least) to deal with the fact that people have been doing `\makeatletter\ExplSyntaxOn` or `\ExplSyntaxOn\makeatletter` forever now.

**Comment by josephwright** [comment]
Discussed on the team list and not to be taken further at present.
