### ISSUE TITLE
k-type argument type in xparse

### ISSUE THREAD

**Issue by josephwright** [latex3/latex3#226]
As discussed on LaTeX-L, an argument type to deal with TeX core-like `_`/`^` syntax would be useful
```TeX
\DeclareDocumentCommand\foo{k{_^!*}}{%
  % #1 = Argument to _ or \NoValue if not seen
  % #2 = Argument to ^ or \NoValue if not seen
  % #3 = Argument to ! or \NoValue if not seen
  % #4 = Argument to * or \NoValue if not seen
  }
```

**Comment by josephwright** [comment]
The above isn't quite right, I think, as we have to date had one letter in the arg spec as one TeX argument. I'd rather keep that so
```latex
\DeclareDocumentCommand\foo{k{_^!*}}{%
  %  #1 => Four brace groups, each the argument or \NoValue
}
```
I'll look to do this soon (this week).

**Comment by blefloch** [comment]
I'm minded to reopen: the main goal of having k-type arguments was
that the order in which "^{...}" and "_{...}" appear was not fixed.

This is tricky to implement, and I plan to look into it as part of
fixing other issues relating to xparse.  I may reuse the
`..._flush_m...` machinery to also collect k-type arguments, so that
`k^ k_` is equivalent to `k_ k^`.

**Comment by blefloch** [comment]
> I'm minded to reopen: the main goal of having k-type arguments was
> that the order in which "^{...}" and "_{...}" appear was not fixed.
>
> This is tricky to implement, and I plan to look into it as part of
> fixing other issues relating to xparse.  I may reuse the
> `..._flush_m...` machinery to also collect k-type arguments, so that
> `k^ k_` is equivalent to `k_ k^`.

Sorry, I misremembered what Joseph had done so let me take back what I
said.  I might actually agree with Joseph's approach.

**Comment by josephwright** [comment]
@blefloch I thought quite a bit about this (hence the delay after Darmstadt for implementation) :-) In favour of the 'no ordering' approach is of course the keyval-like nature of such arguments and the analogy to the TeX primitive `^`/`_` syntax. The problem I had with that is how describing it fits into `xparse`. Either we need one `k` per arg type and then 'run together' when setting stuff up _or_ we have a single `k` type argument searching for multiple tokens. The first version is tricky as the signature implies ordering but that's not what happens, the second is tricky as we break the 'one letter per argument' approach we've had to date in `xparse`. I was also not that happy with how defaults would come out in the latter (`K{^_}{{a}{b}`?). Finally I was worried a bit that while the TeX primitive syntax is 'nice' the point of `xparse` is to have at least a somewhat predictable approach, and that saying 'it's always `^` then `_`' (the most likely use case) isn't that bad.

Implementation, particularly for expandable use, looks tricky but that was not the biggest concern.

I've deliberately said this is all experimental as I can see the reasoning for other approaches. I

**Comment by josephwright** [comment]
I did get part-way through implementing `k{^_}` syntax but got stuck with the default argument part, in the sense I wasn't sure about the form. I _think_ that a single 'group of keys' is probably better than lots of one-key specs, but could of course be wrong.

**Comment by aparsloe** [comment]
In LyX the order is always _ then ^. Even if you enter a superscript before a subscript, the latex that LyX produces arranges them in the subscript superscript order.
