### ISSUE TITLE
Interface for \write18

### ISSUE THREAD

**Issue by josephwright** [latex3/latex3#228]
Taken from https://github.com/latex3/svn-mirror/issues/88, we probably need an interface for this.

**Comment by blefloch** [comment]
From looking at TeXLive 2015's `tex/latex` subtree, the only uses of non-immediate `\write18` are:

- in `glossaries.sty`, to call `makeindex` or `xindy`, but this is done `\AtEndDocument`, so `\immediate\write18` probably works too.

- in `graphviz.sty` I think that is a bug (I've reported it to the maintainer).

Thus we only need a wrapper for `\immediate\write18` and for `\pdfshellescape` (I've seen some packages test for `\ifeof18` but I didn't check when that is true/false).  Presumably they can fit into the new module containing os/engine/output information and commands.

**Comment by josephwright** [comment]
Yes, was also my thinking also.

**Comment by blefloch** [comment]
It may be good to provide a function similar to Python's `os.execv(path, args)`, which runs a command (given by the `path`) with some arguments `args`, escaping special characters as needed.

From what I could understand, escaping all characters with a backslash, although an overkill, should work in Linux and perhaps Mac: e.g., `\sys_call_get:nnN { ls } { { -l } { figures/ } } \l_result_tl` could call `\immediate\write18{ls \-\l \f\i\g\u\r\e\s\/}` (or actually `\input|`) and `ls` correctly receives the option `-l` and the argument `figures/`.  I'd hope someone (probably not us) provides a nice interface on top of this to various commands, taking care of dangerous file names e.g., those starting with `-`.

The situation in Windows seems to be completely insane, as every program can decide to parse the command-line differently, with different escape characters, as explained in [a stackoverflow question](http://stackoverflow.com/questions/4094699).

**Comment by blefloch** [comment]
For the record, Python's (deprecated?) `pipes.quote` does something less stupid than my idea of putting backslash before every character.  It leaves the arg unchanged if all of its chars are alphanumeric or in `%+,-./:=@_`.  Otherwise it surrounds the arg with single quotes and replaces single quotes by `'"'"'` (that's five chars, single-double-single-double-single quotes), where the outer single quotes interrupt the single-quoted string, and `"'"` inserts a single quote.

**Comment by josephwright** [comment]
Oh, we did this!
