### ISSUE TITLE
Add basic output methods to format mode

### ISSUE THREAD

**Issue by josephwright** [latex3/latex3#231]
Currently building a stand-alone format with `expl3` built-in (`texlua build.lua format`) only includes `expl3` itself. For _testing_ it would be useful to have some minimal OR and font loading. The plan is to add this very much as 'testing only' code, probably with a big log warning.

**Comment by wspr** [comment]
I guess some of that is up to me :)

**Comment by josephwright** [comment]
@wspr  My plan was that first I'll add a truly minimal amount of code then we can expand a bit. I was thinking that for initial testing we just need to hard-code loading Latin Modern at one size :-)

**Comment by wspr** [comment]
@josephwright That's probably a faster way to get there, yes :)

**Comment by josephwright** [comment]
@wspr  Plan is to first deal with upTeX and probably the lowercsae business, then this is next on my list
