### ISSUE TITLE
Move engine tests to a dedicated prefix

### ISSUE THREAD

**Issue by josephwright** [latex3/latex3#233]
As discussed at TUG2015, `\engine_if_...` seems most sensible here. May also have some relation to https://github.com/latex3/svn-mirror/issues/230 so check on that first!

**Comment by wspr** [comment]
Not \mode_if_... ?

**Comment by blefloch** [comment]
Joseph, you might remember some email discussion we had (just the two of us, for some reason) starting on November 12, 2012, from an email entitled `Re: [l3svn] r4297 - Allow "driver" option to deal with all cases properly`.  I'm not going to reproduce the whole discussion here.  The main point was that we may want to provide eventually all of the following tests:

- `\mode_if_horizontal:TF` and friends (`vertical`, `math`, `inner`), about the current state of TeX

- `\output_if_pdf:TF` as in `pdf` versus `dvi`

- `\engine_if_pdftex:TF` and `xetex`, `luatex`

- `\os_if_macos:TF` and other operating systems, but also `\os_if_shelllescape:TF`.

As I've written them in this list, each set of conditionals comes with a different prefix, but another option is to use `\mode_if_engine_pdftex:TF` and so one, all with the `mode` prefix, or some other prefix (`now`?).

The main question is to decide the naming scheme: one prefix for all these things, or a different prefix for each kind as done in the present post of mine?

**Comment by u-fischer** [comment]
Imho a dedicated prefix should only be used if there is/will be a reasonable number of functions with this prefix.   Also it doesn't looks really right to put shellescape under `os`. And where will you put a test for `batchmode` (can one test for it?? I will have to check)?   One prefix like in `\mode_if_engine_pdftex:TF` or `\mode_engine_if_pdftex:TF`  looks currently more natural to me.

**Comment by josephwright** [comment]
@u-fischer  There's a balance between 'not using up prefixes' and 'logical naming'. Here, I'm not sure I see `\mode_...` relating to engine: at present at least `mode` is about the modes TeX can be in. Moreover, as @wspr  (I think) said at the TUG meeting, `\engine_...` is unlikely to be needed for other things. Of course, you are right that there are other tests that fit in some way into this area. How about something like `\runtime_..`, which seems to cover the general area and would allow for the OS, shell escape and so one.

**Comment by blefloch** [comment]
`\runtime_...` is better than any unified prefix proposed earlier, I think.  I have no preference between a unified prefix and several small ones.

**Comment by u-fischer** [comment]
`\runtime` sounds good.

**Comment by josephwright** [comment]
OK, `runtime` it is. I'll perhaps make a new small `.dtx` as there will be additional stuff to add over time (PDF/DVI, shell escape, Win/Mac/Linux, ...). There are some additional issues in bringing in ()p-TeX (see https://github.com/latex3/svn-mirror/issues/230): makes sense to raise these at the same time. I'll put some ideas down for that before making any changes.

**Comment by wspr** [comment]
N.B. that detecting between platforms (Win/Mac/Linux) is a bit funny and not always reliable. E.g., tests for Windows are negative if using Cygwin. You might be able to come up with something more robust that in ifplatform, of course `:)`

**Comment by josephwright** [comment]
@wspr I'm not saying I'll add that any time soon, but people might expect such abilities (as they are done already by packages).

**Comment by u-fischer** [comment]
@wspr Wouldn't it be useful if the texsystems (or the user) add at installation time a file somewhere that describes the system and which ifplatform could query?

**Comment by josephwright** [comment]
@u-fischer Possible but probably best as an over-ride. In the case @wspr points to, detecting as Linux is likely to be OK. The use case for platform tests tends to be for auto-tidying in concert with `\write18`, and `rm` will work on a Cygwin system so it's not unreasonable.

**Comment by FrankMittelbach** [comment]
On 24.07.2015 00:12, Will Robertson wrote:
> Not \mode_if_... ?
>

\mode is something that is variable within TeX while the other tests all 
query static information about the actual engine or platform used so I 
think there aren't the same category.

**Comment by FrankMittelbach** [comment]
On 28.07.2015 21:35, Joseph Wright wrote:
> OK, |runtime| it is. I'll perhaps make a new small |.dtx| as there will
> be additional stuff to add over time (PDF/DVI, shell escape,
> Win/Mac/Linux, ...). There are some additional issues in bringing in
> ()p-TeX (see #230 <https://github.com/latex3/svn-mirror/issues/230>):
> makes sense to raise these at the same time. I'll put some ideas down
> for that before making any changes.

not sure I like runtime but I have to think a bit further about that 
space before making a proposal. But whaever prefix (or prefixes) we 
should not include the internal modes of TeX into the engine/output/os 
... static ones in my opinion. They serve totally different purposes.

**Comment by josephwright** [comment]
@FrankMittelbach  I was thinking that for any given TeX run things like engine, OS, shell escape availability are static. DVI/PDF output is a bit odd (as it can be changed before starting a PDF), but to me it seemed to fit in a similar space.

**Comment by FrankMittelbach** [comment]
On 29.07.2015 12:47, u-fischer wrote:
> @wspr <https://github.com/wspr> Wouldn't it be useful if the texsystems
> (or the user) add at installation time a file somewhere that describes
> the system and which ifplatform could query?

if we are unable to reliably determine the type of static data about the 
TeX system in all cases then such an external file is probably a useful 
way out (as an overwrite) but we should not make it a standard requirement.

There is also the difficulty that it is not clear how the right file 
gets selected if you have several engines.

**Comment by FrankMittelbach** [comment]
On 29.07.2015 19:14, Joseph Wright wrote:
> @FrankMittelbach <https://github.com/FrankMittelbach> I was thinking
> that for any given TeX run things like engine, OS, shell escape
> availability are static. DVI/PDF output is a bit odd (as it can be
> changed before starting a PDF), but to me it seemed to fit in a similar
> space.

yes all those would fit into static I think even though some can be set 
up in a document. However, our current mode_vertical etc do not fit that 
and the initial proposal was to lump all of them under \mode_

**Comment by josephwright** [comment]
@FrankMittelbach  Certainly: `mode` would be wrong :-)

**Comment by u-fischer** [comment]
> if we are unable to reliably determine the type of static data about the
> TeX system in all cases then such an external file is probably a useful
> way out (as an overwrite) but we should not make it a standard requirement.

No, I thought about some `\IfFileExist{ifplatform.data}{...}`.  And I only suggested it because Will said the test is not always reliable. Then the user should have a chance to help ifplatform.  (But in the long run imho the format should set the OS-switches). 

> There is also the difficulty that it is not clear how the right file
> gets selected if you have several engines.

? Why different files? Ifplatform tries to get datas about the OS and this is not engine dependant.

**Comment by FrankMittelbach** [comment]
On 29.07.2015 19:34, u-fischer wrote:
>     There is also the difficulty that it is not clear how the right file
>     gets selected if you have several engines.
>
> ? Why different files? Ifplatform tries to get datas about the OS and
> this is not engine dependant.

yeah, rubbish. I was thinking about engine dependency parts but that is 
nonsense. so it would be a single file.

**Comment by josephwright** [comment]
@FrankMittelbach  Any further thoughts on a good prefix here? Getting e-(u)pTeX support added mainly needs a decision on this as the rest of the work there is trivial.

**Comment by blefloch** [comment]
Proposals I can make that might perhaps make Frank happy: `system` (`sys`), `runtime` (`run`), `around`, `world`, `outside`, `external` (`ext`), `status` (`stat`), `current`.  I have a very slight preference for `sys`.

**Comment by blefloch** [comment]
In addition to functions/variables discussed above, the following fit in the same space (I went through the documentation of Python's `sys` module for ideas): `\sys_exit:` = `\tex_end:D` ; `\c_sys_version_tl` = `\ver@expl3-generic.tex`  ;  `\c_sys_max_char_int` (or `\c_char_max_int`?) = 255 or 1114111.

**Comment by wspr** [comment]
Before choosing a prefix, can we take a look at the whole (proposed) list of functions that would live under it?

* Querying current TeX typesetting states:

    \mode_if_horizontal:TF
    \mode_if_vertical:TF
    \mode_if_math:TF
    ...

* Querying the engine:

    \ZZZ_if_xetex:TF
    \ZZZ_if_luatex:TF
    \ZZZ_if_pdftex:TF
    \ZZZ_if_uptex:TF

* Others:

    \YYY_if_shellescape:TF
    \YYY_if_restrictedshellescape:TF (?)

    \YYY_if_osx:TF ("macosx" appears to be deprecated; could just have _if_mac:TF)
    \YYY_if_windows:TF
    \YYY_if_???:TF ("unix-like", "linux", ...)

    \XXX_if_batchmode:TF
    \XXX_if_nonstopmode:TF
    \XXX_if_interactionmode:TF

It's not clear at all these (XXX,YYY,ZZZ) should actually share a prefix `:)`. But seeing them all together should help to come up with one, if we can agree. I think something like `\sys_` works for ZZZ and YYY but maybe not XXX, the "interaction" ones. (And note that XXX is not static during a document run.)

What about something totally generic, like `\bool_if_batchmode:TF` and so on?

By the way, I like Ulrike's suggestion that we use TeXLive/MiKTeX to give us more information for testing the OS, etc., by using an auxiliary file.

**Comment by blefloch** [comment]
Let me broaden your list to things that are not :TF conditionals.  `bool` only works for conditionals.  I'm ordering the items by how far from the inside of TeX they are.

- TeX typesetting mode: `\mode_if_(horizontal|vertical|math|inner):TF`.
- Interaction mode: `\AAA_if_(batch|nonstop|scroll|errorstop):TF` but also setting it through `\AAA_set_(batch|...):`, also `\c_AAA_interaction_int` (or tl?).
- Output target: `\BBB_if_(pdf|dvi|html|xml|text|svg):TF` or `\c_BBB_output_tl`, perhaps `\BBB_output:n` as a wrapper around `\special`.
- Engine and driver: `\CCC_if_(lua|xe|pdf|up|p)tex:TF` or `\c_CCC_engine_tl`, `\c_CCC_driver_tl` (not sure where `tex4ht` or `ConTeXt` fit in there).
- Platform and shell: `\DDD_if_(mac|windows|linux):TF`, `\c_DDD_platform_tl`, `\DDD_if_(restricted|)shellescape:TF`, `\c_DDD_shell_tl` (for shell name: "bash", "dash", "cmd.exe" etc), `\DDD_run:n` (for `\write18`)

Misc that could fit somewhere there: wrappers for `\time`, `\day`, `\month`, `\year`, `\pdfcreationdate`, `\jobname`, `\end`, information gathered from `\pdftexbanner`/`\XeTeXversion`/..., pdf primitives like `\pdfcompresslevel`, a variable containing the expl3 version, max char (255 or 1114111).

**Comment by wspr** [comment]
Now we're getting somewhere `:)`.
Timing functions could also fit in there too under "misc" I'm guessing.

You ask about `tex4h` and `context`; I'd suggest they also need something
like `\EEE_if_(latex|plain|context|tex4h):TF` and/or `\EEE_format_tl`.

**Comment by josephwright** [comment]
Remember that the reason for the discussion is in part that there was a desire not to use too many prefixes :-) I'd said `\engine_...` for the engine tests but that is very 'small', hence the idea of `\runtime_...` to contain more sub-options.

**Comment by wspr** [comment]
Agreed — I just thought that enumerating the tests we were talking about would help to decide whether `\runtime_` or `\system_` was indeed appropriate. If we pick a single prefix that is kinda awkward, that's probably worse than several prefixes (prefices?) with only a few functions each. Neither `\runtime_if_batchmode` nor `\system_if_batchmode` work that well to me personally, but maybe the "interaction" ones should be dropped from this list.

Frank always does well at this point, usually suggesting something nice and neat once it's all laid out... so... Frank? `:)`

**Comment by josephwright** [comment]
My feeling is that querying interaction mode is _extremely_ unlikely. I can see wanting to set interaction mode for a script but that's still quite a niche use (most generic scripts that might need this are written in plain).

**Comment by FrankMittelbach** [comment]
Am 12.08.15 um 08:38 schrieb Will Robertson:
> Frank always does well at this point, usually suggesting something nice
> and neat once it's all laid out... so... Frank? |:)|

heard you ... still convalescing a bit ... give me a break

**Comment by wspr** [comment]
I'd suggest for interaction modes we'd provide a push/pop interface for them. I want to use them sometimes when tidying up the console output, for example, but I agree their use would be fairly niche. (You're right when it's usually script-related, such as in the pstool package.) We haven't let niche uses stop us before in expl3 `:)`

**Comment by blefloch** [comment]
I'd say `interactionmode`s etc can fit into the `\mode_` prefix, as it pertains to "what is TeX currently up to?".  If we were to provide at some point support for `\ifincsname` (we shouldn't), it could be called `\mode_if_in_csname:TF` as in "is TeX currently expanding a csname?".  All other commands mentioned above fit in `runtime` or `sys`.

**Comment by u-fischer** [comment]
I don't think that interactionmode fits into `\mode`.  The TeX typesetting modes `\mode_if_(horizontal|vertical|math|inner):TF`  are imho really something different. While you can change the interaction mode inside a document it is not the natural thing to do.  

I like runtime as it doesn't sounds to static and so fits also for the "changable" values like output and interaction mode.  But I could also offer  `env`, `base`, `basic`, `state`, `altas`.

**Comment by FrankMittelbach** [comment]
Am 12.08.15 um 11:06 schrieb u-fischer:
> I don't think that interactionmode fits into |\mode|. The TeX
> typesetting modes |\mode_if_(horizontal|vertical|math|inner):TF| are
> imho really something different. While you can change the interaction
> mode inside a document it is not the natural thing to do.

I also don't think that the interaction set of states should be bundled 
with the typesetting modes. Technically the former are part of the error 
handling whereas the latter are really typesetting states (and that will 
eventually have its own module (which is why "mode" was perhaps a bad idea).

As for interaction I know at least one case where I explicitly set it. 
(But yes normally it is static).

**Comment by josephwright** [comment]
Actioned in https://github.com/latex3/latex3/commit/d230e78d099aaeebc32d78c98d332eb4fae30d88.
