### ISSUE TITLE
Make \keys_show:nn show more information

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#247]
Right now, `\keys_show:nn` only shows the `.code:n` associated to the key.  For instance,

    \keys_define:nn { foo }
      {
        bar .tl_set:N = \l_foo_tl ,
        bar .value_required:n = true
      }
    \keys_show:nn { foo } { bar }

will show

    > \key code > foo/bar=\protected\long macro:#1->\tl_set:Nn \l_foo_tl {#1}.

and give no information about the fact that a value is required.  From a cursory glance through `l3keys` the "info" property list (whose csname is `\c__keys_info_root_tl \l_keys_path_tl`) can contain the following keys: `choice`, `choices`, `default`, `groups`, `required`, `forbidden`.

@Joseph can I simply `\prop_show:c { \c__keys_info_root_tl \l_keys_path_tl }` to show the information in a reasonable way?

**Comment by josephwright** [comment]
The idea here was models on `.show code` from `pgfkeys`, as that is in general what 'show' functions have tended to do. We can certainly alter, although at present the property list stuff is not documented.

**Comment by blefloch** [comment]
I'm thinking that for instance coffins try to show all information in an accessible manner, so keys should too.  It's probably enough for the moment to just do (a slightly more compact version of) `\prop_show:c { ... }` then the current `\keys_show:nn`.

I was a bit disappointed when realizing that the property list only contains `choice => true` for choice/multichoice keys, rather than a list of the choices.  Is that information preserved anywhere?  More generally, would it be useful to keep track of all keys of a module, etc, so that one can `\keys_show:n { module }`?

**Comment by josephwright** [comment]
@B

**Comment by josephwright** [comment]
@blefloch Do you want to do the logging part as you seem to be working on that at the moment?

In terms of why you can't see what a choice has as sub-choices, notice that a choice key (`/path/foo`) simply means that the value will be mapped to a key 'below' it (`/path/foo/value`). I've not (at present) tried to track the entire tree structure, which would be required to do the look up. This relates to some extent to the idea of keeping a track of all 'current' key values: that is doable without needing to track the entire tree.

**Comment by blefloch** [comment]
@josephwright please take a look at the result that the code i committed gives, and let me know if that's ok.  Should the `code` include `#1->` as i did or not?

**Comment by josephwright** [comment]
This seems to be done :-)
