### ISSUE TITLE
Provide interface for setting rounding mode

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#249]
Taken from comments in  #222: we can easily provide a way to change how intermediate results are rounded when evaluating floating point expressions.  Currently there is no interface.  Should we provide one?

```
\cs_new_protected:Npn \my_fp_term_round_up:n #1
  {
    \group_begin:
    \cs_set_eq:NN \__fp_round:NNN \__fp_round_to_pinf:NNN
    \cs_set_eq:NN \__fp_round_neg:NNN \__fp_round_to_pinf_neg:NNN
    \iow_term:x { \fp_eval:n {#1} }
    \group_end:
  }
\tl_set:Nn \l_expr_tl { 12 / 87 * 87 / 34 * 34 }
\my_fp_term_round_up:n { \l_expr_tl }
\iow_term:x { \fp_eval:n { \l_expr_tl } }
```

My thinking is that we can simply provide `\fp_set_rounding_mode_up:` that does the two `\cs_set_eq:NN` above, and similarly for other rounding modes.

**Comment by josephwright** [comment]
This was sorted ages ago.
