### ISSUE TITLE
Implement arrays of integers

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#250]
Arrays of (global!) dimensions or integers in the range ±(2^30-1) can be implemented by abusing `\fontdimen` parameters.  This would be useful for (I'll update use cases as I remember them)
- storing Unicode data,
- converting from legacy 8-bit encodings to Unicode (and back),
- cleaning up the `l3regex` code by using these arrays rather than all `skip`, `muskip`, etc.,
- storing the many constants that `l3fp` needs,
- `unicode-math` mappings between math alphabets due to `\mathbf` (or `\symbf`) etc.
- storing some input as a list of charcodes for my `runner` package which provides interpreters for various programming languages,
- some other code I have (IIRC).

The main difficulty is that the number of `\fontdimen` parameters must be declared in advance.  Either `l3array` could require users/programmers to specify the size of their array, or it could allow for resizing and manage the space that has been freed.

**Comment by blefloch** [comment]
Partially implemented in `l3experimental/l3str/l3intarray`.  Currently the code is very naive: it requires the user to declare arrays himself and doesn't allow resizing arrays nor freeing them.

**Comment by josephwright** [comment]
I think this is covered by ed1165d477dcf3cf08689451554623a84f2d1411.
