### ISSUE TITLE
l3experimental packages should work in generic mode

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#252]
Most packages in `l3experimental` are not really specific to LaTeX2e.  The only reason that they don't work in plain/ConTeXt is that they use `\RequirePackage{expl3}` instead of the format agnostic `\input expl3-generic\relax`.

If there are no objections, I plan to simply change `\RequirePackage{expl3}` to `\input expl3-generic\relax` in all packages which otherwise work in generic mode.

**Comment by josephwright** [comment]
This is up to you, but remember generic mode is actually quite specialised :-) It's mainly there to support a small number of users with very specific requirements.

**Comment by blefloch** [comment]
This requires a stack like what LaTeX2e does for managing the catcode of `@`, and requires packages to end with a particular command (unless we decide to set `\everyeof`?).  I suggest that we define `\EndExplFile` that does nothing in LaTeX2e (or perhaps `\endinput` or `\ExplSyntaxOff`).  In generic mode, I suggest that we define `\ProvidesExplFile` and `\ProvidesExplPackage` which call `\ExplSyntaxOn` after pushing current catcodes to a stack, and `\EndExplFile` that pops from a stack.

It would also be useful to have an equivalent of `\@ifpackagelater`, but I can live without.

**Comment by wspr** [comment]
Not a bad idea to have an explicit delimiter to mark the end of a package.
I'm in favour.

**Comment by josephwright** [comment]
I'm not keen on having to add stuff to `expl3` packages just to show the 'end' for the _very rare_ case of using things in generic mode. It's nice for the programming layer but that doesn't mean we should treat it in any way as a priority and in particular it shouldn't distort how we write the core ideas.

**Comment by davidcarlisle** [comment]
On 11 August 2015 at 16:01, Bruno Le Floch <notifications@github.com> wrote:

> Most packages in l3experimental are not really specific to LaTeX2e. The
> only reason that they don't work in plain/ConTeXt is that they use
> \RequirePackage{expl3} instead of the format agnostic \input
> expl3-generic\relax.
>
> If there are no objections, I plan to simply change \RequirePackage{expl3}
> to \input expl3-generic\relax in all packages which otherwise work in
> generic mode.
>

I think I'd be rather against that, you can see similar in the
ltluatex/luatexbase packages which aren't expl3 but for various reasons we
want to work in plain, it's not hard to do but it distorts the package
structure.

For plain I'd rather have the calling convention be that the file uses

\input expl3-generic

and then, if we want, that generic file defines enough of the
\ProvidesPackage suite of commands that other
higher level expl3 packages just work.

**Comment by josephwright** [comment]
Note that the 'sensible' packages here (`l3color`, `l3draw`, `l3str` extensions) all do work as @davidcarlisle suggests, e.g.
```latex
\input expl3-generic %
\def\RequirePackage#1{}
\def\ProvidesExplPackage#1#2#3#4{}
\ExplSyntaxOn
\input l3color.sty ~
\input l3draw.sty ~
\draw_begin:
\draw_path_moveto:n { 0cm , 0cm }
\draw_path_lineto:n { 1cm , 1cm }
\draw_path_lineto:n { 2cm , 1cm }
\draw_path_lineto:n { 3cm , 0.5cm }
\draw_path_lineto:n { 3cm , 0cm }
\draw_color_fill:n { yellow!80!black }
\draw_path_use_clear:n { fill , stroke }
\draw_end:
\ExplSyntaxOff
\bye
```

**Comment by blefloch** [comment]
I don't see how adding `\EndExplFile` at the end of the file "distorts the package structure".  It is basically the same as the old habit to end with `\endinput`.

**Comment by josephwright** [comment]
I think we are agreed this is not happening.
