### ISSUE TITLE
Add \file_if_exist_input:nnTF (note second 'n'!)

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#253]
We've had many discussions on how to provide a functionality similar to LaTeX2e's `\InputIfFileExists`.  The discussion inevitably hits the question of whether the true branch should be performed before or after inputting the file.  It is typically very useful to run some _`setup`_ code after testing file existence but before inputting the file, but on the other hand, `TF` is really reserved for things happening after the function has done its work, and the `T` or `F` branch should be followed by the rest of the input stream.

I thus propose `\file_if_exist_input:nnTF {`_`filename`_`} {`_`setup`_`} {`_`True`_`} {`_`False`_`}` defined as

```
\prg_new_protected_conditional:Npnn \file_if_exist_input:nn #1#2 { TF }
  {
    \file_if_exist:nTF {#1}
      {
         #2
        \file_input:n {#1}
        \prg_return_true:
      }
      { \prg_return_false: }
  }
```

The _`setup`_ argument is inspired by the similar arguments of `\tl_rescan:nn`, `\tl_set_rescan:Nnn`, and `\iow_wrap:nnnN`.

**Comment by wspr** [comment]
I am happy with this `:)`

**Comment by FrankMittelbach** [comment]
what about

\file_if_exist_use:nTTF

instead or even perhaps more logical

\file_if_exist_use:nTFT

not sure I'm serious ... it is hot and just after lunch

**Comment by blefloch** [comment]
Let's say you're not serious :).  The `TF` branches really should behave as much as possible as those of a conditional (and in my proposal they precisely are).  Having two `T` does not really make sense, although I do have to agree that what I call the *`setup`* argument is indeed only run in the True case.  I'd prefer `n`, but if others prefer `T`, I'll accept it: better get the function with a non-optimal name than not get the function.

**Comment by FrankMittelbach** [comment]
Am 12.08.15 um 17:49 schrieb Bruno Le Floch:
> Let's say you're not serious :). The |TF| branches really should behave
> as much as possible as those of a conditional (and in my proposal they
> precisely are).

well I'm partly serious but I'm aware that my proposal wouldn't fly

> Having two |T| does not really make sense, although I do
> have to agree that what I call the /|setup|/ argument is indeed only run
> in the True case. I'd prefer |n|, but if others prefer |T|, I'll accept
> it: better get the function with a non-optimal name than not get the
> function.

my main question really is: is there really a practical use case for 
this (in terms of being needed more often) after all if this is used 
only once or twice then people could simply code

\file_if_exist:nT{foo}
   {<setup>
    \input{foo}
    <post-setup>
   }

without much loss.

The second question is how often does one need a post-setup ever.

So all in all I guess I would vote for

\file_if_exist_input:nTF

with TF being executed before inputing the file (as that is I think the 
more common need)

**Comment by blefloch** [comment]
(Sorry, I just changed `if_exist_use` to `if_exist_input` throughout the thread including Frank's comments, presumably that's what everybody meant.)

I agree with you that the most frequent use case will be (in my notations) `\file_if_exist_input:nnF` because performing some code after loading the file is typically not so useful.  However, your proposal would make `\file_if_exist_input` an exception among all functions with `TF` branches: all of them do "(Try to) do something, then if it succeeded run `T`, and if it failed, `F`." and the `T` or `F` code is always directly followed by the rest of the input stream, with no `expl3` junk in between.

Use case for `nnTF`:

    \file_if_exist_input:nnTF { foobar-table.dat }
      {
        \begin{tabular}{ccc}
        \ExplSyntaxOff
      }
      { \end{tabular} }
      { \msg_error:nn { mypkg } { foobar-missing } }

**Comment by wspr** [comment]
Nice use case `:)`.

Many of the `_case` commands also are most commonly used with only the `F` branch and I'd see something similar here where `\file_if_exist_input:nnF` turns out to be the one that's most commonly used. And having the `TF` version adds nice symmetry. I'm in agreement with Bruno.

**Comment by josephwright** [comment]
I think we are pretty happy with the set of functions we now have in this area: closing for the present as I doubt we'll do it.
