### ISSUE TITLE
:w or :ww for several 'weird' arguments?

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#255]
The only appearance of a 'weird' argument in `l3styleguide` is in an auxiliary function

```
\cs_new_protected:Npn \@@_function_aux:w #1#2 \q_stop { ... }
```

This suggests that the preferred signature for such a function is simply `:w`, with no further detail specfying e.g. the number of arguments.  My preferred style is to be as informative as possible, following the lead of `\exp_after:wN`.  Thus I would give the function the signature `:nw` or `:Nw` depending on whether its first argument may be several tokens or must be a single one.

One advantage of this style is that `\cs_generate_variant:Nn` is able to provide expansion for the arguments before the weird argument.  Another advantage is that the function's signature still says how many argument the TeX macro has.  One drawback is that in complicated cases the function's signature looks crazy (e.g., `\__fp_rrot:www` or `\__fp_small_int:wTF`).

If others in the team agree that continuing to keep track of other arguments before/after a weird argument is good, it should be added to `l3styleguide`.

**Comment by josephwright** [comment]
As I wrote the style guide, I'll do this.

**Comment by FrankMittelbach** [comment]
Am 12.08.15 um 05:52 schrieb Bruno Le Floch:
> The only appearance of a 'weird' argument in |l3styleguide| is in an
>  auxiliary function
>
> |\cs_new_protected:Npn \@@_function_aux:w #1#2 \q_stop { ... } |
>
> This suggests that the preferred signature for such a function is
> simply |:w|, with no further detail specifying e.g. the number of
> arguments.

I don't think that this represents accurately the initial thoughts for 
"w". The initial though was that "w" represents the set of *all* final 
arguments if they do not follow the normal parsing convention without 
detailing them further (ie not trying to encode the number of final 
arguments).

At a later stage we made one exception which is |\exp_after:wN|  --- 
that was initially but |\exp_after:NN| but we realized that the first N 
is wrong.

> My preferred style is to be as informative as possible, following the
> lead of |\exp_after:wN|. Thus I would give the function the signature
> |:nw| or |:Nw| depending on whether its first argument may be several
> tokens or must be a single one.
 > One advantage of this style is that |\cs_generate_variant:Nn| is able
 > to provide expansion for the arguments before the weird argument.

agreed about |:nw| or |:Nw| and the fact that this allows 
|\cs_generate_variant:Nn|


> Another advantage is that the function's signature still says how
> many argument the TeX macro has. One drawback is that in complicated
> cases the function's signature looks crazy (e.g., |\__fp_rrot:www| or
>  |\__fp_small_int:wTF|).

we felt back then (and I still do :-) ) that denoting the number of 
arguments in that particular case is not that helpful because without 
looking into the function you wouldn't know what the arguments are 
anyway, e.g. what does |\foo:ww 12345| tell you without knowing about
|\cs_new:Npn \foo:ww #1 23 #2 5{...}| ?

So the approach was that "w" means weird arguments ahead and you need to 
look into the function to really understand the details.

And the variant business doesn't work "after" the weird part either so 
denoting "normal" args there is not really helpful either.

So in retrospect we should have perhaps called |\exp_after:wN| just 
|\exp_after:w| but on the other hand in that case the "N" still is 
really visible in the code so is is/was probably fine as it is.

> If others in the team agree that continuing to keep track of other
> arguments before/after a weird argument is good, it should be added
> to |l3styleguide|.

I'm for keeping track of the one ones before (and I think this is what 
is done in real code (it least mine :-)) but I would not go for denoting 
arguments after "w" normally

**Comment by josephwright** [comment]
@FrankMittelbach Good argument. I think we can probably live with `\exp_after:wN`, not least because it is quite well-defined for a `w`-type argument (the next non-space token even if `{`/`}`).

**Comment by wspr** [comment]
I agree with Bruno on this; informally I'd say that if you said each weird argument was denoted by `w`, but multiple `w` collapsed together, and `w` before anything else collapses to `w`, you'd have:

* `\cs_set:Npn foo:w xyz #2 / #3 / #4 \q_stop { ... }`
* `\cs_set:Npn foo:w xyz #2 / #3 / #4 \q_stop #5 { ... }`
* `\cs_set:Npn foo:Nw #1 xyz #2 \q_stop { ... }`
* `\cs_set:Npn foo:Nw #1 xyz #2 / #3 / #4 \q_stop { ... }`

All of these "feel" quite sensible to me, and IMO occur relatively often when you're passing data around various parsing functions.

---

TBH I still quite like my old proposal to write things like

    \cs_set:Npn \foo:wq #1/#2 \q_stop

I.e., `q` indicates a quark delimiter that terminates the preceding `w`. Again, to me it "felt" quite natural in the code. But I'm okay with not using it `:)`

**Comment by FrankMittelbach** [comment]
Am 12.08.15 um 09:14 schrieb Joseph Wright:
> @FrankMittelbach <https://github.com/FrankMittelbach> Good argument. I
> think we can probably live with |\exp_after:wN|, not least because it is
> quite well-defined for a |w|-type argument (the next non-space token
> even if |{|/|}|).

right, which is why we settled on it. All I was saying is that it is a 
bit outside the general approach (but I wouldn't change it).

**Comment by FrankMittelbach** [comment]
Am 12.08.15 um 10:00 schrieb Will Robertson:
> I agree with Bruno on this; informally I'd say that if you said each
> weird argument was denoted by |w|, but multiple |w| collapsed together,

informally I wouldn't, I guess. Instead I think of "w" is denoting 
anything arbitrarily complex in terms of argument(s). After all you 
can't really see the arguments when you see the command in action (only 
when you look at its definition. An so having several "w" in succession 
doesn't really tell you much.


> and |w| before anything else collapses to |w|, you'd have:
>
>   * |\cs_set:Npn foo:w xyz #2 / #3 / #4 \q_stop { ... }|
>   * |\cs_set:Npn foo:w xyz #2 / #3 / #4 \q_stop #5 { ... }|

The last one would be ":wn" if you do normal arguments on the right (or 
multiple "w" collapsed).

And I think hiding "w" in the middle of the signature is bad as it no 
longer stands out in that case which is the to me an important aspect.


>
> TBH I still quite like my old proposal to write things like
>
> |\cs_set:Npn \foo:wq #1/#2 \q_stop |
>
> I.e., |q| indicates a quark delimiter that terminates the preceding |w|.
> Again, to me it "felt" quite natural in the code. But I'm okay with not
> using it |:)|

what speaks against this is that so far the letters in the signature 
denote arguments while "q" would not denote an argument here but "wq" 
but perhaps that could be talked away :-)

But what about

|\cs_set:Npn \foo:wq #1\q_continue #2 \q_stop |

should that now be ":wqwq" or ":wqq" or ...?

maybe ":wqq" but I'm not sure we want to change anything in this space. 
It would be rather dramatic and to what gain?

**Comment by blefloch** [comment]
I think that `:wn` (to go back to Frank's example here) doesn't hide the `w` too much, and it helps understand what is going on in some cases.  For instance, to reverse a string (ignore spaces), I'd do something like

    \cs_set:Npn \str_reverse:n #1
      { \__str_reverse_loop:Nwn #1 \q_recursion_tail \q_recursion_stop { } }
    \cs_set:Npn \__str_reverse_loop:Nwn #1#2 \q_recursion_stop #3
      {
        \quark_if_recursion_tail_stop_do:nn {#2}
          { \exp_after:wN \use_none:n \use:n }
        \__str_reverse_loop:Nwn #2 \q_recursion_stop { #1 #3 }
      }

and knowing that the last argument is `n` helps me understand/remember that I am collecting something there.

I'd prefer if we allow for both conventions, but I don't feel that strongly about it.

**Comment by wspr** [comment]
After some lengthy discussion (commit/b08f40a9e4a478761d951dab5fed3f3c736b705b) it seems like there's not too much to add here. Some wording could be improved probably but I hope I've caught the main idea.

Happy to close this as an issue?
