### ISSUE TITLE
\bool_const:Nn, \seq_const:Nn, \prop_const:Nn

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#257]
There was no conclusion in the most recent discussion about adding `\bool_const:Nn` as an analogue of `\int_const:Nn` etc.  Such a function would be used for things like

```
\bool_const:Nn \c_@@_unicode_bookmarks_bool
  {
    \luatex_if_engine_p: || \xetex_if_engine_p: ||
    \prop_if_in_p:Nn \g_@@_options_prop { unicode-bookmarks }
  }
% ...
\bool_if:NTF \c_@@_unicode_bookmarks_bool { ... } { ... }
```

In a similar space, there are potential `\seq_const:Nn` and `\prop_const:Nn`.  We already have `\seq_set_from_clist:Nn` and `\seq_set_split:Nnn`  We could provide `\seq_const_from_clist:Nn` and `\seq_const_split:Nnn`.  For initializing props we could do `\prop_const_from_keyval:Nn` (and similar `set` and `gset` functions.

**Comment by wspr** [comment]
I'm sold on the `bool` case, as it's quite a simple data type; I'd be happy to include the others for consistency, or instead add a sentence to the documentation "`const` functions are not provided for complex datatypes, you should use `_new` plus some setting function if you need it". What are your thoughts?

**Comment by blefloch** [comment]
There are a couple places where `\seq_const_from_clist:Nn` and `\prop_const_from_keyval:Nn` would be useful.  I'll go ahead and add them to `l3candidates`.  Also `\bool_const:Nn`.

**Comment by blefloch** [comment]
I forgot to mention that the previous approach of using `\prop_new:N` then `\prop_put:Nnn` does not work anymore with `check-declarations`, because that option now checks that local/global assignments are not mixed nor applied to constants (actually the approach can still be used between `\debug_suspend: ... \debug_resume:`).

I'm closing since I've added to `l3candidates` almost all functions described here: the exception is `\seq_const_split:Nnn`, and I haven't provided the unclear aliases `\seq_const:Nn` and `\prop_const:Nn`.
