### ISSUE TITLE
\fp_to_scientific does not always include the exponent part

### ISSUE THREAD

**Issue by josephwright** [latex3/latex3#258]
As currently documented

``` tex
\input expl3-generic\relax
\ExplSyntaxOn
\exp_args:Nf \tl_show:n { \fp_to_scientific:n { 1.0 } }
```

should give `1e0` but gives just `1`, the documented behaviour for `fp_to_tl:n`.

**Comment by josephwright** [comment]
Note that `\fp_to_scientific:n { 1e1 }` or `\fp_to_scientific:n { 10 } ` do lead to the expected output but that `\fp_to_scientific:n { 1e0 } ` does not! Thus it looks like an issue with zero-value exponents.

**Comment by josephwright** [comment]
I see it's deliberate:
```tex
    \cs_new:Npn \@@_to_scientific_normal:wnnnnn
        \s_@@ \@@_chk:w 1 #1 #2 #3#4#5#6 ;
      {
        \if_int_compare:w #2 = \c_one
          \exp_after:wN \@@_to_scientific_normal:wNw
        \else:
          \exp_after:wN \@@_to_scientific_normal:wNw
          \exp_after:wN E
          \int_use:N \__int_eval:w #2 - \c_one
        \fi:
        ; #3 #4 #5 #6 ;
      }
```
but not documented: change either the code or the docs?

**Comment by blefloch** [comment]
You have more experience in how numbers should be displayed.  What would `siunitx` do by default in this case?  I'm minded to include `e0` so that it is easier to manipulate things programmatically.

**Comment by josephwright** [comment]
@blefloch  `siunitx` does 'display': I only have manipulation when it's forced! For 'scientific' output of the form we've got here I'd always include the exponent. We have `\fp_to_tl:n` for the 'flexible' case, after all. (The latter does something similar to the `pgfplotstable` approach to the same area.)

**Comment by blefloch** [comment]
Ok.  Can you please make the change?  I should really prepare my trip to the US.

**Comment by josephwright** [comment]
Will do later on: looks easy enough. I'll also document the behaviour and alter the catcode of `e`.

**Comment by josephwright** [comment]
There are a few issues here: I'm going to raise on LaTeX-L.

**Comment by blefloch** [comment]
Reading through later discussions it seemed the consensus was to change catcode of `e` to letter, and always include a `.` and `e`.  For special markers it's not clear, but at least the `\fp_to_tl:n` ones should be catcode letter.

**Comment by blefloch** [comment]
Right now I have some code that gives things like

    -3.666666666666667e0
    -1.000000000000000e0
    0.000000000000000e0
    1.200000000000000e1
    1.525878906250000e-4
