### ISSUE TITLE
Possible additions to l3token

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#260]
This is to record several ideas of additions to l3token.
- `\token_to_char:N` expanding to a character, based on the `\meaning` of a given token (and giving `\scan_stop:` if the token is not a character token).  E.g., `\token_to_char:N \bgroup` would give `{` (of catcode other).
- `\token_if_definable:NTF` (expandable), which gives true if the token is a control sequence (even `\bgroup` or others which currently give false for `\token_if_cs:NTF`) or is an active character, and false for explicit non-active character tokens.
- `\peek_catcode_case:nTF`, `\peek_charcode_case:nTF`, `\peek_meaning_case:nTF` (or perhaps swap `case` with the other word), to run different code depending on what the following token is.  Perhaps similar functions with `_ignore_spaces` or `_remove`.

**Comment by blefloch** [comment]
Also about `l3token`: right now `\token_if_int_register:NTF` doesn't see integer constants between 0 and the max `\mathchar` or `\char` as registers, because they are implemented using `\mathchardef` or `\chardef`.  Not sure we should keep `\token_if_int_regiser:NTF` in a rewriting of `l3token`, but otherwise worth keeping in mind.

**Comment by FrankMittelbach** [comment]
Am 26.09.15 um 21:10 schrieb Bruno Le Floch:
> Also about |l3token|: right now |\token_if_int_register:NTF| doesn't see
> integer constants between 0 and the max |\mathchar| or |\char| as
> registers, because they are implemented using |\mathchardef| or
> |\chardef|. Not sure we should keep |\token_if_int_regiser:NTF| in a
> rewriting of |l3token|, but otherwise worth keeping in mind.

my question would be what are the intended use cases for such a test?

I mean why would you want to know that a certain constant is implemented 
as a register? Probably for constants that should in reality always 
return false --- if you want any of those tests at all (on a 
non-internal basis).

**Comment by blefloch** [comment]
To be honest, I think most of `l3token` should be deprecated and removed, but we haven't yet had time to figure out what exactly.  That particular behaviour of `\token_if_int_register:NTF` is most probably wrong, unless we rename it `\token_if_tex_count:NTF` or something like that.

At an `expl3` level, it could make sense to have a `\token_guess_type:N` which returns `int` for `\count123`, `\mathchar"ABC` and `\char"ABC`, `dim` for `\dimen123`, `skip` for `\skip123`, `muskip` for `\muskip123`, `tl` for `macro:->...` unless it starts with `\s__seq` in case it should give `seq`, or `\s__prop` giving `prop`, etc.  (One difficulty is boxes, which are currently indistinguishable from constants.) The current tests are probably almost useless.

After googling a bit, I find `\token_if_int_register:cTF { c@#1 }` used in `zhnumber`, so presumably some of these tests have uses (LaTeX counters are indeed implemented as `\count` registers).

**Comment by josephwright** [comment]
@blefloch  I suspect your are right that a lot of the stuff here will need to be re-though: there's of course a difference between '`expl3` on 2e' and 'pure `expl3`' in that regard (see also _e.g._ `\char_set_lccode:nn`).

**Comment by FrankMittelbach** [comment]
Am 28.09.2015 um 14:47 schrieb Bruno Le Floch:
> After googling a bit, I find |\token_if_int_register:cTF { c@#1 }| used
> in |zhnumber|, so presumably some of these tests have uses (LaTeX
> counters are indeed implemented as |\count| registers).

not in the version of the package that is in TL2015 (I think) and the 
above would have been somewhat suspicious I guess because c@#1 in 2e is 
supposed to be either a register or undefined (\relax) but nothing else. 
So what I see here

\int_if_exist:cTF { c@#1 }

makes much more sense

**Comment by blefloch** [comment]
That was 3 years ago, sorry.

In most cases, `\int_if_exist:cTF` will do fine, I admit.  But I think `\token_if_int_register:cTF { c@#1 }` makes some sense, as someone unaware of the LaTeX convention on counters might have defined a command `\c@...` and checking that indeed we have an `int` variable is useful.

**Comment by josephwright** [comment]
We are pretty clear we want to tighten up `l3token`. I'm going to close here: if there are useful additions after a tidy-up, they can be noted separately.
