### ISSUE TITLE
\tl_set_rescan:Nnn gives an error with an empty token list arg

### ISSUE THREAD

**Issue by josephwright** [latex3/latex3#266]
Using 
```tex
\tl_set_rescan:Nnn \l_tmpa_tl {} {} 
```
gives error
```
! Improper alphabetic constant.
<to be read again> 
                   \__int_eval_end: 
```
This should be sorted: a quick test for an empty `tl` should do it.

**Comment by blefloch** [comment]
> ```tex
> \tl_set_rescan:Nnn \l_tmpa_tl {} {}
> ```
> gives error
>
> This should be sorted: a quick test for an empty `tl` should do it.

I looked.  This is the correct fix indeed.
