### ISSUE TITLE
Hyperlinks in interfaces documentation

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#274]
Quoth D.B. on LaTeX-L: there's a bug in The LaTeX3 Interfaces documentation: in the index, all
pages numbers' hyperlinks go to page 1.

**Comment by minoki** [comment]
Running the `latex` program twice seems to solve the problem.

I added the following code to [the `typeset` function](https://github.com/latex3/latex3/blob/master/l3build/l3build.lua#L1407) in `l3build.lua`, and the generated links in the Index section works as expected.
```diff
diff --git a/l3build/l3build.lua b/l3build/l3build.lua
index 75ca48d..1188b4a 100644
--- a/l3build/l3build.lua
+++ b/l3build/l3build.lua
@@ -1423,6 +1423,9 @@ typeset = typeset or function(file)
       if errorlevel ~= 0 then
         errorlevel = cycle(name)
       end
+      if errorlevel == 0 then
+        errorlevel = tex(file)
+      end
     end
     return errorlevel
   end
```

I noticed this problem when reading `source2e.pdf` (I suppose LaTeX2e documentation is also generated with `l3build.lua`).

**Comment by josephwright** [comment]
Looking at this, the `~=~` is wrong: should be `==`: a very easy fix coming up!
