### ISSUE TITLE
xfrac's \sfrac command needs curly braces 

### ISSUE THREAD

**Issue by gvdeynde** [latex3/latex3#283]
Using 

`$f(x) = \left(\frac{T}{T_0}\right)^\sfrac{1}{2}$` 

leads to an error in xelatex ('Missing } inserted'). It took me a while to figure out I had to brace the sfrac command like 

`$f(x) = \left(\frac{T}{T_0}\right)^{\sfrac{1}{2}}$` 

which is a bit counter-intuItive and not in line with a classical fraction which allows this syntax:

`$f(x) = \left(\frac{T}{T_0}\right)^\frac{1}{2}$`

`

**Comment by josephwright** [comment]
This is entirely to be expected: whilst things like `\mathrm` are set up to work with `^` and `_` even without braces, in general `^` and `_` should be treated as being macro-like and taking (braced) arguments.

**Comment by josephwright** [comment]
Note that the LaTeX2e manual is clear on arguments _always_ needing braces in the document-level syntax.
