### ISSUE TITLE
Expandable xparse commands and l/u arguments

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#285]
The `xparse` documentation says that for expandable document commands, "The mandatory argument types \texttt{l} and \texttt{u} are not available."  I don't understand why there is such a restriction.

Just a reminder: "l" grabs an argument delimted by a left brace, using the `\def\foo#1#{...}` trick (trailing `#` in parameters); "u" grabs a delimited argument.  Both of these can be done by expandable functions, and are simpler than `d`/`D` optional arguments.

I may be missing the original reason.

**Comment by josephwright** [comment]
I think it was mainly that supporting them means creating more aux functions at point of definition and we were not aiming to 'encourage' either expandable definitions or odd arg types. For `l`-type I'd also check what happens with a non-standard open-arguemtn charcode set up (it may not work in any case).

**Comment by blefloch** [comment]
Well, `l` wouldn't work with a non-left-brace catcode 1 character even for non-expandable commands.  I agree that these arguments require defining more functions, but it's no different from `d` and `D` types, which we are not particularly discouraging.

**Comment by josephwright** [comment]
Sure: quite possibly this is more 'I couldn't be bothered to do all of the cases' more than anything else! I've no objection to a change here if you like.

**Comment by blefloch** [comment]
Grabbing `l` and `u` type arguments expandably is fine on their own.  However, after an optional argument that was not there the next token is braced.  This will break `l` and `u`-type arguments: the former because there may be an unexpected brace too early and the second because the delimiter may be broken up by the braces.

I'm closing this issue since it is not possible to implement `l` and `u` after optional args (`t`, `s`, `o`, `O`, `d`, `D`) and it would be messy to only allow them after mandatory args (both in terms of explanations in the doc, and in terms of code).
