### ISSUE TITLE
\NewDocumentCommand etc should be document commands

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#286]
At the moment, `\ShowDocumentCommandArgSpec{\NewDocumentCommand}`  complains that `\NewDocumentCommand` is not a document command.  I think it should be one.

This applies to all commands defined by `xparse`, and is an easy change: replace e.g.

    \cs_new_protected:Npn \DeclareDocumentCommand #1#2#3
      { \@@_declare_cmd:Nnn #1 {#2} {#3} }

by

    \cs_new_protected:Npn \DeclareDocumentCommand { }
    \@@_declare_cmd:Nnn \DeclareDocumentCommand { m m m }
      { \@@_declare_cmd:Nnn #1 {#2} {#3} }

(the first line ensures `\DeclareDocumentCommand` is not yet defined)

Perhaps `\ExplSyntaxOn` and `\ExplSyntaxOff` also should be document commands.

**Comment by josephwright** [comment]
This is by-design: they are _not_ document commands (not the Camel-case names). `xparse` is for _defining_ document commands so works at the _design_ level.

**Comment by blefloch** [comment]
Ah, ok, it makes sense.  So conceptually, `\RequirePackage` would not be a document command, but `\usepackage` would?

Anyway, we should improve the error message from `Unknown document command '\NewDocumentCommand'` to `'\NewDocumentCommand' is not a document command` for cases where the command is actually defined.

Not that anyone will use `\ShowDocumentCommandArgSpec` given how long its name is...

**Comment by josephwright** [comment]
Yes, that was the plan last time we discussed it (more or less). The idea is that `xparse` is about one form of translation for a 'document' to code syntax, whereas set up in a preamble would presumably be separate. Of course, until we have some real L3 docs this is a bit academic!

Certainly you are right about the error message :-)
