### ISSUE TITLE
Check that first argument of \NewDocumentCommand is a single definable token

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#287]
We should check that the command-to-be-defined argument of `\NewDocumentCommand` and friends is a single token, and that it is definable.  This would catch silly mistakes such as

    \NewDocumentCommand{foobar}{}{}

giving

    ! LaTeX Error: Missing \begin{document}.

**Comment by josephwright** [comment]
Certainly: I think this has come up before but has just not been implemented.

**Comment by blefloch** [comment]
I'm minded to add a conditional `\tl_if_definable_token:nTF` to `l3candidates` for `l3tl`.  Is that too specific, and should it better be in `xparse`?

**Comment by blefloch** [comment]
I'm still not sure whether to put the test in `l3tl` or `xparse`, but for the record I'm writing the steps needed.

This test should x-expand `\tl_trim_spaces:n` then do `\tl_if_single_token:nTF` on the result, then test definability of the single token.  For the record, here is possible code

    \prg_new_protected_conditional:Npnn \@@_if_definable_token:n #1
      { TF }
      {
        \group_begin:
          \tl_set:Nx \l_@@_tmpa_tl { \tl_trim_spaces:n {#1} }
          \tl_if_single_token:NTF \l_@@_tmpa_tl
            { \exp_args:No \@@_if_definable_token_aux:n { \l_@@_tmpa_tl } }
            { \group_end: \prg_return_false: }
      }
    \group_begin:
      \char_set_catcode_active:n { `\^^@ }
      \cs_new_protected:Npn \@@_if_definable_token_aux:n #1
        {
          \int_set:Nn \tex_escapechar:D { 92 }
          \exp_args:Nx \tl_if_empty:nTF
            { \exp_args:No \str_tail:n { \token_to_str:N #1 } }
            {
              \exp_args:Nx \char_set_lccode:nn
                { ` \str_head:n {#1} } { `^^@ }
              \tex_lowercase:D { \tl_if_eq:nnTF {#1} } { ^^@ }
                { \group_end: \prg_return_true: }
                { \group_end: \prg_return_false: }
            }
            { \group_end: \prg_return_true: }
        }
    \group_end:

Using `\tex_lowercase:D` could be avoided, but it still seems like the best approach to detect active characters let equal to the same non-active character.  Such tokens are definable but the only ways to detect them are to (1) redefine the active character with that character code and see if the token's meaning changes, (2) compare the token to the active character using `\tl_if_eq:nnTF` or a delimited argument, (3) compare the token to the non-active character using `\tl_if_eq:nnTF` or a delimited argument, (4) normalize the token's character code using `\lowercase` or `\uppercase` and apply methods 2 or 3 to the normalized token.  Methods 1 and 2 require needlessly building an active character, which pollutes the hash table in XeTeX.  Method 3 requires distinguishing various cases according to the category code of the token's meaning (and requires `\lowercase` under the hood, in the guise of `\char_generate:nn`).  Method 4 is robust and quite straightforward; its only drawback is the explicit use of `\tex_lowercase:D`.

**Comment by blefloch** [comment]
I opted for putting the code in `xparse`.  The code is slightly wrong and must use any character other than `^^@` because lowercasing with an `\lccode` of 0 does nothing.
