### ISSUE TITLE
Integer division might be broken

### ISSUE THREAD

**Issue by hmenke** [latex3/latex3#290]
I wanted to implement an RNG for `expl3` but found that the integer division inside `\int_eval:n` is broken.  The following MWE outputs something like

    -93000930
    -93100931
    -93000930

Typeset with `lualatex` as it uses Lua for comparison to prove that TeX itself isn't off.

    \documentclass{article}
    \usepackage{expl3}
    \begin{document}
    \ExplSyntaxOn
    \newcount\cnt
    \cnt=93082241\relax
    \divide\cnt by 100001\relax
    \multiply\cnt by -100001\relax

    \the\cnt\par
    \int_eval:n { -100001 * ( 93082241 / 100001 ) }\par
    \lua_now:n { tex.sprint( -100001 * math.floor( 93082241 / 100001 ) ) }
    \ExplSyntaxOff
    \end{document}

**Comment by hmenke** [comment]
As discussed in the TeX.SX chat, the bug is in `\numexpr`, i.e. in the TeX engine itself.

**Comment by blefloch** [comment]
@hmenke You got me worried about eTeX having a bug.  Actually it's not a bug anywhere.  Contrarily to TeX's `\divide`, eTeX division rounds to the nearest integer (ties away from zero).  If you want to round the result towards zero (i.e., floor for positive and ceil for negative) use `\int_div_truncate:nn`, so

    \int_eval:n { -100001 * \int_div_truncate:nn { 93082241 } { 100001 } }

Using `l3fp` as `\fp_eval:n { -100001 * floor(93082241/100001) }` works but is very significantly slower than integer expressions.
