### ISSUE TITLE
Move l3sort to l3kernel

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#291]
Requested by Denis B.: move `l3sort` (sorting token lists, comma lists and sequences) from experimental to stable.

We need to check whether the interface is acceptable.

I should check whether one of the numerous sort implementations I tried is faster than the one currently in.  IIIRC, `l3sort` only supports lists with less than roughly 20000 items; I may need to think of a way to extend that (even with lower performance).

I may need to think again about the possible interaction with ideas about a future `l3obj`.

**Comment by josephwright** [comment]
The implementation detail is only important in as far as it impacts on interface. I suspect that a limit of 20k items is acceptable for almost all users. (If someone really does need to sort more items then saying 'you'll need an external tool' isn't so unreasonable.)

**Comment by blefloch** [comment]
Should that be closed now that @josephwright moved `l3sort` to `l3kernel`?

**Comment by josephwright** [comment]
Closed by 376cbf0.
