### ISSUE TITLE
Experimental packages should be mentioned in "The LaTeX3 Interfaces" documentation

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#292]
Because not mentioned in "The LaTeX3 Interfaces" documentation, one can miss the experimental packages (`l3sort`, `l3str`, `xcoffins`, `xgalley`).

Well, there are exceptions:
- `xcoffins` is mentioned,
- `l3str` is both in the experimental bundle and in `expl3` (what's its status?)

**Comment by josephwright** [comment]
I think we are pretty clear we _don't_ want to do this, on reflection. `interface3` is meant to be the 'stable' part of our work: indeed we are trying to get things tigher in that regard.

**Comment by dbitouze** [comment]
OK but `l3experimental` is incidentally mentioned (twice). It could be clearly explained that:

 - it exists,
 - what role it has,
 - it is a danger zone.

**Comment by pablgonz** [comment]
@josephwright  I think this is clear from the current documentation.

**Comment by dbitouze** [comment]
@pablgonz  I don't see what you mean.

**Comment by pablgonz** [comment]
@dbitouze `l3str` for example is stable (`l3str-format` is experimental). That's clear to me in 'interface3', with 'expl3' it's the same.

**Comment by dbitouze** [comment]
> @dbitouze `l3str` for example is stable

Indeed.

> (`l3str-format` is experimental). That's clear to me in 'interface3', with 'expl3' it's the same.

My point is e.g. `l3str-format` isn't mentioned neither in `interface3` nor in `expl3`. Okay, `l3experimental` is quite explained in the latter but, once again, only incidentally  mentioned (twice) in the former (the main point of this issue). `interface3` could clearly explain that `l3experimental`:

-  exists,
-  what's its role,
-  it is a danger zone,

and lists its packages. It would have been helpful for me when `l3sort` was in `l3experimental` and I was looking in vain for the features it provides in `interface3`.

**Comment by pablgonz** [comment]
@dbitouze Now I understand your point, it's true, the only information about who makes up `l3experimental` is in the `README.md` file and is not mentioned in `expl3`.

**Comment by josephwright** [comment]
Things have moved on here and I think we won't be changing the doc structure.
