### ISSUE TITLE
Add \prop_count

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#293]
The number of items in a sequence or in a clist is easily available, thanks to `\seq_count:(N|c)` and `\clist_count:(N|c|n)`. It could be helpful to provide similar command for property lists.

**Comment by blefloch** [comment]
Sounds useful indeed.  I'll try to do that soonish.  In the meantime you can do

    \cs_new:Npn \__dbitouze_prop_count:nn #1#2 { + 1 }
    \cs_new:Npn \dbitouze_prop_count:N #1
      { \int_eval:n { 0 \prop_map_function:NN #1 \__dbitouze_prop_count:nn } }

**Comment by dbitouze** [comment]
Thanks!
