### ISSUE TITLE
Latest code totally breaks compilation; possible fix

### ISSUE THREAD

**Issue by kalrish** [latex3/latex3#295]
I recently updated my TeX Live installation and the latest code broke document compilation. I currently have no time to properly dig into the issue nor the knowledge to feel sure about this fix, but here it goes, should it be useful to you.

[l3kernel/l3bootstrap.dtx, lines 365-366](https://github.com/latex3/latex3/blob/c6cf993c06b24c56912e209f6d29c28fd5ae8889/l3kernel/l3bootstrap.dtx#L365):

    local charcat_table = \number\ucharcat@table
    l3kernel.charcat_table = charcat_table
Here, the engine complains and aborts. I don't know why. For it to work, these two lines must be turned into this one:

    l3kernel.charcat_table = \number\ucharcat@table
Lua-wise, this change is totally innocuous; actually, the new code is equivalent to the older, but simpler. That `local charcat_table` exists only in the scope of the `\directlua`, so I guess it was just forgotten there and may be removed safely. Therefore, I guess there are dark things happening on the TeX side. The output with this change is as expected.

I hope I haven't wasted your time. I'm sorry for not submitting this issue properly.

**Comment by josephwright** [comment]
Can you upload or send me (joseph.wright@morningstar2.co.uk)  a `.log` for a simple file, _e.g._ just

    \RequirePackage{expl3}
    \stop

The two constructs aren't quite equivalent for me the one we have works, so I need to track down where the issue is.

**Comment by kalrish** [comment]
With the following code:

    \RequirePackage{expl3}
    \stop
* LuaTeX is fine.
* LuaJITTeX, however, complains:

```
This is LuajitTeX, Version beta-0.80.0 (TeX Live 2015/W32TeX) (rev 5238) 
 restricted \write18 enabled.
(./main.tex
LaTeX2e <2015/10/01> patch level 2
Babel <3.9m> and hyphenation patterns for 18 languages loaded.
(c:/texlive/2015/texmf-dist/tex/latex/l3kernel/expl3.sty (c:/texlive/2015/texmf-dist/tex/latex/l3kernel/expl3-code.tex
! LuaTeX error [\directlua]:1: malformed number near '5l3kernel.charcat_table'.
l.282     }
         %
? 
```
I was working with LuaJITTeX but didn't notice it, and thought that the error was due to the code itself. Sorry about that. Do you need anything more?

**Comment by josephwright** [comment]
Hmm, looks like a difference is space treatment between the two LuaTeX engines. I'll add a defensive `\space` which should deal with it.

**Comment by kalrish** [comment]
That solves the problem. Thanks!

The difference seems quite weird from an outsider's point of view. Could it be a bug in LuaJITTeX?

**Comment by josephwright** [comment]
I assume it's a bug in one or other of LuaTeX/LuaJITTeX (clearly they are handling spacing differently).
