### ISSUE TITLE
\fp_factorial:n and \fp_gamma:n

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#297]
See LaTeX-L: proposed addition of "factorial" and "gamma", which could be useful to integrate into the kernel (or as a separate package perhaps).  Main idea for gamma is to use the [Lanczos approximation](https://en.wikipedia.org/wiki/Lanczos_approximation) with relative error about 1e-11.  To reduce the relative error down to 1e-16 as I'd like we have to either include more terms in the Lanczos approximation, or to use Spouge's approximation, which has easier-to-compute coefficients.

**Comment by blefloch** [comment]
We should provide `lngamma` instead of `gamma`, because the latter overflows/underflows for relatively small arguments.

For a small argument (in [-100,100] or so), reduce to (1,2) or some such to use Lanczos.

For a negative argument use the reflection formula Gamma(1-z)=pi/sin(pi z)/Gamma(z).

For a positive argument greater than about 100, a few terms of [Stirling's approximation](https://en.wikipedia.org/wiki/Stirling%27s_approximation) are enough to get 16 digits.

**Comment by josephwright** [comment]
I think these are sufficiently specialised that we can close: I don't see this ever being a useful thing to do given the implementation work.
