### ISSUE TITLE
\cs_new:Nxn macro

### ISSUE THREAD

**Issue by sergey-s-betke** [latex3/latex3#300]
Please, add `\cs_new_nopar:Nxn` macro, analog for

    \use:NNx
      \cs_new_nopar:Npn \@@_if_eskdfont_auxi:w { ##1 \c_@@_mainfont_tl (##2) }
        { #1 }

Expected syntax:

    \cs_new_nopar:Nxn \@@_if_eskdfont_auxi:w { #1 \c_@@_mainfont_tl (#2) }
      { #1 }

Thank You!

**Comment by josephwright** [comment]
The team have thought carefully about variants and the mappings are clear: `c` is based on `N`, `x`, `v`, `V`, `o` and `f` are based on `n`, and `w`, `p` and `D` don't have variant mappings. As such, the rare case of needing to expand in the arg. spec. has to be done manually. BTW, we tend to favour
```
\use:x
  {
    \cs_new_nopar:Npn \exp_not:N \@@_if_eskdfont_auxi:w
       ##1 \exp_not:V \c_@@_mainfont_tl ( ##2 )
      {##1}
  }
```

**Comment by wspr** [comment]
Sergey, is this mechanism to parse the family names defined by fontspec? Perhaps I could offer more convenient tools for this in fontspec itself? Feel free to contact me separately (via fontspec GitHub repository perhaps best) if you have a specific application in mind.

**Comment by sergey-s-betke** [comment]
@wspr, yes, for my package https://github.com/Metrolog/Font.GOST2.304-81, based on fontforge and my font.

**Comment by sergey-s-betke** [comment]
@josephwright , Thank You for answer.

For source code:

    \cs_new_nopar:Nxn \@@_if_eskdfont_auxi:w { #1 \c_@@_mainfont_tl (#2) }
      { #1 }

Result:

    \cs_new_nopar:Npn \@@_if_eskdfont_auxi:w #1eskdfont(#2)
      { #1 }

I think, first syntax is easier to read than

\use:x
  {
    \cs_new_nopar:Npn \exp_not:N \@@_if_eskdfont_auxi:w
       ##1 \c_@@_mainfont_tl ( ##2 )
      {##1}
  }

Just IMHO.

**Comment by josephwright** [comment]
Perhaps, but `x` simply isn't related to `p`: most importantly, it should expand to a _braced_ result. Moreover, this is a _rare_ construct.

**Comment by sergey-s-betke** [comment]
ok...

**Comment by wspr** [comment]
Sergey, I think something like the following would probably suit you.
First define an “x unbraced” function for your needs:

    \cs_set_protected_nopar:Npn \@@_exp_last_unbraced:NNx { \::N \::x_unbraced \::: }

Then you should be able to write:

    \@@_exp_last_unbraced:NNx \cs_new_nopar:Npn \@@_if_eskdfont_auxi:w { #1 \c_@@_mainfont_tl (#2) }
  { #1 }

As Joseph mentions, it’s really the “unbraced” nature of the `p` argument that means we can’t define any pre-built variations for it using the standard expl3 syntax. For cases like this, something like the example above is the recommended approach.

I’d like to re-iterate, however, that if you’re parsing internal fontspec names there’s a chance that there’s an easier way we could be writing this code, even if I have to add some new functions to fontspec. You shouldn’t really be relying on the exact form of the family name that fontspec constructs in case I ever decide to change it `:)`

**Comment by blefloch** [comment]
In fact with Will's approach one still needs to double # in the
x-expanded argument.  This is unavoidable without quite some code.
