### ISSUE TITLE
\vcoffin_set:Nnw failed with package color in XeLaTeX

### ISSUE THREAD

**Issue by qinglee** [latex3/latex3#301]
MWE:

```TeX
% !TeX program  = XeLaTeX
\documentclass{article}
\usepackage{expl3} %% 2016/05/14 v6495
\usepackage{color}
\begin{document}

\ExplSyntaxOn
\group_begin:
\vcoffin_set:Nnw \l_tmpa_coffin { \linewidth }
\vcoffin_set_end:
\group_end:
\ExplSyntaxOff

\end{document}
```
And TeX complains:

```
! Missing } inserted.
<inserted text> 
                }
l.11 \group_end:
                
?
```

**Comment by josephwright** [comment]
I see the issue: a stray `\exp_not:N`. I'll fix today and send to CTAN: not sure if I'll make the TL'16 DVD or not!

**Comment by qinglee** [comment]
I also note that there is no `\color_ensure_current:` in `\vcoffin_set:Nnn` as documented. But it is still in `\vcoffin_set:Nnw`. It is some kinds of inconsistency. Is this intentional?

**Comment by josephwright** [comment]
That I'll need to check
