### ISSUE TITLE
Recursive tl_replace

### ISSUE THREAD

**Issue by wspr** [latex3/latex3#303]
See: http://tex.stackexchange.com/questions/311699/tl-replace-allnnn-recurse-subgroups

This seems to come up every now and then; it might be good to offer an official solution even if it's not a built-in part of expl3, or otherwise use this issue to have a statement explaining why it doesn't exist.

**Comment by FrankMittelbach** [comment]
Am 27.05.16 um 01:43 schrieb Will Robertson:
> See:
> http://tex.stackexchange.com/questions/311699/tl-replace-allnnn-recurse-subgroups
>
> This seems to come up every now and then; it might be good to offer an
> official solution even if it's not a built-in part of expl3, or
> otherwise use this issue to have a statement explaining why it doesn't
> exist.

guess this is something for Bruno to say if it is reasonably doable. I 
don't have much of an opinion there other than a suspicion that it is 
need when trying to solve something that isn't really meant to be solved 
in this way (within TeX). But I may be wrong.

**Comment by blefloch** [comment]
For the record (but with no short-term plan to do it), let me collect several different things broadly related to the question of replacements.

- We could add `\tl_replace_recursively:Nnn \l_tmpa_tl { search } { replace }` meaning "repeatedly apply `\tl_replace_all:Nnn` until the token list stops changing" (NB: it seems this leads to an infinite loop if and only if `search` appears in `replace` (and in the original text of course)).

- We could add `\tl_replace_case_once:Nn \l_tmpa_tl { { search1 } { replace1 } { search2 } { replace2 } .... }` meaning replace the first of these search results by the corresponding replacement, and similarly add `\tl_replace_case_all:Nn` and perhaps some `TF` versions.

- The question seems to request a `tl_replace` also acting within brace groups.  For this I would use regex replacements: there is even the possibility of searching for the contents of a certain token list variable.  I really don't think we should provide a specific command for simple replacement within groups.

Some things could be provided expandably.

- In `l3trial/l3kernel-extras` there is some code (probably not up to date) to define (non-expandably) some expandable functions that perform a given replacement.

- When working with strings it is possible to do comparisons (hence replacements) expandably.

**Comment by josephwright** [comment]
I have wondered if we should reconsider `\tl_replace_once:Nnn`/`\tl_replace_all:Nnn` here and go for `\tl_replace:Nnn` at 'outer level' only and `\tl_replace_all:Nnn` inside brace groups (or as you say could be recursive).

Not sure about expandable replacement: it's clever but is it generally useful ...

**Comment by blefloch** [comment]
I don't understand what you suggest.  It is hard to replace also in groups and for that use case I would point people to `l3regex` (I can try to speed-up the case of a regex that simply matches a single list of tokens rather than involving actual regex constructions).

**Comment by josephwright** [comment]
AS we are likely to make the regex code stable in the near future, I think we can close this one.
