### ISSUE TITLE
Infinite loop with tl_lower_case

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#306]
Doing

     \documentclass{article}
     \usepackage{amsmath,expl3}
     \ExplSyntaxOn\cs_set_eq:NN\lo\tl_lower_case:n\ExplSyntaxOff
     \begin{document}
     $\lo{\tilde{S}}$
     \end{document}

gives a `! TeX capacity exceeded, sorry [parameter stack size=10000].` error while replacing `\lo` by `\edef\foo` gives the usual `! Undefined control sequence.` which points to something being wrongly expanded.

I think it would make more sense for `\tl_lower_case:n` to either

- expand even undefined control sequences (right now they are considered not expandable and just put into the output)

- treat `\protect` and `\noexpand` specially and when encountering them automatically dump the next token in the output (with `\protect` resp. nothing in front of it).

I'm inclined towards the second option.  Do others disagree?

**Comment by wspr** [comment]
I guess the second option makes more sense “in the wild” since this code will no doubt interact with legacy 2e definitions. I’d be happy with that approach since there’s already code to deal with certain LICR inputs, right? I.e., it’s not just plain unicode text any more?

**Comment by FrankMittelbach** [comment]
Am 08.08.16 um 16:43 schrieb Will Robertson:
> I guess the second option makes more sense “in the wild” since this code
> will no doubt interact with legacy 2e definitions. I’d be happy with
> that approach since there’s already code to deal with certain LICR
> inputs, right? I.e., it’s not just plain unicode text any more?

agreed that it makes more sense to support the 2e legacy here (though it 
is a bit unclean from a theoretical point of view)

**Comment by blefloch** [comment]
So, I tried simply putting `\protect` in `\l_tl_case_change_exclude_tl` alongside `\cite`, `\label`, etc, but this is not taken into account.  In fact, the code only uses that tl for the case of non-protected macros.  This means for instance that
```
\tl_put_right:Nn \l_tl_case_change_exclude_tl { \NoChangeCase }
\cs_set_protected:Npn \NoChangeCase #1 { }
\tl_set:Nx \l_tmpa_tl { \tl_lower_case:n { \NoCaseChange { ABC } } }
```
gives `\NoCaseChange { abc }`.  I'll see if I can move the check of `\l_tl_case_change_exclude_tl` to before the code distinguishes between expandable and non-expandable tokens.

**Comment by blefloch** [comment]
Please ignore my last comment (deleted since).  I had typed `\protected` instead of `\protect` in my code, and in the example I gave I mixed up `\NoChangeCase` and `\NoCaseChange`.

Anyhow, Joseph's code is written in the right order and first tests for the special commands before distinguishing between expandable and non-expandable tokens.

**Comment by blefloch** [comment]
Fixed by revision 6650.  More precisely, one simply has to replace `\tilde` by `\protect\tilde` in my example above.
