### ISSUE TITLE
\ior_get_str:NN versus \ior_str_map_inline:Nn

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#308]
We have quite an unfortunate naming: `\ior_get_str:NN #1 #2` reads a line from the stream `#1` with `\etex_readline:D` and stores it into `#2` (without trailing end-line character).  Similarly, `\ior_str_map_inline:Nn #1 {#2}` runs the code `#2` for each line (read with `\etex_readline:D`, so a string) of the stream `#1`.  I see two reasonable renamings:
- `\ior_get_str:NN` and `\ior_map_inline_str:Nn`
- `\ior_str_get:NN` and `\ior_str_map_inline:Nn`

I have a very slight preference for the second, but am really not sure.  Opinions?  Provide both?

**Comment by wspr** [comment]
Good catch. I also prefer the latter!

**Comment by josephwright** [comment]
Fine for a tidy up here: second option fine with me.

**Comment by FrankMittelbach** [comment]
Am 21.08.16 um 22:03 schrieb Joseph Wright:
> Fine for a tidy up here: second option fine with me.

second looks fine
