### ISSUE TITLE
Provide \c_max_char_int

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#309]
It would be nice to have `\c_max_char_int` (255 for pdfTeX, 1114111 for LuaTeX/XeTeX, ? for pTeX/upTeX).  At the moment I've been providing it in the experimental package `l3str-convert`, but that doesn't seem like the right place.

**Comment by FrankMittelbach** [comment]
Am 19.08.16 um 22:53 schrieb Bruno Le Floch:
> It would be nice to have |\c_max_char_int| (255 for pdfTeX, 1114111 for
> LuaTeX/XeTeX, ? for pTeX/upTeX). At the moment I've been providing it in
> the experimental package |l3str-convert|, but that doesn't seem like the
> right place.

I think a constant like that would be sensible, perhaps in l3str?

**Comment by josephwright** [comment]
I'd add to `l3int` myself.

**Comment by blefloch** [comment]
I just ran a quick test to see which character codes are allowed in each of the 5 engines.  I tried both `\lccode` and `\catcode`.   Namely, for which values `\catcode`*`value`* or `\lccode`*`value`* can be set.  In hexadecimal,

- pdfTeX: 0-FF
- XeTeX: 0-10FFFF
- LuaTeX: 0-10FFFF
- epTeX: 0-FF and (any multiple of 2^16 plus) XXYY with XX in (A1-FE) and YY in (A1-FE)
- eupTeX: 0-FFFF and (any multiple of 2^16 plus) 0100-FFFF

Since I do not know of any English-language documentation of (e)(u)pTeX I am not sure that I am testing the right thing.  At least the epTeX results match [some code I found](http://get-software.net/language/japanese/ptex/kanji.c), I did not track down the eupTeX code.

Ah, I just ran a slightly different test that checks possible values of `\lccode0` and it seems that's bounded in 0..255.

The question is then what values to use for `\c_max_char_int` in epTeX and eupTeX.  For epTeX, 255 seems most reasonable but for upTeX both 255 and 65535 are reasonable.

Humpf, there's also a bug in upTeX: when `\lccode` receives an invalid char code first argument it's silently turned to 0, so  `\lccode65536=1234\showthe\lccode0` gives 1234.

**Comment by aminophen** [comment]
Thanks for your report at texjporg/uptex-base#1. (actually this repo is intended only for plain TeX macro, but i think it's open for the upTeX engine itself. But... few people are watching the repo, so i should forward the issue to someone)

> Since I do not know of any English-language documentation of (e)(u)pTeX I am not sure that I am testing the right thing.

Sorry about that... english documentation is not started at all. Maybe @h-kitagawa can answer the question more precisely. Or, if you look for the latest sources of (e-)(u)pTeX, see [texlive svn](http://tug.org/svn/texlive/trunk/Build/source/texk/web2c/).

**Comment by blefloch** [comment]
Thanks for the speedy bugfix.  Just to recapitulate here the situation with (e-)(u)pTeX since [revision 41998 on the texlive svn](http://www.tug.org/svn/texlive?view=revision&revision=41998): now `\lccode` and related primitives only allow a first argument in [0,255] rather than allowing a larger range and actually truncating.  My tests were not being careful enough.  Anyways, this means the max char code should be 255.
