### ISSUE TITLE
Use new LuaTeX primitive \lastnamedcs

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#313]
We could use the new LuaTeX primitive `\lastnamedcs` (when available) in `\cs_if_exist_use:cTF` and related functions.

**Comment by josephwright** [comment]
This one is down as being pretty 'risky': you _have_ to know the exact construct entirely for it to be safe. I can see that we should be OK but I'm extremely wary here.

**Comment by blefloch** [comment]
I'm pretty confident that it is safe (e.g. it works with nested csnames, see below), and I think it would actually gain quite a bit of speed since it avoids expanding tokens more than once.  I remember a few times when I struggled to expand all function calls before passing the result to `\cs_if_exist_use:cTF`, to avoid calling functions twice.

    % with LuaTeX
    \tracingall
    \ifcsname
            \csname empty\endcsname
            space%
            \lastnamedcs % => \empty
    \endcsname
      \empty
      \lastnamedcs % => \space
    \fi
