### ISSUE TITLE
Use new LuaTeX primitive \suppressoutererror

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#314]
Since we do not support `\outer` commands it might make sense to run LuaTeX's `\suppressoutererror`, but I'm not so sure.

**Comment by josephwright** [comment]
Not really helpful I suspect, at least at present. The idea of the primitive is that it will disable the `\outer` check, but unless the code is LuaTeX-only that is not all that useful. Of course, if one imagines longer-term going LuaTeX-only then there is a point as we disable the primitive and make it a no-op.

**Comment by blefloch** [comment]
I agree LuaTeX only makes this useless as long as we support other engines.

Just a thought: simply `\let\outer\empty` would work just as well in a format.

**Comment by FrankMittelbach** [comment]
Am 01.09.16 um 18:11 schrieb Bruno Le Floch:
> I agree LuaTeX only makes this useless as long as we support other engines.
>
> Just a thought: simply |\let\outer\empty| would work just as well in a
> format.

if you want to get rid of outer (which is a good thing :-), but I  guess 
this is a different semantics to that \suppressoutererror. Without 
having checked my expectation is that this allows you to conditionally 
allow outer macros in non-outer context so smething you can toggle on 
and off ... not that I would want that :-)
