### ISSUE TITLE
Other new LuaTeX primitives

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#315]
In the same TUGboat article are mentioned:
- `\nohrule` and `\novrule`, which have the same syntax as rules and produce an empty box;
- `\nospaces` which (locally) suppresses spaces completely (i.e., `\spaceskip` etc are ignored) or makes them be `0pt` skips;
- `\toksapp`, `\tokspre`, `\etoksapp`, `\etokspre` which append/prepend material to toks registers (but I am a bit confused by examples of how this interacts with grouping) with or without expansion;
- `\hpack`, `\vpack`, `\tpack` which do like `\hbox`, `\vbox`, `\vtop` but without running some LuaTeX hooks and without messing with hyphenation and the like;
- `\suppresslongerror`, `\suppressmathparerror`, `\suppressifcsnameerror` which suppress various errors.

I think none of these primitives are our concern for now, but I'd prefer if someone else can take a look then close this issue.

**Comment by josephwright** [comment]
I looked at several of these in my latest experiments, in particular the toks business. Some of these are likely useful for LuaTeX-specific code, but unless one goes LuaTeX-only that's not going to show.
