### ISSUE TITLE
Deprecate \c_minus_one in favor of -\c_one

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#316]
Contrarily to other integer constants provided out of the box, `\c_minus_one` (a copy of `\m@ne`) can be assigned y accident: `\c_minus_one junk` sets it to zero and wreaks havoc in all subsequent code.  This leads to very [confusing errors](http://tex.stackexchange.com/questions/328412/) which suggest that using `\c_minus_one` should be avoided where possible... perhaps deprecated.  In most places `\c_minus_one` could be replaced by `-\c_one` (which has the same termination behaviour) or `-1`.  In the remaining places it might make sense to use a private constant equal to minus one.

**Comment by josephwright** [comment]
As you might remember, I think we should significantly cut down integer constant use: most of the time it's not really needed, and where it is we probably should use something internal. So I'd be happy to go to `-1`/`\c__int_minus_one_int` or similar.

**Comment by blefloch** [comment]
Concrete example of silent bad behaviour: if one mistakenly provides a `tl` instead of an `int` variable to `\int_decr:N`, `\c_minus_one` gets assigned (fixed in upcoming commit).

    \int_decr:N \l_tmpa_tl
    \int_set:Nn \l_tmpb_tl { 10 }
    \int_show:N \c_minus_one % => 9
