### ISSUE TITLE
hyperref aware latex3

### ISSUE THREAD

**Issue by bastien-roucaries** [latex3/latex3#321]
It is a pain to support hyper reference in latex2e.

I am maintaining footmisx and I plan to approach the xfootnote template, but I will like to see hook for supporting hyperref.

I do not care if we use hyperref package but I will like to have latex3 hyperref not to be a hack.

This is more for discussion but it need to be better than now.

A generic solution is better based on hook

Bastien

**Comment by bastien-roucaries** [comment]
Another example in footnote context. mkfnmark is both used to type set a target and an anchor. Latex3 should offer different command for anchor and target (that are in case of no hyperref aliased to a raw version that produce the same result)

**Comment by bastien-roucaries** [comment]
Please note also that star command should be clarified. For instance ref* means no hyperref whereas footmark* (xfootnote package) means use a counter

**Comment by josephwright** [comment]
Note that decisions about user interfaces for a future format are not yet made. It's likely one form will be  similar to LaTeX2e, though some change may happen. In particular the `*` form doesn't have any general meaning: it's simply 'a variant on the parent'.

**Comment by josephwright** [comment]
I think this is covered by ongoing integration of `hyperref` concepts into `expl3` and thus the LaTeX2e format. @u-fischer where do you  feel this one 'lives'?

**Comment by u-fischer** [comment]
Well as I wrote I think some weeks ago, the main problem is that currently there is only a rather week connection between a mark and the footnote, at least if \footnotemark/\footnotetext is used. Beside this there is the problem that a footnote can refer to more than one mark, so backreferencing from the footnote is not trivial. Imho this problems must be resolve in latex2e.

**Comment by FrankMittelbach** [comment]
Guess, it belongs more specifically to task 2.2.2 of the WTPDF project and needs handling there.

**Comment by josephwright** [comment]
I think this issue is too broad to be likely to be 'addressed' in a meaningful way, although the wider PDF project is in this area. So closing but only as there's low probability of being able to 'fix' in the current form,
