### ISSUE TITLE
l3docstrip disable comment

### ISSUE THREAD

**Issue by bastien-roucaries** [latex3/latex3#323]
sometime I want to type `\@@par` that is replaced by some code.

I could workarround using `\cs_set_eq:cc {@@_par} {@ @ par}` but it is ugly

At least it should be documented in documentation

```
% Enable lt3docstrip stripping
%    \begin{macrocode}
%<@@=footmisx>
```

**Comment by josephwright** [comment]
In general using `\@@par` should be very rare in `expl3` code, and even in LaTeX2e work. I agree that documentation here would be useful, though perhaps we might have a 'disable' mode for replacement.

**Comment by wspr** [comment]
I believe (but haven’t tested) that writing

    %<@@=>
…
    %<@@=original>

(where “original” is whatever current package name you’re using) will temporarily disable the replacements.

**Comment by blefloch** [comment]
What Will says is correct (unless my implementation is buggy).

**Comment by bastien-roucaries** [comment]
No it fail

**Comment by wspr** [comment]
Did your reply get cut off? More details would be good.

**Comment by blefloch** [comment]
Most likely meant that %<@@=> fails.  That means there is a bug in l3doc.

**Comment by josephwright** [comment]
Handled by solving #328 in checkin 7ffb6fbc8.
