### ISSUE TITLE
Providing \IfNoValueOrEmptyTF in xparse

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#327]
I've seen it defined in a package using `xparse`.  It was used when defining a command with two optional arguments: to specify the second optional argument without the first, the user can leave the first empty.

Should we provide this?

**Comment by josephwright** [comment]
If someone wants to have an empty value they can simply use `O{}` to get the same behaviour as LaTeX2e. Moreover, using two optionals net to one another isn't necessarily an interface we want to encourage being used in new document commands. There's a strong reason to feel that in most situations using keyval arguments is the best plan. I'd really rather not add this!

**Comment by FrankMittelbach** [comment]
Am 04.01.17 um 09:40 schrieb Joseph Wright:
> If someone wants to have an empty value they can simply use |O{}| to get
> the same behaviour as LaTeX2e. Moreover, using two optionals net to one
> another isn't necessarily an interface we want to encourage being used
> in new document commands. There's a strong reason to feel that in most
> situations using keyval arguments is the best plan. I'd really rather
> not add this!

I read this differently Joseph. This wants to make

    \foo{bar}
    \foo[]{bar}

with the meaning that an empty value is the same as providing none. That 
is not what you get from |O{}| as that make []| a value not a non-value, 
or not?

I would add it if it is used in several packages. I see its usefulness 
but it is probably not needed that often to warrant a core definition.

**Comment by josephwright** [comment]
On 04/01/2017 11:12, Frank Mittelbach wrote:
> I read this differently Joseph. This wants to make
> 
>     \foo{bar}
>     \foo[]{bar}
> 
> with the meaning that an empty value is the same as providing none. That 
> is not what you get from |O{}| as that make []| a value not a non-value, 
> or not?

My point was that if you do

    \DeclareDocumentCommand\foo{ O{} m }{%
      \IfEmptyTF{#1} % Hypothetical at present
        {Stuff}
        {Other stuff}%
    }

then you don't need to think about `\NoValue` at all: it can never pop up.

My issue with the above is that the entire point of having a `\NoValue`
test is for cases where you need to 'do something different' if the
value was not present at all. In the above, the most likely is passing
to a keyval set up, which doesn't need the test at all

    \DeclareDocumentCommand \foo { O{} m }
      {
        \keys_set:nn { foo } {#1}
      }

For cases like current LaTeX syntax for box constructs (a marker token)
you again don't need to test as you put the standard value as `O{...}`.

I guess I want to see some use cases!

**Comment by FrankMittelbach** [comment]
Am 04.01.17 um 12:23 schrieb Joseph Wright:
>
> My point was that if you do
>
> \DeclareDocumentCommand\foo{ O{} m }{%
> \IfEmptyTF{#1} % Hypothetical at present
> {Stuff}
> {Other stuff}%
> }
>
> then you don't need to think about `\NoValue` at all: it can never pop up.

you're right as usual ... ok forget it. That does the same and about the 
same amount of tokens (more or less)

**Comment by josephwright** [comment]
On 04/01/2017 11:28, Frank Mittelbach wrote:
> Am 04.01.17 um 12:23 schrieb Joseph Wright:
>>
>> My point was that if you do
>>
>> \DeclareDocumentCommand\foo{ O{} m }{%
>> \IfEmptyTF{#1} % Hypothetical at present
>> {Stuff}
>> {Other stuff}%
>> }
>>
>> then you don't need to think about `\NoValue` at all: it can never pop up.
> 
> you're right as usual ... ok forget it. That does the same and about the 
> same amount of tokens (more or less)

Well the `\IfEmpty` business has come up several times and might well be worth adding: at present you have to use code-level `\tl_if_blank:n(TF)`.

**Comment by FrankMittelbach** [comment]
Am 04.01.17 um 12:30 schrieb Joseph Wright:
> Well the |\IfEmpty| business has come up several times and might well be
> worth adding: at present you have to use code-level |\tl_if_blank:n(TF)|.

oh. the word hypothetical didn't register (I thought you meant the whole 
code).

If \IfEmptyTF doesn't exist then I'm not sure what is better to provide.

For this use case \IfNoValueOrEmptyTF and \IfEmptyTF are more or less 
equiv (except that you write |o| in one case and |O{}| in the other.

\IfEmptyTF is more general so you could use it for different purposes, 
but I really don't want to see xparse providing general code logic. In 
my view it should parse the arguments and then call an internal command 
that does the rest and not a lot of stuff and offering generic logical 
commands goes in a different direction whereas \IfVoValueOrEmptyTF is 
clearly tied to arg processing.

So if it is either or to provide I would go with \IfVoValueOrEmptyTF I 
think ... but then I don't know your use cases for \IfEmptyTF

**Comment by blefloch** [comment]
Sorry for lack of time this week.  The package is sidenotes if anyone wants to take a look (it mixes layers in several respects).  I agree it could be using a hypothetical `\IfEmptyTF`.

    \NewDocumentCommand \sidenotetext { o o +m }
      {
        \IfNoValueOrEmptyTF{#1}
          {
            \@sidenotes@placemarginal{#2}{\textsuperscript{\thesidenote}{}~#3}
            \refstepcounter{sidenote}
          }
          {\@sidenotes@placemarginal{#2}{\textsuperscript{#1}~#3}}
      }

**Comment by josephwright** [comment]
In the end, we can worry about `\IfNoValueOrEmptyTF` _vs_ `\IfEmptyTF` if we feel that supporting the basic idea is appropriate. So my question is 'How do we feel about 'chained' optional arguments?'. They are of course used by LaTeX2e but one might well argue that a more 'rigid' (keyval) syntax is the way to go with new stuff: certainly that makes it easier to extend commands, _etc._ On the other hand, our coffin experiments do suggest that positional arguments still have a place (!).

**Comment by wspr** [comment]
I don’t have a strong opinion either way whether it should be `IfEmpty` or `IfBlank`… I would probably lean towards `IfBlank` and argue that when writing `\foo[][ ]{x}` (“empty”, “blank”, “x”) it’s probably more likely that the blank case is rarely needed to be differentiated from the empty case.

**Comment by josephwright** [comment]
As we've decided [elsewhere](https://github.com/latex3/latexbug/blob/master/latexbug.dtx) that `etoolbox` is more-or-less 'trusted', we could simply point to `\ifblank` for the use case outlined. (The current definition of `\ifblank` _is_ `\tl_if_blank:nTF` as I back-ported the code.)

**Comment by wspr** [comment]
Good point — I’d be okay with that.

**Comment by blefloch** [comment]
Issue resolved:
- if one wants to treat `-NoValue-` the same as empty just replace `o`-type arguments by `O{}`
- to test for emptyness without resorting to `expl3`, use `\ifempty` or `\ifblank` from `etoolbox`

**Comment by josephwright** [comment]
@blefloch  Do we want to document that anywhere?
