### ISSUE TITLE
l3docstrip: use @@@@ when you need @@?

### ISSUE THREAD

**Issue by wspr** [latex3/latex3#328]
Coming back to `unicode-math` after quite some time, I discovered this at the top of my dtx file:

```
\input l3docstrip.tex
\begingroup
  \catcode`\_ = 12 %
  \long\gdef\prepareActiveModule#1{%
    \if\relax#1\relax
       \let\replaceModuleInLine\empty
    \else
      \def\replaceModuleInLine{%
        \replaceAllIn\inLine{@@@@}{!!!!!FOURAT!!!!!}%
        \replaceAllIn\inLine{__@@}{__#1}%
        \replaceAllIn\inLine{_@@}{__#1}%
        \replaceAllIn\inLine{@@}{__#1}%
        \replaceAllIn\inLine{!!!!!FOURAT!!!!!}{@@}% i.e., use @@@@ when you need literal @@ in code
      }%
    \fi
  }
\endgroup
```

I suspect that I needed to do this when interfacing with a fair bit of 2e code… in some ways I think it's nicer than turning the @@ replacement on and off again. On the other hand, for pure expl3 code it should never be needed.

Any thoughts one way or another whether it would be good to add to l3docstrip?

**Comment by blefloch** [comment]
Quite reasonable I would say.

**Comment by FrankMittelbach** [comment]
Am 25.01.17 um 16:24 schrieb Bruno Le Floch:
> Quite reasonable I would say.

agreed, much better than turning prefixing on and off in the 2e context
