### ISSUE TITLE
Detect +t ("long" single-token) in xparse

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#329]
Currently xparse accepts `\DeclareDocumentCommand{\foo}{+t*}{...}`, and it behaves identically to a signature `t*`.  More precisely some internal command that has no argument ends up being defined to be long or not.

Should we detect that case?

**Comment by FrankMittelbach** [comment]
Am 06.02.17 um 22:39 schrieb Bruno Le Floch:
> Currently xparse accepts |\DeclareDocumentCommand{\foo}{+t*}{...}|, and
> it behaves identically to a signature |t*|. More precisely some internal
> command that has no argument ends up being defined to be long or not.
>
> Should we detect that case?

it is top-level code, ie it will be executed only once, so even if it 
does cost a "little" that wouldn't hurt and from an interface 
perspective one can argue that detecting that case is a good thing.

On the other hand it is minor and having a non-argument cs being long 
isn't doing any harm so if it requires noticeably more or more complex 
code then I would say, leave it as is

frank

**Comment by josephwright** [comment]
I left `+t` alone as one might at least imagine `+t\par`: if we trap it we have to allow for the latter. I guess the  biggest impact is in the expandable case where we do grab an argument. Probably as @FrankMittelbach says it is just about worth picking this up as there is no real need for the `+`. Perhaps do that with some non-critical info in the log (just `info`?).

**Comment by blefloch** [comment]
Trickier:

    \DeclareExpandableDocumentCommand{\foo}{+m +m s +m}{}

leads to an error (`s` should be `+s`) even though arguably it should be allowed.

**Comment by blefloch** [comment]
It turns out we don't grab an argument using the t-type's auxiliary even in the expandable case: instead we simply use a generic auxiliary shared by all arguments of the function.  Anyways, I've fixed things in my next commit by making t/s transparent to longness.
