### ISSUE TITLE
Make xparse commands context-aware (pdf bookmarks etc)

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#333]
(Despite having had a few internal discussions on that we surprisingly never opened an issue.)

For pdf bookmarks, toc, math/text mode etc. we need xparse commands to give different outcomes (but keep the same signature).  What syntax should we use?  How general should the concept be?

**Comment by wspr** [comment]
(Just to reiterate some comments left previously…)

In terms of structure only, but not naming, I think (?) we’re converging on something like

    \DeclareDocumentCommand \command {sig} {def}  % <- default for global definition for all contexts remains the same as current interface 
    \DeclareContextCommand \command {context} {def}  % <- if \DeclareDocumentCommand already given

And

    \DeclareCommandSignature \command {sig}
    \DeclareContextCommand \command {context} {def}  % <- if \DeclareDocumentCommand not given

Here `\command` would only be valid in the given context(s), whereas in the first case `\command` would have a “normal” definition but that would be overloaded in the given context(s).

Now, I’m fairly keen on the idea of adding keyval somewhere in here. Whether we’re talking…

    \DeclareContextCommand \command {thiscontext,key=val,key=val} {def}

…or…

    \DeclareContextCommand \command {context=thiscontext,key=val,key=val} {def}

…or just…

    \DeclareContextCommand \command {thiscontext} [key=val,key=val] {def}

…I’m not sure!

**Comment by josephwright** [comment]
Closing here as this code has all moved to LaTeX2e, and a different structure of discussion would be needed there.
