### ISSUE TITLE
l3doc should allow both y/m/d and y-m-d date formats

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#335]
Currently, the values of keys such as `deprecated` or `added` for the `macro` or `variable` or `function` environments must be dates in a format such as `2017-02-09`.  It would be better to allow, or at least detect, `2017/02/09`, and probably also allow leading `0` to be omitted.

**Comment by blefloch** [comment]
To force consistency in source files I've gone for the easier route of detecting `/` and issuing an error saying the format should be `YYYY-MM-DD`.  Commit upcoming.

**Comment by davidcarlisle** [comment]
I'd be tempted to allow the - form in package dates (even perhaps in the
core 2e code), It's harder to justify a latex-specific date format these
days.

**Comment by FrankMittelbach** [comment]
Am 12.02.17 um 17:04 schrieb David Carlisle:
> I'd be tempted to allow the - form in package dates (even perhaps in the
> core 2e code), It's harder to justify a latex-specific date format these
> days.


allowing the iso date there too is probably sensible -- unfortunately we 
can't get rid of the old form so it would mean supporting both
