### ISSUE TITLE
Move l3flag to l3kernel, use it in l3fp-traps

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#336]
The experimental package `l3experimental/l3str/l3flags` defines a variable type holding non-negative integers, that can be incremented expandably.  A very similar kind of variables is used internally in `l3fp-traps`.  It would be nice to reduce duplication and simply provide `l3flag` in `l3kernel`.

**Comment by blefloch** [comment]
It would actually be reasonably possible to allow flags to be decremented expandably too (both increments and decrements are in steps of 1 only).

**Comment by josephwright** [comment]
This is all internal code, right? Don't see a problem ...

**Comment by blefloch** [comment]
Well, I think the commands `\flag_new:n`, `\flag_raise:n` etc could be provided to users.  The use cases are quite specific and I'd need to write some words on it, but it's not much more arcane than quarks for instance.

**Comment by FrankMittelbach** [comment]
Am 12.02.2017 um 20:49 schrieb Bruno Le Floch:
> Well, I think the commands |\flag_new:n|, |\flag_raise:n| etc could be
> provided to users. The use cases are quite specific and I'd need to
> write some words on it, but it's not much more arcane than quarks for
> instance.

are those going to be local only (probably if they are supposed to be 
raised in an expandable way)?

I think I can see a number of good use cases, so a standard interface is 
probably a good idea, though whether or not the non-internal  side is 
day one part of the kernel is  perhaps another matter

frank

**Comment by blefloch** [comment]
The package is tiny (ten functions or so) and all of its commands are public, so I'd rather not do the work of renaming all of its commands to internal names for now and later renaming them back everywhere.

**Comment by wspr** [comment]
+1 for adding these commands alongside quarks in expl3.

**Comment by FrankMittelbach** [comment]
Am 13.02.17 um 02:56 schrieb Bruno Le Floch:
> The package is tiny (ten functions or so) and all of its commands are
> public, so I'd rather not do the work of renaming all of its commands to
> internal names for now and later renaming them back everywhere.

guess you are right, especially as there aren't any manipulations other 
than raising or lowering a flag, so what's the proposed syntax beside _new ?

**Comment by josephwright** [comment]
Looks like we are good-to-go here: @blefloch  will you do or should I?

**Comment by blefloch** [comment]
In my last commit I rename `\flag_clear:n` to `\flag_zero:n` and `\flag_height:n` to `\flag_use:n` to make them be closer to names of `int` functions.  It could make sense to rename `\flag_raise:n` to `\flag_incr:n` because that's what it does; however that function is expandable while its `int` analogue `\int_incr:N` is not.  Thus for now I keep `\flag_raise:n`.

**Comment by blefloch** [comment]
Question: should the recommended naming of flags be things like `fp_invalid_operation` (like parts of usual variables) or should it be `fp/invalid-operation` like messages and keys?

**Comment by wspr** [comment]
Flip a coin :) I’d say like usual variables, I think. Keys and messages have slashes partially because they can be subdivided/referred to in groups… flags don’t really fit that idea.

**Comment by blefloch** [comment]
Thanks, so the only remaining questions are:
- rename `\fp_raise:n` to `\fp_incr:n`?  (I'm against)
- rename `\fp_if_raised:nTF` to `\fp_if_zero:nTF` (I hesitate)

**Comment by wspr** [comment]
I assume you mean "flag" not "fp". I really like the conceit of "raising a flag", so my vote would be to stick to that terminology. I wouldn't even mind both \flag_if_raised AND \flag_if_zero if that makes sense for any reason. (And I assume \flag_if_lowered is a step too far!!)

**Comment by josephwright** [comment]
We have to step outside the 'normal' names somewhere as the entire point here is to be expandable. 'raise' seems fine to me but perhaps that means 'zero' is a bit odd. 

On the slashes business, flags are addressed as other variables not like keys, so I'd go with `_`.

**Comment by FrankMittelbach** [comment]
Am 14.02.2017 um 09:14 schrieb Joseph Wright:
> We have to step outside the 'normal' names somewhere as the entire point
> here is to be expandable. 'raise' seems fine to me but perhaps that
> means 'zero' is a bit odd.

also think that raise is fine, given that this is rather a special type. 
Don't like _zero much (even as you say the height is zeroed).

I first thought _lowered but that doesn't remakes it clear that it is 
reset/cleared.  maybe  _grounded

guess the nautical verb would be to slack, but I guess that is kind of 
odd :-)

or _clear after all

**Comment by josephwright** [comment]
I thought 'reset' but as we use 'clear' for other variables in which 'zero' is inappropriate then probably is best.

**Comment by blefloch** [comment]
Ok, I've gone back to `_clear`, to limit the number of verbs.

Then the question is should I revert `\flag_use:n` to `\flag_height:n` to continue the analogy with raising?
