### ISSUE TITLE
Give better way to determine if deprecated commands are used

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#337]
Right now deprecated commands are announced as deprecated and then some time later dropped.  At no point there is a warning when compiling documents, so package authors who use `expl3` but don't follow the mailing list may miss such deprecations and have to revise their packages quickly once the command is actually removed.

Suggestion: provide an option in `expl3` to make all deprecated commands `\outer`, so that a package that uses them simply won't load.  This won't catch cases where the deprecated command was only accessed in the package using `c`-expansion, but that should be pretty rare I suppose.

**Comment by blefloch** [comment]
Note that the code could be pretty simple: at the end of `expl3`

    \tl_map_inline:nn
      {
        \clist_length:N
        \clist_length:c % it is important to include variants
        % ...
      }
      { \tex_outer:D \tex_def:D #1 { \DEPRECATED } }

with some nicer (expandable) error message.  No need to worry about making protected commands protected: if they are going to be expanded then either they will give an error due to `\outer` or due to the expandable error message.

**Comment by josephwright** [comment]
Reasonable idea but I suspect final removals will still come down to me checking over TeX Live and sending people emails!

**Comment by wspr** [comment]
I agree it's a good idea since it provides more info to the confused end-user who has somehow stumbled across the situation. 

In terms of catching problems earlier, would a \typeout solution (non-expandable commands only) make sense? I can definitely imagine people emailing me to inform me that they're getting some new warning when loading fontspec after updating expl3.

**Comment by blefloch** [comment]
In the commits listed above I've implemented `l3deprecation` (in `l3trial`) which makes all previously deprecated command `\outer` and makes them produce an error message, and which provides `\deprecation_error:` to make all functions marked for future deletion do the same.  Where should we put `l3deprecation`?

**Comment by wspr** [comment]
On 17 Feb 2017, at 6:22 am, Bruno Le Floch <notifications@github.com> wrote:
> 
> In the commits listed above I've implemented l3deprecation (in l3trial) which makes all previously deprecated command \outer and makes them produce an error message, and which provides \deprecation_error: to make all functions marked for future deletion do the same. Where should we put l3deprecation?

Makes sense to me to add it to expl3 and have it loaded by default… little overhead really.

Cheers,
Will

**Comment by blefloch** [comment]
You should know there is a surprisingly large number of deprecated
commands.  Maybe we want to ignore those deleted as part of the Big Bang
in 2011?  That would divide by at least 2 the number.

**Comment by wspr** [comment]
I guess the rough feeling for the numbers didn’t include variants. What about multiple deprecation packages? Or just modules within the package? One for pre-bang, one for post- (and another one day if there’s another “bang” :)).

**Comment by blefloch** [comment]
300 in 2011
4 in 2012
99 in 2013
72 in 2014
9 in 2015
8 in 2016
14 in 2017

**Comment by davidcarlisle** [comment]
just make it an error for (say) two years then drop it essentially freeing
the names?

David

**Comment by FrankMittelbach** [comment]
Am 17.02.17 um 00:53 schrieb David Carlisle:
> just make it an error for (say) two years then drop it essentially freeing
> the names?

guess that should be fully sufficient, but the numbers are down, so the 
above would mean ignore old ones from before 2015 and then we are down 
to a few dozen anyway and could let them stay in (at least for a couple 
more years)

**Comment by josephwright** [comment]
@blefloch The log of officially-deprecated functions only goes back to when things got 'broadly' stable: there were a lot more before that :)

We've been reasonable 'aggressive'  removing names, though even that is on a couple-of-years cycle. We could of course not remove stuff (except in the cases where we actually directly alter semantics), but in the main it seems to work reasonably well. I'm happy if we want to extend the period with a warning given after two years and removal later: what I don't feel we want is to wait long but with no clear  warning.
