### ISSUE TITLE
xparse's document commands used in math su(p|b)scripts with no brace give error

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#338]
Document commands containing math symbol and then used in math su(p|b)scripts are:

- okay if created with the usual `\newcommand`,
- not okay if created with `xparse`'s `\NewDocumentCommand` and the like.

In the latter case, the compilation fails with the error:
```
? 
! Missing { inserted.
<to be read again> 
                   \tex_let:D
```
This is pointed out by the following MCE where the error appears if `\newcommand{\mypm}{\pm}` is removed.
```latex
\RequirePackage{latexbug}

\documentclass{article}
\usepackage{xparse}
%
\newcommand{\mypm}{\pm}
\ProvideDocumentCommand \mypm {} {\pm}
%
\begin{document}
$_\mypm$
\end{document}
```

**Comment by josephwright** [comment]
There are a combination of factors here. First, you are using the primitive `_` syntax which carries out expansion rather than taking an argument. That's never been officially supported, and indeed
```latex
$_{\mypm}$
```
will work fine.

That's showing up as we altered how commands with no args (and all-`m` args) were implemented. In almost all cases that makes no odds as they are `\protected`, but it shows up

- Inside `\csname`
- After primitive `_`/`^`

as these carry out expansion but don't 'respect' `\protected`. We've reverted the change for other reasons  but are still working out an 'official' position here.

**Comment by davidcarlisle** [comment]
It's probably worth noting that in general it's never been the case that
commands defined using \newcomamd work after _

\documentclass{article}
%\newcommand{\mypm}{abc}
%\begin{document}$_\mypm$\end{document}

generates no error but only subscripts  a not abc

(That is the cause of the error here, as you are just subscripting the
first token of an internal definition,
although as Joseph says this is reverted in the current sources)

**Comment by dbitouze** [comment]
Thanks for your insights.

BTW, I stumbled upon this error when I recompiled an old document which used to compile like a charm.
And I'm not sure to understand: will you restore the old behavior?

**Comment by blefloch** [comment]
In the latest development versions (soon on CTAN I suppose) the code you give works as it used to.  We are not sure if long-term that is the best plan: the fact that your code used to work was accidental (but quite natural, as a user, I would say).

I would push for making `_` and `^` active and grabbing an argument, but I have seen colleagues use `_\text{abc}` quite often, which would break if `_` was made to take an argument.  We could make `xparse` do some magic to detect such cases without braces where the argument (a single token) is a command with further arguments.

**Comment by dbitouze** [comment]
>In the latest development versions (soon on CTAN I suppose) the code you give works as it used to.

Okay. Before asking, I had a look at the last commits but was as puzzled as before looking at them :)

> `_\text{abc}` [...] would break [...]

Please, don't! :$

**Comment by blefloch** [comment]
> > |_\text{abc}| [...] would break [...]
> 
> Please, don't! :$

That was exactly my reaction when seeing this horrible abuse of
`\text`... I suppose we disagree then: you seem to want us to somehow
make it work even though it was never meant to work.

You can't hope to have it both ways.  Either `_`*token* always works,
and for this `_` needs to take an argument like a macro, or things like
`_\mathcal{A}` work, and for that you need `_` to have the primitive
syntax and to expand `\mathcal` (or `\text` in my previous example).

**Comment by dbitouze** [comment]
> I suppose we disagree then: you seem to want us to somehow make it work even though it was never meant to work.

Old habits die hard. Maybe you're right...

**Comment by onstrees** [comment]
I think (I am too new to LaTeX to be sure) that this issue is similar to an issue I reported on the sidenotes package: [sidenotes seems to have stopped working with new xparse #41](https://github.com/andythomas/TeX-sidenotes/issues/41)

**Comment by josephwright** [comment]
This was fixed a while ago.
