### ISSUE TITLE
Extract items from a token list

### ISSUE THREAD

**Issue by eg9** [latex3/latex3#339]
Proposed syntax

    \tl_set_extract:Nnnn

1. token list variable to set
2. start from
3. end with
4. token list

Examples

    \tl_set_extract:Nnnn \l_tmpa_tl {2}{4} {ab{cd}efg}
    \tl_set_extract:Nnnn \l_tmpa_tl {3}{} {ab{cd}efg}

should set `\l_tmpa_tl` respectively to `b{cd}e` and to `{cd}efg`. With negative numbers,

    \tl_set_extract:Nnnn \l_tmpa_tl {}{-2} {ab{cd}efg}

should set `\l_tmpa_tl` to `ab{cd}ef`. So an empty second argument should be interpreted as “minus infinity” and an empty third argument should be “infinity”.

This is different from what can be achieved with `l3regex`, because it deals with items in a token list.

**Comment by blefloch** [comment]
If braces don't have to be preserved it would be reasonable to provide the expandable `\tl_range:nnn` generalizing `\tl_item:nn`.

**Comment by eg9** [comment]
@blefloch I think that for the applications I have in mind this could be enough; expandability would indeed be a bonus.
