### ISSUE TITLE
Write tests for documented internal commands

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#341]
Some commands have a well-defined interface despite being for use inside the `l3kernel` bundle only.  They should have unit tests too, as changing the commands can affect code far from the change.

**Comment by josephwright** [comment]
Most of these are very low-level, and will get caught by the existing tests I'd expect. I'd say this is likely to be extremely hard to do, and probably not a good use of resources ...

**Comment by blefloch** [comment]
I agree with Joseph.
