### ISSUE TITLE
Make xparse detect @ and _ in command names

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#344]
I suggest making xparse detect command names with characters such as `@` and `_` and complain that there is probably some abuse of `xparse` concepts going on.

I have some code doing that and putting out a warning for things like `\NewDocumentCommand\foo@bar{}{}`, but I'm not sure exactly what should be accepted as names of `xparse` commands.

**Comment by wspr** [comment]
Makes sense and is a good way to emphasise that we are trying to work towards a more rigorous idea of what a "document command" is.

**Comment by josephwright** [comment]
We need at least to allow for environments: they can have stars (see other discussion). Presumably for a normal document command we go with either (i) just ASCII letters (possibly too restrictive) or (ii) only catcode-11 chars.

**Comment by josephwright** [comment]
I guess I'll update the `siunitx` internals now to allow for this!

**Comment by davidcarlisle** [comment]
On 7 March 2017 at 06:57, Joseph Wright <notifications@github.com> wrote:

> We need at least to allow for environments: they can have stars (see other
> discussion). Presumably for a normal document command we go with either (i)
> just ASCII letters (possibly too restrictive) or (ii) only catcode-11 chars.
>
>
Not ASCII, I'd just go for banning characters that are made not catcode 11
by \ExplSyntaxOff  (and \@makeatother) (rather than enumerating characters
that are allowed)

**Comment by josephwright** [comment]
So something like
``latex
\tl_set:Nn \l_@@_tmpa_tl {#1}
\tl_set_rescan:Nnn \l__@@_tmpb_tl { \ExplSyntaxOff \@makeother } {#1}
\int_compare:nNnTF { \tl_count:N \l_@@_tmpa_tl } { \tl_count:N  \l_@@_tmpb_tl }
```
would be about right? This covers the environment case for a star (both should be two tokens) as well as the more common case of a single token.

**Comment by josephwright** [comment]
BTW, any change here probably needs to be a warning not an error: there are lots of uses of `xparse` on CTAN where the commands set up are not document level. That's of course something we are not encouraging but at the same time we don't want to deliberately break loads of files.

**Comment by blefloch** [comment]
I think checking length of token lists doesn't do the right test.  Maybe the correct approach is to say any ASCII character in the name must be a letter?  By the way, we need to allow for control characters `\@` and `\_`.

**Comment by davidcarlisle** [comment]
On 7 March 2017 at 12:04, Bruno Le Floch <notifications@github.com> wrote:

> I think checking length of token lists doesn't do the right test. Maybe
> the correct approach is to say any ASCII character in the name must be a
> letter? By the way, we need to allow for control characters \@ and \_.
>

Or simpler, don't do the test.

there is a danger of code that only generates error messages (or warnings)
that in the end it does more harm than good (no one mention \outer:-)
for example the intention here is to discourage the use of
\NewDocumentCommand for defining internal command names
but the same code may equally be seen as encouraging the use of all-letter
document command names for internal commands,
so they can be defined with \NewDocumentCommand.

If \NewDocumentCommand\foo@bar generates an error it seems the simplest
change is to use
\NewDocumentComand\foobar rather than use some different definition idiom.
That isn't quite the intention of the check.

**Comment by FrankMittelbach** [comment]
I tend to side with David on this one (even though I love to see less/no 
misuse of the interfaces) it is more likely to do more harm than good

**Comment by blefloch** [comment]
Ok, I fold. You guys are probably right.
