### ISSUE TITLE
l3fp: sign() and ?

### ISSUE THREAD

**Issue by wspr** [latex3/latex3#346]
From Andrew on LaTeX-L:

> Two functions which I think could be beneficially added to l3fp without straining its role as a kernel module (in the way that, say, the gamma function would) are the signature function (sgn) and a unit step function (Heaviside? -- the difficulty is what value to assign at 0). Given the numerical values assigned to true and false in l3fp, it is easy to mimic these with simple inequalities (e.g. (#1 > 0) - (#1 < 0) for sgn) but perhaps the functions should be there in the first place?
> 
> I found myself wanting these when considering a table of fp values where it made sense to blank cells containing negative values which "got in the way". The code creating the table contained the option of blanking zero-value cells, so I multiplied the tabulated formula by 1 - (#1 < 0).

**Comment by wspr** [comment]
`sign()` or `sgn()` definitely makes sense to me, but I’m not sure about `step()` / `heaviside()` / whatever. Can you give another example for the use case there?

**Comment by blefloch** [comment]
I'm adding `sign` in the next commit.  I'm not adding `step`/`heaviside` because it will be impossible to decide whether `+0` and `-0` should give `1` or `0`.  Also, there is already `#1>0`, or the more explicit `#1>0?1:0`.

**Comment by wspr** [comment]
Thanks Bruno, I agree.

**Comment by aparsloe** [comment]
The use case instanced was the one that prompted the suggestion. For that, the step function was more relevant, but the mathematician in me felt uncomfortable including a relation like (#1 < 0) in a formula, where it is an accident of implementation that it gives the right values. I had overlooked the ?: operation, but I see it could ease my discomfort.
Andrew

**Comment by blefloch** [comment]
@aparsloe I suppose I can close the issue, then.
