### ISSUE TITLE
[xparse] argument processors

### ISSUE THREAD

**Issue by mrpiggi** [latex3/latex3#347]
With the current version of package xparse, the sequence of calling argument processors has been changed when using several processors on an argument. The documentation of xparse tells, that 

> Processors are applied from right to left, so that >{\ProcessorB} >{\ProcessorA} m would apply \ProcessorA followed by \ProcessorB to the tokens grabbed by the m argument.

But with the current version, it’s the other way around. I was wondering, if this was changed by purpose. In this case, the documentation should be updated and maybe marked with a change note.

```latex
\documentclass{article}
\usepackage{xparse}
\NewDocumentCommand\ProcessorTest{>{\ProcessorC}>{\ProcessorB}>{\ProcessorA}m}{%
  Result: #1%
}
\NewDocumentCommand\ProcessorA{m}{%
  \def\ProcessedArgument{ResultA}
  ProcessorA called with #1. Result is \ProcessedArgument\endgraf
}
\NewDocumentCommand\ProcessorB{m}{%
  \def\ProcessedArgument{ResultB}
  ProcessorB called with #1. Result is \ProcessedArgument\endgraf
}
\NewDocumentCommand\ProcessorC{m}{%
  \def\ProcessedArgument{ResultC}
  ProcessorC called with #1. Result is \ProcessedArgument\endgraf
}
\begin{document}
\ProcessorTest{Nothing}
\end{document}
```

**Comment by josephwright** [comment]
Issue comes from 30bef22da8317634d4bf7137d474e01f919e8555.

**Comment by blefloch** [comment]
Sorry, this was my mistake in `30bef22`, as Joseph says.  I had overestimated our test coverage and had not thought carefully about the order of processors, believing the test suite would check it for me.

I've added a test and committed a 9-character fix.
