### ISSUE TITLE
[xparse] Passing optional arguments as mandatory to internal functions

### ISSUE THREAD

**Issue by mrpiggi** [latex3/latex3#349]
With the current version of package xparse, there’s also a problem with passing optional arguments as mandatory ones to internal functions, if they are a  `–NoValue–` marker. In this case, the passed argument is empty.

```latex
\documentclass{article}
\usepackage{xparse}
\begin{document}

\NewDocumentCommand{\Test}{omom}{%
  \SubTest[#1]{#2}{#3}{#4}%
}{}
\NewDocumentCommand{\SubTest}{ommm}{%
  \detokenize{#1/#2/#3/#4}%
}
\Test{ABC}{123}

\end{document}
```

**Comment by josephwright** [comment]
This is @blefloch's fault :) Caused by  30bef22da8317634d4bf7137d474e01f919e8555!

**Comment by josephwright** [comment]
To be fair, internal functions should not take optional arguments ...

**Comment by mrpiggi** [comment]
In this case, it would great to have a macro on application level, which could be used to pass the `-NoValue-` marker to internal functions in order to utilize them for different cases.

```latex
\documentclass{article}
\usepackage{xparse}
\begin{document}

\NewDocumentCommand{\Test}{omom}{%
  \SubTest{#1}{#2}{#3}{#4}%
}
\NewDocumentCommand{\AnotherTest}{mm}{%
  \SubTest{-NoValueMarker-}{#1}{-NoValueMarker-}{#2}%
}
\NewDocumentCommand{\SubTest}{mmmm}{%
  \detokenize{#1/#2/#3/#4}%
}
\Test{ABC}{123}

\Test[bar]{ABC}[foo]{123}

\AnotherTest{DEF}{456}

\end{document}
```

**Comment by eg9** [comment]
The purpose of `xparse` is to provide an easy way to parse arguments in various formats: simple mandatory ones, optional ones with or without default, *-variants, delimited mandatory or optional ones. It also has facilities for splitting arguments in different ways.

After parsing, you have two choices: either go to the `expl3` level or, for simpler tasks at document level, process again the arguments or lists thereof with an internal (secondary) macro having *all* mandatory arguments, that can be tested with `\IfNoValueTF` or variants.

I see little usefulness in

    \NewDocumentCommand{\Test}{omom}{%
      \SubTest[#1]{#2}{#3}{#4}%
    }

where the argument `#1` is *always* present, so it's not optional.

This said, even if one chooses this approach, the `\SubTest` macro should be passed `-NoValue-` nonetheless.

**Comment by blefloch** [comment]
Fix incoming.  I had estimated that passing `-NoValue-` as a mandatory argument was unlikely but you give a use-case where that assumption is violated.  I agree the current outcome is confusing.

In the coming commit, however, passing `-NoValue-` as an optional argument is equivalent to not providing the optional argument at all.
