### ISSUE TITLE
Version error loading l3regex

### ISSUE THREAD

**Issue by thompcinnamon** [latex3/latex3#351]
When trying to compile a document with `mhchem` that uses `l3regex`, I got the following error:

    LaTeX Warning: You have requested, on input line 22, version
                   '2017/03/11' of package expl3,
                   but only version
                   '2017/03/07 v6984 L3 programming layer (loader) '
                   is available.

    ! Package l3regex Error: Support package l3kernel too old.

and the document doesn't compile because of too many errors when trying to use regex functions. Downgrading to the previous version of `l3experimental` makes the document compile just fine.

`tlmgr update --all` finds no updates. It is possible I would need to manually update `expl3`.

**Comment by eg9** [comment]
I had the problem this morning, but updated and it went OK

**Comment by josephwright** [comment]
Presumably installation of updates into TeX Live got split up: that's outside of the control of the team I'm afraid.

**Comment by thompcinnamon** [comment]
I can confirm after having updated today, it's working fine.

I had thought that it might have been just a typo somehow. Thank you for the explanation.
