### ISSUE TITLE
Specifying number of decimal places in \fp_to_tl:n

### ISSUE THREAD

**Issue by aparsloe** [latex3/latex3#352]
It would simplify some calculations to have a function like
\fp_to_tl:nn { fp expr. } { k } 
where k evaluates to an integer < 16 and specifies the number of decimal places. At present, e.g. calculating the Boltzmann constant from the gas constant and Avogadro number,
\fp_to_tl:n { 8.315/6.022e23 } => 1.380770508136832e-32
Since the inputs are to 3 decimal places what is wanted is
\fp_to_tl:n { round( 8.315/6.022e23, 26 ) } => 1.381e-23
In this instance it is not difficult to estimate the appropriate rounding value, but it would be more intuitive to write
\fp_to_tl:nn { 8.315/6.022e23 } { 3 } => 1.381e-23

**Comment by eg9** [comment]
Can you point to some use cases? For just printing the value, you can use `siunitx`:

    \documentclass{article}
    \usepackage{xparse,siunitx,xfp}

    \begin{document}

    $\num[
      round-mode=places,
      round-precision=3,
      scientific-notation=true,
    ]{\fpeval{8.315/6.022e23}}$

    \end{document}

![screen shot 2017-03-17 at 14 06 36](https://cloud.githubusercontent.com/assets/302839/24044286/f9102eb4-0b1a-11e7-8799-cb987cf0a03b.png)

**Comment by aparsloe** [comment]
Yes, there are other ways of achieving the desired effect, like using siunitx. (For my own use, I wrote a simple routine that splits a scientific-notation number into its two components and rounds the significand rather than the number itself.) My suggestion was prompted by looking at a table of constants, and the relations among them. Because these are dimensioned quantities, it is their ratios rather than sums or differences which are of concern, hence the interest in the number of decimal places in the significand rather than the size of the exponent.

**Comment by blefloch** [comment]
I think it would make sense to provide a way to round to a given number of places within floating point expressions, something like `roundplaces` (analogue of the `round` function).  What I'm wary about is that one would have to also provide `truncplaces` and `floorplaces` and `ceilplaces` for completeness.

Maybe an alternative would be to provide `exponentof` and let the user write `round(#1,2-exponentof(#1))`?

**Comment by aparsloe** [comment]
Yes, a function like ```exponentof``` would do the job. (And doubtless create pressure for also providing ```significandof```.)

**Comment by josephwright** [comment]
I suspect this would be covered by https://github.com/latex3/latex3/issues/173 (and so by `siunitx` v3.1, probably).

**Comment by blefloch** [comment]
`exponentof` is called `logb` in the IEEE standard, so I used this name.  So `round(#1,2-exponentof(#1))` should work now.  I'd rather have some kind of `roundplaces` or similar, but I cannot come up with a good name for it.
