### ISSUE TITLE
enhancement: specify destination page for float

### ISSUE THREAD

**Issue by kberry** [latex3/latex3#354]
This is likely not the right place to submit this
enhancement idea, but I figure it can be moved
around later if needed.

Especially when working on documents with lots of
figures, dealing with their placement is a
tremendous hassle. This is well known. In working
on such a TUGboat article recently
(https://www.tug.org/TUGboat/tb37-3/tb117lemberg.pdf,
sources available on request), I had an idea:
could LaTeX support tying a figure to a
user-specified page? For the sake of argument,
something like:

\begin{figure}[P=15]

which would force the figure to be at the top of
page 15 (t could be implicit, or for extra credit
both t and b could be supported).  For two-column,
it could be something like

\begin{figure}[P=15L] % or R
Syntax doesn't matter to me, logical vs. physical
pages doesn't matter, etc.; the details can always
be worked out. I'm just after the plausibility of
the basic concept in this initial submission.

In practice, this is what I (and, from what I've
seen over the years, thousands of other users)
would like to see: just put the figure on the page
I specify. Of course there may be all kinds of
completely unacceptable consequences, but that
doesn't matter. LaTeX puts the figure where I want
it, and then it's up to me to adjust the figure
size and other aspects to get things right. Which
is what I have to do now -- except without final
control over the placement.

In working on a given document, many times I know
for sure that I want a figure to end up at a
certain place (for semantic or physical reasons),
and will adjust sizes and text to make it work. It
would be a indescribably tremendous help to be
able to override LaTeX's placement algorithm and
just tell LaTeX "put the figure <there>". Having
figures move around while trying to do the page
layout makes everything soooo much harder.

[H] is not sufficient because it's not useful in
connection with float pages (e.g., the above
article has many of those), among other
reasons. The float parameters are nowhere near
sensitive enough to allow for such control, and
can't be adjusted float-by-float anyway.

Is that basic idea remotely workable?

Thanks, Karl

**Comment by FrankMittelbach** [comment]
Am 31.03.17 um 01:23 schrieb kberry:
> Is that basic idea remotely workable?

yes it is (in theory) ... I presume you want this for 2e not LaTeX3

I'll get back to you for questions on spec but not today

frank

**Comment by josephwright** [comment]
This is a 2e request, as it stands: I'll log there and close here.
