### ISSUE TITLE
Document that \fp_show:n { \infty } cannot detect the error

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#357]
Funnily,

    \RequirePackage{expl3}
    \ExplSyntaxOn
    \fp_show:n { \infty }

tells us that `\infty =561`.  This is unavoidable as `\infty` and a constant integer with value 561 have identical meanings `\mathchar"231`.  I need to figure out where to document that.

**Comment by FrankMittelbach** [comment]
Am 14.04.17 um 23:15 schrieb Bruno Le Floch:
> tells us that |\infty =561|. This is unavoidable as |\infty| and a
> constant integer with value 561 have identical meanings |\mathchar"231|.
> I need to figure out where to document that.

sounds weird

did know that 42 has an important meaning but not that 561 is equally 
important :-)

**Comment by eg9** [comment]
> On 14 Apr 2017, at 23:15 , Bruno Le Floch <notifications@github.com> wrote:
> 
> Funnily,
> 
> \RequirePackage{expl3}
> \ExplSyntaxOn
> \fp_show:n { \infty }
> tells us that \infty =561. This is unavoidable as \infty and a constant integer with value 561 have identical meanings \mathchar"231. I need to figure out where to document that.
> 

At the end of section 9.1 it is described how to input special numbers. I guess we can
add a final note such as

  Beware that \infty cannot be used in place of inf, as it denotes a math character,
  and unexpected results will occur. Also using \pi instead of pi would yield wrong results.

Ciao
Enrico

**Comment by blefloch** [comment]
If we think of a reasonably efficient test that distinguishes the control sequences `\infty`, `\pi` on the one hand, and `\c_my_constant_int` on the other hand, we could simply make l3fp complain about the former.  At first I thought of testing for the presence of `_`, but that would forbid things like `\tw@` or `\maxdimen`.

One option is `\cs_if_exist:cTF { __fp_parse_forbidden_ \cs_to_str:N #1 :w }` and then define things like `\__fp_parse_forbidden_infty:w` so that a short list of `\mathchardef`-ed commands are forbidden.

**Comment by eg9** [comment]
@blefloch If it doesn't add much overhead it could be a good idea. The list should contain `\infty`, `\pi`, but there will always be somebody who defines `\euler` to be the Euler constant and use it also in computations “for uniformity”.
