### ISSUE TITLE
l3regex: no support for Japanese?

### ISSUE THREAD

**Issue by aminophen** [latex3/latex3#363]
l3regex causes an error for tokens containing Japanese characters.

~~~~ tex
%#!uplatex
\documentclass{ujarticle}
\usepackage{expl3,l3regex,xparse}
\ExplSyntaxOn
\NewDocumentCommand \TEST { m }
  {
    \tl_set:Nn \l_tmpa_tl {#1}
    \regex_replace_all:nnN { some } { ful } \l_tmpa_tl
    \l_tmpa_tl
  }
\ExplSyntaxOff
\begin{document}

\TEST{{\TeX} is awesome!}% OK

\TEST{{\TeX} is 超 awesome!}% NG

\end{document}
~~~~

~~~~
! Invalid code, should be in the range 0..255.
~~~~

For practical use, mhchem fails to include Japanese characters, starting from version 4. mhchem version 3.x did not use expl3, so it could include Japanese tokens, so this is a serious problem for us Japanese users.

~~~~ tex
\documentclass{ujarticle}
\usepackage[version=4]{mhchem}
\begin{document}
\ce{PbCl2 ->[熱湯に溶解] Pb^2+ + 2Cl-}
\end{document}
~~~~

**Comment by blefloch** [comment]
I slightly disagree with Joseph here.  It is true that l3regex currently only supports the range 0-255, but at least the issue raised here is simply due to `l3tl-analysis` trying to be too clever, I've amended the code and will commit as soon as tests finish running.

There's actually a second issue which is that mhchem checks for letters using the regexp `[a-zA-Z]` which does not allow kanji.

**Comment by blefloch** [comment]
We should think of a more efficient way than what `mhchem` currently does with a series of `\__mhchem_regex_peek:NTF`.  Excerpt of the setup code:
```
\cs_new_protected:Npn \__mhchem_regex_peek_compile:Nn #1#2
  { \regex_const:Nn #1 { \A the\ (character|letter)\ (#2) \Z } }
\cs_new_protected:Npn \__mhchem_regex_peek:NTF #1#2#3
  {
    \peek_catcode:NTF ##
      {#3}
      { \regex_match:NoTF #1 { \token_to_meaning:N \l_peek_token } {#2} {#3} }
  }
```

**Comment by josephwright** [comment]
Do we need an urgent CTAN update here (make the TL'17 DVD)?

**Comment by josephwright** [comment]
@blefloch  Interface something like `\regex_peek:nN(TF)`?

**Comment by blefloch** [comment]
I can't figure out when our last CTAN release was.  If there was no "dangerous" change since then, then it makes sense to release now: currently, `l3regex` is unusable in (u)pTeX for a stupid reason.  In practice it won't fix the mhchem issue, but it comes up whenever a Japanese user uses regexes.

**Comment by josephwright** [comment]
@blefloch Last release `2017-04-01` (`git tag` or `svn ls ^/tags`, depending on the 'view' you are using). I'll sort an update tomorrow.

**Comment by FrankMittelbach** [comment]
Am 12.05.17 um 23:08 schrieb Bruno Le Floch:
> In practice it won't fix the mhchem issue, but it comes up whenever a
> Japanese user uses regexes.

how complicated is the fix for mhchem package? is its author aware of 
the issue?

**Comment by blefloch** [comment]
@josephwright  Thanks.  I think it would have been needed anyways due to r7076 (`Make xparse e-type give separate arguments (see #226, #331) (breaking change)`), no?

**Comment by blefloch** [comment]
@FrankMittelbach The fix is quite complicated.  I need to read the code more carefully to figure out exactly what the author wants to test.  Unfortunately I won't have time before the freeze.

**Comment by aminophen** [comment]
Checked out 9750b92 and "Invalid code" error has gone. And happily,

~~~~ tex
\usepackage[version=3]{mhchem}% instead of version=4
~~~~

became successful. Thanks!

> I need to read the code more carefully to figure out exactly what the author wants to test.

I will also read the code to figure out the changes between version=3 and version=4.

**Comment by aminophen** [comment]
My friend in Japan suggested that the syntax between version 3 and 4 are as follows:

~~~~ tex
\documentclass{ujarticle}
\usepackage[version=3]{mhchem}
\begin{document}
% version 3 syntax: none for math, C for chemicals, T for texts
\ce{A ->C[+H2O] B}\par
\ce{A ->[\Delta] B}\par
\ce{A ->T[Hot water] B}\par
\ce{A ->T[熱湯に溶解] B}\par
\end{document}
~~~~

~~~~ tex
\documentclass{ujarticle}
\usepackage[version=4]{mhchem}
\begin{document}
% version 4 syntax: none for chemicals and texts, $...$ for math, {} for texts
\ce{A ->[+H2O] B}\par
\ce{A ->[$\Delta$] B}\par
\ce{A ->[{Hot water}] B}\par
\ce{A ->[{熱湯に溶解}] B}\par
\end{document}
~~~~

The above codes work fine with commit 9750b92.
