### ISSUE TITLE
xparse e-type arguments with undefined control sequences not diagnosed

### ISSUE THREAD

**Issue by zauguin** [latex3/latex3#367]
When multiple undefined tokens are given to the xparse e-type argument, they are treated as if they were the same, except that this doesn't result in an error message.
This can lead to weird behaviour, for example
```latex
\documentclass{scrartcl}
\usepackage{xparse}
\ExplSyntaxOn
\DeclareDocumentCommand\command{e{\undefinedFirstArgument\undefinedSecondArgument}}{
  #1/#2
}
\ExplSyntaxOff
\begin{document}
\command\undefinedSecondArgument{something}
\end{document}
```
results in `something/-NoValue-` instead of `-NoValue-/something`.

**Comment by blefloch** [comment]
All of these optional arguments, in which the token denoting the presence of the argument is customizable (such as `d`, `t` or `e`), are really meant to be used for single characters, not arbitrary tokens.  Any `\futurelet` based approach will encounter the problem you describe.  It is in principle fixable but right now the balance between usefulness and difficulty to code seems to be in favor of not implementing this.

A more likely option now will be to add a test that only single characters are provided to `e`.  Actually, the same should probably be done for `t` type and `d` type arguments.
