### ISSUE TITLE
State is lost when \keys_set_known is nested

### ISSUE THREAD

**Issue by jmfarrow** [latex3/latex3#370]
There appears to be a bug in `\keys_set_known:nn` which does the following:

```
\cs_new_protected:Npn \keys_set_known:nn #1#2
  {
    \bool_set_true:N \l__keys_only_known_bool
    \keys_set:nn {#1} {#2}
    \bool_set_false:N \l__keys_only_known_bool
  }
```

_i.e._ if there are nested calls to `\keys_set_known` going on (which I imagine could happen if the .code of a key is injecting or parsing further keys?), the state of `\l__keys_only_known_bool` will get lost and things will blow up at the end of the second-deepest `\keys_set_known` which is now in the wrong state.

It should save the current state of `\l__keys_only_known_bool` at the state and restore that value at the end instead of setting it to false.

See also: https://github.com/wspr/fontspec/issues/292

**Comment by josephwright** [comment]
I have to admit my original concept here was that the rather specialist case of setting only know keys would not be used with nesting! I'll address this shortly.
