### ISSUE TITLE
\lua_now:n, etc. do not allow for escaping strings

### ISSUE THREAD

**Issue by josephwright** [latex3/latex3#371]
At present, the way `\lua_now:n` is set up means that it can't be used with _e.g._ `\lua_escape:n`. At the same time, the latter is likely wrong for the reasons noted in `l3str`.  Most likely we should define `\lua_now(_x):n` to escape the string automatically, and drop the escape functions.

This comes up as looking at the Lua-specific fix for https://github.com/latex3/latex3/issues/288, trying to swap the primitives for the higher-level functions fails to work correctly. However, the issue is more general.

**Comment by josephwright** [comment]
@hmenke Any comment here from the point of view of shell escape?

**Comment by josephwright** [comment]
@qinglee  Any comment here as you are using `\lua_now_x:n` in CTeX?

**Comment by josephwright** [comment]
To be clear, I suspect we should have
```latex
\cs_new:Npn \lua_now_x:n #1
  {
    \luatex_directlua:D
      {
        \luatex_luaescapestring:D
          \etex_detokenize:D \exp_after:wN { \luatex_expanded:D {#1} }
      }
  }
\cs_new:Npn \lua_now:n #1
  {
    \luatex_directlua:D
      {
        \luatex_luaescapestring:D
          \etex_detokenize:D \exp_after:wN {#1}
      }
  }
```
and drop the public interface to escaping strings (and similar for the `shipout` versions). This changes some semantics, hence being slightly wary.

**Comment by josephwright** [comment]
We might not need to worry about `#` doubling, of course, provided we get the documentation right. In genreal we only have LuaTeX to support, so it can simply do 'whatever'. For the special case of shell escape (where other engines do have something to match) we can always code by hand.

**Comment by hmenke** [comment]
Currently the shell escape in `l3sys` uses the primitives directly.  I though this would be the desired method in the kernel, as the same is done in the Lua version of `\__str_if_eq_x:nn`.  It should be possible though to switch to high-level commands instead.

**Comment by josephwright** [comment]
On the quick one of why not `\cs_new_eq:NN \lua_now_x:n \luatex_directlua:D`, that would then have different expansion behaviour in LuaTeX and other engines (which have to have a macro and thus at least two steps to a result). There's also the business that in general we are trying not to encourage depending on particular expansion changes: one would imagine here that either `f` or `x`-type expansion would be fine for getting a result.

**Comment by josephwright** [comment]
Note that the reason we have `_x` here is that the commands are expandable but carry out  `x`-type expansion of their argument. This is the same as `\str_if_eq_x:nn(TF)`: we used to call that `\str_if_eq:xx(TF)` but that was wrong (and got us into some confusion/trouble). The nearest comparison is something like `\int_eval:n`, which does have expansion 'built in' to the treatment of the argument. However, that's not `x`-type (it's nearer to `f`-type).

**Comment by josephwright** [comment]
It's far from decided (or even discussed), but at the moment I don't see us wanting to do anything akin to the stuff provided by `luacode`. All of that breaks expandability at point-of-definition, which is far from ideal. But more importantly, beyond trivial amounts of Lua it's best to have the code in a separate file anyway, so I'd overall imagine encouraging that sort of approach for programmers.

**Comment by josephwright** [comment]
(To remind me) The reason that the situation with shell escape is different from that here is that the former (1) does have to work in all engines in the same way and (2) isn't expandable. That means we can have a 'simple' `n`-type base function with a normal `x`-type variant.

On the other hand, here as we really want to maintain expandability we (almost certainly) can't do that: it would be very odd to drop the expandability.

**Comment by hmenke** [comment]
Okay, agreed.  But the proposed solution does not fix anything but breaks forwarding of quotes which is what you do very often in LuaTeX.  Everything that is a string is usually delimited by `"..."` and one just does, e.g. `print("\luaescapestring{<str>}")`.  The outer quotes would be escaped with your solution making it impossible to obtain literal quotes.  As an alternative one could use `[[...]]` but then you don't have to escape inner quotes anymore and something like `\lua_now_x:n { print([[ "Hello World!" ]]) }` will have spurious ` \ ` characters in the output.  Bottomlined the lack of escaping in `\lua_now:n` is justified and necessary.  That is the main point I was trying to make.

**Comment by josephwright** [comment]
OK, for the present I will leave this alone: we may want to revisit some of this in the future, though.

**Comment by hmenke** [comment]
At the same time I wonder, should L3 even expose a public interface to the `\directlua` functionality?  It is completely separate from the fundamental concepts of LaTeX.  For the same reason there is also no public interface in L3 for XeTeX charclasses.

**Comment by josephwright** [comment]
Remember that the long-term goal is that all functionality we expect people to need to use will have some code-level interface (or in a few cases a design-level one only, most obviously `xparse`). Thus to 'allow' use of Lua code in LaTeX3 we have to have some way of getting to Lua. The same is true for XeTeX charclasses, but the difference is that the latter will most likely end up with a structured interface with no exposure of the core concept. For Lua code, that's not an option so we can be pretty sure we need a 'thin' wrapper around `\directlua`: it's just a question of how 'thin'.
