### ISSUE TITLE
Add option to upload using l3build

### ISSUE THREAD

**Issue by josephwright** [latex3/latex3#372]
Similar to [`ctanupload`](https://www.ctan.org/pkg/ctanupload), it would be useful if something like `l3build upload <meta-data>` could submit a package directly to CTAN.

**Comment by blefloch** [comment]
Even better if the metadata could be put once and for all in the directory's `build.lua` file, perhaps?

**Comment by wspr** [comment]
Yes, indeed!

I'm also idly wondering about the possibility of grabbing appropriate text from (or writing to?) a RELEASENOTES file. 

I need to check whether there have been any updates to ctanupload recently; if there haven't been I think it no longer works :-) Will report back.

**Comment by josephwright** [comment]
Moved to https://github.com/latex3/l3build/issues/1
