### ISSUE TITLE
xparse: Number and dimension arguments

### ISSUE THREAD

**Issue by hmenke** [latex3/latex3#373]
I was thinking that it would be cool if the parser could check whether an argument is a number or a dimension, so the user does not have to check it themselves.  The new shortcuts `n` for number and `l` for length seem appropriate. (EDIT: unfortunately, both `l` and `d` are taken)
````latex
\NewDocumentCommand \concept { n l }
{
  \looseness=#1
  \setlength\tabcolsep{#2}
}
````
This seems very user-friendly to me because the error is caught immediately when trying to expand the first stage.  Otherwise the user would get
````
Missing number, treated as zero.
<to be read again> 
                   .
l.3 \looseness=.
                ..
````
without knowing where it comes from.

**Comment by eg9** [comment]
I'd not add it.

**Comment by josephwright** [comment]
The nature of `xparse` argument types is that they relate to grabbing the argument. WE have got 'processors' which could be used here
```latex
\documentclass{article}
\usepackage{xparse}

\NewDocumentCommand \concept { >{\CheckInteger}mm }
{
  \looseness=#1
  \setlength\tabcolsep{#2}
}
\ExplSyntaxOn
\cs_new_protected:Npn \CheckInteger #1
  {
    \regex_match:nnF { ^[\+\-]*[\d]+$ } {#1}
      {
        \ERROR % Some real message!
      }
  }
\ExplSyntaxOff
\begin{document}

\concept{10}{10ml}

\end{document}
```
although in general we've not tried to cover validation.

**Comment by hmenke** [comment]
The processors are a good feature.  I like the idea of adding a set of validators.  Is `l3regex` part of the kernel?

**Comment by josephwright** [comment]
We moved `l3regex` to the kernel in the most recent release.

**Comment by josephwright** [comment]
I think at present this is a 'no' for the reasons outlined above.
