### ISSUE TITLE
indexing is missing a backslash

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/latex3#374]
if something like `\cs[index=str_clear:N]{str_(g)clear:N}`is used then we end up with an index entry without a `\` despite what the documentation claims

**Comment by josephwright** [comment]
Various index things are bust, see for example my `siunitx` issue (almost everything appears twice) ...

**Comment by FrankMittelbach** [comment]
if we record it ... one day we may fix it :-) ... a good index helps in analysis (me at least)

**Comment by wspr** [comment]
Sorry, didn't have time to re-architect this for slightly clearer code. Anyway, it works now :)
