### ISSUE TITLE
Missing error-check for unbalanced braces in \regex_extract_once:nnN

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#377]
`\regex_extract_once:nnN` fails to check for unbalanced braces, making the resulting sequence invalid.
```
\RequirePackage{expl3}
\ExplSyntaxOn
\regex_extract_once:nnN { a..b } { {a}{b} } \l_tmpa_seq
\show\l_tmpa_seq
```
I haven't checked yet if I introduced that bug in recent `l3regex` changes (when switching to `\fontdimen` maybe I made mistakes) or if the test is simply missing from that function.  More testing needed with other functions.

**Comment by eg9** [comment]
> On 12 Jul 2017, at 17:32, Bruno Le Floch <notifications@github.com> wrote:
> 
> \RequirePackage{expl3}
> \ExplSyntaxOn
> \regex_extract_once:nnN { a..b } { {a}{b} } \l_tmpa_seq
> \show\l_tmpa_seq

I tried the code with TL from 2014 and the result is always the same

Ciao
Enrico

**Comment by blefloch** [comment]
Thanks Enrico!  From the code it seems both the `extract` and the
`split` functions should be affected: only the `replace` function has
the necessary brace-balance code.  That's a bit tricky to get right
since for `extract` and `split` each part needs to be balanced; I hope
to get time on Friday or this weekend.

**Comment by blefloch** [comment]
Actually the brace-balance code is not clever enough at all:

1. The end-group character `>` below ends the tl assignment, then we have `\show<`.
    ```
    \regex_replace_all:nnN { } { a \cE\> \c{show} \cB\< } \l_tmpa_tl
    \tl_show:N \l_tmpa_tl
    ```
2. Similarly, duplicating the `}` and `{` here wrongly ends the assignment.
    ```
    \tl_set:Nn \l_tmpa_tl { { a } { b } }
    \regex_replace_all:nnN { (\}) (\{) } { \1\1 \c{show} \2\2 } \l_tmpa_tl
    \tl_show:N \l_tmpa_tl
    ```

**Comment by blefloch** [comment]
That was tough.
