### ISSUE TITLE
Peeking for ampersand

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#379]
The following code shows that `peek` functions need `\group_align_safe_begin:` to be applied more widely.  At present the following breaks when trying to save the peeked token into `\l__peek_search_token`.  Even if that was fixed, it would break when calling `\__peek_true_remove:w`.
```
\documentclass{article}
\usepackage{expl3}
\begin{document}
\ExplSyntaxOn
\begin{tabular}{cc}
  \peek_catcode_remove:NTF {&} {\TRUE\show}{\FALSE\show} & a \\
\end{tabular}
\end{document}
```

**Comment by davidcarlisle** [comment]
Perhaps or perhaps this is just a "legacy" issue and there should never be
a raw exposed catcode 4 `&` in the document

```
\documentclass{article}
\usepackage{expl3}
\begin{document}
\ExplSyntaxOn
\let\halignsep&
\catcode`\&13
\protected\def&{\halignsep}
\begin{tabular}{cc}
  \peek_catcode_remove:NTF {&} {\TRUE\show}{\FALSE\show} & a \\
\end{tabular}
\end{document}
```

**Comment by josephwright** [comment]
We do have a tension between 'works entirely generically' and 'targetting a new format': if we can make stuff work *relatively easily* that is good, but if it is extremely complex and has a better long-term solution anyway, then documentation is likely the way to go.

**Comment by FrankMittelbach** [comment]
Am 14.07.17 um 10:07 schrieb Joseph Wright:
> We do have a tension between 'works entirely generically' and 
> 'targetting a new format': if we can make stuff work /relatively easily/ 
> that is good, but if it is extremely complex and has a better long-term 
> solution anyway, then documentation is likely the way to go.

I was always wondering what (if anything) would break if we move already 
in 2e from raw ampersands to active ampersands

if the catcode 4 vanishes already in the kernel then packages using & 
should pick up things (I guess) correctly except for those that do tests 
for catcode 4 explicitly. Wonder how many there are?

frank

**Comment by josephwright** [comment]
BTW, I'd call the macro name `\aligntab` as that's a primitive for exactly this purpose in LuaTeX ...

**Comment by josephwright** [comment]
@davidcarlisle  Markdown doesn't work in emailed replies ;)

**Comment by josephwright** [comment]
@FrankMittelbach  Probably 'very few': I was worried about `tex4ht` but a quick check shows no issues there. If we can change the 2e kernel then I'd definitely not worry about this at the `expl3` end beyond documentation.

**Comment by davidcarlisle** [comment]
flicking through package documentation we find...

```
% .....
% approximates to the truth about what is actually happening. The idea
% of making it easier to allow entries to be taken as arguments may be a
% non-starter if "&" is allowed to become a `short-ref' (ie "\active")
% character.
```

Which basically is warning that the second table here will blow up.

```
\documentclass{article}

\usepackage{array}
\def\foo#1!{\fbox{#1}}
\begin{document}

\begin{tabular}{>{\foo}c<{!}c}
 xx&bb\\
\end{tabular}



\let\halignsep&
\catcode`\&13
\protected\def&{\halignsep}

\begin{tabular}{>{\foo}c<{!}c}
xx&bb\\
\end{tabular}

\end{document}
```

I think that idiom is used in several places to catch a cell as a macro argument. Of course with active & you can probably do this more easily but still means changing the 2e format would break some stuff (that doesn't necessarily mean we shouldn't do it)

**Comment by blefloch** [comment]
amsmath breaks (but IIRC that would be trivial to fix in the source).
```
\let\halignsep&
\catcode`\&13
\protected\def&{\halignsep}
\documentclass{article}
\usepackage{amsmath}
```

**Comment by davidcarlisle** [comment]
Bruno's example suggests this might be safer (it doesn't break amsmath at least)


```
\let\halignsep&
\protected\def\tmp{&}
\catcode`\&13
\let&\tmp

```

**Comment by blefloch** [comment]
I've fixed the issue in `l3token` (just needed to move `\group_align_safe_begin:` ... `\group_align_safe_end:` at the very beginning/end of the peeking).
