### ISSUE TITLE
Consider adding \inteval and \dimeval to xfp

### ISSUE THREAD

**Issue by hmenke** [latex3/latex3#382]
These two would make a good substitute for `\numexpr...\relax` and `\dimexpr...\relax` with much more functionality.

**Comment by blefloch** [comment]
That's a good point.  (Although note that `\int_eval:n` and `\dim_eval:n` are very very thin wrappers around the primitives.)

**Comment by blefloch** [comment]
If we add that we should consider `\skipeval` and `\muskipeval` too.

That makes me hesitate a bit.

**Comment by hmenke** [comment]
This is mainly about writing docs.  The commands themselves are rather trivial, right?
```latex
\DeclareExpandableDocumentCommand \XXXeval { m }
{
  \XXX_eval:n { #1 }
}
```

**Comment by hmenke** [comment]
Can you assign me to this issue?  I'll try do it soon.  Perhaps @josephwright needs to add me to the LaTeX3 project group first.

**Comment by blefloch** [comment]
It's a matter of deciding whether we want to commit to having more LaTeXe interfaces to `expl3`-level commands, which we might or might not.  I'd just want more people to chime in (or at least a less tired version of myself).

`\stop`ping for tonight, sorry.

**Comment by wspr** [comment]
If it were expl3 itself I would definitely hesitate before seeing some very compelling use cases. Where possible I think we should be encouraging people to use `\ExplSyntaxOn/Off` if they are actually doing programming-style work, and if they’re not we should be pushing for whatever interface they’re using to adopt fp internally.

But since xfp has to be loaded separately, I don’t mind adding the extra `\XXeval` macros ones here too.

**Comment by josephwright** [comment]
The reason we went for `\fpeval` is it otherwise requires `\ExplSyntaxOn`. `\inteval` can be done using `\newcommand`
```latex
\newcommand*{\inteval}{\intexpr #1\relax}
```
as it's just a wrapper around the primitive.

**Comment by wspr** [comment]
Oh, of course. I had it in my head that the fp parser was being used here. If not then there’s no need for \inteval and friends.

**Comment by blefloch** [comment]
Slight correction to what Joseph wrote:

    \newcommand*{\inteval}{\the\numexpr #1\relax}

**Comment by blefloch** [comment]
One extra feature we could provide, that would maybe justify adding `\inteval` etc, is better error-checking, such as testing for balanced parentheses etc, but I'm not sure whether or not it's worth the effort.

Maybe just doing the following with parentheses is worthwhile since people might not think of it?

    \newcommand{\inteval}{\the\numexpr(#1)\relax}

Or something slightly more robust: computing the `\numexpr` in a brace group to make trailing `\@gobble` (or similar) cause comprehensible errors.

    \newcommand{\inteval}{\the\numexpr\unexpanded\expandafter{\the\numexpr(#1)}\relax}

Or something more clever testing that the result in the brace group is really only an integer and has no trailing junk.

**Comment by eg9** [comment]
> On 16 Jul 2017, at 08:48, Joseph Wright <notifications@github.com> wrote:
> 
> The reason we went for \fpeval is it otherwise requires \ExplSyntaxOn. \inteval can be done using \newcommand
> 
> \newcommand*{\inteval}{\intexpr #1\relax}
> as it's just a wrapper around the primitive.

Yes, but

    \newcommand*{\inteval}{\the\numexpr #1\relax}

doesn’t really fit LaTeX3 syntax.

Ciao
Enrico

**Comment by blefloch** [comment]
@eg9 Can you clarify whether you're arguing for or against adding `\inteval` to `xfp`?  (Sorry, it's probably obvious but I'm failing to see.)

**Comment by eg9** [comment]
> On 19 Jul 2017, at 13:58, Bruno Le Floch <notifications@github.com> wrote:
> 
> @eg9 Can you clarify whether you're arguing for or against adding \inteval to xfp? (Sorry, it's probably obvious but I'm failing to see.)

For. Or for adding to interface3/xparse doc the suggestion of doing

    \NewExpandableDocumentCommand{\inteval}{ m }{ \int_eval:n { #1 } }

Ciao
Enrico

**Comment by blefloch** [comment]
Thanks.  That makes some sense.  Naming-wise, `\inteval` is ok, `\dimeval` probably too, but should it be `\skipeval`, `\lengtheval` (in keeping with LaTeXe's `\setlength`), `\glueeval`?  Same questions for `\muskipeval`, `\mulengtheval`(??), `\muglueeval`(?).

**Comment by eg9** [comment]
> On 19 Jul 2017, at 14:16, Bruno Le Floch <notifications@github.com> wrote:
> 
> Thanks. That makes some sense. Naming-wise, \inteval is ok, \dimeval probably too, but should it be \skipeval, \lengtheval (in keeping with LaTeXe's \setlength), \glueeval? Same questions for \muskipeval, \mulengtheval(??), \muglueeval(?).

\lengtheval seems necessary for `\setlength{\foo}{\lengtheval{<whatever>}}

This would avoid the need for `calc` in almost all places. The “mu” related
commands don’t seem so important.

Ciao
Enrico

**Comment by josephwright** [comment]
@eg9  My point was that `\fpeval` _requires_ access to `expl3` code, so fits within 'our' remit. On the other hand, users can already use integer, dimension and glue expressions as they are engine-supported: my `\newcommand` example was really just to make the point 'no `\ExplSyntaxOn` or `\makeatletter` required'. One might argue that `\inteval` is useful, but wouldn't it belong in the 2e kernel?

**Comment by blefloch** [comment]
Note that most features of `\inteval` and `\dimeval` are supported out of the box by `\fpeval`.  Exceptions: hexadecimal/octal/backquote escapes and `true` units.

**Comment by car222222** [comment]
I got a bit lost on this one.  

But I do think that having a terminated version easily available must be a good thing.

Do people really use googling to remove the \relax when using such forms?  That sounds very perverse to me.

Chris

> \newcommand{\inteval}{\the\numexpr(#1)\relax}
> Or something slightly more robust: computing the \numexpr in a brace group to make trailing \@gobble (or similar) cause comprehensible errors.
> 
> \newcommand{\inteval}{\the\numexpr\unexpanded\expandafter{\the\numexpr(#1)}\relax}
> Or something more clever testing that the result in the brace group is really only an integer and has no trailing junk.
>

**Comment by blefloch** [comment]
@car222222 Sorry, I was unclear.  I meant if bad macros accidentally try to grab arguments past the end of the expression they'd hit the brace and produce an error rather than grabbing `)\relax`.  I shouldn't have mentioned `\@gobble` which suggests it would be done on purpose.

**Comment by josephwright** [comment]
Fixed by https://github.com/latex3/latex3/commit/5409da13d5d770082bc9b7b387185ab11d720491.
