### ISSUE TITLE
xcolor with 'rgb' “breaks” l3doc

### ISSUE THREAD

**Issue by tweh** [latex3/latex3#383]
It seems like something has changed, so that now the output of the functions in the left margin are corrupted (i.e. they disappear) when using `xcolor` and the `rgb` option in `l3doc`.

```latex
\documentclass{l3doc}

%\usepackage{xcolor}% works
%\usepackage[cmyk]{xcolor}% works
\usepackage[rgb]{xcolor}% doesn't work

\begin{document}

\begin{function}{\function}
Description
\end{function}

\end{document}
```

I know that `l3doc` is far away from being stable, but I still like to use it and wonder what causes the problem with `rgb`.

**Comment by blefloch** [comment]
Thanks for the bug report!  Your test shows it's there but in white.  I don't know why.

**Comment by tweh** [comment]
Sorry, I could have been a bit more precise instead of just writing ”disappears“.

**Comment by wspr** [comment]
I just updated MacTeX 2017 completely and I can’t reproduce the problem. (Hopefully I’m not missing something obvious.)
I almost wonder if it might be a PDF display bug?

**Comment by blefloch** [comment]
There seems to be a bug in `\color_ensure_current:` (or rather in our `native` drivers). It incorrectly uses the rgb values as cmyk.  For instance, 
```
\documentclass{article}
\usepackage[rgb]{xcolor}
\usepackage{expl3}
\begin{document}
\color[rgb]{0.5 0 0}
abc
\ExplSyntaxOn
\color_ensure_current:
\ExplSyntaxOff
abc
\end{document}
```
gives something like red and cyan text.  Probably @josephwright will have a much better grasp on what to do?

**Comment by josephwright** [comment]
I'll take a look: I think this must be an issue with the conversion of internal colour data formats.

**Comment by josephwright** [comment]
I'll look to do a release this evening: broken colour is not ideal!

**Comment by tweh** [comment]
Great. Thanks for the fast fix!

Just for reference, I attach my PDF and `log` file because I wonder why @wspr can’t reproduce it … It is build with an up to date (at time of writing this) MacTeX. I also tried Acrobat Pro, Illustrator, Preview.app and Skim. The PDF looks the same (white margin par) in all viewers.

[l3doc-test.zip](https://github.com/latex3/latex3/files/1158181/l3doc-test.zip)

**Comment by josephwright** [comment]
@tweh I guess @wspr has an old copy of the `l3pdfmode.def` somewhere: the bug is clear when you look at the code!

**Comment by tweh** [comment]
Ok. Thanks for clarification :-)

**Comment by wspr** [comment]
Sorry for the noise — I had forgotten that my TeX editor defaults to using XeTeX :( Indeed, the problem is plain when you use pdfLaTeX!
