### ISSUE TITLE
l3seq.dtx: Explain the "true" branch of the functions in the "Recovering values from sequences with branching" section

### ISSUE THREAD

**Issue by EvanAad** [latex3/latex3#394]
The description of none of the functions listed in the "Recovering values from sequences with branching" section of the l3seq documentation explains how and when the `<true code>` is used.

The same applies to the first three of the last four functions in the "Sequences as stacks" section of the same document.

**Comment by josephwright** [comment]
I tightened some of this up a while ago: must have missed the TRUE branches. I'll adjust.
