### ISSUE TITLE
Add functions for using sequences as sets

### ISSUE THREAD

**Issue by EvanAad** [latex3/latex3#396]
Could you please provide standard functions for manipulating sequences as sets? The API as well as its implementation are already given in section 10 ("Sequences as sets") of the l3seq.dtx document, so what's the big deal making them available as functions? Why force every programmer who wants to use these functions to copy-and-paste them from the manual? You think they won't be used much? Maybe you're right; maybe not. And if you're right, why even bother writing this section in the manual? And what's so terrible in having a handful of standard functions that won't be used as much as the others?

It should also be mentioned that all the most popular general-purpose programming languages in use today - C++, Java, Python, C# - offer a set API, which brings into question the claim that this functionality is rarely used by programmers.

**Comment by wspr** [comment]
We are wary of providing too many interfaces — such guidance is provided so that users can experiment with this functionality, and if they find them useful we can consider adding them properly to the kernel. Do you have a particular use case in mind?

**Comment by wspr** [comment]
TeX is not an efficient programming language for certain things. Just because it can be done doesn’t necessarily mean it should be. Do you have any examples for programming a LaTeX package (say) that would benefit from having in-built set functions?

I’m definitely not personally against the idea of having functions like \seq_union:NNN and so on. As I mentioned, if people did start using set-based functions in a handful of situations then we would almost certainly add them to the kernel.

**Comment by eg9** [comment]
> On 29 Sep 2017, at 01:14 , Will Robertson <notifications@github.com> wrote:
> 
> TeX is not an efficient programming language for certain things. Just because it can be done doesn’t necessarily mean it should be. Do you have any examples for programming a LaTeX package (say) that would benefit from having in-built set functions?
> 
> I’m definitely not personally against the idea of having functions like \seq_union:NNN and so on. As I mentioned, if people did start using set-based functions in a handful of situations then we would almost certainly add them to the kernel.

I concur. I wrote hundreds of lines of expl3 code, sometimes reusing ideas and functions,
but only in a few cases I asked for addition to the kernel.

The fact that TeX can be used for CAD (see TikZ/PGF) doesn’t mean we want to
add a full fledged drawing machine to the expl3 kernel.

I know well that sets are basic in all fields of mathematics, but this doesn’t mean
we want to implement boolean algebra of sets in the kernel.

An intellectual problem can be entertaining and amusing to solve, but we’re providing
a system for _typesetting_, we shouldn’t forget it.

Ciao
Enrico

**Comment by blefloch** [comment]
I'm in favour of adding these functions, but with important disclaimers about efficiency.

The main reason I didn't add them when revamping `l3seq` was that it wasn't clear what these functions should do when the input isn't a set (i.e. has duplicate items), and in what order items should be put in the result.

Now that we have l3sort it could actually make sense to use it to make the implementation reasonably fast.

**Comment by EvanAad** [comment]
In hindsight, maybe adding a set abstraction to the LaTeX3 language is not as simple as I thought, since there are several varieties of a set (viz. a set, a multiset, an ordered set), and so many ways to implement it. Maybe the best approach would be to write a package dedicated to this abstraction with all its myriad faces. This package need not be a part of the core LaTeX3 language; at least not at first.

**Comment by FrankMittelbach** [comment]
Am 29.09.17 um 09:14 schrieb EvanAad:
> In hindsight, maybe adding a set abstraction to the LaTeX3 language is 
> not as simple ...

which is precisely why we are slow in adding too much stuff (as Will 
already mentioned).

Orthogonality is a theme for expl3, eg we try to have predicatable names 
and if one data type say has a certain function and that make sense for 
another data type then that should be there too but before we add new 
abstractions we want some clear use to avoid that the language gets 
tooooo big

frank

**Comment by wspr** [comment]
Based on @EvanAad 's comment above I think it's fair to see we agree not to keep this issue open any more.
