### ISSUE TITLE
l3int.dtx - \__int_to_roman:w ... "non-expandable token"?

### ISSUE THREAD

**Issue by EvanAad** [latex3/latex3#397]
The description of the `\__int_to_roman:w` function in the l3int.dtx document says:

> Expansion ends when a space or non-expandable token is found.

But isn't the integer built out of non-expandable digit tokens? Maybe the documentation means "an unexpandable token which is not a valid part of an integer", which is the phrase used in the description of the function `\__int_eval:w` in the same document.

**Comment by josephwright** [comment]
We could change that but notice that this is already a 'documented internal' function: we use it in various places in the kernel but it's not for wider use. (We are currently discussing some aspects of how to document and otherwise mark up such cases, which are necessary inside the kernel.)

**Comment by car222222** [comment]
It means ‘the expansion of a token ends . . . ‘ ; if a digit is found then the expansion process continues with the next token, otherwise it stops completely.



.

**Comment by eg9** [comment]
> On 28 Sep 2017, at 12:31, EvanAad <notifications@github.com> wrote:
> 
> The description of the \__int_to_roman:w function in the l3int.dtx document says:
> 
> Expansion ends when a space or non-expandable token is found.
> 
> But isn't the integer built out of non-expandable digit tokens? Maybe the documentation means "non-numeric token”?

I agree that it is not clear for people not acquainted with the working of \romannumeral

However, <integer> should already cover the matter, weren’t for the fact it’s used
in a different sense elsewhere. Probably <integer denotation> would be better here.

Ciao
Enrico
