### ISSUE TITLE
XeLaTeX and xparse error with MikTeX (Undefined control sequence)

### ISSUE THREAD

**Issue by joshuaehill** [latex3/latex3#40]
When I attempt to compile the minimal .tex file:
---snip---
% !TEX TS-program = xelatex
% !TEX encoding = UTF-8
\documentclass[11pt]{article}
\usepackage{fontspec}
\begin{document}
Problem with xparse.sty
\end{document} 
---snip---

using XeLaTex Version 3.1415926-2.3-0.9997.5 (MiKTeX 2.9), I am getting the following error:

---snip---
("C:\Program Files (x86)\MiKTeX 2.9\tex\latex\l3packages\xparse\xparse.sty"
! Undefined control sequence.
<argument> \ExplFileName 

l.57 ...e}{\ExplFileVersion}{\ExplFileDescription}
---snip---

I've verified that I don't have a conflict with an earlier version of xparse.sty elsewhere, and that the current version of l3kernel/l3packages on CTAN (downloaded on 2011-August-18) exhibits the same problem.

**Comment by aakhtar4** [comment]
> Sorry for the trouble and thanks for writing. I don't use MiKTeX personally, but I believe that this error is caused by a slightly older `l3kernel` package (and thus being out of sync with `l3packages`). Does this package appear in your MiKTeX package repository? Please try updating everything to the very latest versions and things should hopefully be okay.

Thanks this helped. I had to remove `l3kernel` in favor of `l3packages` which was installed recently and the `Undefined control sequence` error with `xparse` went away.
