### ISSUE TITLE
[file:l3prop.dtx, section:4-Modifying property lists, function:\prop_remove:Nn] Clarify whether the entry is removed locally.

### ISSUE THREAD

**Issue by EvanAad** [latex3/latex3#403]
SORRY! PLEASE DISREGARD THIS BUG REPORT. I WOULD DELETE IT, IF I KNEW HOW.

***

File: l3prop.dtx
Section: 4 - Modifying property lists
Function: `\prop_remove:Nn`

Is the entry removed locally or globally? This isn't specified currently.

**Comment by josephwright** [comment]
It's local: `remove` is one of the terms we systematically use `g` with for global operations. You'll see that the documentation covers both.

**Comment by EvanAad** [comment]
Yeah. I noticed it immediately after posting this bug report, but I couldn't figure out how to delete the report.

**Comment by josephwright** [comment]
@EvanAad You can't delete issues, but you can close them :)
