### ISSUE TITLE
l3keys: trim spaces instead of remove spaces

### ISSUE THREAD

**Issue by wspr** [latex3/latex3#413]
The following code demonstrates how l3keys removes all spaces from input keys.

```
\documentclass{article}
\usepackage{expl3}
\begin{document}
\ExplSyntaxOn
\keys_define:nn {bar} { unknown .code:n = { \typeout{`\l_keys_key_tl'=#1} } }
\def\KVB#1{\keys_set:nn {bar}{#1}}
\ExplSyntaxOff
\KVB {key c=book}
\end{document}
```

While this was added for flexibility in accepting input, on balance I think we agree that it is better to be more strict here. It might make sense to have another option to enable whether keys in a family should be normalised. (Or a shorthand to simply define a pair of keys at setup time, one with and one without spaces removed.)

The main motivation for bringing this up is that I needed to use the unknown key in its original form, and it would be cumbersome to say the least to keep track of the unnormalised input while keeping the current behaviour.

**Comment by josephwright** [comment]
A quick check shows this should be a safe enough change: doesn't break the core packages in the test suite.
