### ISSUE TITLE
l3skip: view the dimension of LaTeX2e macro

### ISSUE THREAD

**Issue by Stone-Zeng** [latex3/latex3#417]
Try the following code:

```tex
\documentclass{article}
\usepackage{expl3}

\begin{document}
\ExplSyntaxOn
\tl_const:Nn \c__foo_test_tl { 1cm }
\dim_set:Nn \rightskip { \c__foo_test_tl }
\dim_show:N \rightskip
\dim_show:N \rightskip
\ExplSyntaxOff
\end{document}
```

Only the second `\dim_show:N` gives the right value:
```tex
> \rightskip=0.0pt.
<recently read> }
                 
l.8 \dim_show:N \rightskip
                          
? 
> \rightskip=28.45274pt.
<recently read> }
                 
l.9 \dim_show:N \rightskip
                          
? x
```

If try this

```tex
\dim_set:Nn \rightskip { \c__foo_test_tl }
\cs_show:N \dim_show:N  % something else
\dim_show:N \rightskip
```

The result of `\dim_show:N` is also correct.

Of course, when using the "appropriate way" as `\skip_set:Nn \rightskip { \c__foo_test_tl }` instead, both results is OK then.

LaTeX3 version: 2017/11/14.

**Comment by josephwright** [comment]
You are using `\dim_set:Nn` on something that is a skip: I'm not sure that anything other than 'trouble' can arise ...

**Comment by FrankMittelbach** [comment]
> You are using |\dim_set:Nn| on something that is a skip: I'm not sure 
> that anything other than 'trouble' can arise ...

well it wouldn't need to and it is kind of reasonable to expect that 
\dim_set:Nn would set the main part of a skip and the plus/minus to zero

all that is missing is a \scan_stop: in the definition, isn't it? that 
would guard against it like it guards against it in \skip_set:Nn.

So even if that is a bit of a questionable use the outcome should either 
be an error or sensible not kind of random.

**Comment by josephwright** [comment]
@FrankMittelbach There is a `\__dim_eval_end:` = `\scan_stop:` there: I guess you mean you need two to catch this situation?

**Comment by FrankMittelbach** [comment]
Am 24.11.17 um 15:45 schrieb Joseph Wright:
> @FrankMittelbach <https://github.com/frankmittelbach> There is a 
> |\__dim_eval_end:| = |\scan_stop:| there: I guess you mean you need two 
> to catch this situation?

that stop the \__dim_eval:w   but it does not stop #1 ~ for scanning 
further if #1 is a skip not a dim.

**Comment by car222222** [comment]
> You are using \dim_set:Nn on something that is a skip:
> 
Whichever operand is which, both should do something sensible (by reasonably normal coercion).
Certainly not a cause for dismissal as ‘trouble’.  More an opportunity for some politesse and a fix.
