### ISSUE TITLE
Should something like \cs_generate_variant:Nn \foo_my_func:n { N }  throw an error?

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/latex3#418]
In my opinion trying to change an "n" argument to "N" is actually  an interface misuse as both are base types, ie a function either excepts a single token so "N" or it expects a braced aregument so "n". It doesn't hurt so much (at least in this direction) but it is actually wrong.

**Comment by eg9** [comment]
I agree it is wrong to even try defining such a variant; an error message seems OK; also N to n, I'd say.

**Comment by blefloch** [comment]
I probably didn't envision this case when I revised the code some years ago.

Actually I remember someone was actively using that `\cs_generate_variant:Nn \foo:n { c }` works (personally I find such code bad).  What should we decide about that?

There might be a previous issue about `\cs_generate_variant:Nn` to look at.

**Comment by wspr** [comment]
Why would someone do this? The more sanity checks the better for code like this. I'm in favour of restricting the allowed inputs/outputs to a strictly defined (and sensible) set of possibilities.

Same Bruno's example. (I can imagine code of mine looking like this at one point as I was translating and mutating internal 2e-style code as I went.) I don't see a problem of enforcing the mappings that only `N` can "varianted" into "c", etc.

**Comment by josephwright** [comment]
@wspr  There was an example on TeX-sx: https://tex.stackexchange.com/q/402862. That came down to a misunderstanding of how `tl` variables work ...

**Comment by FrankMittelbach** [comment]
> Actually I remember someone was actively using that 
> |\cs_generate_variant:Nn \foo:n { c }| works (personally I find such 
> code bad). 

bad code in probably most cases, but it is a bit more defensible imo. 
After all

  \foo:n { \l_bar_tl }

would be perfectly legal, so

  \foo:c { l_ #1 _tl }

could be a use case.

> What should we decide about that?

for that reason I would probably allow it. In fact, n -> N could be 
allowed too though it is more likely simply a mistake/misunderstanding 
so that one I'm more in favor of catching if it can be done easily.

but N -> n should definitely result in an error (maybe it does not 
checked) because that is wrong and could lead downstream to serious 
problems.

**Comment by blefloch** [comment]
I now think we should forbid n→c.  It is pretty common to have a function `\tl_foo:N` and another `\tl_foo:n` that operate on token lists (in the first case on the contents of a variable) so allowing to generate c variants of n-type args can become confusing.  For instance `\tl_count:c` is not the c-variant of `\tl_count:n` but of `\tl_count:N`.

For the case Frank gives I think I would write

    \exp_args:Nc \foo:n { l_ #1 _tl }

or if I wanted to be pedantic perhaps one of

    \exp_args:Nx \foo:n { \exp_not:c { l_#1_tl } }
    \exp_args:Nf \foo:n { \exp_args:Nc \exp_stop_f: { l_#1_tl } }

**Comment by eg9** [comment]
> On 26 Nov 2017, at 14:52 , Frank Mittelbach <notifications@github.com> wrote:
> 
> > Actually I remember someone was actively using that 
> > |\cs_generate_variant:Nn \foo:n { c }| works (personally I find such 
> > code bad). 
> 
> bad code in probably most cases, but it is a bit more defensible imo. 
> After all
> 
> \foo:n { \l_bar_tl }
> 
> would be perfectly legal, so
> 
> \foo:c { l_ #1 _tl }
> 
> could be a use case.

I don’t think so: this should be one of

\foo:V \l_bar_tl
\foo:v { l_#1_tl }

Ciao
Enrico

**Comment by blefloch** [comment]
@eg9 I think Frank's point was to feed `\foo:n` the single-token token list consisting of the control sequence `\l_bar_tl` (which happens to be a token list), not the contents of the token list (most common use-case, for which you provide correct code).

**Comment by eg9** [comment]
> On 26 Nov 2017, at 17:59 , Bruno Le Floch <notifications@github.com> wrote:
> 
> @eg9 <https://github.com/eg9> I think Frank's point was to feed \foo:n the single-token token list consisting of the control sequence \l_bar_tl (which happens to be a token list), not the contents of the token list (most common use-case, for which you provide correct code).
> 
I'm not sure what a use case for that should be. We are distinguishing between N and n on purpose,
aren’t we?

Ciao
Enrico

**Comment by blefloch** [comment]
@eg9 The use case for changing `n` to `N` or `c` is rare and not clear, doable with the `x`-type or `f`-type expansion as outlined above.

I'll try in the next few days to commit code that

1. only allows to change `N` to `c` and only allows to change `n` to one of `V`, `v`, `o`, `f`, `x`,
2. otherwise allows any argument to remain unchanged (as currently done) except `w` and `p`,
3. trim trailing arguments that are the same in both base and variant,
4. of course forbids making the signature longer.

For instance in the following the first three would be allowed and the last three forbidden

    \cs_generate_variant:Nn \foo:Nn { Nn }
    \cs_generate_variant:Nn \foo:nNN { nNc }
    \cs_generate_variant:Nn \foo:VnonTF { VnoxT }
    \cs_generate_variant:Nn \foo:Npn { Npo }
    \cs_generate_variant:Nn \foo:Nn { oc } % forbidden for two reasons
    \cs_generate_variant:Nn \foo:nn { nonono }

The only difference compared to the current status is to forbid `n` to `N` or `c` and `N` to `n`, `V`, `v`, `o`, `f`, `x`.

**Comment by blefloch** [comment]
It turns out it's easier to put out an error rather than just a warning.  Should I do that, or is it very important to make this (changing N to n or vice-versa or their variants) a warning for a couple of release?

**Comment by blefloch** [comment]
I have code that makes this an error, but clearly some people were using the old behaviour, as running the contrib tests gives me the error

    Variant form 'c' invalid for base form '\zhnum_int:n'

when reading `zhnumber.sty`, and similar errors in xeCJK, where some `c`-type args should be `v`.  I'll try to reduce the error to a warning in such cases.

**Comment by josephwright** [comment]
We should put in pull requests :)

**Comment by FrankMittelbach** [comment]
> We should put in pull requests :)

may not be a bad idea, but doesn't quite solve the problem I guess.

**Comment by FrankMittelbach** [comment]
I have a bit of a problem with this one:

> |\cs_generate_variant:Nn \foo:VnonTF { VnoxT }|

in my opinion that is invalid as it should have been

|\cs_generate_variant:Nn \foo:nnonTF { VnoxT }|

ie  V is not a base function specifier.

**Comment by FrankMittelbach** [comment]
> I now think we should forbid n→c. It is pretty common to have a function 
> |\tl_foo:N| and another |\tl_foo:n| that operate on token lists (in the 
> first case on the contents of a variable) so allowing to generate c 
> variants of n-type args can become confusing. For instance |\tl_count:c| 
> is not the c-variant of |\tl_count:n| but of |\tl_count:N|.

ok agreed but then we should document that and also explain what to do, ie:
> 
> For the case Frank gives I think I would write
> 
> |\exp_args:Nc \foo:n { l_ #1 _tl } |

don't think "pedantic" version is really appropriate :-)

**Comment by blefloch** [comment]
I now have code that only produces warnings for `n` to `c` and `N` to `o` (also used by xeCJK) and errors for other erroneous cases.  We can easily add more warning-only cases.  Should I push?

> I have a bit of a problem with this one:
    |\cs_generate_variant:Nn \foo:VnonTF { VnoxT }|
    in my opinion that is invalid as it should have been
    |\cs_generate_variant:Nn \foo:nnonTF { VnoxT }|
    ie  V is not a base function specifier.

I agree but there may be cases where some other package writer has only defined `\foo:on` and one wants `\foo:oo`, and it seems slightly more friendly to allow it.  I don't really mind either way but I would have to reshuffle the code yet a bit more.  I'd rather stop.

**Comment by eg9** [comment]
> On 27 Nov 2017, at 22:30 , Bruno Le Floch <notifications@github.com> wrote:
> I agree but there may be cases where some other package writer has only defined \foo:on and one wants \foo:oo, and it seems slightly more friendly to allow it. I don't really mind either way but I would have to reshuffle the code yet a bit more. I'd rather stop.
> 

If there is `\foo:on` there should also be `\foo:nn`, so the next variant should be

    \cs_generate_variant:Nn \foo:nn { oo }

Ciao
Enrico

**Comment by blefloch** [comment]
Ah, now I know why I did it that way: to avoid complaining about trailing `T` or `F` (see #100) we need to allow variants that "change" `T` to `T` or `F` to `F`, and we also need that for `n` or `N` and that started to be enough args that I figured I might as well allow all of them rather than hard-code a list.

**Comment by aparsloe** [comment]
For the record, there are at least three further packages (in addition to zhnumber.sty) available on MiKTeX which generate a c variant from an n argument, and one which generates n from N. 

This discussion makes clear to me that I have been sinning badly, happily converting N arguments to o or V variants. Some expanded documentation around this issue would be helpful.

**Comment by FrankMittelbach** [comment]
> This discussion makes clear to me that I have been sinning badly, 
> happily converting N arguments to o or V variants. Some expanded 
> documentation around this issue would be helpful.

agreed that might be worth a small article in TUB (and/or for sure in 
l3news)

**Comment by wspr** [comment]
For the record, in the distant past we did have `O` (and others?) which was like `o` except the results were passed along as a single token instead of a braced list. I don't think I was part of the discussion when they were dropped.

I guess some people might come up with use cases like:

    \tl_set:Nx \l_foo_pointer_tl { \exp_not:c { l__foo_dynamic_#1_tl } }
    ...
    \tl_set:On \l_foo_pointer_tl {...}

But is this any better than

    \tl_set:cn { l__foo_dynamic_#1_tl } {...}

? Maybe if you didn't want the construction of the `l__foo_dynamic_#1_tl` to be littered all through the code, it would be clearer to have `\tl_set:On` form instead.

I'm not arguing we need to change anything here, but I think discussions around use cases are important even now when we perceive the expl3 argument specifiers to be quite mature.

**Comment by blefloch** [comment]
In view of @aparsloe's comment, what cases should I down-grade to warnings?  I suppose all conversions from N or n to N,n,c,o,V,v,f,x?

In a previous commit I've at least added some explanation to `\cs_generate_variant:Nn`.

**Comment by eg9** [comment]
> On 28 Nov 2017, at 12:44, Will Robertson <notifications@github.com> wrote:
> 
> For the record, in the distant past we did have O (and others?) which was like o except the results were passed along as a single token instead of a braced list. I don't think I was part of the discussion when they were dropped.
> 
> I guess some people might come up with use cases like:
> 
> \tl_set:Nx \l_foo_pointer_tl { \exp_not:c { l__foo_dynamic_#1_tl } }
> ...
> \tl_set:On \l_foo_pointer_tl {...}
> 
> But is this any better than
> 
> \tl_set:cn { l__foo_dynamic_#1_tl } {...}
> 
> ? Maybe if you didn't want the construction of the l__foo_dynamic_#1_tl to be littered all through the code, it would be clearer to have \tl_set:On form instead.
> 
> I'm not arguing we need to change anything here, but I think discussions around use cases are important even now when we perceive the expl3 argument specifiers to be quite mature.

Instead of littering `l__foo_dynamic_#1_tl` all through the code, the programmer should do

    \cs_new_protected:Nn \__foo_dynamic_tl_set:nn
     {
      \tl_set:cn { l__foo_dynamic_#1_tl } { #2 }
     }
    \cs_generate_variant:Nn \__foo_dynamic_tl_set:nn { V }


    \__foo_dynamic_tl_set:nn { xyz } { ... }
    \__foo_dynamic_tl_set:Vn \l_foo_pointer_tl { ... }

assuming that `\l_foo_pointer_tl` points to `xyz` (no need to load it with the whole name).
Other strategies are possible.

Ciao
Enrico

**Comment by wspr** [comment]
That is a cleaner approach! I'm convinced we're on the right track here. Thanks Enrico!

**Comment by blefloch** [comment]
Should `\cs_generate_variant:Nn \foo:NNw { ccw }` be allowed?  After all, including the trailing arguments that agree between the base and variant doesn't affect the resulting definition, so I could imagine a coding style that prefers explicitly writing the whole variant signature every time.

**Comment by wspr** [comment]
`{ ccw }` would be nice to have, but if it's easier to just detect when `w` is appearing and print a sensible error message like *`w` is not supported; if you have trailing `w` arguments omit them* that would be understandable I think.
