### ISSUE TITLE
Foreign internals: avoid using internals of other expl3 modules

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#419]
Here is a list of control sequences (for variables the leading `\g` or `\l` or `\c` is stripped) that are used in the "wrong" module, with the (approximate) number of times they are used.
```
__alloc_attribute_int
__alloc_bytecode_int
__alloc_chunkname_int
__alloc_whatsit_int
__char_generate:nn (x7)
__chk_if_free_cs:N or :c (x24)
__chk_if_free_msg:nn (x3)
__clist_wrap_item:n
__color_current_tl (x4)
__cs_generate_variant_loop_warning:nnxxxx (x2)
__cs_parm_from_arg_count:nnF
__cs_split_function:NN (x4)
__cs_tmp:w (x2)
__deprecation_minus_one (x4)
__dim_eval:w (x24)
__dim_eval_end: (x20)
__driver_box_use_clip:N
__driver_box_use_rotate:Nn
__driver_box_use_scale:Nnn
__driver_color_pickup:N
__driver_color_reset:
__driver_color_select:V
__file_base_name_str (x3)
__file_full_name_str (x14)
__file_internal_ior (x2)
__file_missing:n (x3)
__file_name_sanitize:nN (x3)
__fp_rand_size_int (x6)
__image_ (x16)
__image_decode_tl (x13)
__image_extract_bb:n (x4)
__image_interpolate_bool (x9)
__image_llx_dim (x3)
__image_lly_dim (x3)
__image_page_int (x15)
__image_pagebox_tl (x14)
__image_read_bb:n (x2)
__image_tmp_box (x6)
__image_urx_dim (x6)
__image_ury_dim (x9)
__image_utx_dim
__int_eval:w (x309)
__int_eval_end: (x51)
__int_to_roman:w (x7)
__int_value:w (x427)
__intarray_gset_fast:Nnn (x19)
__intarray_item_fast:Nn (x19)
__intarray_new:Nn (x8)
__ior_list:Nn
__ior_open:No (x2)
__iow_with:Nnn (x6)
__kernel_register_log:N or :c (x7)
__kernel_register_show:N (x5)
__max_constdef_int (x4)
__msg_coding_error_text_tl (x6)
__msg_kernel_error:nn or variants (x89)
__msg_kernel_expandable_error:nn (x49)
__msg_kernel_fatal:nn (x2)
__msg_kernel_new:nnn or :nnnn (x85)
__msg_kernel_warning:nn or variants (x12)
__msg_log_next: (x24)
__msg_show_item:n (x3)
__msg_show_item:nn (x2)
__msg_show_item_unbraced:nn (x4)
__msg_show_pre:nnxxxx (x7)
__msg_show_variable:NNNnn (x14)
__msg_show_wrap:Nn (x6)
__msg_show_wrap:n (x16)
__prg_break: (x22)
__prg_break:n (x5)
__prg_break_point: (x22)
__prg_break_point:Nn (x22)
__prg_case_end:nw (x6)
__prg_compare_error: (x10)
__prg_compare_error:Nw (x6)
__prg_map_ (x15)
__prg_map_break:Nn (x15)
__prg_map_int (x39)
__quark_if_recursion_tail_break:NN (x3)
__quark_if_recursion_tail_break:nN (x4)
__scan_new:N (x10)
__seq (x6)
__seq_item:n (x8)
__skip_if_finite:wwNw (x3)
__stop (x10)
__stop:w (x2)
__str_analysis_map_inline:nn
__str_if_eq_x:nn (x11)
__str_if_eq_x_return:nn (x2)
__str_to_other_fast:n (x4)
__tl (x43)
__tl_act_mark (x2)
__tl_act_stop (x2)
__tl_analysis_from_str_map_inline:nn
__tl_analysis_map_inline:nn (x4)
__tl_build:Nw (x8)
__tl_build_end: (x10)
__tl_build_one:n or variants (x46)
__tl_build_x:Nw
__tl_gbuild:Nw (x2)
__tl_gbuild_x:Nw (x2)
__tl_if_empty_return:o (x2)
__tl_trim_spaces:nn (x4)
__unicode_ (x5)
__unicode_I_ogonek_tl (x3)
__unicode_accents_lt_tl (x4)
__unicode_codepoint_to_UTFviii:n (x6)
__unicode_codepoint_to_UTFviii_auxi:n (x3)
__unicode_codepoint_to_UTFviii_auxii:Nnn (x5)
__unicode_codepoint_to_UTFviii_auxiii:n (x8)
__unicode_dot_above_tl (x4)
__unicode_dotless_i_tl (x5)
__unicode_dotted_I_tl (x3)
__unicode_final_sigma_tl (x5)
__unicode_i_ogonek_tl (x3)
__unicode_lower_ (x2)
__unicode_mixed_ (x2)
__unicode_std_sigma_tl (x4)
__unicode_upper_ (x2)
__unicode_upper_Eszett_tl (x4)
__use_none_delimit_by_s (x2)
```

**Comment by blefloch** [comment]
The most used offender is `\__int_eval:w`, mostly used in the `fp` module.  For this we could either use the primitive, or do `\cs_new_eq:NN \__fp_int_eval:w \etex_numexpr:D` at the beginning of the module.

The harder cases are things like `\__msg_kernel_new:nnnn`, which rely on complicated functions in `l3msg` and which we probably should keep internal in some way.  Perhaps calling it `\kernel_...` would help avoid people using it?

**Comment by FrankMittelbach** [comment]
> The harder cases are things like |\__msg_kernel_new:nnnn|, which rely on 
> complicated functions in |l3msg| and which we probably should keep 
> internal in some way. Perhaps calling it |\kernel_...| would help avoid 
> people using it?

Would it make sense to call those generally

|\__kernel_|

i.e., clearly keep the internal state by using |\__| but indicate that 
it is a cross kernel internal by calling it "kernel" and not "<module>".

**Comment by blefloch** [comment]
I like it.  It should work for most or even all of the examples I can think of.

**Comment by FrankMittelbach** [comment]
let's hear what others think but I think i could give us the best of two worlds and it fairly clear and easy understandable. If we do it I think we should keep the definitions within the individual modules (since there it is easier to to understand).  The index would then bring all together.

**Comment by wspr** [comment]
+1 for a `kernel` module name

**Comment by josephwright** [comment]
Fine with me (more or less my thinking too), though we should ensure that we check which names are moved. For example, I suspect much of the driver stuff I've written could be documented and public.

BTW, we probably need an `l3doc` option to ignore the relevant internal names within modules where it's 'allowed' (could be done by hard-coding the list of kernel `@@` prefixes).

**Comment by eg9** [comment]
> On 3 Dec 2017, at 21:16 , Frank Mittelbach <notifications@github.com> wrote:
> 
> let's hear what others think but I think i could give us the best of two worlds and it fairly clear and easy understandable. If we do it I think we should keep the definitions within the individual modules (since there it is easier to to understand). The index would then bring all together.
> 
Fine with me. Reserved for use in the kernel. :-)

Ciao
Enrico

**Comment by FrankMittelbach** [comment]
> Fine with me (more or less my thinking too), though we should ensure 
> that we check which names are moved. For example, I suspect much of the 
> driver stuff I've written could be documented and public.

my proposal is to *not* make it public but to keep this an internal 
"module" with all commands internal, i.e., all having \__kernel_

it should probably be documented in interface3 as people looking at the 
code will see it more often and in some sense out of context but in the 
sections "Internal commands" under each module.

if you have a public command then it can stay in its module and use the 
module name in my opinion.

**Comment by blefloch** [comment]
Rather than moving everything to `\__kernel_...` in bulk we may want to take advantage of the transition to also turn some of them into public interfaces. (I think Joseph's point was that.)

The hard part remaining is the use of these kernel commands in `l3packages` and `l3experimental` (and to a lesser extent `l3trial).  There are some cases of `\__msg_show_...` for nice display of datatypes; I should look into making the interface better and make it public.

**Comment by josephwright** [comment]
@blefloch Yes, that's what I was getting at: before moving these things to a new 'internal' place, we should be sure that they really are 'team only'.

**Comment by FrankMittelbach** [comment]
no disagreement, of course we should in each case decide if the command warrants becoming generally public rather than just kernel internal. When public they should keep module names if internal they should move to |\__kernel_|.

**Comment by josephwright** [comment]
Cool: I think we can start on the work then.

**Comment by blefloch** [comment]
Here are my findings about some packages (outside l3kernel,
l3experimental, l3trial) using our internals or things that look like
our internals.

1. \__msg_show_variable:NNNnn and \__msg_show_item:nn in pml3array.  We
should make these public (slightly modified, I'll do it now).

2. xunicode-addon.sty and the ctex bundle use \l__kernel_expl_bool to
know the \ExplSyntaxOn status.  We should make it public.

3. \g__prg_map_int (spath3.sty (very incorrectly!), pml3array).  We
should provide an interface to the infrastructure underlying map_inline.

4. peek internals (xeCJK.sty, siunitx.sty).  Can we give an interface?

5. prop internals in lt3graph.sty  Can we give an interface?

6. \l__keys_module_tl in xeCJK.sty to conditionally complain about
unknown keys.  Can we give an interface?

7. l3doc internals __codedoc_ in ctxdoc.cls  Can we give an interface?

8. \__dim_eval:w in fontspec-xetex.sty, fontspec-luatex.sty could be
avoided using l3fp

9. \__int_value:w and \__int_eval:w are used in flexisym.sty (could be
replaced by using \exp_stop_f:), ebproof.sty (could be replaced by
\int_eval:n), unravel.sty (should be replaced by the primitive)

10. prop internals in spath3.sty that could be replaced using
\prop_get:NnNTF

11. \c__keys_code_root_tl in ltxmdf.cls (to re-make it public but then
do nothing with it?)

12. sseqmessages.code.tex hooking in l3msg internals... they could've
just as well included their extra stuff in the text of their messages
without any loss of functionality instead,

13. sseqmacromakers.code.tex, sseqparsers.code.tex,
sseqcheckdefinitions.code.tex abuse xparse

14. the xltxtra.sty package uses __xetex as its prefix,

15. \l__file_contents_iow (xsim.verbwrite.code.tex) should change name.

**Comment by josephwright** [comment]
@blefloch  I'm not sure all of these should be public. For example

- `siunitx` uses `peek` internals as currently public  `peek` functions can't be used anywhere that already applies the Appendix D trick
- I don't see the need to know about ` \c__keys_code_root_tl`
- Similarly for `\__kernel_expl_bool`,` \g__prg_map_int`, _etc._: I think we need to look at this case-by-case and see what _exactly_ is needed (if anything)

**Comment by FrankMittelbach** [comment]
Am 04.12.2017 um 18:44 schrieb Joseph Wright:
> @blefloch <https://github.com/blefloch> I'm not sure all of these should 
> be public. For example
> 
>   * |siunitx| uses |peek| internals as currently public |peek| functions
>     can't be used anywhere that already applies the Appendix D trick

that sounds like there is an interface missing

>   * I don't see the need to know about |\c__keys_code_root_tl|

yes would like to see the exact use case and if that is valid then we 
may find that it is better served by an interface not by exposing such 
internal

>   * Similarly for |\__kernel_expl_bool|,|\g__prg_map_int|, /etc./: I
>     think we need to look at this case-by-case and see what /exactly/ is
>     needed (if anything)

maybe it pays off to split your list out into individual issues (label 
third-party), figure out what's the real underlying use case and how 
that is best served and if it is by changing the package code then push 
that to the owner of the package (not sure that is possible on github to 
assign outside of the team, but if necessary we can then mail the owner

frank

**Comment by josephwright** [comment]
Now done (bar one deprecated function which will therefore vanish) in `l3kernel`.
