### ISSUE TITLE
Is there a LaTeX3 equivalent for \kern?

### ISSUE THREAD

**Issue by Vidabe** [latex3/latex3#421]
Maybe I am missing it, but is there are LaTeX3 equivalent for `\kern`? I would like to add a space using a `dim`, but cannot find a kernel command for that purpose. (I know that there is `\skip_horizontal:N`, but this are for  `skip` and not `dim`.)

**Comment by josephwright** [comment]
At present 'no'.

**Comment by Vidabe** [comment]
Then, is it ok if I use e.g. `\skip_horizontal:N \l_@@_lentgh_dim` until such a command is introduced?

**Comment by josephwright** [comment]
@Vidabe  If you want a kern, not a skip, at present you'll need to use `\tex_kern:D` or stick to the '2e name' and go with `\kern`. We know this is a gap, we just haven't yet got a feel for the best approach!

**Comment by josephwright** [comment]
We know there is a gap here: closing for the present.
