### ISSUE TITLE
[xparse] "optional token" or "list of options for t type argument"

### ISSUE THREAD

**Issue by dragomang87** [latex3/latex3#424]
The t type argument allows to check for a specific token as in `{ t\foo }`. However it might be useful to have a `T` argument that reads any token or allowing  `t` to match a list of tokens as in `{ t{char1,char2, ..., charN} }`.

Use case: see for example the `physics` package implementation. To check for manual sizing, the internal fuctions are defined with options like `{ t\big t\Big t\bigg t\Bigg ... }` forcing a long cascade of `\IfBooleanTF`. (And incidentally allowing the counterintuitive syntax of `\quantity\big\Big\Bigg(foo)` that ignores all but one of the sizes)

PS: the documentation of `t` makes it sound like only a single one character is allowed, as if it were a generalization of `s` to any character.

PPS: I can't seem to figure out how to add the enhancement tag.

**Comment by eg9** [comment]
I have considered the same idea, although not in connection with `physics`, for which a standard optional argument would be much better.

There is `E`, but it's not the same thing as you propose.

**Comment by FrankMittelbach** [comment]
@dragomang87 on PPS: labels ie classifications can only be added if one has write access the code base (that's the way github seems to function)

**Comment by FrankMittelbach** [comment]
The intention of the `t` specifier was indeed to be a generalization of the `s` specifier to allow for using something like a "!"  as an additional marker. Note that it returns a boolean so testing for novalue doesn't get you anywhere. What you seem to be after (with several tokens) is  different as you want more than just knowing that any of the following tokens was present (yes/no), right?

What you want, if I understand it correctly, is:  having a single optional token but with a restricted set of allowed values, e.g., something like `X{\foo\bar\baz}` returning either `\foo`,  `\bar` or `\baz` or `\NoValue` (and not removing the next token if it is neither of them.

Not sure that really fits the design ideas behind xparse  and the general philospophy how LaTeX commands are constructed (and after all the next question then is why single tokens why not words ... where do you end here?) ... guess, we'll have to think about that further.

**Comment by wspr** [comment]
The more I think this through the more I think it's a good idea in that it fits with the other options we provide -- it would be like a complement to `g` (although I know some don't like that one as it is...).

Thinking through the implementation, it would have to use a `\futurelet` approach, so declaring the allowed tokens up front is necessary so the logic is all packaged up within the argument processing.

Regard the OP's comment: 

> (And incidentally allowing the counterintuitive syntax of \quantity\big\Big\Bigg(foo) that ignores all but one of the sizes)

This should be overcome by having a boolean that is set the first time one of those `t` options is seen and calling an error with that boolean the next time.

**Comment by dragomang87** [comment]
@FrankMittelbach yes, as you point out it cannot be a boolean argument. Yes, the `X` option is exactly what I was thinking about. Regarding where you draw the line: the same way `t` does, as it seems to accept a subset of the possible strings that includes tokens, which led me to wrongly propose `t`.

Is it clear what strings `t` accepts? or is accepting tokens an unpredicted feature?

@eg9 I think the doc for `e` and `E` is not clear either, but if I understand correctly it does limit each embellishment to be a single character, just like `t` is (maybe) supposed to do, right?

**Comment by pablgonz** [comment]
MMM.. It is related to (https://github.com/latex3/latex3/commit/e4def006739bbeb3ff0481dd94bba077f9d544bd)

**Comment by josephwright** [comment]
Closing here as the code has moved: if this still needs work, it can be addressed in the 2e repo.
