### ISSUE TITLE
Missing temporary variables

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#429]
For most datatypes we define temp variables.
At least `\l_tmpa_regex` is missing.

**Comment by FrankMittelbach** [comment]
I guess the general feeling was that they aren't that useful after all (so I think we always warn about them these days). However, since we indeed have sich temps for most datatypes  it would be consistent to provide them here too (with the usual caveat note)

**Comment by blefloch** [comment]
I suppose we should also include \g_tmpa_ior, \g_tmpb_ior, \g_tmpa_iow,
\g_tmpb_iow?  (Global because all ior/iow are global because of TeX.)

**Comment by wspr** [comment]
Alternatively we could remove all temp variables? But that is probably a bit disruptive. So I guess I agree having one or two (?) tmp variables per datatype probably makes sense for consistency.
