### ISSUE TITLE
Provide a test for output mode

### ISSUE THREAD

**Issue by josephwright** [latex3/latex3#43]
In [issue 32](https://github.com/latex3/svn-mirror/issues/32) the point was made that using pdfTeX as an engine is not the same as PDF output. We don't currently have a test for the later. I'm not clear on whether we'll want one long-term (this depends on how output mode is selected), but we should perhaps have something at least in package mode. `\mode_if_output_pdf:(TF)` might fit with other names we currently use.

**Comment by josephwright** [comment]
Collect potential use cases

**Comment by josephwright** [comment]
See also https://github.com/latex3/svn-mirror/issues/233: at present the working name (in my head!) is something like `\runtime_if_output_pdf:(TF)`/`\runtime_if_output_dvi:TF`, dependent on final decision on module name here and what people think about the 'payload' naming.

**Comment by blefloch** [comment]
Fixed by Joseph some time ago: the output tests are `\sys_if_output_dvi:TF` and `\sys_if_output_pdf:TF`.
