### ISSUE TITLE
`no_value` or `novalue`

### ISSUE THREAD

**Issue by stone-zeng** [latex3/latex3#435]
In `l3quark`,  the macros are like `\q_no_value`, `\quark_if_no_value:NTF` etc, but in `l3tl` there are `\c_novalue_tl`, `\tl_if_novalue:nTF` etc. Why the names are not unified?

**Comment by josephwright** [comment]
The two have separate history and use separate underlying approaches. In the quark module, `\q_no_value` is purely a marker (attempting to typeset it leads to infinite recursion). As with all quarks, it is designed to offer a fast way to do testing at a low level. In `l3tl`, 'novalue' is a special token list which _can_ be typeset and also can be tested for presence, but which is not 'accidentally' going to appear in user input. It offers a different test: it's slower than the quark approach but is 'safer' (and better suited to higher-level code). So the two ideas are not exactly interchangeable. On the 'historical' front, it's worth noting that the `tl` approach has always been called 'NoValue' (or similar), even when the marker was internal.

Now, one can argue that we could alter one or other name (more likely the `tl` one as it's newer).

**Comment by Stone-Zeng** [comment]
I think it's better to seperate all the words, i.e. `\tl_if_no_value:nTF`.

**Comment by FrankMittelbach** [comment]
@josephwright seeing them side by side I do feel @Stone-Zeng has a good point.  `\c_novalue_tl` is really interfacing to the xparse level so it may make sense to consider a deviation from the normal expl3 convention and calling those `\c_NoValue_tl` (which some appropate documentation explaining why).

**Comment by josephwright** [comment]
@FrankMittelbach I do see the point: my original thought was to go with `\c_no_value_tl` :) I think we ended up as we are there as we are trying to cut down 'odd' names (ones where we elide having `tl` in twice). I'm not sure `\c_NoValue_tl` really helps here: it's the same issue, more-or-less, isn't it?

**Comment by FrankMittelbach** [comment]
@josephwright well, the "novalue" in `\c_novalue_tl` doesn't mean that this constant does not contain a value (which would be `\c_empty_tl`) but that it contains a "special marker" used to indicate that a higher-level protocol had  been given "No Value". So my thought is it is not quite on the same level as `\q_no_value` which is a marker not contains one (well it does contain itself, but that another story :-) )

But for the unsuspecting reader of code it kind of reads as if that tl has no value. Maybe I'm overinterpreting things here, but  `\c_NoValue_tl` or even `\c_NoValue_indicator_tl` ties it much better to the higher-level exparse interface (or any other future module that provides an interface on that level).

**Comment by wspr** [comment]
It would get a bit confusing with both `\q_no_value` and `\c_no_value_tl` given that they don’t actually have anything to do with each other! So I would favour distinct names. Exactly what those names should be, though, is a trickier one...

**Comment by eg9** [comment]
> On 5 Jan 2018, at 16:41 , Will Robertson <notifications@github.com> wrote:
> 
> It would get a bit confusing with both `\q_no_value` and `\c_no_value_tl` given that they don’t actually have anything to do with each other! So I would favour distinct names. Exactly what those names should be, though, is a trickier one…

I’m with Will on this. The \q_no_value quark is returned as a result from operations that would otherwise
yield an undefined result (popping from an empty sequence, for instance).

The (contents of the) \c_novalue_tl token list is delivered as an expected result when
an optional argument is not present.

Maybe the name of the latter is badly chosen. On the other hand, I still
believe that we should have \xparse_if_novalue:nTF and \c_xparse_novalue_tl,
that is, the two should be part of xparse rather than the kernel.

Ciao
Enrico

**Comment by Stone-Zeng** [comment]
> Maybe the name of the latter is badly chosen. On the other hand, I still
believe that we should have \xparse_if_novalue:nTF and \c_xparse_novalue_tl,
that is, the two should be part of xparse rather than the kernel.

Agree with it too.

**Comment by FrankMittelbach** [comment]
well I don't. I consider  having the user interface level returning `-NoValue-`  (it what is currently inside `\c_novalue_tl`) a general concept. That concept is currently only implemented by `xparse`, true, but that doesn't make it an xparse-concept.  You can easily envision a different top-level interface that passes its parsing results to the kernel for further processing. and at the kernel level there should then be only a single interface. In other words two different UI interfaces should be able to pass their result to a single kernel or package function and that means the kernel should provide a way to deal with the UI returning "no value in this arg".

**Comment by FrankMittelbach** [comment]
Instead of xparse as a prefic we could of course think of this as kernel user interface support and call it `\c_ui_novalue_tl` or some other name but I don't like xparse here as that is the UI for a LaTeX2e look and feel interface.
