### ISSUE TITLE
[xparse] Feature Request: Provide NoValueMarker

### ISSUE THREAD

**Issue by e-kwsm** [latex3/latex3#436]
At present `\BooleanTrue` and `\BooleanFalse` literals are provided by xparse, while `-NoValue-` marker not:

https://github.com/latex3/latex3/blob/a8c344a0633ff673a512f5e02652ab449bab3eef/l3packages/xparse/xparse.dtx#L488-L494

Do you have a plan to provide it, or how to use it explicitly?
The `-NoValue-` marker will make it easy to implement an underlying function with variable arguments. 

---

* TeX Live 2017
* expl3 2017/12/16 L3 programming layer
* xparse 2017/12/16 L3 Experimental document command parser
* (engine-independent)

**Comment by blefloch** [comment]
We added `\c_novalue_tl` to `l3tl` somewhat recently.  Note that it's a bit different than for `\BooleanTrue` and `\BooleanFalse` as those can be directly passed as arguments to `\IfBooleanTF` while one needs to pass the expansion of `\c_novalue_tl` (e.g. obtained using `\exp_args:No`) to `\IfValueTF`.

**Comment by e-kwsm** [comment]
> one needs to pass the expansion of <code>\c_novalue_tl</code> (e.g. obtained using <code>\exp_args:No</code>) to <code>\IfValueTF</code>.</p>

I'm sorry but I'm new to expl3. Would you show me how to expand `\c_novalue_tl` by `\exp_args:No`?

**Comment by wspr** [comment]
All Bruno means here is that the “no value” marker is stored within \c_novalue_tl. It would be unlikely you’d actually want to use its contents for anything directly (I think). To use a contrived example,

    \exp_args:No \IfNoValueTF \c_novalue_tl {true} {false}

would evaluate to “true”, always.

Where I am guessing \c_novalue_tl would be useful are situations like this:

     \NewDocumentCommand \foo { o m }
       {
         \tl_set:Nn \l_foo_oarg_tl {#1}
         \tl_set:Nn \l_foo_marg_tl {#2}
         \foo_aux:
       }

     \cs_new_protected:Npn \foo_aux:
       {
         \tl_if_eq:NNTF \l_foo_oarg_tl \c_novalue_tl
           { true } { false }
       }

You might ask why not just pass in #1 as an argument and then use \IfNoValueTF, but we discourage mixing programming layers — the definition of \foo is in the “xparse layer” and should contain minimal expl3 programming.

The definition of \foo_aux: is in the “expl3 layer” and should avoid as much as possible using the “xparse layer”. Where mixing is needed indicates that either the code is a bit jumbled, or that expl3+xparse have missed something in their approach for the particular problem you’re trying to solve.

**Comment by e-kwsm** [comment]
Thank you for clear examples!
