### ISSUE TITLE
xparse and l3kernel not synced

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#441]
After TeX Live 2017's update this morning, the following MCE:
```latex
\documentclass{article}
\usepackage{xparse}
\begin{document}
Foo.
\end{document}
```
failed to (`pdflatex`) compile with the error:

>! Package xparse Error: Support package l3kernel too old.

BTW, also the following warning is emitted:

>LaTeX Warning: You have requested, on input line 26, version`2018/02/21' of package expl3, but only version `2017/12/16 L3 programming layer (loader) ' is available.

Here is my File list:
 ```
*File List*
 article.cls    2014/09/29 v1.4h Standard LaTeX document class
  size10.clo    2014/09/29 v1.4h Standard LaTeX file (size option)
  xparse.sty    
   expl3.sty    2017/12/16 L3 programming layer (loader) 
expl3-code.tex    2017/12/16 L3 programming layer 
l3pdfmode.def    2017/03/18 v L3 Experimental driver: PDF mode
 ***********
```

**Comment by Stone-Zeng** [comment]
On CTAN, `l3kernel` and `l3packages` (including `xparse`) may not be updated at the same time. So you can wait for several days, when all the LaTeX3 packages are updated.

**Comment by dbitouze** [comment]
>On CTAN, l3kernel and l3packages (including xparse) may not be updated at the same time.

IMHO, they should be: currently, all the documents that (directly or indirectly) make use of `xparse` cannot be compiled and that may be critical!

**Comment by josephwright** [comment]
Everything went to CTAN as usual at the same time. Unfortunately, neither the LaTeX team nor CTAN control how packages are then added to TeX Live/MiKTeX. Occasionally it happens that only one of the updates gets picked up: most likely this is because there are very minor differences in when things actually change, and that crosses a 'cutoff' point for TL updates.

**Comment by josephwright** [comment]
@davidcarlisle  This already happens: I mean 'picked up' by the TeX Live/MiKTeX processes

**Comment by FrankMittelbach** [comment]
@dbitouze what you ask for Denis is all already done, ie  getting messages to CTAN people (and they know that things have to go together and that they have to be careful with that --- and they are).
But even then they can't  make the bundles appear at precisely the same moment on CTAN (if done by a single person there are a few minutes or possible hours between the installs)

Anyway it was carefully done yesterday:

kernel install 22:24
xpackages install 22:40
experimental install  22:53

But as Joseph said, neither we nor them control how packages get integrated (by automatic?) means into TL and MikTeX and it seems that in this case TL only picked up  xpackages so in some sense wrong place to complain I would say

**Comment by dbitouze** [comment]
@FrankMittelbach Okay. Sorry if I may have offended you, it was not my aim : I was just stressed by a document that _had to compile_ this morning. But I could manage by restoring `l3packages` to its previous version  :)

**Comment by FrankMittelbach** [comment]
Am 23.02.18 um 09:05 schrieb Denis Bitouzé:
> @FrankMittelbach <https://github.com/frankmittelbach> Okay. Sorry if I 
> may have offended you, it was not my aim : I was just stressed by a 
> document that /had to compile/ this morning. But I could manage by 
> restoring |l3packages| to its previous version :)

nobody is offended, it is just that we aren't really in control here 
beyond what what we already do as far as I can see

I guess we do see your problem but there is no obvious solution to it at 
least not any that I can see.

We could perhaps send l3kernel first then way a few days then ... but 
that isn't  necessarily workable either, sometimes all 3 really need to 
go together and if for some reason in the TL mirrors only one or 2 end 
up (as it seems to be the case today then ...)

btw I replayed your scenario here and my mirror had the same issue  (but 
worse than in your scenario trying the backup made TLmanager die on my 
Mac so I had to reinstall l3 code from github (which fortunately I can 
do fairly easily)

**Comment by dbitouze** [comment]
After this morning update, everything is fine.
