### ISSUE TITLE
\iow_wrap:nnnN and non-printable bytes in pdfTeX

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#451]
When pdfTeX prints a message to the terminal (and not any time earlier in the processing, such as in \detokenize) characters with character code from 0 to 31 are output in the three character notation `^^@` etc. (There are a couple exceptions, such as `^^J`.)  For pdfTeX line-wrapping purposes these count as three characters, while `\iow_wrap:nnnN` cannot know about them and treats them as a single character.  This leads to bad line-wrapping by pdfTeX on top of the `\iow_wrap:nnnN` line-wrapping.

    \RequirePackage{expl3}
    \ExplSyntaxOn
    \char_set_catcode_other:N \^^@
    \iow_wrap:nnnN { \prg_replicate:nn { 54 } { abc ^^@ def ~ } } { } { } \iow_term:n

**Comment by davidcarlisle** [comment]
i wonder if enough terminal are now safe with those characters that we
could ask that texlive change that default. If you use pdflatex -8bit then
the null come through as null

**Comment by josephwright** [comment]
Might make `l3build` normalisation a bit nicer (currently I have to 'flatten' everything to `^^` notation, which makes non-ASCII parts unreadable ...).

**Comment by josephwright** [comment]
I think for `expl3` we leave this alone, and if there is anything to be done it's at the engine level.
