### ISSUE TITLE
`_x` like argument specifier for LuaTeX

### ISSUE THREAD

**Issue by zauguin** [latex3/latex3#452]
Recently `\use_x:n` was added as a wrapper for `\luatex_expanded:D`. I think it would be useful to add a argument specifier to integrate this type of expansion into `expl3`. It could be implemented with

    \cs_new:Npn \::e #1 \::: #2 #3
      {
        \exp_after:wN \__exp_arg_next:nnn \luatex_expanded:D { { #3 } } { #1 } { #2 }
      }

Sadly this has very limited engine support right now.

**Comment by josephwright** [comment]
Actioned in b4f7b630c12757ddcc2710f78b9648c4fa1b02b0: renames of a few functions to follow.
