### ISSUE TITLE
l3doc indexes any macro ending in T or F as a ending in TF

### ISSUE THREAD

**Issue by dcpurton** [latex3/latex3#453]
`l3doc` indexes any macro ending in `T` or `F` as a Boolean macro ending in `TF`. I happened to discover this when documenting a macro ending in `PDF` which was indexed as `PDTF`.

I think it would make more sense for this only to occur only for Expl3 macros ending in `:T` or `:F`.

# MWE

```TeX
% \iffalse meta-comment
%<*driver>
\documentclass{l3doc}
\begin{document}
\DocInput{\jobname.dtx}
\end{document}
%</driver>
% \fi
% \begin{documentation}
% \begin{function}{\TestT, \TestF}
% \end{function}
% \end{documentation}
% \PrintIndex
```

**Comment by josephwright** [comment]
It's not as simple as restricting to `expl3` syntax, as for example one sees `\IfBooleanT`, `\IfBooleanF` and `\IfBooleanTF` in `xparse`. We might need an explicit 'Do not check for a terminal `T` or `F`' switch.

**Comment by blefloch** [comment]
Thanks Joseph for fishing out that cod.  I think `\IfBooleanT` etc form an isolated example, for which it could actually be valuable to index the three variants as separate functions.  So I've added code that skips the replacement when the name does not contain `:`.  Commit soon.
