### ISSUE TITLE
More integer step functions

### ISSUE THREAD

**Issue by Stone-Zeng** [latex3/latex3#454]
Please consider to add the function `\int_step_function:nN` and `\int_step_inline:nn` to step from 1 to some number, with step 1. They will do the same thing as `\int_step_function:nnnN {1} {1} {<number>} <func>` etc, but will be a useful shorthand.

**Comment by josephwright** [comment]
You are almost certainly right: I've wondered about this for ages. I'll add as candidates, but if the rest of the team are happy they can perhaps go almost directly into the core.

**Comment by eg9** [comment]
These are probably the most used cases for `\int_step…`. While this is basically syntactic sugar, we already have something similar such as `\seq_use:Nn <sequence> {<tokens>}` for `\seq_use:Nnnn <sequence> {<tokens>} {<tokens>} {<tokens>}`.

I'm certainly favorable.

**Comment by FrankMittelbach** [comment]
Am 22.04.18 um 10:44 schrieb Enrico Gregorio:
> These are probably the most used cases for |\int_step…|. While this is 
> basically syntactic sugar, we already have something similar such as 
> |\seq_use:Nn <sequence> {<tokens>}| for |\seq_use:Nnnn <sequence> 
> {<tokens>} {<tokens>} {<tokens>}|.
> 
> I'm certainly favorable.

I agree and think they could go directly in

**Comment by josephwright** [comment]
Seems we are agreed here: I'll add shortly (just finalising the documentation).
