### ISSUE TITLE
Provide 'shuffle' functions for seq/tl/clist

### ISSUE THREAD

**Issue by josephwright** [latex3/latex3#456]
As requested in https://tex.stackexchange.com/questions/425589/shuffle-elements-of-a-latex3-sequence, it would be good to be able to shuffle ordered data. This could be done even for XeTeX as it's not expansion-based, but probably we are best sticking with the random number primitive.

**Comment by blefloch** [comment]
What do you have in mind in XeTeX?  Implementing the pdfTeX engine's
random code in LaTeX3 in that case?  (Last time I looked it seemed
reasonably short.)

**Comment by car222222** [comment]
Providing ‘random’ reordering of an interval of integers of length n (probably 1 . . . n) might be useful.

Providing the most efficient method(s) to reorder the various list types may also be wise (but probably not needed in the kernel).

It would not be wise to hide either of these types of utility in any combined code: separation of concerns, please!

**Comment by josephwright** [comment]
@blefloch  I was thinking more-or-less along those lines, though perhaps it's clearer to stick to 'XeTeX can't do random stuff' as a blank position.

**Comment by blefloch** [comment]
Using `\toks` register I have some code that shuffles a sequence 4x faster than all solutions on stackexchange.  The underlying algorithm makes it very easy to provide a `\seq_sample:Nn \l_my_seq { 12 }` that would randomly (uniformly) select 12 different items in the sequence.  This is a pretty common use case, for instance to select 12 exercises out of a database.

A variant that I think I can provide is `\seq_sample:Nnn \l_my_seq { 1234 } { code }` where the code (gets each item index and value and) expands to an integer weight that determines the probability of selecting each item.

Somewhat relatedly we could provide `\seq_pick_items:NN \l_my_seq \g_indices_intarray` that would select the n-th item of `\l_my_seq` for each n in `\g_indices_intarray` in order, then put all of these indices together back into `\l_my_seq`.  This is useful in particular to permute the elements of the sequence.

I think the key is to know what the use cases are.

**Comment by car222222** [comment]
Sampling should also not be tied to each collection type.  A Randonm Sample from integers is a generic idea, not specific to any data type, so should be kept away from any particular type.  Selecting a fixed subsetbkrdering specifiesd by numbers, keys or whatever is not related At all random. Please do not continue to conflate these.

**Comment by blefloch** [comment]
Thank you Chris; however there are two notions in what you write.

- Sampling items from a collection.  Our main "collection" type is
sequences, while clists are mostly meant for input and for interaction
with LaTeX2e.  We document that for more complicated operations
sequences should be preferred.  For instance \clist_sort:Nn just
converts the result of \seq_sort:Nn to a clist.  Should we even have
such convenience functions?

- Sampling from a probability distribution over integers.

I agree that selecting a fixed subset is a different notion (for which
we provide \seq_set_filter:NNn and I'm planning to provide
\seq_set_indexed_filter:NNn).  However, when choosing a random sample it
is useful to want to give more probability to some items than others,
and as a particular case to give zero probability to some, in effect
filtering them out.

**Comment by wspr** [comment]
I agree with Bruno that seq is basically the only data type we should be considering for these higher-level functions, so it makes sense not to decouple the logic. (Which would require a user interface to `intarray`, for a start.)

**Comment by car222222** [comment]
Point well taken about ‘all collections are actually seqs’ (I think we had that conversation before somewhere.)  So agreed, this leaves only the question of whether to obscure this by providing names such as \clist_sort:Nn .

Considering only ‘Sampling items from a collection’ (for this thread), there is an important distinction between 
a: sampling (including non-random selection) based only on the positive integer I call here the ‘index’ (this means the position in the sequence, not any other ‘key’);
b: anything based aso on the sequence ‘entry/value’ at an ‘index’.

If you are considering (only) case b: then I agree the special case of the ‘identity integer sequence, n’ is not important.  

However, having this sequence and case a: as useful special cases could be considered. But these would probably lie best in another module, such as ‘rand’.

 Re: intarray, maybe it (and other arrays) need similar selection/sampling functions?

**Comment by wspr** [comment]
Worth noting at the moment intarray is not public and has a limited set of functionality for (Bruno’s) internal kernel work.

It’s not clear to me if there are ramifications for extending what intarray can do (i.e., whether it’s sensible to advertise it as a public data type). I should probably experiment with using it in unicode-math…

**Comment by josephwright** [comment]
I think we've done this, at least in as far as this issue covers ...
