### ISSUE TITLE
[DOC] unclear explanations for `\use:c`

### ISSUE THREAD

**Issue by jfbu** [latex3/latex3#457]
At https://github.com/latex3/latex3/blob/3bfea2da1e66ed1a71076b436bedc2b96499382c/l3kernel/l3basics.dtx#L710-L714, it is made mention of tokens which must not be active when being fully expanded. Again at https://github.com/latex3/latex3/blob/3bfea2da1e66ed1a71076b436bedc2b96499382c/l3kernel/l3basics.dtx#L710-L714.

This is not clear, how could there be some left-over active tokens after full expansion ? For example, using e-TeX,

```
\catcode`Z \active
\defZ{WWW}
\def\WWWWWW{hello}

\csname \unexpanded{ZZ}\endcsname
```

of course the `\unexpanded` dropped out, and there did not remain an active `Z`, but only its expansion.

**Comment by josephwright** [comment]
Because they could be `\protected`

**Comment by jfbu** [comment]
But

```
\catcode`Z \active

\protected\defZ{WWW}

\csname ZZ\endcsname
```

causes no issue. `\protected` does not work here.

**Comment by jfbu** [comment]
Sure an active token could cause an infinite recursion and should then never be submitted to a `\csname..\endcsname` expansion but that's still something else.

**Comment by blefloch** [comment]
We should document (in `l3expan` and in `l3basics` I suppose) that `c`-expansion expands `\protected` commands.

You can get an active char after expansion using `\exp_not:N` (namely `\noexpand`), but I think that's a more general problem than what the doc of `\use:c` suggests.

**Comment by jfbu** [comment]
ah right, indeed `\noexpand` contrarily to `\unexpanded` can (and will definitely with a control sequence) cause a lowe-level TeX error within `\csname`.

**Comment by jfbu** [comment]
At

https://github.com/latex3/latex3/blob/3bfea2da1e66ed1a71076b436bedc2b96499382c/l3kernel/l3expan.dtx#L619-L621

which documents `\exp_not:n` it could be added that it is without effect in `c` type arguments.
