### ISSUE TITLE
[DOC] a problem in the documentation of `\exp_end_continue_f:w`

### ISSUE THREAD

**Issue by jfbu** [latex3/latex3#458]
The doc

https://github.com/latex3/latex3/blob/3bfea2da1e66ed1a71076b436bedc2b96499382c/l3kernel/l3expan.dtx#L745-L759

is erroneous as this demonstrates:

```latex
\ExplSyntaxOn

\exp_args:NNo \cs_set:Npn \foo: 
{ \exp:w \exp_stop_f: \exp_stop_f: \exp_stop_f: \exp_stop_f:
  \exp_end_continue_f:w \int_use:N \__int_eval:w 3 * 2 . }

\cs_set:Npx \bar: {  \exp_stop_f: \exp_stop_f: \exp_stop_f: \exp_stop_f: }

\show\foo:

\show\bar:
\ExplSyntaxOff
```

The space character tokens are removed by `\romannumeral` prior to the  `` `^^@ ``. Bu these spaces do not leave "empty" contents under "full" expansion.

**Comment by blefloch** [comment]
Thanks, I've made a note in the documentation of `\exp:w` that this behaviour of `\romannumeral` should probably not be relied on.  I don't see a use case where the fact that it ignores spaces (and signs in fact) is important.  Perhaps you see one?

**Comment by jfbu** [comment]
@blefloch I don't see a use case but my experience is limited: my code in xint uses either ``\romannumeral`^^@`` or also ``\romannumeral0`` which is ended by a space token, so I never used naked `\romannumeral`.
