### ISSUE TITLE
Regexpatch typo

### ISSUE THREAD

**Issue by gusbrs** [latex3/latex3#459]
Earlier this year, I faced some trouble with the `regexpatch` equivalents of `xpatch` commands, and was assisted by egreg at TeX.SX (https://tex.stackexchange.com/a/410638/105447). It turned out it was a "hidden feature".

egreg provided then a patch for `regexpatch` and promised a fix later. This was kindly done. 
The patch he then provided is the following:

```
\ExplSyntaxOn
\makeatletter
\exp_args:Nc \xpatchcmd { xpatchbibmacro~code }
 {\xpatch_main:Ncnnnn}
 {\xpatch_main_four:Ncnnnn}
 {}{}
\makeatother
\ExplSyntaxOff
```

However, as I updated to TeX Live 2018, I faced new problems with it. (I checked it was fixed, and dropped the patch, of course).
In examining the package file, I found the changed line and it currently reads:

```
\xpatch_main)four:Ncnnnn \xpatch_patchcmd_once:Nnnnn
```
I'm actually not acquainted with expl3 syntax, but it does not correspond to the patch provided at TeX.SX and it does look a parenthesis is in place of an underscore.

**Comment by car222222** [comment]
What does this mean: “probably INVALID for this database“ ?

**Comment by josephwright** [comment]
@car222222  Well if the bug is in `regexpath` then it's not reportable here, so should be closed with some status.  The standard GitHub labs include 'INVALID', which covers this case. Here, we've actually got one 'NOT-US', which I guess is what can be used.

**Comment by FrankMittelbach** [comment]
think that got fixed so it could be closed -- @eg9 correct?

**Comment by eg9** [comment]
@FrankMittelbach  Correct.

**Comment by gusbrs** [comment]
Thank you very much.

**Comment by car222222** [comment]
@josephwright   I am not so worried about where you put it, but in what you write: please add something that non-githubites can understand.  Also, I was not aware that this was a database in any conventional sense.
