### ISSUE TITLE
xparse: arguments of restricted content

### ISSUE THREAD

**Issue by ajparsloe** [latex3/latex3#465]
This is an enhancement request. I would like to see xparse cope with arguments of restricted content -- e.g. to letters only. If such a letters-only argument were the first argument an appropriate opening delimiter would be a dot (period, full stop). The argument would terminate with the first non-letter encountered -- perhaps a space or * or [ or {. Placed between other arguments, perhaps no delimiters would be needed. 

Such an argument type allows an elegant correspondence between template names (using xtemplate) and document commands. Taking a fanciful example, suppose the object type is "blot" (an essential accompaniment if using a cursive-like font) taking one argument (colour, say):

```\DeclareObjectType { blot } { 1 }```

There is a general specification 
```
\DeclareTemplateInterface { blot} { general } { 1 } 
  { <key type specs> }
```
  
giving rise to an "average" blot using the defaults,

```\DeclareInstance { blot } { oops } { general } { }```

and various specialisations, small, big, messy, Rorschach, named according to the scheme, ```oops.small```, ```oops.big```, etc.:

```
\DeclareInstance { blot } { oops.small } { general } 
  { <key values for small blots> }
```

Defining a document command 

```
\NewDocumentCommand \blot { . m }
  {
    < some code >
    \IfValueT { #1 } { \tl_set:Nn \l_tmpa_tl { .#1 } }
    \UseInstance { blot } { oops \l_tmpa_tl } { <argument> }
  }
```
  
then means that ```\blot { red }``` prints an average red blot from the oops instance and ```\blot.small { blue }``` prints a small blue blot from the oops.small instance.

Of course it is perfectly possible to nearly do this using a delimited argument where a dot is used fore-and-aft as the delimiter ( d.. ), so that e.g. ```\blot.messy. { blue }``` produces a messy blue blot, but having to write that second dot irritates. Yes, it is a small thing but it is redundant: the content of the argument is restricted to letters only and where it ends is already clear.

This request was spurred by considering the multitude of ways in which derivatives (differential coefficients) are written and trying to handle most cases by just such a correspondence between document command and templates.

**Comment by josephwright** [comment]
I'd handle this using an argument processor I think.

**Comment by ajparsloe** [comment]
I'm confused by the suggestion. The only way I can see an argument processor enabling use of a (suggested) single-dot argument is when an l-type argument is used:

```\NewDocumentCommand \blot { >{\GetDotArg} l m }```

where `\GetDotArg` would extract the single-dot argument from the l-type argument (by omitting the initial dot). But l-type arguments are now deprecated. (If I had noted the demotion of l, u and g arguments to the back of the xparse documentation earlier, I would probably not have made this enhancement request since it seems to run counter to the LaTeX3 team's current thinking. Are l, u and g arguments likely to be dropped from xparse in the next year or two?)
