### ISSUE TITLE
xparse: eats space token while looking for not provided, trailing optional argument

### ISSUE THREAD

**Issue by frougon** [latex3/latex3#466]
Hi,

With more or less recent xparse, a function definition such as
```\NewDocumentCommand \foobar { m o } { ... }```
results in strange behavior when `\foobar` is called without the optional argument. The strange behavior is that the following space token (at least) gets eaten. This did not happen in TL 2016 (Debian stretch), but does happen in TL 2018 (Debian unstable, xparse 2018-04-30; I also manually added xparse.sty 2018-05-12 for testing, same problem). Here is a MWE:

```
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{xparse}
\usepackage{expl3}

\ExplSyntaxOn

\NewDocumentCommand \foobar { m o }
  { #1 -#2- }

\ExplSyntaxOff

\begin{document}
Hell\foobar{o} .
\end{document}
```

Note that there is a space token between the `\foobar{o}` and the following period. In TL 2018 (Debian unstable, xparse 2018-04-30, and also with manually added xparse.sty 2018-05-12), the resulting PDF file after running pdflatex contains `Hello—NoValue—.` (there is no space before the period). In TL 2016 however (Debian stretch, aka "stable"), the output is what I expected, that is `Hello—NoValue— .` (one space before the period).

Thanks!

**Comment by josephwright** [comment]
We know about this, and there is work ongoing.

There was a deliberate change made to do with how we deal with trailing optional arguments: this comes down to the need to allow space skipping to be turned off in some cases. However, where commands with trailing optional arguments are used _in the document body_, this reveals an issue with the `expl3` `peek` functions: they do no reinsert 'skipped' spaces if no match is found. We are currently sorting an appropriate syntax to extend `peek` functions to deal with this.

(In LaTeX2e, the only commands with trailing optional arguments are intended for the preamble, so the question of how to handle this scenario doesn't arise.)

I'd expect to get something concrete sorted during the TUG2018 meeting at the end of next week.

**Comment by frougon** [comment]
Thank you very much for your answer, great to see the problem is under such tight scrutiny. :)

**Comment by josephwright** [comment]
@blefloch  is reviewing and thinking about the low-level support issues here.

**Comment by agrahn** [comment]
Thank you for fixing this!

**Comment by frougon** [comment]
Hi,

I confirm that after installing the latest l3kernel and l3packages from CTAN, the problem disappeared. Thank you so much!
