### ISSUE TITLE
xparse sorted embellishment list

### ISSUE THREAD

**Issue by tobiasdiez** [latex3/latex3#467]
It would be nice to support embellishments that occur multiple times, like for example in tensor expressions
````
\tensor{T}^a_b^c_d.
````
With the `e` argument option, one is able to grab the first two arguments `^a_b` (but looses their order). My proposal would be a new argument type, say `p{chars}`, which accepts chars like the embellishment `e`, and converts the input into a map. For example, the input above with `p{^_}` should result in the ordered map
````
^  -> a
_  -> b
^  -> c
_  -> d
````
(I'm not sure if latex3 already provides such an ordered property list; if not then one can also take it as a sequence of tuples).

**Comment by josephwright** [comment]
I think we are unlikely to do this now, as the nature of `xparse` is largely 'fixed' with the move to `ltcmd`. Closing here: if there is a real pressing need, it should be revisited in the LaTeX2e repo.
