### ISSUE TITLE
"alias" module name  for messages

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex3#471]
Let's assume that I want to write a package called "kernel" (I don't plan this, but it shows the problem). 
There is no package with this name on ctan so as package name it is unproblematic. 

But `kernel`  is a registered prefix. So I can't use it. This is not a problem: I can use e.g. `ufker`. 
But when I use this prefix I get confusing messages for the user:

~~~~
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! ufker error: "wrong-input"
! 
! This command needs an argument!
! 
! See the ufker documentation for further information.
! 
! Type <return> to continue.
!..............................................
~~~~

Could you implement something that allows to setup a module name for messages which is independant from the actual prefix so that package authors are not forced to register and use two prefixes for a package in such cases?

Side remark: such a translation system would perhaps also avoid that the expl3 code uses such hard coded replacements:

~~~~
\cs_new:Npn \msg_see_documentation_text:n #1
  {
    \\ \\ See~the~
    \str_if_eq:nnTF {#1} { LaTeX } { LaTeX3 } {#1} ~
    documentation~for~further~information.
  }
~~~~

**Comment by FrankMittelbach** [comment]
Probably a good idea. I wonder if it requires more than offering a simple mapping from prefix to "display" name, that is many to one or some thing more elaborate with changes depending on context.

**Comment by blefloch** [comment]
Don't we also need to have this mapping in `\msg_fatal_text:n`, `\msg_critical_text:n`, `\msg_error_text:n`, `\msg_warning_text:n`, `\msg_info_text:n`?  This would have a side-effect of changing things like `! LaTeX error: "kernel/variable-not-defined"` from `LaTeX` to `LaTeX3`, hence my slight hesitation.

**Comment by josephwright** [comment]
@blefloch The request is specifically about the name of the _documentation_ for a module, not the name of the module itself.

**Comment by blefloch** [comment]
I'll let @u-fischer comment on what is needed in an application.

**Comment by blefloch** [comment]
> and the user should not see utftag but tagpdf. I don't know if this
> would need also changes in |\msg_fatal_text:n| etc ;-)

Yes it would.  Currently error messages would start with "uftag error:".

**Comment by josephwright** [comment]
@blefloch  I'm not sure I agree. The name of the _error_ is linked to the name of the module at a _code_ level, whereas the advice to 'see module X documentation' is about what the docs are called. If we change the name of the error itself, that messes up the ability of a user to know what they might need to change to alter the text ...

**Comment by u-fischer** [comment]
@josephwright but the prefix is not necessary the modul name -- at least that is my request. I would like to choose a prefix like ufxxx unrelated to the package, module and the file names. The user should not see it, unless there is some low-level error message. 

See e.g. unicode-math. Its prefix is "um", but error messages with "um error" are only confusing. And so naturally unicode-math creates all messages as `\msg_new:nnn {unicode-math}...`.

**Comment by blefloch** [comment]
I'm hesitating: if the displayed name is customizable the internal name
is not visible to the user anymore, which prevents them from using
message redirection to silence a message.  That sounds annoying for the
user.  Perhaps the first line of an error message should be

Unicode-math error "um/font-not-defined"

instead of

um error "font-not-defined"

**Comment by u-fischer** [comment]
@blefloch would be fine for me too.
