### ISSUE TITLE
State clearly security aspects of l3sys-shell

### ISSUE THREAD

**Issue by jfine2358** [latex3/latex3#472]
To work, this package requires shell escape to be enabled. But this allows any TeX document or style file to execute arbitrary code. Which is a security problem.

There's no mention at all of security in [commit 7b62e64](https://github.com/latex3/latex3/commit/7b62e64dde239f9cb6ae0f08400c0b5ccde815d8).

A clear statement of the security aspects would be most helpful.

**Comment by jfine2358** [comment]
Do you intend to say anything about injection attacks?

**Comment by josephwright** [comment]
@jfine2358 Does the commit above cover this sufficiently?

**Comment by jfine2358** [comment]
I've place a comment on the above commit.

**Comment by josephwright** [comment]
I think we have covered this.
