### ISSUE TITLE
[Stupid? FR] Give to PdfLatex3 the ability of using TrueType/OpenType fonts (à la XeLatex/Luatex)

### ISSUE THREAD

**Issue by q2dg** [latex3/latex3#473]
Sorry if I've said something silly, I don't know many technical inners of Latex.
Maybe you're planning merging pdflatex, xelatex and/or luatex in only one engine (it would fantastic!) and I haven't noticed it.
Thanks a lot, anyway

**Comment by josephwright** [comment]
This is an engine thing, not a macro level one: pdfTeX is an 8-bit program, and simply can't use Unicode-encoded OpenType fonts.

**Comment by Stone-Zeng** [comment]
Can pdfTeX use TrueType fonts?

By the way, what exactly is an OpenType/TrueType font? With `.otf`/`.ttf` suffix, or opentype/truetype layout, or opentype/truetype outlines?

**Comment by FrankMittelbach** [comment]
Am 26.08.18 um 11:05 schrieb Xiangdong Zeng:
> Can pdfTeX use TrueType fonts?
> 
> By the way, what exactly is an OpenType/TrueType font? With 
> |.otf|/|.ttf| suffix, or opentype/truetype layout, or opentype/truetype 
> outlines?
> 
  please try to *not* litter the github issues with general questions -- 
not with LaTeX related general questions but even more so *not* with 
general engine questions that don't have anything to do with macro level 
LaTeX3.

Those are much better asked at something like stackexchange (and may 
have an answer there already) --- thanks
