### ISSUE TITLE
How to easily check for obsolete functions or variables in a .dtx file?

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#474]
I'm looking for a method that lets me check if some obsolete functions or variables listed in `l3obsolete.txt` are still present in my `.dtx` (or `.sty`) files: performing this manually is quite off-putting.

**Comment by josephwright** [comment]
This is available using the debugging system. In particular, for testing something like
``latex

\RequirePackage[enable-debug ,check-declarations]{expl3}
\ExplSyntaxOn
\debug_on:n { deprecation }
\ExplSyntaxOff
```
is recommended (we use it for the `expl3` tests themselves).

**Comment by dbitouze** [comment]
OK, thanks. BTW, wrong Markdown syntax in your comment.

**Comment by dbitouze** [comment]
Sigh... Sorry: meanwhile, you corrected it
