### ISSUE TITLE
l3doc: {explTF} referenced but does not exist

### ISSUE THREAD

**Issue by kberry** [latex3/latex3#477]
With Frank's widows-and-orphans.dtx (attached as .txt to placate github) and current l3doc.cls, invocation just "pdflatex widows-and-orphans.dtx", there is a warning:

pdfTeX warning (dest): name {explTF} has been referenced but does not exist, replaced by a fixed one

So apparently \CodedocExplainTF is not being called but \__codedoc_typeset_TF is. No idea, but there's a bug somewhere ...
[widows-and-orphans.txt](https://github.com/latex3/latex3/files/2359015/widows-and-orphans.txt)

**Comment by wspr** [comment]
Thanks, I did have this in the back of my mind to fix up at some stage...

**Comment by Stone-Zeng** [comment]
You may add the following patching in the preamble to fix it temporarily:

```tex

% Do not add hyperlink for `TF`, while do not change color.
\ExplSyntaxOn
\cs_set_protected:Npn \__codedoc_typeset_TF:
  {
    \group_begin:
      \exp_args:No \__codedoc_if_macro_internal:nT \l__codedoc_tmpa_tl
        { \color[gray]{0.5} }
      \itshape TF
      \makebox[0pt][r]
        {
          \color{red}
          \underline{\phantom{\itshape TF} \kern-0.1em}
        }
    \group_end:
  }
\ExplSyntaxOff
```

**Comment by kberry** [comment]
thanks. i don't actually understand the point of underlining/reddening the "TF", either, so I dropped the \makebox too. will, wdyt?

**Comment by Stone-Zeng** [comment]
`TF` means that the function can be actually `T`, `F` or `TF`, so they use an underline to mark this special situation.

In the patching, I just remove the hyperlink, while color and underline are the same as in the original `l3doc`.
