### ISSUE TITLE
l3doc: do not insert hyphen when breaking a cs

### ISSUE THREAD

**Issue by kberry** [latex3/latex3#479]
In l3doc, if \cs{x_y} breaks at the _, I think it would be much (much much) better not to insert a hyphen as if it were a normal word. That looks confusing o me.

E.g., in wao, "either \cs{@@_problem_identified:n} or" breaks. and produces output:

  ... Either \__fmwao_problem_-
  identified:n or ...

But I propose just

  ... Either \__fmwao_problem_
  identified:n or ...

would be better. Not just \cs I suppose, if there are other commands
that typeset control sequences.

Viable? I'd like to have this possibility for the tugboat publication, anyway ... ?  --thanks, karl.

**Comment by wspr** [comment]
Now fixed. For manually tweaking for TUB purposes, replace the following line in l3doc.cls:

              { \token_to_str:N _ } { \_ }

by 

              { \token_to_str:N _ } { \textunderscore\discretionary{}{}{} }

**Comment by FrankMittelbach** [comment]
it is simpler to delegate to the underscore package which is loaded anyway and use the nohpyhen option (not mentioned in the documentation by Robin)

**Comment by eg9** [comment]
Possibly another option should be added: with `nohyphen` a break after the underscore is always possible, which may not be wanted.

See https://tex.stackexchange.com/q/450019/4427

**Comment by wspr** [comment]
Hmm, I would guess whoever added underscore (no idea whether it was me) did so to achieve the current behaviour of supporting hyphenation. Since my recent change makes it work without underscore.sty, perhaps it would be better to no longer load the package.

**Comment by FrankMittelbach** [comment]
maybe. Still think it would be a useful user choice. Personally, I find the hypen helpful depending on the type of document so I'm not sure it should be unconditionally on or off. And @eg9 has a point that you may not want any breakage of such names.

**Comment by wspr** [comment]
I can see you wouldn’t want to hyphenate after underscores that start a csname (like \_foobar:n). Since the current behaviour is achieved by detokenizing and then search/replacing _ for \_ or similar, we could add regex instead to only insert \_ where it makes sense.

            \regex_replace_all:nnN {([^\\])_([^\_])} {\1\c{BreakableUnderscore}\2} \l_@@_cmd_tl

But then I started thinking this is just a waste of time and we should keep it simple since there are lots of edge cases.

So am I right in thinking you’d prefer just to roll back and if people want to omit the underscore they write

        \PassOptionsToPackage{nohyphen}{underscore}

before loading the class? Or do you think a little regex here might improve a few areas?

**Comment by wspr** [comment]
For lack of anything better I called the class options:

    [cs-break-off]
    [cs-break-nohyphen]

Bikeshedding welcome.

Turns out l3doc relies heavily on using underscore.sty, so the best approach is definitely to lean more on that package.
