### ISSUE TITLE
Peeking for regexes in xparse

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#482]
1. Given #466 I've looked again at `\peek_` functions.  Despite there being many functions: 3 `catcode`/`charcode`/`meaning`, times 2 (`remove` or not), times 2 (`ignore_spaces` or not), times 3 (`TF`, `T`, `F`), plus a few others (`N_type`, `collect_inline`, …), the functions don't cover every use case.  One option is to try and find building blocks.  Another option is to provide a very general tool: peeking for an arbitrary regex, e.g.

       \peek_regex:nTF { [A-Za-z]* }   { word ~ "#1" ~ found }   { no ~ word }

   or a more general `\peek_regex_replace:nnTF`, or even something like

       \peek_case_regex_replace:nTF
        {
         { regex1 } { replacement1 } { code receiving replacement1 as #1 }
         { regex2 } { replacement2 } { code receiving replacement2 as #1 }
         ...
       }
       { code for when one case matched }
       { code for when no case matched }

2. We regularly get requests for all sorts of new argument types in `xparse` (#424, #465, #467, some stackexchange questions).  Should we bite the bullet and provide a `regex` argument type, perhaps `p` for pattern?

**Comment by josephwright** [comment]
I'm going to 'forward dupe' to https://github.com/latex3/latex3/issues/820.
