### ISSUE TITLE
xparse: RequirePackage date parsing leads to an ifnum error

### ISSUE THREAD

**Issue by jduf** [latex3/latex3#484]
After installing the github version (commit a1082a7c) with the command 

    lualatex build.lua install

run in the folders:

    l3experimental  l3kernel   l3packages  l3trial

the following code:

    \documentclass{article}
    \usepackage{xparse}
    \begin{document}
    \end{document}

returns the error:

    LaTeX2e <2017/01/01> patch level 3
    Babel <3.9r> and hyphenation patterns for 10 language(s) loaded.
    (/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
    Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
    (/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
    (/usr/local/share/texmf/tex/latex/l3latex/l3packages/xparse/xparse.sty
    (/usr/local/share/texmf/tex/latex/l3latex/l3kernel/expl3.sty
    (/usr/local/share/texmf/tex/latex/l3latex/l3kernel/expl3-code.tex)
    (/usr/local/share/texmf/tex/latex/l3latex/l3kernel/l3pdfmode.def)
    ! Missing = inserted for \ifnum.
    <to be read again> 
                   -

My current config is:

    Package: expl3 2018-09-24 L3 programming layer (loader) 
    pdfTeX 3.14159265-2.6-1.40.17 (TeX Live 2016/Debian)

The problem seems to arise due to the date formatting (using '-' instead of '/') of the RequirePackage command. How can I fix it without updating the whole TexLive distribution?

**Comment by josephwright** [comment]
You'll need to use `latexrelease`, which will patch the kernel to recognise the new date format. You can get `latexrelease` by checking out the LaTeX2e kernel repo and running `tex unpack.ins`, then adding
```latex
\RequirePackage{latexrelease}
```
right at the top of your input.

(Generally, we work on the basis that almost all users will get updated `xparse` or whatever as part of an general TeX system update.e)

**Comment by jduf** [comment]
Thx for you very quick answer! I works

Great work btw!
