### ISSUE TITLE
l3doc: page break can happen before \end{macro}

### ISSUE THREAD

**Issue by kberry** [latex3/latex3#486]
At least in l3doc, a page break is evidently allowed before \end{macro}, that is, I have a break between the last line of {macro} code and the generated output line "(End definition for ...)". I think it would be better to prohibit a break there. Putting a \nobreak on a new line before the \end{macro} did not help, not that I expected it to.

I see there is already a \nobreak in \__codedoc_macro_end_style:n, but clearly it is not sufficient. Maybe \parskip glue preceding? Something related to the previous \end{macrocode}?

I'll attach the various files (hope I got enough so you can run). The bad break happens for \c@totalgapnumber, at the bottom of page 7 / top of page 8. Thanks.

[enddefbreak.zip](https://github.com/latex3/latex3/files/2474733/enddefbreak.zip)

**Comment by FrankMittelbach** [comment]
I think the title should have rather been "Pagebreak can happen after `\end{macrocode}`" which is really what seems to happen here. Pproblem of course is that normally you rather like to break there so forbidding it always seems out and delaying also not simple.

For the current production, you can try

```
% \makeatletter\@endparpenalty=10000\makeatother
%    \begin{macrocode}
\newcounter{totalgapnumber}
%    \end{macrocode}
%  \end{macro}
```
but of course that is a kludge
