### ISSUE TITLE
\int_eval:w 

### ISSUE THREAD

**Issue by ajparsloe** [latex3/latex3#489]
interface3.pdf describes ```\int_eval:w {<integer expression>}``` but, at least in TeXWorks as provided by MiKTeX, ```\int_eval:w { 1+2 }```  produces a "Missing number, treated as zero" error. Since ```\int_eval:w 1+2``` and ```\int_eval:w (1+2)``` evaluate to 3, I suspect this is a documentation error -- the braces should not be there.

**Comment by wspr** [comment]
You are correct — thanks for reporting this.
