### ISSUE TITLE
interface3.pdf new function list

### ISSUE THREAD

**Issue by ajparsloe** [latex3/latex3#490]
I have just searched through interface3.pdf looking for anything with 2018 in it. This catches a sizable number of new functions, some of considerable interest to me and unavailable when I was actively working on a project last year. I wonder if it would be possible to add to interface3.pdf a list of functions added in 2018 (perhaps also, in 2017). This would enable one to scan, rather like an index, what has recently been added to expl3, rather than doing a search and having to locate the functions one by one.

**Comment by blefloch** [comment]
I think Joseph and I (we're the ones adding most of the functions in
recent years) have actually been really good at tagging them with
"added", so the first approach may give a complete list.  The second
approach is obviously more automatic.  In fact,
l3kernel/testfiles/m3expl001.tlg is alread such a list.  A first attempt is

    git diff -U0 22f541 l3kernel/testfiles/m3expl001.tlg |
    grep -v 'index\|l3kernel\|@@\|__\|File\|Package\|Defining message'

but then pairs of lines such as

    +Defining \c_sys_jobname_str on line ...
    -Defining \c_sys_jobname_str on line ...

(not on consecutive lines) need to be deleted from the list.

**Comment by FrankMittelbach** [comment]
Am 17.10.18 um 10:49 schrieb Bruno Le Floch:
> I think Joseph and I (we're the ones adding most of the functions in
> recent years) have actually been really good at tagging them with
> "added", so the first approach may give a complete list.

I wasn't saying you aren't good at proper tagging, only that being 
manual some entries might got missed.

But in principle, I think it might be a nice idea, to collect tagged 
commands inside l3doc and sort them by year and offer a way to output them

Either route has its advantages and disadvantages, but something is 
clearly doable.

**Comment by josephwright** [comment]
Reading this back, I'm wondering what the use case is: normally you want a feature not 'stuff added in a particular timeframe'.

**Comment by ajparsloe** [comment]
Perhaps it depends on one's overall grasp of expl3 (or lack thereof). Although it is 8 or 9 years ago now, I recall coming across '\clist_reverse:N' a significant time after it had been introduced and realizing it was exactly what was needed to avoid a work around (in an early version of `diffcoeff`). `\seq_mapthread_function:NNN` is another that would have given me an"aha!" moment.  However, this was always only a nice-to-have request.

**Comment by josephwright** [comment]
Hmm, we do now have the ChangeLog with `Added` sections: that doesn't systematically have every function listed, but it is reasonably complete. Does it address the requirement?

**Comment by FrankMittelbach** [comment]
What pains me a little @josephwright is that we call it ChangeLog.md here while in any other place it is called changes.txt. Other than that this is precisely where I would expect to look to see what happened during a certain period and what got added or changed.

**Comment by ajparsloe** [comment]
Thanks for directing my attention to the ChangeLog. Yes, that will do nicely.

**Comment by josephwright** [comment]
> What pains me a little @josephwright is that we call it ChangeLog.md here while in any other place it is called changes.txt. Other than that this is precisely where I would expect to look to see what happened during a certain period and what got added or changed.

Not exactly :) The `changes.txt` in e.g. latex3/latex2e is more like a pre-version control log of all changes, as it includes dates, files, individuals making changes, etc. The ChangeLog is more meant as an overview of *significant* changes to the overall structures but expecting that the version control log is used for detailed debugging, etc. And the format is not my invention :)

**Comment by josephwright** [comment]
I think the ChangeLog covers this
