### ISSUE TITLE
\prevdepth management in the galley module

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#50]
One reasonable application of the galley module is to collect material from various places in a vertical box (galley). The naive code for that would be

```
 \box_new:N \g_my_box
 \cs_new_protected:Npn \my_append:n #1
   { \vbox_gset:Nn \g_my_box { \vbox_unpack_clear:N \g_my_box #1 } }
 \my_append:n { Hello. }
 \my_append:n { Hello again. }
```

This does not quite work: the horizontal boxes from the two lines are on top of each other with no baseline skip. A fix is to somehow preserve the `\prevdepth` before closing the vertical box, and restoring it when collecting the next material. I think this fits in the scope of a galley module.

**Comment by josephwright** [comment]
There's apparently an article on _TUGboat_ on this: latest one on the team site.

**Comment by blefloch** [comment]
For the record: one can simply use the correc `\prevdepth` as follows:
```latex
\documentclass{article}
\usepackage{expl3}
\begin{document}
\ExplSyntaxOn
\box_new:N \g_my_box
\dim_new:N \l_my_dp_dim
\cs_new_protected:Npn \my_append:n #1
  {
    \vbox_gset:Nn \g_my_box
      {
        \dim_set:Nn \l_my_dp_dim { \box_dp:N \g_my_box }
        \vbox_unpack_drop:N \g_my_box
        \dim_set:Nn \prevdepth { \l_my_dp_dim }
        #1
      }
  }
\my_append:n { Hello. }
\my_append:n { Hello again. }
\my_append:n { Hello again. }
\box_use:N \g_my_box
\ExplSyntaxOff

Hello.

Hello again.

Hello again.

\end{document}
```
