### ISSUE TITLE
l3keys: spaces in keys still being removed rather than trimmed?

### ISSUE THREAD

**Issue by callegar** [latex3/latex3#506]
Hi,

I'm trying to put together a package managing options via l3keys. Following bug #413 I thought that it was safe to use key names with spaces in them, but I am having trouble and finding subtle issues:

Consider the following:

```
\keys_define:nn { stuff }
  {
    constants format .choice:,
    constants format / roman .code:n =
      {
         %%% Do something here
      },
    constants format / blackboard .code:n =
      {
        %%% Do something else here
      }
  }
```

In the package I am using `l3keys2e` and `\ProcessKeysPackageOptions{stuff}`

Now, the package loading works either with `\RequirePackage[constants format = roman]{stuff}` or with `\RequirePackage[constantsformat = roman]{stuff}`, giving the impression that all spaces are removed in the key name.

Even worse, in the package I have a

```
\NewDocumentCommand\stuffOptions { m }
  {  
    \keys_set:nn { stuff }{ #1 }%
  }
```
To let me change the options after the package is loaded.

Now, if in my document I do a `\stuffOptions{constants format = blackboard}` I get an error, as if the key was undefined. Conversely, everything is fine if I do `\stuffOptions{constantsformat = blackboard}`

Is this the expected behavior?

**Comment by callegar** [comment]
Thanks for the immediate answer and sorry for my evidently naive question.  However, there is one thing that is still not clear to me (actually the thing that mislead me from start). If the key is defined without the spaces, how can the `\RequirePackage[constants format = roman]{stuff}` work?

**Comment by josephwright** [comment]
@callegar  `\zap@space` :(

**Comment by callegar** [comment]
So it looks like there is no chance... if I define the key as `constants~format`, then it won't be possible to use it for package options, unless I use ugly braces in the package option list like `{constants format} = arrow`. Is this correct?

Incidentally, where is the `\zap@space`? In the `\ProcessKeysPackageOptions` in `l3keys2e` or already in the `\RequirePackage` code?

**Comment by josephwright** [comment]
It's part of the 2e kernel, so 'inside `\RequirePackage`' is the best description. There has been talk about looking at this, but the impact would be pretty wide.

**Comment by josephwright** [comment]
@davidcarlisle  Want to elaborate?

**Comment by davidcarlisle** [comment]
There is long standing issue that all white space is removed in the option handling code, so even if you substitute a modified option handler for key=value options, the list of options has already been processed by the standard code.

We have an open issue tracking this 

https://github.com/latex3/latex2e/issues/85

As you can see in the log of that issue, we did contemplate adding some code to better support this for the release of LaTeX2e earlier this month, but testing showed there were issues with compatibility with existing classes, and it wasn't clear if the "modest change" suggested there would really be enough, so the code was reverted for this release, although we will (probably) look at that again for a future release.

Currently if you want to support keys in the `\usepackage` option list rather than via a separate package setup command, it is best to avoid spaces.

**Comment by tail-reversion** [comment]
Here’s my unsolicited opinion :-)

I strongly believe in using a hyphen as a separator in keys (e.g. `constants-format`) for two reasons:
1. It avoids space-related issues altogether.
2. I personally find it clearer as a user. When I first started using `tikz`, I was confused by keywords that contained spaces: I thought they were special syntax and not keywords at all! Although, it’s quite likely that I was the only person confused by that…

**Comment by josephwright** [comment]
@tail-reversion Yup, my conclusion too: see how I do stuff in `siunitx`.

**Comment by callegar** [comment]
@tail-reversion Indeed, even before reading your comment, I converted my code to it!

My two cents suggestion is that recalling this aspect in the l3keys2e documentation would be a very good thing to do.

**Comment by Skillmon** [comment]
@tail-reversion more over there are keys in Ti*k*Z that are clearly separate words which are not split by white space (e.g. `useasboundingbox`). Though I personally use the space variant in some of my packages and like it that way. The hyphen is just so much harder to type :)
