### ISSUE TITLE
xfp doc squished baselines

### ISSUE THREAD

**Issue by kberry** [latex3/latex3#511]
In the xfp.pdf currently distributed, the text and the list on the first page don't have a normal baseline. That is, these two lines are squished together:

operation to give a purely numerical result
   Briefly, the floating point expressions may comprise:

The same thing happens on the second page, between "... give a purely numerical result." and then the new paragraph "An example of use...".

P.S. Not related, but the index seems pointless to me.

**Comment by wspr** [comment]
This is “my fault”, perhaps. The design of l3doc uses coffins and when moving from a coffin to a paragraph the baselineskip isn’t correct for some reason. I should have chased down the reason for this long ago…

**Comment by u-fischer** [comment]
@wspr  that's the same problem as in https://github.com/latex3/latex3/issues/488. And it is the standard problem you get when you have a box with large depth and a following paragraph:

~~~~
\documentclass[]{article}
\begin{document}
\parbox{3cm}{x\\x\\x\\x}\par
xxxxx

\bigskip

\parbox{3cm}{x\\x\\x\\x\strut}\par
xxxxx

\bigskip

\parbox{3cm}{x\\x\\x\\x\strut}\par
\strut xxxxx

\end{document}
~~~~

![image](https://user-images.githubusercontent.com/4047173/50735585-d7dd5100-11b1-11e9-8451-2b13cf045f8e.png)

**Comment by blefloch** [comment]
If we tweak the example to have material above and below the `\parbox` it's even worse: one needs four `\strut` to get the vertical spacing correct (I've set `\parindent=0pt` to avoid confusing the matters).  A cleaner way seems to be to use `\vbox` and appropriately keeping track of the `\prevdepth`: both sets of three lines typeset the same.

```latex
\documentclass[]{article}
\setlength{\parindent}{0pt}
\begin{document}

xxxxx\strut\par
\parbox{3cm}{\strut x\\x\\x\\x\strut}\par
\strut xxxxx

xxxxx\par
\dimen0=\prevdepth\vbox{\prevdepth=\dimen0\hsize=3cm x\\x\\x\\x}\par
xxxxx

\end{document}
```

I'm opening an issue aiming to find some `l3coffins` interface for this.

**Comment by blefloch** [comment]
Ah, in fact I'm not opening an issue: since the `\hbox` in our case has the correct height it seems (or at least nobody complained about spacing above an `l3doc` `function` environment), the only thing left is to set `\prevdepth` to the correct depth.  But one of the coffins has exactly the right depth since it is set as a vertical coffin.
