### ISSUE TITLE
l3keys2e's option with accent: \UseTextAccent… \@curr@enc error

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#512]
- Version of `expl3`: see file list below.
- TeX system: up to date TeX Live 2018.
- Engine used: `pdfTeX`.

The following `expl3` class, that provides the option `mykeyword` (thanks to `l3keys2e`):

- works like a charm with:
  - the default value option (that contains an accent: "Café"),
   - values given to this option that don't contain any accent, e.g. "Bar",
- fails to work with values that do contain accents e.g. "Café" (indeed, the same as the default one!). In this case, the compilation fails with the following error:
  >    ! Undefined control sequence. \UseTextAccent ...up @firstofone \let @curr@enc \cf@encoding @use@text@en...

```latex
\begin{filecontents*}{myclass.cls}
\RequirePackage{l3keys2e}
\RequirePackage{expl3}
\ExplSyntaxOn
\ProvidesExplClass
  {myclass}
  {2019/01/05}
  {0.1}
  {
    My Nice Class.%
  }
\NeedsTeXFormat{LaTeX2e}
\LoadClass { report }
\RequirePackage[utf8]{inputenc} % Useless nowadays
%
\tl_set:Nn \l__myclass_my_keyword_tl {Café}
\keys_define:nn { myclass }
{
  mykeyword .tl_set:N = \l__myclass_my_keyword_tl,%
}%
\ProcessKeysOptions { myclass }
\AtEndDocument{\l__myclass_my_keyword_tl}
\end{filecontents*}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass{myclass}
% \documentclass[mykeyword=Bar]{myclass}
% \documentclass[mykeyword=Café]{myclass}
\begin{document}
Foo and
\end{document}
```

Here is my  *File List*:
```
latexbug.sty    2018/12/31 v1.0e Bug-classification
 myclass.cls    2019/01/05 v0.1 My Nice Class.
l3keys2e.sty    2018-10-17 LaTeX2e option processing using LaTeX3 keys
   expl3.sty    2018-12-12 L3 programming layer (loader) 
expl3-code.tex    2018-12-12 L3 programming layer 
l3pdfmode.def    2018-12-12 v L3 Experimental driver: PDF mode
  report.cls    2018/09/03 v1.4i Standard LaTeX document class
  size10.clo    2018/09/03 v1.4i Standard LaTeX file (size option)
inputenc.sty    2018/08/11 v1.3c Input encoding file
 ***********
```

BTW, I didn't use  `latexbug.sty` because it complains about "Third-party file(s)" `myclass.cls` but this file is precisely the crux of the issue.

**Comment by josephwright** [comment]
This happens at the point where the LaTeX2e kernel processes options, before anything gets passed to `l3keys2e`.  Somewhat related is https://github.com/latex3/latex2e/issues/85; in any case, things cannot be fixed here at the LaTeX3 level.

**Comment by dbitouze** [comment]
@josephwright Is it worth reporting to https://github.com/latex3/latex2e/issues?

**Comment by josephwright** [comment]
Erm, you can, but it's not like the team don't know abiut this :) When the option mechanism was written, the assumption about what would appear was pretty simple: a few straight ASCII options. And there were a far fewer tokens available to code up processing. Probably @davidcarlisle has some comment here.

**Comment by dbitouze** [comment]
Okay :) Don't know it it worth but, as a workaround, it is enough to use this option not at the `\documentclass` level but in a "setup" command, as in the edit of my question [on SE](https://tex.stackexchange.com/q/468759/18401).

**Comment by davidcarlisle** [comment]
@dbitouze  if you follow the trace of   https://github.com/latex3/latex2e/issues/85 you'll see that this was _almost_ solved in the LaTeX2e release last month, code was checked in that would make the original unmangled option lists available to extension packages (so l3keys could then use those as the basis of its option handling).

However we backed it out as testing showed that it broke things in the wild, absolutely every latex document class and package passes through that code path at some point and even "safe" changes turn out not to be safe as packages patch the code in various ways...

So we backed out all the changed code at this time, but probably we will come back to this but need to do it with a longer advertised time and more extensive testing of third party code and more time to contact package authors if there are any compatibility issues.
