### ISSUE TITLE
Accented letters not uppercased by \tl_mixed_case

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#514]
- Version of `expl3`: see file list below.
- TeX system: up to date TeX Live 2018.
- Engine used: `pdfTeX`.

Accented letters are uppercased by `\tl_upper_case` but not by `\tl_mixed_case`, as shown by the following MCE which leads to:

• ÉLÉPHANT
• éléphant

```latex
\documentclass{article}
\usepackage{expl3}
\begin{document}
\ExplSyntaxOn
\begin{itemize}
\item \tl_upper_case:n {éléphant}
\item \tl_mixed_case:n {éléphant}
\end{itemize}
\ExplSyntaxOff
\end{document}
```

Here is my  *File List*
```
 article.cls    2018/09/03 v1.4i Standard LaTeX document class
  size10.clo    2018/09/03 v1.4i Standard LaTeX file (size option)
   expl3.sty    2018-12-12 L3 programming layer (loader) 
expl3-code.tex    2018-12-12 L3 programming layer 
l3pdfmode.def    2018-12-12 v L3 Experimental driver: PDF mode
  omscmr.fd    2014/09/29 v2.5h Standard LaTeX font definitions
 ***********
```

**Comment by eg9** [comment]
Yes, the documentation says

> In the case of 8-bit engines, mappings are provided for characters which can be represented in output typeset using the T1 font encoding. Thus for example `ä` can be case-changed using pdfTeX.

**Comment by dbitouze** [comment]
@eg9 I had read this part of the documentation but still don't understand how it explains the case-changed works with `\tl_upper_case` but not with `\tl_mixed_case`.

**Comment by eg9** [comment]
@dbitouze I wanted to emphasize that the documentation makes no difference between the two cases.

**Comment by dbitouze** [comment]
>I wanted to emphasize that the documentation makes no difference between the two cases.

@eg9 I understood after your comment's change and then deleted my comment :)
