### ISSUE TITLE
xfp doc insufficient

### ISSUE THREAD

**Issue by kberry** [latex3/latex3#515]
regarding the actual content of xfp.pdf.

minor: in the "Extrema" item, I suggest x_1, x_2, ... instead of x, y, ..., because these are lists of indefinite length (I assume).

more substantive: in the "Rounding functions" item, sorry, but I can't make heads or tails of it. What are n and t used for? And I gather they are optional in some cases. (I was trying to understand an \fpeval{round(...), 2)} example in Joseph's paper; the doc did not help me :(. Probably if I looked at the source I could understand, but ...)

On the formatting front, that lengthy "Rounding functions" list might be better as a sublist instead of a single long paragraph.

In "Random numbers" item: given Joseph's primitives rationalization, perhaps these are (will be, for TL) available in xetex now?

thanks.

**Comment by josephwright** [comment]
@blefloch seems happy ...
