### ISSUE TITLE
\box_set_eq_clear:NN, \box_gset_eq_clear:NN falsely claimed to clear box globally

### ISSUE THREAD

**Issue by gabor-braun** [latex3/latex3#518]
Version 2018-12-12 of the LaTeX3 interfaces document claims (emphasis are my addition):

> \box_set_eq_clear:NN \<box1> \<box2>
> Sets the content of \<box1> within the current TEX group equal to that of \<box2>, then
> *clears \<box2> globally*.
>
> \box_gset_eq_clear:NN \<box1> \<box2>
> Sets the content of \<box1> equal to that of \<box2>, then clears \<box2>. *These assignments
> are global*.

I have tested this with the following example under plain TeX with pdftex (a slight variation fo the example at `\box_use_drop:N`):
```tex
\input expl3-generic.tex
\ExplSyntaxOn
\hbox_set:Nn \l_tmpa_box { a }
\group_begin:
  \hbox_set:Nn \l_tmpa_box { b }
  \group_begin:
    \box_set_eq_clear:NN \l_tmpb_box \l_tmpa_box
  \group_end:
  1:~ \box_use:N \l_tmpa_box \par
\group_end:
2:~ \box_use:N \l_tmpa_box

\newpage

\hbox_set:Nn \l_tmpa_box { a }
\group_begin:
  \hbox_set:Nn \l_tmpa_box { b }
  \group_begin:
    \box_gset_eq_clear:NN \g_tmpb_box \l_tmpa_box
  \group_end:
  1:~ \box_use:N \l_tmpa_box \par
\group_end:
2:~ \box_use:N \l_tmpa_box

\ExplSyntaxOff
\end
```
The created PDF looks like (omtting page number):
```
1:
2: a
3:
4: a
```
If `\l_tmpa_box` were cleared globally, the `a` shouldn't be there.

A formulation like that of `\box_use_drop:N` is a better description of the observed behaviour:
*\<box2> is cleared at the group level it was set*.

Log file:
```log
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2019/dev/Debian) (preloaded format=pdftex 2018.12.21)  11 JAN 2019 13:58
entering extended mode
 restricted \write18 enabled.
 file:line:error style messages enabled.
 %&-line parsing enabled.
**\input box-set-eq-clear.tex
(./box-set-eq-clear.tex
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/expl3-generic.tex
Package: expl3 2018-12-12 L3 programming layer (loader)

(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/expl3-code.tex
Package: expl3 2018-12-12 L3 programming layer (code)
\c_max_int=\count27
\l_tmpa_int=\count28
\l_tmpb_int=\count29
\g_tmpa_int=\count30
\g_tmpb_int=\count31
\g__kernel_prg_map_int=\count32
\c_log_iow=\count33
\l_iow_line_count_int=\count34
\l__iow_line_target_int=\count35
\l__iow_one_indent_int=\count36
\l__iow_indent_int=\count37
\c_zero_dim=\dimen16
\c_max_dim=\dimen17
\l_tmpa_dim=\dimen18
\l_tmpb_dim=\dimen19
\g_tmpa_dim=\dimen20
\g_tmpb_dim=\dimen21
\c_zero_skip=\skip18
\c_max_skip=\skip19
\l_tmpa_skip=\skip20
\l_tmpb_skip=\skip21
\g_tmpa_skip=\skip22
\g_tmpb_skip=\skip23
\c_zero_muskip=\muskip10
\c_max_muskip=\muskip11
\l_tmpa_muskip=\muskip12
\l_tmpb_muskip=\muskip13
\g_tmpa_muskip=\muskip14
\g_tmpb_muskip=\muskip15
\l_keys_choice_int=\count38
\l__intarray_loop_int=\count39
\c__intarray_sp_dim=\dimen22
\g__intarray_font_int=\count40
\c__fp_leading_shift_int=\count41
\c__fp_middle_shift_int=\count42
\c__fp_trailing_shift_int=\count43
\c__fp_big_leading_shift_int=\count44
\c__fp_big_middle_shift_int=\count45
\c__fp_big_trailing_shift_int=\count46
\c__fp_Bigg_leading_shift_int=\count47
\c__fp_Bigg_middle_shift_int=\count48
\c__fp_Bigg_trailing_shift_int=\count49
\c__kernel_randint_max_int=\count50
\g__fp_array_int=\count51
\l__fp_array_loop_int=\count52
\l__sort_length_int=\count53
\l__sort_min_int=\count54
\l__sort_top_int=\count55
\l__sort_max_int=\count56
\l__sort_true_max_int=\count57
\l__sort_block_int=\count58
\l__sort_begin_int=\count59
\l__sort_end_int=\count60
\l__sort_A_int=\count61
\l__sort_B_int=\count62
\l__sort_C_int=\count63
\l__tl_analysis_normal_int=\count64
\l__tl_analysis_index_int=\count65
\l__tl_analysis_nesting_int=\count66
\l__tl_analysis_type_int=\count67
\l__regex_internal_a_int=\count68
\l__regex_internal_b_int=\count69
\l__regex_internal_c_int=\count70
\l__regex_balance_int=\count71
\l__regex_group_level_int=\count72
\l__regex_mode_int=\count73
\c__regex_cs_in_class_mode_int=\count74
\c__regex_cs_mode_int=\count75
\l__regex_catcodes_int=\count76
\l__regex_default_catcodes_int=\count77
\c__regex_catcode_D_int=\count78
\c__regex_catcode_S_int=\count79
\c__regex_catcode_L_int=\count80
\c__regex_catcode_O_int=\count81
\c__regex_catcode_A_int=\count82
\c__regex_all_catcodes_int=\count83
\l__regex_show_lines_int=\count84
\l__regex_min_state_int=\count85
\l__regex_max_state_int=\count86
\l__regex_left_state_int=\count87
\l__regex_right_state_int=\count88
\l__regex_capturing_group_int=\count89
\l__regex_min_pos_int=\count90
\l__regex_max_pos_int=\count91
\l__regex_curr_pos_int=\count92
\l__regex_start_pos_int=\count93
\l__regex_success_pos_int=\count94
\l__regex_curr_char_int=\count95
\l__regex_curr_catcode_int=\count96
\l__regex_last_char_int=\count97
\l__regex_case_changed_char_int=\count98
\l__regex_curr_state_int=\count99
\l__regex_step_int=\count100
\l__regex_min_active_int=\count101
\l__regex_max_active_int=\count102
\l__regex_replacement_csnames_int=\count103
\l__regex_match_count_int=\count104
\l__regex_min_submatch_int=\count105
\l__regex_submatch_int=\count106
\l__regex_zeroth_submatch_int=\count107
\g__regex_trace_regex_int=\count108
\c_empty_box=\box16
\l_tmpa_box=\box17
\l_tmpb_box=\box18
\g_tmpa_box=\box19
\g_tmpb_box=\box20
\l__box_top_dim=\dimen23
\l__box_bottom_dim=\dimen24
\l__box_left_dim=\dimen25
\l__box_right_dim=\dimen26
\l__box_top_new_dim=\dimen27
\l__box_bottom_new_dim=\dimen28
\l__box_left_new_dim=\dimen29
\l__box_right_new_dim=\dimen30
\l__box_internal_box=\box21
\l__coffin_internal_box=\box22
\l__coffin_internal_dim=\dimen31
\l__coffin_offset_x_dim=\dimen32
\l__coffin_offset_y_dim=\dimen33
\l__coffin_x_dim=\dimen34
\l__coffin_y_dim=\dimen35
\l__coffin_x_prime_dim=\dimen36
\l__coffin_y_prime_dim=\dimen37
\c_empty_coffin=\box23
\l__coffin_aligned_coffin=\box24
\l__coffin_aligned_internal_coffin=\box25
\l_tmpa_coffin=\box26
\l_tmpb_coffin=\box27
\l__coffin_display_coffin=\box28
\l__coffin_display_coord_coffin=\box29
\l__coffin_display_pole_coffin=\box30
\l__coffin_display_offset_dim=\dimen38
\l__coffin_display_x_dim=\dimen39
\l__coffin_display_y_dim=\dimen40
\g__file_internal_ior=\read1
\l__coffin_bounding_shift_dim=\dimen41
\l__coffin_left_corner_dim=\dimen42
\l__coffin_right_corner_dim=\dimen43
\l__coffin_bottom_corner_dim=\dimen44
\l__coffin_top_corner_dim=\dimen45
\l__coffin_scaled_total_height_dim=\dimen46
\l__coffin_scaled_width_dim=\dimen47
\l__seq_internal_a_int=\count109
\l__seq_internal_b_int=\count110
)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3pdfmode.def
File: l3pdfmode.def 2018-12-12 v L3 Experimental driver: PDF mode
\l__driver_color_stack_int=\count111
)) [1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}] )</usr/share/texlive/
texmf-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb>
Output written on box-set-eq-clear.pdf (1 page, 11159 bytes).
PDF statistics:
 12 PDF objects out of 1000 (max. 8388607)
 7 compressed objects within 1 object stream
 0 named destinations out of 1000 (max. 500000)
 1 words of extra memory for PDF output out of 10000 (max. 10000000)
```

**Comment by eg9** [comment]
The definition of `\box_set_eq_clear:NN` is
```latex
\protected\long macro:#1#2->\tex_setbox:D #1\tex_box:D #2
```
that in primitive terms is
```
\setbox #1 \box #2 
```
This is “global” in the sense of boxes, which are quite peculiar under this respect. What's cleared is the _current incarnation_ of the box. In your case the box register that's cleared is that at grouping level 1.
If you remove the `\hbox_set:Nn \l_tmpa_box { b }` instruction, you get nothing in all cases when you do `\box_use:N\l_tmpa_box`, because the current incarnation of `\l_tmpa_box` is the one living at grouping level 0.

Yes, the documentation is slightly misleading.

**Comment by gabor-braun** [comment]
> I guess this falls in the same category as the renaming of 
\box_use_clear:N
> into \box_use_drop:N

These functions also fall in the same category (claimed to be the 
primitives \unhbox and \unvbox): 

\hbox_unpack_clear:N
\vbox_unpack_clear:N

I have gone through the list of documented box functions, and there seems 
to be no more, i.e., to summarize, this is the complete list (without 
alternative signatures), where _clear is used in the meaning "make last 
argument void at the group level it was set":

\box_set_eq_clear:NN
\box_gset_eq_clear:NN
\hbox_unpack_clear:N
\vbox_unpack_clear:N

(\box_clear:N, \box_clear_new:N and its variants are not in this 
category.)

Gábor

**Comment by blefloch** [comment]
We are in the process of renaming all ...`clear`... functions that use `\box` or `\unhbox` or `\unvbox` behind the scenes into ...`drop`..., see pull request #522.  Thanks for the detailed check.

**Comment by car222222** [comment]
Maybe _void would be even better (if you drop a box then it may get broken!).

**Comment by FrankMittelbach** [comment]
> Maybe _void would be even better (if you drop a box then it may get 
> broken!).

while _void can be a verb, in  a setting like

\box_set_eq_void:NN

I would probably misread this as the boxes are set to void not the first 
is set to the second and the send then becomes void

**Comment by blefloch** [comment]
> Maybe _void would be even better (if you drop a box then it may get
> broken!).

Nice quip, and quite true!  However, \box_use_void:N suggests we are
using a void box, \box_set_eq_void:NN reads like we are setting the box
equal to a void box, etc.  I think the reason is that "void" can be a
(topic-relevant) noun, while "drop" cannot.

**Comment by car222222** [comment]
I think you mean adjective, rather than noun: voiding something means making it void, not making it (or throwing it) into a void. 

I do not see that the verb “void” differs at all in this respect from “drop” or “clear” (both of which can also be both adjective and verb (although “drop” as adjective appears only in specialised  vocabularies: drop head and drop scone come immediately to mind, although both may better be hyphenated or concatenated into one word).  Note further that whereas “drop” can also be a noun, “clear” cannot, classically and AFAIK:-).

**Comment by car222222** [comment]
But I accept the arguments against “void” from both these experts in Euro-English (as that is not a language in which I am very literate).

**Comment by FrankMittelbach** [comment]
Am 18.01.19 um 12:09 schrieb Chris Rowley:
> I do not see that the verb “void” differs at all in this respect from 
> “drop” or “clear” (both of which can also be both adjective and verb 
> (although “drop” as adjective appears only in specialised vocabularies: 
> drop head and drop scone come immediately to mind, although both may 
> better be hyphenated or concatenated into one word). Note further that 
> whereas “drop” can also be a noun, “clear” cannot, classically and AFAIK:-).

the verb doesn't differ ,but what I (and Bruno I guess) think that in 
that constellation I don't read as verb but more like

box_set_eq_void:NN   as    "to void"

  but

box_set_eq_drop:NN   as    "and drop"
box_seq_eq_clear:NN  as    "and clear"
