### ISSUE TITLE
Overlappings in interfaces documentation

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#527]
Some overlappings have been introduced in `interfaces` documentation with version 2019-01-28:

- p. 152: `\file_get:nnN` and `\file_get:nnNTF`,
- p. 252: `\sys_shell_get:nnN` and `\sys_shell_get:nnNTF`.

**Comment by josephwright** [comment]
The two functions are separate ...

**Comment by wspr** [comment]
While this is consistent with other parts of the documentation, I now think we do this frequently enough it would make sense to merge.

E.g.,  \prop_pop:NnN and \prop_pop:NnNTF are documented 2 pages apart from each other. (Although one references the other.) 

I’d suggest nowadays that the TF versions are the “preferred” ones so probably make sense to include first, and combining the docs avoids some duplication.

If you agree I’d be happy to (slowly) work through the docs to combine all the cases where we have differing base: and base:TF documentation.

**Comment by blefloch** [comment]
The overlaps are gone, not sure in which commit.  I've moved Will's suggestion to a new issue.

**Comment by car222222** [comment]
But there are now very many other things in this issue.  What now happens to,them?  Maybe should create new issues?
