### ISSUE TITLE
galley packags and upload to CTAN

### ISSUE THREAD

**Issue by norbusan** [latex3/latex3#529]
Dear all,
it seems that xhj and galley2 from the galley directory have never been uploaded to CTAN. Unfortunately, there are already packages out there in the wild using them.

Is this on purpose?

Best

Norbert

**Comment by FrankMittelbach** [comment]
What packages in the wild are those? galley was an early prototype that was deliberately not put on CTAN and was always stated as it is a prototype that is likely to change and that it should never be used for production purposes. Same with xhj.

**Comment by norbusan** [comment]
docindex

**Comment by norbusan** [comment]
Ok, but then we should do something with https://ctan.org/pkg/xdoc?lang=en which depends on these two (hard dep via `RequirePackage`). Any suggestion?

**Comment by FrankMittelbach** [comment]
Suggest to Lars to update xdoc to use xgalley perhaps? (or withdrew?)  I mean if xdoc is using galley and that was never generally available the package can't have been used that much if ever, can it?

**Comment by blefloch** [comment]
Another option that may be more palatable to Lars would be to suggest to
him to include the galley code in his code.

**Comment by FrankMittelbach** [comment]
Are you sure @blefloch ? I haven't checked but my guess is that galley still draws on a version of expl3 that is way away from current expl3, I mean that is the first attempt at galley way back followed by galley2 followed by what is now in the expl3 package distribution which is xgalley.

**Comment by blefloch** [comment]
I had underestimated the unusability of galley now.  Probably worth
informing Lars.  It's not clear what he should do.

**Comment by josephwright** [comment]
I think this is a clear 'no': the code is truly ancient, never released, etc.
