### ISSUE TITLE
Enhancement: \bool_case:n and \bool_case:nTF in expl3

### ISSUE THREAD

**Issue by shmuelmetz** [latex3/latex3#530]
I would like a case statement similar to the if/elseif/else/endif constructs of various other languages, e.g., SELECT/WHEN/OTHERWISE/END in REXX, as discussed at https://tex.stackexchange.com/questions/473979/is-there-latex3-work-being-done-on-a-boolean-case-statement. The preferred syntax would be something like
<pre>
\bool_case:n
  {
    {test 1} {action 1}
    ...
    {test n} {action n}
  }
</pre>
and
<pre>
\bool_case:nTF
  {
    {test 1} {action 1}
    ...
    {test n} {action n}
  }
  {
  {match-any-action}
  {no-match-action}
</pre>

**Comment by tail-reversion** [comment]
I had wondered about requesting this, so I did some looking and discovered that it had been discussed on the LaTeX-L mailing list. The reasoning given there for not providing a `\bool_case:n` was that there are already specific case functions for integers, token lists, strings, and dimensions, which covers most use cases. Since expl3 is oriented around typesetting needs, these specific functions will tend to be more common than complex boolean statements anyways.

That being said, I think that adding `\bool_case:n` could be useful… Though I’m curious to see an example of a use case, because I realized I couldn’t come up with one that couldn’t be easily restated in terms of the existing functions.

**Comment by wspr** [comment]
Here's an example implementation. Criticism welcome. I mildly support adding it to the kernel as it fits the pattern of the other modules and has occasional use cases.

I also think adding a construct for "jumping ahead" would be useful in cases where you have multiple booleans that are NOT expandable.

```
\documentclass{article}
\usepackage{expl3}
\begin{document}
\ExplSyntaxOn
\quark_new:N \q_bool_case_end
\cs_new_protected:Npn \__quark_bool_case_end: #1 \q_bool_case_end {}
\cs_new_protected:Npn \bool_case:nTF #1 #2 #3
  {
    \tl_if_empty:nT {#1} { \ERRORRR \__quark_bool_case_end: }
    \int_if_odd:nT { \tl_count:n {#1} } { \ERROR \__quark_bool_case_end: }
    \__bool_case:nnnn {#2} {#3} #1 \q_nil \q_nil
    #3
    \__quark_bool_case_end:
    \q_bool_case_end
  }
\cs_new_protected:Npn \__bool_case:nnnn #1 #2 #3 #4
  {
    \quark_if_nil:nT {#3} { #2 \__quark_bool_case_end: }
    \bool_if:nT {#3} { #4 #1 \__quark_bool_case_end: }
    \__bool_case:nnnn {#1} {#2}
  }

\bool_case:nTF
  {
    { \tl_if_empty_p:n {C} } {empty}
    { \int_compare_p:n {1<2} } {right}
    { \int_compare_p:n {1>2} } {wrong}
  }
  {T}
  {F}

\ExplSyntaxOff
\end{document}
```

**Comment by wspr** [comment]
On my second point, I'd missed this has been added to expl3 already:  `\prg_break_point:` can be inserted after a number of conditionals, and `\prg_break:`/`\prg_break:n` used to "goto" that point in the code.

**Comment by wspr** [comment]
It's worth mentioning that last time this function was requested there was discussion around the fact that it doesn't match the same syntax as the other `case` functions, in that it isn't passed a variable which is being matched to a value. That's an okay argument that `\bool_case:n` probably isn't the best name. Perhaps something like `\bool_if_first:nTF` or `\bool_if_list:nTF` would work?

**Comment by blefloch** [comment]
I'm in favor of the proposed \bool_case:n(TF) addition with that name
despite the slight difference compared to other case functions.  The
implementation should be essentially copied from the other ones (sorry
Will but yours has some termination tests that can easily be avoided).

**Comment by blefloch** [comment]
Unless I messed up, there should now be a branch "bool_case" in the
repo, with one new commit implementing \bool_case:n(TF).

**Comment by shmuelmetz** [comment]
Where I was coming from was a PL/I background, where the SELECT statement can be used either with or without a test expression. If the expression is present than the values in the WHEN statements are matched against it. If the expression is not present, then the values in the when statements are converted to BIT (normally they will already be BIT(1).) and the first WHEN to evaluate as '1'B is selected. The syntax is essentially the same for both uses.

Thanks.


--
Shmuel (Seymour J.) Metz
http://mason.gmu.edu/~smetz3

________________________________________

**Comment by shmuelmetz** [comment]
My motivation for wanting this is that I coded a math mode macro \strict[option]{base}, where the intent is to underset base with an upright modifier that defaults to "strict", could be foo-strict where #2 is foo-, could be explicitly provided as the value of #2 or could be one of two other values selected by abbreviations. I'd like to consolidate the code below into the definition of \show_strict:nn.

<pre>
\ExplSyntaxOn

% Render underscored with some variation of strict
\NewDocumentCommand{\strict}{O{strict} m}
  {
    \str_if_eq:eeTF {\str_item:nn {#1} {-1}} {-}
      {
        \show_strict:nn {{#1}strict} {#2}
      }
      {
        \show_strict:nn {#1} {#2}
      }
  }

\cs_new_protected:Npn \show_strict:nn #1 #2
  {
    \str_case:nnF {#1}
      {
          {*}
          {  \underset {\textup{(semi-strict,strict)}} {#2} }
          {**}
          { \underset {\textup{semi-strict (strict)}} {#2} }
      }
      {
        \underset {\textup{#1}} {#2}
      }

\ExplSyntaxOff
  }</pre>


--
Shmuel (Seymour J.) Metz
http://mason.gmu.edu/~smetz3

________________________________________

**Comment by PhelypeOleinik** [comment]
This feature is now in the kernel (`l3candidates`) as `\bool_case_true:n(TF)` and `\bool_case_false:n(TF)` (added in #533):

![Screenshot from 2020-03-10 08-11-45](https://user-images.githubusercontent.com/12678598/76307051-d40df880-62a6-11ea-9c10-511484cfd002.png)
