### ISSUE TITLE
l3keys : a problem when use of .inherit:n

### ISSUE THREAD

**Issue by fpantigny** [latex3/latex3#535]
The following code gives an error : `Missing \begin{document}`.

There is no error if the final affectation is not in a boolean. There is no error if there is no use of `.inherit:n` before. 

```
\documentclass{article}
\usepackage{expl3}[2019-01-28]
\ExplSyntaxOn
% Two keys modules with .inherit:n
\keys_define:nn { foo } { test .code:n = {} }
\keys_define:nn { } { bar .inherit:n = foo }
\keys_set:nn { bar } { test = a }

% Another module with an affection for boolean
\keys_define:nn { Module } { key2 .bool_set:N = \l_tmpa_bool }
\keys_set:nn {Module} {key2 = false}
\ExplSyntaxOff


\begin{document}
Some text.
\end{document}
```

**Comment by blefloch** [comment]
\__keys_choice_find:nn checks whether "\key code > foo/key2/false"
exists (it doesn't), then falls back to calling "\key code >
foo/key2/unknown", which is unfortunately not defined hence does not
grab its argument "{false}".  Thus, "{false}" ends up incorrectly in the
input stream, causing the Missing \begin{document} error.

I don't know the key internals well enough to say which of "\key code >
foo/key2/false" or "\key code > foo/key2/unknown" should be defined nor
where.

**Comment by fpantigny** [comment]
I'm still perplex because, the instruction which leads to an error is `\keys_set:nn {Module} {key2 = false}` and not `\keys_set:nn {foo} {key2 = false}`. Why is there an interaction between the modules 'foo' and 'Module'?
