### ISSUE TITLE
Large roman numerals

### ISSUE THREAD

**Issue by stone-zeng** [latex3/latex3#540]
`\int_to_roman:n { 5000 }` gives "mmmmm", but in the "standard" roman numerals use overbar such as `\bar{v}`. Of course it may not be permitted in the pure-text mode. So please consider to add a notice that the integer inside `\int_to_roman:n` should not larger than 4999, otherwise the result may not be so correct.

**Comment by eg9** [comment]
`\int_to_roman:n` is an `expl3` wrapper around `\romannumeral` (allowing integer expressions). It is not really for printing arbitrary numbers in Roman notation, which pertains to formatting and is out of the scope of `expl3`.

It might be useful to add a short note about this in the documentation.

**Comment by josephwright** [comment]
As @eg9 says, this is a number conversion function: I don't think one could actually store the bar notation in a portable way.
