### ISSUE TITLE
\str_if_eq:nn not defined

### ISSUE THREAD

**Issue by shmuelmetz** [latex3/latex3#542]
The interface3.pdf manual shows \str_if_eq:nnTF with TF underlined, but \str_if_eq:nn is undefined. If the intent is that \str_if_eq_p:nn should be used instead then the underlining should be removed or a not added.
```latex
\documentclass{article}
\usepackage{mathtools}
\usepackage{xparse}

\newcommand \pagecref [1]
   {
     \fullcref{#1} on \cpageref{#1}
   }

\newcommand \Pagecref [1]
   {
     \Fullcref{#1} on \cpageref{#1}
   }

\ExplSyntaxOn

% Render type # (description)
%       \begin{equation} does not retain optional parameter in \nameref{label}
\NewDocumentCommand \fullcref {m}
    {
      \fullcref:nn {cref} {#1}
    }

\NewDocumentCommand \Fullcref {m}
    {
      \fullcref:nn {Cref} {#1}
    }

\cs_new:Npn \fullcref:nn #1 #2
  {
     \ str_log:n {fullcref: #2 has tl_count:n {#2} tokens}
     \ str_log:n {fullcref: #2 labels a \namecref{#2}}
      \bool_if:nTF
        {
          \str_if_eq:nn {\str_range:nnn {#2} {1} {3}} {eq:} ||
%         \str_if_eq:nn {\namecref{#2}}               {equation} || ?
          \str_if_eq:nn {\nameref{#1}}                {}
        }
        {
          {use:c {#1}} {#2} on \cpageref{#2}
        }
        {
          {use:c {#1}} {#2} (\nameref{#1}) on \cpageref{#1}
        }
  }

\ExplSyntaxOff

\usepackage[colorlinks,hidelinks,draft=false]{hyperref}

\usepackage{cleveref}
\usepackage[draft]{showlabels}

\begin{document}
\section{foo bear}
\label{sec:foo}
This is dummy text.

\begin{equation}
\label{eq:foo}
\end{equation}

This is text that refers to \fullcref{sec:foo}.

This is text that refers to \fullcref{eq:foo}.

This is text that refers to \fullcref{def:foo}.

This is text that refers to \fullcref{def:bar}.

This is text that refers to \pagecref{sec:foo}.

This is text that refers to \pagecref{eq:foo}.

This is text that refers to \pagecref{def:foo}.

This is text that refers to \pagecref{def:bar}.

\begin{definition}
\label{def:foo}
This is a definition without descriptive text.
\end{definition}

\Fullcref{sec:foo}.

\Fullcref{eq:foo}.

\Fullcref{def:foo}.

\Fullcref{def:bar}.

\Pagecref{sec:foo}.

\Pagecref{eq:foo}.

\Pagecref{def:foo}.

\Pagecref{def:bar}.

\begin{definition}[dummy definition]
\label{def:bar}
This is a definition with descriptive text.
\end{definition}

\end{document}
```

The error message:

```latex
! Undefined control sequence.
<argument> \str_if_eq:nn 
                         {\str_range:nnn {sec:foo}{1}{3}}{eq:}||\str_if_eq:n...
```

**Comment by eg9** [comment]
You're supposed to use _predicates_ in the first argument to `\bool_if:nTF`. So `\str_if_eq_p:nn`, not `\str_if_eq:nn` which would return nothing at all, if it were defined.

**Comment by tail-reversion** [comment]
>The interface3.pdf manual shows \str_if_eq:nnTF with TF underlined, but \str_if_eq:nn is undefined. If the intent is that \str_if_eq_p:nn should be used instead then the underlining should be removed or a not added.
The underline for `TF` is just a way of indicating that `\str_if_eq:nnT`, `\str_if_eq:nnF`, and `\str_if_eq:nnTF` are all defined.

**Comment by FrankMittelbach** [comment]
> The underline for `TF` is just a way of indicating that `\str_if_eq:nnT`, `\str_if_eq:nnF`, and `\str_if_eq:nnTF` are all defined.

correct. if that is not documented early on then there is a task to add some explanation on syntax conventions up front (can't check right now).

**Comment by eg9** [comment]
@tail-reversion Right.

There are a few cases where also the function with neither `T` nor `F` is defined, see for instance `\cs_if_exist_use:N` that exists along with `\cs_if_exist_use:NT`, `\cs_if_exist_use:NF` and `\cs_if_exist_use:NTF`, but it is explicitly mentioned in the manual.

A function such as `\str_if_eq:nn` would serve no purpose, as it would just gobble its two arguments. One might conceive code where `T` or `F` are added “dynamically” with `\cs_use:c`, but I'd discard such an idea because the number of arguments would not be known a priori.

**Comment by tail-reversion** [comment]
@FrankMittelbach 
> if that is not documented early on then there is a task to add some explanation on syntax conventions up front (can't check right now).

The `TF` underline conventions are documented, along with the stars for expandability, in Part I, Section 2: “Documentation Conventions”. All uses of these conventions also hyperlink to that section.

**Comment by shmuelmetz** [comment]
@eg9 I misremembered the underlining as meaning 4 forms rather than three. My intended use was as a predicate within a Boolean expression, and as such I want it to gobble up its arguments. I'll change it to \str_if_eq_p:ee.

If \namecref{#2} won't return the environment type for a label in an equation, what is the corrct way to query it?

Thanks.

**Comment by eg9** [comment]
@shmuelmetz 

> If \namecref{#2} won't return the environment type for a label in an equation, what is the corrct way to query it?

This is completely out of the scope of this site.
