### ISSUE TITLE
Enhancement: Allow multiple values in case

### ISSUE THREAD

**Issue by shmuelmetz** [latex3/latex3#543]
The various case statements, e.g., \int_case:nnTF, \tl_case:NnTF , allow a single value for each case. I would like to see an extension where you could provide a list of values and the code would be executed if any of the values matched. I'm not sure whether it would be feasible to overload the existing names, e.g.,

    \str_case:nn <test string> 
      {
        {<string case 1>} 
        {<code case 1>} 
        {
          {<string 1 case 2>}
          {<string 2 case 2} 
        }
        {<code case2>} 
        ... 
        {<string case n>}
        {<code case n>}
      }

**Comment by blefloch** [comment]
It would be good to have a tool for that.

For speed reasons this cannot be done by overloading the name: detecting any syntax like that would be much slower than the current code.

**Comment by FrankMittelbach** [comment]
At the moment this can be coded as 

```
\str_case:nn <test string> 
  {
    {<string case 1>} 
      {<code case 1>} 
    {<string 1 case 2>}
      {<code case2>} 
    {<string 2 case 2>} 
      {<code case2>} 
   }
    ... 
    {<string case n>}
      {<code case n>}
  }
```
which a little less clear as it is not obvious that the two code cases are the  same. But I'm not so sure that the use case happens often enough to come up with something like `\str_multi_case:nn` . Furthermore, that would then be less efficient compared to the above above as each branch would do a test if it is multi or single and that most likely takes more time than bypassing `<code case2>` twice.

**Comment by eg9** [comment]
Anything that avoids code duplication is interesting. On the other hand, making `\str_case:nn(TF)` much slower for dealing with a few use cases doesn't seem to be a good bargain.

Complex code that appears in several cases should be made into a function, so the code duplication is just repeating a function name.

**Comment by FrankMittelbach** [comment]
Which is why I think this is not something we should do. So I'll close this unless somebody strongly disagrees.

**Comment by shmuelmetz** [comment]
Would it still be too expensive if the interface used a clist for the case value rather than a tl?

**Comment by FrankMittelbach** [comment]
I don't think that makes any difference in processing. Besides, it would introduce a new syntax convention as we don't use comma separation on the level of programming. So the conclusion stays the same.

**Comment by blefloch** [comment]
We do in fact use clist at the level of programming: in
\cs_generate_variant:Nn and in \exp_args_generate:n.  This may be the
only place.

If you have a concrete use case (not just theoretical) we could see if
rewriting it along the lines suggested by Enrico and Frank.  This would
show us whether there is an added benefit.

**Comment by shmuelmetz** [comment]
Alas, while I have used multiple values in a single case in Ada and PL/I, I don't have a use case for LaTeX.


--
Shmuel (Seymour J.) Metz
http://mason.gmu.edu/~smetz3

________________________________________
