### ISSUE TITLE
l3keys : problem with \keys_set_known:nn and .inherit:n 

### ISSUE THREAD

**Issue by fpantigny** [latex3/latex3#548]
Consider the following code (with `expl3` of 2019-02-15):

``` 
\documentclass{article}
\usepackage{expl3}
\ExplSyntaxOn
\keys_define:nn { module1 } 
  { key1 .code:n = \tl_show:n { #1 } }
\keys_define:nn { }
  { module2 .inherit:n = module1 }
\keys_set_known:nn { module2 } { key1 = something }
\ExplSyntaxOff
\begin{document}
Some text.
\end{document}
```

The key `key1` is not executed as it should (with `\keys_set:nn` instead of `\keys_set_unknown:nn`, the key is executed).

**Comment by josephwright** [comment]
There's clearly a conceptual question here: I'm not entirely sure if this key is _known_ in a strict sense or not.

**Comment by josephwright** [comment]
Code here would be easy to change: it's only a question of the ordering of a couple of tests (see `\__keys_execute:`).

**Comment by fpantigny** [comment]
Yes. It's choice. For, me it appears more logical to considerer that the key is known.

**Comment by fpantigny** [comment]
I fear that, with the modification ededa4d, there will be another problem. Consider the following code:

    \documentclass{article}
    \usepackage{expl3}
    \ExplSyntaxOn
    \keys_define:nn { module1 } 
      { key1 .code:n = \tl_show:n { #1 } }
    \keys_define:nn { }
      { module2 .inherit:n = module1 }
    \keys_set_known:nn { module2 } { key1 = something , key2 }
    \ExplSyntaxOff
    \begin{document}
    Some text.
    \end{document}

LaTeX will now complain with an unknown key `key2`.

Maybe the solution is to modify `\l__keys_execute_unknown:` with a test on `\l__keys_only_known_bool`:

    \cs_set_protected:Npn \__keys_execute_unknown:
      { \bool_if:NF \l__keys_only_known_bool
          {
            \cs_if_exist:cTF
              { \c__keys_code_root_tl \l__keys_module_tl / unknown }
              {
                \cs:w \c__keys_code_root_tl \l__keys_module_tl / unknown
                  \exp_after:wN \cs_end: \exp_after:wN { \l_keys_value_tl }
              }
              {
                \__kernel_msg_error:nnxx { kernel } { key-unknown }
                 { \l_keys_path_tl } { \l__keys_module_tl }
              }
          }
      }
