### ISSUE TITLE
l3sys breaks on TeX Live 2017

### ISSUE THREAD

**Issue by stone-zeng** [latex3/latex3#555]
In d2e8cbac25d1377baeaf9bfdddf19f989f9bc6b2, defensive code for redefinition of `\time`, `\day`, `\month` and `\year` have been added. However, on TeX Live 2017, it may break:

```latex
\documentclass{article}
\usepackage{expl3}
\begin{document}
Hello
\end{document}
```

which gives the error:

```latex
! Missing number, treated as zero.
<to be read again> 
                   \primitive 
l.7649 ...d:nn { \tex_primitive:D \time } { 60 } }
                                                  
A number should have been here; I inserted `0'.
(If you can't figure out why I needed to see a number,
look up `weird error' in the index to The TeXbook.)
```

Although TL2019 is about to release, overleaf is still using TL2017 (actually this test is on overleaf), and it seems that they will not change to the latest distribution in the very near future.

**Comment by wspr** [comment]
Does Overleaf using TL2017 but update somehow to the latest expl3? Or do you manually add the new expl3 code to your Overleaf document? (Neither right or wrong, I think, just trying to get a better picture here.)

**Comment by stone-zeng** [comment]
I upload the latest `expl3` manually.

**Comment by josephwright** [comment]
I've just checked on TL'17 as as I'd expect everything is fine. Did you upload (or create) a copy of `expl3` with code from mis-matched sources?

**Comment by josephwright** [comment]
I get an issue on Overleaf but that's becuase they seem to have TL'14 and the older format that doesn't recognised `YYYY-MM-DD` years. So I uploaded `latexrelease` and got
```latex
\RequirePackage[2018-12-01]{latexrelease}
\documentclass{article}
\usepackage{expl3}
\begin{document}
Hello
\end{document}
```
to work fine. No issue at all with the `\year` code.  (See https://www.overleaf.com/project/56536ff84afad55f1198b468: my 'scratch' project.)

**Comment by eg9** [comment]
Indeed, compiling
```latex
\documentclass{article}
\begin{document}
\input{|"kpsewhich -var-value=TEXMFMAIN"}
\end{document}
```
on Overleaf produces
<img width="281" alt="Screen Shot 2019-03-20 at 09 50 07 " src="https://user-images.githubusercontent.com/302839/54671171-a956ed00-4af5-11e9-86cd-197e0635ed9a.png">

This is a stopper for using or recommending Overleaf.

**Comment by josephwright** [comment]
@eg9 Interesting: there's no obvious way to change that. I've created a second test project ...

**Comment by josephwright** [comment]
Second project: https://www.overleaf.com/project/5c920aff3c967329130e1ebe. Again, I have no issues.

**Comment by stone-zeng** [comment]
Why you have the `latexrelease` package for the future features :joy:?

Line 974-982:

```latex
\IncludeInRelease{2019/04/01}%
  {\InputIfFileExists}{Don't lose the file name}%
\long\def \InputIfFileExists#1#2{%
  \IfFileExists{#1}%
    {%
  \expandafter\@swaptwoargs\expandafter
      {\@filef@und}{#2\@addtofilelist{#1}\@@input}}}
\long\def\@swaptwoargs#1#2{#2#1}
\EndIncludeInRelease
```

**Comment by stone-zeng** [comment]
I find that pdfLaTeX and LuaLaTeX can run it (even without `latexrelease`), but XeLaTeX can't.

**Comment by josephwright** [comment]
@stone-zeng Ah right: we are talking about engines which pre-date addition of `\(pdf)primitive` support. I can make the code more defensive there, but first I think the team may need to consider which engine versions we want to support.

**Comment by josephwright** [comment]
@eg9 I don't think TL'17 is in itself an issue, but we do need to be thinking about what features are available.

**Comment by josephwright** [comment]
We could just go back to only defining the various constants if `\<thing>` as a primitive exists ...

**Comment by blefloch** [comment]
I'd rather go for

\int_const:Nn \c_sys_year_int
  {
    \str_if_eq:eeF { \cs_meaning:N \year } { \year }
      { \primitive }
    \year
  }

or similar (not tested), where we define the integer in all cases, but
only use \primitive if needed.

**Comment by josephwright** [comment]
@blefloch  Well yes but that still leaves us needing `\primitive`, which may not exist (older XeTeX, (u)pTeX) or work (XeTeX in TL'2017). Yes, we can test all of those cases but ... do we _really_ want to do that? I was thinking
```latex
\int_const:Nn \c_sys_year_int
    {
      \str_if_eq:eeF { \cs_meaning:N \year } { \year }
        { \year }
        { 0 }
    }
```
or similar.

**Comment by blefloch** [comment]
I was thinking about the situation going into the future.  Packages that
mess up \year will always exist, but engines without \primitive won't
always exist.

On the other hand your suggestion is easier to document.  Actually, let
me change my mind to your suggestion, plus a warning (saying to load
expl3 earlier) if \year is not found.  With your approach, to get the
correct \year one simply needs to load expl3 early enough.

**Comment by josephwright** [comment]
In the end, the extra code is not _too_ bad so I've added it. We can look again at this area when/if we require `\expanded` (as that will automatically include `\primitive` in all current engines, and certainly deals with the XeTeX issue).
