### ISSUE TITLE
trigonometric functions should return random values for large floating point inputs

### ISSUE THREAD

**Issue by jfbu** [latex3/latex3#556]
Consider Avogadro's number. Starting May 20, 2019, it fill be fixed to have exact value N_A = 6,022 140 76 × 10^23 mol^(−1). (dixit [French Wikipédia](https://fr.wikipedia.org/wiki/Nombre_d%27Avogadro).)

Now does it make sense to compute its sine or cosine ? we see that 0, 000 000 01 x 10^23 is 10^15. That's many many intervals of length 2π. Hence the only possible conclusion is that the sine is random.

Generally, working with floating point numbers of 16 digits mantissas, a number such as 1e20 for example represents an equivalence class of real numbers. But this equivalence class comprises a multitude of full 2π length intervals. Thus the sine of 1e20 has only meaning as a random variable.

Now, I see that fp Latex3 module ensures exact range reduction for its range of exponents (up to 9999 if I understand correctly). This needs 10000 digits of the decimal expansion of π, which end up in TeX memory. Of course this is very well done, but does it have any mathematical sense ?

I think Latex3 could go the more economical way and renounce such perfection...

Of course this is not real issue, but a topic of discussion.

**Comment by blefloch** [comment]
> Now does it make sense to compute its sine or cosine ?

Physically?  No.  Mathematically?  Yes.  Does it give useful
information?  Most likely not.  Is it random?  Definitely not.

See IEEE 754 standard, section 9.2 (at least in one of the latest drafts
for the 2019 revision), concerning trig functions and the like: "A
conforming operation shall return results correctly rounded for the
applicable rounding direction for all operands in its domain." Given the
rest of the standard, this pretty clearly means that range reduction has
to be done exactly.

> Generally, working with floating point numbers of 16 digits mantissas, a
> number such as 1e20 for example represents an equivalence class of real
> numbers.

Definitely not.  If you want that, use unums or interval arithmetic,
which is unfortunately not implemented in l3fp.

> I think Latex3 could go the more economical way and renounce such
> perfection...

Not a real issue.  The data you're talking about is 0.7% of the expl3
source code in terms of lines of code.  And it is stored much more
efficiently than TeX macros, because blocks of 8 digits are stored in a
32bit \fontdimen entry, which takes as much space as one token in a
macro definition.  So the data takes around 5 kilobytes at run-time.
Compare for instance with the 4 megabytes of the format I get by loading
latex.ltx.

On the other hand I wouldn't be opposed to reducing the exponent range
to ±384, which is the standard IEEE value (roughly, I didn't check
exactly), and which would save us some pain when computing exponentials,
logs, or powers, in addition to saving on trig argument reduction.

**Comment by jfbu** [comment]
Let `x = 10^3`, let `y = x^7 - 1` let `z = y + 2`. Do we mathematically have `y = z`? No. Now let's compute with xfp or Python or whatever working with floats of 16 digits precision. We find that both `y` and `z` have the same internal representation. Now we compute `sin(y)` or `sin(z)` we get the same result. Does the result have any mathematical meaning? No. It is the correct rounding of the mathematical value of `sin(10^21)` from which we could indeed deduce (almost) the correct rounding of `sin(10^21-1)` and `sin(10^21+1)` (but this _assuming_ we know that in fact we are handling one of `10^21±1` and not some other number rounding to `10^21`), but the whole point of the floating point format is to replace the exact `y` and the exact `z` by some approximation. Now this means that internal representations are equivalence class of real numbers ; as an operation even as basic as multiplication does not pass over to the quotient by the equivalence relation, a choice is made of canonical representants from those equivalence classes and the exact math operation is applied to the representants and then the canonical representant of the equivalence class of the result is decided to be the generally usable value. Hence many completely different roads will create numbers being represented by `10^21`. Only some such roads would have given the exact  `10^21`. If one makes an expression ending up into evaluation of `sin(10^21)`, what one gets from the computation is in 99% of cases basically meaningless quantity.

No engineering value, nothing having any use in anything except from the pure theoretical consideration of exact `sin(10^21)` can benefit from this when such computation arises from quantities involved in real problems.

Let me now consider `x=5^25` and `y=x^2`. The exact  `x` is `298023223876953125` which gets represented by `2.980232238769531e17`, we compute the square of that this gives correctly rounded `8.881784197001251e34`, which represents `y`. But `5^50` is exactly `88817841970012523233890533447265625`. Is there any relation between the mathematical `sin(5^50)` and `sin(y)`. None.

This means that such computations have no meaning except for the very very very very rare case that someone somewhere sometime does need mathematical `sin(5^50)`. I can not imagine any human circumstance leading to the need for that value.

Yes, there are some standards, now do we have to conform to standards ? The standards have their admirable internal logic but they cover a too vague utility range when reaching to the limits of the whole concept of "floating point numbers".

I maintain that, all admiration for brilliant implementation being put aside for a minute, it would be perfectly legitimate to return a random value, according to the value distribution of the sine function. A user employing multiple times `sin(5^50)` should let xfp do the random evaluation once and assign the result to a variable if it is intended to make multiple usages of this (meaningless) computation result.

**Comment by jfbu** [comment]
(in my comment I referred to Python ; naturally it uses radix 2, not 10)

**Comment by blefloch** [comment]
While I mostly agree with @jfbu, it is much better to default to following harmless standards than cooking up one's own.  Returning random values is completely unreasonable as running the same document several times or on different machines would give different results.  Returning values based on some chosen approximation of pi would be reasonable.

The main point of this discussion seems to be about whether it was wise to write the code in the first place.  Maybe it wasn't, but certainly now that it is written rewriting it to make the results objectively worse isn't a good idea.
