### ISSUE TITLE
\@firstoftwo and \@secondoftwo should be mentioned in "The LaTeX3 Interfaces" documentation

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#563]
While "The LaTeX3 Interfaces" documentation contains numerous "TeXhackers notes", one is missing IMHO: that `\use_i:nn` and `\use_ii:nn` are the equivalent to LaTeX2ε’s `\@firstoftwo` and `\@secondoftwo`.

**Comment by eg9** [comment]
The current TeXhackers notes are only about primitives or about technical details.

I only find references to LaTeX's `\newif` and `\leavevmode` for warning about differences. This doesn't mean that your suggestion is to be rejected, though. Indeed, the description at the top reads

> In some cases, the function is similar to one in LaTeX2ε or plain TeX. In these cases, the text will include an extra “TeXhackers note” section

and this might be a case where to recall a very common construction in LaTeX. On the other hand, conditionals in `expl3` are quite different and the usage of `\use_i:nn` and `\use_ii:nn` somewhat rarer.

**Comment by blefloch** [comment]
Yes, there should certainly be TeXhacker notes about \@firstoftwo etc
(including \@gobble and \@firstofone).
