### ISSUE TITLE
Support for HarfTeX

### ISSUE THREAD

**Issue by josephwright** [latex3/latex3#567]
At present, we support five engines (pdfTeX, XeTeX, LuaTeX, e-pTeX, e-upTeX). The [HarfTeX](https://github.com/khaledhosny/harftex) project is something we should likely be thinking about.

We need to address two things. First, we need a marker that HarfTeX is in use: @khaledhosny an hopefully illuminate us there. We also need to think about the `\sys_if_engine...` situation: for e-pTeX and e-upTeX, testing for both does need a `\bool_lazy_or:nnTF`, so perhaps we end up with
```latex
\bool_lazy_or:nnT
  { \sys_if_engine_luatex_p: }
  { \sys_if_engine_harftex_p: } 
  {
    % Code using Lua
  }
```
or perhaps we need a specific test.

**Comment by khaledhosny** [comment]
There is two new HarfTeX-specific primitives, `\harftexversion` and `\harftexrevision` (which should work similar to the corresponding LuaTeX primitives). All existing LuaTeX primitives are kept unchanged, so `\sys_if_engine_luatex_p` should be true for HarfTeX as well. In general, the intention is for HarfTeX is to behave like LuaTeX for all practical purposes, as long as no HarfTeX-specific features are used.

**Comment by josephwright** [comment]
@khaledhosny No, `\sys_if_engine_luatex_p:` should be false for HarfTeX as it is _not LuaTeX_. The switches are meant to be true for _exactly one_ engine, or at least that was the decision with pTeX/upTeX, where again there is a lot of overlap.

Assuming that the rest of the team agree on this, I'll do a quick pass over `expl3` and adjust. Of course, that means a knock-on for things like `fontspec`. So there is likely to be at least a little discussion first!

**Comment by khaledhosny** [comment]
That is up to you to decide, I’m not arguing with that. What I meant to say is that right now such code would think it was running under LuaTeX, for better or worse.

**Comment by josephwright** [comment]
@khaledhosny Sure: any change will need to be done carefully such that it maintains a working set up for HarfTeX. I'll perhaps add the two new primitives to `l3names` (I think the team want to support HarfTeX!), but will wait on any other changes to see if everyone else agrees with the conceptual split.

**Comment by davidcarlisle** [comment]
@josephwright  I'm not sure. (Haven't tried to build harftex yet but assuming it's not so different from earlier luahbtex trials the difference between harftex and luatex loading a compiled harbuzz lua module are not relevant in almost all cases.


people will use `\sys_if_engine_luatex_p:` to mean "can I use `\directlua` ? if that's false for harftex a lot of code that could work will not work.

I think we could consider making that true for both and some other `\sys_if` to distinguish them.

**Comment by josephwright** [comment]
@davidcarlisle We had this as I say with pTeX and upTeX (OK, very different issue in many ways). There, we took the line that `engine_<name>` means exactly one engine. Arguably, if we want a 'supports Lua' switch it should say exactly that: `\sys_if_lua_enabled:TF`?

**Comment by josephwright** [comment]
@khaledhosny I assume once you get more leverage on the project you won't define `\luatexversion` in HarfTeX?

**Comment by josephwright** [comment]
Alternatively, as HarfTeX is I guess _strictly additive_ to LuaTeX (right?), one might argue that it is OK for it to test positive for being LuaTeX, and that we then a second switch purely to know if the 'HarfTeX extensions' are available. (Contrast with pTeX/upTeX: upTeX is more capable than pTeX from the get-go.)

**Comment by khaledhosny** [comment]
I’d like to keep it, in the same way that LuaTeX keeps `\eTeXversion`, and also because one might actually want to check for a certain LuaTeX behavior based on its version as I intend to keep HarfTeX in sync with LuaTeX as much as possible.

Things might change in the future and there might be breaking changes, but none is planned right now.

**Comment by davidcarlisle** [comment]
On Fri, 26 Apr 2019 at 21:48, Joseph Wright <notifications@github.com>
wrote:

> @davidcarlisle <https://github.com/davidcarlisle> We had this as I say
> with pTeX and upTeX (OK, very different issue in many ways). There, we took
> the line that engine_<name> means exactly one engine. Arguably, if we
> want a 'supports Lua' switch it should say exactly that:
> \sys_if_lua_enabled:TF?
>
> —
>

yes but the differences between ptex and uptex are more pervasive affecting
end user document functionality,  luatex and harftex are the same source
(for the non harfbuzz bits) and apart from interfacing to fontspec should
be indistinguishable for almost all expl3 code, adding \expanded to xetex
makes more difference in terms of the kind of code that's likely to be
testing `\sys...` capability but xetex+\expanded is still xetex, whereas
luatex+harfbuzz linked to the executable is not but  luatex with harfbuzz
loaded via a compiled lua module is...
I don't think "exactly one engine" is a completely well defined thing, we
just need to provide whatever boolean switches seem useful.

I don't mind much, I think I'd prefer \sys_if_engine_luatex_p: to be true
but if we make it false we should recommend that's only used for _very_ low
level code and most  package code should use \sys_if_engine_something_p:
which we should provide that is true for both

**Comment by wspr** [comment]
I don’t have a strong opinion about the booleans.
With distinct  \sys_if_engine_luatex_p: and  \sys_if_engine_harftex_p: this means LuaTeX package authors need to explicitly add support to their work if there is ever an error check or similar.

With overlapping booleans, all code continues to run without modification on either engine, and if a difference is needed only then is  \sys_if_engine_harftex_p: required.

If the stated aim of HarfTeX is retain compatibility with LuaTeX I think the latter option is the more pragmatic choice. If there is ever a bifurcation, we could reassess.

**Comment by josephwright** [comment]
I guess I'm happy to leave the LuaTeX tests alone as long as the current understanding is that HarfTeX is treating LuaTeX much like pdfTeX/LuaTeX/XeTeX treat e-TeX. The one thing we might want to consider is that to return for the engine name/version strings. Like I said, at some stage 
we also presumably will want a 'HarfTeX extensions' switch.

Probably we should document that we support it, too.
