### ISSUE TITLE
Infinite loop with expl3 and landscape page

### ISSUE THREAD

**Issue by josephwright** [latex3/latex3#570]
As reported on the TeX Live list
```latex
\documentclass[landscape]{article}
\usepackage{expl3}
\begin{document}
\begin{center}
  \rule{1.1\linewidth}{1.1\linewidth}
\end{center}
\end{document}
```
gives a loop in DVI mode.

**Comment by josephwright** [comment]
The problem is the `\special` added to `\@startcolumn` for link breaking.

**Comment by car222222** [comment]
Do you mean that expl3 is trying to interface with the 2e OR?  For example, by Adding stuff to  startcolumn?

**Comment by josephwright** [comment]
@car222222 There is an addition to `\@startcolumn` that came from the package `hypdvips` which amongst other things allows breakable links in DVI mode. @davidcarlisle suggested various torture tests to make sure that code was robust, and it worked pretty well, plus of course it's been in public for years. However, we missed this particular case.

If there is no good way to put the special in safely then I'll have to strip out the breakable link code, or at least make it user-selectable as a load-time option for `expl3`. I find it hard to believe there is nowhere that we can find for 'if a column has some output, add this special'.

**Comment by josephwright** [comment]
I've gone for a fix that deals with the issue: we may still need to do more here, but hopefully the idea is workable.

**Comment by car222222** [comment]
@josephwright   “There is an addition to \@startcolumn that came from the package hypdvips which amongst other things allows breakable links in DVI mode.”  So I am questioning whether such an interface to 2e document processing code should be in expl3.  It may be Better to keep such stuff in a package until we have completely built all such interfaces between 2e and expl3?

**Comment by josephwright** [comment]
@car222222 The specific code here is used to enable breakable links in DVI mode. The interface we provide for links in general is currently very low-level and doesn't in general impinge on LaTeX2e.

The one thing we need is a place to put some PostScript to allow the link breaking stuff to work. I'm not sure what interface we would look to add to LaTeX2e for that: it's a very specific thing and it's going to look exactly the same if we do it by adding a hook from the `expl3` side. If we want to add a hook to the LaTeX2e kernel to do this, we end up with co-dependency issues: what do we do if loaded on an older format?

We have a few other places we have to hook in for stuff to work: the most obvious one is to allow `\ProvidesExplPackage` to push/pop the syntax status  (we modify `\@pushfilename`/`\@popfilename`).

**Comment by car222222** [comment]
@josephwright  “We have a few other places we have to hook in for stuff to work:”
Sure, But the current strategy (as i understand it) is to build proper interfaces for these (and many more) into the basics of 2e.  Noting that There will be more than a few of these “getting stuff to work” requirements over time!   

It seems to me that Putting the currently needed ad hoc hooks to the current 2e into expl3 makes them look too permanent, as if “using a few such hooks” is the future development route for 2e + expl3: Maybe you believe that this is the intended development route?  Rather than the “mild refactoring” of 2e to provide generic, fully documented, commands that function like luatex call-backs and can therefore be replace by any code with the necessary PRE and POST conditions (assuming that this terminology is still used??) 

Such ad hoc hooks may be needed temporarily to enable immediate experiments in the use of L3PL ideas with the 2e document processing model, but these should be in packages, not in expl3 itself.  Indeed, as I have said before, no document processing stuff should be “just another module” in a house homogeneous, and over-crowded expl3!

**Comment by josephwright** [comment]
@car222222 Certainly that is one way of looking at it. @davidcarlisle and I were wondering if we should back stuff out simply because any change here is likely risky.

I can look to shift the 'break links' code into a separate package which then has to be loaded separately. I'll see what others think.

**Comment by josephwright** [comment]
Other than the hook, I think the a spin-out would just be the PostScript code: we can leave stubs in the macro code.

**Comment by josephwright** [comment]
I've been looking at where a hook would be needed. One could just have right at the start of `\@makecol`, something like `\every@makecol`.
```latex
\gdef \@makecol {%
   \every@makecol
   \ifvoid\footins
     \setbox\@outputbox \box\@cclv
   \else
 ...
```
Or one could set up explicitly to add stuff to the start and end of the box content, so we might have `\every@makecol@begin` and `\every@makecol@end` or similar.
```latex
\gdef \@makecol {%
   \ifvoid\footins
     \setbox\@outputbox \vbox{\every@makecol@begin\box\@cclv\every@makecol@end}%
   \else
     \setbox\@outputbox \vbox {%
       \boxmaxdepth \@maxdepth
       \every@makecol@begin
       \unvbox \@cclv
       \every@makecol@end % Here?
       \vskip \skip\footins
       \color@begingroup
         \normalcolor
         \footnoterule
         \unvbox \footins
       \color@endgroup
       }%
   \fi
```

The first version is more or less the same code as I've currently added using `expl3`. Of course, the issue then is what happens if `expl3` is loaded with an older kernel. That's a particular problem for online systems.

**Comment by josephwright** [comment]
I guess we need input from @FrankMittelbach here. I'm wondering what to do about the bug itself.

**Comment by davidcarlisle** [comment]
On Sat, 4 May 2019 at 21:46, Joseph Wright <notifications@github.com> wrote:

> I guess we need input from @FrankMittelbach
> <https://github.com/FrankMittelbach> here. I'm wondering what to do about
> the bug itself.
>

possibly push a release of expl3 that adds the the begin/end hooks to
makecol if they are not already there, but with empty content

then later have a package interface to adding the specials for links

perhaps...

**Comment by josephwright** [comment]
@davidcarlisle So strip out the breakable link concept for the present? It will be in the history and I can give us a nice clear commit message (it's also in `hypdvips` and I now get how it works in at least part).

**Comment by u-fischer** [comment]
Couldn't the code stay but be activated/used only if the makecol-hook is there? Then one could offer a small package to add the hooks, until the hooks are in latex?

**Comment by josephwright** [comment]
@u-fischer  Sure, that is more-or-less the same plan as stripping out the code into a separate package. It's only a question of adding a couple of conditionals or holder functions which allow us to activate/deactivate the bits and pieces (`\hbox_unpack:N` _versus_ `\box_use:N` and a couple of hooks for the PostScript).

**Comment by davidcarlisle** [comment]
well personally I'd not object to leaving it all in, but if we want to aim
for mostly package interfaces to extensions then adding the hooks now via
expl3 gives a way to do that without being tied to a future format update

**Comment by u-fischer** [comment]
@josephwright  It would be a pity to strip out the code completly. Breakable links is something  dvips users would imho value.

**Comment by josephwright** [comment]
@u-fischer I'm thinking strip out for the present so we can fix the issue here and get a consistent position on the hooks we need. The make the idea available in a way that we are all happy with, which basically comes down to how we inject the PostScript into `\@makecol` (or somewhere else,if Frank feels there is a better place).

**Comment by josephwright** [comment]
@davidcarlisle  So you'd like something like create a hooks package of some sort, and have `expl3` core use the hooks if available (`\AtBeginDocument`?) and otherwise stick to non-breakable links here? That means we have a clearly-defined way to adjust the core 2e behaviour which is separate from the programming part of `expl3`. Just leaves me having to allow for that delay. I suspect I'll need something like that anyway, so will start on the necessary auxiliaries.

**Comment by josephwright** [comment]
I've put a suggestion in https://github.com/latex3/latex3/tree/makecol. The idea is that all of the code is in place for breakable links, but none of it is active unless we find a hook I've called `\@makecol@hook`. That then has the same code we've already got set up attached. If we go with this, there are no changes to LaTeX2e unless the user opts-in: we'll need a way to do that better than 
```latex
\ExplSyntaxOn
\tl_new:c { @makecol@hook }
\tl_put_left:cx { @makecol } { \exp_not:c { @makecol@hook } }
\ExplSyntaxOff
```

Thoughts on the nature  of the hook, _etc., welcome: this fixes both the technical issue and I think the conceptual question (@car222222 ?).

**Comment by josephwright** [comment]
We have a similar discussion, I guess, about the idea of a shipout hook .. though that may be covered by inlining `atbegshi`.

**Comment by FrankMittelbach** [comment]
> possibly push a release of expl3 that adds the the begin/end hooks to
> makecol if they are not already there, but with empty content

I don't think it would be good if we add hooks now in one or two places 
with namesthat in the end we may not want and then want to 
change/normalize. I'm all for adding hooks soon but not so much adding 
some now and then possibly fairly soonish changing them (or being forced 
to keep their names even though they do not quite fit others nearby)

**Comment by josephwright** [comment]
@FrankMittelbach Well we could miss out the 'activation' part, just have the 'hidden' mechanism for breaking links. That way we don't loose the code in the history, but we don't create a hook. For testing, we can make a hook manually then decided on a name. Basically that means just removing 
```latex
\AtBeginDocument
  {
    \cs_if_exist:NT \@makecol@hook
      {
        \tl_put_right:Nn \@makecol@hook
          {
            \box_if_empty:NF \@cclv
              {
                \vbox_set:Nn \@cclv
                  {
                    \@@_postscript:n
                      {
                        driver.globaldict /driver.brokenlink.rect ~ known
                          { driver.bordertracking.continue }
                        if
                      }
                    \vbox_unpack_drop:N \@cclv
                    \@@_postscript:n
                      { driver.bordertracking.endpage }
                  }
              }
          }
        \tl_clear:N \l_@@_breaklink_obj_tl
        \tl_set:Nn \l_@@_breaklink_pdfmark_tl { driver.pdfmark }
        \cs_set_eq:NN \@@_breaklink_postscript:n \@@_postscript:n
        \cs_set_eq:NN \@@_breaklink_usebox:N \hbox_unpack:N
    }
  }
```
or if we want to leave it there for reference, making it `\use_none:n`.

**Comment by FrankMittelbach** [comment]
Am 05.05.19 um 10:15 schrieb Joseph Wright:
> @FrankMittelbach <https://github.com/FrankMittelbach> Well we could miss 
> out the 'activation' part, just have the 'hidden' mechanism for breaking 
> links. That way we don't loose the code in the history, but we don't 
> create a hook. For testing, we can make a hook manually then decided on 
> a name. Basically that means just ...

I would suggest to do something like this - Frank

ps will be without internet again soon. Not sure when I have any again 
during the next days

**Comment by josephwright** [comment]
I'll go with the 'present but disabled' plan: we can deal with the nature of the hook required in a new issue if necessary.
