### ISSUE TITLE
About \driver_pdf_objects_disable:

### ISSUE THREAD

**Issue by zauguin** [latex3/latex3#571]
I think the naming and description of `\driver_pdf_objects_{en,dis}able:` is a bit unfortunate:
They are documented as:
> Enables or disables the creation of PDF objects.

Disabling the creation of PDF objects while still generating a PDF file sounds like a really bad idea(TM), because everything in a PDF file is a PDF object. So this would basically disable any output.

I guess this setting is actually supposed to disable the generation of *object streams* and instead use regular PDF objects. In this case I would recommend changing the documentation and maybe even their names.

**Comment by josephwright** [comment]
I'd welcome suggestions on how to handle this particular concept. I've not been entirely happy with enable/disable, but the subtleties seem extremely unlikely to be useful.

The setting only affects non-stream objects and whether they are converted to compressed streams. I guess it could be `\driver_pdf_compress_objects:n` (taking `true` or `false`), or `\driver_pdf_compress_objects_(en|dis)able:` (in which case perhaps renaming `\driver_pdf_compresslevel:n` too).

**Comment by u-fischer** [comment]
I'm not quite happy with the name either but I'm unsure what would be better. Perhaps one should stick to something near the pdf/luatex naming and use `\driver_pdf_objcompress_disable:` and internally `\__driver_pdf_objcompresslevel:n`, but `\driver_pdf_compress_objects_(en|dis)able:` sounds ok too.

**Comment by zauguin** [comment]
Personally I would prefer `\driver_pdf_compress_objects:n`, but all the options look good IMHO :+1:

**Comment by josephwright** [comment]
@zauguin What's the argument you expect in that case? pdfTeX has various values, which I think are a bit confusing, but for `dvipdfmx` it's a yes/no.

**Comment by zauguin** [comment]
@josephwright I think only `true` / `false` is useful: pdfTeX's option `1` is intended to be used if there are problems caused by embedded files. So I think it makes sense to hide the choice between `1` and `2` in the kernel, then this can be changed to `1` if anyone should actually discover such problems.

On the other hand exposing `3` might be useful. I do no think that it should be the default, especially because searching for a document becomes harder if `3` is enabled and the Info dictionary is compressed, but especially with Unicode engines it might have some uses: The Info dictionary might contain arbitrary additional metadata according to the PDF specs, e.g. I once seen a file which included a whole abstract there. So it can be quite big and with Unicode engines it isn't searchable with non-PDF readers anyway, so I certainly see why people might want it compressed.

But I think this should not be controlled by `\driver_pdf_compress_objects:n` even if it is supported. E.g. if there would be a package setting some big-ish metadata, this package might want to enable object compression for the Info dictionary.
But I do not think that this should enable object compression if that is disabled globally, so I think it would be more useful to add a second command controlling the choice between `objcompresslevel` `2` or `3`. Maybe there could be something like `\g_driver_pdf_compress_objects_level_int`, such that `\driver_pdf_compress_objects:n{true}` uses the level defined in `\g_driver_pdf_compress_objects_level_int`. Then there is an easy `true/false` interface for most cases but for special cases the other options would be available too.

**Comment by josephwright** [comment]
I've gone for `\driver_pdf_compress_objects:n` but have left the details of the compress level out: it's only relevant to pdfTeX/LuaTeX and we can revisit that later if required. Hopefully the new name is nice and memorable.
