### ISSUE TITLE
Unexpected result when \tl_lower_case:n argument contains \TeX macro

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#574]
If `\tl_lower_case:n` (and `\tl_mixed_case:n`) argument contains the `\TeX` macro, the result is not the expected one (\TeX logo but with lowercase "t", "e" and "x"). By contrast, no problem with `\LaTeX` macro (probably related: [\TeX and \LaTeX differently expl3-x-written (exhaustive expansion) to an auxiliary file](https://tex.stackexchange.com/q/490125/18401)).

```latex
\documentclass{article}
\usepackage{expl3}
\begin{document}
\ExplSyntaxOn
\tl_lower_case:n{foo~and~\TeX{}~and~\LaTeX{}~are~nice!}~

\tl_mixed_case:n{foo~and~\TeX{}~and~\LaTeX{}~are~nice!}~

\tl_upper_case:n{foo~and~\TeX{}~and~\LaTeX{}~are~nice!}
\ExplSyntaxOff
\end{document}
```
![test](https://user-images.githubusercontent.com/1032633/57554692-6afde180-7372-11e9-848d-1e1aeb9849b2.png)

**Comment by josephwright** [comment]
This is 'not our fault' at the `expl3` end: the current definition of `\TeX` is not one of the special cases that gets skipped. I'd probably
```latex
\usepackage{etoolbox}
\robustify{\TeX}
```

**Comment by FrankMittelbach** [comment]
It should get resolved if we robustify more 2e user level commands via https://github.com/latex3/latex2e/issues/123

**Comment by car222222** [comment]
Yes, \TeX (and a few other macros that are left-over/unchanged from plain) are in the list labelled “definitely make robust”.
