### ISSUE TITLE
xparse: Space before \SplitArgument is passed to output

### ISSUE THREAD

**Issue by mikkelee** [latex3/latex3#578]
Hi

When using `xparse` and `\SplitArgument`, a space before the latter will be passed to output — the example in the documentation has a space, though (release date in docs 2019-03-05).

Example:

```latex
\documentclass{article}

\usepackage{nicefrac}
\usepackage{xparse}

\makeatletter

\newcommand\@dato[3]{%
	% contents of this irrelevant for discussion
	\nicefrac{#1}{#2}\IfValueT{#3}{~#3}%
}
\NewDocumentCommand\datoA{ > { \SplitArgument { 1 } { / } } m o }{%
	% notice space before \SplitArgument
	\@dato#1{#2}%
}
\NewDocumentCommand\datoB{ > {\SplitArgument { 1 } { / } } m o }{%
	% no space before \SplitArgument
	\@dato#1{#2}%
}

\makeatother

\begin{document}

Space before \string\datoA: (\datoA{18/1}[1785])

No space before \string\datoB: (\datoB{18/1}[1785])

Space before \string\datoA: (\datoA{18/1})

No space before \string\datoB: (\datoB{18/1})

\end{document}
```

**Comment by josephwright** [comment]
I don't think we've every said there is any special treatment of spaces in `xparse`: we usually have the declarations inside `\ExplSyntaxOn`, which allows us to 'spread', but that's not a requirement. On the other hand, I guess only the active processor should affect the output.

**Comment by blefloch** [comment]
I guess we could be nice and run the processor in a \setbox0\hbox{...}?
 Then of course smuggle the \ProcessedArgument outside the group.

**Comment by josephwright** [comment]
Don't we just need to trim spaces inside the argument to `>`, then TeX will clean up between the arguments to `\Split...` or whatever.

**Comment by mikkelee** [comment]
💯 thanks for speedy reply & resolution!
