### ISSUE TITLE
\tl_map_variable:nNn should save/restore #2

### ISSUE THREAD

**Issue by wspr** [latex3/latex3#581]
See discussion here: https://tex.stackexchange.com/q/492857/179 — in short, 

    \tl_map_variable:nNn {abc} \l_foo_tl {\tl_use:N \l_foo_tl}
    \tl_use:N \l_foo_tl

is an infinite loop as `\l_foo_tl` contains a quark. Unless I'm missing something, I think the state of that variable should be manually saved and restored as part of the mapping function?

(I'm happy to make the change, just in a rush at the moment.)

**Comment by u-fischer** [comment]
Imho `\l_foo_tl` is a temporary variable and one shouldn't expect that is has a sensible value  after the mapping (and if I had expected a sensible value it would have been the last token `c` and not the value before the mapping). But perhaps it would a good idea to remove the quark to prevent unclean code to loop.

**Comment by PhelypeOleinik** [comment]
I think that it would be a nice _feature_ to have `\(tl,seq,clist,...)_map_variable:nNn` restore the contents of the `⟨tl var⟩`, however it would imply some sort of grouping which is not actually done, so I agree with @u-fischer that a sensible choice would be the last item in the loop or nothing at all.

However, whatever option is taken, it should be mentioned in the documentation, as currently this is not mentioned (not that I could find, at least).

**Comment by eg9** [comment]
I concur that the tl variable should be set to nothing or whatever else, _except_ `\q_recursion_tail`.
In my opinion, clear it is the best choice, as the variable only makes sense during the loop.

**Comment by josephwright** [comment]
Something as simple as
```latex
\cs_new_protected:Npn \tl_map_variable:nNn #1#2#3
  { \exp_args:NV \@@_map_variable:nnNn #2 {#1} #2 #3 }
\cs_new_protected:Npn \@@_map_variable:nnNn #1#2#3#4
  {
    \@@_map_variable:Nnn #3 {#4} #2
      \q_recursion_tail
    \prg_break_point:Nn \tl_map_break:n { \tl_set:Nn #3 {#1} }
  }
```
would work (same approach for other functions).

**Comment by wspr** [comment]
I see no conflict / confusion with saving and restoring the value of the variable, even in the absence of grouping. (Documented with wording along the same lines: “The mapping is done at the current group level and the temporary variable is restored to its previous state once the mapping is complete”)

It’s barely more time/memory than clearing the variable after the loop, and if it saves just one bug it’s probably worth it :)

**Comment by wspr** [comment]
@josephwright Possible edge case? — if `#2` doesn't exist a different branch might be needed.

**Comment by blefloch** [comment]
The easiest thing to do would be to swap the quark test and variable
assignment in the loop (at the cost of using an n-type quark test
instead of an N-type quark test).  Then the variable is left equal to
the last item in the list (or to its original value if the list is empty).

As far as I can read in the code, this is already the (accidental)
behavior of the str, seq and ior "map_variable", but not of the tl and
clist "map_variable".
