### ISSUE TITLE
Interfaces for \luadef (and \luafunction(call)?)

### ISSUE THREAD

**Issue by josephwright** [latex3/latex3#582]
(Raised in https://github.com/latex3/latex3/pull/580.)

For some time, LuaTeX has provided `\luafunction` to allow pre-tokenization of heavily-used Lua functions. That was not that not so useful until the addition of `token.scan_string()` and more recently `token.scan_argument()`. With the addition of `\luadef` in LuaTeX v1.10, these combine to mean that anything significant using Lua should probably be defined that way.

There are two parts to the issue here. The first is whether or not to have an interface for `\luafunction` or just for `\luadef`: the latter more-or-less allows us to wrap up `\luafunction(call)` inside a csname without needing a macro. A toy example
```latex
\directlua{
  local t = lua.get_functions_table()
  t[1] = function()
      local a = token.scan_argument()
      tex.print("\string\\showtokens{" .. a .. "}")
    end
}
\luadef\luashow 1
\protected\def\baz{}
\luashow{foo bar\baz}
\show\luashow
```

Perhaps the cleanest way to provide an interface is only to make `\luadef` public and deal with the `\luafunction` stuff internally. That still leaves where to put it all. For example, is it `\lua_cs_new:Nn`/`\lua_cs_(g)set:Nn` (plus `\protected` variants). If so, how do we deal with the fact that stored Lua functions do have to be allocated: can be done without exposing that, but is that what we want?

(In format mode we have to work out how to cover some of what `ltluatex` does: that's a separate issue, probably can be covered reality easily.)

**Comment by zauguin** [comment]
I see one problem with `lua_cs_new:Nn`, which is basically what to pass as second argument.
We could take the code of the to be invoked Lua function, but (especially optimized) Lua functions will normally always need additional context before the function. Another option would be to pass a function name defined in another file, but then the function would need to *have* a public name which will often be odd. After all these are functions which take their arguments by scanning things on the TeX level and not by real Lua arguments, so they are not useful interfaces from a Lua perspective.

Therefore I think I would prefer to only provide a nice wrapper for `set_lua` in Lua and not provide any TeX level interface.

**Comment by hmenke** [comment]
No idea, whether anyone cares about my opinion, but I don't think an interface is necessary at all.  There is also not really a need for an allocator because the Lua function table knows its own length and hence if users abide by the following idiom it's impossible to clash:
```lua
local t = lua.get_functions_table()
t[#t + 1] = function()
    ...
end
token.set_lua("luashow", #t)
```
This is how I define my Lua functions so that I never actually have to care about which number it is assigned to.

**Comment by josephwright** [comment]
@hmenke How do you deal with things when they are created from TeX? That's rather the point here: we need a way to say 'here's some code that is best expressed via Lua, so we need to interface it', and still fit with the `expl3` set up.

**Comment by hmenke** [comment]
What do you mean by “created from TeX”?  A `\luadef` call?  Just leave it at `\tex_luadef:D`, or if you really want to have some sort of interface, `\let` it to something like `\lua_def:NN` (no idea whether `N` is okay for an integer).  I mean, the audience of this interface is very constrained anyway, so I don't think that a very sophisticated interface is expected here.

**Comment by josephwright** [comment]
@hmenke  Well `:D` is for ... just the team or until we sort a defined interface. The audience is constrained but tends to grow: see the usual 'I spotted this code and tried to modify' position.

**Comment by davidcarlisle** [comment]
@josephwright  but in most cases the primitive :D command has to be used _somewhere_ to access the functionality, but here I think Henri and Marcel are right that it could be undefined (or left as :D and not used) the set_lua interface from Lua is functionaly equivalent and more natural since you are starting from Lua code here.

**Comment by hmenke** [comment]
In fact, thinking a bit more about it, I believe that it should remain not interfaced in the hope to encourage people to put Lua code in separate files rather than into the TeX file, which inadvertently leads to expansion and catcode problems.

**Comment by zauguin** [comment]
> No idea, whether anyone cares about my opinion, but I don't think an interface is necessary at all. There is also not really a need for an allocator because the Lua function table knows its own length and hence if users abide by the following idiom it's impossible to clash:
> 
> ```lua
> local t = lua.get_functions_table()
> t[#t + 1] = function()
>     ...
> end
> token.set_lua("luashow", #t)
> ```
> 
> This is how I define my Lua functions so that I never actually have to care about which number it is assigned to.

We have to deal with the fact that at least in LaTeX (and plain if ltluatex is loaded) there already is an allocator for luafunctions which can not be changed to be compatible with this without breaking compatibility.

Also the existence of the allocator has the advantage that it allows logging the allocations which makes the logfile, especially when `\let` is used with luadef based macros, much more useful. (e.g. `\show\tmp` showing `\tmp=expandable luacall 5.` would be pretty useless if there wasn't a line `Lua function luaul.set_underline_func = 5` before that)

**Comment by zauguin** [comment]
> but in most cases the primitive :D command has to be used _somewhere_ to access the functionality, but here I think Henri and Marcel are right that it could be undefined (or left as :D and not used) the set_lua interface from Lua is functionaly equivalent and more natural since you are starting from Lua code here.

> In fact, thinking a bit more about it, I believe that it should remain not interfaced in the hope to encourage people to put Lua code in separate files rather than into the TeX file, which inadvertently leads to expansion and catcode problems.

I think that is especially true for an expl3 context. Writing any Lua code inline in expl3 almost always leads to confusion and weird code issues.

**Comment by josephwright** [comment]
I think on the basis of the above, we close this no action
