### ISSUE TITLE
Use more definite approach for fatal messages

### ISSUE THREAD

**Issue by josephwright** [latex3/latex3#587]
As detailed in https://tex.stackexchange.com/questions/493564/how-to-halt-compilation-and-output-error-message-to-the-console-with-expl3, it would be good to ensure we bail out even when inside an `\hbox`.

**Comment by josephwright** [comment]
One might want to ensure all groups are closed first: do we want to try to do this? e-TeX does provide all of the data.

**Comment by davidcarlisle** [comment]
On Mon, 3 Jun 2019 at 15:17, Joseph Wright <notifications@github.com> wrote:

> One might want to ensure all groups are closed first: do we want to try to
> do this? e-TeX does provide all of the data.
>

I wondered about that in the initial tex.sx comment but possibly not, since
you are documenting as issuing a fatal error anyway, cleaning up nicely
before the fatal blow doesn't seem that necessary, (and may trigger
somewhat arbitrary amounts of code to be injected before the end if you
worry about aftergroup etc.)

**Comment by PhelypeOleinik** [comment]
I think that only `\batchmode\end` might be especially problematic, for example, if due to the error some quark slips in, or in longer documents where it might take a while for TeX to run through all the following errors.

Here's a code that forces the end of all conditionals and group levels based on the current group types:

```latex
\ExplSyntaxOn
\cs_new:Npn \bailout
  {
    \if_clear:
    \group_clear:
    \tex_end:D
  }
\cs_new:Npn \if_clear:
  { \prg_replicate:nn { \tex_currentiflevel:D } { \fi: } }
\cs_new:Npn \group_clear:
  {
    \use:c { __group_abort~ \int_use:N \tex_currentgrouptype:D : }
    \group_clear:
  }
\cs_new:cpn { __group_abort~  0: } { \use_none:n }
\cs_new:cpn { __group_abort~  1: } { \if_false: { \fi: } }
\cs_new:cpn { __group_abort~  2: } { \if_false: { \fi: } }
\cs_new:cpn { __group_abort~  3: } { \if_false: { \fi: } }
\cs_new:cpn { __group_abort~  4: } { \if_false: { \fi: } }
\cs_new:cpn { __group_abort~  5: } { \if_false: { \fi: } }
\cs_new:cpn { __group_abort~  6: } { \tex_cr:D \if_false: { \fi: } }
\cs_new:cpn { __group_abort~  7: } { \if_false: { \fi: } }
\cs_new:cpn { __group_abort~  8: } { \tex_shipout:D \tex_box:D 255~ \if_false: { \fi: \exp_after:wN } }
\cs_new:cpn { __group_abort~  9: } { \if_false: { \fi: } }
\cs_new:cpn { __group_abort~ 10: } { \if_false: { \fi: } { } { } }
\cs_new:cpn { __group_abort~ 11: } { \if_false: { \fi: } }
\cs_new:cpn { __group_abort~ 12: } { \if_false: { \fi: } }
\cs_new:cpn { __group_abort~ 13: } { \if_false: { \fi: } { } { } { } }
\cs_new:cpn { __group_abort~ 14: } { \tex_endgroup:D }
\cs_new:cpn { __group_abort~ 15: } { \exp_after:wN \c_math_toggle_token \if_mode_inner: \else: \c_math_toggle_token \fi: }
\cs_new:cpn { __group_abort~ 16: } { \tex_right:D . }
\ExplSyntaxOff
```

Most of them are just a `}`, so it could be simplified somehow. Type 6 ensures that the alignment doesn't end before a `\cr`, or TeX will complain. Type 8 ensures the output box is cleared and uses a trick (https://tex.stackexchange.com/a/65745/134574) to lure tex into accepting the inserted brace. Type 10 and 13 ensure that TeX finds all the braces it needs to complete the command. The other ones are pretty straightforward.

I think most of them are useless, (who even makes an error in `\discretionary` :). This ends correctly(ish):

```latex
\if TT 1{
\if TT   3\par\hbox{% swapped with 2
\if TT  2\hbox{
\if TT    4\vbox{
\if TT     5\vtop{
\if TT      6\halign{#\cr
\if TT       7\cr\noalign{
\if TT        % 8\output{ % This just stores the abort code in the register :/
\if TT         9$${
\if TT           1\insert0{
\if TT            2$\vcenter{
\if TT             3$\mathchoice{
\if TT              4\begingroup
\if TT                6\left(
\if TT          0\discretionary{%
\if TT\bailout
```

**Comment by PhelypeOleinik** [comment]
`\aftergroup` would be a pain though, using the code above. However I still think it's better than taking ages to end with `\batchmode`.

Another arguably better option would be to cause a fatal error in the engine itself (https://tex.stackexchange.com/q/31517/134574):

```latex
\def\bailout{\valign{\halign##\cr!}}
```

**Comment by FrankMittelbach** [comment]
> I wondered about that in the initial tex.sx comment but possibly not, since
> you are documenting as issuing a fatal error anyway, cleaning up nicely
> before the fatal blow doesn't seem that necessary, (and may trigger
> somewhat arbitrary amounts of code to be injected before the end if you
> worry about aftergroup etc.)

true but the idea of "This can't happen" error message might be a nice 
(and somewhat funny) twist and perhaps better as possibly a long set of 
follow up errors

**Comment by FrankMittelbach** [comment]
> rather than use \batchmode\end anoher alternative would be
> `\batchmode\read-1\relax` does really issue a fatal error and stop.

or this if it does the trick

**Comment by PhelypeOleinik** [comment]
> true but the idea of "This can't happen" error message might be a nice (and somewhat funny) twist and perhaps better as possibly a long set of follow up errors

Unfortunately the "This can't happen" code (`\halign{#&&#\cr\multispan{300}\cr}`) doesn't work inside an `\hbox`, throwing a `Missing } inserted`. The only one I that is apparently consistent is the code in Bruno's question, `\valign{\halign##\cr!}`, which says `! Emergency stop`.

**Comment by blefloch** [comment]
On 6/3/19 17:25, Phelype Oleinik wrote:
>     true but the idea of "This can't happen" error message might be a
>     nice (and somewhat funny) twist and perhaps better as possibly a
>     long set of follow up errors
> 
> Unfortunately the "This can't happen" code
> (|\halign{#&&#\cr\multispan{300}\cr}|) doesn't work inside an |\hbox|,
> throwing a |Missing } inserted|. The only one I that is apparently
> consistent is the code in Bruno's question, |\valign{\halign##\cr!}|,
> which says |! Emergency stop|.
> 

Did you try wrapping it in a \vbox{ ?
Of course all of this needs various \everyvbox{}\everycr{} (and so on?).

**Comment by josephwright** [comment]
So we want
```latex
\vbox{\halign{#&&#\cr\multispan{300}\cr}}
```
with presumably `\batchmode` before it?

**Comment by PhelypeOleinik** [comment]
> with presumably `\batchmode` before it?

Or without, to print `This can't happen` (followed by an admittedly off context `(256 spans)`) and `!  ==> Fatal error occurred, no output PDF file produced!`.

**Comment by blefloch** [comment]
On 6/3/19 17:53, Phelype Oleinik wrote:
>     with presumably |\batchmode| before it?
> 
> Or without, to print |This can't happen| (followed by an admittedly off
> context |(256 spans)|) and |! ==> Fatal error occurred, no output PDF
> file produced!|.
> 

I don't think "This can't happen" is good to have as part of our fatal
error messages.  They can definitely happen.

Remember to clear \everyvbox and other such hooks.

**Comment by josephwright** [comment]
@blefloch Right, got it. I'll adjust again in a bit.

**Comment by davidcarlisle** [comment]
does the halign version stop in more cases than \read ? it seems more
complicated (needing to clear the hooks etc)

**Comment by blefloch** [comment]
Much better to do

  \batchmode \read -1 to \l_tmpa_tl

(no need for \end).  The code in pdftex.web at least is pretty clear:
this stops regardless of anything[^1], doesn't insert anything and
doesn't print things like unclosed groups or ifs.  We should definitely
not try to close groups because \aftergroup makes it unsafe.  We could
close ifs but I see no point.

[^1] unless \read is redefined I guess.

**Comment by FrankMittelbach** [comment]
> Much better to do
> 
> \batchmode \read -1 to \l_tmpa_tl
> 
> (no need for \end). The code in pdftex.web at least is pretty clear:
> this stops regardless of anything[^1], doesn't insert anything and
> doesn't print things like unclosed groups or ifs. We should definitely
> not try to close groups because \aftergroup makes it unsafe. We could
> close ifs but I see no point.
> 
> [^1] unless \read is redefined I guess.

I think we should go for this - simple and clear (doubt that many people 
would have gotten the"Can't happen joke" anyway and only complained that 
it did happen

**Comment by josephwright** [comment]
@FrankMittelbach Hopefully that's the case in the latest commit.

I'd appreciate it if someone would check the code before I close the issue.

**Comment by PhelypeOleinik** [comment]
@josephwright Seems to be working fine:

```latex
\documentclass{standalone}
\usepackage{expl3}
\begin{document}
\ExplSyntaxOn
\msg_new:nnnn { bp2017 } { logical-error }
  { The~thing~that~wasn't~supposed~to~happen~happened. }
  { I~don't~know~how~to~help~you~further. }%
\msg_fatal:nn { bp2017 } { logical-error }
\q_nil
```

```none
! Fatal Package bp2017 Error: The thing that wasn't supposed to happen
(bp2017)                      happened.

For immediate help type H <return>.
 ...

l.8 \msg_fatal:nn { bp2017 } { logical-error }

? h

I don't know how to help you further.

This is a fatal error: LaTeX will abort.

?


C:\Users\Phelype\Desktop\test>
```

It also stops regardless of being in `\hbox`, `\vbox`, `\halign`, `\output`, etc. And the "more help" text is also there. Looks good :-)

**Comment by josephwright** [comment]
Cool: calling this closed then.

**Comment by FrankMittelbach** [comment]
Am 04.06.2019 um 13:23 schrieb Joseph Wright:
> @FrankMittelbach <https://github.com/FrankMittelbach> Hopefully that's 
> the case in the latest commit.
> 
> I'd appreciate it if someone would check the code before I close the issue.

sorry bit restricted with my dead ssd with respect to coding or checking 
(confirmed to be 100% dead ... hopefully replacement there by the end of 
the week)
