### ISSUE TITLE
Composing regular expressions in l3regex

### ISSUE THREAD

**Issue by PhelypeOleinik** [latex3/latex3#590]
A couple of days ago a question was asked at TeX.SX about composing regexes: https://tex.stackexchange.com/q/494830/134574. In the post, OP wanted an escape sequence similar to `\u{<tl var>}` which, instead of using the literal tokens contained in `\<tl var>`, would parse them as a regular expression. I thought about two ways of doing that:

 1. Having the `\<tl var>` be a compiled regex and inserting in the current regex. The code for this one could be very similar to `\u`, changing only the final step, where for `\u` the `\<tl var>` is read "verbatim", and now it would be read assuming that it is a `\<regex var>` (possibly with a validity verification). The downside of this method is that the `\<regex var>` being used would have to be a complete expression by itself (compiling VAR=`a-z` and `[VAR]+` would result in "any of `a`, `-`, and `z`, one or more times, greedy"). The usage would be like:
```latex
\regex_set:Nn \l_tmpa_regex { [a-z]+ } % Compile \l_tmpa_regex
\regex_set:Nn \l_tmpb_regex { \[ \y{l_tmpa_regex} \] } % Insert it with \y{...}
```

 2. Having the `\<tl var>` be an _arbitrary_ token list which is compiled as a regular expression each time it is used. This method would offer a great deal of flexibility, as there would be no bounds on the contents of the `\<tl var>` as long as, at the very end, the whole thing would make a valid regular expression. However the implementation for this one would be problematic because at the time the `\<tl var>` was read in, the engine would be at the second compilation step and would need to return to the first to scan the `\<tl var>`. If this method were to be used, then perhaps a pre-scanning of the regular expression to expand the `\<tl var>` would be easier (but would be very different from the other steps, and I don't know how problematic that would be). The usage would be like:
```latex
\tl_set:Nn \l_tmpa_tl { [a-z]+ }
\regex_set:Nn \l_tmpb_tl { \[ \y{l_tmpa_tl } \] } % Insert it with \y{...}
```
but could also be:
```latex
\tl_set:Nn \l_tmpa_tl { [a- }
\regex_set:Nn \l_tmpb_tl { \[ \y{l_tmpa_tl }z]+ \] } % Insert it with \y{...}
```

So is this feature still planned? Which of those versions would be implemented (or something else entirely)?

---

The asker also raised the issue of `\regex_show:N` being a tad hard to debug with the many lines of `char code <num>`, which I fully agree. This could easily be improved with something like:
```latex
\cs_new:Npn \__regex_show_if_visible_ascii:n #1
  {
    \if_int_compare:w
      \if_int_compare:w \int_eval:n{#1}>31  ~ 1 \else: 0 \fi:
      \if_int_compare:w \int_eval:n{#1}<127 ~ 1 \else: 0 \fi:
      = 11 \exp_stop_f:
      \c_space_tl (\char_generate:nn {#1} {12})
    \fi:
  }
```
and then using `\__regex_show_if_visible_ascii:n {<num>}` wherever a `char code <num>` is printed. The output would be:
```latex
+-branch
  ,-group begin
  | Match, repeated 1 or more times, greedy
  |   range [97 (a),122 (z)]
  |   range [65 (A),90 (Z)]
  |   range [48 (0),57 (9)]
  |   char code 95 (_)
  `-group end
  ,-group begin
  | char code 91 ([)
  | range [97 (a),122 (z)]
  | char code 93 (])
  `-group end.
```
Much easier to follow :-)

**Comment by eg9** [comment]
I second the idea, but with `\y{<regex variable>}`. I'm not sure that allowing incomplete regexes would add good or useful functionality.

**Comment by blefloch** [comment]
I've got a fix in the gh590 branch.  Should I also make the `\regex_show:n` changes in that branch, or should this be moved to a separate issue?

**Comment by PhelypeOleinik** [comment]
Since it's just a logging change and it can be linked to this issue (and since I should have made two separate issues back then :), I think it's not a problem being in the same branch.
