### ISSUE TITLE
l3keys can't handle paths containing control sequences

### ISSUE THREAD

**Issue by schtandard** [latex3/latex3#594]
`interface3.pdf` states in the introduction to `l3keys`

> Key names may contain any tokens, as they are handled internally using <tt>\tl_to_str:n</tt>.

However, in the following MWE, the `\keys_if_exist:nnTF` follows the `false` branch and consequently the `\keys_set:nn` fails with the message
```
! LaTeX3 Error: The key 'foo/\test' is unknown and is being ignored.
```
```tex
\documentclass{article}

\usepackage{expl3}

\begin{document}

\ExplSyntaxOn

\keys_define:nn { foo } {
	\test .code:n = You~typed~` \tl_to_str:n {#1} '.\par,
}

\keys_if_exist:nnTF { foo } { \test } { yes \par } { no \par }

\keys_set:nn { foo } { \test = Hello World! }

\ExplSyntaxOff

\end{document}
```

----

Regarding the module name, `interface3.pdf` states

> The _⟨module⟩_ name should be a text value, but there are no restrictions on the nature of the text.

It is a bit unclear to me what exactly this means (Is "text" the same as "string"? If not, is macro expansion performed? Are active characters allowed?), but I assumed the same rule as for key names applies. After all, sub keys can be defined by appending `/ key` to the module name.

However, the following MWE (same as above, but with `foo` and `\test` substituted with `\foo` and `test`, respectively), `\keys_if_exist:nnTF` also follows the `false` branch but `\keys_set:nn` executes successfully despite this!
```tex
\documentclass{article}

\usepackage{expl3}

\begin{document}

\ExplSyntaxOn

\keys_define:nn { \foo } {
	test .code:n = You~typed~` \tl_to_str:n {#1} '.\par,
}

\keys_if_exist:nnTF { \foo } { test } { yes \par } { no \par }

\keys_set:nn { \foo } { test = Hello World! }

\ExplSyntaxOff

\end{document}
```

**Comment by josephwright** [comment]
OK, the issue here is space stripping: I see the problem. A fix coming up.

**Comment by josephwright** [comment]
I've tweaked the code here plus the docs on the module name.
