### ISSUE TITLE
l3doc support for multiple <@@=...>

### ISSUE THREAD

**Issue by PhelypeOleinik** [latex3/latex3#595]
Hey, it's me again. From here: https://tex.stackexchange.com/q/497410/134574
I had noticed this issue before, but hadn't explored it further until now. `docstrip` reads a source file line by line and the `l3docstrip` patch does the replacement of `@@` in the code as they appear. For instance this source:
```latex
%    \begin{macrocode}
%<@@=hello>
\cs_new:Npn \@@_world:n {}
%<@@=goodbye>
\cs_new:Npn \@@_world:n {}
%    \end{macrocode}
```
produces (unsurprisingly) this code:
```latex
\cs_new:Npn \__hello_world:n {}
\cs_new:Npn \__goodbye_world:n {}
```
`l3doc` grabs an entire `macrocode` environment and checks for a `<@@=...>` there and does the replacement accordingly. However `l3doc` chokes on the replacement of `@@` for the typeset output of the code because it expects at most one occurrence of `<@@=...>` per `macrocode` environment. A slight change allows multiple `<@@=...>` in the same `macrocode` environment:
```latex
\group_begin:
  \char_set_catcode_letter:N \@
  \char_set_catcode_active:N \<
  \char_set_catcode_active:N \>
  \cs_gset_protected:Npn \__codedoc_xmacro_code:n #1
    {
      \tl_clear:N \l__codedoc_tmpa_tl
      \tl_if_in:nnTF {#1} { < @ @ = }
        { \__codedoc_xmacro_code:w #1 < @ @ = \q_recursion_tail > \q_recursion_stop }
        {
          \tl_set:Nn \l__codedoc_tmpa_tl {#1}
          \__codedoc_detect_internals:N \l__codedoc_tmpa_tl
          \__codedoc_replace_at_at:N \l__codedoc_tmpa_tl
          \tl_use:N \l__codedoc_tmpa_tl
        }
    }
  \cs_gset_protected:Npn \__codedoc_xmacro_code:w #1 < @ @ = #2 >
    {
      % Add code before <@@=...>
      \tl_set:Nn \l__codedoc_tmpb_tl {#1}
      \__codedoc_detect_internals:N \l__codedoc_tmpb_tl
      \__codedoc_replace_at_at:N \l__codedoc_tmpb_tl
      \tl_put_right:NV \l__codedoc_tmpa_tl \l__codedoc_tmpb_tl
      % Check for \q_recursion_tail
      \quark_if_recursion_tail_stop_do:nn {#2}
        { \tl_use:N \l__codedoc_tmpa_tl }
      % Change module name and add <@@=#2> to typeset output
      \tl_gset:Nn \g__codedoc_module_name_tl {#2}
      \tl_put_right:Nn \l__codedoc_tmpa_tl { < \text { \verbatim@font @ @ = #2 } > }
      % Loop
      \__codedoc_xmacro_code:w
    }
\group_end:
```
One could argue that changing the module name in the middle of the code should not be done, but in that case I think a suitable error/warning message could be issued instead. However I think it's okay (and coherent with the behaviour of `l3docstrip`) to allow module name changes in the code.

**Comment by blefloch** [comment]
Incidentally this applies to l3debug in the debug branch since my last
commit, because I merged several blocks of code into one.

**Comment by FrankMittelbach** [comment]
> One could argue that changing the module name in the middle of the code should not be done, but in that case I think a suitable error/warning message could be issued instead. However I think it's okay (and coherent with the behaviour of `l3docstrip`) to allow module name changes in the code.

It is clearly sensibleto allow this (after all one could copy different modules into a single source file and even having several ones in one macrocode should be allowed too imho even if it is somehting that I would not recommend.

Could you be so kind to turn this into a pull request?

**Comment by PhelypeOleinik** [comment]
> Could you be so kind to turn this into a pull request?

Done :-) https://github.com/latex3/latex3/pull/596
