### ISSUE TITLE
Create a milestone to understand what is missing for the first release

### ISSUE THREAD

**Issue by XVilka** [latex3/latex3#597]
It will help understand new contributors the priorities, the overall progress and what is need to be done as soon as possible. Moreover, it makes sense to split the whole bunch of issues in a number of projects, grouped by the common subject. See https://github.com/features/project-management/. The projects on GitHub can span across the whole organization, not just one repository, which can be helpful in case of the "feature" consisting of small issues and pull requests in different repositories: https://help.github.com/en/articles/about-project-boards
We use it in radare2/cutter projects, and it is really a blast.

**Comment by josephwright** [comment]
I'm not really sure what this issue is about ...

**Comment by hmenke** [comment]
There is an official release date already, so I don't know what else you would want.
![test](https://user-images.githubusercontent.com/1903556/60256082-6a88be00-98c0-11e9-9e1a-237cc07236d5.png)
Source: https://chat.stackexchange.com/transcript/message/49676921#49676921
