### ISSUE TITLE
Error on printing PDF document with pdflatex.exe

### ISSUE THREAD

**Issue by dnsnx** [latex3/latex3#598]
Hi, 

I'm not quite sure, if this is the right place to discuss my error. If not, please feel free to close the issue. 

My story's a little longer. So I'll start at the beginning. If you need more information about some points, please let me know, then I will add them.

I'm using pdflatex.exe to produce PDF files via a webpage. 
That worked fine 2 or 3 years ago with the help of MiKTeX. Now I'm working again on this project and I did not work anymore. So I tried to install a new version of MiKTeX, but I wasn't able to install it on my Windows 10 computer (development machine). With MiKTeX portable I was able to produce PDF documents in  the console, but it still did not work with my software. It did not even start to produce the PDF file (no .aux or .log files have been created).

So lately I switched to TeXLive. 
Here I was also able to produce PDF documents in the console of Win10. 
When I use the exact command in my software it starts to produce the PDF file (.aux and .log files being created), but it throws an error:

> {d:/Program Files/TeXLive/texlive/2019/texmf-var/fonts/map/pdftex/updmap/pdftex
> .map
> !pdfTeX error: pdflatex.exe (file d:/Program Files/TeXLive/texlive/2019/texmf-v
> ar/fonts/map/pdftex/updmap/pdftex.map): fflush() failed (Invalid argument)
>  ==> Fatal error occurred, no output PDF file produced!

I tried to create a simple .tex file and run this in my software. The error is the same. 
I tried it with this .tex file:

```
\documentclass{article}

\begin{document}

\title{Introduction to \LaTeX{}}
\author{Author's Name}

\maketitle

\begin{abstract}
The abstract text goes here.
\end{abstract}

\section{Introduction}
Here is the text of your introduction.

\begin{equation}
    \label{simple_equation}
    \alpha = \sqrt{ \beta }
\end{equation}

\subsection{Subsection Heading Here}
Write your subsection text here.

\section{Conclusion}
Write your conclusion here.

\end{document}

```
and the .log file is this:

> This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/W32TeX) (preloaded format=pdflatex 2019.6.23)  23 JUN 2019 22:20
> entering extended mode
>  restricted \write18 enabled.
>  %&-line parsing enabled.
> **"D:/Files/Company/Einzelunternehmung Me/Kunden/Customer/IngTo
> ols/app/Classes/Rechnung/LaTex/Output/Rechnung_yTi8JxtZyNV2UW8OmYVI_000053-19" 
> -output-directory=D:/Files/Company/Einzelunternehmung Me/Kunden/Customer/
> Software/app/Classes/Rechnung/LaTex/Output/ -jobname=Rechnung_000053-
> 19 D:/Files/Company/Einzelunternehmung Me/Kunden/Customer/Software/
> app/Classes/Rechnung/LaTex/Output/Rechnung_gLxNgg92TyfHLv7TymAK_000053-19.tex
> 
> (d:/Files/Company/Einzelunternehmung Me/Kunden/Customer/Software
> /app/Classes/Rechnung/LaTex/Output/Rechnung_yTi8JxtZyNV2UW8OmYVI_000053-19.tex
> LaTeX2e <2018-12-01>
> (d:/Program Files/TeXLive/texlive/2019/texmf-dist/tex/latex/base/article.cls
> Document Class: article 2018/09/03 v1.4i Standard LaTeX document class
> (d:/Program Files/TeXLive/texlive/2019/texmf-dist/tex/latex/base/size10.clo
> File: size10.clo 2018/09/03 v1.4i Standard LaTeX file (size option)
> )
> \c@part=\count80
> \c@section=\count81
> \c@subsection=\count82
> \c@subsubsection=\count83
> \c@paragraph=\count84
> \c@subparagraph=\count85
> \c@figure=\count86
> \c@table=\count87
> \abovecaptionskip=\skip41
> \belowcaptionskip=\skip42
> \bibindent=\dimen102
> )
> (./Rechnung_yTi8JxtZyNV2UW8OmYVI_000053-19.aux)
> \openout1 = `Rechnung_yTi8JxtZyNV2UW8OmYVI_000053-19.aux'.
> 
> LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 3.
> LaTeX Font Info:    ... okay on input line 3.
> LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 3.
> LaTeX Font Info:    ... okay on input line 3.
> LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 3.
> LaTeX Font Info:    ... okay on input line 3.
> LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 3.
> LaTeX Font Info:    ... okay on input line 3.
> LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 3.
> LaTeX Font Info:    ... okay on input line 3.
> LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 3.
> LaTeX Font Info:    ... okay on input line 3.
> LaTeX Font Info:    External font `cmex10' loaded for size
> (Font)              <17.28> on input line 8.
> LaTeX Font Info:    External font `cmex10' loaded for size
> (Font)              <12> on input line 8.
> LaTeX Font Info:    External font `cmex10' loaded for size
> (Font)              <8> on input line 8.
> LaTeX Font Info:    External font `cmex10' loaded for size
> (Font)              <6> on input line 8.
> LaTeX Font Info:    External font `cmex10' loaded for size
> (Font)              <7> on input line 17.
> LaTeX Font Info:    External font `cmex10' loaded for size
> (Font)              <5> on input line 17.
>  [1
> 
> {d:/Program Files/TeXLive/texlive/2019/texmf-var/fonts/map/pdftex/updmap/pdftex
> .map
> !pdfTeX error: pdflatex.exe (file d:/Program Files/TeXLive/texlive/2019/texmf-v
> ar/fonts/map/pdftex/updmap/pdftex.map): fflush() failed (Invalid argument)
>  ==> Fatal error occurred, no output PDF file produced!
> 

The files are produced by a PHP page with the `proc_open` command:

```
$descriptorspec = array(
            0 => array("pipe", "r"),  // STDIN ist eine Pipe, von der das Child liest
            1 => array("pipe", "w"),  // STDOUT ist eine Pipe, in die das Child schreibt
            2 => array("file", "D:/Freigabe/error.txt", "a") // STDERR ist eine Datei,
                                                             // in die geschrieben wird
         );
         
         $cwd = 'D:/Files/Company/Einzelunternehmung Me/Kunden/Customer/Software/public';
         $env = null;
$this->execute = '"' .str_replace('/','\\',env('PDFLATEXENGINE', 'C:/Program Files (x86)/MiKTeX 2.9/miktex/bin/pdflatex.exe')) .'" "D:\Files\Company\Einzelunternehmung Me\Kunden\Customer\Software\app\Classes\Rechnung\LaTex\Output\Rechnung_yTi8JxtZyNV2UW8OmYVI_000053-19" -output-directory="D:\Files\Company\Einzelunternehmung Me\Kunden\Customer\Software\app\Classes\Rechnung\LaTex\Output\" -jobname="' .str_replace('.pdf','',$this->pdfFileName) .' ' .$this->latexFilePath .'"';
$process = proc_open('"' .$this->execute .'"', $descriptorspec, $pipes, $cwd, $env);
```

System Infos: 
- Windows 10 Build 1809
- PHP 7.0.0
The application pool of the page is running on the same account, when I run the commands in the command window of windows.

**Comment by josephwright** [comment]
Sorry, this is all completely outside of the control of the team (we don't create binaries) and isn't linked to LaTeX3 work. Please raise on for example the TeX Live mailing list.
