### ISSUE TITLE
missing l3backend on CTAN?

### ISSUE THREAD

**Issue by BrianCriswell** [latex3/latex3#600]
The CI on my project broke sometime in the last 17 hours.
LaTeX cannot find l3backend, whether in PDFLaTeX, LuaTeX, or XeTeX.

```
(/srv/texlive/texmf-dist/tex/latex/l3packages/xparse/xparse.sty
(/srv/texlive/texmf-dist/tex/latex/l3kernel/expl3.sty
(/srv/texlive/texmf-dist/tex/latex/l3kernel/expl3-code.tex)

! LaTeX Error: File `l3backend-pdfmode.def' not found.
```

I have not made any code changes on my end, so I was wondering if the error message made sense here.

Working log: https://gist.github.com/BrianCriswell/c7bbff163fccef99006a364894bf70ad

Broken log: https://gist.github.com/BrianCriswell/11c81d3f895c062fa89680ab021d4af5

Apologies in advance if I am barking up the wrong tree.

**Comment by eg9** [comment]
No error on my side, because I updated my TeX Live which also installed `l3backend`.

**Comment by josephwright** [comment]
The entire LaTeX3 'stack' was updated on CTAN a couple of days ago, and we arranged that everything went into TeX Live/MiKTeX at once. If you have a 'cut down' system with no auto-install, you may need to add `l3backend` on.

**Comment by BrianCriswell** [comment]
Thanks for the prompt response, Our CI installs a minimal TeXLive install before installing dependencies, and I had missed that l3backend was now apparently separate (plus I had an tlmgr error the first time I tried to include it). 

Cheers!
