### ISSUE TITLE
l3draw, polar coordinates

### ISSUE THREAD

**Issue by hvoss49** [latex3/latex3#608]
L3draw uses polar coordinates noation similiar to tikz as `(<angle>,r)`. It is more or less common sense to use it the other way round as  `(r,<angle>)`. Compare for example:

mathworld.wolfram.com:  The expression of a point as an ordered pair (r,theta) is known as polar notation, 

https://www.iso.org/obp/ui/#iso:std:iso:19111:ed-3:v1:en

ISO 80000-2, for spherical coordinates r,theta,phi

**Comment by josephwright** [comment]
The syntax matches `pgf`, which uses `<angle>,<r>`;  unless there are good reasons, I've tried to match the `pgf` API. Here, I'm not sure there is a 'right approach, certainly an ISO is not definitive. I'll see what others think.

**Comment by u-fischer** [comment]
the pgf syntax is `<angle>:<r>`  with a colon, the extended syntax `(canvas polar cs:angle=30,radius=1cm);` has imho no order. I can't find anything looking like `(<angle>,<r>)` in pgf. When using a pair with a comma  `(r,angle)` is certainly the common order in germany.

**Comment by hvoss49** [comment]
Am So., 18. Aug. 2019 um 14:06 Uhr schrieb Ulrike Fischer <
notifications@github.com>:

> the pgf syntax is <angle>:<r> with a colon, the extended syntax (canvas
> polar cs:angle=30,radius=1cm); has imho no order. I can't find anything
> looking like (<angle>,<r>) in pgf. When using a pair with a comma
> (r,angle) is certainly the common order in germany.
>

not only in Germany. However, we also say r(phi) for a polar function and
not phi(r).
I know that pgf uses <Alpha;r>, which was _not_ a good decision ...

Herbert

**Comment by josephwright** [comment]
Certainly I think we are happy to adjust the API where there are clear deficiencies: I'm going to see what our 'real' mathematician thinks! (@eg9)

**Comment by josephwright** [comment]
@u-fischer  It's `\pgfpointpolar`, with `#1` as the angle and `#2` as the axis or axes.

**Comment by car222222** [comment]
Of course, in Real Maths it is r * exp ( i \theta )  :-).

I agree with Herbert that it the (angle, radius) is “never” used by anyone, ever.

**Comment by josephwright** [comment]
@car222222 OK, I'm happy to go with 'change the API' here: I'll action shortly

**Comment by eg9** [comment]
Radius and angle, definitely.

**Comment by josephwright** [comment]
OK, seems pretty clear.
