### ISSUE TITLE
l3draw, \draw_path_close: and \draw_path_use_clear:n{stroke}

### ISSUE THREAD

**Issue by hvoss49** [latex3/latex3#609]
If a path starts and ends in `{0cm,0cm}` and I then close the path I get:

! Undefined control sequence.
<argument> \LaTeX3 error: 
                           Invalid operation (0)/(0)
l.18 \draw_path_use_clear:n { stroke }

Without using `\draw_path_close:` it works fine:

```
\documentclass{minimal}
\usepackage{l3draw}
\begin{document}

\ExplSyntaxOn
\draw_begin:
\dim_new:N \l_r_dim 
\dim_set:Nn \l_r_dim{ 2cm }
\draw_path_corner_arc:nn { 3pt } { 3pt }
\draw_path_moveto:n { 0cm, 0cm }
\int_step_inline:nnnn { 30 } { 60 } { 330 }
{
  \draw_path_lineto:n { \draw_point_polar:nn { #1 } { \l_r_dim }}
  \draw_path_lineto:n { \draw_point_polar:nn { #1+30 } {\l_r_dim}}
  \draw_path_lineto:n { 0pt, 0pt }
}
%\draw_path_close:                  %%%%% works
\draw_path_use_clear:n { stroke }
\draw_end:
\ExplSyntaxOff

\end{document}
```

Up-to-date TL2019

I suppose, that the problem always happens if the startpoint and 
endpoint are the same.

**Comment by josephwright** [comment]
@hvoss49 Yes, that's correct: I think I forgot to allow for the lineto and close points being the same. Now I have to remember how this all works ... should be fixed today. Is an update urgent?

**Comment by hvoss49** [comment]
no, I can wait ... 
Anyway, thanks

**Comment by hvoss49** [comment]
The problematic part looks like:
`\cs_new_protected:Npn \__draw_path_use:n #1` 

and then 
```

    \__draw_softpath_round_corners:
    \bool_lazy_and:nnT
      { \l_draw_bb_update_bool }
      { \l__draw_path_use_stroke_bool }
      { \__draw_path_use_stroke_bb: }
    \__draw_softpath_use:
```
Without rounded corners it is ok.

**Comment by josephwright** [comment]
Problem is as you say the corner rounding: I'm more-or-less used the `pgf` approach, I need to spot where I've missed out a test ..

**Comment by josephwright** [comment]
Problem is in `\draw_point_interpolate_distance:nnn`, which in the current version doesn't like a zero-length line. The `pgf` approach doesn't care!

**Comment by josephwright** [comment]
That then comes from how I've done the implementation and the way `\pdfpointnormalize` works with small values ... hmm

**Comment by josephwright** [comment]
Should now be sorted. I do wonder about how that rounding works for the last place: neither option looks quite 'right'.

**Comment by blefloch** [comment]
I see you've opted to make the normalization (unit vector) of (0,0) be
(0,1), i.e., a vertical vector.  I think it would make more sense to
have it be (1,0), a horizontal vector (so 1 in the complex plane).

**Comment by josephwright** [comment]
@blefloch Based on `pgf` so we get the same outcomes:

> `\pgfpointnormalised{<point>}`
This command returns a normalised version of <point>, that is, a vector of length 1pt pointing in the
direction of <point>. If <point> is the 0-vector or extremely short, a vector of length 1pt pointing upwards is returned.

As with the polar co-ordinates business, I'm happy to break the API compatibility if the real mathematicians think it's appropriate: @eg9, @car222222, @davidcarlisle?

**Comment by car222222** [comment]
Mathematically speaking, the 0 vector (0,0) has no direction so this function should be undefined.
Similarly, this point has, afaik, no “canonical representation in polar co-ordinates”, any value for the angle can be used when radius=0.  There may be a conventional value used in computational maths, @davidcarlisle ??

So, we need to look at how this function is used in other functions to see whether it matters how we define it at 0.

**Comment by car222222** [comment]
“I do wonder about how that rounding works for the last place: neither option looks quite 'right'.”
Another one for the guys (any gender) at NAG!

All I can say is that in numerical analysis courses, as we used to call it, you mostly learn that nothing is ever “looks quite rightl”.  And i got that from Leslie Fox, together with the impression that this is the reason why he “invented” the subject, and hence NAG !

**Comment by car222222** [comment]
A general comment: when working with very small numbers, “how to do the rounding” will always be a problem and, in particular, it is wise to never round to exactly 0.

**Comment by josephwright** [comment]
@car222222 Apologies, I was not clear. By 'rounding I really do mean 'making corners round', not anything to do with calculations. Look at the final repeat of the shape: with or without the closing function, it's 'wrong'.
