### ISSUE TITLE
l3cctab and \endlinechar

### ISSUE THREAD

**Issue by josephwright** [latex3/latex3#611]
As raised in https://github.com/latex3/latex3/issues/610 (and somewhat linked to https://github.com/latex3/latex3/issues/48), it might be useful if `cctab` functions handle `\endlinechar`. In favour

- Allows us to have a single interface
- Makes it possible to implement `\ExplSyntaxOn` as a `cctab`
- Would be useful for a putative `\tl_rescan:Nn` or similar, where `#1` is a `cctab`

Against

- It's not a catcode
- Might be confusing where `cctab`s are accessed from Lua (where only the real part would work)

**Comment by u-fischer** [comment]
I can't make up my mind yet ;-). But as you write about lua, imho it would be useful to a function for the access to the table as replacement for something like this:

~~~~
\directlua{tex.sprint(luatexbase.registernumber("c_my_cctab"),"??")}
~~~~

**Comment by car222222** [comment]
I agree that the lua data structure and accessors must also change.

**Comment by josephwright** [comment]
@u-fischer  We could cover just cctab data, but isn't this really something we should do in the 2e kernel/`l3alloc`?
