### ISSUE TITLE
l3keys strange behaviour and not suitable in expandable context

### ISSUE THREAD

**Issue by bastien-roucaries** [latex3/latex3#616]
For polyglossia I wish to use l3keys for parsing list of option.

This is not suitable because l3keys does not like to work in expandable context. Minimal text case:
\documentclass{minimal}

\usepackage{expl3}
\ExplSyntaxOn
\keys_define:nn {k} {
  lang .tl_gset:N =  \g_tmpa_tl,
  lang .default:n = {local},
  lang .initial:n = {local}
}

\cs_new:Npn \testtwo  #1 {
  #1
}
  
\cs_new:Npn \testfull #1  {
  \keys_set:nn {k} {#1}
  \testtwo{\g_tmpa_tl}    
}

\ExplSyntaxOff

\def\test{\testfull{lang=french}}
\edef\teste{\testfull{lang=french}}

\begin{document}
\test==\teste?
\end{document}

**Comment by PhelypeOleinik** [comment]
The entire `l3keys` approach for key-val parsing is not expandable. This is by-design.

For your example to expand, the `.tl_set:N` instruction (which is a `\def` down below) would
need to be somehow expandable, so it isn't really possible.

What is the behaviour you expect? Perhaps another approach could be used, either with
`l3keys` and not relying on full expansion, or something expandable with `l3prop`...

---

On the output difference you see:

The `\test` macro is really just `\testfull{lang=french}`, which does what you expect (when
typeset): `\keys_set:nn` is evaluated, and `french` is assigned to `\g_tmpa_tl`. `\g_tmpa_tl`
is then typeset by `\testtwo` (which should, by the way, be defined with `\tl_use:N`).

When `\teste` macro expands, `\keys_set:nn` is preserved (it's `\protected`) and then
`\testtwo` expands with `\g_tmpa_tl`. At the time of the definition, `\g_tmpa_tl` contains
the `.initial:n` value (`local`), which is then appended to the `\teste` macro. When `\teste`
is typeset the `\keys_set:nn` is evaluated (nothing is output), and then `local` is typeset.

If you define the `\testfull` macro with `\cs_new_protected:Npn` instead of `\cs_new:Npn`
(which you should, since it is not expandable), then the output is the same for both examples.

**Comment by bastien-roucaries** [comment]
I will like firsty to implement band aid:
1. First it should be stated clearly in documentation, at the begining of l3keys
2. It should if possible error out during the edef if possible.

Secondly the function I want to implement is \localnumber[lang variant key list]{counter}
this function will be used for print section number. So it need to be expandable. I know how to use \cs_new_protected:Npn but it will break with hyperref that need an expandable token list.

I can work arround using old latex but even \keyval_parse:NNn is not marked expand safe...

**Comment by wspr** [comment]
Expandable operations in TeX are extremely limited in being able to achieve the kinds of behaviour you are describing. Even grabbing optional arguments expandably is difficult and has edge cases — although xparse has some functions to help.

I think the only realistic possibility here is to limit the scope of your section numbering macro. Perhaps the variants that you need can be predefined in advance?

**Comment by u-fischer** [comment]
The documentation quite clearly distinguish expandable and non-expandable commands: all expandable commands have a star. 

But even if it were expandable: I don't think that it is good idea to mix typesetting of a counter with programming tasks like setting a destination name in hyperref. This should be separated. An arabic or greek number won't work well in a pdf name. hyperref uses for destination names not the counter itself but normally the Hcounter variant. So it should be possible to set this independantly.

**Comment by bastien-roucaries** [comment]
@wspr I could implement a sax like handler by hand, but it was difficult. Setting thepage to localnumber fail with hypperef bo

@u-fisher: the problem is the bookmark generation that are completly destroyed

**Comment by u-fischer** [comment]
@bastien-roucaries  yes that too. But it is the same problem: typesetting, bookmarks, destination names and references through the aux have different requirements towards a number representation. For simple ascii representations you can often ignore this but when other scripts are involved it gets important.

**Comment by bastien-roucaries** [comment]
i achieved simple option parsing using this kind of code:
```
% print using main language
% #2 is the numeral to print
% #3 is the mainlanguage (should be expanded)
% #4 is the current language (should be expanded)
% #1 is the option list (should be expanded)
\cs_new:Nn \polyglossia_localnumber_mainlang:nnnn {
  \use:c {\prop_item:Nn \polyglossia@langsetup  {#3/localnumber}} {#1} {#2}
}

% print using local language
% #2 is the numeral to print
% #3 is the mainlanguage (should be expanded)
% #4 is the current language (should be expanded)
% #1 is the option list (should be expanded)
\cs_new:Nn \polyglossia_localnumber_locallang:nnnn {
  \use:c {\prop_item:Nn \polyglossia@langsetup  {#4/localnumber}} {#1} {#2}
}


\cs_new:Npn \polyglossia_iii_map_csv_field_split_kv_iii_localnumber:w  #1 = #2 \q_stop {
  \str_case:nnF{#2}{
    {local}  {\clist_map_break:n{\use_i:nn \polyglossia_localnumber_locallang:nnnn }}
    {default}{\clist_map_break:n{\use_i:nn \polyglossia_localnumber_locallang:nnnn }}
    {*}      {\clist_map_break:n{\use_i:nn\polyglossia_localnumber_mainlang:nnnn   }}
    {main}   {\clist_map_break:n{\use_i:nn\polyglossia_localnumber_mainlang:nnnn   }}
  }{
    \clist_map_break:n{ \use_i_ii:nnn \polyglossia_localnumber_langlang:nnnnn {{#2}} }
  }
}

% call the language
\cs_new:Nn \polyglossia_localnumber_langlang:nnnnn {
  \use:c {\prop_item:Nn \polyglossia@langsetup  {#1/localnumber}} {#2} {#3}
}


% check if empty value
\cs_new:Npn \polyglossia_iii_map_csv_field_split_kv_ii_localnumber:w  #1 #2 = #3 \q_stop {
  \quark_if_no_value:NTF {#3}
  {
    \clist_map_break:n{\use_i:nn \polyglossia_localnumber_locallang:nnnn}
  }
  {
    \polyglossia_iii_map_csv_field_split_kv_iii_localnumber:w #1 \q_stop
  }
}

\cs_new:Npn \polyglossia_iii_map_csv_field_split_kv_i_localnumber:nw #1 #2 = #3 \q_stop {
  % parse only lang tag
  \tl_trim_spaces_apply:nN {#2} \str_if_eq:nnT {lang}
  {
    % if empty value
    \quark_if_nil:nTF{#3}
    {
      \clist_map_break:n{\use_i:nn \polyglossia_localnumber_locallang:nnnn}
    }
    {
      % here we know what we have an equal sign
      \polyglossia_iii_map_csv_field_split_kv_ii_localnumber:w {#1} #1 \q_no_value \q_stop
    }
  }
}


% map function 
\cs_new:Nn \polyglossia_iii_map_csv_localnumber:n {
  % fast case is do nothing is empty 
  \tl_if_empty:nF{#1}
  {
    \polyglossia_iii_map_csv_field_split_kv_i_localnumber:nw {#1} #1 = \q_nil \q_stop
  }
}


% treat option is empty and option is lang=local
% #2 number
% #3 mainlanguage
% #4 locallanguage
% #1 option
% strip space to option
\cs_new:Nn \polyglossia_iii_localnumber:nnnn {
  % use postscript like trick push to stack {#1} {#2} {#3} {#4}
  \tl_if_blank:nTF{#1}
  {
    \polyglossia_localnumber_mainlang:nnnn
  }
  {
    \str_if_eq:nnTF{#1}{lang=local}
    {
      \polyglossia_localnumber_locallang:nnnn
    }
    {
      % use postscript like trick push to stack {#1} {#2} {#3} {#4}
      % same trick here if found we emit  \use_i:nn
      % thus discarding the default choice that is not lang specified thus local
      \clist_map_function:nN {#1} {\polyglossia_iii_map_csv_localnumber:n}
      \polyglossia_localnumber_locallang:nnnn
    }
  }
  {#1} {#2} {#3} {#4}
}

% internal helper useful for oeee and onnn
% #1 number
% #2 mainlanguage
% #3 locallanguage
% #4 option
% strip space to option
\cs_new:Nn \polyglossia_ii_localnumber:nnnn {
  \tl_trim_spaces_apply:nN {#4} \polyglossia_iii_localnumber:nnnn {#1}{#2}{#3}
}
\cs_generate_variant:Nn \polyglossia_ii_localnumber:nnnn {
  eeen
}

% convert the counter to value
% #1 counter
% #2 mainlanguage
% #3 locallanguage
% #4 option
\cs_new:Nn \polyglossia_i_localnumber:nnnn
{
  \polyglossia_ii_localnumber:eeen {\int_value:w #1} {#2} {#3} {#4}
}

% print number usage Localnumber[option]{numeral}
% \Localnumber[]{numeral} use main language
% \localnumber{numeral} use local language
\NewExpandableDocumentCommand{\Localnumber}{om}
{
  \IfNoValueTF {#1}
  {
    \polyglossia_ii_localnumber:eeen {\int_eval:n{#2}}{\mainlanguagename} {\languagename} {lang=local}
  }
  {
    \polyglossia_ii_localnumber:eeen {\int_eval:n{#2}}{\mainlanguagename} {\languagename} {#1}
  }
}

% print number usage Localnumber[option]{counter}
% \Localnumber[]{numeral} use main language
% \localnumber{numeral} use local language
\NewExpandableDocumentCommand{\localnumber}{om}
{
  \IfNoValueTF {#1}
  {
    \exp_args:Nc \polyglossia_i_localnumber:nnnn {c@#2}{\mainlanguagename} {\languagename}{lang=local}
  }
  {
    \exp_args:Nc \polyglossia_i_localnumber:nnnn {c@#2}{\mainlanguagename} {\languagename}{#1}
  }
}

```

**Comment by bastien-roucaries** [comment]
i really think a version of keyval_parse:NNn that is expandable would be the best.

This function should be able to break the cvs list.

Using curing we could get something nice.

Better will be \keyval_parse:Nn key_valstring function
 
For each entry of the csv the function will take four argument:
#1 the name of the key
#2 the value of the key (\q_nil if no =  and \q_no_value if = empty)
#3 the option list not parsed (identity mapping)
#4 the positionnal argument in the option list

**Comment by josephwright** [comment]
I've written some expandable keyval parse code in the past, but you always come down to the same issues: you are restricted on handling the catcode of `{`, and the 'payload' is very limited (all has to be also expandable). (This was in the context of some `biblatex` stuff: in the end an alternative was found.)

My concern with all of that is if one takes the model that a key has a set value, we can't do it expandably other than with LuaTeX. It's very very much an edge use-case, and really without a rock-solid use case with no alternative, I'm wary.

**Comment by FrankMittelbach** [comment]
> i really think a version of keyval_parse:NNn that is expandable would be the best.

well, key/val parsing is essentially always about assigning values to variables, registers, macros and the like and that is due to limitations in TeX not possible within `\edef` and there is nothing that you can really do about that other than ensuring that it  doesn't try to expand in such places and break. I guess you aren't the only person who would wish that Don had designed TeX differently in this respect but this is nothing you can program around.

**Comment by josephwright** [comment]
@FrankMittelbach Of course, LuaTeX can do this in recent versions (see `\immediateassignment`)!

**Comment by FrankMittelbach** [comment]
@josephwright yeah sure but unless you are intending to abandom the other engines at that point in time that doesnt help, does it?

**Comment by josephwright** [comment]
@FrankMittelbach Not for us, but perhaps for others (`polyglossia` I guess needs to work with XeTeX too, but there will  be people in different situations). We could perhaps have a 'LuaTeX-only' function in this area: keeps catcodes so good at the 'TeX side', in comparison with parsing from Lua.

**Comment by u-fischer** [comment]
@josephwright Imho it would be not a bad idea to check if (and which) commands can be made "luatex-expandable".

**Comment by josephwright** [comment]
@u-fischer In principle, anything that doesn't involve typesetting can be done expandably in LuaTeX. So one could re-work more-or-less all of `expl3`. But of course, in a LuaTeX-only situation you'd make some pretty big changes anyway.

**Comment by zauguin** [comment]
@josephwright Actually LuaTeX *can* do expandable typesetting (It's sometimes useful if you have to typeset stuff from a callback or similar), but it doesn't seem useful in a expl3 context.
Maybe we could identify a subset of expl3 which is particularly useful in LuaTeX (mostly everything where catcodes are important e.g. `l3tl/l3seq/l3prop/l3clist`?) and provide LuaTeX-expandable versions there?

**Comment by bastien-roucaries** [comment]
@FrankMittelbach; expandable look like lambda computing, using curing I can simulte setting macros. It is a pain but less than programming in brainfuck.

@josephwright: in polyglossia payload should be expansable, we replace \@arabic so it is expansable. I could live with the \catcode limitation.

And about setting N values we could transforme the setting of value to pass to curing macro N parameters affected in the right order and we the value. It is weird but it is lambda computing

**Comment by josephwright** [comment]
@zauguin Sure, but I don;t think that makes `\setbox` an expandable assignment does it? (I may have missed it, of course.)

I'm very wary of having different expansion behaviour with different engines. That's asking for all sorts of trouble (years ago we had something similar before requiring `\pdfstrcmp`: it was hairy). As I've said, the moment one is 'LuaTeX only' then quite a lot of ideas might well be re-worked anyway.

**Comment by bastien-roucaries** [comment]
@josephwright before going luaonly we should handle the same language than xetex.

**Comment by josephwright** [comment]
@bastien-roucaries  Simply saying 'it needs to be expandable isn't what I meant: this is a thorny area, and I think working through interface questions is needed before one can make that call. As keyvals here would be restricted and not consistent with others in LaTeX, I'm very keen to explore the full range of possibilities.

**Comment by josephwright** [comment]
@bastien-roucaries In terms of LuaTeX-only I mean that having extensive _macros_ dedicated purely to LuaTeX is someone that probably only makes sense for ConTeXt or LuaLaTeX-only packages.

**Comment by bastien-roucaries** [comment]
(Exercice left to the reader: expandable tex is equivalent to lambda computation, we could reimplement tex problematic primitive using lambda computation)

**Comment by FrankMittelbach** [comment]
> I'm very wary of having different expansion behaviour with different engines. That's asking for all sorts of trouble (years ago we had something similar before requiring `\pdfstrcmp`: it was hairy). As I've said, the moment one is 'LuaTeX only' then quite a lot of ideas might well be re-worked anyway.

agreed; we are not at a point where we can or should abandom any engine and getting different expansion results (even if it is only how many times you need to example before you get the same result) is deadly and has been proven to be so in the past. So we really should limit the differences between engines to a minimum not expand on this at this point in time.

**Comment by josephwright** [comment]
Exactly so any 'LuaTeX expandble' functions need to be separate from the general ones: that I think we can all live with.

**Comment by FrankMittelbach** [comment]
In my opinion this is only asking for trouble

**Comment by FrankMittelbach** [comment]
unless you meant to have different function names but that is having other problems so I'm not sure that would be a good idea either

**Comment by josephwright** [comment]
@FrankMittelbach  I meant other function names, likely in the `lua` module

**Comment by zauguin** [comment]
> @zauguin Sure, but I don;t think that makes `\setbox` an expandable assignment does it? (I may have missed it, of course.)

@josephwright Right, but implementing an expandable `\setbox` using `tex.setbox` and `.scan_list` is a one-liner, so as long as you can accept a separate macro for global setbox and don't need the primitive `\global` support, the difference is mostly academic.

@FrankMittelbach I agree that reusing function names would be problematic, but as long as they are different and the limited compatibility of the expandable functions is clearly documented, I think it wouldn't lead to problems.

@josephwright I don't know if `lua` makes sense because while the functions would only work in LuaTeX, they are not really Lua related. So maybe a new module? (`l3immediate`?)

**Comment by josephwright** [comment]
I guess my concern (and I suspect @FrankMittelbach's) is that one could expend a lot of energy here without getting much in the way of result. Code targetting just LuaTeX is likely to be able to use Lua-based approaches when expandablity is required, and the number of places that `expl3` interfaces make real sense as additions is very limited. In the case of keyvals, for example, we know `polyglossia` also needs XeTeX support so any code there has to be 'classical' and thus heavily restricted in an expansion context.

I also realise that I was a bit over-ambitious earlier: anything involving a group still can't be expandable in LuaTeX as the group itself isn't.

**Comment by u-fischer** [comment]
@zauguin 

> I don't know if `lua` makes sense because while the functions would only work in LuaTeX, they are not really Lua related. So maybe a new module? (`l3immediate`?)

l3iTeX  ;-) https://tex.stackexchange.com/questions/19079/what-on-earth-is-itex

Imho this is a good idea. It could go in l3trial. Even if at the end it isn't added to l3kernel it would be useful as a systematic collection and documentation how the various lua functions can be used - the documentation in the luatex manual about the scanners etc are rather sparse and incomplete.

**Comment by FrankMittelbach** [comment]
I don't mind a separate module but I think its function should be "lua-something" as long as the functionality is restricted to the luatex engine  --- we decided long ago that we call luatex only functions lua not luatex so \lua_... is not wrong

**Comment by josephwright** [comment]
We do have an open request to use more efficient approaches when using Lua for providing macro 'inners': that falls in the scope of a new module and really is needed.  It like;y does want to be `\lua_...` or perhaps `\cs_lua...`. I'm less convinced about stuff that is purely macro-layer but is expandable-due-to-LuaTeX.

**Comment by josephwright** [comment]
For reference: https://github.com/latex3/latex3/pull/580 is where we are looking at using `\luadef`/`\luafunction` (one or both should have interfaces which as I say could arguably be `\lua_...`).

**Comment by zauguin** [comment]
> I guess my concern (and I suspect @FrankMittelbach's) is that one could expend a lot of energy here without getting much in the way of result. Code targetting just LuaTeX is likely to be able to use Lua-based approaches when expandablity is required, and the number of places that `expl3` interfaces make real sense as additions is very limited. In the case of keyvals, for example, we know `polyglossia` also needs XeTeX support so any code there has to be 'classical' and thus heavily restricted in an expansion context.

Starting with TeX Live 2020 we can also just add a single function (`\lua_evaluate_tex:n`?) which is expandable and executes arbitrary non-expandable commands. Then all of expl3 can be used even in an expansion only context under LuaTeX but we have almost no additional work.

> I also realise that I was a bit over-ambitious earlier: anything involving a group still can't be expandable in LuaTeX as the group itself isn't.

Slightly off topic, but LuaTeX allows expandable `\begingroup`/`\endgroup` (or expandable `{` and `}`) and therefore expandable groups through `runtoks` since TeXLive 2019.

**Comment by josephwright** [comment]
@zauguin  How would that be done? On the group business, I've probably missed on of Hans' changes.

**Comment by zauguin** [comment]
@josephwright The magic is in `tex.runtoks`. Basically it accepts a Lua function or a token register and evaluates them in a nested TeX loop. (More precisely, it appends a internal version of the `\endlocalcontrol` primitive after an equivalent of `\luafunction` or `\toks` and then evaluates everything up to the first `\endlocalcontrol` primitive. This allows some trickery to evaluate an argument without having to use slow Lua scanners.) So you could use

```
\input expl3-generic
\ExplSyntaxOn
\cs_new:Npn \lua_evaluate_tex:n {
  \lua_now:n {
    tex.runtoks(function() token.put_next(token.create'use_ii_i:nn') end)
  }
}

\keys_define:nn {k} {
  lang .tl_gset:N = \g_tmpa_tl,
  lang .default:n = {local},
  lang .initial:n = {local}
}

\cs_new:Npn \testtwo #1 {
#1
}

\cs_new:Npn \testfull #1 {
  \lua_evaluate_tex:n { % This is enough to make everything "expandable"
    \keys_set:nn {k} {#1}
  }
  \testtwo{\g_tmpa_tl}
}

\ExplSyntaxOff

\def\test{\testfull{lang=french}}
\edef\teste{\testfull{lang=french}}

\test==\teste?
\bye
```
For groups you just use `\begingroup`/`\endgroup`/`\bgroup`/`\egroup` as parameter (or pass them to `tex.runtoks` directly. The only important point is that if the to be evaluated part contains a macro assignment and `\lua_evaluate_tex:n` is evaluated inside of an `\edef` (or similar), [a LuaTeX bug is triggered.](https://mailman.ntg.nl/pipermail/dev-luatex/2019-September/006297.html) This severly limits it's use in current LuaTeX version, but the problem does not occur when "only" a group command is evaluated. (Also Luigi fixed the bug for the next version)

**Comment by josephwright** [comment]
I think for the original issue here we are clear: the code was never marked as expandable. Further discussion about LuaTeX approaches and/or expandable key processing belongs in separate (linked) issues.

**Comment by Skillmon** [comment]
Just to let the OP of this issue know: In new versions of `l3keys`, `\keyval_parse:NNn` is expandable, see https://github.com/latex3/latex3/pull/678 (but note that `\keys_set:nn` still isn't). Another expandable engine-independent key=value package is `expkv`, which might come in handy especially with `expkv-cs`. Still they can't do any assignment in an expandable manner.
