### ISSUE TITLE
[xparse] doc - make differences between "stable" and "experimental" more clear

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#617]
In the doc of `xparse`, sec. 3.2 Argument processors, six functions are documented. The full list is
```latex
\ProcessedArgument
\ReverseBoolean
\SplitArgument
\SplitList
\ProcessList
\TrimSpaces
```

1. in the beginning of doc of `xparse`, it says
https://github.com/latex3/latex3/blob/e05ae381f4ab484d31b8f8ed8a0fa1145e6f88ce/l3packages/xparse/xparse.dtx#L104-L106
This may be understood as "other functions, including all the above six functions, are all experimental".

2. But in the Sec. 3.2 of doc, only `\ProcessList` and `\TrimSpaces` are denoted experimental. This, may be understood as "each of other four functions in the above list is not experimental".

Maybe a more clear description about "which xparse functions are experimental" is needed.

**Comment by josephwright** [comment]
I think at this stage we likely should mark all of `xparse` as stable: probably some documentation improvements are needed too.

**Comment by pablgonz** [comment]
@josephwright  I think this is clear from the current documentation.

**Comment by josephwright** [comment]
The move of `xparse` to `ltcmd` I think clears this all up.

**Comment by muzimuzhi** [comment]
> I think at this stage we likely should mark all of `xparse` as stable: probably some documentation improvements are needed too.
> from https://github.com/latex3/latex3/issues/617#issuecomment-533232706

Do there need some sort of documentation improvements, for example removing words about "this function/type is experimental"?

**Comment by josephwright** [comment]
> > I think at this stage we likely should mark all of `xparse` as stable: probably some documentation improvements are needed too.
> > from [#617 (comment)](https://github.com/latex3/latex3/issues/617#issuecomment-533232706)
> 
> Do there need some sort of documentation improvements, for example removing words about "this function/type is experimental"?

I'll sweep over the sources and check
