### ISSUE TITLE
Ending a vbox with \par

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#62]
In `\vbox{Abc.}`, TeX ends the paragraph beyond our control, and there is no way to hook into the end of the paragraph. This is due to TeX _not_ inserting the macro `\par`. Instead, it ends the paragraph as if the primitive had been inserted. (See discussions on [when TeX inserts `\par`](http://tex.stackexchange.com/questions/37042/) on the tex.stackexchange website.)

We could define `\vbox_set_end:` to be `\mode_if_horizontal:T {\par} \c_group_end_token` to have more control.

**Comment by josephwright** [comment]
This was altered some time ago.

**Comment by blefloch** [comment]
There are several other cases to consider, cf the list above `\vbox`, `\vtop`, `\vcenter`, `\halign`, `\insert`, `\output`, `\noalign`.  I say leave it open or at least record it somewhere.  We will never look again at closed issues.

**Comment by car222222** [comment]
I am not clear exactly what you mean when you include \halign, \output and \noalign in this list.  
Is the primitive par added (potentially) in hmode in these cases?

**Comment by car222222** [comment]
I now see why two of these shoukd be in the list since they may need to end hmode to get back into internal vm ode, just like vbox.  But I am still unclear how one can be in hmode at the very end of an \halign (rather than at the end of the last cell).

**Comment by car222222** [comment]
But another case is \valign (Remember it??) where each cell needs to end in internal vmode.

**Comment by FrankMittelbach** [comment]
> But another case is \valign (Remember it??) where each cell needs to end 
> in internal vmode.

uhhh, how many people have ever been brave enough to twist their head 
around that one?

**Comment by eg9** [comment]
> On 17 Nov 2017, at 20:19 , Frank Mittelbach <notifications@github.com> wrote:
> 
> > But another case is \valign (Remember it??) where each cell needs to end 
> > in internal vmode.
> 
> uhhh, how many people have ever been brave enough to twist their head 
> around that one?

https://tex.stackexchange.com/a/202195/4427 <https://tex.stackexchange.com/a/202195/4427>
https://tex.stackexchange.com/a/16351/4427 <https://tex.stackexchange.com/a/16351/4427>
https://tex.stackexchange.com/a/193033/4427 <https://tex.stackexchange.com/a/193033/4427>

Ciao
Enrico
