### ISSUE TITLE
Regex replacement turns letter tokens into other tokens

### ISSUE THREAD

**Issue by PhelypeOleinik** [latex3/latex3#621]
From [this](https://tex.stackexchange.com/a/506624/134574) TeX.SX thread. The code:
```latex
\input expl3-generic
\ExplSyntaxOn
\tl_set:Nn \l_tmpa_tl { a }
\regex_replace_once:nnN { a } { \0 b } \l_tmpa_tl
\tl_analysis_show:N \l_tmpa_tl
\use:c { stop }
\bye
```
shows this in the terminal:
```none
The token list \l_tmpa_tl contains the tokens:
>  a (the letter a)
>  b (the character b).
```
with the `b` becoming a catcode 12 token (I believe due to the `\detokenize` applied to the regular expression before processing).

This makes, in the linked thread, `\regexpatchcmd` fail because when retokenized, `b` will have catcode 11 and `\regexpatchcmd` thinks (correctly) that the function was defined under a different catcode regime.

**Comment by josephwright** [comment]
This is or was by design: the inserted tokens are 'string-like' unless explicitly requested to do otherwise.

**Comment by blefloch** [comment]
Certainly was by design: you can do \cLb to get a catcode-letter "b".

In hindsight it might be better to make the default catcode be whatever
the current catcode is for that character.

**Comment by PhelypeOleinik** [comment]
I should probably read the documentation _before_ posting issues...
Sorry about the noise.

> In hindsight it might be better to make the default catcode be whatever
> the current catcode is for that character.

That's what I thought it did, before reading the documentation. It seems more
natural... I think.

**Comment by FrankMittelbach** [comment]
> > In hindsight it might be better to make the default catcode be whatever
> > the current catcode is for that character.
> 
> That's what I thought it did, before reading the documentation. It seems more
> natural... I think.

This might be worth revisiting before we cement something that is failry unnatural. I would expect the major usage of regex is dealing with textual material from the document where an implicit conversion to "string" is not really that appropriate is it?

**Comment by blefloch** [comment]
>>>         In hindsight it might be better to make the default catcode be
>>>         whatever
>>>         the current catcode is for that character.
>> 
>>     That's what I thought it did, before reading the documentation. It
>>     seems more
>>     natural... I think.
> 
> This might be worth revisiting before we cement something that is failry
> unnatural. I would expect the major usage of regex is dealing with
> textual material from the document where an implicit conversion to
> "string" is not really that appropriate is it?

I'll have to look at how to implement such a "default catcode is current
value of \catcode".  Or do we want "default catcode is frozen to the
document catcodes" with some universally fixed list?  This may matter if
someone uses a regex when implementing some verbatim environment, or
applies a regex during a package's set-up.

Actually, in option 1 we also have to decide if catcodes are frozen when
defining storing a regex in a variable or if one uses the catcodes that
are current when using the regex.

I *think* all of these options are implementable without too much pain.

**Comment by PhelypeOleinik** [comment]
> I'll have to look at how to implement such a "default catcode is current
> value of \catcode". Or do we want "default catcode is frozen to the
> document catcodes" with some universally fixed list? This may matter if
> someone uses a regex when implementing some verbatim environment, or
> applies a regex during a package's set-up.

Right now what looks better to my eyes is "default catcode is current value of
\catcode", which makes it look like that the tokens used in the function call
are the ones that will actually be inserted in the output token list.

> Actually, in option 1 we also have to decide if catcodes are frozen when
> defining storing a regex in a variable or if one uses the catcodes that
> are current when using the regex.

I would find it strange that a compiled regular expression changes its behaviour
when the catcode settings change. Over-simplifying the analysis, TeX freezes the
catcodes when it first sees the character: I (think I) would expect a compiled
regex to behave more or less the same in this respect.

**Comment by blefloch** [comment]
> freeze the catcodes when it first sees the character
It makes sense.  One drawback is that it will remain difficult to insert
a subscript character for instance.  One would still have to use "\cD\_"
(without the quotes).
