### ISSUE TITLE
\__kernel_file_name_quote:e used but not defined

### ISSUE THREAD

**Issue by callegar** [latex3/latex3#624]
In the version of `l3kernel` currently distributed with TeXlive 2019, in file expl3-code.tex one finds `\__kernel_file_name_quote:e` which should probably be `\__kernel_file_name_quote:n`.  In fact, `\__kernel_file_name_quote:e` is not defined and its reference causes latex to error out in the compilation of several documents of mine.

**Comment by josephwright** [comment]
Ooops, must have missed on variant: I'll fix.

**Comment by ondohotola** [comment]
You guys are quick :-)-O

el
