### ISSUE TITLE
[xparse] Make value reference to other arguments accessible for argument processors

### ISSUE THREAD

**Issue by mrpiggi** [latex3/latex3#629]
First of all, many thanks for the excellent work on LaTeX3. I've seen recently that default values for optional arguments can refer to other arguments. I wanted to know if this functionality could be transferred to argument processors as well. The following example is only intended to demonstrate the desired procedure and would not be necessary for this simple case.
```tex
\documentclass{article}
\usepackage{xparse}
\makeatletter
\NewDocumentCommand\TestLabels{o m d==}{%
  \Test@Labels[#1]{#2}=#3=%
}
\NewDocumentCommand{\Processor@Labels}{m m m}{%
  \IfValueTF{#1}%
    {\def\ProcessedArgument{#1:#3}}%
    {\def\ProcessedArgument{#3}}%
  \IfValueT{#2}
    {%
      \expandafter\def\expandafter\ProcessedArgument%
        \expandafter{\ProcessedArgument:#2}%
    }%
}
\NewDocumentCommand\Test@Labels{r[] m r==}{%
  \Processor@Labels{#1}{#3}{#2}%
  \texttt{\ProcessedArgument}
}
%%% requested functionality
%\RenewDocumentCommand\Test@Labels{r[] >{\Processor@Labels{#1}{#3}}m r==}{%
%  \texttt{#2}
%}
\makeatother
\begin{document}

\TestLabels{base}

\TestLabels[prefix]{base}

\TestLabels{base}=suffix=

\TestLabels[prefix]{base}=suffix=

\end{document}
```

**Comment by josephwright** [comment]
I won't rule out @blefloch magic, but basically I think 'no, sorry'. The processor code is really 'attached' to a single argument.

**Comment by blefloch** [comment]
Magic not too hard if I read the code properly: \@@_args_process_aux:n
receives the code for one processor (which in the current proposal would
involve macro parameter chars #).  We need to add to it something like

\cs_generate_from_arg_count:Nn \@@_tmp:w
  { \tl_count:N \l_@@_args_tl } {#1}
\exp_args:NNNo \exp_after:wN \@@_tmp:w \l_@@_args_tl
  { \ProcessedArgument }

What this would conceptually do is (1) read args from the input stream,
(2) fill in default args that can depend on other ones from the first
step, (3) pass these arguments to processors and apply the processors'
code, (4) run the command's actual code.  At steps (2), (3), (4) the
meaning of #1, #2 etc would be different.

Is that what we want?
