### ISSUE TITLE
[no-link] option in variable/macro environments (l3doc)

### ISSUE THREAD

**Issue by pablgonz** [latex3/latex3#635]
Hello everyone, I always see the advances in this repository, now I have realized that l3doc will become a public package, which is great.
I have a request that might be useful, I explain a little. Let's consider as an example the current l3doc documentation the `564` line code:
```tex
% \begin{variable}{g_docinput_clist}
```
and the code in line `930`
```tex
% \begin{macro}
```
When compiling documentation, the first generates:
```
(End definition for \g_docinput_clist. This variable is documented on page ??.)
```
and the second:
```
(End definition for \seq_set_split:NoV and others. These functions are documented on page ??.)
```
Which is exactly the same as it is with some documents in which I use `l3doc`. They would consider the idea of adding the `[no-link]` option (or another name) to these environments or being able to customize the message, to avoid unresolved reference messages (I use `latexmk` and `hyperref` and it takes more than the time to compile).

**Comment by wspr** [comment]
The current setup is definitely intended for the use-case of wanting to publicly document all functions. I can see there are scenarios where this is not needed/useful.

At the very least, we could check for the existence of the reference, and if it is missing just drop the text that reads "This XXX [is/are] documented on page ??.”

**Comment by pablgonz** [comment]
Yes... that would be great (and simpler than my requirement).

**Comment by PhelypeOleinik** [comment]
Another thing that might be good is to add customisation points for the user. Currently there is an internal function which does the typesetting of this sentence, but an interface could be added, for easier customisation (of this an other) hard-coded things.

**Comment by josephwright** [comment]
To cover in https://github.com/latex3/latex3/issues/1136
