### ISSUE TITLE
Latex3 case and token manipulation functions not working well with 8-bit engines

### ISSUE THREAD

**Issue by callegar** [latex3/latex3#638]
Hi,

I am having trouble with case manipulation functions with 8-bit engines (pdflatex). For instance, consider the following snippet:
```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[artemisia]{textgreek}
\usepackage[LGR, T1]{autofe}
\usepackage{expl3}
\begin{document}
\ExplSyntaxOn
\str_upper_case:n{ΔΣ~modulator}
\ExplSyntaxOff
\end{document}
```
This works fine in lualatex but does not produce the intended result with pdflatex.

Even worse:
```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[artemisia]{textgreek}
\usepackage[LGR, T1]{autofe}
\usepackage{expl3}
\begin{document}
\ExplSyntaxOn
\tl_head:n{ΔΣ~modulator}
\ExplSyntaxOff
\end{document}
```
This breaks badly.

The same goes when trying to use a small delta as the first letter. The issue is relevant because it breaks the `acro` package that typesets acronyms and in some cases tries to capitalize the first letter of the long form and one may have the expectation that `inputenc` can let you use unicode safely on the 8 bits engines.

**Comment by josephwright** [comment]
The _string_ functions leave everything as catcode-12 ('other'): you can set that the result is 'correct' using
```latex
\tl_set:Nx \l_tmpa_tl{\str_upper_case:n{ΔΣ~modulator}}\show\l_tmpa_tl
```
For changing the case of the first 'letter', the function `\tl_mixed_case:n` 'knows' about UTF-8 so does the correct thing.

Functions like `\tl_head:n` act strictly on the first token: this is by-design.

**Comment by josephwright** [comment]
Try 
```latex
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[artemisia]{textgreek}
\usepackage[LGR, T1]{autofe}
\usepackage{expl3}
\begin{document}
\ExplSyntaxOn
\tl_mixed_case:n{ΔΣ~modulator}
\ExplSyntaxOff
\end{document}
```

(There are a few issues outstanding with Greek specifically ...)

**Comment by callegar** [comment]
Thanks for the clarification! I guess the issue is with `acro.sty` trying to identify the first character to capitalize using a token manipulation function which works on the unicode engine where 1 char is one token but does not on the 8 bit engines. Is this the case?

Unfortunately, `\tl_mixed_case` does not do what is needed by `acro.sty` which strictly wants only the first letter capitalized and the rest unchanged. Is there some support for this?

**Comment by josephwright** [comment]
The problem with saying 'only capitalise the first letter' is that what one is supposed to do does depend on the rest of the content. This shows up for the small number of cases where the 'title case' version of a code point is not the same as the 'upper case' one: they mainly look like two letters together. The whole thing being upper case means the first char looks like 'XX', whereas when the rest of the text is lower case it looks like 'Xx'. As such, what we've tried to implement at the moment sticks to what Unicode describe fro case changing (except we've called it 'mixed' not 'title' case).

Can you detail why this needs to be 'strictly first-upper' not 'Unicode titlecase (see http://www.unicode.org/faq/casemap_charprop.html).

**Comment by josephwright** [comment]
We could either alter the current function or perhaps provide a new one: I can see that this is a complex area (and there is a reason everything is currently marked as experimental).

**Comment by FrankMittelbach** [comment]
Something like `acro` needs to uppercase the first Unicode character not the first character of every word, e.g., the abbrev `\ac{dh}`  generates "das heißt" and `\Ac{dh}` has to turn that into "Das heißt" not "Das Heißt".

[aside: just noticed that "ß" -> "Ss" with the expl code which is definitely wrong, it should either be SS or the newly coined uppercase ß which I think is in unicode but not in many fonts]

**Comment by josephwright** [comment]
@FrankMittelbach  On `ß`, you mean the 'mixed' case situation? That's just following Unicode: see `SpecialCasing.txt`! I'm not saying they are right, but that is our starting point ...

**Comment by josephwright** [comment]
@FrankMittelbach Note that what Unicode call 'titlecase' is really only about the first word ... more like sentence case _but_ the description doesn't cover sentences ...

**Comment by callegar** [comment]
Sorry for coming back late in the discussion. The main issue with `\tl_mixed_case` for `acro` (for which I am just a user) is readily shown by an example: `\tl_mixed_case:n{ΔΣ~MOdulator}` gives you `ΔΣ modulator`. In other words, it also affects the case of of the words following the first one. Now, `acro` manages acronyms and for each of them it stores two strings, the *short* version and the *long* one. When it comes at the beginning of a sentence, the long version needs its first letter capitalized. Because the rest of the string may contains other acronyms or names, the capitalization of the rest of the string needs to stay untouched. This is why the acro package tries to separate the first letter from the rest using `\tl_head` which may obviously be wrong in 8-bits engines.

**Comment by callegar** [comment]
Looks like having something similar to `\makefirstuc` from the `mfirstuc` package natively supported in LaTeX3 would be really useful. More so because the `mfirstuc` implementation relies on the `datatool-base` package and particularly on its `\dtl@getfirst@UTFviii` internal for identifying the first letter in the unicode case. The latter looks very much like an *internal* command and is also indicated as experimental, so being able to rely on something more stable and official would help!

**Comment by FrankMittelbach** [comment]
> @FrankMittelbach Note that what Unicode call 'titlecase' is really only about the first word ... more like sentence case _but_ the description doesn't cover sentences ...

I kind of realized that by now, but it is really weird imho. What is the use case for this? Not even in the English language you are supposed to lowercase everything in a sentence if it contains, say, acronyms. And in other languages it is totally wrong.

So in my opinion a function that uppercases just the first "real" unicode char in a given text is much more useful (and what is now called titlecase would then be implementable by first lowercasing everything and then applying that function (but as I said I don't really see the usecase). 

Wha I know as a use case that could be reasonably called "titlecasing" is to uppercase each and every word --- but that then omits some short words (which depend on the house style as I under stand).

**Comment by josephwright** [comment]
The use case is that one doesn't know the case of stuff, classically in English book titles: see BibTeX. The case changing functions have a 'no change' function, which one might apply to input with a fixed casing. One might also use the language argument to select e.g. that German 'does nothing' for everything except the first char.

Note of course that one can't just 'grab the first char' due to things like `iPhone`: that too requires some form of 'escape' even if the scheme adopted is to case change only the first char.

**Comment by josephwright** [comment]
BTW, I'm not saying the current set up is necessary right, just that there is some logic to doing more than just 'leave everything bar the first char alone'. As I say, this is common for book titles, where at least in English it's common to title case them in some styles, and to 'squash' that in others.

**Comment by josephwright** [comment]
The formal reference at https://www.unicode.org/versions/Unicode12.0.0/UnicodeStandard-12.0.pdf says

> Titlecasing refers to a casing practice wherein the first letter of a word is an uppercase letter and the rest of the letters are lowercase. This typically applies, for example, to initial words of sentences and to proper nouns. Depending on the language and orthographic practice,this convention may apply to other words as well, as for common nouns in German.

In particular, notice that it does say the rest is lowercased, implying that if supplied an all-uppercase string we should lowercase the 'balance'. (The docs make it clear that titlecase is regarded as applying on a per-word basis.)

**Comment by FrankMittelbach** [comment]
But we don't offer that, do we? 

Basically a nice (maybe only higher-level) function would be to titlecase word by word. But a low-level function that only uppercases the first utf-8 char would also be rather helpful for situations like with acro or `\Ref` etc. where you really don't want any other characters touched at all.

**Comment by josephwright** [comment]
@FrankMittelbach Well no, but we need to start with some 'building blocks'. I understand the point about 'first upper only', I'm just wary of the fact that with all uppercase input that is going to give (probably) the wrong outcome.

**Comment by josephwright** [comment]
We are in a way back with the naming problem: upper/lower is easy, but is this 'firstupper' or 'titlecase' or ...

**Comment by josephwright** [comment]
Thinking, I wonder if the requirement here is a single function with a 'combinatorial' set of outcomes:
`\tl_change_case:nnn { <first-char> } { <other-chars> } { <tokens> }` where the current `\tl_upper_case:n` and `\tl_lower_case:n` would be short-cuts? It's essentially a generalisation of `\tl_mixed_case:n`.

**Comment by josephwright** [comment]
See https://github.com/latex3/latex3/pull/654: there, I have a function `\text_titlecase_first:n` which only case-changes the very first character. This is part of a more general 'upgrade' of the case functions.

**Comment by josephwright** [comment]
PR now merged and covers this.
