### ISSUE TITLE
! LaTeX3 Error: Unknown color ''. (l3color)

### ISSUE THREAD

**Issue by pablgonz** [latex3/latex3#640]
Hello, the following example does not work with the color `gray` with TeXLive updated to date. 
```tex
\documentclass{article}
\usepackage{l3draw}
\begin{document}
\ExplSyntaxOn
\draw_begin:
\draw_linewidth:n { 0.5pt }
\draw_color:n { gray }
%\draw_color:n { yellow!80!black } % OK
\draw_path_grid:nnnn
{ 0.5cm } { 0.5cm } { 0cm , 0cm } { \linewidth , 2cm }
\draw_path_use_clear:n { stroke }
\draw_end:
\ExplSyntaxOff
\end{document}
```
say
```
! LaTeX3 Error: Unknown color ''.

For immediate help type H <return>.
 ...                                              
                                                  
l.7 \draw_color:n { gray }
                          
? h

LaTeX has been asked to use a color named '', but this has never been defined.

? 
```
Ops, (I think this is from texlive, but...) `texdoc l3color` shows `interface3`.

**Comment by josephwright** [comment]
Well the error message is unhelpful, but the core point is right ... core colours are `black`, `white`, `red`, `green`, `blue`, `cyan`, `magneta`, `yellow`.

**Comment by pablgonz** [comment]
Report `texdoc l3color` in texdoc mail list..now fix :)

**Comment by wtsnjp** [comment]
yes, it has been 😄 
https://github.com/TeX-Live/texdoc/commit/5ac9a80cf9802899090fb94b2469692d54559dae
