### ISSUE TITLE
\file_if_exist:nTF fails on files with spaces in its name

### ISSUE THREAD

**Issue by zepinglee** [latex3/latex3#642]
When testing files with spaces in its name, the `\file_if_exist:nTF` gives wrong result with engines other than `pdftex`.

The test code is at https://github.com/zepinglee/latex3/commit/b9bc776a634abffab1216af0c55dc38815a5c522.

I add a file called `file test.txt` and test if it exists: `\file_if_exist:nTF {file~test.txt}{\TRUE}{\FALSE}` in `m3file001.lvt`. The `pdftex` gives the correct output `TRUE` as expected in `3file001.tlg` but when other engines give wrong results.

By the way, the `testfile.txt` is mistyped and it should be `filetest.txt`.
https://github.com/latex3/latex3/blob/1db9abb8381d9197d38abd09e18cdbf23602284d/l3kernel/testfiles/m3file001.lvt#L34

**Comment by josephwright** [comment]
I get the correct result with (u)pTeX: just XeTeX and LuaTeX fail. Is that what you are seeing?

**Comment by zepinglee** [comment]
Ah, my mistake. The results of pTeX/upTex are correct.

**Comment by josephwright** [comment]
I think I see the issue: seems the XeTeX implementation of the primitive doesn't ignore quote marks, probably the same for LuaTeX. Should be fixed soon.

**Comment by zepinglee** [comment]
https://github.com/latex3/latex3/blob/7ac253b59fe96d6a8fe0a3b14b0937f0d612d697/l3kernel/testfiles/m3file001.tlg#L5-L16

The expectation in the title needs `/T/T` at the end.
