### ISSUE TITLE
Should primitive conditionals still be a part of expl3?

### ISSUE THREAD

**Issue by wspr** [latex3/latex3#643]
Logging this thought for later.

I count around 20 "primitive conditionals" in source3. Given the tidying up we've done in other places, I think we should consider deprecating at least a good number of these — they're fragile and unnecessary IMO. Perhaps in the first instance we could check all uses in TeXLive and deprecate those not in current use (I suspect that is the majority of them). Then see what is left over.

**Comment by josephwright** [comment]
I think the short answer here is 'yes'. There are places where performance is important, and for those, primitives are useful. There are _lots_ of uses of the primitive conditionals in TeX Live: far too many to drop.

**Comment by FrankMittelbach** [comment]
Perhaps it need some verification but I agree that there are places where you want them for speed and most likely they are used. And dropping only a handful and keeping the rest wouldn't be that consistent either, so I'm also voting for keeping them.

**Comment by blefloch** [comment]
I agree we should keep them.  Removing them would be really annoying for
my packages and for many of my answers on StackExchange.

**Comment by wspr** [comment]
Thanks for the comments. Sounds sensible. On a re-look I don't see what my main objection here was :)
