### ISSUE TITLE
l3kernel v. 2019-10-27 crashes XeLaTeX in Ubuntu 18.04

### ISSUE THREAD

**Issue by jsbtic** [latex3/latex3#644]
Hi,
     for some reason the l3kernel v. 2019-10-27 causes the following error with xelatex

```console
This is XeTeX, Version 3.14159265-2.6-0.99998 (TeX Live 2017/Debian)
 (preloadedf ormat=xelatex)
 restricted \write18 enabled.
entering extended mode
(./test.tex
LaTeX2e <2017-04-15>
Babel <3.18> and hyphenation patterns for 84 language(s) loaded.
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/home/johndoe/texmf/tex/latex/fontspec/fontspec.sty
(/home/johndoe/texmf/tex/latex/l3packages/xparse/xparse.sty
(/home/johndoe/texmf/tex/latex/l3kernel/expl3.sty
(/home/johndoe/texmf/tex/latex/l3kernel/expl3-code.tex)
Runaway argument?
##2##3{\if_int_compare:w ##1>1\exp_stop_f: \exp_after:wN \__tl_range_collect_un
braced:w \ETC.
! File ended while scanning use of \__char_data_auxii:w.
<inserted text> 
                \par 
l.50   {\input{expl3-code.tex}}
                               %^^M
?
```
Here's a MWE
```latex
\documentclass{article} 
\usepackage{fontspec}

\begin{document}
lorem ipsum
\end{document} 
```

with luatex (v. 1.0.4) everything works fine. Here's the `\listfiles` output:

```console
 *File List*
 article.cls    2014/09/29 v1.4h Standard LaTeX document class
  size11.clo    2014/09/29 v1.4h Standard LaTeX file (size option)
fontspec.sty    2019/10/19 v2.7d Font selection for XeLaTeX and LuaLaTeX
  xparse.sty    2019-10-11 L3 Experimental document command parser
   expl3.sty    2019-10-27 L3 programming layer (loader) 
expl3-code.tex    2019-10-27 L3 programming layer 
l3backend-xdvipdfmx.def    2019-04-06 L3 backend support: xdvipdfmx
fontspec-xetex.sty    2019/10/19 v2.7d Font selection for XeLaTeX and LuaLaTeX
 fontenc.sty
   tuenc.def    2017/04/05 v2.0i Standard LaTeX file
fontspec.cfg
 ***********
```

Does anyone else have the same problem?

**Comment by u-fischer** [comment]
Why are you using an new l3kernel  in a texlive 2017? (I can't reproduce the problem in a current texlive 2019 and would have to install l3kernel in an older one first for a test.)

**Comment by josephwright** [comment]
As a ref, issue has been present since 2019-09-05 release: I see the general area.

**Comment by josephwright** [comment]
Problem stems from b13f4d26eb24f19251730c52e8307623c89401b3, though it's a bit hard to track down due to other bugs in the same set of commits.

**Comment by jsbtic** [comment]
> Why are you using an new l3kernel in a texlive 2017? (I can't reproduce the problem in a current texlive 2019 and would have to install l3kernel in an older one first for a test.)

At some point some package usually requires newer version an other package and over time these requirements cumulate and eventually one also needs a newer version of l3-packages. But you are quite right that one could solve this by upgrading to newer version TexLive (e.g. Ubuntu distro upgrade)
