### ISSUE TITLE
impossible change pdfversion in pdflatex

### ISSUE THREAD

**Issue by AlexandrKozlovskiy** [latex3/latex3#645]
When i use:
```latex
\ExplSyntaxOn
\pdf_version_gset:n{2.0}
\ExplSyntaxOff
```
in pdflatex i have pdf 1.0 instead 2.0. In lualatex it's all ok.

**Comment by josephwright** [comment]
The current release pdfTeX does not support setting PDF major version: the value is hard-coded in the binary as `1`. The LaTeX team have submitted a patch to introduce new functionality here, but that will not be released before TeX Live 2020 at the earliest.

**Comment by blefloch** [comment]
Wouldn't it make sense then to have an error message if a version cannot
be set in the engine in use?

**Comment by u-fischer** [comment]
@blefloch I haven't made up my mind yet, which tests are needed/sensible here. Also with the other engines the support for 2.x is quite new and it could get messy if we try to catch every case (and I'm not even sure if it can be checked safely).

**Comment by AlexandrKozlovskiy** [comment]
Yes,in my opinion it better throws an error,if it impossible set pdf version. If it will be in pdflatex,this feature,i mean setting major version of pdf will works only in texlive or in miktex to?

**Comment by u-fischer** [comment]
miktex will certainly get the changes too.
