### ISSUE TITLE
\tl_if_eq_p:nn is missing

### ISSUE THREAD

**Issue by callegar** [latex3/latex3#647]
`\tl_if_eq_p:nn` is missing. This means that it is also impossible to generate a variant ``\tl_if_eq_p:Vn` that would be useful in some cases.

Is this intentional for some practical reason or just something that got lost by mistake?

**Comment by stone-zeng** [comment]
It's because the `:nn` version is not expandable.

**Comment by eg9** [comment]
`\tl_if_eq:nn(TF)` is not expandable, so the predicate form can't be available.

**Comment by dbitouze** [comment]
But would it make sense to provide `\tl_if_eq_p:Nn`? It would be helpful if the commented part in the following MCE would work:
```latex
\documentclass{article}
\begin{document}
\ExplSyntaxOn

\tl_set:Nn \l_tmpa_tl { foo }
\tl_set:Nn \l_tmpb_tl { bar }

\tl_if_eq:NnTF \l_tmpa_tl {
  bar
} {True} { False }

\bool_if:nTF {
  \tl_if_eq_p:NN \l_tmpa_tl \l_tmpb_tl
}{True} {False}

% \bool_if:nTF {
%   \tl_if_eq_p:Nn \l_tmpa_tl {bar}
% }{True} {False}

\ExplSyntaxOff
\end{document}
```

**Comment by PhelypeOleinik** [comment]
@dbitouze The issue remains. `\tl_if_eq:Nn` (or `:nn` or `:nN`) would not be expandable, thus it doesn't work where `_p:` variants go.  In your example you can safely use `\str_if_eq_p:nn` though to get the same results.

**Comment by dbitouze** [comment]
@PhelypeOleinik OK but there's no `\str_if_eq_p:Nn` and I'd like to test a (token list or string) *variable* against a token list or a string.

**Comment by PhelypeOleinik** [comment]
@dbitouze Can't check now, but I believe there is `\str_if_eq_p:Vn`, which turns the variable into an `n` argument.  If that's not built in the kernel, you can define yourself with `\prg_generate_conditional_variant:Nnn \str_if_eq:nn { V } { p }`.
