### ISSUE TITLE
l3doc: referenced destination HD.0 does not exist

### ISSUE THREAD

**Issue by PhelypeOleinik** [latex3/latex3#649]
With the example:
```latex
% arara: pdflatex
% arara: makeindex: { style: gind.ist }
% arara: pdflatex
\documentclass{l3doc}
\begin{document}
abc\cs{def}
\PrintIndex
\end{document}
```
pdfLaTeX complains:
```none
pdfTeX warning (dest): name{HD.0} has been referenced but does not exist, replaced by a fixed one
```

**Comment by u-fischer** [comment]
The `\cs` command doesn't set a target (for hypdoc). It should internally do something like this;

~~~~
\documentclass{l3doc}

\begin{document}

abc \makeatletter\HD@target\makeatother\cs{def}

xxx \makeatletter\HD@target\makeatother\cs{def}
\PrintIndex
\end{document}
~~~~

**Comment by u-fischer** [comment]
The bug affects also the l3kernel documention, but it is not very obvious as there are so many targets that the jumps are "near enough". One example is e.g. \ExplSyntaxOn which has a link to page 118 but jumps to the previous target on page 117.

**Comment by blefloch** [comment]
I tried @u-fischer 's fix, but this leads to more warnings from `makeindex` and more repeated entries in the index because `makeindex` is not able to merge multiple `\cs{foo}` appearing one after the other.
