### ISSUE TITLE
Feature request: new function \int_if_pos:nTF

### ISSUE THREAD

**Issue by ajparsloe** [latex3/latex3#652]
At present `l3int` provides `\int_if_odd:n` and `\int_if_even:n`. I've found a number of occasions where it would be convenient to write 
```
\int_if_pos:nTF { int expr } 
    { ... } { ... }
```
where an integer is being used like a flag, but its actual value is irrelevant beyond the fact that it is non-zero. Obviously it is not difficult to write
```
\int_compare:nNnTF { int expr } > { 0 } 
    { ... } { ... }
```
but it is not as immediately obvious. (I did consider using flags but according to the l3flag documentation, they are very much slower.)

**Comment by eg9** [comment]
`\int_compare:nTF { <int expr> !=0 } { true } { false }`

**Comment by ajparsloe** [comment]
On reflection, it would be more consistent with conditionals like `\tl_if_empty:nTF` to define `\int_if_zero:nTF` returning true when the integer is zero (and just as useful for the specific matter that prompted this request).

**Comment by blefloch** [comment]
I'm against \int_if_pos because it is slightly ambiguous as to whether 0
is considered positive or not (e.g., in French, inequalities are "or
equal" by default).

\int_if_zero sounds like feature creep, but the consistency argument
makes sense.

**Comment by wspr** [comment]
FWIW I think I have wanted \int_if_zero:N before as a kind of partner to \int_zero:N. (Of course i forget the context now.) I may even have a local definition of just that in my packages.

**Comment by FrankMittelbach** [comment]
Am 22.12.19 um 11:23 schrieb Bruno Le Floch:
> I'm against \int_if_pos because it is slightly ambiguous as to
> whether 0 is considered positive or not (e.g., in French,
> inequalities are "or equal" by default).

I understand that you can describe "x is positive" as  0<x and if you
say something like greater is always "greater or equal by default in
French ... hmmm

  But then
"if positive"  as well as  "if negative" would be true for 0, would it
not? Seems strange.


Anyway I  wouldn't like "pos" in the first place. It could perhaps be
\int_if_positive:nTF but if you say it is ambigous in French then maybe not.

> \int_if_zero sounds like feature creep, but the consistency argument 
> makes sense.

I wouldn't mind that

**Comment by car222222** [comment]
﻿
> On 23 Dec 2019, at 07:50, Frank Mittelbach <notifications@github.com> wrote:
> 
> But then
> "if positive" as well as "if negative" would be true for 0, would it
> not? Seems strange.

Oh, site, ces francais!!  
In English we sometimes use the adjective “Strictly . . . “ to make it clear, so I guess that 0 is both positive and negative for some people (but maybe not in some countries??).

> Anyway I wouldn't like "pos" in the first place.
Nor me.

Merry Christmas!

**Comment by car222222** [comment]
Where did that “site” come from?
>  Oh, site, ces francais!!

**Comment by jfbu** [comment]
Only to confirm French usage (which has the advantage of avoiding convoluted "non-negative" of Anglo-Saxons), however `positive` is English if not confusable with feminine form of French `positif`. Thus `\inf_if_positive:nTF` is not "ambiguous in French" as it is English.

**Comment by car222222** [comment]
Aha, a new module, “l3inf” 👍  :-)
 \inf_if_
Special Xmas release with full support for evaluating 
“strongly inaccessible cardinals”??

**Comment by jfbu** [comment]
> Special Xmas release with full support for evaluating
> “strongly inaccessible cardinals”??

What a better gift to Bruno than such a challenge?

**Comment by josephwright** [comment]
I think unless we can see a need for significant optimisation, this is not really something we want to add.

**Comment by ajparsloe** [comment]
I had forgotten that this was still languishing out there in the github undergrowth. I have defined for my own use `\int_if_zero:nTF` because (i) it is shorter to write and (ii) seems that little bit more straightforward and "obvious" than `\int_compare:nNnTF`. But I have no objection to this being closed.

**Comment by car222222** [comment]
I think that the suggested \int_if_zero:nTF test should be added to the kernel, even at this late stage, as it is both: a fundamental, very common test on integers in many contexts; and it is totally ambiguity free.
