### ISSUE TITLE
l3keys: inherit doesn't seem to inherit .value_forbidden:n

### ISSUE THREAD

**Issue by fpantigny** [latex3/latex3#653]
Consider the following code:

    \documentclass{article}
    \usepackage{expl3}[2019-11-07]
    \ExplSyntaxOn
    \keys_define:nn { foo } 
      { 
        test .code:n = {} ,
        test .value_forbidden:n = true ,
      }
    \keys_define:nn { } { bar .inherit:n = foo }
    \keys_set:nn { bar } { test = a }
    \ExplSyntaxOff
    \begin{document}
    Some text.
    \end{document}

It should raise an error since the key `test` is used with a value in the command `\keys_set:nn`. However, there is no error at compilation.

**Comment by josephwright** [comment]
I'm not sure this is a bug: inheritance means that values are passed along, its not clear that this means that forbidden/required status does.

**Comment by fpantigny** [comment]
I understand. However, I think it would be useful to have a mechanism to pass all the characteristics of a key.
