### ISSUE TITLE
[xtemplate] Use of instance-type keys not clearly documented

### ISSUE THREAD

**Issue by tail-reversion** [latex3/latex3#656]
Template parameters can include instances of other templates, however, the documentation does not say what type of variable the instances should be assigned to, nor does it say how to use an instance-type parameter in template code.

That is, given

```
\DeclareTemplateInterface { myobject } { mytemplate } { 0 }
  { foo : instance { otherobject } }
```

it is unclear how to proceed at the next step:

```
\DeclareTemplateCode { myobject } { mytemplate } { 0 }
  { foo = ??? }
  { how to use foo? }
```

**Comment by tail-reversion** [comment]
Reading through the code of xgalley and its example file, I’ve found that the name of the instance is what should be passed to the parameter key, that the appropriate variable is a function name with the correct signature, and that the assigned instance is then used like any other function.

That is, the next step would be

```
\DeclareTemplateCode { myobject } { mytemplate } { 0 }
  { foo = \__my_foo: }
  { \__my_foo: }
```

and

```
\DeclareInstance { myobject } { myinstance } { mytemplate }
  { foo = myotherinstance }
```

**Comment by josephwright** [comment]
It's pretty clear that `xtemplate` is a set of good ideas but won't go forward: I'm not sure what's best here.

**Comment by car222222** [comment]
>> but won't go forward

Meaning?

**Comment by FrankMittelbach** [comment]
> > > but won't go forward
> 
> Meaning?

meaning that most of us (all? I?) think that xtemplate was a good prototype with good ideas but not necessarily the best or the most appropriate ones in the end and that by the end of the days the final interface will look different even though it will probably incoprporate several of the ideas in xtemplate in one way or the other. And that's what Joseph referred to.

**Comment by car222222** [comment]
Ok, so just the interfaces will not 'go forward'.  Much relief.

**Comment by tail-reversion** [comment]
Considering this information and considering how heavily my experimental class relies on xtemplate, it sounds like it might be best to shelve the class, for the time being, and spend my time on other LaTeX-related development.

**Comment by josephwright** [comment]
@tail-reversion `xtemplate` is not going to get removed or anything like that: there will at some stage be an improved approach. I wouldn't want to put you off: if no one tries stuff out, we don't know where to go next!

**Comment by tail-reversion** [comment]
In that case, I’ll continue developing the class, using xtemplate. When a better solution is ready, then I’ll replace the old code.

**Comment by josephwright** [comment]
This has all moved to the kernel: I'm not sure if the query is still valid, but will close here and a new one can be opened on the 2e repo if needed.
