### ISSUE TITLE
Unused global option warning for driver

### ISSUE THREAD

**Issue by aminophen** [latex3/latex3#657]
## Brief outline of the bug

When compiling the MWE with latex-dev (in DVI mode), it shows a warning:

```
LaTeX Warning: Unused global option(s):
    [dvipdfmx].
```

but the option is actually used when expl3 is preloaded into the format, in order to select the backend (in this case `l3backend-dvipdfmx.def`).  The global driver option that can be interpreted as an expl3 backend should be free from the warning.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass[dvipdfmx]{article}
\begin{document}
a
\end{document}
```

## Log file (required) and possibly PDF file  

* [drv.log](https://github.com/latex3/latex2e/files/4025285/drv.log)

**Comment by josephwright** [comment]
This looks like a timing issue: the option does get removed, but not early enough as the warning has already been issued. I'll have to think about it a bit.

**Comment by josephwright** [comment]
Probably this will go to CTAN toward the end of the week: OK?

**Comment by aminophen** [comment]
Checked 26da686; seems ok, thank you very much.
