### ISSUE TITLE
[l3keys] Require value by default for standard setters

### ISSUE THREAD

**Issue by tail-reversion** [latex3/latex3#661]
For standard setters (e.g. `.dim_set:N`) it would be useful if it the property `.value_required:n` would default to `true`, especially since such keys will fail confusingly, if no value is given.

**Comment by Skillmon** [comment]
I don't think that this should be done. I could create a key that is a `.dim_set:N` but provide a default value for it, so that the key without a value serves as a reset to package defaults. This would break such code in existing packages.

**Comment by blefloch** [comment]
On 1/14/20 7:17 PM, Skillmon wrote:
> I don't think that this should be done. I could create a key that is a
> |.dim_set:N| but provide a default value for it, so that the key without
> a value serves as a reset to package defaults. This would break such
> code in existing packages.

I don't think an interface like you describe, Skillmon, is very clear,
but one way to avoid breaking such a hypothetical use would be as
follows: make |.dim_set:N| imply |required|, make any |default| setting
cancel |required|.  (There may be ordering issues with the settings?)

**Comment by tail-reversion** [comment]
I like @blefloch’s suggestion. And, since key properties are already documented as being order-sensitive, it would not be a strange, new idea for programmer to deal with.
