### ISSUE TITLE
Deprecation of `\l_tl_case_change_exclude_tl` not documented

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#663]
AFAICS, `\l_tl_case_change_exclude_tl` has been:

- deprecated,
-  replaced by `\l_text_case_exclude_arg_tl` (am I right?),

but this isn't documented anywhere.

**Comment by josephwright** [comment]
As the entire `tl` case change code was experimental, adding it to the deprecation cycle was not a given: we did because it's in use in some people's code. However, the control `tl` isn't in any packages in TeX Live, so doesn't go into the deprecation cycle (it's tricky to do anyway).

**Comment by dbitouze** [comment]
OK, thanks.

Does `\l_text_case_exclude_arg_tl` replace `\l_tl_case_change_exclude_tl`?

**Comment by josephwright** [comment]
Yes, that's correct. It's possible we may yet need to extend the mechanism here a bit, but as the code is now stable that would go with a formally-supported cycle if we needed to change `\l_text_case_exclude_arg_tl`.

**Comment by dbitouze** [comment]
OK, thanks.
