### ISSUE TITLE
[l3legacy] Add setters for legacy booleans

### ISSUE THREAD

**Issue by tail-reversion** [latex3/latex3#664]
To complement `\legacy_if:n(TF)`, it would be useful to have functions that abstract over the old Boolean setters (e.g. `\@twosidetrue`), including global versions of such functions. Perhaps inverse setters would be useful, too?

Since this would be a small, simple addition, I’d be happy to make a fork and send a pull request.

**Comment by wspr** [comment]
What would we call these? \legacy_bool_(g)set_true:n ?
It makes me wonder if \legacy_bool_if:n(TF) would be a better name than \legacy_if:n(TF) …

**Comment by tail-reversion** [comment]
> What would we call these? \legacy_bool_(g)set_true:n ? It makes me wonder if \legacy_bool_if:n(TF) would be a better name than \legacy_if:n(TF) …

I agree on both points.

**Comment by josephwright** [comment]
We avoided `bool` here as it would be confusing with `\bool_...`: the 'raw' conditionals are called `\if_..`.

**Comment by wspr** [comment]
Alternative for \legacy_bool_(g)set_(true|false):n then?  \legacy_if_set_(true|false):n ?? Or do you think this is a bridge too far?

**Comment by Skillmon** [comment]
Also hearing `\lecagcy_bool` I'd think of `etoolbox`'s bools and not of plain's `\if` constructs.
