### ISSUE TITLE
If \text_titlecase replaces \tl_mixed_case, should be explicit

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#665]
In https://github.com/latex3/latex3/blob/master/l3kernel/CHANGELOG.md, 2020-01-12, it is said:

- Added: `\text_<type>case:n(n)`
- Deprecated: `\tl_<type>_case:n(n)`

It is not so evident the former _replaces_ the latter, e.g. that `\text_uppercase` replaces `\text_upper_case` but, AFAICS, `\text_titlecase` replace `\tl_mixed_case`. Given the underlying names ("title" vs "mixed") are different, the replacement should be explicit.

More generally, the successive name replacements should be listed somewhere.

**Comment by josephwright** [comment]
Most of the time, direct replacements are listed in the ChangeLog. Here, we have a couple of wrinkles

- `\tl_.._case:n` functions were never stable
- The code has been re-worked so it's not quite a drop-in name change

That said, we can list this information: it's basically the same as covered in the code in `l3deprecations`.

**Comment by dbitouze** [comment]
OK, thanks for pointing out `l3deprecation` (spurious "s" in your last comment). BTW:

- why no `l3deprecation.pdf` is provided?
- is it documented somewhere how to make a package that used to use deprecated commands to work with:
  - TeX installations where those commands were not deprecated,
  - TeX installations where those commands now are deprecated?

**Comment by josephwright** [comment]
The deprecation code appears in `source3` but not elsewhere: it's there to give you the warnings/errors if you set debugging.

In terms of deprecation, we've been pretty clear that we only support the current release: that's the whole 'broadly stable but still experimental' business. You can always do
```latex
\cs_if_exist:NTF \text_uppercase:n
   { \cs_set_eq:NN \private_uppercase:n \text_uppercase:n }
  { \cs_set_eq:NN \private_uppercase:n \tl_upper_case:n }
```
or similar.

**Comment by josephwright** [comment]
I've updated the ChangeLog here; we could consider adding an explicit `.txt` file to list mappings, or extend `l3obsolete`.
