### ISSUE TITLE
[l3keys] Set keys from property list

### ISSUE THREAD

**Issue by tail-reversion** [latex3/latex3#669]
It would be convenient to be able to take a property list and use it to set keys, i.e. `\keys_set_from_prop:nN`. Something like this is already done in xtemplate, but I think that this would be useful for general-purpose programming and other concepts.

Such a function can already be implemented using the public interface, but I’m guessing that the private interface would offer a more efficient implementation.

Also, if one were to implement this function using the public interface, the fact that `\prop_map_function:NN` does not guarantee the order in which entries are processed means that, if some keys need to be set in a certain order, then the order must be stored, separately, as a seq.

**Comment by josephwright** [comment]
A couple of things. First, on ordering, I'd strongly encourage not making keys ordered: I tend to think of them as properties not actions. That avoids any issue with needing a sequence. Second, could you provide a use case here that's not covered by a simple mapping?

**Comment by tail-reversion** [comment]
For context: while working on my class, I’ve found that xtemplate is awkward for describing design-level concepts, but its ability to save and edit settings is useful, that can even be used as a programming pattern, in some cases.

Therefore, the general use case would be when one wants to store commonly-used key settings and have the ability to copy and to edit them. Aside from being useful for managing design settings, it could be useful to programmers for managing variables that are not local to functions, analogous to how catcode tables are used. And, like catcode tables, this would be more flexible than simply saving settings in a macro.

**Comment by tail-reversion** [comment]
Since ordering isn’t a concern, then `\prop_map_function:NN` would be fine.

**Comment by tail-reversion** [comment]
@josephwright Forgive me, I may have misunderstood your second question.

**Comment by u-fischer** [comment]
> I'd strongly encourage not making keys ordered: I tend to think of them as properties not actions.

While I do understand the feeling, I think that this is difficult to do. As soon graphics and drawing is involved keys tends to have an action element and order matters:

~~~~
\documentclass{article}
\usepackage{tikz}
\usepackage{graphicx}

\begin{document}

\includegraphics[angle=45,height=1cm]{example-image-duck}

\includegraphics[height=1cm,angle=45]{example-image-duck}

\tikz\path[red,fill=green] (0,0) rectangle (1,1);

\tikz\path[fill=green,red] (0,0) rectangle (1,1);

\end{document}
~~~~

![image](https://user-images.githubusercontent.com/4047173/73824417-6a5b8400-47fa-11ea-8429-f5726de97511.png)

The first could probably be made order independant by changing the height key to mean "final height", but I don't quite see how to handle combinations of base and meta keys like in the tikz example without making it difficult for the user to understand.

Order can also matter for test suites. That isn't really a problem with latex properties as they are predictable, but lua tables e.g. have to be sorted sometimes to avoid randomly changing outputs.

**Comment by FrankMittelbach** [comment]
I also don't really believe that you can ignore the order. There are too many use cases where order matters. Basically half of the design templates that have be done via xtemplate rely on order and they aren't the odd ones out, really.

**Comment by josephwright** [comment]
@dffischer  Lots of programming lnaguages use keys without ordering them ...

**Comment by davidcarlisle** [comment]
@josephwright in a language where keys are scalar values it's relatively easy to have a let form where order is guaranteed not to have an effect as all settings are set using cached values from above, and the value assigned to one key never depends on a value assigned to another key in the same block of assignments.

But in a situation as here where keys can execute arbitrary code and have arbitrary side effects it would be really quite difficult to arrange that order does not matter wouldn't it?

**Comment by FrankMittelbach** [comment]
sure, all I'm saying is that the use cases I've in the design space fairly often require it to usefully apply the concept without requiring a huge amount of (unwanted) repetition.

**Comment by tail-reversion** [comment]
Although it’s preferable to have keys be unordered, for the cases where order does matter, perhaps there could be a means by which the order could be declared?

**Comment by tail-reversion** [comment]
Perhaps a two-step process could be used:

1. Provide a `\prop_to_keyval:N` function, which doesn’t have to guarantee key order.
2. Provide a `\tl_sort_keyval:Nn` function, which uses a clist to determine the order that keys should be sorted, perhaps with special handling for unmentioned keys. (It would also be nice if the sorting could be done expandably, but it’s not necessary.)

**Comment by josephwright** [comment]
We've added `\prop_to_keyval:N`, so closing.

**Comment by Skillmon** [comment]
To be fair, `\prop_to_keyval:N` isn't as fast as a direct map would've been.

On the order of keys: An expandable `\tl_sort:nN` function is available, you could use that with a slightly involved conditional function:

```
\ExplSyntaxOn
\cs_generate_variant:Nn \tl_map_tokens:nn { e }
\cs_generate_variant:Nn \tl_sort:nN { e }
\cs_generate_variant:Nn \clist_map_function:nN { e }
\seq_const_from_clist:Nn \c_tailrevision_key_order_seq
  { key1, key2, key3 }
% to understand this function look from inside to outside!
\cs_new:Npn \tailrevision_prop_to_sorted_keyval:N #1
  {
    \exp_args:Ne
    \exp_not:o
      {
        % remove the leading comma from the next transformation
        \exp_not:N \use_none:n
        % turn the tl-elements back into keyval-elements
        \tl_map_tokens:en
          {
            % sort the tl-elements
            \tl_sort:eN 
              {
                % turn the keyval-list's elements into tl-elements
                \clist_map_function:eN
                  { \prop_to_keyval:N #1 }
                  \__tailrevision_brace:n
              }
              \__tailrevision_sort:nnTF
          }
          { , ~ \exp_not:n } % also restores the leading spaces
      }
  }
\cs_new:Npn \__tailrevision_brace:n #1 { { \exp_not:n {#1} } }
\prg_new_conditional:Npnn \__tailrevision_sort:nn #1#2 { TF }
  {
    % evil function knowing the output form of \prop_to_keyval:N and that
    % \clist_map_function:nN will have stripped the leading spaces!
    \__tailrevision_sort_extract:ww #1\q_stop #2\q_stop
  }
\cs_new:Npn \__tailrevision_sort_extract:ww #1=#2\q_stop #3=#4\q_stop
  {
    % if both equal don't swap
    \str_if_eq:nnF {#1} {#3}
      {
        \seq_map_tokens:Nn \c_tailrevision_key_order_seq
          { \__tailrevision_sort_compare:nnn {#1} {#3} }
      }
    \prg_return_true:
  }
\cs_new:Npn \__tailrevision_sort_compare:nnn #1#2#3
  {
    % if first key has higher priority don't swap
    \str_if_eq:nnTF {#1} {#3}
      { \seq_map_break: }
      {
        % if second key has higher priority swap
        \str_if_eq:nnT {#2} {#3}
          { \seq_map_break:n { \use_i:nn \prg_return_false: } }
      }
  }

\prop_set_from_keyval:Nn \l_tmpa_prop { key3 = 1 , key1 = 1, key2 = 1 }
\exp_args:Ne \tl_analysis_show:n 
  { \tailrevision_prop_to_sorted_keyval:N \l_tmpa_prop }
\ExplSyntaxOff
```
