### ISSUE TITLE
[xparse] \NewExpandableDocumentCommand and delimited Arguments

### ISSUE THREAD

**Issue by mrpiggi** [latex3/latex3#672]
## Brief outline of the bug
Using delimited argument with identical characters like r'' in \NewExpandableDocumentCommand throws an error.

## Minimal example showing the bug

```latex
\listfiles
\documentclass{article}
\usepackage{xparse}
\begin{document}
\NewExpandableDocumentCommand\TestQuote{r""}{#1}
\TestQuote""

\NewExpandableDocumentCommand\TestAngle{r<<}{#1}
\TestAngle<<

\NewExpandableDocumentCommand\TestSlash{r//}{#1}
\TestSlash//

\NewExpandableDocumentCommand\TestExclam{r!!}{#1}
\TestExclam!!

\NewExpandableDocumentCommand\TestApostrophe{r''}{#1}
\TestApostrophe''

\NewExpandableDocumentCommand\TestBar{r||}{#1}
\TestBar||
\end{document}
```

## Log file (required) and possibly PDF file  
[test.log](https://github.com/latex3/latex3/files/4202137/test.log)

**Comment by PhelypeOleinik** [comment]
Fixed. Thanks for the report!

**Comment by mrpiggi** [comment]
That was really fast! :)

**Comment by PhelypeOleinik** [comment]
If all bugs were this easy... ;-)

**Comment by blefloch** [comment]
Can you also add a regression test to one of the existing
testfiles/xparse00N.lvt please?
