### ISSUE TITLE
[l3doc]  conflicting index entries when referencing "usage"

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/latex3#673]
Just came across a document generating the following usage entries:
```
\indexentry{TeX and LaTeX2e commands:=\TeX{} and \LaTeXe{} commands:>@tryfcolumn={\verbatim@font \verb*&\@tryfcolumn&}|hdclindex{80}{usage}}{11}
\indexentry{TeX and LaTeX2e commands:=\TeX{} and \LaTeXe{} commands:>@tryfcolumn={\verbatim@font \verb*&\@tryfcolumn&}|hdclindex{80}{usage}}{11}
\indexentry{TeX and LaTeX2e commands:=\TeX{} and \LaTeXe{} commands:>@tryfcolumn={\verbatim@font \verb*&\@tryfcolumn&}|hdclindex{85}{usage}}{11}
```

Those got generated through

```
 text ... \cs{@tryfcolumn} .... \cs{@tryfcolumn ... text
<code block>
test ... \cs{@tryfcolumn} 
```

looks like the conflicting numbers 80 and 85 are hyperref backlinks to a nearby code block and and here the three  `\cs` calls are in different text blocks but on the same page (i.e., 11).

As a result one gets warnings about bad encaps and the page number 11 twice in the index.

Maybe the hyperlink should just go to the page not to a code block if making "page reference".

**Comment by blefloch** [comment]
We have the same problem in `interface3`: for instance the index for `\ExplSyntaxOn` has two links to the same page 9 (and correspondingly `makeindex` complains).

I'm tempted to suggest parsing the `ind` file after the fact and removing offending entries (all those after the first on a page) on the TeX side.

**Comment by josephwright** [comment]
I think one to revisit once we address https://github.com/latex3/latex3/issues/1136.
