### ISSUE TITLE
l3backend-dvips.def (2020-02-21) broken?

### ISSUE THREAD

**Issue by balducci** [latex3/latex3#679]
## Brief outline of the bug

Processing the source below fails with l3backend-dvips.def
(2020-02-21), where it succeeds with l3backend-dvips.def (2020-02-03)

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\begin{document}
Hello, world!
\end{document}
```

## Log file (required) and possibly PDF file  

[mom.log](https://github.com/latex3/latex2e/files/4241221/mom.log)

thanks a lot
ciao
-gabriele

**Comment by josephwright** [comment]
I'll re-release the backend to address this

**Comment by balducci** [comment]
>     * There was a matching update to `l3kernel` which it looks like you are missing

oh yes! I forgot to rebuild the latex formats after upgrade of l3kernel/l3backend
After rebuilding my latex formats vs latest l3kernel/l3backend the error seems to have gone

Apologies for the noise!

and thank you very much indeed

ciao
-g
