### ISSUE TITLE
Cannot extract code from \@begindocumenthook after preloading expl3

### ISSUE THREAD

**Issue by aminophen** [latex3/latex3#681]
I'm not sure whether this is the correct place for reporting this ...

## Brief outline of the bug

After LaTeX2e 2020-02-02 with preloading expl3, \patchcmd of etoolbox cannot detect codes inserted into `\@begindocumenthook`.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}

% try to detect \foobar inserted into \@begindocumenthook
\AtBeginDocument{\foobar}
\makeatletter
\usepackage{etoolbox}
\patchcmd\@begindocumenthook{\foobar}{}{\YES}{\NO}

\stop
```

## Log file (required) and possibly PDF file  

* [latex20200202.log](https://github.com/latex3/latex3/files/4244417/latex20200202.log)

For reference, the result with LaTeX2e 2019-10-01 patch level 3 is also attached.

* [latex20191001.log](https://github.com/latex3/latex3/files/4244416/latex20191001.log)

**Comment by josephwright** [comment]
`\tracingpatches` will tell you the reason:
```
[debug] tracing \patchcmd on input line 9
[debug] analyzing '\@begindocumenthook'
[debug] ++ control sequence is defined
[debug] ++ control sequence is a macro
[debug] -- macro cannot be retokenized cleanly
[debug] -> the macro may have been defined under a category
[debug]    code regime different from the current one
[debug] -> the replacement text may contain special control
[debug]    sequence tokens formed with \csname...\endcsname;
[debug] -> the replacement text may contain carriage return,
[debug]    newline, or similar characters
```
as we have some `expl3` code there. However, lots of other 'stuff' can lead to the same (try loading `siunitx` with an older kernel, and I don't feel we've ever supported removal of material in this way.

There is work ongoing on hook management, and that will likely include more formalised mechanisms to adjust hook content. However, that won't directly allow manipulation of `\@begindocumenthook`.

**Comment by josephwright** [comment]
Perhaps you could outline a real use case?

**Comment by josephwright** [comment]
Even just loading `expl3` would have done this in the past: we need some information up-front.

**Comment by aminophen** [comment]
> a real use case

A Japanese user have reported that the following code does not work after upgrading LaTeX2e to 2020-02-02:

``` tex
\documentclass[dvipdfmx,b5j,landscape]{tbook}
\usepackage{lltjp-geometry}
\usepackage{geometry}
\usepackage{bxjalipsum}
\begin{document}
\jalipsum{wagahai}
\end{document}
```

However, we can get the correct output by `\usepackage[force]{lltjp-geometry}`.

The difference between `\usepackage{lltjp-geometry}` and `\usepackage[force]{lltjp-geometry}` is that the former executes

``` tex
\patchcmd\@begindocumenthook{\tate}{\tate}{\@ltj@@geometry@tatetrue}{}%
```

which tries to detect automatically whether `\tate` is executed or not.

**Comment by davidcarlisle** [comment]
If you do the patch with a combined makeatletter /ExplSyntaxOn regime then it does succeed, although as Joseph says this isn't really a supported interface to the hook

```
\documentclass{article}

% try to detect \foobar inserted into \@begindocumenthook
\AtBeginDocument{\foobar}
\makeatletter
\usepackage{etoolbox}

\ExplSyntaxOn
\patchcmd\@begindocumenthook{\foobar}{}{\YES}{\NO}
\ExplSyntaxOff
\stop
```

**Comment by aminophen** [comment]
> If you do the patch with a combined makeatletter /ExplSyntaxOn regime then it does succeed

Thanks.

> as Joseph says this isn't really a supported interface to the hook

I see ..., but I'd like to know some supported interface to manipulate the hook; sometimes we need to extract some information from `\@begindocumenthook`

**Comment by PhelypeOleinik** [comment]
On Mon, Feb 24, 2020 at 9:22 AM Hironobu Yamashita
<notifications@github.com> wrote:
>
> If you do the patch with a combined makeatletter /ExplSyntaxOn regime then it does succeed

Note that this is not guaranteed to work. As soon as
something with a space character is added to the hook,
it won't work anymore:
```latex
\documentclass{article}
\AtBeginDocument{\foobar}
\makeatletter
% Uncomment this:
% \AtBeginDocument{\@gobble{something with space}}
\usepackage{etoolbox}
\ExplSyntaxOn
\patchcmd\@begindocumenthook{\foobar}{}{\YES}{\NO}
\ExplSyntaxOff
\stop
```

**Comment by FrankMittelbach** [comment]
@aminophen we plan a full fledged hook management for the fall release, so this will take a bit of time, but we'll keep your use case in mind

**Comment by aminophen** [comment]
@FrankMittelbach Thanks, will wait for it.

**Comment by blefloch** [comment]
One option was missed by others, since \@begindocumenthook is simply a
token list (in expl3 parlance), we can do

    \ExplSyntaxOn
    \tl_greplace_once:Nnn \@begindocumenthook
      { \tate } { something~else }
    \ExplSyntaxOff

The reason \patchcmd fails is that it is meant for very general macros
with possibly complicated arg spec and replacement text.

**Comment by u-fischer** [comment]
@blefloch  imho the purpose is not to *replace* something - the example replaces `\tate` with `\tate`. They are after the side effect which tells them is `\tate` was in the hook or not.  So it is more a case of `\tl_if_in`.

**Comment by blefloch** [comment]
Sorry, I hadn't looked at the code nearly carefully enough.  Anyways, we
have the suitable tool, even if it looks a bit ugly to do

    \tl_if_in:NnT \@begindocumenthook { \tate }
      { \@ltj@@geometry@tatetrue }

**Comment by FrankMittelbach** [comment]
I'm still a bit confused about the actual use case. Am I reading this right, that the actual question to be answered is whether or not another package has been loaded or configured in some special way (which puts something into the hook and though you can detect that at the point `\@begindocumenthook` is about to be executed) or what is it?

Because if `\@begindocumenthook` is inspected earlier then it depends on whether the other package is loaded before or after. And if it is executed when `\@begindocumenthook` is run then you probably don't even need to look into `\@begindocumenthook` to figure out what is going on. However, `\tl_if_in:NnT` would certainly work for this use case (if that is what is intended).

**Comment by aminophen** [comment]
In practice, \AtBeginDocument{\tate} is done by a document class instead of some packages, since that code affects the overall layout. \usepackage{lltjp-geometry} is always done after \documentclass, so it's necessary and safe enough to examine the content of `\@begindocumenthook`.

On luatexja 20200227.0 release, lltjp-geometry.sty is changed to use `\tl_if_in:NnT`; the specific problem is now gone.
