### ISSUE TITLE
choice keys that expand the value

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex3#685]
It would be useful if there where a `.choice_x` handler that expands the value so that choices can be given with commands. This here works but gives the wrong key in the error if the choice is unknown:

~~~~
\documentclass{article}
\begin{document}
\ExplSyntaxOn
\keys_define:nn {my}{
 key   .code:n = \exp_args:Nnx \keys_set:nn{my}{__key=#1},
 __key .choice: ,
 __key / choicea .code:n = A
}
\newcommand\testA {choicea}
\keys_set:nn {my} { key = choicea}
\keys_set:nn {my} { key = \testA}
\keys_set:nn {my} { key = blub}
\ExplSyntaxOff

\end{document}
~~~~

**Comment by blefloch** [comment]
Are choices always strings?
If so, should we simply always expand them?
It seems strange that the package author would have to decide whether to
allow key=\testA or not by writing ".choice:" or ".choice_x:" in their code.

**Comment by josephwright** [comment]
On reflection, I agree with @blefloch  here: I think I want to hear a strong argument for supporting what seems like an interface issue.

**Comment by u-fischer** [comment]
Well my choice key values are simple strings and it would be fine with me if they are expanded always. But as they are handled currently as strings they can theoretically contains everything, including commands, so if we start to expand them fully it could break  code:

~~~~
\documentclass{article}
\begin{document}
\ExplSyntaxOn
\keys_define:nn {my}{
   keyA   .code:n = \exp_args:Nnx \keys_set:nn{my}{__key=#1},
   keyB   .code:n = \keys_set:nn{my}{__key=#1},
 __key .choice: ,
 __key / choicea .code:n = A,
 __key / \testA  .code:n=B, 
}
\newcommand\testA {choicea}
\keys_set:nn {my} { keyA = choicea}
\keys_set:nn {my} { keyA = \testA}
\quad 
\keys_set:nn {my} { keyB = choicea}
\keys_set:nn {my} { keyB = \testA}
\ExplSyntaxOff

\end{document}
~~~~

![image](https://github.com/latex3/latex3/assets/4047173/c44fd899-32d4-47c7-9a06-d7e66592eeac)

**Comment by josephwright** [comment]
I've thought about this and I'm going to say 'no'. Choices are simply key names at 'one remove', and we don't expand those.
