### ISSUE TITLE
Error detection with \cs_new:Nn

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#69]
It seems that there is some frequent confusion about expansion, with people expecting

    \cs_new:Nn \bar:foo { ... }

to expand its arguments. Perhaps we should check that functions defined using `\cs_new...:Nn` (and I'd say `\cs_(g)set...:Nn` too) only have `N` and `n` in their arg spec? This comes with a performance cost at definition time, but those functions are already slow anyways.

**Comment by josephwright** [comment]
I'm with @FrankMittelbach  here: we need some rules for the programming approach and enabling 'sloppy' work here is not a good plan.

**Comment by blefloch** [comment]
Sorry, I don't understand what you mean @josephwright .  I think @FrankMittelbach was ranting not-quite-seriously against the existence of `\cs_new:Nn`.  I wasn't planning on enabling sloppy work, just checking for errors.

Perhaps we should seriously reconsider providing a "check-for-many-programming-errors" mode, and otherwise skip as many checks as possible?

**Comment by josephwright** [comment]
@blefloch  OK, I'll leave open then :-) (Like @FrankMittelbach  I stick to `Npn` so its academic for me.)

**Comment by josephwright** [comment]
`l3chk`

**Comment by blefloch** [comment]
It's not a very expensive check and it's for `\cs_new:Nn` that is already quite a bit slower than `\cs_new:Npn` so I've added the check in all cases.  I've had to allow `T` and `F` as that's used in the wild.
