### ISSUE TITLE
feature suggestion: enums / small integers

### ISSUE THREAD

**Issue by callegar** [latex3/latex3#692]
Hi,

I wonder if it could make sense to slightly enhance the integer type interface to make it more flexible for the implementation of something resembling an enum data type.

Enums are often used to implement multi-value switches, associate symbolic names to the values the switch can take, and let a flow of execution be based on the switch value, using the symbolic names for the tests for maximum readability.

In plain tex, this concept is substantially covered by the `\ifcase` primitive. However, the latter is not very expressive because symbolic names cannot be employed.

In LaTeX3, one can use integer constants to provide the symbolic names and then `\int_case:nn' for the control flow, which is nice. For instance:

```latex
% Define switch variable
\int_new:N \g_mypkg_fmt_int
% Define the values that the switch can take
\int_const:Nn \c_mypkg_fmt_blue_int {0}
\int_const:Nn \c_mypkg_fmt_red_int {1}
\int_const:Nn \c_mypkg_fmt_green_int {2}
%
% ...
%
% Have somewhere the assignment
\int_set_eq:NN  \g_mypkg_fmt_int \c_mypkg_fmt_blue_int
%
% ...
%
% Use it to control flow
\int_case:nn { \g_mypkg_fmt_int }
  {
    { \c_mypkg_fmt_blue_int } {  Do this for the blue case }
    { \c_mypkg_fmt_green_int } { Do this for the green case }
    { \c_mypkg_fmt_red_int } { Do this for the red case }
  }
```
(hope this is sufficiently syntactically correct, but it should convey the idea)

The snippet above seems to me much more readable than a plain TeX switch. However, I see a limitation in that an `\int_new:N` always consumes a full counter register, that in older engines are limited (256? probably 32k ?). In principle one should never run into the limit, because it is large enough. Yet, because small positive integers are generally enough for enums, a `\chardef` might be more than enough for storing a multi-valued switch value. Thus, I wonder if it could make sense to introduce some assignment command restricted to *small integers* to more efficiently support the *enum-like* usage case.

As of today, one can probably use `\__int_constdef:Nw`, but this is obviously meant as an internal command and with the implication of defining constants. I wonder if an `\int_set_small_eq:NN`  could fit.

The introduction of a shorthand for declaring many constants at once could also be useful. E.g., something like `\int_declare_enum:nn {<prefix>}{values}`, defining `\<prefix>_<value_i>_int` for each value.  With these two additions, the code above could become:

```latex
% Define the values that the switch can take
\int_declare_enum:nn {c_mypgk_fmt} {blue, red, green}
%
% ...
%
% Have somewhere the assignment
\int_gset_small_eq:NN  \g_mypkg_fmt_int \c_mypkg_fmt_blue_int
%
% ...
%
% Use it to control flow
\int_case:nn { \g_mypkg_fmt_int }
  {
    { \c_mypkg_fmt_blue_int } {  Do this for the blue case }
    { \c_mypkg_fmt_green_int } { Do this for the green case }
    { \c_mypkg_fmt_red_int } { Do this for the red case }
  }
```

The biggest advantage, would be to have a LaTeX3 interface explicitly suggesting a preferred way to deal with multivalued switches or enums. As of today, I think that there are packages using many different approaches (chardefs, token lists, counters) for storing multivalued switches which conversely are a rather standard construct in most programming languages and this may be confusing. Furthermore, many packages do now support keyval configuration interfaces, and in many cases the <value> is a keyword to be picked in a finite set, i.e. a concept that could map perfectly into a multivalued switch once the option has been parsed.

Does this make any sense to you?

**Comment by josephwright** [comment]
`\int_const:Nn` already uses `\chardef` or `\mathchardef` where this is applicable: that's hidden in the code but it is there. So you are already likely not using a `\count` register for anything you decide to make a symbolic variable. At the same time, if you are really worried you could simply use a `tl`, of which there are a lot more.

In general, we've cut down on constant integers 'for the sake of them' (like `\c_two`) as they didn't really make the code more readable. There's no issue having meaningful constants, but I'm not sure about having an dedicated creator: I think on balance having the code lines saying what value applie is a good thing.

**Comment by u-fischer** [comment]
@josephwright  I do find the description a bit unclear but it sounds like what the bitset package provides. If this is meant then I think we should think about a similar expl3 data structure.

**Comment by josephwright** [comment]
@u-fischer `bitset` is for packing a series of settings into one integer, I'm not sure that's what's being asked for here. My understanding was that the outcome would still be 'normal' integers, not bit-based settings.

**Comment by car222222** [comment]
bitset is for many things, not necessarily much to do with integers.  But bit vectors are not much related to this use of a set of small integers as internal labels for cases, so that \ifcase can be easily used to select the code to run.

**Comment by josephwright** [comment]
@u-fischer We clearly do need bitwise functions: probably one for an `l3experimental` (or `l3trial`) module. Perhaps open another issue and list out the interfaces required for `hyperref`?

**Comment by callegar** [comment]
@josephwright Looking at the code, indeed I noticed that latex3 was not using counters when possible for the constants. My initial message in some sense originated from from that. I wondered whether it could make sense to have a short integer data type *never* using counters.

In my sample implementation of a multivalued switch above, you actually use constants for the symbolic names, but you need a full counter for the switch variable itself. E.g., you have the `\int_new:N \g_mypkg_fmt_int`. Obviously, you can use a `\tl_new:N` for that variable but it feels somehow wrong to then do a `\tl_set_eq:NN` between variables where one has a `tl` signature and the other one has an `int` signature, particularly when one considers that in latex3 there is all this naming convention to help catching mistakes early since TeX can obviously provide no type checking.

My question came out of the fact that for certain things you may easily need tens and tens of different enum like variables, to customize the many aspects of a template where various elements each have a finite set of variants, so I was wondering if it was sensible to take up all these many counters.

Well, I guess a reasonable approach may be to define the symbolic contants with `\tl_new:N` dropping the `int` from the name as in the kernel for `\c_zero`, etc., use a token list variable for the switch variable itself, and use `\int_case:nn` for the comparison, not worrying too much about mixing types.

For what concerns the symbolic names for the constants, having an helper may be useful when you have a large number of them to define, but indeed that may be specific enough to be dealt with at the package level.

**Comment by FrankMittelbach** [comment]
We did have fake integers at ome point in expl3 when registers were still rare, but these days having an additional type for the sake of saving registers seems pointless which is why that got dropped at some point.

**Comment by callegar** [comment]
OK, that's good to know. Relaxing the need to be careful with counter registers sounds good. I had this remembrance that e-tex and all the modern engines have at least 32k counters but that those above the first 256 had some slightly different behavior, so it was still sensible to be careful on registers, is there any truth in it?

**Comment by josephwright** [comment]
@callegar  There is a difference in performance for first 256 registers unless one is using LuaTeX, but it's very likely that those will already have been consumed by the kernel. The performance difference is so small it's not worth considering today.

**Comment by blefloch** [comment]
I think it could be worthwhile to have an enum type, not to save \count registers but because it avoids setting the counter to a value that is beyond the maximum for the enum, for instance.
```
\enum_new_type:nn { biosafety }
  { {P1} {P2} {P3} {P4} }

\enum_new:Nn \l_jeanmerieux_biosafety_enum { biosafety }
\enum_new:Nn \l_NEIDL_biosafety_enum { biosafety }

\enum_set:Nn \l_jeanmerieux_biosafety_enum { P4 }
\enum_set:Nn \l_NEIDL_biosafety_enum { P3 }
% ... then in 2017 ...
\enum_set:Nn \l_NEIDL_biosafety_enum { P4 }

\enum_case:Nnn \l_NEIDL_biosafety_enum { biosafety }
  {
    {P1} {...}
    {P2} {...}
    {P3} {...}
    {P4} {...}
  }
```
To be honest I'm not yet 100% sold on the idea, but I could be easily convinced by better examples.  One major difference compared to various other programming languages is that we don't have a compilation step that could optimize the above `\enum_case:Nnn` into an `\ifcase` statement.  Maybe it's worth looking at arguments for adding an `enum` type to Python https://www.python.org/dev/peps/pep-0435/

**Comment by callegar** [comment]
@bleflock that certainly makes things quite readable and the intentions of the programmer immediately evident.

**Comment by blefloch** [comment]
Another motivation is that enums cannot be compared to integers (this can be achieved for us by storing enums in a way different from integers, e.g., simply as strings?)

**Comment by josephwright** [comment]
I've looked back at this, and I think 'not convinced' is the best description. Without a strong use case, I don't think the balance is right here.

**Comment by car222222** [comment]
This is another issue where the discussion ranges over a range useful related ideas.  Therefore the discussion should not simply get buried by closing it, rather it should be preserved somehow.

**Comment by josephwright** [comment]
@car222222 The issue being closed doesn't remove it from the database. I'd say that _issues_ are closed either if they are fixed or if the conclusion is that they won't be worked on 'ever'. We could convert to a discussion (currently not used in this repo so would be an experiment), but somehow one still needs to know which threads are 'active'.

**Comment by car222222** [comment]
The problem is not with closing it, per se.  But in not having anyway of distinguishing between those issues that are probably of little future interest, for example because an uncontroversial bug was fixed, and those issues which hide useful ideas and discussions.  How do we know where the good stuff is?

**Comment by u-fischer** [comment]
@car222222  you could go through the issues and add a label "good stuff" or "with useful ideas".

**Comment by car222222** [comment]
Such a label might indeed be useful.

**Comment by josephwright** [comment]
I think either that or move to Discussion rather than an Issue: the aim remains to have open Issues as 'things with an action potentially attached'.
