### ISSUE TITLE
l3doc.cls: wrong spacing if link is made to macro name

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/latex3#693]
In `l__codedoc_macro_typeset_on:nN` there is a space added after the macro name through `\ `.
This is normally set in typewriter (as this is a macro) but if there is a link made the the `\MacroFont` gets hidden inside the link box and as a result the space is typeset in the document font resulting in a noticable offset.  Adding `\MacroFont`in front fixes it but that isn't quite right, I guess, instead the  font change should happen outside the link (or the space here should be a fixed one, eg `\enspace`.

```
\documentclass{l3doc}

\ExplSyntaxOn
\cs_set_protected:Npn \__codedoc_macro_typeset_one:nN #1#2
  {
    \vbox_set:Nn \l__codedoc_macro_box
      {
        \vbox_unpack_drop:N \l__codedoc_macro_box
        \hbox { \llap { \__codedoc_print_macroname:nN {#1} #2
 %           \MacroFont       % <----- without it the \ is in lmr10 if a link is made
            \      
        } }
      }
    \int_incr:N \l__codedoc_macro_int
  }
\ExplSyntaxOff



\begin{filecontents*}[overwrite]{\jobname-1}

% \begin{function}
%   {\hook_gput_code:nnn,\hook_gput_code:non,\hook_gput_code:nnv,\hook_gput_code:nov}
%   \begin{syntax}
%     \cs{hook_gput_code:nnn} \Arg{hook} \Arg{label} \Arg{code}
%   \end{syntax}
%    Add a chunk of \meta{code} to the \meta{hook} labeled
%    \meta{label}. If the label aready exists the \meta{code} is
%    appended to already existing code.
% \end{function}
%
%  \begin{macro}{\hook_gput_code:nnn,\hook_gput_code:non,
%                \hook_gput_code:nnv,\hook_gput_code:nov}
%    
%    \begin{macrocode}
Test
%    \end{macrocode}
%  \end{macro}
\end{filecontents*}

\begin{document}

\DocInput{\jobname-1}

\end{document}
```

**Comment by blefloch** [comment]
This is actually a valid fix (and has been in `l3doc` for a while, thanks).  Things can always be improved later on by replacing this fixed-size space `\MacroFont\ ` by a customizable space (still must be of fixed sized for all macros).
