### ISSUE TITLE
l3kernel: Incomplete deprecation error message

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#694]
Using `\str_if_eq_x:nnTF` causes incomplete deprecation error message. I am using texlive 2019 with updated packages, latex2e 20200202 patch level 5. Not tested under texlive 2020 pretest yet.

```tex
\documentclass{article}

\begin{document}
\ExplSyntaxOn
% complete error message
\msg_log:n {text}

% incomplete error message
\str_if_eq_x:nnTF{a}{a}{true}{false}
\ExplSyntaxOff
\end{document}
```

`\msg_log:n {text}` causes
```tex
! LaTeX3 Error: '\msg_log:n' deprecated on 2020-01-01. Use '\iow_log:n '. For
(LaTeX3)        6 months after that date one can restore a deprecated
(LaTeX3)        command by loading the expl3 package with the option
(LaTeX3)        'undo-recent-deprecations'.
```

while `\str_if_eq_x:nnTF{a}{a}{true}{false}` causes
```tex
! Undefined control sequence.
<argument> \LaTeX3 error: 
                           '\str_if_eq_x:nnTF' deprecated on 2020-01-01. Use...
l.10 \str_if_eq_x:nnTF
                       {a}{a}{true}{false}
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.
```

**Comment by FrankMittelbach** [comment]
The difference between the two deprecated commands is that \str_if_eq_x:nnTF is expandable, so it can be used inside some \edef expansion. To be able to produce an error in that case we have to resort to something drastic to make it  show up without causing unrelated errors and so the trick is instead of a normal screen message we call some undefined command  `\LaTeX3 error:`.
This way you see the string following 
```
<argument> \LaTeX3 error: 
                           '\str_if_eq_x:nnTF' deprecated on 2020-01-01. Use...
```
in the input to help you what is wrong, but the unfortunate side effect is the engine error message about undefined csnames. But this is the best we could come up with ...

**Comment by blefloch** [comment]
We talked about reordering the error message to move the date later and
the replacement command earlier in the message so that the date ends up
being cropped instead of the replacement command.


In LuaTeX we can make very nice expandable errors, I had some code for that.

**Comment by FrankMittelbach** [comment]
Am 04.04.20 um 11:19 schrieb Bruno Le Floch:
> We talked about reordering the error message to move the date later and
> the replacement command earlier in the message so that the date ends up
> being cropped instead of the replacement command.

I thought that had actually happened by now but I haven't checked.

But despite that, the fact that you get a strange error message 
mentioning \hbox is a bit unfortunate. Perhaps we can at least improve 
the documentation in interface3.pdf to have a section  on error messages 
that explicitly explains the this kind of expandable error. After all it 
also shows up if, say, \tl_use:c{l_my_undefined_tl} appears in an 
\typeout situation, etc.

So I would classify this as a documentation improvement not a bug.

> In LuaTeX we can make very nice expandable errors, I had some code for that.

might be good to use when possible but that doesn't help with the other 
engines.

**Comment by muzimuzhi** [comment]
> The difference between the two deprecated commands is that \str_if_eq_x:nnTF is expandable, so it can be used inside some \edef expansion. To be able to produce an error in that case we have to resort to something drastic to make it show up without causing unrelated errors and so the trick is instead of a normal screen message we call some undefined command `\LaTeX3 error:`.

Ah, this explains the `! Undefined control sequence.` error type. But since `\str_if_eq_x:nnTF` is deprecated and is not doing its thing (unless with `expl3` option `undo-recent-deprecations`), do we still need it to be expandable?

Another thing, maybe a list of deprecated function and variable names as well as their corresponding successors will help a lot. Currently this corresponding info can only be seen from error message and `source3.pdf`. The `l3obsolete.txt` do contains a full list of deprecated (and removed) names, but not their successors, if any.

**Comment by josephwright** [comment]
Deprecations all get listed in the ChangeLog

**Comment by blefloch** [comment]
I've fixed the main issue, but I'm wondering if we should simply use a
non-expandable error message as suggested.

**Comment by FrankMittelbach** [comment]
The mechnism is used in other places, such as \tl_use:c and unless I'm mistaken a non-expandable error message in that case would just blow up

**Comment by blefloch** [comment]
Ok.  That leaves the question of making better error messages in LuaTeX.
Roughly speaking the way (if l3kernel-extras is to be believed) is

    \cs_gset:Npn \__msg_expandable_error:n #1
      {
        \tex_directlua:D
          {
            tex.error
              ( "
                \tex_luaescapestring:D
                  { LaTeX3~error:~ \tl_to_str:n {#1} }
              " )
          }
      }

**Comment by zauguin** [comment]
@blefloch I think I would go a step further and provide "full" errors in LuaTeX even for the expandable case (I mean including the additional text and maybe allowing the control sequences documented for regular messages.)
That would need a slightly bigger change though, especially to get compatible wrapping behavior. We could either reimplement the wrapping in Lua or use runtoks to call the regular error functions in an expandable way. (The last option would be nicer but probably requires LuaTeX >= 1.12 to work reliably)
