### ISSUE TITLE
xparse: triggers start of cell in \halign

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/latex3#695]
In contrast to `\newcommand` a simple `\NewDocumentCommand` triggers the start of a cell even if it has trivial content. This means that it can't hold `\multicolumn` etc.

```
\documentclass{article}

\usepackage{xparse}

\newcommand\foo{\multicolumn{1}{l}{foo}}

\begin{document}

\hrule
\begin{tabular}{c}
 x \\ y \\ \foo
\end{tabular}
\hrule
 
 \RenewDocumentCommand\foo{}{\multicolumn{1}{l}{foo}}

\hrule
\begin{tabular}{c}
 x \\ y \\ \foo
\end{tabular}
\hrule
\end{document}
```

While I understand  the usefulness of standard protection and agree with the approach I think we should improve the documentation and explicitly mention the restrictions inside tabular structures and the need to use the Expandable versions in this case. Refering to "if you don't understand you have no need for it" doesn't seem to be enough imo.

**Comment by josephwright** [comment]
Perhaps one to address when we do the `xparse` 're-arrangement'?

**Comment by josephwright** [comment]
Addressed in https://github.com/latex3/latex2e/commit/8815c6077f300b6661e274f34189a630b7caa5ac.
