### ISSUE TITLE
l3keys: multiple equal signs should be split at first

### ISSUE THREAD

**Issue by Skillmon** [latex3/latex3#698]
Currently the `l3keys` module (well, actually the `keyval` module) enforces a strict syntax on equal signs in key=val pairs. Namely there has to be only a single (ungrouped) equal sign, else `\keyval_parse:NNn` will throw `\keyval_misplaced_equal_error:`.

I'd like to remove this requirement and just split at the first occurring equal sign (of category 12 or 13) and assume any other equal signs are part of the value. Imho, this wouldn't make the syntax less clear (and if one feels it does, putting braces around the value would still work).

There are no big advantages here either, my main points for this decision would be:

1. there is, imho, no strong reason for this restriction

2. it would be easier for me to port performance gains of `expkv`'s `\ekvparse` over to L3's version of the code, as that's the syntax decision I made for that package.

The only "regression" which could be caused by this would be that documents which wouldn't have worked because of this error would work from now on.

**Comment by zauguin** [comment]
An advantage I see with restricting equal signs here is that this ensures that a missing `,` is caught much earlier, making it harder to miss some bugs.
Also to me `a=b=c` looks more like a shortcut for `a=c,b=c` than assigning the value `b=c` to `a`.

**Comment by FrankMittelbach** [comment]
one regression would be that incorrect input, i.e., one where a comma is missing (which is not an unlikely scenario) will get silently accepted, raising errors later or none at all but producing incorrect output.

**Comment by Skillmon** [comment]
I haven't thought of missing commas (who would...). That's a valid point.

I currently got things sorted to be regression free and still achieving an estimated 25%-35% speed up for `\keyval_parse:NNn`. Another 10%-20% could be cut off (totalling at 40% time savings) if multiple equal signs were allowed.

Expect a PR later today or maybe tomorrow for the 25%-35% speed up :)

**Comment by FrankMittelbach** [comment]
I'm all for improvement gains in this area with more and more key/val usage but I'm against dropping that requirement for the outlined reason.

**Comment by Skillmon** [comment]
Understood and accepted. Meanwhile: https://github.com/latex3/latex3/pull/701
