### ISSUE TITLE
Ampersand in tabular close variable group scope

### ISSUE THREAD

**Issue by marlox-ouda** [latex3/latex3#705]
### System

* TeX Live 2019
* XeTeX, Version 3.14159265-2.6-0.999991 
* expl3 2019-07-01

### Expected behavior

I wish to loop over a `seq` in `tabular` environment. To do that, I tried different `\seq_map_…` function.

I expect to:
* Have usable **local** variable inside the whole loop function (the core issue of this ticket)
* Avoid `\relax` or equivalent appended at the end of the call of `\seq_map_…` (may be at every loop)

### Resulting behavior

* **local** variable assignment is cancelled after the first ampersand whatever the used `\seq_map_…` (I repeat call to local variable to underline that the ampersand is responsible of the cancelling)
* Using `\seq_map_function:NN` avoid the appending of a new empty cell at the end. The two others (`\seq_map_variable:NNn` and `\seq_map_inline:Nn`) not. <= may be treated in other ticket if necessary

Note: I do not care of the space issue at this moment.

### Example code

```latex
\documentclass{article}
\usepackage{expl3}
\begin{document}
\ExplSyntaxOn
\seq_new:N \g_mytabular_seq
\tl_new:N \g_var_tl

\seq_gput_right:Nn \g_mytabular_seq {row~one}
\seq_gput_right:Nn \g_mytabular_seq {row~two}
%\tl_set:Nn \l_tmpa_tl {FAIL}

\section{Variable}

\begin{tabular}{|c|c|}
  \seq_map_variable:NNn \g_mytabular_seq \l_tmpa_tl {
    \tl_use:N \l_tmpa_tl ~and~\tl_use:N \l_tmpa_tl &
    \tl_use:N \l_tmpa_tl ~and~\tl_use:N \l_tmpa_tl \\
  }
\end{tabular}

\section{Inline~with~local~variable}

\begin{tabular}{|c|c|}
  \seq_map_inline:Nn \g_mytabular_seq {
    \tl_set:Nn \l_tmpa_tl {#1}
    \tl_use:N \l_tmpa_tl ~and~\tl_use:N \l_tmpa_tl &
    \tl_use:N \l_tmpa_tl ~and~\tl_use:N \l_tmpa_tl \\
  }
\end{tabular}

\section{Inline~with~global~variable}

\begin{tabular}{|c|c|}
  \seq_map_inline:Nn \g_mytabular_seq {
    \tl_gset:Nn \g_var_tl {#1}
    \tl_use:N \g_var_tl ~and~\tl_use:N \g_var_tl &
    \tl_use:N \g_var_tl ~and~\tl_use:N \g_var_tl \\
  }
\end{tabular}

\section{Function~with~local~variable}

\cs_new:Npn \row_draw_local:n #1 {
    \tl_set:Nn \l_tmpa_tl {#1}
    \tl_use:N \l_tmpa_tl ~and~\tl_use:N \l_tmpa_tl &
    \tl_use:N \l_tmpa_tl ~and~\tl_use:N \l_tmpa_tl \\
}

\begin{tabular}{|c|c|}
  \seq_map_function:NN \g_mytabular_seq \row_draw_local:n
\end{tabular}

\section{Function~with~global~variable}

\cs_new:Npn \row_draw_global:n #1 {
    \tl_gset:Nn \g_var_tl {#1}
    \tl_use:N \g_var_tl ~and~\tl_use:N \g_var_tl &
    \tl_use:N \g_var_tl ~and~\tl_use:N \g_var_tl \\
}

\begin{tabular}{|c|c|}
  \seq_map_function:NN \g_mytabular_seq \row_draw_global:n
\end{tabular}

\section{Function~with~parameter}

\cs_new:Npn \row_draw_parameter:n #1 {
    #1 ~and~#1 &
    #1 ~and~#1 \\
}

\begin{tabular}{|c|c|}
  \seq_map_function:NN \g_mytabular_seq \row_draw_parameter:n
\end{tabular}

\section{Emulation~of~last~cell~bug}
\begin{tabular}{|c|c|}
  row~one~and~row~one & row~one~and~row~one \\
  row~two~and~row~two & row~two~and~row~two \\
  \relax
\end{tabular}

\section{Wanted~result}
\begin{tabular}{|c|c|}
  row~one~and~row~one & row~one~and~row~one \\
  row~two~and~row~two & row~two~and~row~two \\
\end{tabular}

\section{Version}
Done~with~version~\c_sys_engine_version_str
\end{document}
```

**Comment by marlox-ouda** [comment]
In fact, it seems to be more complex that expected.

With the following code:
```latex
\documentclass{article}
\usepackage{expl3}
\begin{document}
\ExplSyntaxOn
\seq_new:N \g_mytabular_seq
\tl_new:N \g_var_tl

\seq_gput_right:Nn \g_mytabular_seq {row~one}
\seq_gput_right:Nn \g_mytabular_seq {row~two}
\seq_gput_right:Nn \g_mytabular_seq {row~three}

\tl_set:Nn \l_tmpa_tl {FAIL < G}
\group_begin:
  \tl_set:Nn \l_tmpa_tl {G < FAIL < T}
  \begin{tabular}{|c|c|c|}
    \tl_set:Nn \l_tmpa_tl {T < FAIL}
    \seq_map_variable:NNn \g_mytabular_seq \l_tmpa_tl {
      \tl_use:N \l_tmpa_tl ~and~\tl_use:N \l_tmpa_tl &
      \tl_use:N \l_tmpa_tl ~and~\tl_use:N \l_tmpa_tl &
      \tl_use:N \l_tmpa_tl ~and~\tl_use:N \l_tmpa_tl \\
    }
  \end{tabular}
\group_end:

\end{document}
```
I get on each row : `expected value | G < FAIL < T | G < FAIL < T`. So ampersand does not close every score. It seem to close tabular inner scope.

Furthurmore, if I exchange `\begin{tabular}` and `\group_begin:` (same at the end), I got an error : 
```
! Extra }, or forgotten \endgroup.
<template> \unskip \hfil }
                          \hskip \tabcolsep \hskip -.5\arrayrulewidth \vrule...
l.21     }
```

**Comment by u-fischer** [comment]
tabular cells build groups.  Better avoid code that tries to loop over cells.

**Comment by FrankMittelbach** [comment]
Am 14.04.20 um 22:08 schrieb marlox-ouda:
> In fact, it seems to be more complex that expected.

welcome to the world of TeX's \halign primitive :-)   --- it is complex 
but not impossible to master once you twist your brain a couple of turns

If you are letting TeX typeset a "tabular" and you do that by passing on 
some material and some "&" back to the typesetting part of TeX, there is 
a lot happening in parallel.

In a nutshell every cell in such a tabular is a local group (of some 
sort) so anything locally defined/changed within the scope of that cell 
is reset after the &.

The grouping used in not quite { ... }  nor is it \begingroup ... 
\endgroup so there is no way to fake yourself out of it.


So what happens if you start to loop over a sequence inside the first 
cell is that the & you generate closes a group and any further text 
material opens a new "cell group". Thus local variables altered in side 
your loop just go bong.

outside of tabular an a similar case would be a loop function that 
contains "\group_end: ... \group_begin:" as part of its code.

One approach is not to do typesetting, ie, use the loop to build up the 
material you want to pass to tabular inside a tl including all the & and 
once done go \tl_use:N

**Comment by marlox-ouda** [comment]
Thank you for explanation. Its clear
I understand my mistake. After the `\begin{tabular}`, the environment is not a *table* one, it is already the first *cell* one. And I am trapped inside :/ . 

I manage to solve the issue with concatenation before the table, with taking care of expansion
```latex
    \seq_map_variable:NNn \g_my_tabular_seq \l_tmpa_prop {
      \tl_put_right:Nx \l_tmpa_tl {\prop_item:Nn \l_tmpa_prop {property1}}
      \tl_put_right:Nn \l_tmpa_tl {&}
      \tl_put_right:Nx \l_tmpa_tl {\prop_item:Nn \l_tmpa_prop {property2}}
      \tl_put_right:Nn \l_tmpa_tl {&}
      \tl_put_right:Nx \l_tmpa_tl {\prop_item:Nn \l_tmpa_prop {property3}}
      \tl_put_right:Nn \l_tmpa_tl {\\ \hline}
    }
```
and then use `\tl_use:N \l_tmpa_tl` in *tabular* environment.
