### ISSUE TITLE
l3text: issues with babel shorthands

### ISSUE THREAD

**Issue by moewew** [latex3/latex3#715]
The following MWE

```latex
\documentclass[ngerman]{article}
\usepackage{babel}
\usepackage{expl3}

\ExplSyntaxOn
\newcommand*{\test}{\text_titlecase:n}
\ExplSyntaxOff

\begin{document}
"`Lo"=rem"' -- \test{"`Lo"=rem"'}
\end{document}
```
fails with
```
! Argument of \language@active@arg" has an extra }.
<inserted text> 
                \par 
l.10 "`Lo"=rem"' -- \test{"`Lo"=rem"'}
                                      
? 
Runaway argument?
! Paragraph ended before \language@active@arg" was complete.
<to be read again> 
                   \par 
l.10 "`Lo"=rem"' -- \test{"`Lo"=rem"'}
                                      
? 
! Argument of \language@active@arg" has an extra }.
<inserted text> 
                \par 
l.10 "`Lo"=rem"' -- \test{"`Lo"=rem"'}
                                      
? 
Runaway argument?
! Paragraph ended before \language@active@arg" was complete.
<to be read again> 
                   \par 
l.10 "`Lo"=rem"' -- \test{"`Lo"=rem"'}
                                      
? 
! Argument of \language@active@arg" has an extra }.
<inserted text> 
                \par 
l.10 "`Lo"=rem"' -- \test{"`Lo"=rem"'}
                                      
? 
Runaway argument?
! Paragraph ended before \language@active@arg" was complete.
<to be read again> 
                   \par 
l.10 "`Lo"=rem"' -- \test{"`Lo"=rem"'}
                                      
? 
```
on pdfLaTeX, LuaLaTeX and XeLaTeX
```
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-04-06>
```

Maybe babel shorthands/active characters are a bit too much to ask for here, but I'd like to at least try.

---

*edit* Added `"=`.

**Comment by u-fischer** [comment]
@josephwright titlecasing after the quote doesn't work:

~~~
\documentclass[ngerman]{article}
\usepackage{babel}
\usepackage{expl3}

\ExplSyntaxOn
\newcommand*{\test}{\text_titlecase:n}
\ExplSyntaxOff

\begin{document}
\test{"`lorem"'} \test{lorem} \test{!lorem}
\end{document}
~~~

![image](https://user-images.githubusercontent.com/4047173/81056623-1e88ab80-8ecb-11ea-9e66-916da4f270ff.png)

**Comment by josephwright** [comment]
@u-fischer That one is very tricky (and probably deserves it's own issue). I'm still trying to work out how we handle 'tell what the first letter is'. At the moment, I've gone for 'first token' or 'first catcode-11 token' unless we hit various special cases. We probably need to think about more rules ...

**Comment by josephwright** [comment]
Actually, it's ore about how you tell if an active char is part of a multi-byte sequence: I'll see what I can do

**Comment by u-fischer** [comment]
@josephwright I would understand the problem if `"a` where used  but why doesn't the l count as the first-catcode-11-token after "`  ?  There are not catcode 11 token here.

**Comment by josephwright** [comment]
It would with LuaTeX/XeTeX, but at present for 8-bit engines we've got to allow for UTF-8 active chars.  At the moment, the detection doesn't bother to check if the active char is part of a UTF-8 sequence: I'll need to address that.

**Comment by u-fischer** [comment]
Ah I see. Would it make sense (and be possible) to add combinations like "` or "=  to some exclude list?

**Comment by josephwright** [comment]
@u-fischer Getting all of this right is pretty hard, as we have a lot of reasons something _might_ be excluded. At present, I'd like to make the code more sophisticated in terms of checking for UTF-8 sequences: once we do that, things might be a bit clearer.

**Comment by u-fischer** [comment]
@josephwright I know it's hard - I had an interesting read today about uppercasing and lowercasing ;-)

**Comment by josephwright** [comment]
@u-fischer  Where was that?

**Comment by u-fischer** [comment]
TUGBoat ;-)
