### ISSUE TITLE
l3text: first "letter" in titlecase

### ISSUE THREAD

**Issue by moewew** [latex3/latex3#716]
Just so it doesn't get lost, here is Ulrike's example from #715 again (extended with some other cases)
```latex
\documentclass[ngerman]{article}
\usepackage{babel}
\usepackage{expl3}

\ExplSyntaxOn
\newcommand*{\test}{\text_titlecase:n}
\ExplSyntaxOff

\begin{document}
\test{"`lorem"'} \test{\glqq lorem\grqq} \test{lorem} \test{!lorem} \test{3 lorem}
\end{document}
```

More generally, it may be nice to have more control over what `l3text` skips when looking for the character to capitalise in `text_titlecase`. (We've had a similar discussion in https://github.com/plk/biblatex/issues/960#issuecomment-599020843 and it brought us `\l_text_titlecase_check_letter_bool`, but something more sophisticated might be nice so that I can decide to ignore only punctuation but not digits...)

**Comment by josephwright** [comment]
I think at least in part this links to loading all of the Unicode character class data: now doable but I need to get round to it. Once I can offer that, we can see where this goes.

**Comment by josephwright** [comment]
https://github.com/latex3/latex3/pull/1280 perhaps? I could look at having the nature of the match as a selectable function (e.g. have a comma list of all Unicode classes that count).

**Comment by josephwright** [comment]
@moewew Could you have another look here? Now we are using Unicode char classes, we get the 'right' outcome for all of the examples
```latex
\test{"`lorem"'} \test{\glqq lorem\grqq} \test{lorem} \test{!lorem} \test{3lorem}
```
(`\test{3 lorem}` in the question has a word boundary, so is expected not to titlecase the second word.)

**Comment by moewew** [comment]
The output seems reasonable. It might be subtly different from what `biblatex` previously had, but so far I don't think anyone complained.
