### ISSUE TITLE
libpoppler.so.99 cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Rubix982** [latex3/latex3#724]
Hello!

I recently downloaded and setup `texlive-most` for `Arch Linux`. 
I wanted to compile a latex file to generate a pdf  file using `pdflatex`. so I ran the command
```
pdflatex example.tex
```

I was instead thrown the error,
```
pdflatex: error while loading shared libraries: libpoppler.so.99: cannot open shared object file: No such file or directory
```

I then ran the `latex` command, and I was thrown the same error again,
```
latex: error while loading shared libraries: libpoppler.so.99: cannot open shared object file: No such file or directory
```

I cannot even run `pdflatex --version`.

Any clue what could be the issue?

The following files exist in `/usr/lib/`
```
ibpoppler-cpp.so@         libpoppler-qt5.so.1.22.0*
libpoppler-cpp.so.0@       libpoppler.so@           
libpoppler-cpp.so.0.7.0*   libpoppler.so.95@        
libpoppler-qt5.so@         libpoppler.so.95.0.0*    
libpoppler-qt5.so.1@         
```
In `/usr/lib64/` I have,
```
libpoppler-cpp.so@         libpoppler-qt5.so.1.22.0*
libpoppler-cpp.so.0@       libpoppler.so@           
libpoppler-cpp.so.0.7.0*   libpoppler.so.95@        
libpoppler-qt5.so@         libpoppler.so.95.0.0*    
libpoppler-qt5.so.1@       
```

I don't have `libpoppler.so.99` anywhere in these two, 

Any help would be appreciated. Thank you.

**Comment by Skillmon** [comment]
Looks like an error caused by the package maintainers of Arch Linux. I'm running Arch as well but installed the vanilla TeX Live instead of the packaged version in the Arch repos and don't face any such issues.

**Comment by josephwright** [comment]
Sorry, but this is 'not us': it's not an issue with the macro layer at all.

**Comment by Rubix982** [comment]
@Skillmon, alright, will do.

@josephwright, it's alright, no problem. My apologies for the wrong question. Have a nice day. 👍
