### ISSUE TITLE
Optimize \seq_item:Nn when its #2 is zero

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#726]
When the `#2` of `\seq_item:Nn` is evaluated to zero:
 - The code `\seq_item:Nn \x_seq {0}` leaves nothing in the input stream.
 - But in the current implementation, `#2` is only tested with `< 0`. Another testing against `= 0` added inside `\__seq_item:nN` may optimize the time complexity when `#2` of `\seq_item:Nn` is evaluated to zero.

https://github.com/latex3/latex3/blob/e2652070cfff89601695a719b445a7d2ca00ab3e/l3kernel/l3seq.dtx#L1826-L1859

This may apply to similar functions in other latex3 packages.

**Comment by PhelypeOleinik** [comment]
Adding a test to `\__seq_item:nN` wouldn't work because this macro has to expand to a number, which `\__seq_item:nwn` then takes as argument, so it can't take an “action” from there (not without dirty brace hacks, at least :-).

Something else would have to be changed to test that `#2` is zero, at the cost of slowing down _all_ other cases, so at first it doesn't seem like too much profit. (how common is to use `0` there, after all?)

One option would be to first normalise `#2` (`\seq_count:N` is only used when it is negative, so the overhead for zero is negligible), then check the normalised argument and `\prg_break:` in case of zero:

```latex
\RequirePackage{l3benchmark}
\ExplSyntaxOn

\def\x{}
\seq_set_from_clist:Nn \l_tmpa_seq { \x,\x,\x,\x,\x,\x }

\iow_term:n { Current~definition: }
\int_step_inline:nnn { -6 } { 6 }
  { \benchmark:n { \seq_item:Nn \l_tmpa_seq {#1} } }


\cs_gset:Npn \__seq_item:wNn \s__seq #1 \s__seq_stop #2#3
  {
    \exp_args:Nf \__seq_item_check:nwn
      { \exp_args:Nf \__seq_item:nN { \int_eval:n {#3} } #2 }
    #1
    \prg_break: \__seq_item:n { }
    \prg_break_point:
  }
\cs_new:Npn \__seq_item_check:nwn #1
  {
    \int_compare:nNnTF {#1} = 0
      { \prg_break: }
      { \__seq_item:nwn {#1} }
  }

\iow_term:n { Proposed~change: }
\int_step_inline:nnn { -6 } { 6 }
  { \benchmark:n { \seq_item:Nn \l_tmpa_seq {#1} } }

\stop
```

Though with the code above I get:
```none
Current definition:
4.84e-6 seconds (21.1 ops)
6.08e-6 seconds (26.5 ops)
7.23e-6 seconds (31.4 ops)
8.37e-6 seconds (37 ops)
9.53e-6 seconds (41.3 ops)
1.08e-5 seconds (47.4 ops)
1.02e-5 seconds (41.4 ops) % zero
3.07e-6 seconds (13.5 ops)
4.32e-6 seconds (18.9 ops)
5.45e-6 seconds (23.7 ops)
6.81e-6 seconds (29.6 ops)
7.79e-6 seconds (34.5 ops)
8.92e-6 seconds (39 ops)
Proposed change:
5.69e-6 seconds (25.1 ops)
6.58e-6 seconds (29.1 ops)
7.81e-6 seconds (34.3 ops)
8.93e-6 seconds (39.1 ops)
1.01e-5 seconds (44.2 ops)
1.13e-5 seconds (49.1 ops)
2.77e-6 seconds (12 ops) % zero
3.59e-6 seconds (15.8 ops)
4.85e-6 seconds (20.7 ops)
5.98e-6 seconds (26.2 ops)
7.16e-6 seconds (31.1 ops)
8.35e-6 seconds (36.2 ops)
9.51e-6 seconds (41.6 ops)
```

which makes a (very small) increase in the processing time of `\seq_item:Nn` (more noticeable when `#2` is small, of course).  Of course, the case of `#2==0` gets drastically reduced (about 70% in my test list with 6 elements, and even more in longer lists).

Now looking at it, it may perhaps be a good tradeoff, though I'm still skeptical about how common zero is...

**Comment by PhelypeOleinik** [comment]
A better implementation: it uses `\ifcase` on the argument if it is zero, positive, or negative, then proceeds accordingly. For positive arguments this is slightly faster than my implementation above, but still a bit slower than the current kernel version. For negative arguments, it is as fast as the kernel version, plus it is quite fast for zero.

```latex
\RequirePackage{l3benchmark}
\ExplSyntaxOn

\def\x{}
\seq_set_from_clist:Nn \l_tmpa_seq { \x,\x,\x,\x,\x,\x }

\iow_term:n { Current~definition: }
\int_step_inline:nnn { -6 } { 6 }
  { \benchmark:n { \seq_item:Nn \l_tmpa_seq {#1} } }

% =======================================================

\cs_gset:Npn \__seq_item:wNn \s__seq #1 \s__seq_stop #2#3
  {
    \exp_args:Nf \__seq_item_check:nwn
      { \exp_args:Nf \__seq_item:nN { \int_eval:n {#3} } #2 }
    #1
    \prg_break: \__seq_item:n { }
    \prg_break_point:
  }
\cs_new:Npn \__seq_item_check:nwn #1
  {
    \int_compare:nNnTF {#1} = 0
      { \prg_break: }
      { \__seq_item:nwn {#1} }
  }

\iow_term:n { Version~1: }
\int_step_inline:nnn { -6 } { 6 }
  { \benchmark:n { \seq_item:Nn \l_tmpa_seq {#1} } }

% =======================================================

\cs_gset:Npn \__seq_item:wNn \s__seq #1 \s__seq_stop #2#3
  {
    \exp_args:Nf \__seq_item_case:nNw { \int_eval:n {#3} } #2
    #1
    \prg_break: \__seq_item:n { }
    \prg_break_point:
  }
\cs_new:Npn \__seq_item_case:nNw #1#2
  {
    \if_case:w \int_sign:n {#1} \exp_stop_f:
           \exp_after:wN \prg_break:
    \or:   \exp_after:wN \use_i:nn
    \else: \exp_after:wN \use_ii:nn
    \fi:
      { \__seq_item:nwn {#1} }
      {
        \exp_args:Nf \__seq_item:nwn
          { \int_eval:n { \seq_count:N #2 + 1 + #1 } }
      }
  }

\iow_term:n { Version~2: }
\int_step_inline:nnn { -6 } { 6 }
  { \benchmark:n { \seq_item:Nn \l_tmpa_seq {#1} } }

\stop
```

```none
Current definition:
5.1e-06 seconds (21.1 ops)
6.4e-06 seconds (26.8 ops)
7.7e-06 seconds (32.1 ops)
8.9e-06 seconds (36.8 ops)
1e-05 seconds (41.8 ops)
1.1e-05 seconds (47.2 ops)
1.1e-05 seconds (44.0 ops) % zero
3.3e-06 seconds (13.4 ops)
4.6e-06 seconds (18.8 ops)
5.8e-06 seconds (23.8 ops)
7.1e-06 seconds (29.1 ops)
8.2e-06 seconds (34.0 ops)
9.5e-06 seconds (39.1 ops)
Version 1:
5.7e-06 seconds (23.6 ops)
7e-06 seconds (28.4 ops)
8.2e-06 seconds (33.9 ops)
9.5e-06 seconds (38.5 ops)
1.1e-05 seconds (44.3 ops)
1.2e-05 seconds (48.5 ops)
2.9e-06 seconds (12.1 ops) % zero
3.8e-06 seconds (15.7 ops)
5.1e-06 seconds (21.1 ops)
6.4e-06 seconds (26.1 ops)
7.7e-06 seconds (31.2 ops)
8.8e-06 seconds (36.0 ops)
1e-05 seconds (41.3 ops)
Version 2:
5.5e-06 seconds (22.1 ops)
6.8e-06 seconds (28.0 ops)
8.1e-06 seconds (32.9 ops)
9.3e-06 seconds (37.9 ops)
1.1e-05 seconds (42.8 ops)
1.2e-05 seconds (47.7 ops)
2.2e-06 seconds (9.2 ops) % zero
3.2e-06 seconds (13.1 ops)
4.5e-06 seconds (18.5 ops)
5.8e-06 seconds (23.5 ops)
7e-06 seconds (28.5 ops)
8.3e-06 seconds (33.3 ops)
9.6e-06 seconds (38.9 ops)
```

**Comment by muzimuzhi** [comment]
> Something else would have to be changed to test that `#2` is zero, at the cost of slowing down _all_ other cases, so at first it doesn't seem like too much profit. (how common is to use `0` there, after all?)

Ah, I opened this issue without careful consideration.

**Comment by PhelypeOleinik** [comment]
Well, squeezing the code a tad further (replacing `\int_sign:n` by a slightly faster code and doing some expansion shortcuts) I got a version that performs the same as the current kernel implementation for positive input, and is even faster for negative input:
```latex
\RequirePackage{l3benchmark}
\ExplSyntaxOn

\def\x{}
\seq_set_from_clist:Nn \l_tmpa_seq { \x,\x,\x,\x,\x,\x }

\iow_term:n { Current~definition: }
\int_step_inline:nnn { -6 } { 6 }
  { \benchmark:n { \seq_item:Nn \l_tmpa_seq {#1} } }

% =======================================================

\cs_gset:Npn \__seq_item:wNn \s__seq #1 \s__seq_stop #2#3
  {
    \exp_args:Nf \__seq_item_case:nNw { \int_eval:n {#3} } #2
    #1
    \prg_break: \__seq_item:n { }
    \prg_break_point:
  }
\cs_new:Npn \__seq_item_case:nNw #1#2
  {
    \if_case:w
        \if_meaning:w 0 #1
          0
        \else:
          \if_charcode:w - \tl_head:w #1 \q_stop - \fi: 1
        \fi:
      \exp_stop_f:
         \exp_after:wN \prg_break:
    \or: \exp_after:wN \use_ii:nnn
    \fi:
    \use_ii:nn
      { \__seq_item:nwn {#1} }
      {
        \exp_args:Nf \__seq_item:nwn
          { \int_eval:n { \seq_count:N #2 + 1 + #1 } }
      }
  }

\iow_term:n { Version~3: }
\int_step_inline:nnn { -6 } { 6 }
  { \benchmark:n { \seq_item:Nn \l_tmpa_seq {#1} } }

\stop
```

I get (in average):
```none
Current definition:
5.5e-06 seconds (21.4 ops)
6.9e-06 seconds (27.0 ops)
8.3e-06 seconds (32.7 ops)
9.5e-06 seconds (37.4 ops)
1.1e-05 seconds (42.2 ops)
1.2e-05 seconds (47.3 ops)
1.2e-05 seconds (45.4 ops)
3.5e-06 seconds (13.5 ops)
4.9e-06 seconds (19.3 ops)
6.2e-06 seconds (24.2 ops)
7.6e-06 seconds (29.3 ops)
8.9e-06 seconds (34.6 ops)
1e-05 seconds (40.0 ops)
Version 3:
5.5e-06 seconds (21.2 ops)
7e-06 seconds (26.9 ops)
8.3e-06 seconds (31.9 ops)
9.6e-06 seconds (37.1 ops)
1.1e-05 seconds (42.0 ops)
1.2e-05 seconds (48.0 ops)
2e-06 seconds (7.8 ops)
3.1e-06 seconds (12.0 ops)
4.6e-06 seconds (17.8 ops)
5.9e-06 seconds (22.5 ops)
7.2e-06 seconds (27.7 ops)
8.5e-06 seconds (32.8 ops)
1e-05 seconds (38.0 ops)
```

I guess we could make the change... Thoughts?

**Comment by wspr** [comment]
No objections to performance improvements :)

I do wonder how we maintain optimised code like this over time. Do we need a collection of test files that contain a naive implementation and the hard-coded implementation and actually test (in the CI sense) that the optimised code is actually faster?

Just thinking out loud, not saying anything needs to be done about this now.

**Comment by blefloch** [comment]
On 5/22/20 1:58 AM, Will Robertson wrote:
> No objections to performance improvements :)

Depends.  You have to strike a balance between speed and readability of
the code (and length; we don't want expl3 to be too bloated).  I haven't
looked at the code here, but I suppose it's ok.

> I do wonder how we maintain optimised code like this over time. Do we
> need a collection of test files that contain a naive implementation and
> the hard-coded implementation and actually test (in the CI sense) that
> the optimised code is actually faster?

In principle a good idea!  I worry that this could lead to "Heisenbugs"
where the tests fail simply because the Travis instance is busy at the
wrong time during the test.  This can be mitigated by running the
benchmarks a few times and doing some more serious stats, but that's not
ideal because it would slow down every test run.

**Comment by PhelypeOleinik** [comment]
@wspr I'm not sure it can be reasonably tested (unless we want tests to fail randomly, which doesn't sound fun :-). For instance, the benchmarks I show above are not 100% true: they are an average of 10 separate runs.

If you take the second line of each test above you see `6.9e-06 s` _vs._ `7e-06 s`, which are pretty much the same. But if I look at one of the runs that I used in the average (which is what you'd see in a benchmark test) I see `6.85e-6 s` and `7.07e-6 s`, which shows that my version is a bit _slower_ in some of the runs, so the test would fail.  Of course, this one the performance improvement is really for when the input is zero, the rest is collateral damage.

There's also this: https://chat.stackexchange.com/transcript/41?m=53612989#53612989 :-)

**Comment by wspr** [comment]
@blefloch @PhelypeOleinik Good points! Of course you'd need a tolerance to trip an error but I think you're both right we don't want this part of the usual Travis setup...

**Comment by FrankMittelbach** [comment]
Am 22.05.20 um 02:43 schrieb Bruno Le Floch:
> On 5/22/20 1:58 AM, Will Robertson wrote:
>  > No objections to performance improvements :)
> 
> Depends. You have to strike a balance between speed and readability of
> the code (and length; we don't want expl3 to be too bloated). I haven't
> looked at the code here, but I suppose it's ok.

Striking that balance is very important I think.

On the whole we should only optimize code (at the cost of essentially 
unreadable code) if that part of the code is regularly used *very often* 
in *many* documents.

Maybe we have to set us some guidelines what "very often" should mean 
but if you need, say, several 1000 calls of the code to see a minimal 
difference and if in nearly all documents you have only 0-10 of such 
calls typically, then I think it is wrong to  optimize (unless the 
optimized code is as easy to understand as the non-optimized. But if it 
requires tricks that we frown upon when used by others we should not 
optimize.)

**Comment by blefloch** [comment]
The proposed optimizations (those that remain at the same level of using `n`-type functions and not low-level `\if_...` tests etc) speed up the zero case but slow down all other cases, and the overall time of things like getting `\tl_item:Nn \l_tmpa_tl {#1}` for all `#1` between 0 and the length of the list is not improved.  We can get a much larger improvement by replacing constructions such as `\exp_args:Nf \func:n { \int_eval:n { #1 - 1 } }` by some lower-level code.  Another improvement is to go through items more than one at a time.  As such, I am closing this issue.
