### ISSUE TITLE
xparse: provide \ShowDocumentCommandCode etc

### ISSUE THREAD

**Issue by stone-zeng** [latex3/latex3#728]
Currently, one can use `\cs_show:c { foo ~ code }` to check a xparse-defined command. Could you please consider to provide some helper functions such as `\ShowDocumentCommandCode`, `\ShowDocumentEnvironmentCode` etc for checking their content?

By the way, is it possible to use `latexdef` to see the definition of a xparse-defined command?

**Comment by Skillmon** [comment]
> By the way, is it possible to use latexdef to see the definition of a xparse-defined command?

You can use

```sh
latexdef 'foo code'
```

**Comment by blefloch** [comment]
Closing because the duplicate later issue #795 has slightly more details and pointers to the LaTeX2e repository.
