### ISSUE TITLE
l3doc doesn't make "TF" grey when documenting internal conditionals

### ISSUE THREAD

**Issue by joulev** [latex3/latex3#730]
MWE

```tex
% \iffalse
%<*driver>
\documentclass{l3doc}
\begin{document}
\DocInput{\jobname.dtx}
\end{document}
%</driver>
% \fi
% \begin{implementation}
%    \begin{macrocode}
%<@@=testpkg>
%<*package>
%    \end{macrocode}
% \begin{macro}[TF]{\@@_true:}
% This function is interesting.
%    \begin{macrocode}
\prg_new_conditional:Nnn \@@_true: { T, F, TF }
  { \prg_return_true: }
%    \end{macrocode}
% \end{macro}
%    \begin{macrocode}
%</package>
%    \end{macrocode}
% \end{implementation}
```

![image](https://user-images.githubusercontent.com/44609036/82862927-0eed0780-9f4b-11ea-84e1-5841e7c3a81b.png)

"TF" should be gray, shouldn't it?

**Comment by PhelypeOleinik** [comment]
The `TF` is typeset by `\@@_typeset_TF:`, which adds an explicit `\color{black}`.  Indeed it would probably look better if it was grey too.

**Comment by muzimuzhi** [comment]
FYI, the `\color{black}` and `\color{red}` in `\@@_typeset_TF:` were both added in a87b8872 (add documentation for "restricted expandable" functions, 2011-09-04).

https://github.com/latex3/latex3/blob/46c6191f5f899f46087e6738348f233793c69ca3/l3kernel/l3doc.dtx#L2124-L2138
