### ISSUE TITLE
\str_convert_pdfname:n fails when the argument contains a space. 

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex3#737]
~~~~
\documentclass{article}
\begin{document}
\ExplSyntaxOn
\str_convert_pdfname:n{abc~cde}
\ExplSyntaxOff
\end{document}
~~~~

gives 

! Missing number, treated as zero.
<to be read again> 
                   !
Not quite when it got lost, it worked previously.

**Comment by blefloch** [comment]
On 6/2/20 6:40 PM, Ulrike Fischer wrote:
> |\documentclass{article} \begin{document} \ExplSyntaxOn
> \str_convert_pdfname:n{abc~cde} \ExplSyntaxOff \end{document} |
> 
> gives
> 
> ! Missing number, treated as zero.
> 
> !
> Not quite when it got lost, it worked previously.

Oops!  It's my fault for pushing \str_map_function:nN without pushing for
changing \__str_convert_pdfname:N to be n-type and detect spaces somewhere in
the processing.  Sorry.

**Comment by PhelypeOleinik** [comment]
I think I have a patch to allow spaces. It's currently printing `abc#20cde` with your example. Is that correct or should it be `abc cde`?

**Comment by u-fischer** [comment]
`abc#20cde` is correct. That is the escaping needed for a pdfname.
