### ISSUE TITLE
Add support for multiple color models

### ISSUE THREAD

**Issue by josephwright** [latex3/latex3#739]
In `xcolor`, it is possible to set up named colors with data for multiple models. We should have the same idea: automated mapping between color models is not always optimal. The most obvious way is to use the `xcolor` syntax
```latex
\color_set:nnn { some-name } { cmyk / rgb } { 0.1 , 0.2 , 0.3 , 0.4 / 0.5 , 0.6 , 0.7 }
```

The plan at present is to store this data up-front, so unlike `xcolor` it will not be necessary to reload colors to apply these settings.

**Comment by car222222** [comment]
This is one of the new issues that I fully understand and support. 

It reminds me also that any automatic mappings that are built-in should be documented, maybe only via a reference to external documentation.

**Comment by josephwright** [comment]
@car222222 At present, the `cmyk` <-> `rgb` mapping is set up as for `xcolor`, which is derived from the Adobe docs. There are some variable parts I did not expose: we may want to look at a low-level interface for that at some stage. I'm quite happy to add a ref. to `xcolor`: it's got very rich docs and I'd rather not reproduce all of them.

**Comment by car222222** [comment]
Yes, it is a very good idea to refer to xcolor for documentation.  I find most of it is very clearly expressed and sufficiently detailed.

**Comment by car222222** [comment]
I have written a few paragraphs to (try to) explain some of this, and related issues.  

I could either add them here, or open a new issue for them, eg: Documentation ideas

**Comment by josephwright** [comment]
@car222222 I think that's a separate issue: please open one

**Comment by u-fischer** [comment]
Yes, I think that is a good plan. Probably the storing should be ordered, or at least the first model be marked as "main" so that if a "color using command"  is able to use more than one model knows which is meant to be the "default".

**Comment by josephwright** [comment]
@u-fischer Code nearly finished here :) My current plan is to store the 'main' color in the existing `tl`, add a `prop` for 'all colors', and thus have fast access for the common case.

**Comment by josephwright** [comment]
I'm going to rebase here onto https://github.com/latex3/latex3/pull/747: to get things right, I really need to allow for moving "parse" out of the way first, then deal with the complexity as an 'internal issue'.
