### ISSUE TITLE
Allow mixing of spot/separation colors

### ISSUE THREAD

**Issue by josephwright** [latex3/latex3#741]
Mixing spot colors is not currently supported. This depends on having more complex color space family support as mentioned in https://github.com/latex3/latex3/issues/740. The open question is exactly how complex this should be: two separations can be mixed in a single color space, but mixing separations and process colors is more complex. A special case is 'mixing' with white, which is a change of tint and must be supported.

**Comment by car222222** [comment]
I am not sure if this is the best place for this question, but it does concern one of the simplest case of mixing: tint transforms of Separation colors.

Does/will l3color provide any support for specifying a general function to use in the (mandatory) tintTramsform parameter?  Note that colorspace always uses the canonical (linear/ratio) function.

**Comment by car222222** [comment]
I see that the same terminology is used for more general mixing in the PDF reference, here again, the tintTransform parameter can be any type of function, not just the canonical linear mixing function:  

“DeviceN was designed to represent color spaces containing multiple components that correspond to colorants of some target device. As with Separation color spaces, PDF consumer applications must be able to approximate the colorants if they are not available on the current output device, such as a display. To accomplish this, the color space  definition [must provide] a tint transformation function that can be used to convert all the components to an alternate color space.“

**Comment by car222222** [comment]
Beyond ‘simple DeviceN’, in which all the component colors must fall-back to the same base color space, there is the subtype NChannel, where this restriction is lifted — but this requires the addition to the PDF of an attributes dictionary containing further information including, optionally, MixingHints.

**Comment by u-fischer** [comment]
I assume that the issue is about mixing when using a color. 

The syntax `\color{foo!30} ` should work (and should be workable) for all color types and give a spot color when used for text if foo is a spot color. 

`\color{foo!30!bar}`  should imho  fall back to cmyk or rgb. There are some examples in the colorspace docu where such a mix can give a spot color, but I don't find this very convincing. It works only under restrictions and with tricks. I don't think that we should spent time to figure out what people could mean with such a mix in terms of spot colors. If someone wants a "professional" color mix, they shouldn't use this "lazy" syntax but setup the mix in a "professional" way. In colorspace syntax:

```
\definecolorspace{mixspace}{mixed}{spot1,spot2}
\definecolor{mixedcolor}{mixspace}{.5,.4}
\color[mixspace]{.5,.4} or \color{mixedcolor}

```

**Comment by josephwright** [comment]
@u-fischer  More or less my take, expect what about a case where they do `spot1!35!spot2` with a pre-defined `mixspace`? That might reasonably be expected to work.

**Comment by josephwright** [comment]
@car222222 Over time we are almost certain to add these functions: I am trying to build up as I get a handle on the requirements!

**Comment by u-fischer** [comment]
>  expect what about a case where they do `spot1!35!spot2` with a pre-defined `mixspace`? That might reasonably be expected to work.

There are cases where is can work and where there is a consens what is should sensibly do. But it will always be "spot1!35!spot2" will work **if the following conditions are met...**. Which means that we would have to collect the conditions, document them, and check in the code. E.g. in your example if `spot1!35!spot2`  is expected to work, then `spot2!35!spot1`  probably too. So you would have to sort the involved models to be able to detect permutations. That looks like a lot trouble for a bit of syntactic sugar that in a professional environment is not really needed.

**Comment by jbezos** [comment]
> `\color{foo!30!bar}` should imho fall back to cmyk or rgb.

I don't like the idea at all. This is clearly against the expectations in the pre-press world, where spot + black must be exactly that, a mixture of 2 inks. Either support it correctly, or don't support it.

**Comment by josephwright** [comment]
@jbezos Spot + black (or cyan/magenta/yellow) explicitly is one thing, but what about spot + named mixture of cmyk? Or spot1 + spot2 where there is no pre-defined mixed color space? At present, I'm a decent distance form implementing any of this, and it's going to take work: I'm happy to discuss and sketch out ideas. (@u-fischer's point I think is that for professional printing one should explicitly define a mixed color space rather than have the code 'create' one on-the-fly.)

**Comment by u-fischer** [comment]
> > `\color{foo!30!bar}` should imho fall back to cmyk or rgb.
> 
> I don't like the idea at all. This is clearly against the expectations in the pre-press world, where spot + black must be exactly that, a mixture of 2 inks. Either support it correctly, or don't support it.

I wasn't quite precise. My main use case is hyperref support. That mean I want `linkcolor=foo!30!bar` to do something more or less sensible and inks are not involved here. I simply need a rgb or cmyk number. So falling back is the right thing.

Regarding `\color{spot1!30!bar}`  in text: I don't think that we can make it work correctly (in the sense that it always gives the right ink mix) without a lot trouble, so imho the choices are 

1. fall back silently to cmyk or rgb (not so good in text but the wanted behaviour for hyperref)
2. fall back with a warning to cmyk or rgb 
3. error

3. Is probably the best default for text commands, but 2. should be possible. So I think we will need some control here ...

**Comment by josephwright** [comment]
For `hyperref` or similar, I think we'll be covered by #742 in any case: if I get 'full mixing' right for print, it will still need conversion to `rgb` for `hyperref`.

**Comment by jbezos** [comment]
Of course, for screen any color (spot or process, ‘pure’ or mixed) must fallback to rgb (even cmyk will be eventually converted to rgb).

[As an aside, I compared the results of `colorspace` and InDesign to make sure (wherever possible) they matched, because any preflight program understands InDesign, you know.]

**Comment by josephwright** [comment]
@jbezos Now all I need is a preflight tool ;) Seriously, I'll aim to be as close as possible to `colorspace`.

**Comment by car222222** [comment]
Agreed that for screen colors in hyperref etc., all that is needed is ‘named colors’ using RGB.  

The Separation color spaces, process colors and CMYK are used only for printing (largely with some type of inks).

But I read this today, suggesting that modern digital printing technologies can all use RGB variants:

The old “RGB versus CMYK” color wars don’t matter much anymore. RGB content can now be seamlessly processed by most modern print workflows and gets converted on the fly to CMYK for any offset printing applications. Digital output devices like professional digital printers may even give you _better_ color if you don’t convert to CMYK. 

Source:
https://www.printingforless.com/blog/printing/guide-to-using-color-and-ink-in-commercial-printing/

**Comment by car222222** [comment]
‘full mixing’ ??  . . . out with the paint pots!

**Comment by car222222** [comment]
@josephwright  wrote: but mixing separations and process colors is more complex

In what ways?  At what level?  (I do not think that you mean the level of ‘choosing the inks’?

It seems to me that ‘process colors’ do not case any problems when the mixing is specified using a DeviceN space.  So maybe it is these that are ’more complex’?

**Comment by josephwright** [comment]
@car222222 I mean 'I'm going to have more fun implementing', really. I'm currently re-reading the Adobe docs to make a second pass at re-working Separation, DeviceN, etc., support

**Comment by car222222** [comment]
@josephwright Sounds good, not to mention fun!  
Are you going to include the ChannelN subtype?  This is for mixing (mostly) Separation colors that have distinct fall-back basic spaces.

**Comment by car222222** [comment]
As @jbezos wrote about mixing screen (RGB) colors:

> doing it at the TeX level is fine for elements not to be printed

So for these you need only ‘named colors’ and the rule that any mixture of colors from distinct spaces will most likely be in RGB (unless something more complex is explicitly asked for or very clearly intended).

**Comment by josephwright** [comment]
I've covered this I think in that one can create a DeviceN space containing the Separation colours.

**Comment by car222222** [comment]
Good.
