### ISSUE TITLE
Provide a mechanism to format colors for different uses

### ISSUE THREAD

**Issue by josephwright** [latex3/latex3#742]
Internally, `l3color` stores colors in a device-independent format close to the way `dvips` writes color. The backend then re-formats in specials. However, there are places that need other formats. We likely need some form of
```latex
\color_format:nn { expr } { format }
\color_format:nnn { model } { values } { format }
```

This links to the question of expandability: the above assume an expandable approach, which would require us to re-work `\color_parse:nN`. This is doable but we need more idea of the use cases here.

There are some knock-ons for color models that don't have parameter-based setups.

**Comment by u-fischer** [comment]
If one assume that the color model is setup up, imho every actual *use* of a color  consist of writing out rather simple strings build from model + values. 

For pdf we will need the output formats (example names ...)
`pdfstroke`, `pdffill`, `pdfstrokefill`  which give for general model/value something like 
` \pdfnameofmodel{model} CS values SCN`  and for rgb/cmyk/gray the shorter variants. 

For colors e.g. in annotation dictionaries we will need formats to output rgb/cmyk as array with numbers separated by spaces. 

fontspec and html export will probably want the values as hex numbers. 

I'm not sure about svg, we should ask the dvisvgm maintainer.

Making `\color_format:nnn { model } { values } { format }` expandable should be imho not a problem. If it is difficult with  `expr` I don't really see a problem to provide `\color_format:nnN { expr } { format } \tl_var` instead. Most color settings where this matters are imho done in keyval anyway.

**Comment by josephwright** [comment]
I wonder if rather than a generic conversion function, we want instead some specific functions for different results. The general ideas of `stroke`, `fill`, `fillstroke` are already covered by the backend, as the results are backend-dependent. Moreover, those don't need to have the possibility of switching to rgb/cmyk: we know that separations, etc., will already have that at the backend level. So there's no need to 'export in a public way' for them. (There, `dvisvgm` works like `dvips`.)

I guess annotations are different as they don't 'live' in the `color` module. They also (I think) have to be rgb/cmyk, and also are I suspect backend-independent. The latter point is important: if things are not backend-indpendent, they need to be abstracted so we get a clean split.

Thinking a bit more, perhaps we only need to accept explicit model data plus pre-parsed expression data. That would give us `\color_format:nnn` and `\color_format:Nn`, and could be expandable (I can rework `\color_parse:nN` to an expandable version, but I'm wary as color operations are intrinsically non-expandable.)

I'll make some suggestions and we can see if they go anywhere.

**Comment by u-fischer** [comment]
> I guess annotations are different as they don't 'live' in the color module. 

I don't think so. I mean I know that the color package is quite focussed on "how to get the color into the pdf/postscript". Currently the core color representation is identical to the pdf format, a color and its pdf format is viewed as one unit.  But that is what makes it so difficult for other uses to access the color and which leads to packages like hycolor.  We should separate this. "red" is not `1 0 0 R 1 0 0 r`. "red" is `{rgb}{1,0,0}` and writing with `\pdfliteral`  `1 0 0 R 1 0 0 r` to the page stream is *one* way to format and use the color, but writing  `[1 0 0]` to a dictionary is another one and not less valid or less "colorlike" than the first.   

That doesn't mean that l3color should contains commands to add color to annotations or that `\color_set` commands should be expanded to cover this. But when thinking about which output formats are needed we should not differentiate if the format is needed by "our" commands (like \color_set) or by some other use but think about which formats are needed and how to provide them.

**Comment by josephwright** [comment]
@u-fischer 
> > I guess annotations are different as they don't 'live' in the color module.
> 
> I don't think so. I mean I know that the color package is quite focussed on "how to get the color into the pdf/postscript". Currently the core color representation is identical to the pdf format, a color and its pdf format is viewed as one unit.

For `l3color`, the internal format is currently similar to `dvips`, not to PDF, as the model is most useful if it comes first. I suspect I should change the internal format to `{<model>}{<values>}` as that has some advantages when getting the model 'back out' (no need for `:w` functions). The `values` always end up `:w` in some way, it's just a question of whether to use spaces or commas, really.

> But that is what makes it so difficult for other uses to access the color and which leads to packages like hycolor. We should separate this. "red" is not `1 0 0 R 1 0 0 r`. "red" is `{rgb}{1,0,0}` and writing with `\pdfliteral` `1 0 0 R 1 0 0 r` to the page stream is _one_ way to format and use the color, but writing `[1 0 0]` to a dictionary is another one and not less valid or less "colorlike" than the first.

No question there, which is why I chose from the start to use an internal format that didn't depend on the backend.

> That doesn't mean that l3color should contains commands to add color to annotations or that `\color_set` commands should be expanded to cover this. But when thinking about which output formats are needed we should not differentiate if the format is needed by "our" commands (like \color_set) or by some other use but think about which formats are needed and how to provide them.

True but perhaps misses my point. For setting color, there is a backend element as PDF and `dvips` need different formats, so somewhere there is a device-neutral hand-off to a `\__color_backend_...` function. For other uses, I'm not clear if there is a backend dependence, partly I guess as I'm still not sure what is workable/desirable in PostScipt or SVG (or ...). That's something we likely have to clarify: for example, do you know how to write annotations in PostScript and the equivalent in SVG, and to specify the color? Possibly they also need the same format as PDF, but possibly not.

**Comment by u-fischer** [comment]
> True but perhaps misses my point. For setting color, there is a backend element as PDF and `dvips` need different formats,

Oh you mean what `\color_format:nnn{rgb}{1,0,0}{pdffillstroke}`  should output with dvips or xetex?

I think it should output what you get now with `\show\current@color`.  so `rgb 1 0 0` . But I agree that this is a difficult question, as the model is not included here.

**Comment by josephwright** [comment]
@u-fischer A few things. First, for 'basic' colors like fills/strokes, I'd hope `l3color` and `l3draw` already cover stuff. It's also worth noting that the _color itself_ is the same for `dvips` and PDF: `1 0 0` (OK, complexity is where the model sits).

What's more interesting that input colors as rgb/cmyk is input as separations, etc., where we _do_ need the `l3color` internals to decide what to do. (For basic conversion of 'appearance', all that's really needed is a documented format for `l3color` itself.)

I'll probably re-work the `l3color` internal format first, then make proposals in this area.

**Comment by car222222** [comment]
@josephwright Since you are reworking this ‘internal format’, maybe it would be a good time to specify what information it needs to contain (be a format for).  

This is answering the question: what is ‘a color’ in l3color? 

Maybe this is the same  (albeit at a more abstract level) as what you 
wrote parenthetically here:
    For basic conversion of 'appearance', all that's really needed is a 
    documented format for l3color itself.

Note for the documentation: need to be clear what words like ‘format’ and ‘appearance’ exactly mean.

Technically, I think that your use of ‘format’ here is what I would call ‘syntax’ or ‘representation’.   In the context of LaTeX document processing, ‘format’ suggests two totally different things to me: either something related to ‘formatting something in the document’ or to ‘the pdfLaTeX format’.

**Comment by car222222** [comment]
@josephwright wrote:   the color itself is the same for dvips and PDF: 1 0 0 
No!  :-)  the ‘colour itself’ is definitely not 1 0 0 !!  

1 0 0 is only the internal representation that you choose to use for ‘the color’.

To dvips, this syntax, 1 0 0, may have a unique interpretation as ‘the color red’ because their is a hidden convention that ‘a triple of numbers’ is interpreted as using RGB.  But I am not aware of any such convention in PDF.

As you suggest here:

>  (OK, complexity is where the model sits).

[Please can I use this totally amazing sentence as my email tag line?]

but it is not just ‘complexity’ that sits there.  Rather, everything needed to interpret 1 0 0 also lies there.  So the model must be specified (possibly by a default value) along with any representation of ‘the color itself’.  

It is not clear to me that every ‘color itself ‘ in every model/colorspace can be usefully represented by a single RGB triple.  Maybe that is what you are addressing by your reworking. We live in hope:-)!

**Comment by car222222** [comment]
Aside re language: The title of this issue implies strongly that ‘format colors for different uses’ refers to ‘the use of colors in the formatting of different typesetting cases’.

**Comment by josephwright** [comment]
@car222222 I meant that once you specify a color is rgb, then `1 0 0` is how it's represented in PDF, so it _is_ the color. Sometimes one needs to explicitly include the model, other times one doesn't. In any case, internally we need to track both model and values, and it's just a question of whether to do that as I've got set up now or to modify subtly. There are advantages in TeX terms in going for two balanced texts, as it allows `\exp_after:wN \use_i:nn \l_some_tl` to quickly extract the model without `:w` arguments.

**Comment by u-fischer** [comment]
two balanced arguments sounds right. 

> it's just a question of whether to use spaces or commas, really.

I have been wondering about that too. Most output formats use spaces, so when a color is used directly there would be a speed gain if spaces where used. On the other side fp-tupels expect commas, so  when calculations are involved commas are probably the better choice yes?

**Comment by josephwright** [comment]
@u-fischer `fp` tuples always end up with parenthesis around them, so that doesn't help. The performance difference is likely tiny, so I'm minded to switch to a comma-list as it's more 'normal' and better when showing the stored data.

I'll do this change first then start on the output formats.

**Comment by josephwright** [comment]
@u-fischer  Looking over the code, I think you are right: I'll stick to spaces, and make sure the values are always passed 'cleaned up'. (That also applies in `l3draw`, where I can gain a bit of performance by the look of things: I'll do that too.)

**Comment by u-fischer** [comment]
Nice to hear that I'm right when I actually wrote that I haven't made my mind up :-). But it is your call, you know the internal code better.

**Comment by u-fischer** [comment]
I think annotation and html export have been mixed up, at least I get FF0000 with annotation. 

I would also need "annotation-cmyk" export (I have a feature request to support cmyk in link colors: https://github.com/latex3/hyperref/issues/133). (Perhaps names like "space-rgb", "space-cmyk" would be more generic here).

**Comment by josephwright** [comment]
@u-fischer  Reversal fixed

On naming, I take it you are happy with the idea that the export format can implicitly force a model (like `HTML` => `rgb`).  I'm happy with say `pdf-rgb` or `space-rgb` or `rgb-space-sep` or ...

**Comment by car222222** [comment]
@josephwright 
Please can you give a more precise soec for the syntax of these?  And some idea of the their semantics, and of ‘export formats’ and ‘forcing’?

Also, note that HTML ==> RGB (and vice versa) is only a distinction in the number of values allowed and how they are written.   Both are just distinct ways of representing ‘a point in the RGB gamut’.  I think that the hue, ... spaces are also just ‘another way of writing RGB colors’ (but more different than HTML).

By contrast CMYK ==> RGB is a ‘change of space’, number of coordinates, meaning etc, etc., as would/will be conversions to/from any ICC CIE etc., spaces.

**Comment by josephwright** [comment]
@car222222  HTML and RGB have exactly the same number of allowed values: 256 per channel. Perhaps you mean rgb, which has three floats? (I've followed `xcolor`: uppercase abbreviations are integer-based, lowercase ones are floating point, so RGB and rgb are distinct.)

You are right that HSB is 'another way of looking at RGB', which is why internally I've converted both HSB and Hsb to rgb.

**Comment by car222222** [comment]
OK. I had forgotten that you are using rgb and RGB for these two.  So HTML and RGB are even closer!  

What about the integer representations that use 0 to 100 (integer percentages): are you covering those too?

**Comment by josephwright** [comment]
@car222222  `xcolor` lets the user set the integer range. At the moment, I've not added that ability: I'm not sure it's particularly useful

**Comment by car222222** [comment]
@josephwright  I agree it is not clear how many different systems need support at the level of l3color.

As to the particular case of ‘integers 0 to 100’: this has some common uses in the real world, including these two:

—  for rgb values, it seems to be quite common in CSS (and hence probably other web uses);
—  it is ‘traditional’ to use it for CMYK specifications (dating from pre-digital times).  There are logical explanations of why 101 theoretical levels made sense there (and still do, I guess).

But note that Neither of these is a compelling reason for including it in l3color.

**Comment by car222222** [comment]
Also, of course, conversion from % to number is ’dead simple’.

**Comment by josephwright** [comment]
I've looked up CSS and it can take various formats: percentage is not _required_.  We can happily have `percentage-RGB` or whatever: these are easy to add.

**Comment by car222222** [comment]
Neither does HTML _require_   #<6 hex digits> . . .
 For example, one can use rgb ( R, B, G ) , with R, G, B being decimal integers 0 to 255.

**Comment by u-fischer** [comment]
> Neither does HTML _require_ #<6 hex digits> . . .
> For example, one can use rgb ( R, B, G ) , with R, G, B being decimal integers 0 to 255.

yes there a lots of variants possible and around. But we shouldn't add formats at random but concentrate on the variants for which concrete examples of their use and need in the tex world exists. hex number are e.g. used by fontspec, and space separated values by hyperref.

**Comment by josephwright** [comment]
@car222222 Sure, but `HTML` is a defined _input_ format for `xcolor` which it makes sense for us to also support and to be able to re-export.

**Comment by josephwright** [comment]
@u-fischer Are you happy for me to merge here?

**Comment by car222222** [comment]
Use of color fonts, as in fontspec, somewhat different from what is provided by l3color or xcolor.  AFAICT (in Open Type fonts at least) it is an idea for incorporating SVG specs into glyph definitions. Again, no articulat color reorientation is _required._

I agree that l3color does not need to provide  much in the way of export formats/representations: these should handled in a higher level like xcolor.

**Comment by u-fischer** [comment]
> Use of color fonts, as in fontspec, somewhat different from what is provided by l3color or xcolor. AFAICT (in Open Type fonts at least) it is an idea for incorporating SVG specs into glyph definitions. Again, no articulat color reorientation is _required.

Fonts can also be colored without some svg involved -- that is only needed if more than one color per glyph is involved. 

fontspec creates for example font calls like 

     Arial:mode=node;script=latn;language=DFLT;+tlig;color=FF0000FF

.  (the last two bytes are the opacity) and so needs something that allows it to translate a key `Color=red!50!blue` into NNNNNN  with the right hex numbers so that it can write out the correct code.

**Comment by josephwright** [comment]
@car222222  The point here is that we want `l3color` to deal with 'color storage and expression' as a single point of truth

**Comment by car222222** [comment]
@josephwright Sure, but what expression(s)?

I am not trying to state what representations are needed in the l3color layer.  I am only describing the range of possibilities and what certain systems ‘require’ (or do not).

Btw: fontspec probably can also get the required font by using color=rgb( M, N , O ).   
HTML is not _required_  for a color in an OpenType font.  It is not clear whether, when xcolor is used, it can now correctly interpret Color=red!50!blue, but it probably can (must check the code).

**Comment by u-fischer** [comment]
> Btw: fontspec probably can also get the required font by using color=rgb( M, N , O ).

No. The low-level syntax it has to use to pass the color to the engines requires hex number.  

Try (with lualatex):

```
\documentclass{book}
\begin{document}
\font\test= {file:lmroman10-regular.otf:mode=node;color=FF0000FF;}\test abc
\end{document}
```

the xelatex syntax is similar.

**Comment by car222222** [comment]
@u-fischer  Thanks for the information.

  I looked at the fontspec  code now: it is very specialised, including the name from xcolor case.
