### ISSUE TITLE
Support color spaces in DVI mode

### ISSUE THREAD

**Issue by josephwright** [latex3/latex3#744]
Spot color support is based at present on `colorspace` and only works in PDF mode. There is older PostScript code from SPQR which should be used to extend to PostScript-based routes. There is likely a need to review current practice at printers in this regard.

**Comment by car222222** [comment]
I found this brief summary of ‘postscript for printing’:

https://www.compart.com/en/postscript

Another feasible method of dealing with postscript seems to be to post-process the pdf.
There are many pdf to ps conversion facilities around.  I have not looked at any reviews of this methodology.

Here is an online (and free) one:

https://www.zamzar.com/convert/pdf-to-ps/

**Comment by josephwright** [comment]
@car222222  Sounds like it's much the same as PDF, I guess we just need the right 'magic' to set up the color spaces

**Comment by josephwright** [comment]
Fixed by ca23f18dff7229ad5978a43ffe7bcf425c27b0ef
