### ISSUE TITLE
Mixing colors from different color spaces

### ISSUE THREAD

**Issue by car222222** [latex3/latex3#748]
Since RGB is becoming ubiquitous, I think that a good fall-back rule is that, if there is no other obvious color space for the mixture, it should always fall-back to RGB.

Some cases of ‘obvious’: 

— all the colors to be mixed have the same ‘main color space’;

— an explicit color space is given (in an optional argument);

— (probably will not arise) mixing Separation and Process colors should involve a DeviceN space but what should happen if this space is not set up and explicitly specified?

**Comment by josephwright** [comment]
The current approach is the same as `xcolor`: in a mix, you follow the model given for the first colour _unless_ it's a case of `<gray>!x!<non-gray>`, where you follow the non-gray model. There is already the possibility to force a model at poin-0of-use: doesn't that cover it?

**Comment by car222222** [comment]
OK, probably.  Wait and see if people are happy with that.

Maybe document how to ‘force a model’?

**Comment by josephwright** [comment]
@car222222  I thought I had!

**Comment by josephwright** [comment]
I think this is already covered.
