### ISSUE TITLE
l3backend packaging

### ISSUE THREAD

**Issue by vincentb1** [latex3/latex3#763]
In the `l3backend.zip` file found on CTAN, there is some `l3backend.ins` script, and when one passes it to pdftex, there is some `l3docstrip.dtx` \input file not found issue.

OK, maybe you need the user to install some l3docstrip package in order to process the `.ins` file and this l3docstrip can anyway be found in the l3kernel package, but what also disturbs me, is that you input some `.dtx`and not some `.tex`for using l3docstrip. This is confusing because the `.dtx`files are supposed to fulfill the double objective to 
1) be some code documentation source file
2) be some file archive &mdash; like a tar file

They are not supposed to be the package itself as pdftex would load it, ie here to extract the files from the `l3backend.dtx` archive, aren't they ?

**Comment by josephwright** [comment]
The `l3docstrip.dtx` 'program' is somewhat special: DocStrip has to work _without_ extraction from the source for bootstrapping. As such, whilst the file is a `.dtx` it's designed to work directly, not require extraction. (The original DocStrip has extension `.tex` but is a `dtx`-style file in the same way.)

Extensions here are really only a guide in any case, and very few end users need to extract the code in any `l3` bundle.

**Comment by FrankMittelbach** [comment]
there is a task open to incorporate the l3docstrip features into docstrip.tex so over time the former will go away (or rather stay as an empty shell) https://github.com/latex3/latex2e/issues/337#issue-623061733
