### ISSUE TITLE
\seq_set_map:NNn and \seq_set_map:NNx

### ISSUE THREAD

**Issue by PhelypeOleinik** [latex3/latex3#766]
The documentation for `\seq_set_map:NNn` says it `x`-expands the `<inline function>`, so shouldn't it be `\seq_set_map:NNx` instead?

A `\seq_set_map:NNn` that doesn't expand would be a natural addition in this case.

**Comment by josephwright** [comment]
Isn't this set up so we get reasonable performance on longer sequences? Using an internal `x`-type expansion means there's only one assignment.

**Comment by PhelypeOleinik** [comment]
But the `x` variant doesn't need to be derived from `n`, I think.  With an `\exp_after:wN` and a `\use:n` more than before, for the `x`-expanding version, it could be defined like this:
```latex
\cs_new_protected:Npn \seq_set_map:NNx
  { \__seq_set_map:NnNNn \tl_set:Nx  { \exp_after:wN \exp_not:N \use:n } }
\cs_new_protected:Npn \seq_gset_map:NNx
  { \__seq_set_map:NnNNn \tl_gset:Nx { \exp_after:wN \exp_not:N \use:n } }
\cs_gset_protected:Npn \seq_set_map:NNn
  { \__seq_set_map:NnNNn \tl_set:Nx  { \exp_not:n } }
\cs_gset_protected:Npn \seq_gset_map:NNn
  { \__seq_set_map:NnNNn \tl_gset:Nx { \exp_not:n } }
\cs_new_protected:Npn \__seq_set_map:NnNNn #1#2#3#4#5
  {
    \__seq_push_item_def:n { #2 { \__seq_item:n {#5} } }
    #1 #3 { #4 }
    \__seq_pop_item_def:
  }
```

Of course, this is an odd one, because the `x` variant wouldn't expand _the argument_, it would only kick in later when the function applies to the sequence.  It's a weird situation...

**Comment by josephwright** [comment]
Rules on `x`-type expansion are clear: has to be equivalent to `\cs_generate_variant:Nn \name  { x }`. If it's not, then the name is `\thing_x:n`.

**Comment by eg9** [comment]
@josephwright 

Then it should be `\seq_set_map_x:NNn`

**Comment by PhelypeOleinik** [comment]
I'm with @eg9: I find it really odd to need to prefix macros with `\exp_not:N` in a `n` (or not otherwise explicitly `x`) function.

**Comment by blefloch** [comment]
+1 to renaming \seq_set_map:NNn to \seq_set_map_x:NNn (and same for gset of course).
