### ISSUE TITLE
Provide \msg_term:nn(nnnn) for diagnostic messages

### ISSUE THREAD

**Issue by PhelypeOleinik** [latex3/latex3#767]
Sometimes packages have `debug` options, or things like that, that print diagnostic messages to the terminal, and in those cases one has to use `\iow_term:n`, which doesn't (directly) allow saving messages separately like `\msg_new:nnn` does, nor does it provide line wrapping with `\iow_wrap:nnnN`, or other goodies from `l3msg`.

I think a new `term` class for messages would be useful in these cases. It could be defined like the `log` class, but with `\iow_term:n` instead:
```latex
  \__msg_class_new:nn { term }
    {
      \iow_wrap:nnnN
        { \use:c { \c__msg_text_prefix_tl #1 / #2 } {#3} {#4} {#5} {#6} }
        { } { } \iow_term:n
    }
```

Does it make sense?

**Comment by josephwright** [comment]
We used to have a debug message type, but the issue is that message redirection is slow compared to a simple `\cs_set_eq:NN \@@_debug:n \use_none:n`. So I removed it. That was when messages were more wordy: perhaps it's worth revisiting.

**Comment by FrankMittelbach** [comment]
Am 12.07.20 um 10:45 schrieb Joseph Wright:
> We used to have a debug message type, but the issue is that message 
> redirection is slow compared to a simple |\cs_set_eq:NN \@@_debug:n 
> \use_none:n|. So I removed it. That was when messages were more wordy: 
> perhaps it's worth revisiting.

code that stays in production versions as \@@_debug:n should really be 
as fast as possible so set to \use_non:n preferably in my opinion. But 
maybe that doesn't mean that there is sucha type to be used when 
debugging is set to "on"

**Comment by FrankMittelbach** [comment]
guess a "not" too many or missing: I meant perhaps we can have that type to be used debug is "on"

**Comment by PhelypeOleinik** [comment]
> We used to have a debug message type, but the issue is that message redirection is slow compared to a simple `\cs_set_eq:NN \@@_debug:n \use_none:n`. So I removed it. That was when messages were more wordy: perhaps it's worth revisiting.

Well, the idea really is that `l3msg` currently offers, for printing stuff to the terminal:
 - `log`, which can be easily missed (and is awful for debugging)
 - `warning`, which usually indicates something bad, or
 - `show`, which stops compilation

The idea is to have something that just prints some message to the terminal (no `warning` text, no stopping compilation) to print whatever messages are necessary.

If the purpose is for debugging performance-critical code, then the package writer should know that `\use_none:n` will do better than redirection (and of course, some documentation saying that redirection can be a bit slow).
