### ISSUE TITLE
Coffin display options in initex mode

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#770]
In `l3coffins` we have a few lines wrapped by docstrip guards `%<*package>...%</package>` that set colors and set a particular font for coffin coordinates etc.: `\@@_color:n` and `\l_@@_display_font_tl`.  The analogue for initex is marked as "TODO".

I'm not sure what the status of the `<initex>` sections is: is it for use when `expl3` is loaded as part of the LaTeX format?  Is it not used anymore?

**Comment by josephwright** [comment]
I think we can close here but over time tidy up the guards.

**Comment by blefloch** [comment]
Can you clarify what has to be done to tidy up the guards, perhaps as a separate
issue?  I didn't understand the conclusion of the discussion.
