### ISSUE TITLE
Missing expl3.sty file

### ISSUE THREAD

**Issue by devon-ge** [latex3/latex3#775]
I could not find expl3.sty file in my local distributions after update via tlmgr. Is the package deprecated now? Some packages like ctex and xeCJK still require expl3.

I download the file from http://mirrors.ctan.org/install/macros/latex/contrib/l3kernel.tds.zip. Unzip the file I get l3kernel folder which contains expl3.sty. Currently I put the .sty file in the project folder.

Is there any plan to fix this issue?

**Comment by josephwright** [comment]
This sounds like a 'local' issue in your update: `expl3.sty` remains part of the core distribution. Do you have access to the log from your latest `tlmgr` run?

**Comment by devon-ge** [comment]
@josephwright 
in the command line (`tlmgr update --all`), it shows the below info

> tlmgr.pl: skipping forcibly removed package: l3kernel
tlmgr.pl: skipping forcibly removed package: tex4ht

I don't know what happened, I never remove any package before.

After I run `tlmgr update --all --reinstall-forcibly-removed`, The ending lines of log file show:

> [Sun Jul 19 22:07:03 2020] auto-install new: l3kernel (55860)
[Sun Jul 19 22:08:29 2020] auto-install new: tex4ht (55858)

Now the problem is solved.
