### ISSUE TITLE
Reduce/clean up IniTeX guards

### ISSUE THREAD

**Issue by josephwright** [latex3/latex3#776]
As raised in https://github.com/latex3/latex3/issues/770#issuecomment-660639272, we likely should move to fewer IniTeX guards. Most of them can be converted to conditionals with relatively low cost.

**Comment by josephwright** [comment]
https://github.com/latex3/latex3/commit/a1f77a02566d25314f0d5b0675e5a68cb068a4f4 is the first commit on this, even though it's 'retrospective'.

**Comment by blefloch** [comment]
@josephwright Can you clarify which different modes the code can be loaded in?  I wouldn't know what to replace `<*initex>` guards by.

**Comment by josephwright** [comment]
@blefloch Other than `l3bootstrap` and `expl3`,  nothing really 'knows' how it was loaded: it's all extracted into `expl3-generic`. So all that's needed is to switch for example to `\cs_if_exist:N`-based approaches to testing 'can we set this'.

**Comment by josephwright** [comment]
@blefloch It's mainly a question of thinking 'does this rely on LaTeX2e' and putting in appropriate fall-backs: that's true often for generic stuff as much as IniTeX.

**Comment by josephwright** [comment]
My plan is to clean up first in `l3kernel` other than the hardcore IniTeX stuff (`l3alloc`, `l3final`, etc.), then do the rest of the tree before coming back to the hardcore area: we have some wider questions to address to finalise there.

I'm going to do one file at a time so there is no danger of a clash with anyone else also working on this.
