### ISSUE TITLE
Cannot use \char in `l3doc`

### ISSUE THREAD

**Issue by cykerway** [latex3/latex3#780]
Good:

``` tex
\documentclass{ltxdoc}
\begin{document}
Char \char"002E
\end{document}
```
Bad:

```tex
\documentclass{l3doc}
\begin{document}
Char \char"002E
\end{document}
```

**Comment by blefloch** [comment]
On 7/23/20 11:28 AM, Cyker Way wrote:
> Good:
> 
> \documentclass{ltxdoc}
> \begin{document}
> Char \char"002E
> \end{document}
> 
> Bad:
> 
> \documentclass{l3doc}
> \begin{document}
> Char \char"002E
> \end{document}

l3doc makes the quote character active so unavoidably leads to such issues.  Use
\char\string"002E to turn that " into a normal character token (catcode 12), or
more generally do \DeleteShortVerb{\"} (the backslash is important there) after
l3doc activates the quote character.  I think this happens \AtBeginDocument, so
you either need to put it after \begin{document}, or simply do
\AtBeginDocument{\DeleteShortVerb{\"}}.

\documentclass{l3doc}
\begin{document}
\DeleteShortVerb{\"}
Char \char"004E
\end{document}

**Comment by cykerway** [comment]
Right, I saw it in `\AtBeginDocument`:

``` tex
\MakeShortVerb \"
```
