### ISSUE TITLE
expl3 cannot be explicitely loaded with latex-dev

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#781]
The following MCE:

```latex
\documentclass{article}
\usepackage{expl3}
\begin{document}
\end{document}
```

run with `latex-dev`:

>This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=latex-dev)

leads to the following error:

```
! Undefined control sequence.
l.67   \bool
            _new:N \g__expl_reload_bool
```

**Comment by eg9** [comment]
I get this:

```tex
latex-dev  dberr
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=latex-dev)
 restricted \write18 enabled.
entering extended mode
(./dberr.tex
LaTeX2e <2020-10-01> pre-release-7 (develop 2020-7-23 branch)
L3 programming layer <2020-07-17> xparse <2020-03-03>
(/usr/local/texlive/2020/texmf-dist/tex/latex-dev/base/article.cls
Document Class: article 2020/04/10 v1.4m Standard LaTeX document class
(/usr/local/texlive/2020/texmf-dist/tex/latex-dev/base/size10.clo))
(/usr/local/texlive/2020/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/local/texlive/2020/texmf-dist/tex/latex/l3backend/l3backend-dvips.def))
(./dberr.aux) (./dberr.aux) )
No pages of output.
Transcript written on dberr.log.
```

**Comment by josephwright** [comment]
@dbitouze That error happens when the format files get out of sync with the TeX tree: can you do `fmtutil-sys -byfmt pdflatex-dev`?

**Comment by u-fischer** [comment]
if the problem persists check with `kpsewhich --all --engine=pdftex latex-dev.fmt` if you have some local format lurking around.

**Comment by dbitouze** [comment]
@josephwright Same result. Even more weird: `pdflatex test` is okay but, despite a `fmtutil-sys -byfmt latex`, `latex test` gives the same error.

**Comment by dbitouze** [comment]
@u-fischer
```
$ kpsewhich --all --engine=pdftex latex-dev.fmt
/home/bitouze/.texlive2020/texmf-var/web2c/pdftex/latex-dev.fmt
/usr/local/texlive/2020/texmf-var/web2c/pdftex/latex-dev.fmt
```
I will be offline from now on until tomorrow.

**Comment by u-fischer** [comment]
@dbitouze delete the `/home/bitouze/.texlive2020/texmf-var/web2c/pdftex/latex-dev.fmt`.

**Comment by dbitouze** [comment]
@u-fischer Deleting `/home/bitouze/.texlive2020/texmf-var/web2c/pdftex/latex-dev.fmt` did indeed the trick.
