### ISSUE TITLE
l3seq: (Feature Request) Split Without Trimming Spaces

### ISSUE THREAD

**Issue by tail-reversion** [latex3/latex3#784]
A version of `\seq_set_split:Nnn` that does not trim spaces would be very useful for splitting verbatim text into lines.

In [his answer to my tex.SX question](https://tex.stackexchange.com/a/555365/122239), @josephwright provided a temporary solution for me and suggested that I make a feature request here.

**Comment by blefloch** [comment]
Any suggestion for the name?

**Comment by blefloch** [comment]
Another stackexchange question, «[Preserving spaces when scannig `tl` variables into a sequence using `\seq_set_split`](https://tex.stackexchange.com/questions/459519)» seems related too.

**Comment by zauguin** [comment]
> Any suggestion for the name?

I would suggest `\seq_set_split_keep_spaces:Nnn`, similar to the `ignore_spaces` variants we have for other macros.

**Comment by car222222** [comment]
I agree with @zauguin on the name.

Assuming that there is as yet no similar phrase in use.

**Comment by josephwright** [comment]
I'll look to add this shortly
