### ISSUE TITLE
Command to set a tl to the underlying token list of a structure.

### ISSUE THREAD

**Issue by car222222** [latex3/latex3#791]
Rather than having a lot of commands such as \tl_set_from_clist:NN , . . . have a single command that will do this 'forgetting' for any structure based on a tl.

I shall refrain from getting into the major task of naming it as I have no ideas, not even bad ones!

**Comment by Skillmon** [comment]
While setting a `tl` from a `clist` or `str` like this isn't an issue, other data-types would need more care (e.g., I doubt that `\tl_set_from_other:NN \l_tmpa_tl \l_tmpa_seq` -- name not to meant to be the final name -- should behave like `\cs_set_eq:NN \l_tmpa_tl \l_tmpa_seq`). What exactly would you want to have covered with this new function?

**Comment by car222222** [comment]
I should have made it clear that this would only be for things like clist and seq that are 'just a tl'.  

That is why thinking of a name is so difficult.

**Comment by FrankMittelbach** [comment]
The core of expl3 what has been named l3kernel or L3 programming layer attempts to use type data structures. In line with its philosphy would be conversion from one datastructur to another, e.g., `\tl_set_from_clist:NN`, `\tl_set_from_seq:NN, etc but not something like `\tl_set_from_anything:NN` where anything could be any datastructure and the command would first determine what is type is in the second argument and then call the appropriate `\tl_set_from_<type>:NN`.

There is nothing wrong with having such a command per se, but it doesn't belong into L3 programming layer, it is a higher abstraction. But for programming I see no gain in such a thing, if I have a variable of some `<type1>`and  want to convert it to some other `<type2>` and then the expl3 naming convention for this is
```
    \<type2>_set_from_<type1>:NN  \l_<name>_<type2>  \l_<othername>_<type1>
```
with the appropriate variations for global setting and global variables.
So what is needed is `\tl_set_from_clist:NN` as that is missing (and it is).

**Comment by eg9** [comment]
I'm not sure whether `\tl_set_from_clist:NN` is needed at all. Should it remove the commas or not? If it should, then
```tex
\tl_set:Nx \l_tmpa_tl { \clist_map_function:NN \l_tmpa_clist \use:n }
```
would do. Similarly for sequences, but I can't see what the “underlying token list” of a sequence is.

Keeping the commas would be using implementation details: the _external_ representation of a clist is with commas, the internal one might not be.

**Comment by car222222** [comment]
Whilst I agree with Frank,that the wording 'setting from a clist, etc.' is perhaps ambiguous, there is here an unambiguous thing that one may want to do.

@eg9 wrote:
but not something like \tl_set_from_anything:NN, where anything could be any datastructure and the command would first determine what is type is in the second argument and then call the appropriate\tl_set_from_:NN`.

No!  Not really 'anything'.  There are some data structures that are clearly documented as being 'just a tl' (called the 'underlying tl') whose internal syntax is interpreted in a documented way.

For these it is completely unambiguous what the 'forgetful setter' does: it simply returns the 'underlying tl'.  

This is a very common type of constructor in typed languages.

**Comment by car222222** [comment]
Important note: this forgetter is actually just \tl_set_eq:NN (which is just \let in old currency).  No new magic here, just a suitable 'typed name' to keep Frank happy:-).

**Comment by u-fischer** [comment]
> There are some data structures that are clearly documented as being 'just a tl'

Where is documentated that a clist is just a tl?

**Comment by car222222** [comment]
@u-fischer :  

16.2 Allocation and initialisation

Internally, comma lists are just token lists.

BUT, I also discovered a seq is internally a c:
Curiouser and Curiouser!

**Comment by u-fischer** [comment]
sorry but "internally" describes only something internal, and doesn't mean that this can't change in future. "Documentated" in the sense that you can rely on it, would require that it is described as user interface in interface3.

**Comment by blefloch** [comment]
On 8/16/20 5:39 PM, Ulrike Fischer wrote:
> sorry but "internally" describes only something internal, and doesn't mean that
> this can't change in future. "Documentated" in the sense that you can rely on
> it, would require that it is described as user interface in interface3.

It will be hard to grep for it, but I'm pretty certain that people have relied
on the fact that expanding a clist once gives something that can be passed
directly to usual LaTeX2e constructs so we really cannot change the internal
implementation there.  Now perhaps it is not documented, but it should be.

Bruno

**Comment by Skillmon** [comment]
@blefloch the kernel itself does rely on that already (though, of course, the kernel can be easily changed once the internals of a `clist` change).

**Comment by blefloch** [comment]
In https://github.com/latex3/latex3/commit/9753642068fd4608b95fb64c425da6e2885103c2 I've implemented `\tl_set_eq_clist:NN`, leading to the following exchange with Frank.

>> **Bruno wrote:** Implement `\tl_set_eq_clist:NN` to change type but not data (see #786)
>> In `l3keys` there are various places where one has a clist variable and one wants to store it in a tl.  I wouldn't mind using `\tl_set_eq:NN` (tl var) (clist var), with the thought that the (clist var) is in particular a tl var, but others may disagree.     We should discuss.
-----
> **Frank wrote:**
> just reread the earlier part of the discussion on #786.
>
> I would say my initial point there was not about the tl - clist relationship but about using `\cs_...` instead of `\tl_set` `\clist_...` and  so forth.
>
> The relationship between tls and clists is  a bit special in the sent that they are documented (?) to be the same but with a different focus
>
> We have opted back then to have clist as a type as it is really helpful (imho) to see that some variable "contains tokens separated by commas and down the line going to be interpreted by 'splitting' along the commas" but in practice any tl is a clist and vice versa
>
> so yes I wouldn't be too worried about `\tl_set_eq:NN (tl var) (clist var)` either, but on the other hand since we have the two types we could make conversions which is perhaps a little bit cleaner.
>
> However, when it then comes to names, should be the conversion function `\tl_set_from_clist:NN` not set_eq ?
>
> I mean technically it is set equal but conceptually it says, from here on I don't care about using this a a comma-list any more so I convert it to a tl

Yes, but `\seq_set_from_clist:NN` changes items of the clist into items of the seq, while the function we are talking about does not give you a tl whose items are the items of a clist.  I would expect `\tl_set_from_clist:NN` to transform `a,bc,cd into `{a}{bc}{cd}`.

Should we simply scrap the special name and use `\tl_set_eq:NN`?  That sounds simpler, especially because the same question arises for strings.  Despite my branch, I like this better.

**Comment by car222222** [comment]
@blefloch asks: Should we simply scrap the special name and use \tl_set_eq:NN? 

Well, 'calling this spade a spade' would have the advantage of circumventing all the arguments about whether it should even be known that such list data types are nothing more than 'fancy tls'.  
Not to mention the naming problem, which is where we came in . . . 

But the idea of a synonym for this is appealing! This being generic idea of being 'forgetful' , i.e., 'changing only the type name - no change of content'.

Just for a laugh, here is my dreadful attempt at a suitable name:

\tl_from_internal:NN       --  shortest 
\tl_set_from_internal:NN
\tl_from_internaltl:NN
. . .

**Comment by car222222** [comment]
Someone wrote:  I would expect \tl_set_from_clist:NN 
to transform "a,bc,cd" into "{a}{bc}{cd}".

Maybe, but why have the braces 'replacing' the commas?  
Remember that they are equally themselves items of the tl, just like the commas would be.  

The tl data-type is not defined as a sequence of 'brace-groups or single tokens', AFAIK!  It is simply a nuisance artefact of the notation that the braces must be balanced.

A converter function that does put items into brace groups may also be useful, but this is a distinct idea.
