### ISSUE TITLE
[doc] xfp: possible typo, "x >? y" should be "x ? y"

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#793]
from https://tex.stackexchange.com/q/558606

Related source lines:
https://github.com/latex3/latex3/blob/8e237df69c46e0625f352e4c9d6b13189008e698/l3packages/xfp/xfp.dtx#L90-L92

From related documentation for floating point expressions in `texdoc interface3`, it seems the 
```tex
$x\mathop{\mathtt{>?}}y$
```
in line 91 should be 
```tex
$x\mathop{\mathtt{?}}y$
```
which compares if `x` and `y` are not ordered (for example, one of them is NaN).

**Comment by hmenke** [comment]
Not a bug.  These operators are composable.

**Comment by muzimuzhi** [comment]
Sorry.

Here is the related doc for `\fp_eval:n`
https://github.com/latex3/latex3/blob/8e237df69c46e0625f352e4c9d6b13189008e698/l3kernel/l3fp.dtx#L955-L972

> %   Each \meta{relation} consists of a **non-empty** string of |<|, |=|,
> %   |>|, and~|?|, optionally preceded by~|!|, and **may not** start
> %   with~|?|.

**Comment by blefloch** [comment]
We could actually allow x??y if people find this clearer than x!<=>y.  The
reason not to allow x?y is the ambiguity with the ternary operator x?y:z.

**Comment by hmenke** [comment]
@blefloch Why does `?` exist in the first place?  Isn't the `nan` case covered by `x != x`?
