### ISSUE TITLE
Add renaming of \draw_color:n to \color_select:n to changelog?

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#799]
Roughly speaking, `\draw_color:n` was renamed to `\color_select:n` by https://github.com/latex3/latex3/commit/7bb3e4a163c7e18d4bccbd68660fb19fc013d830.

Is this worth being recorded in the [`CHANGELOG.md`](https://github.com/latex3/latex3/blob/master/l3experimental/CHANGELOG.md) of l3experimental?

**Comment by josephwright** [comment]
The change log for `l3experimental` reflects the 'experimental' nature of the code, so it's not as detailed as other parts of the codebase. There is a line about the change, but I can extend.

**Comment by muzimuzhi** [comment]
Thanks. I encountered the reported problem when I tried to compile the `l3draw` example you posted in https://github.com/pgf-tikz/pgf/issues/817#issuecomment-572943428 but found `\draw_color:n` undefined.
