### ISSUE TITLE
 `l3backend-xdvipdfmx.def' not found

### ISSUE THREAD

**Issue by devon-ge** [latex3/latex3#801]
When I compile my document, the command line shows:

>(c:/texlive/2020/texmf-dist/tex/latex/amsmath/amsmath.sty
>For additional information on amsmath, use the `?' option.
>(c:/texlive/2020/texmf-dist/tex/latex/amsmath/amstext.sty
>(c:/texlive/2020/texmf-dist/tex/latex/amsmath/amsgen.sty))
>(c:/texlive/2020/texmf-dist/tex/latex/amsmath/amsbsy.sty)
>(c:/texlive/2020/texmf-dist/tex/latex/amsmath/amsopn.sty))
>(c:/texlive/2020/texmf-dist/tex/latex/ctex/ctexbook.cls
>(c:/texlive/2020/texmf-dist/tex/latex/ctex/config/ctexbackend.cfg)
>(c:/texlive/2020/texmf-dist/tex/latex/l3kernel/expl3.sty
>
>! LaTeX Error: Missing \begin{document}.
>
>See the LaTeX manual or LaTeX Companion for explanation.
>Type  H <return>  for immediate help.
> ...
>
>l.77      \ExplLoaderFileDate{expl3.sty}}
>                                         %
>
>! LaTeX Error: File `l3backend-xdvipdfmx.def' not found.
>
>Type X to quit or <RETURN> to proceed,
>or enter new name. (Default extension: def)
>
>Enter file name:
>! Emergency stop.
><read *>
>
>l.148   { \sys_load_backend:n { } }
>
>No pages of output.

I got this issue after the latest update via `tlmgr update --all`. What happens to `expl3.sty`?

**Comment by josephwright** [comment]
We have carried out minor file renames: did you update both `l3kernel` and `l3backend`?

**Comment by devon-ge** [comment]
@josephwright I've updated all packages, including `l3kernel` and `l3backend`. Now all packages are up-to-date. 

log from TeXstudio:
`expl3.sty` line 77: Missing \begin{document}. \ExplLoaderFileDate{expl3.sty}}
`expl3.sty` line 148: File `l3backend-xdvipdfmx.def' not found. { \sys_load_backend:n { } }

Is there a way to see the diff of `expl3.sty`?

**Comment by josephwright** [comment]
@devon-ge As I said, this is due to a change which needs to match in `l3backend`: I can tell you the exact line, all you really need is the file date in `expl3.sty` (right at the top of the file): your one is too old. Are you perhaps using MiKTeX?

**Comment by u-fischer** [comment]
try to recreate the formats with fmtutil-sys --all, the ` Missing \begin{document}. \ExplLoaderFileDate{expl3.sty}}` normally indicates that the code in the format is older than the current expl3.sty

**Comment by devon-ge** [comment]
@josephwright Thanks. did u mean this comment? the date is 2020/09/03
>%%
%% This is file `expl3.sty',
%% generated with the docstrip utility.
%%
%% The original source files were:
%%
%% expl3.dtx  (with options: `package,loader')
%% 
%% Copyright (C) 1990-2020 The LaTeX3 Project
%% 
%% It may be distributed and/or modified under the conditions of
%% the LaTeX Project Public License (LPPL), either version 1.3c of
%% this license or (at your option) any later version.  The latest
%% version of this license is in the file:
%% 
%%    https://www.latex-project.org/lppl.txt
%% 
%% This file is part of the "l3kernel bundle" (The Work in LPPL)
%% and all files in that bundle must be distributed together.
%% 
%% File: expl3.dtx
\def\ExplFileDate{2020-09-03}%
\let\ExplLoaderFileDate\ExplFileDate
\ProvidesPackage{expl3}
...

I use TeXLive 2020.

**Comment by devon-ge** [comment]
`tlmgr update --all` does not update the filename database. In TeX Live manager, `Regenerate filename database` solved this issue.
