### ISSUE TITLE
\sys_timer: and \sys_gzero_timer:

### ISSUE THREAD

**Issue by zauguin** [latex3/latex3#803]
On 8/24/20 1:48 PM, Marcel Krüger wrote:
>     I mean that as we want as far as possible engine-neutral behaviour, don't we
>     just accept that the results are not analytical, and aim for consistent
>     behaviour between engines?
> 
> I now added an implementation which gives the same behavior in LuaTeX as in
> pdfTeX: Wall time is used instead of CPU time. For initialization reasons, the
> time zero is a bit less defined and currently this stuff is defined in a
> \lua_now:n block, but that will get better once this is loaded in the format.
> That's unrelated to this PR, but think we should consider moving |\sys_timer:|
> to l3sys and maybe then drop |\sys_gzero_timer:| (or move that to l3sys too).
> The current design of l3benchmark defining a l3sys function it doesn't even use
> feels wrong.
> 

I suspect these functions have not been used much so they can be
changed/simplified/removed without too much worry if they seem wrong.  No
opinion on that.

B

_Originally posted by @blefloch in https://github.com/latex3/latex3/pull/796#issuecomment-679337918_

Continuing this here: Currently `l3benchmark` defines `\sys_timer:` and `\sys_gzero_timer:`. I would like to move `\sys_timer:` to `l3sys` but we should first decide what to do about `\sys_gzero_timer:`. 
`\sys_gzero_timer:` is not used anywhere currently and it's problematic because it can easily break code which assumes that `\sys_timer:` counts monotonically. Therefore I would prefer to drop it, we could reintroduce it if we ever really need it. (All usecases I can think of involve TeX runs taking more than 9 hours, so I think it's unlikely that we will need it anytime soon.)

Does anyone else have an opinion on this?

**Comment by josephwright** [comment]
I think we should do this: @zauguin can you action?
