### ISSUE TITLE
! LaTeX Error: Missing \begin{document}.

### ISSUE THREAD

**Issue by wabristow** [latex3/latex3#805]
After update of all packages I get:

(/usr/local/texlive/2020/texmf-dist/tex/latex/l3kernel/expl3.sty

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.77      \ExplLoaderFileDate{expl3.sty}}
                                         %

**Comment by u-fischer** [comment]
Your format is not in sync with the expl3 files. Check with  `kpsewhich --engine=pdftex pdflatex.fmt` (if the error is with pdflatx) if you have some some local formats interferring and delete them. Then recreate the system formats with fmtutil-sys --all.

**Comment by hehhehheh** [comment]
I'm replicating this error on my Debian Testing installation of Tex Live 2020.
Using the minimal working example:
`\documentclass{article}`
`\usepackage{expl3}`
`\begin{document}`
`\end{document}`

and compiling it with:
`latex test.tex`
`pdflatex test.tex`
`lualatex test.tex`

always produces the error:
`(/home/qwed/texmf/tex/latex/l3kernel/expl3.sty`
`Package: expl3 2020-10-05 L3 programming layer (loader)` 


`! LaTeX Error: Missing \begin{document}.`

`See the LaTeX manual or LaTeX Companion for explanation.`
`Type  H <return>  for immediate help.`
 `...                                          `    
                                                  
`l.77      \ExplLoaderFileDate{expl3.sty}}`
`                                         %`
`? `

Trying to find the non-synced format files with
` kpsewhich --engine=/ pdflatex.fmt`
and `lualatex.fmt` or `latex.fmt`.
I only got the files
`/var/lib/texmf/web2c/pdftex/pdflatex.fmt`
`/var/lib/texmf/web2c/pdftex/latex.fmt`
`/var/lib/texmf/web2c/luahbtex/lualatex.fmt`
which I understand should be correct outputs?

I did try recreating them with
`fmtutil-sys --all`
but this did not help.

Moving the entire web2c folder away temporarily and compiling gives the error:
`(/home/qwed/texmf/tex/latex/l3kernel/expl3.sty`
`Package: expl3 2020-10-05 L3 programming layer (loader) `


! LaTeX Error: File `l3backend-pdftex.def' not found.

`Type X to quit or <RETURN> to proceed,`
`or enter new name. (Default extension: def)`

`Enter file name: x`

So I'm pretty sure I should have these format files.
Am I missing something here?
I'm not sure I've ever tried using a package with expl3.sty before so I can't say if this is a new problem.

**Comment by u-fischer** [comment]
@hehhehheh  Show the complete log-file, not only a snippet.

**Comment by davidcarlisle** [comment]
the error indicates that your format and expl3 are not matching. Perhaps not unrelated, your installed locations look a bit odd with the formats in a system location at /var/lib/texmf but your expl3 in a different tree at /home/qwed/texmf

**Comment by hehhehheh** [comment]
It was not unrelated. Removing the `/home/qwed/texmf/` folder fixed the problem and it did not reappear after reinitializing the folder using tlmgr. The problem seems to therefore have been with an old local Tex Live folder and not latex3. Thank you.
This was not a solution I saw anywhere else, so I hope it'll be of use to someone.
