### ISSUE TITLE
l3fp: improve doc for unit `sp`

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#807]
Unit `sp` is currently documented as
https://github.com/latex3/latex3/blob/34a8d7bab969dcd174684de61b34e25c158d8a87/l3kernel/l3fp.dtx#L1381
and the output is not very well.
![image](https://user-images.githubusercontent.com/6376638/93643895-7582bd80-fa33-11ea-8ef2-f0e55a0d3697.png)

An attempt would be
```diff
diff --git a/l3kernel/l3fp.dtx b/l3kernel/l3fp.dtx
index f19f21c1c..f52e94e9d 100644
--- a/l3kernel/l3fp.dtx
+++ b/l3kernel/l3fp.dtx
@@ -1378,7 +1378,7 @@
 %     1 \unit{nd} & = 0.375 \unit{mm} = 1.066978346456693 \unit{pt} \\
 %     1 \unit{nc} & = 12 \unit{nd} = 12.80374015748031 \unit{pt} \\
 %     1 \unit{bp} & = \frac{1}{72} \unit{in} = 1.00375 \unit{pt} \\
-%     1 \unit{sp} & = 2^{-16} \unit{pt} = 1.52587890625e-5 \unit{pt}.
+%     1 \unit{sp} & = 2^{-16} \unit{pt} = 1.52587890625\mathrm{e}{-}5 \unit{pt}.
 %   \end{align*}
 %   The values of the (font-dependent) units \unit{em} and \unit{ex} are
 %   gathered from \TeX{} when the surrounding floating point expression
```
which will give
![image](https://user-images.githubusercontent.com/6376638/93643845-600d9380-fa33-11ea-9326-690a63f4d8f9.png)

**Comment by car222222** [comment]
A small refinement to the layout would be something like:


1.52587890625\,\mathrm{e}{-5}\, \unit{pt}.

**Comment by dbitouze** [comment]
@car222222 I don't see the point with the commas. Why not make use of `siunitx`?
```latex
\documentclass{article}
\usepackage{amssymb}
\usepackage{mathtools}
\usepackage{siunitx}
\newcommand{\unit}[1]{\text{\texttt{#1}}}
\begin{document}
\begin{align*}
  1 \unit{sp} & = 2^{-16} \unit{pt} = 1.52587890625e-5 \unit{pt} \\
  1 \unit{sp} & = 2^{-16} \unit{pt} = 1.52587890625\mathrm{e}{-}5 \unit{pt} \\
  1 \unit{sp} & = 2^{-16} \unit{pt} = 1.52587890625,\mathrm{e}{-5}, \unit{pt} \\
  1 \unit{sp} & = 2^{-16} \unit{pt} = \SI{1.52587890625e-5}{\unit{pt}}.
\end{align*}
\end{document}
```
![test](https://user-images.githubusercontent.com/1032633/93667131-c02c2600-fa83-11ea-8a19-a46bd4d60c36.png)

**Comment by blefloch** [comment]
@dbitouze I'm pretty sure that @car222222 meant to type thin spaces `\,` but it got eaten at some point in the conversion.  I agree with you that the $\times 10^{-5}$ form is better, but I wouldn't want to use `siunitx` for that because it's best to keep the doc building somewhat self-contained.

**Comment by car222222** [comment]
Yes, I meant thinspaces, but other formats are OK too.
