### ISSUE TITLE
Error in `\tl_if_head_eq_charcode:nN` and `\tl_if_head_eq_catcode:nN`

### ISSUE THREAD

**Issue by Skillmon** [latex3/latex3#808]
The current implementation of `\tl_if_head_eq_charcode:nN` and `\tl_if_head_eq_catcode:nN` assumes that `\prg_return_true: \else:` can be safely gobbled by `\use_none:nn`. With the current implementation of `\prg_new_conditional:Npnn` this holds true for `TF`, `T`, and `F`, but not for `p`, and only by chance because in the working cases two tokens are inserted as an optimisation (`\exp_after:wN \use_ii:nnn`), unlike in the `p` variant in which only one token (`\__prg_p_true:w`) is inserted.

MWE showing both errors:

```
\documentclass[]{article}

\begin{document}
\ExplSyntaxOn
\bool_if:nTF { \tl_if_head_eq_catcode_p:nN {} ? }
  {}
  {}

\bool_if:nTF { \tl_if_head_eq_charcode_p:nN {} ? }
  {}
  {}
\ExplSyntaxOff
\end{document}
```

(A fix will be part of https://github.com/latex3/latex3/pull/789.)

**Comment by josephwright** [comment]
@blefloch Any comment here?
