### ISSUE TITLE
xparse

### ISSUE THREAD

**Issue by NikolayTach** [latex3/latex3#809]
LaTeX2e <2019-10-01> patch level 3
(/usr/local/texlive/2019/texmf-dist/tex/latex/tugboat/ltugboat.cls
Document Class: ltugboat 2019-11-09 v2.22 TUGboat journal class
(/usr/local/texlive/2019/texmf-dist/tex/latex/base/article.cls
Document Class: article 2019/10/25 v1.4k Standard LaTeX document class
(/usr/local/texlive/2019/texmf-dist/tex/latex/base/size10.clo
File: size10.clo 2019/10/25 v1.4k Standard LaTeX file (size option)
)

**Comment by josephwright** [comment]
I'm not sure what the issue you are trying to report is!

**Comment by NikolayTach** [comment]
Doesn't allocate the sorted .cls files everywhere:
 \def\tubmultipleaffilauthor{\unskip, \ignorespaces}%
 \def\tubmultipleaffilauthor{\skip, \ignorespaces}%
=====

**Comment by NikolayTach** [comment]
Only works on the new latex version.

**Comment by josephwright** [comment]
Still no idea what you mean

**Comment by NikolayTach** [comment]
`
\documentclass[final]{ltugboat}

\makeatletter
\def\thepage{%
  \ifnum\value{page}>1000
    \textit{?\@arabic{\numexpr\the\c@page-1000\relax}}%
  \else
       \arabic{page}%
  \fi}
\makeatother
` 
does simply not run on the old LaTex version.

**Comment by josephwright** [comment]
It does: you must have a version of `ltugboat` using features newer than your LaTeX installation. In any case, it's not maintained by the team so it's not something that can be fixed by a report here: sorry.

**Comment by NikolayTach** [comment]
I see. Thank you anyway!
