### ISSUE TITLE
Is it stable?

### ISSUE THREAD

**Issue by egils-consulting** [latex3/latex3#810]
Hi I am new to latex, is latex3 stable? I could not find any information about beta/stable on the website nor in here.

**Comment by josephwright** [comment]
There is no separate LaTeX3, but there is an `expl3` programming layer. This is documented as broadly stable for example in `interface3.pdf`, and is being used to support new LaTeX2e functions. As such you can be confident of future support.

**Comment by josephwright** [comment]
I would say `expl3` is stable, and this is documented in a number of places.
