### ISSUE TITLE
\c_document_cctab does not make upper-half of the 8-bit range active

### ISSUE THREAD

**Issue by stone-zeng** [latex3/latex3#814]
In `l3interface`:

> - `\c_document_cctab`:
>
>    Category code table for a standard LaTeX document, as set by the LaTeX kernel. In particular, the upper-half of the 8-bit range will be set to "active" with pdfTeX *only*. No `babel` shorthands will be activated.

However, for the following example:

```tex
\csname tl_analysis_show:n\endcsname{1:^^70^^80}

\ExplSyntaxOn
\tl_analysis_show:n { 2:^^70^^80 }

\cctab_begin:N \c_document_cctab
\csname tl_analysis_show:n\endcsname{3:^^70^^80}
\cctab_end:

\ExplSyntaxOff
```

Run with `latex` or `pdflatex` (or `*-dev`), it gives

```
LaTeX2e <2020-10-01>
L3 programming layer <2020-09-24> xparse <2020-03-03>
The token list contains the tokens:
>  1 (the character 1)
>  : (the character :)
>  p (the letter p)
>  � (active character=macro:->\UTFviii@invalid@err �).
<recently read> }
                 
l.1 ...me tl_analysis_show:n\endcsname{1:^^70^^80}
                                                  
? 
The token list contains the tokens:
>  2 (the character 2)
>  : (the letter :)
>  p (the letter p)
>  � (active character=macro:->\UTFviii@invalid@err �).
<recently read> }
                 
l.4 \tl_analysis_show:n { 2:^^70^^80 }
                                      
? 
The token list contains the tokens:
>  3 (the character 3)
>  : (the character :)
>  p (the letter p)
>  � (the character �).
<recently read> }
                 
l.7 ...me tl_analysis_show:n\endcsname{3:^^70^^80}
                                                  
? 
```

So after `\c_document_cctab`, `^^80` becomes a normal character rather than an active one.

BTW, the variables described here should be `\c_code_cctab` and `\c_document_cctab`:

https://github.com/latex3/latex3/blob/19ea461b8a5126f08f1b5ed7494e328be033ec90/l3kernel/l3cctab.dtx#L769-L775

**Comment by josephwright** [comment]
Hopefully now sorted: I was forgetting that we needed to do this

**Comment by josephwright** [comment]
@PhelypeOleinik  (but others too): is there any point in the delay I set up for creating the table? I think we are now ignoring LaTeX2e settings entirely, so we could skip that: correct?

**Comment by zauguin** [comment]
@josephwright If I'm not missing anything we are only ignoring the LaTeX2e settings in 8-bit engines and therefore still need the delay for Unicode engines.

**Comment by josephwright** [comment]
@zauguin Ah right yes: the catcodes from `UnicodeData` have to be loaded. Probably should note that in the code!
