### ISSUE TITLE
xbox: \rule_horizontal:nn and \rule_vertical:n should be terminated properly

### ISSUE THREAD

**Issue by RuixiZhang42** [latex3/latex3#815]
The descriptions for `\rule_horizontal:nn` and `\rule_vertical:n` sound like these commands will be terminated properly after absorbing their arguments. However, a simple input
```latex
\rule_vertical:n {10pt} heightened
```
leads to low-level TeX error
```
! Missing number, treated as zero.
<to be read again> 
                   e
```
since the primitive `\tex_vrule:D` keeps scanning ahead for keywords (`height` in this example). A worse example is
```latex
\rule_vertical:n {10pt} width 20pt ~
```
resulting in a 20pt-wide vertical rule.

These should perhaps be implemented as follows:
```latex
\cs_new_protected:Npn \rule_horizontal:nn #1#2
  {
    \tex_hrule:D
      height \dim_eval:n {#1} \exp_stop_f:
      depth  \dim_eval:n {#2} \exp_stop_f:
      \scan_stop:
  }
\cs_new_protected:Npn \rule_vertical:n #1
  {
    \tex_vrule:D
      width \dim_eval:n {#1} \exp_stop_f:
      \scan_stop:
  }
```

**Comment by RuixiZhang42** [comment]
Also, the description of `\rule:nnn` is wrong:
https://github.com/latex3/latex3/blob/19ea461b8a5126f08f1b5ed7494e328be033ec90/l3trial/xbox/xbox.dtx#L589-L597
According to its implementation, `\rule:nnn` does NOT insert rule in horizontal mode. It simply wraps a vertical rule in an hbox, then put this hbox in a list. So `\par\rule:nnn{...}{...}{...}` would insert a rule in vertical mode.

**Comment by josephwright** [comment]
I'll tidy up, though I do note that `xbox` is in `l3trial` and thus not actually released!

**Comment by RuixiZhang42** [comment]
@josephwright 
> […] `xbox` is in `l3trial` and thus not actually released!

True. The reason for this report is because I was implementing my version of `\tex_vrule:D`. I wan’t sure how many `\tex_relax:D` were needed so I searched this repo for code snippets. I found out the missing `\relax` when I tested my version.

Unlike glue specification (which, after seeing `minus <shrink dimen>`, will stop scanning ahead), rule specification allows repeated use of `height`, `depth` and `width` in any order (where the last one overrules). So, even if all 3 keywords `height`, `depth` and `width` are present in a rule specification, we still need a `\relax` to terminate further scanning (unless the rule was enclosed in a box, in which the specification is terminated by the box closing&nbsp;`}`).

**Comment by car222222** [comment]
Thanks, @RuixiZhang42, for pointing out this technicality of rule specs.  You live and learn (or rather 'relearn' in my case:-)!

**Comment by RuixiZhang42** [comment]
In https://github.com/latex3/latex3/commit/5dc338962c3dea6ea5fe4fe9d92d764380603b10 a `\mode_leave_vertical:` was added to `\rule:nnn`. As a result,
https://github.com/latex3/latex3/blob/5dc338962c3dea6ea5fe4fe9d92d764380603b10/l3trial/xbox/xbox.dtx#L1545-L1549
now has double `\mode_leave_vertical:`’s, which is redundant.

According to *The TeXbook*:
> If you say `\vrule` in vertical mode, TeX starts a new paragraph[…]

So why not
```latex
\cs_new_protected:Npn \rule:nnn #1#2#3
  {
    \tex_vrule:D
      height \dim_eval:n {#2} \exp_stop_f:
      depth  \dim_eval:n {#3} \exp_stop_f:
      width  \dim_eval:n {#1} \exp_stop_f:
      \scan_stop:
  }
```
and then
```latex
\RenewDocumentCommand \rule { O { 0pt } m m }
  {
    \mode_leave_vertical:
    \hbox:n { \rule:nnn {#2} { #3 + #1 } { -#1 } }
  }
```

**Comment by RuixiZhang42** [comment]
@josephwright There are two `\RenewDocumentCommand \rule ...`?? I think the second one (referenced below) should be removed…
https://github.com/latex3/latex3/blob/de1aa9be2570748b3eb081ce04ad0bf07274e4bc/l3trial/xbox/xbox.dtx#L1541-L1545

**Comment by josephwright** [comment]
I've dropped the first one: it's in the wrong part of the source

**Comment by RuixiZhang42** [comment]
@josephwright But then the remaining one doesn’t have the proper `\hbox:n` wrapped around the now-“naked” `\rule:nnn`…

**Comment by josephwright** [comment]
Sorted now?

**Comment by RuixiZhang42** [comment]
@josephwright Looks good! Thanks.
