### ISSUE TITLE
use ISO 8601 dates

### ISSUE THREAD

**Issue by mark-senn** [latex3/latex3#816]
Please transition to using ISO 8601 (updated version known as ISO 9601)
dates.  ISO 8601 is an international standard---dates are of the form
yyyy-mm-dd.

Or support the current yyyy/mm/dd and yyyy-mm-dd.

Thanks.    Mark Senn <mark@purdue.edu>

**Comment by PhelypeOleinik** [comment]
The LaTeX2e kernel already supports both the old yyyy/mm/dd format and the ISO yyyy-mm-dd format. The changelog entry dates back to 2017:
```latex
2017-03-08  David Carlisle  <latex-bugs@latex-project.org>

       * ltclass.dtx, latexrelease.ins: support yyyy-mm-dd format
       in addition to yyyy/mm/dd
```

So if there are parts of the code that don't understand the ISO format, we probably need to standardise.

What part of the code have you spotted that doesn't support yyyy-mm-dd?

**Comment by mark-senn** [comment]
I've only noticed the yyyy/mm/dd format, so I assumed yyyy-mm-dd didn't 
work.
Sorry for bothering you.
You may want to transition to yyyy-mm-dd dates since they have an ISO 
standard.
Thanks for your reply.
-mark

**Comment by FrankMittelbach** [comment]
Personally I prefer the old LaTeX notation in places like \changes entries or \ProvidesPackage as I find it more readable in those places, but you are right, the yyyy-mm-dd is an ISO standard and we therefore support it for a long time in parallel to the old notation (expl3 based code kernel usually is using it, 2e code not so often)

**Comment by PhelypeOleinik** [comment]
> I've only noticed the yyyy/mm/dd format

Yeah, there are many places in the sources that we still use `yyyy/mm/dd` (which I also kinda prefer, even though it is not ISO) simple because they weren't changed yet, but both format should be usable interchangeably.

I'll close this here, but if you find somewhere that `yyyy-mm-dd` doesn't work, please report.
