### ISSUE TITLE
xparse regex argument specifier

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#820]
With the addition of `\peek_regex_replace_once:nnTF` to l3regex in #779, it becomes rather easy to implement an all-encompassing argument type in xparse that would cover various additions that people asked throughout the years (e.g., grabbing any number of `+` or `*` tokens, grabbing digits, or whatever).  Something like

    \NewDocumentCommand { \rating }
      { x{[A-Fa-f]} x{\+*|\-*} }
      { \texttt{#1}\textsuperscript{#2} }
    \rating A+++
    \rating F-

would print A^{+++} and F^-.  Just as for other argument types there could be an argument type `X` with a default value for when the argument is not found.

**Comment by u-fischer** [comment]
But I guess that one can't do this in an expandable way, and that writing an expandable version that does something more or less sensible e.g. for such a in the bookmarks would be difficult to impossible?  (That doesn't mean that one shouldn't write such commands,  only that it should be documented/discussed how argument types behave in different contexts).

**Comment by josephwright** [comment]
Yes, non-expandable only, but that's no different to trailing-optional or verbatim or whatever.

**Comment by eg9** [comment]
It would be a very nice addition, indeed. I'd not worry about expandability. Parsing expandably has to use different tools anyway.

**Comment by josephwright** [comment]
I've merged the `expl3` support, so we should be good to go here.

**Comment by blefloch** [comment]
In which files should new argument types be documented?

**Comment by josephwright** [comment]
I think new stuff should go into `usrguide3`, as it will be added to the part of `xparse` that will move 'finally' across in the near future.

**Comment by blefloch** [comment]
Where is usrguide3?  Probably in some branch somewhere, but I cannot find it.

**Comment by FrankMittelbach** [comment]
In the latex2e repository (but probably only in master at the moment - not checked) with the next PL there (hopefully in a few of days when @PhelypeOleinik has recovered from thesis stress) it should appear in "develop" there.

**Comment by josephwright** [comment]
It's in https://github.com/latex3/latex2e/tree/hotfix/gh448, which is as-yet not merged to master or to develop. (Ideally each hotfix should get merged across to develop as well as master, but I suspect we are going to bulk-merge master back to develop.)

**Comment by FrankMittelbach** [comment]
given that there are always merge conflicts because of the date and version changes (and we seldom have several hotfixes at the same time) doing a bulk merge back to develop when the PL is ready seems more sensible to me.

**Comment by blefloch** [comment]
Thanks all, I'll wait until all is settled down a bit more before starting on
this xparse issue.  There is no rush at all.

**Comment by josephwright** [comment]
I've re-reported at https://github.com/latex3/latex2e/issues/1065 in the 2e format and without the discussion of the underlying `expl3` code.
