### ISSUE TITLE
ltx.utils.filedump and \file_hex_dump:nnn index from different values

### ISSUE THREAD

**Issue by josephwright** [latex3/latex3#825]
As raised in https://chat.stackexchange.com/transcript/message/56254361#56254361, the following gives no output for the TeX-level case
```latex
\documentclass{article}

\begin{document}
\ExplSyntaxOn
\lua_now:e{
  tex.sprint(ltx.utils.filedump( "\lua_escape:e{\c_sys_jobname_str.tex}", 0, 8 ))
}
\par
% (empty)
\file_hex_dump:nnn{\c_sys_jobname_str.tex}{0}{8}
\ExplSyntaxOff
\end{document}
```

That happens as we deliberately filter out the index-from-zero situation in the TeX code for LuaTeX. But that seems inconsistent both with the Lua interface and with the pdfTeX version (which returns the same result for both starting a 0 and at 1). As we are emulating the latter, I think we need to adjust the Lua and the TeX code:

- Index from 1
- Allow 0 as functionally-equivalent to zero

**Comment by agrahn** [comment]
Also, the meaning of the second argument is different from `pdftex` and `luatex`. There, it is the number of bytes to be read starting from offset, not an absolute index into the file.

**Comment by zauguin** [comment]
> As we are emulating the latter, I think we need to adjust the Lua and the TeX code:
> 
>     * Index from 1

For the Lua interface, we are emulating the \pdffiledump primitive and not file_hex_dump and therefore IMO the 0 based index/length instead of end offset makes sense. We can change it, but then we should also change the function name to indicate that it no longer is equivalent to \pdffiledump.

> 
>     * Allow 0 as functionally-equivalent to zero

Or maybe go the other way and error on 0 in the both the pdfTeX and LuaTeX versions (or at least warn about it)? Passing zero to a 1 based index feels like a bug to me and accepting it silently might only lead to trouble when code changes later and starts using other offsets.

**Comment by davidcarlisle** [comment]
I can't see any reason to make 0 and 1 work the same way? 

for offset +length you want 0 to be the first reasonable value, for star index + end index 1 is the first reasonable value. In both cases you are indexing the bytes starting at 1.

**Comment by josephwright** [comment]
OK, so the 'issue' here is that we need to be clearer in the docs that the `expl3` interface is not the same as the Lua one, as they start from different requirements? (Matching the rest of `expl3` vs matching the pdfTeX primitive)

**Comment by josephwright** [comment]
As in the interface does work as
```latex
\documentclass{article}

\begin{document}
\ExplSyntaxOn
\lua_now:e{
  tex.sprint(ltx.utils.filedump( "\lua_escape:e{\c_sys_jobname_str.tex}",0, 8 ))
}
\par
% doesn't (empty)
\file_hex_dump:nnn{\c_sys_jobname_str.tex}{1}{8}
\ExplSyntaxOff
\end{document}
```

**Comment by josephwright** [comment]
I'd clearly got things wrong here: closing.
