### ISSUE TITLE
Can `l3doc` be customized as a documentation-tool for various programming languages?

### ISSUE THREAD

**Issue by NiranjanTambe** [latex3/latex3#827]
`.dtx`, `.ins` pair is very commonly used to document LaTeX packages, but can it be extended to document codes written in different languages? It would be something like if somebody wants to document a python code, they can declare `\ProgrammingLanguage{python}` in the beginning of the document (we can keep this only for languages other than LaTeX, so that the present codes which don't have this macro will not be disturbed) and then various things will be automatically changed like the comment character in the output will be `#` with the input `%%` and things like that. We can have a separate (`.lbx`?) folder for programming language definitions and contributors can contribute for the programming language of their choice. Is this workable?

**Comment by Skillmon** [comment]
The docstrip utility as such could indeed be used for this, but I'd not start with the `l3doc` class here, as that one is pretty much narrowed down in scope to describe LaTeX code. Since the things inbetween `\begin{macrocode}...\end{macrocode}` blocks are treated verbatim, you don't have to change the comment char at all, and for the `%` at the start of lines in your documentation blocks, they should stay (`docstrip` likes them, and there is no strong reason to change that).

**Comment by NiranjanTambe** [comment]
> The docstrip utility as such could indeed be used for this, but I'd not start with the l3doc class here, as that one is pretty much narrowed down in scope to describe LaTeX code.

So do you mean this issue should be reported on another repo? If yes which?

> Since the things inbetween \begin{macrocode}...\end{macrocode} blocks are treated verbatim, you don't have to change the comment char at all.

Okay.

> For the % at the start of lines in your documentation blocks, they should stay (docstrip likes them, and there is no strong reason to change that).

Yes, I also don't think it should be changed.

**Comment by FrankMittelbach** [comment]
The `doc`package was one of my first LaTeX packages ever (together with `array` I guess) and back then I wanted to have something that works in out of the box in LaTeX (interpreted as code with all the documentation ignored -- which explains why the documentation was hidden behind `%`).  But back then computers were slow so we soon came up with the `docstrip` program as a comanion to  remove the comment lines and also allow for rearranging the code by collecting pieces and writing them into different files.

If I would redo  this today I would probably do things quite differently as it is somewhat painful to beforced to ensure that 

    %    \end{macrocode}

 as exactly four spaces. But given that it is by now a defacto standard in the LaTeX world, there is not much incentive in inventing something new (people have tried and nothing caught on).

Anyway, in the combination of `doc`and `docstrip` you really have everything available to document your python code (or anything else).  All you have to do is to use docstrip guards as needed inside  the `macrocode`  environments and then write a `.ins` file that combines the fragment in your target file (or files). Of course, some parts of the process are quite TeX specific, e.g., the macrocode environment is scanned for macro names to make an index and that will make little sense with other code.

But I can tell you up front that I will not have the bandwidth to generalize the mechansim to support scanning other languages and doing this kind of automation in the background.  S o no there will be no `\ProgramLanguage` interface in the forseeable future if if it could be an interesting project.
