### ISSUE TITLE
l3strconvert: additional escaping method for urls needed?

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex3#838]
The url escaping method of `\str_set_convert:Nnnn` can't be used to create working url as it percents encoding too much:

## Digits

digits are percent encoded:

~~~~
\documentclass{article}
\begin{document}
\ExplSyntaxOn
\str_set_convert:Nnnn \l_tmpa_str
 {example123.org}
 {utf8}{utf8/url}
\str_show:N \l_tmpa_str
\ExplSyntaxOff
\end{document}
~~~~

~~~~
\l_tmpa_str=example%31%32%33.org.
~~~~

Imho this is simply wrong, digits are not reserved chars in an URI and don't think that there is a reason to percent encode them.

## Reserved chars

Reserved chars in an URI are `: / ? # [ ] @ ! $ & ' ( ) * + , ; =` 

Currently the url escaping percent encodes all reserved chars. It also percent encodes the percent symbol itself

~~~~
\documentclass{article}
\begin{document}
\ExplSyntaxOn
\exp_args:NNx
\str_set_convert:Nnnn \l_tmpa_str
 {\c_percent_str20xxxxx:/?\c_hash_str[]@!$&'()*+,;=}
 {utf8}{utf8/url}
\str_show:N \l_tmpa_str
\ExplSyntaxOff
\end{document}
~~~~

~~~~
\l_tmpa_str=%25%32%30xxxxx%3A%2F%3F%23%5B%5D%40%21%24%26%27%28%29%2A%2B%2C%3B%3D.
~~~~

This is fine if one wants to encode some value or parameter, but not to create URI's with perhaps non-ascii chars. There one need an escaping method which percent encodes only the range >127.

**Comment by josephwright** [comment]
Looks like a bug to me, but I'd welcome @blefloch's take

**Comment by blefloch** [comment]
On 2/24/21 6:19 PM, Joseph Wright wrote:
> Looks like a bug to me, but I'd welcome @blefloch
> <https://github.com/blefloch>'s take

No idea, sorry.  I probably picked a list from somewhere and went with it.  It
should be easy to change that in the code, although I don't remember any of it
so anyone else can do this as well as I can.

**Comment by car222222** [comment]
@u-fischer "There one need an escaping method which percent encodes only the range >127."

Please can you post a link to the standard for URI escaping?  Thanks.

As Bruno said, I (even I!)could probably do this recoding!

(I could add the utf-8 BOM (signature) encoding too.)

**Comment by car222222** [comment]
I found this advice (but it is not from any kind of standard):

1.  If you are building a URI programmatically, you must encode each component individually before composing them.

2.  Escape the following characters: 
space !”#$%&'()*+,/:;<=>?@[\]^`{|} 
and U+0000 — U+001F and U+007F and greater.

3.  Do not escape ASCII alphanumeric characters or -._~ (although it doesn’t matter if you do).

(4.  If you have specific knowledge about how the component will be used, you can relax the encoding of certain characters (for example, in a query, you may leave ‘?’ bare; in a “javascript:” URI, you may leave all sub-delims bare). Bear in mind that this could impact the equivalence of URIs.)

**Comment by car222222** [comment]
And from the RFC (3986) here:
https://tools.ietf.org/html/rfc3986

There is a summary of the use and interpretation of escaping:

1.  URI producing applications should percent-encode data 
octets that correspond to characters in the reserved set unless 
these characters are specifically allowed by the URI scheme to 
represent data in that component.  

2.  If a reserved character is found in a URI component and no delimiting role is known for that character, then it must be
interpreted as representing the data octet corresponding to that
character's encoding in US-ASCII.

**Comment by zauguin** [comment]
> Please can you post a link to the standard for URI escaping? Thanks.

There isn't "the" standard for URI encoding. There is [RFC3986](https://tools.ietf.org/html/rfc3986) specifying URIs stating

> Under normal circumstances, the only time when octets within a URI
   are percent-encoded is during the process of producing the URI from
   its component parts.  [...] **Once produced, a URI is always
   in its percent-encoded form.**

Since we already have a URI here and do no try to build it from component parts, the URI should already be encoded. Of course this isn't really what we want here. We want to accept every input which can be parsed as a URI by common applications. So more helpful is probably the [URL (sic!) "Standard"](https://url.spec.whatwg.org/) from WHATWG. According to that what we need is basically parsing followed by serializing. But practically we can restrict ourselfes to what they call "running UTF-8 percent-encode using the C0 control percent-encode set".

**Comment by car222222** [comment]
@u-fischer wrote:
Reserved chars in a URI are:  
   : / ? # [ ] @ ! $ & ' ( ) * + , ; =

RFC3986 subdivides this list as:
  gen-delims:  : / ? # [ ] @
  sub-delims:  ! $ & ' ( ) * + , ; =

 The reserved characters under 'gen-delims' are those used as
   delimiters of the generic URI components.

These ASCII symbol characters are not reserved:  - . _ ~

**Comment by car222222** [comment]
@zauguin "Since we already have a URI here and do no try to build it from component parts"

OK. 

"the URI should already be encoded"

Should be, yes!  

But can we assume this and so not use any string conversion at all?

**Comment by zauguin** [comment]
> But can we assume this and so not use any string conversion at all?

We can't, that was kind of my point. The WHATWG standard I was talking about is dealing with the handling of such URL's which don't strictly correspond to traditional URI syntax rules.

**Comment by car222222** [comment]
In that case this is perhaps not a straight conversion task?  As we do not know exactly how the input is encoded.

But anyway, we need a standard for what to (try to) convert it to.

**Comment by u-fischer** [comment]
> "the URI should already be encoded"
> 
> Should be, yes!
> 
> But can we assume this and so not use any string conversion at all?

No. I have to assume that I get something like this as input

      http://ja.wikipedia.org/wiki/エリザベス1世_(イングランド女王

and need to get out 

    http://ja.wikipedia.org/wiki/%E3%82%A8%E3%83%AA%E3%82%B6%E3%83%99%E3%82%B91%E4%B8%96_\(%E3%82%A4%E3%83%B3%E3%82%B0%E3%83%A9%E3%83%B3%E3%83%89%E5%A5%B3%E7%8E%8B

Currently I'm using the following which give the results I want, but is only kind of inefficient as it first percent encodes lots of chars only to revert this again:

~~~~
% special url command:
\cs_new_protected:cpx { @@_string_from_unicode_utf8/URI-raw:nN }  #1 #2
  {
     \exp_not:N \str_set_convert:Nnnn #2
       { #1 }
       { default }
       {utf8/url}
     \exp_not:N \str_replace_all:Nnn #2 {\c_percent_str 3A} {:}
     \exp_not:N \str_replace_all:Nnn #2 {\c_percent_str 2F} {/}
     \exp_not:N \str_replace_all:Nnn #2 {\c_percent_str 23} {\c_hash_str}
     \exp_not:N \str_replace_all:Nnn #2 {\c_percent_str 5B} {[}
     \exp_not:N \str_replace_all:Nnn #2 {\c_percent_str 5D} {]}
     \exp_not:N \str_replace_all:Nnn #2 {\c_percent_str 40} {\c_atsign_str}
     \exp_not:N \str_replace_all:Nnn #2 {\c_percent_str 21} {!}
     \exp_not:N \str_replace_all:Nnn #2 {\c_percent_str 24} {\c_dollar_str}
     \exp_not:N \str_replace_all:Nnn #2 {\c_percent_str 26} {\c_ampersand_str}
     \exp_not:N \str_replace_all:Nnn #2 {\c_percent_str 27} {'}
     \exp_not:N \str_replace_all:Nnn #2 {\c_percent_str 2A} {*}
     \exp_not:N \str_replace_all:Nnn #2 {\c_percent_str 2B} {+}
     \exp_not:N \str_replace_all:Nnn #2 {\c_percent_str 2C} {,}
     \exp_not:N \str_replace_all:Nnn #2 {\c_percent_str 3B} {;}
     \exp_not:N \str_replace_all:Nnn #2 {\c_percent_str 3D} {=}
     \exp_not:N \str_replace_all:Nnn #2 {\c_percent_str 30} {0}
     \exp_not:N \str_replace_all:Nnn #2 {\c_percent_str 31} {1}
     \exp_not:N \str_replace_all:Nnn #2 {\c_percent_str 32} {2}
     \exp_not:N \str_replace_all:Nnn #2 {\c_percent_str 33} {3}
     \exp_not:N \str_replace_all:Nnn #2 {\c_percent_str 34} {4}
     \exp_not:N \str_replace_all:Nnn #2 {\c_percent_str 35} {5}
     \exp_not:N \str_replace_all:Nnn #2 {\c_percent_str 36} {6}
     \exp_not:N \str_replace_all:Nnn #2 {\c_percent_str 37} {7}
     \exp_not:N \str_replace_all:Nnn #2 {\c_percent_str 38} {8}
     \exp_not:N \str_replace_all:Nnn #2 {\c_percent_str 39} {9}
     \exp_not:N \str_replace_all:Nnn #2 {\c_percent_str 28} {\c_backslash_str(}
     \exp_not:N \str_replace_all:Nnn #2 {\c_percent_str 29} {\c_backslash_str)}
  }
~~~~

**Comment by josephwright** [comment]
The code change here is pretty trivial: what we need is to be clear what the spec is. I think (@blefloch) that the code has to work 'both ways' - the same test is used to 'unescape' input, which is likely linked to what we are seeing here. We could either adjust `\__str_if_escape_url:n(TF)` to some improved spec *or* have a new escape method that is perhaps clearer about only touching some chars.

**Comment by josephwright** [comment]
@u-fischer In your Japanese URL example, you say 'only high chars' but also  change `_(` to `_\(` - could you comment?

**Comment by u-fischer** [comment]
@josephwright The url is used in a pdf string, so I have to escape the `(`. But this could  be separated.

**Comment by josephwright** [comment]
> @josephwright The url is used in a pdf string, so I have to escape the `(`. But this could be separated.

Ah, right: so you could live with just
```latex
\prg_set_conditional:Npnn \__str_if_escape_url:n #1 { TF }
  {
    \if_int_compare:w `#1 > "7E \exp_stop_f:
      \prg_return_false:
    \else:
      \prg_return_true:
    \fi:
  }
```
or some new 'URL-like' scheme which did that.

**Comment by u-fischer** [comment]
Actually I think only "above 127" is not want I meant, at least space (%20) and percent (%25) need encoding too.  Is there anywhere a list which chars the url scheme currently percent encodes?

**Comment by josephwright** [comment]
@u-fischer  Only in the code I think
```latex
\prg_new_conditional:Npnn \@@_if_escape_url:n #1 { TF }
  {
    \if_int_compare:w `#1 < "41 \exp_stop_f:
      \@@_if_contains_char:nnTF { "-.<> } {#1}
        \prg_return_true: \prg_return_false:
    \else:
      \if_int_compare:w `#1 > "7E \exp_stop_f:
        \prg_return_false:
      \else:
        \@@_if_contains_char:nnTF { [ ] } {#1}
          \prg_return_false: \prg_return_true:
      \fi:
    \fi:
  }
```
Everything leading to `\prg_return_false:` gets escaped. (And no, I don't understand why that is the _false_ branch either.)

**Comment by car222222** [comment]
The bytes above "7F are clear, they all need escaping.

Less clear is how to treat the reserved characters (of both types): what guidelines do we use for which of these we escape, and is this context dependent?  

Marcel described this process in general and gave a reference to some pragmatic guidance.

Ulrike is, I think, suggesting not to scape any of them . . . except maybe some, such as (   And  ) ? 

I am asking about all of them!

**Comment by josephwright** [comment]
> The bytes above "7F are clear, they all need escaping.
> 
> Less clear is how to treat the reserved characters (of both types): what guidelines do we use for which of these we escape, and is this context dependent?

Agreed.

> Marcel described this process in general and gave a reference to some pragmatic guidance.
> 
> Ulrike is, I think, suggesting not to scape any of them . . . except maybe some, such as ( And ) ?

I think `(`/`)` were an 'artefact' of her use case - not directly relevant here.

**Comment by car222222** [comment]
My interpretation of the code Joseph posted is as follows:

The only non-escaped bytes will be these 13:
" - . < >
\ ^ _ `
{ | } ~

Thus all these 19 bytes (the reserved characters and <space>) will be escaped:
<space>
: / ? # [ ] @ ! $ & ' ( ) * + , ; =

But it will also escape the 10 digits: this seems wrong to me! 

% is a special case as it should never appear as itself in a URI.  Thus if we want to deal with it in the 'input url' then we could do one of the following:
1.  Leave it, which is correct if it is used legally in the input, as the escape character (and "illegal in gives illegal out");
2.  Check the next two bytes and error if they are not 'hex digits'.

**Comment by u-fischer** [comment]
> But it will also escape the 10 digits: this seems wrong to me!

Well sure, that is what this issue is about isn't it? The current code is wrong.

**Comment by car222222** [comment]
Sure it is.  I had not realised the code was that wrong!   

But if we just fix the digits, will it be OK?

**Comment by u-fischer** [comment]
> But if we just fix the digits, will it be OK?

As my issue says: the digits are completly wrong, and the handling of the reserved chars are wrong for my use case.

**Comment by car222222** [comment]
OK, so we must, and can easily, fix the digits.  But what distinct use-cases are there for the reserved chars (both subgroups)?

**Comment by car222222** [comment]
Here is my attempt at code to fix the digits.

The method of dealing with these 5 chars  : ; = ? @  may not be the most efficient, but heh! 

```
\prg_new_conditional:Npnn \@@_if_escape_url:n #1 { TF }
  {
    \if_int_compare:w `#1 < "30 \exp_stop_f:
      \@@_if_contains_char:nnTF { "-.} {#1}
        \prg_return_true: \prg_return_false:
    \else:
      \if_int_compare:w `#1 > "7E \exp_stop_f:
        \prg_return_false:
      \else:
        \@@_if_contains_char:nnTF 
          { : ; = ? @ [ ] } {#1}
              \prg_return_false: \prg_return_true:
      \fi:
    \fi:
  }
```

**Comment by josephwright** [comment]
> Here is my attempt at code to fix the digits.
> 
> The method of dealing with these 5 chars : ; = ? @ may not be the most efficient, but heh!
> 
> ```
> \prg_new_conditional:Npnn \@@_if_escape_url:n #1 { TF }
>   {
>     \if_int_compare:w `#1 < "30 \exp_stop_f:
>       \@@_if_contains_char:nnTF { "-.} {#1}
>         \prg_return_true: \prg_return_false:
>     \else:
>       \if_int_compare:w `#1 > "7E \exp_stop_f:
>         \prg_return_false:
>       \else:
>         \@@_if_contains_char:nnTF 
>           { : ; = ? @ [ ] } {#1}
>               \prg_return_false: \prg_return_true:
>       \fi:
>     \fi:
>   }
> ```

Certainly works: looks pretty reasonable to me :)

**Comment by car222222** [comment]
To simply pass through all %s, add it here, thus:

```
\@@_if_contains_char:nnTF { " % - .} 
```
