### ISSUE TITLE
xparse in tabular breaks if argument contains &

### ISSUE THREAD

**Issue by PhelypeOleinik** [latex3/latex3#839]
Reported here: https://tex.stackexchange.com/q/578546/134574

`xparse`-defined environments and commands that grab delimited arguments (`D` and its special cases) break in tabular environments if the argument contains an alignment tab token:
```latex
\documentclass{article}
% \usepackage{array}
\NewDocumentCommand\MyEnv{O{x}}
  {$\begin{array}{|cc|}#1\end{array}$}

\begin{document}
\begin{tabular}{c}
  \MyEnv % works
  \MyEnv[x] % works
  \MyEnv[x&y] % breaks
\end{tabular}
\end{document}
```

(it breaks with a different error, depending if `array` is loaded or not).

**Comment by josephwright** [comment]
As we have an open PR to merge most of `xparse` into LaTeX2e, I suspect the issue should be fixed there

**Comment by josephwright** [comment]
https://github.com/latex3/latex2e/pull/446 - if we fix here we should (probably) also adjust there

**Comment by PhelypeOleinik** [comment]
But there will be `l3kernel` releases before the next 2e release (won't it?), so I guess meanwhile fix here and add the fix there (or the other way around).  Seems sensible?

**Comment by josephwright** [comment]
@PhelypeOleinik  `l3packages` but yes I do see that: like I say, probably adjust in both places, perhaps getting the PR merged at the same time
