### ISSUE TITLE
l3doc: commands and environments to document "things without backslashs" like keys

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex3#843]
There is a growing need to document and index other things than commands, for example key names, hook names, PDF dictionaries, color model names, color export format names and similar.  l3doc is missing here suitable environments and commands to properly format and index these.

**Comment by FrankMittelbach** [comment]
something like

https://github.com/FrankMittelbach/fmitex/tree/master/doc-v3

you mean? This is more a doc package question than l3doc class I would say.

**Comment by josephwright** [comment]
One for https://github.com/latex3/latex3/issues/1136
