### ISSUE TITLE
extractbb dependency

### ISSUE THREAD

**Issue by vadimkantorov** [latex3/latex3#850]
I have build XeTeX under WebAssembly/emscripten. I've tried to rebuild with recent texmf, and I found that it now fails because `extractbb` is not available there and it appears in `l3backend-xetex.def` (http://www.tug.org/texlive//devsrc/Master/texmf-dist/tex/latex/l3backend/l3backend-xetex.def).

This is a problem for architectures where calling external processes is not possible.

for reference, my compiler using older texmf is at https://busytex.github.io

**Comment by josephwright** [comment]
`extractbb` is the same binary as `dvipdfmx`, which is essential for the XeTeX workflow. So I'm not sure why you don't have it available! It's also vital for including image files with `dvipdfmx`-based workflows using pdfTeX. So not having it sounds like (essentially) a broken TeX system.

**Comment by vadimkantorov** [comment]
I'm building my own (very restricted set of) TeX binaries (and have definitely not built `extractbb` before). I'm compiling a very simple document: https://github.com/busytex/busytex/blob/main/example/example.tex, so it should not require any bounding box calculations (?). 

Is Latex3 now used by default when installing tex packages via `tl-install`?

**Comment by vadimkantorov** [comment]
It seems that the new job uses patch level 4, while the previous one used patch level 2. Not sure what's changed or how's this controlled... Both TDS were build using `install-tl`

**Comment by zauguin** [comment]
> Not sure what's changed or how's this controlled...

The change is that LaTeX tries to determine the used version of xdvipdfmx. It already deals with the case that shell escape might be disabled, but your version of XeTeX claims to allow shell escape (the second line of the log claims `  restricted \write18 enabled.`) but then doesn't make xdvipdfmx (or at least it's alias `extractbb`) available. So you will either have to disable shell escape officially or you have to make `extractbb` available (which should be possible since you already claim to include `xdvipdfmx`)

**Comment by vadimkantorov** [comment]
I include `xdvipdfmx`, but I don't have process-calling functions in WebAssembly, the user is expected to manually call all needed binaries

Is shell escape enabled by default? I don't have `-shell-escape` in my arguments.

**Comment by josephwright** [comment]
> Is shell escape enabled by default? I don't have `-shell-escape` in my arguments.

Restricted shell escape is enabled: it allows a limited number of 'safe' binaries to be called, which include `extractbb`.

**Comment by vadimkantorov** [comment]
Should I use `-no-shell-escape`? Currently I have `$BUSYXETEX xetex --interaction nonstopmode --halt-on-error --no-pdf --fmt $XETEXFMT example.tex`

**Comment by vadimkantorov** [comment]
Yep, `--no-shell-escape` seems to work. Thanks for advice! If you're interested in chatting about learnings from compiling pdftex/xetex/luatex for WebAssembly, feel free to ping me!
