### ISSUE TITLE
Suggestion : \int_succ:N and \int_pred:N

### ISSUE THREAD

**Issue by fpantigny** [latex3/latex3#852]
I think that it will be useful to have two commands `\int_succ:N` and `\int_pred:N` which would take in as argument the name of a counter (eg. `\l_tmpa_int`) and give, in an expandable way, the value of that counter increased by 1 or −1.

**Comment by josephwright** [comment]
That's just `\int_eval:n { \l_tmpa_int - 1 }` or the oppose, no?

**Comment by fpantigny** [comment]
Yes but I use that very often in my packages. I think it would be shorter to write (and read) and a bit quicker...

**Comment by josephwright** [comment]
Any views from anyone here?

**Comment by davidcarlisle** [comment]
I don't necessarily object but I'd be interested to see the use case. I can see that incrementing a counter is a common activity (`\stepcounter` essentially) but returning a counter+1 expendably without resetting the counter seems a rather specialised activity?

**Comment by u-fischer** [comment]
I'm not sure about the use case either. Typically when I have to do such a calculation, I'm inside an argument that accepts an integer expression, and then `\l_tmpa_int + 1` simply works and is even more readable.  I'm also not really happy with the names.

**Comment by PhelypeOleinik** [comment]
> `\l_tmpa_int + 1` simply works and is even more readable

And slightly faster because it's one fewer layer if `\number \numexpr ... \relax`

**Comment by fpantigny** [comment]
For information, `succ` and `prec` exist in Caml Light (and also `incr` and `decr`). `incr` and `decr` are on the side of imperative programmation whereas `succ` and `prec` are on the side of functionnal programmation.

In my extension `nicematrix`, I have rows and columns for the arrays and PGF/Tikz nodes for the cells, the potential position of the rules, etc.

I often use constructions such as:

    \pgfcoordinate 
      { \@@_env: - row - \int_eval:n { \l_tmpa_int + 1} - base } 
      { \pgfpoint \c_zero_dim { 0.5 \arrayrulewidth } }

`\l_tmpa_int` is the number of a row, but I need to access the position of the rule before and also the position of the rule after that row (hence the `\l_tmpa_int_ + 1`).

I have written my own control sequence `\@@_incr:n` and it is used 40 times in `nicematrix.sty`.

A similar control sequence is also used in my package `witharrows`. That 's not surprising since it also deals with PGF/Tikz nodes in `\halign`.

**Comment by eg9** [comment]
@fpantigny Nothing prevents you from defining your own function for this purpose

```
\cs_new:Nn \fpantigny_int_succ:n { \int_eval:n { #1 + 1 } }
```
which also works if you use an _integer expression_ instead of a register. It's true that the kernel has `\int_use:N`, but it's very rarely used and `\int_eval:n` is perhaps just a bit less efficient.

So, if we ever add something like that, it would probably be `\int_succ:n` and not `\int_succ:N`, the former accepting an _integer expression_ as argument.

**Comment by blefloch** [comment]
Given the use case I would simply define

\cs_new:Npn \@@_coord_next_base:N #1
  { \@@_env: - row - \int_eval:n { #1 + 1 } - base }

or similar, then do

\pgfcoordinate { \@@_coord_next_base:N \l_tmpa_int }
  { \pgfpoint \c_zero_dim { 0.5 \arrayrulewidth } }

or even perhaps include the \pgfcoordinate into the private command itself,
depending on what piece of code is used the most.

**Comment by fpantigny** [comment]
Well... I will keep my commands `\@@_succ:N` and `\@@_pred:N`...
