### ISSUE TITLE
xparse no longer accepts log-declarations

### ISSUE THREAD

**Issue by krono** [latex3/latex3#862]
## Brief outline of the bug

The package option `log-declarations` is no longer accepted by `xparse`.
(Maybe a transitional bug?)

```
(/usr/local/texlive/2020/texmf-dist/tex/latex/l3packages/xparse/xparse.sty
(/usr/local/texlive/2020/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/local/texlive/2020/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def))
(/usr/local/texlive/2020/texmf-dist/tex/latex/l3packages/xparse/xparse-2020-10-
01.sty
(/usr/local/texlive/2020/texmf-dist/tex/latex/l3packages/xparse/xparse-generic.
tex)))

! LaTeX Error: Unknown option `log-declarations=false' for package `xparse'.
```
## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\PassOptionsToPackage{log-declarations=false}{xparse}
\RequirePackage{xparse}
\begin{document}
\end{document}
```
## Log file (required) and possibly PDF file  
(note: latexbug says to report to latex3, but apparently, the package moved here.)
[ltxxparsebug.log](https://github.com/latex3/latex2e/files/5943860/ltxxparsebug.log)

**Comment by PhelypeOleinik** [comment]
Transferred here, as this issue is in the side of `xparse.sty`

**Comment by PhelypeOleinik** [comment]
@FrankMittelbach In `expl3` the option is called `log-functions`, rather than `log-declarations`, so the error is correct

**Comment by krono** [comment]
Thanks!
