### ISSUE TITLE
Infinite(?) loop in `L3 programming layer <2021-01-09> xparse <2020-03-03>`

### ISSUE THREAD

**Issue by Janno** [latex3/latex3#868]
The following piece of code was generated by an automated debugging tool. The tool's intention was *not* to fuzz latex but it seems that that is an unintended side effect. In any case, latex doesn't seem to terminate when building a file with this content:

```
\documentclass
\usepackage[left=4cm,right=2cm,top=3,5cm,bottom=2cm,includeheadfoot]{geometry}
```

I am reasonably sure (but cannot currently verify) that this file is easily rejected by a latex version from 2013.

**Comment by FrankMittelbach** [comment]
`\documentclass\usepackage` is enough and yes this is new, but given that TeX is a macro language you can always produce code that generates a tight loop with suitable (or rather unstuiable :-) user input) and there is nothing possible to prevent this.  LaTeX expects a file name as argument to documentclass but it expands macros trying to find it and that goes badly wrong here.

**Comment by blefloch** [comment]
While looking at this issue "for fun", I noticed that `\@expl@@@filehook@set@curr@file@@nNN` includes a call to `\exp_args:Nf`, which strips away one leading space.  This might mess up which hooks are used for files whose name starts with a space.

More seriously, if we want to address this kind of issues, should `\__kernel_file_name_sanitize:n` complain (with an expandable error? something else?) when it hits a non-expandable token that is not a character?  Here it finds an argument `\let \reserved@d =[\def \reserved@a {\@fileswith@ptions \@pkgextension }\def \reserved@b {\@fileswith@ptions \@pkgextension []}\futurelet \@let@token \@ifnch .\@clsextension` that starts with `\let`, and it's pretty clear that this is not a good file name.

**Comment by FrankMittelbach** [comment]
As @PhelypeOleinik is going to changing the implementation of file name parsing back to a simpler form that type of problem might go away as part of it, so I would not look at improving the current version before that has happened. But on the whole I don't think you can ever safely catch such problem (only some): take `\documentclass\@gobble` or similar. The only way to solve everything is to go away from TeX parsing and do all your input parsing manually and that is out of question for speed reasons.

**Comment by PhelypeOleinik** [comment]
@Janno  On the next `l3kernel` release, a document like that will error with a low-level TeX `Missing \endcsname` error followed by an error that shows (or tries to show) the invalid token:
```latex
! Missing \endcsname inserted.
<to be read again> 
                   \let 
l.3 \usepackage{
                geometry}
? 
! Undefined control sequence.
<argument> \LaTeX3 error: 
                           \let invalid in file name. Lost: \reserved@d =[\d...
l.3 \usepackage{
                geometry}
?
```

**Comment by PhelypeOleinik** [comment]
Fixed with PR #869

**Comment by PhelypeOleinik** [comment]
> While looking at this issue "for fun", I noticed that `\@expl@@@filehook@set@curr@file@@nNN` includes a call to `\exp_args:Nf`, which strips away one leading space. This might mess up which hooks are used for files whose name starts with a space.

True, but the filename sanitisation explicitly trims spaces.  We eventually decided that leading and trailing spaces will not be supported.

**Comment by blefloch** [comment]
On 4/20/21 8:31 PM, Phelype Oleinik wrote:
>     While looking at this issue "for fun", I noticed that
>     ***@***.***@@@***@***.***@***@***.***@@nNN| includes a call to |\exp_args:Nf|,
>     which strips away one leading space. This might mess up which hooks are used
>     for files whose name starts with a space.
> 
> True, but the filename sanitisation explicitly trims spaces. We eventually
> decided that leading and trailing spaces will not be supported.

Understood, thanks.
