### ISSUE TITLE
Finding catcode of a character in a cctab from outside

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#880]
While implementing #877 about catcodes produced by `l3regex` I thought of a nice extension, which would be to use some particular catcode table.  The easiest/fastest approach for this would be to have a way to access particular entries in a catcode table without actually running `\cctab_begin:N`.

The key question is whether this is accessible from the Lua side in LuaTeX (alternatively I guess one could switch to the given catcodetable locally, and look up the catcode on the TeX side).  A possible implementation for non-luatex engines is

    \int_compare:nNnTF {#2} < { 256 }
      { \intarray_item:Nn #1 { #2 + 1 } }
      { \char_value_catcode:n {#2} }

**Comment by zauguin** [comment]
> The key question is whether this is accessible from the Lua side in LuaTeX

It is. (`tex.getcatcode (42, 0x4242)` gives the catcode of char U+4242 in table 42)
