### ISSUE TITLE
ISO format for the date: not possible?

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#888]
According to the following lines about `\ProvidesExplPackage {⟨package⟩} {{⟨date⟩} {⟨version⟩} {⟨description⟩}`:

https://github.com/latex3/latex3/blob/f48894e92059aafa0d722353463e8e0deb7f2974/l3kernel/l3bootstrap.dtx#L86-L87

 the `⟨date⟩` cannot be given in the ISO format `⟨year⟩-⟨month⟩-⟨day⟩`. Is it actually the case?

**Comment by PhelypeOleinik** [comment]
The documentation should be fixed.  The arguments to `\ProvidesExplPackage` are eventually passed to `\ProvidesPackage` which uses LaTeX's date parsing which accepts the ISO format since 2018 (I think?).
