### ISSUE TITLE
Provide alternative names for regex functions

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#890]
Currently, all `l3regex` functions start with `\regex` and their first argument is a regex.  This leads to a sometimes quite unnatural order of arguments.  I propose providing additional commands that are centered around the tl, int, or seq that are being manipulated by regex functions.  Specifically, I suggest the following names and implementation.

    \prg_new_protected_conditional:Npnn \tl_if_regex_match:nn #1#2 { TF , T , F }
      { \regex_match:nnTF {#2} {#1} \prg_return_true: \prg_return_false: }
    \cs_new_protected:Npn \int_set_regex_count:Nnn #1#2#3
      { \regex_count:nnN {#3} {#2} #1 }
    \cs_new_protected:Npn \seq_set_regex_extract:Nnn #1#2#3
      { \regex_extract_all:nnN {#3} {#2} #1 }
    \cs_new_protected:Npn \seq_set_regex_split:Nnn #1#2#3
      { \regex_split:nnN {#3} {#2} #1 }
    \cs_new_protected:Npn \tl_regex_replace_once:Nnn #1#2#3
      { \regex_replace_once:nnN {#2} {#3} #1 }
    \cs_new_protected:Npn \tl_regex_replace_all:Nnn #1#2#3
      { \regex_replace_all:nnN {#2} {#3} #1 }

**Comment by blefloch** [comment]
This opens up the possibility of adding `\seq_remove_all_regex_match:Nn \l_my_seq { regex }` (name to be determined) to filter items in a sequence, or `\seq_replace_...` to make replacements on every sequence item.

**Comment by josephwright** [comment]
Adding as alternative names: no deprecation

**Comment by muzimuzhi** [comment]
BTW there are already some `\peek_regex...` functions:
- `\peek_regex:(N|n)TF`
- `\peek_regex_remove_once:(N|n)TF`
- `\peek_regex_remove_once:(N|n)n` and `\peek_regex_remove_once:(N|n)nTF`

**Comment by FrankMittelbach** [comment]
That would fit well into the scheme proposed in my opinion. Do you see this as an issue or just as a remark?
