### ISSUE TITLE
Testing l3doc with l3build

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#897]
A major pain point when developing `l3doc` is the absence of tests, which means we need to compile the whole doc to really test changes.  I'm ready to spend some time writing tests, if someone can help with setting things up: what is the correct `build.lua` incantation to add a very simple test file of basic `l3doc` functionality to our test suite?  I guess some `\showoutput` tests should be enough, even though it is quite brittle.  Alternatively I'd be interested in testing that the `idx`, `ind`, `ilg` files are as expected.

**Comment by blefloch** [comment]
More precise question: I placed a simple `m3doc001.lvt` test file (with the contents below) in `l3kernel/testfiles/` then ran `l3build check -epdftex m3doc001`.  This fails to compile because `calc.sty` is not found.  Of course this is just one of many different packages that `l3doc` loads.  Should I add `calc.sty` and many more packages to our test suite?  If so, where (putting it in `support/` is not enough)?

    \input regression-test
    \START
    \documentclass{l3doc}
    \begin{document}
    \END

**Comment by zauguin** [comment]
> If so, where (putting it in `support/` is not enough)?

`support/` is the right location, but it additionally has to be added to `checksuppfiles` in `build-config.lua` (or overwriten by setting `checksuppfiles` in the corresponding `build.lua`) or order to be picked up.

That being said,



> Of course this is just one of many different packages that `l3doc` loads. Should I add `calc.sty` and many more packages to our test suite?

In my opinion `l3doc` tests should be allowed to use the normal tree for packages, so run with `checksearch = true`. Since typesetting the documentation also has searching enbled that seems like a more realistic and more practical approach. This could be done e.g. by moving the tests into a completely separate directory with an independent `build.lu` or by using different configurations.

If we are doing that, then I can also setup testing the `idx`, `ind`, `ilg` files there.

**Comment by blefloch** [comment]
@zauguin That sounds ideal!  Could you please set up a test file such as the following (which is compiled as `pdflatex test.lvt ; makeindex -s gind.ist test.idx` a few times, or exactly like the doc is compiled, whichever is easiest to get l3build to do), and then arrange to test the log (normalized into a `tlg`, as usual), the `ind`, `idx`, `ilg` files?  There is no rush at all (weeks is ok).
```
\input regression-test.tex
\START
\documentclass{l3doc}
\usepackage{lipsum}
\CodelineIndex
\begin{document}
\begin{function}{\foo}
  \lipsum[1]
\end{function}
\cs{foo} \lipsum[2]
\begin{macro}{\foo}
    \begin{macrocode}
test
\foo \bar
\bar
%    \end{macrocode}
\cs{bar}
\end{macro}
\PrintIndex
\end{document}
```

**Comment by FrankMittelbach** [comment]
> > If so, where (putting it in `support/` is not enough)?
> 
> `support/` is the right location, but it additionally has to be added to `checksuppfiles` in `build-config.lua` (or overwriten by setting `checksuppfiles` in the corresponding `build.lua`) or order to be picked up.

I would suggest to make a `testfiles-l3build` directory and have a `config-l3build.lua`using it and setting up the necessary special test environment.
> 
> That being said,
> 
> > Of course this is just one of many different packages that `l3doc` loads. Should I add `calc.sty` and many more packages to our test suite?
> 
> In my opinion `l3doc` tests should be allowed to use the normal tree for packages, so run with `checksearch = true`. Since typesetting the documentation also has searching enbled that seems like a more realistic and more practical approach. This could be done e.g. by moving the tests into a completely separate directory with an independent `build.lu` or by using different configurations.

agree checksearch=true for that dir and probably just running on pdftex as this is about functionality not the typical small difference in output that luatex tends to show.

> If we are doing that, then I can also setup testing the `idx`, `ind`, `ilg` files there.

sounds good. So you are picking this up @zauguin ? It would certainly be good to have such a set of tests.

**Comment by FrankMittelbach** [comment]
of course I mean config-l3doc

**Comment by zauguin** [comment]
Yes, I'll take care of it.

**Comment by blefloch** [comment]
I think I messed up slightly from Github's point of view when merging @zauguin 's pull request by hand.  Anyway, this is now fixed and I can start adding useful tests progressively once I decide to make changes to `l3doc`.
