### ISSUE TITLE
xparse creates local functions; should it?

### ISSUE THREAD

**Issue by wspr** [latex3/latex3#9]
I'm not sure what the expected behaviour for

```
\group_begin:
  <catcode setup>
  \DeclareDocumentCommand \foo {} {foo}
\group_end:
```

should be. I'd probably expect the default behaviour to create global commands but have a starred version (or something) to create local ones. But I'm not sure really. What do you think?

**Comment by josephwright** [comment]
This very much depends on the management of context changes: may be needed but needs more understanding of higher level issues.

**Comment by blefloch** [comment]
See #333 on pdf bookmarks and other context-awareness of xparse commands.
