### ISSUE TITLE
Add an [sphack] option to \DeclareDocumentCommand

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#90]
Some LaTeX2e commands such as `\label` should be transparent to spaces, i.e., `a \label{...} b` only puts one space between `a` and `b`.  This is done using `\@bsphack` and `\@esphack`, the first storing the space factor and the last skip, and the second restoring it, and ignoring spaces after the `\label` command if there was a skip before.

It would be nice to provide some interface to this in `xparse`, since this package is meant to define document-level commands.  For instance, changing the signature of `\DeclareDocumentCommand` from `mmm` to `mo{}mm`:

```
\DeclareDocumentCommand { \label } [sphack] { m }
  { \protected@write \@auxout { } { \string \newlabel {#1} { { \@currentlabel } { \thepage } } } }
```

**Comment by tail-reversion** [comment]
Personally, it took me awhile to discover that a few commands are zero-width, so I never expected the behavior: I just never put spaces before `\label` &c. (But that’s just my experience.)

However, now that I know about them, I can see that they are of value in a few cases. One example is actually the `\Dash` from the TUGboat class that inserts an em dash with appropriate spacing and breakpoints.

As for labels, I think that those could somehow be integrated into the syntax for document elements, e.g. `\section[label=mysection]{Some Content}`, a little like the `id` attribute in HTML. This would also mean that authors don’t run the risk of putting a label in the wrong place, leading to unexpected reference behavior.

Footnotes and margin notes are another question… If a command is putting content somewhere other than where the command was issued, then, to me, it makes sense that it would be “invisible”, with respect to spacing. But maybe there is a better approach.

**Comment by josephwright** [comment]
I think we close here and if it is useful re-consider in a 2e context.

**Comment by car222222** [comment]
This ancient issue certainly needs to be kept alive, but OK to move it elsewhere!

And please do not lose this very important idea from @tabove, since we now have the basic mechanism to provide, or even enforce, this:

"As for labels, . . . those [should] somehow be integrated into the syntax for document elements, 
e.g. \section[label=mysection]{Some Content}"

**Comment by josephwright** [comment]
> And please do not lose this very important idea (from @tail-reversion) since we now have the basic mechanism to provide, or even enforce, this:
> 
> "As for labels, . . . those [should] somehow be integrated into the syntax for document elements, e.g. \section[label=mysection]{Some Content}"

I think we are all agreed that this is the best plan; it's something that goes with the keyval support for commands, etc.

**Comment by car222222** [comment]
As @josephwright writes: we are all agreed that this is the best plan

How true!  But for long it has lingered as "only a plan"; it really should be actioned rsn, at least in latex-lab or some other experimental location.
