### ISSUE TITLE
Provide more map_tokens functions

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#900]
For various datatypes (`tl`, `seq`, `prop`, `clist`, `str`) we have four types of mapping functions:
- expandable `(type)_map_function:NN`, `(type)_map_tokens:Nn`, which simply differ by the fact that the latter allows for multiple tokens instead of a single function
- protected `(type)_map_inline:Nn` and `(type)_map_variable:NNn`, which differ in how the argument is handed to the code.
In this list, we are actually missing `\clist_map_tokens:Nn` and  `\str_map_tokens:Nn` (and n type versions).

(We also have some `\seq_map_indexed` functions but these are rather specific.)

**Comment by car222222** [comment]
These names are all a bit strange!  

If we can no of better ones then these could be added as synonyms.

Also, this could be a good time to remove from the documentation the unique concept of 'mapping to' a list.  It should be 'mapping over'.

**Comment by blefloch** [comment]
On 5/5/21 11:52 AM, Chris Rowley wrote:
> Also, this could be a good time to remove from the documentation the unique
> concept of 'mapping to' a list. It should be 'mapping over'.

Done.
