### ISSUE TITLE
\msg_term messages don't tell where they are coming from

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#911]
As shown by the following MCE, `\msg_term` messages don't tell where they are coming from (unlike `\msg_warning` messages):
```latex
\begin{filecontents*}[overwrite]{mypackage.sty}
\ProvidesExplPackage
  {mypackage}
  {2021-05-11}
  {0.1}
  {
    My Nice package
  }
\NeedsTeXFormat{LaTeX2e}
%
\msg_new:nnn {mypackage} {Foo} {FOOBAR}
\msg_warning:nn {mypackage} {Foo}
\msg_term:nn {mypackage} {Foo}
\end{filecontents*}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass{article}
\usepackage{mypackage}
\begin{document}
\end{document}
```
writes:
>Package mypackage Warning: FOOBAR
>
>FOOBAR

whereas, for the latter, one could expect:
>Package mypackage Info: FOOBAR

**Comment by blefloch** [comment]
I'm not super familiar with `l3msg`, but I think that this is by design.  If you want an "Info" message it can be obtained using `\msg_info:nn` (but then it goes to the log).

**Comment by dbitouze** [comment]
> `\msg_info:nn` (but then it goes to the log).

That's the point: AFAICT, it is rather common to see in the terminal some Info messages which are perfectly identifiable.

**Comment by FrankMittelbach** [comment]
@josephwright I tend to agree that "info" should be have like "warning" with the difference that it doesn't show on the terminal but not that it logs the stuff differently. For example, warnings are usually formatted with exlicit  linebreaks based on the idea that there is some "(module)" prefix on following lines and when I change a group from warning to info I think all that should change is where it shows up  not how.

**Comment by blefloch** [comment]
Two separate questions are getting a bit mixed up here.

- Formatted messages: currently we have error/warning/info, with the last one
only appearing in the log.  @dbitouze asks for an info message appearing on the
terminal as well.  Maybe he can clarify a concrete case where such a message
should not simply be a warning message?

- Unformatted messages: \msg_log:nn and \msg_term:nn.  I have no opinion on
whether to keep them.

**Comment by dbitouze** [comment]
> @dbitouze asks for an info message appearing on the terminal as well. Maybe he can clarify a concrete case where such a message should not simply be a warning message?

Sometimes you want to inform the user about something but not scare him with a warning.

**Comment by wspr** [comment]
I agree with this — conceptually I think there are two axes to these messages: where they appear, and how severe they are.

Let’s say I have some diagnostic (marginally useful but not useless) output from processing some stuff, and I send it to the log file by default. Showing it on the console might be nice sometimes (a “verbose” user option) but it would be wrong to call these things warnings.

**Comment by FrankMittelbach** [comment]
I sort of second that but I don't think we really want a second axis. errors + warnings should always be reported imho on the terminal + log ,only for info it seems there are really two classes info (log only) and term-info.

Note that having separate axes would help so much anyway, because we normally don't want all infos to suddenly become  term-infos  (which you could anyway by mapping info to term-info) but typically just some infos to also always go to the terminal so I would consider adding a further category `terminfo` and some corresponding `\msg_terminfo:nn` so that you can make your intentions for the default behavior clear in the code without the need to set that somewhat hidden in msg setup.
