### ISSUE TITLE
Balancing regex replacements without error

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#913]
Assume that one performs a regex replacement such as `\tl_set:Nn \l_tmpa_tl { a { b } c } \regex_replace:nnN { a . } { \0 \0 } \l_tmpa_tl`.  This should give an unbalanced token list `a{a{b}c`, so l3regex correctly detects the problem and adds a missing closing brace after complaining.  I think we should have a way to specify that a given regex replacement should be balanced if needed, and a way to test after the fact whether rebalancing was needed.  This could be achieved using three variables:

- `\l_regex_auto_balance_bool` should be set before doing a regex replacement, to indicate that l3regex should rebalance without complaining.  This could also be useful in `\peek_regex_replace` to implement #820 (xparse regex arg type).
- `\l_regex_added_group_begin_int` and `\l_regex_added_group_end_int` holding the number of `{` and `}` that were added to the beginning and end of the last regex replacement.

Better names welcome, but more importantly, is it a good idea to have such customizations in a kernel-level command?

**Comment by josephwright** [comment]
Without a clear use case, always having an error here seems reasonable.
