### ISSUE TITLE
Provide black-and-white version of source3 for printing

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#92]
Marc Van Dongen reports (well, some time ago)

> The document uses colour which doesn't print well on my black and white printer (I just put in a new cartridge). When printed the text is a very pale shade of grey, which is hardly legible.

This should be fixed by providing a print version of `source3.pdf`, in black-and-white, probably not even grayscale.

**Comment by wspr** [comment]
There's a new package which now provides a direct solution

    \usepackage[ocgcolorlinks]{ocgx2}

I'm inclined to use it but I'm kind of on the fence as to whether this is really needed. I guess if it were part of hyperref we'd just do it :)

Any objections?

**Comment by FrankMittelbach** [comment]
@wspr @josephwright some do for sure, but I would not add a dependency to a new package just for that.

**Comment by wspr** [comment]
@FrankMittelbach — that's a clear position. People can always typeset their own customised copy if they want B+W. No need to keep this open further.

**Comment by FrankMittelbach** [comment]
@wspr not sure it is just my printer driver being so clever, but I can simply tell it to print black-white rather than color or gray scale
