### ISSUE TITLE
l3regex: get the positions of all matches?

### ISSUE THREAD

**Issue by lvjr** [latex3/latex3#921]
In my package [ `codehigh`](https://ctan.org/pkg/codehigh) I use `l3regex` to parse and highlight code.  At this moment it's rather slow and I'm thinking on some ways to improve it. If I know the positions of all matches, I would make my code run faster. Could `l3regex` provide some functions for this? It's better if I could get both of the substrings and positions of all matches with one function call.

**Comment by blefloch** [comment]
Is your code running regexes only on strings (namely catcode 12, except spaces, of catcode 10)?  Maybe this could be used to speed up some parts of `l3regex`, I haven't thought much about it.

I'll provide positions of all matches as a global variable updated by every regex operation.  Is it better to give it as an `intarray` or as a `seq`?

**Comment by blefloch** [comment]
Concretely, the `seq` version would have one item per match.  Each item would take the form `{start_0}{end_0}{start_1}{end_1}...{start_n}{end_n}` where `{start_i}` and `{end_i}` denote the starting and ending positions of the i-th submatch (so the 0-th submatch is the full match).

How will you use the positions?  It can be a bit tricky to extract submatches given only their positions, unless your token list consists only of N-type tokens (no spaces, no brace groups).

**Comment by lvjr** [comment]
My package is running regexes on strings, but still it need more than 10 seconds to highlight one page of source code. Hope it will be much faster with a new algorithm based on the new l3regex variable. Either `intarray` or `seq` is OK for me, if I can also know the total number of matches.

**Comment by lvjr** [comment]
There are some rules for a language, The package will compare the regex positions to find out which rule wins. Then split the string into `substring before` + `match substring` + `substring after`, highlight `substring before` and `match substring`. Next it will continue with `subtring after` and compare positons again.

The package would run faster if `l3regex` could give match positions and split the string at one function call, maybe a `seq` of `substr0, match1, substr1, match2, substr2, ..., matchN, substrN`. In fact, it's an improved version of current `\regex_split` function.

**Comment by blefloch** [comment]
Ah, so you basically want to know which of multiple regexes matches first?  Please take a look at issue #433, asking for `\regex_case_match:nnTF` and more, which I've started working on.  Precise documentation:

https://github.com/latex3/latex3/blob/45836eb266afb362375fd34643cc1a5c97416ebc/l3kernel/l3regex.dtx#L613-L648

I guess this would avoid you needing to know positions of matches?

**Comment by blefloch** [comment]
Something like (with the not-yet-available `\regex_case_replace_all:nN`)

    \cs_new_protected:Npn \@@_other:w #1 \s_@@ { \textcolor{gray}{#1} }
    \cs_new_eq:NN \@@_digit:n \textbf
    \cs_new_eq:NN \@@_identifier:n \textit
    \tl_set:Nn \l_@@_body_tl { var2 + 12 }
    \regex_case_replace_all:nN
      {
        { \d+ } { \c{s_@@} \c{@@_digit:n} { \0 } \c{@@_other:w} }
        { \w+ } { \c{s_@@} \c{@@_identifier:n} { \0 } \c{@@_other:w} }
      }
      \l_@@_body_tl
    \exp_after:wN \@@_other:w \l_@@_body_tl \s_@@

would give `\textit{var2} \textcolor{gray}{+} \textbf{123} \textcolor{gray}{}`.

**Comment by lvjr** [comment]
Fantastic. `\regex_case_replace_all:nN` is more than what I want.

**Comment by blefloch** [comment]
I've now implemented `\regex_case_match:nn(TF)`, `\regex_case_replace_all:nNTF` and the `replace_once` version in pull request #928.  If that is enough for your purposes, I plan to close this issue because it seems difficult to actually use the positions of matches in practice (and not so easy for l3regex to provide it).

**Comment by lvjr** [comment]
OK.
