### ISSUE TITLE
Updating commands for Property Lists

### ISSUE THREAD

**Issue by car222222** [latex3/latex3#924]
Property lists need update functions, probably added to the section “Adding entries to property lists”.

An example with its (rough) spec:

`\prop_update_from_keyval:Nn \MyPL {< list of  key-val items>}`

Updates `\MyPL` (a ⟨ prop var ⟩, using each of the key–val items in turn as follows:
-  if the key already exists in the PL then set (update) its value from this key-val item;
- otherwise, update the PL by adding the item as done by `\prop_put:...` .

Other examples (names only):
`\prop_update_from_prop:Nn`

**Comment by blefloch** [comment]
No strong opinion on whether to add that.  It can be implemented as
```
\cs_new_protected:Npn \prop_update_from_keyval:Nn #1
  { \keyval_parse:nnn { \@@_update:Nn #1 } { \prop_put:Nnn #1 } }
\cs_new_protected:Npn \@@_update:Nn #1#2
  { \prop_put:Nnn #1 {#2} { } } % or error??
```

**Comment by u-fischer** [comment]
Yes that would be useful, I had a few cases where I wanted to add a bunch of key-val to a prop. But I don't like the name `update`, also because it can't handle the local/global setting correctly. 

`prop_put from_keyval:Nn`  and  `prop_gput_from_keyval:Nn` would imho fit better.

**Comment by car222222** [comment]
I am not too concerned about using the name 'update', even though this is exactly what (in normal language) it is doing.

Does 'put' generally imply 'replace/change or add'.  Do not forget that PLs are somewhat distinct from other data-types due to the keys being unique, thus 'updating' is a distinguishing and characteristic action for them. 

Do not forget the other variants, for updating from another PL or maybe from a single key+val pair rather than a list of them.

**Comment by u-fischer** [comment]
> Does 'put' generally imply 'replace/change or add'.

Well the documentation of `\prop_put:Nnn` says, "If the ⟨key⟩ is already present in the ⟨property list⟩, the existing entry is overwritten by the new ⟨value⟩.".

**Comment by car222222** [comment]
@u-fischer So it does: that sentence looks like a bit of an afterthought.  So that actually does 'updating' too.
Maybe the name of the section should be changed to 'Updating ...' rather than implying that it covers only 'adding'. 

This means that the case of updating 'from a single key/val pair' is already provided, but it is called 'putting'.

**Comment by Skillmon** [comment]
@blefloch better implementation would, imho, be (for symmetry of parsing rules with `\prop_set_from_keyval:Nn`):

```tex
\cs_new_protected:Npn \prop_update_from_keyval:Nn #1#2
  {
    \prop_set_eq:NN \l__prop_internal_prop #1
    \__prop_from_keyval:n {#2}
    \prop_set_eq:NN #1 \l__prop_internal_prop
    \prop_clear:N \l__prop_internal_prop
  }
```

The `\__prop_from_keyval:n` function doesn't handle active commas or equal signs at all (the whole `l3prop` module doesn't). And keys without a value throw errors in `l3prop`.
