### ISSUE TITLE
Extra small points on Property Lists

### ISSUE THREAD

**Issue by car222222** [latex3/latex3#925]
About the name: `\prop_const_from_keyval:Nn`

What is the status of “const” here? :  it should be a verb, like set.  
Or maybe the name should be `\prop_const_set_from_keyval:Nn` ?

Documentation query -- 
Does this sentence:
“The ⟨ key ⟩ is stored after processing with `\tl_to_str:n`, meaning that category codes are ignored.” 
apply equally to these two commands? —  `\prop_const/set_from_keyval:Nn`

**Comment by blefloch** [comment]
We have quite a few commands with `(datatype)_set_…`, `(datatype)_gset_…`, and `(datatype)_const_…`, which have the same syntax but expect to assign to a local variable, global variable, or constant variable that will never again be changed.  So in this pattern "const" is treated as a verb, in the same way as "set" and "gset".

Regarding your `\tl_to_str:n` comment, I've added clarification at the start of `l3prop` and mentioned it in `\prop_(const|set)_from_keyval:Nn` so I think we can close this issue here.

**Comment by car222222** [comment]
OK, thanks.  I shall try to invent a suitable verb (or verbal phrase) of which 'const' is a 'contr':-).

**Comment by wspr** [comment]
Clearly the verb we are shortening is `to constantize`, from which is derived `constantiation` to describe the action of doing so :)

**Comment by car222222** [comment]
Thanks, Will!!  :-)

**Comment by blefloch** [comment]
What about "construct"?

**Comment by car222222** [comment]
In fact, 'construct' is what I once thought it did mean!  Now I maybe think I was correct??! 

I changed my interpretation of 'const' to 'constant' because the accompanying text (almost) always  states, essentially:  "Creates a new constant ..."

Looking at the code (for a few of these) shows that there is nothing there to check that it uses 'a constant' rather than a variable, not even a check that the name begins 'c_'

Thus changing all these to:  "Constructs a new (global) variable ..." would maybe sort out this confusion.

However, @blefloch now writes: "... expect to assign to a [local variable, global variable,] or constant variable that will never again be changed."

Confusing!  I do not see why 'intention (no checking done) to create a new constant thing' should be confounded with 'create and explicitly initialise'; they seem to me to be unrelated.

**Comment by blefloch** [comment]
No no no, I was mentioning "construct" in jest, and `const` is a shorthand for constant(ize, as Will suggests to make a verb), nothing else.  It is simply that checking is only done when the `check-declarations` debugging option is on:
```
\RequirePackage[check-declarations]{expl3}
\ExplSyntaxOn
\cs_show:N \tl_const:Nn
```
shows
```
> \tl_const:Nn=\protected\long macro:
#1#2->\__kernel_chk_var_scope:NN c#1\__debug_tl_const:Nn #1{#2}.
```
where `\__kernel_chk_var_scope:NN c #1` basically checks that the given variable starts with `c_`.  With this debugging option, functions such as `\tl_set:Nn` or `\tl_gset:Nn` will only accept variables starting with `l_` or `g_`, respectively, so that they will refuse to change constants.

**Comment by car222222** [comment]
But that still leaves the (maybe unrelated) problem of why only a new constant can be simultaneously initialised. 

 I do not see why 'intention (no checking done) to create a new constant thing' should be confounded with 'create and explicitly initialise'; they seem to me to be unrelated.

**Comment by blefloch** [comment]
Checking is done, as explained in my last message here.

A constant thing cannot be given a value later on, it must be given its value right away, so it wouldn't make sense to separate "create a new constant thing" and "give a value to the constant thing": there would be some time in between where the constant thing is empty/zero/uninitialized before being initialized.  So this explains why `\tl_const:Nn` (constant tl var) (value forever) has to be some atomic operation.

You could argue that it is useful to initialize non-constant variables too, and I agree we could have some `\tl_new:Nn` (tl var) (initial value).  But we have decided almost a decade ago that defining a new variable should have a global effect, so in the case of a local tl var, it wouldn't be clear whether the (initial value) is assigned to the (tl var) locally or globally.

**Comment by FrankMittelbach** [comment]
> But that still leaves the (maybe unrelated) problem of why only a new 
> constant can be simultaneously initialised.
> 
> I do not see why 'intention (no checking done) to create a new constant 
> thing' should be confounded with 'create and explicitly initialise'; 
> they seem to me to be unrelated.
> 

in the early days we had that for some types, eg \tlp_new:Nn  (no tl_) 
but long time ago decided that we separate and have declaration only 
setting a fixed default (internally) and always to the really setting 
separately.

Only exception: constants are always declared and set in one go as 
explained by Bruno.

This is consistent behavior across the whole of the language and nothing 
we should change.

**Comment by car222222** [comment]
All very sophisticated!  

In fact, all(?) declared (created) variables do get (internally) an initial value so this must be done either locally or globally.  Why not also allow it to be an explicit value: are uninitialised variables used a lot? 

Also, local constants are quite common.  

Even more common is declare+initialise: a pity this did not get done some time ago.

@FrankMittelbach It is always possible to add such facilities, even if not on the kernel.  After all, it is only combining two steps into one.  But would such extensions cause practical problems?  Or just spoil the theory?

**Comment by wspr** [comment]
@car222222 local tl is possible of course but not local registers, and for expl3 it was important to unify their interfaces. It is expected that all \l_ variables are allocated globally and modified using locally acting functions. 

I don’t find it a problem in practise to separate the steps of declare and initialise. In some ways I quite like the strict separation it imposes on the code. Note that the check-declarations option allows strict enforcement that the appropriate methods are being used. 

I do sometimes wonder about local variable allocation but I think at this point it’s clear that it’s not necessary and the simplicity of not offering it is a feature in itself.

**Comment by car222222** [comment]
@wspr "I don’t find it a problem in practise to separate the steps of declare and initialise."

Good!  I was just pointing out that it is quite common to support the combination.

**Comment by FrankMittelbach** [comment]
sure it is not uncommon but it bloats the language, you have to add another 100 or so commands which do not give you anything other then filling the string pool. The point is you either have them all and in all variations or you don't and the decision back then was don't as, as you say, it  is just the combination of two commands.

**Comment by car222222** [comment]
"you have to add another 100" -- Added to the 255 for each 8-bit code-point and . . . sure, a major profligacy:-).
