### ISSUE TITLE
str_if_before:nn conditional

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex3#927]
I need a conditional to compare string similar to `\pdf@strcmp`  from the pdftexcmds package. 

Something along these lines

~~~~
\prg_new_conditional:Npnn \str_if_before:nn #1 #2 {p,T,F,TF}
 {
   \int_compare:nNnTF
     { \tex_strcmp:D{#1}{#2}} = {-1}
     { \prg_return_true: }
     { \prg_return_false:}
 }
~~~~

(the PDF format requires that some name lists are sorted lexically).

**Comment by Skillmon** [comment]
The `expl3` name for `\tex_strcmp:D` is `\__str_if_eq:nn`, afaik.

**Comment by u-fischer** [comment]
@Skillmon  yes, you are right (that it is a confusing name ...), but I still need a public name.

**Comment by FrankMittelbach** [comment]
Maybe that should be modeled after `\int_compare:nNnTF`, i.e., `\str_compare:nNnTF` with the `N` being either `<`, `=`, or `>` and internally doing the right thing,

**Comment by u-fischer** [comment]
@FrankMittelbach  that looks cleaner, but I don't know how it would affect the speed - I will manly need the command to sort a sequence of strings.

**Comment by josephwright** [comment]
My worry here of course is that string comparison is (should be) locale-dependent - see the work Biber for example has to do for sorting.

**Comment by u-fischer** [comment]
@josephwright  I don't need locale sorting, but the sorting that the pdf format means when requesting that name tree keys are sorted. So e.g. for destinations one gets this:

~~~~
[(Blub.1) 14 0 R (Doc-Start) 9 0 R (page.1) 8 0 R (section.1) 11 0 R (subsection.1.1) 13 0 R]
~~~~

The output of \pdfstrcmp is fine for this.

**Comment by FrankMittelbach** [comment]
> My worry here of course is that string comparison is (should be) 
> locale-dependent - see the work Biber for example has to do for sorting.

text comparisons should be  but "str" I don't know. This datatype has a 
confusing name, as it is *not* text but the name makes you think that 
--- which I think is wrong.

**Comment by blefloch** [comment]
@u-fischer I notice that your example is sorted both with and without taking letter case into account.  Where would `(chapter.1)` sit in your list?

I second Frank's suggestion of `\str_compare:nNnTF`.  It is not slower.  (The following code is untested but straightforward.)
```
\prg_new_conditional:Npnn \str_compare:nNnTF #1#2#3 { p, T, F, TF }
  {
    \if_int_compare:w \tex_strcmp:D {#1} {#3} #2 \c_zero_int
      \prg_return_true:
    \else:
      \prg_return_false:
    \fi:
  }
```

**Comment by u-fischer** [comment]
> I notice that your example is sorted both with and without taking letter case into account. Where would `(chapter.1)` sit in your list?

it is sorted by ascii order, so uppercase first B,D, then lowercase p, se, su.  chapter.1 would be behind Doc-Start. 

 > I second Frank's suggestion of \str_compare:nNnTF

it is fine with me, I can test it tomorrow.

**Comment by u-fischer** [comment]
> I second Frank's suggestion of `\str_compare:nNnTF`. It is not slower. (The following code is untested but straightforward.)
> 
> ```
> \prg_new_conditional:Npnn \str_compare:nNnTF #1#2#3 { p, T, F, TF }


It should be 

`prg_new_conditional:Npnn \str_compare:nNn #1#2#3 {p,T,F,TF}` but beside this it seems to work fine and does what I need to sort the names.

**Comment by blefloch** [comment]
I'm adding it in 5min when the l3kernel tests finish on my machine.
