### ISSUE TITLE
Optimize \tl_set_eq:NN

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#932]
Currently `\tl_set_eq:NN` and `\cs_set_eq:NN` are defined by
```
\cs_new_protected:Npn \tl_set_eq:NN #1#2 { \cs_set_eq:NN #1#2 }
\cs_new_protected:Npn \cs_set_eq:NN #1 { \tex_let:D #1 = ~ }
```
Of course `=~` are important in case `\cs_set_eq:NN` is used to set a token equal to `=` or to a space.  But `\tl_set_eq:NN \l_tmpa_tl =` would not make any sense, so I contend that we should just make
```
\cs_new_protected:Npn \tl_set_eq:NN #1#2 { \tex_let:D #1#2 }
```
Note that grabbing the arguments helps in case they were braced (which is wrong, but accepted by essentially all commands).  I'm fine with not grabbing.

**Comment by FrankMittelbach** [comment]
I would stay with grabbing, it would be a slight optimization not to, but I guess it would needlessly break some code, and as you say, basically bracing N arguments is accepted everywhere.

**Comment by wspr** [comment]
Are you okay that someone would then be able to write 

    \tl_set_eq:NN \foo + 
    % now \foo is a character token

    \tl_set_eq:NN \foo =
    \baz
    % now \foo is let to \baz

People probably shouldn't be writing this, so it's possibly okay especially if it leads to performance improvements. Just double-checking the edge case.

**Comment by davidcarlisle** [comment]
why not keep the =?

`\cs_new_protected:Npn \tl_set_eq:NN #1#2 { \tex_let:D #1=~#2 }`

whatever the speed differences this seems more consistent than having it silently ignore = and eat the following token as in Will's example.  This would still optimise away the expansion though `\cs_set_eq:NN`

**Comment by FrankMittelbach** [comment]
I would say neither usage in Will's example is ok: a tl should never be a char token, but for efficiency reasons I don't see that you can test for this, so I'm not sure it is worth fixing the second case (where we can) but it is so obviously wrong syntax that I don't see why we should care.

**Comment by PhelypeOleinik** [comment]
A lot of LaTeX in general just breaks with bizarre input, so sanity-checking the arguments of `\tl_set_eq:NN` is really too much I think.  However David's proposal:

> `\cs_new_protected:Npn \tl_set_eq:NN #1#2 { \tex_let:D #1=~#2 }`

seems very reasonable, as we'd avoid weird `=` behaviour as in Will's second example.  Besides, TeX is faster (by an annoyingly small amount) when the `=` is there.  I see no reason not to add the explicit `=` in the definition.

**Comment by FrankMittelbach** [comment]
Interesting, so checking for = and not finding it means that Tex puts the found token back on the stack? and then takes it off again? or what is the reason for being slightly faster? It thought it would be the other way around and without it is faster, but if not then by all means, why not put it there.

**Comment by PhelypeOleinik** [comment]
@FrankMittelbach Yes, the procedure `scan_optional_equals` gets a token unconditionally, and if it's not a `=`<sub>12</sub>, the token is put back on the input stream with `back_input` (which is relatively slow):
```pascal
@p procedure scan_optional_equals;
begin  @<Get the next non-blank non-call token@>;
if cur_tok<>other_token+"=" then back_input;
end;
```
so when TeX sees the `=` it has less work to do.  The difference boils down to one `back_input` less, so it's faster, but by very little.  The good thing about the `=` there is really avoiding the weird behaviour with the speed as a bonus.

**Comment by blefloch** [comment]
Thanks Phelype for the benchmarking.

Along the same vein, I'm removing the `by` from all `\advance ... by \thingexpr ... \relax`, because this speeds things up a bit.  The only drawback is that if someone does the completely nonsensical `\dim_set:Nn { \dimen 123 } { 45pt }` they now end up with `\advance \dimen 123 45 pt` and an error because `45` are taken as part of the dimen's explicit number.

**Comment by PhelypeOleinik** [comment]
> `\dim_set:Nn { \dimen 123 } { 45pt }` they now end up with `\advance \dimen 123 45 pt` and an error

Not quite, because our `\dim_set:Nn` uses `\dimexpr` so the user ends up with `\dimen 123 \dimexpr 45pt \relax`, so it would work either way.

Speaking of which, `\dim_set:Nn` and a few others could also use the added `=`, if that's the level of optimisation we are seeking.

**Comment by blefloch** [comment]
Ah, you're right about the `\dimexpr` saving the day.

Yes, I did the `\dim_set:Nn` and similar changes in the same commit, I forgot to mention it, thanks.
