### ISSUE TITLE
\color_set:nn explodes before backend is loaded

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#936]
Currently, `\color_set:nn { mycol } { blue }` breaks with an undefined control sequence `\__color_backend_pickup:N`.  It would be nicer to have a proper error message.  Of course this affects any `l3color` function that attempts to use backend-defined macros.

I don't know enough about `l3color` to know where to hook, but I would guess `\__color_parse:nN` is a good candidate.

**Comment by josephwright** [comment]
'Fixed' by 0b575cfe2c4e6058e3a4e57ede99dd4de39af887 (as in that change is for other reasons but means this is no longer an issue).
