### ISSUE TITLE
l3seq: unindented code examples in doc section "Sequences as sets"

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#945]
This is because the `\ ` used at the beginning of a line inside `quote` environment is ignored by default.

For example
![image](https://user-images.githubusercontent.com/6376638/121467986-ab663880-c9ec-11eb-8026-49ce688d5007.png)
https://github.com/latex3/latex3/blob/95436ed690026255060de12ddd3cf113ad51265b/l3kernel/l3seq.dtx#L896-L901

**Comment by blefloch** [comment]
The same problem is almost certainly there in other places in the latex3 repository since I thought that this would work.  A good way to find them would be to search `quote`.  By the way, is there a less ugly solution than `\mbox{}\ \ `?

**Comment by muzimuzhi** [comment]
`l3doc.dtx` used `\begin{quote}\parskip=0pt\obeylines`, which might be preferable. For example
https://github.com/latex3/latex3/blob/95436ed690026255060de12ddd3cf113ad51265b/l3kernel/l3doc.dtx#L512-L523

**Comment by car222222** [comment]
Both of these indentation hacks are very strange-looking!

**Comment by josephwright** [comment]
Yes and I think this is something that will want to be handled better in the `l3doc` re-working, but for the present I wanted to fix the actual output!
