### ISSUE TITLE
l3text: \text_expand:n throws low level errors for a macro that expands to nothing in two steps

### ISSUE THREAD

**Issue by Skillmon** [latex3/latex3#946]
The following will result in a low level TeX error (`Use of \__text_expand_space:w doesn't match its definition.`):

```
\def\a{\b}
\def\b{}
\ExplSyntaxOn
\text_expand:n { \a }
\ExplSyntaxOff
```

**Comment by josephwright** [comment]
It's not general: it's because `\b` is an accent ...

**Comment by josephwright** [comment]
For example, try
```latex
\def\a{\b}
\def\b{}
\ExplSyntaxOn
\tl_remove_all:Nn \l_text_accents_tl { \b }
\text_expand:n { \a }
\ExplSyntaxOff
```

**Comment by Skillmon** [comment]
Makes sense. So, user error? (I should've spend more time taking a more thorough look at it, sorry for the noise)

**Comment by josephwright** [comment]
I'm not 100% sure - I suppose I could add a check that the apparent accent commands are really accent, but it gets somewhat tricky. Perhaps best to add this to the docs? 'If you use an accent command for other purposes, you _must_ remove it from the standard accent list'?

**Comment by Skillmon** [comment]
@josephwright well, it is wrong to do `\def\b` in the first place and every experienced TeX user will tell you this. But what I don't understand is the fact that this results in a low level error, while the documentation says it should just be excluded from expansion. So I'd expect the result of `\text_expand:n { \b }` to be `\b`.

**Comment by Skillmon** [comment]
(though admittedly, correct input would include an argument to `\b`...)

**Comment by josephwright** [comment]
The issue comes up as the accent commands are not protected, not long, _etc._, so the easiest way to pick them up is with a hard-coded list. That then assumes that they have an argument we can grab.

I guess an alternative would be to deprecate that approach and use the fact that they look like
```latex
\<accent>=macro:
-> \<enc>-cmd \<accent> \<enc>\<accent>
```
so I could look for that pattern to pick them out.

**Comment by josephwright** [comment]
I guess what is happening in a sense is the same as if you'd done
```latex
\def\foo#1{}
\text_expand:n { \foo }
```
although that might not be obvious ;)

**Comment by blefloch** [comment]
Doing

\text_expand:n { Mistaken trailing accent \' }

seems like a plausible user error.  Would there be a simple way to catch that?
Perhaps by adding a bunch of trailing \s_text_mark markers at the end of the
text to be expanded, then later filtering them out.

**Comment by blefloch** [comment]
My point (which I forgot to state) was that the error could be much nicer when
the argument of an accent is missing.

By the way, why is the argument of an accent protected from expansion?

I agree that Skillmon's example is arguably correct.

**Comment by josephwright** [comment]
@blefloch You get an error as they are commands _known_ to take an argument, so when I try to do `\foo{...}` and the `{...}` is missing, TeX is not happy. I guess I can treat them without the argument grabbing.

**Comment by FrankMittelbach** [comment]
> My point (which I forgot to state) was that the error could be much nicer when the argument of an accent is missing.

true but the same would be the case for any `\foo` with arbitrary signature whose arguments are missing. But that is something you can't reasonably catch without looking at the sig of each and every command and grab for it slowly. Granted a low-level error is not nice, but I guess you get it in all cases, so why handle accents specially? I doubt that they happen more often ther other errors.

**Comment by josephwright** [comment]
I guess I've tried to save a step I shouldn't have ... I'll adjust a bit

**Comment by josephwright** [comment]
Current
```latex
\cs_new:Npn \@@_expand_exclude:N #1
  {
    \exp_args:Ne \@@_expand_exclude:nN
      {
        \exp_not:V \l_text_math_arg_tl
        \exp_not:V \l_text_accents_tl
        \exp_not:V \l_text_expand_exclude_tl
      }
    #1
  }
```
can I guess be split into 'exclude' and 'accent commands', with a different storage strategy.

**Comment by blefloch** [comment]
> true but the same would be the case for any |\foo| with arbitrary signature
> whose arguments are missing. But that is something you can't reasonably catch
> without looking at the sig of each and every command and grab for it slowly.
> Granted a low-level error is not nice, but I guess you get it in all cases, so
> why handle accents specially? I doubt that they happen more often ther other errors.

I suggest to just add a bunch of \s_text_mark scan marks (hence set to \relax)
at the end of the argument of \text_expand:n throughout processing.  This way
any command that has mandatory arguments, or stars, optional arguments etc. will
work fine (obviously we cannot catch "\foo[..." with an unclosed optional argument).

Perhaps adding a bunch of \c_empty_tl instead is better.

**Comment by FrankMittelbach** [comment]
>  Perhaps adding a bunch of \c_empty_tl instead is better.

empty would process the erronous input without a warning wouldn't it? Not sure that is better, is it?What you really want is to get to an error (but not low-level) that has a run-time cost of net to zero unless the error happens. The low-level one is kind of perfect in that sense except that it is low-level :-)
