### ISSUE TITLE
`...set_eq` constants: impossible or non sense?

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#947]
The compilation of the following MCE fails because of:
>! LaTeX3 Error: The variable \c__mymodule_b_tl has not been declared ...

and, even if it is declared:
> Local assignment to a constant variable '\c__mymodule_b_tl'.

or
>Global assignment to a constant variable '\c__mymodule_b_tl'.

Is it impossible (or non-sense) to `..._set_eq` constant ⟨tl var⟩?
```latex
\RequirePackage[check-declarations,enable-debug]{expl3}
\documentclass{article}
\ExplSyntaxOn
\tl_const:Nn  \c__mymodule_a_tl { foo }
% \tl_new:N     \c__mymodule_b_tl
\tl_set_eq:NN \c__mymodule_b_tl \c__mymodule_a_tl
% \tl_gset_eq:NN \c__mymodule_b_tl \c__mymodule_a_tl
\ExplSyntaxOff
\begin{document}
\end{document}
```

**Comment by josephwright** [comment]
You can only make constants using `\<thing>_const:Nn` or similar.

**Comment by Skillmon** [comment]
The whole meaning of constants is that they are set only once and from that time on remain *constant*. `\cs_generate_variant:Nn \tl_const:Nn { No } \tl_const:No \c__mymodule_b_tl { \c__mymodule_a_tl }`. But I wonder what's the point of having two identical constants? Most of the time a single one should suffice, shouldn't it?

**Comment by dbitouze** [comment]
> But I wonder what's the point of having two identical constants?

I can understand :)

> Most of the time a single one should suffice, shouldn't it?

Indeed. It is because of a package of mine which is supposed to be most of the time (but not always) used with a class of mine. It sets some (dimensions in fact) constants except if corresponding ones in the class have been defined: in such a case, these constants have to be set equal to the corresponding ones.

But I managed with something like:
```latex
\tl_const:Nn  \c__mymodule_b_tl { \c__mymodule_a_tl }
```

**Comment by Skillmon** [comment]
Well, in that case I'd use something like the following:

```
\cs_generate_variant:Nn \tl_const:Nn { NV }
\tl_const:NV \c__mymodule_b_tl \c__mymodule_a_tl
```

**Comment by dbitouze** [comment]
Much more elegant! :) Is it really worth going from what I did to what you are proposing?

**Comment by FrankMittelbach** [comment]
@dbitouze yes. Depending on the downstream usage yours may even be wrong. Consider the same but using a clist constant:
```
\clist_const:Nn  \c__mymodule_a_clist  {a,b,c}
\clist_const:Nn  \c__mymodule_b_clist { \c__mymodule_a_clist }
```
"a" is a clist with 3 items but
"b" is a clist with one item (a clist that contains 3 items). Yours is the same with tokens, so you need 2 expansions to get to the content. May not matter but may ...

**Comment by dbitouze** [comment]
Is it worth for `expl3` to provide `\tl_const:NV`?

**Comment by FrankMittelbach** [comment]
Our approach is to provide variants only if we see significant usage, after all `\cs_generate_variant:Nn` can be done multiple times without harm, so it is a balance between using up code space to a small time penalty.  So for now I would say, do it in your class or package.
