### ISSUE TITLE
Documentation interface3.pdf: keys

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex3#951]
The `.code:n` description on page 224 reads:

The ⟨code⟩ can include one parameter (#1), which will be the ⟨value⟩ given for the ⟨key⟩.

When inside a function this is not #1 but ##1, ...

At first glance, one can understand that `\keys_define:nn` cannot be used inside a function.

**Comment by PhelypeOleinik** [comment]
This is true for everything described in `interface3` that takes `<inline code>` as argument (notably `\..._map_inline:` functions). If I recall correctly, somewhere in `interface3` it is mentioned that inside a definition you need to double hashes. If it isn't, it would probably be good to have a section about that, but I'd not add it to every single function that takes `<inline code>` as argument.
