### ISSUE TITLE
`l3color`'s named colors: why so few?

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#955]
`l3color` currently provides the following named colors: `black`, `white`, `red`, `green`, `blue`, `cyan`, `magenta` and `yellow`. 

By contrast, `xcolor` provides in addition the following ones: `gray`, `darkgray`, `lightgray`, `brown`, `lime`, `olive`, `orange`, `pink`, `purple`, `teal` and `violet`. 

Is there a reason for `l3color` to provide so few named colors?

**Comment by josephwright** [comment]
The colours provided by `l3color` are primary ones for the different colour models. In contrast, something like `brown` is arbitrary: there is a value-judgement on what mix it is (and how that translates into different models). That is to me something that should be left to a higher level package or the user.
