### ISSUE TITLE
`\__pdf_backend_link_begin_goto:nnw`  fails in distiller

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex3#957]
In the following example the l3-version of the GoTo links fails in distiller, it stays on the second page  (with ps2pdf it works fine). The hyperref version of the link works in both. 

~~~~
\documentclass{article}
\usepackage{hyperref}
\begin{document}
\section{Introduction}\label{intro}


\newpage
\ExplSyntaxOn
\leavevmode
\__pdf_backend_link_begin_goto:nnw {}
   {section.1}l3backend
\__pdf_backend_link_end:


\ExplSyntaxOff

\hyperref[intro]{Section~\ref*{intro}}
\end{document}
~~~~

**Comment by josephwright** [comment]
Using pdfTeX one gets
```
<<
/Type /Annot
/Subtype /Link
/Border[0 0 1]/H/I/C[1 0 0]
/Rect [147.716 644.284 189.559 653.084]
/A << /S /GoTo /D (section.1) >>
>>
```
from the primitive, and I'm pretty sure I was aiming for 'the same thing' in PostScript, except I've not abbreviated `/Dest` or `/SubType`. and currently haven't got the border/colour detail.

I suspect we could do with someone who _really_ knows Distiller to say if it's getting things wrong here, or if we are.
