### ISSUE TITLE
Colons e.g. in `\definecolor{⋯}{rgb:Hsb}{⋯}` not allowed between `\ExplSyntaxOn/\ExplSyntaxOff`

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#962]
(Original report [here](https://github.com/lvjr/ninecolors/issues/1).)

The following MCE:
```latex
% \RequirePackage{pdfmanagement-testphase}
% \DeclareDocumentMetadata{}
\documentclass{article}
\usepackage{xcolor}
\ExplSyntaxOn
\definecolor{blue3}{rgb:Hsb}{240,0.67,0.70}
\ExplSyntaxOff
\begin{document}
Test.
\end{document}
```
compiles like a charm but, as soon as the two first lines are commented out, throws the error:

>! LaTeX3 Error: Unknown color model 'rgb:Hsb'.
>
>For immediate help type H <return>.
> ...                                              
>                                                  
>l.6 \definecolor{blue3}{rgb:Hsb}{240,0.67,0.70}

**Comment by lvjr** [comment]
There is a similar problem here: https://tex.stackexchange.com/questions/614621/tabularray-and-rgb-xcolor-option

Is it a bug of `xcolor` or my wrong usage of `xcolor` package in `ninecolors` package?

If it is the former, should I open an issue at https://github.com/latex3/xcolor/issues?

**Comment by u-fischer** [comment]
@lvjr This bug here has been resolved. Your problem is another one I opened an issue about it in the xcolor repo. But at a first glance it is not trivial to sort out, so it would be better if you defined your colors in a simpler way, e.g. convert them first.

**Comment by davidcarlisle** [comment]
@lvjr  Ulrike just opened https://github.com/latex3/xcolor/issues/1
