### ISSUE TITLE
l3draw: Add the possibility to shift the baseline

### ISSUE THREAD

**Issue by Skillmon** [latex3/latex3#964]
When one wants to create pictures which should be used inside the text as glyphs, it would be nice to be able to explicitly set the bounding box of the picture. Currently the lower border is set on the baseline, this way, without some box operations involving `\lower`/`\raise` it is impossible to create symbols with descenders (at least without some bounding box trickery involving setting `\l_draw_bb_update_bool`, and then the bounding box could be totally wrong just to get the vertical alignment right).

The PGF-layer has the macro `\pgfsetbaseline` exactly for this.

**Comment by josephwright** [comment]
Honestly, I didn't do much of the scopes part of `pgf` as it was ... not clear what was needed. I'll sort out the baseline stuff and probably the trimming too.

**Comment by Skillmon** [comment]
I don't think trimming is absolutely needed. You already have `clip` and `\l_draw_bb_update_bool`, so unlike the baseline shifting this can already be done from within the documented features (doesn't mean it isn't a nice additional feature, just one with lower priority, since on a more basic level this is already possible from within `l3draw`).

**Comment by josephwright** [comment]
OK, I have a working model for the baseline. One thing I plan to do differently to `pgf` is handling depth. I can see that just because the ymin is negative doesn't mean there's a depth. But if there is an explicit baseline and ymin is below that, I feel there is a depth to the resulting box. Does that sound OK?

**Comment by Skillmon** [comment]
Sounds reasonable.

**Comment by josephwright** [comment]
@Skillmon  See if the current implementation works for you: I've not yet looked at the trimming code
