### ISSUE TITLE
fpexpr → fp expr in interface3.pdf 

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex3#968]
change the`fpexpr` to `fp expr` for better readability and consistency with `fp var`.

**Comment by blefloch** [comment]
Probably also relevant in all other modules (e.g. `intexpr` could be changed to `int expr`).
I have no opinion on whether to do that.

**Comment by FrankMittelbach** [comment]
We are somewhat inconsistent here. Part of the code say `<fpexpr>` or `<intexpr>` part of it says `<floating point expression>` or `<integer expression>`. Not sure if we should normalize on the short or the long form. I updated to the short forms to see how it looks, but maybe always using the long forms is actually better.

**Comment by josephwright** [comment]
I think we did this :)

**Comment by muzimuzhi** [comment]
Seems not.  For example,
```
grep -rn -e '\\\(meta\|Arg\){integer expression}' l3kernel | wc -l
      46
```
and there are a bit more cases in sibling directories other than `l3kernel`.  I will try to provide a PR for this.

**Comment by josephwright** [comment]
> Seems not. For example,
> 
> ```
> grep -rn -e '\\\(meta\|Arg\){integer expression}' l3kernel | wc -l
>       46
> ```
> 
> and there are a bit more cases in sibling directories other than `l3kernel`. I will try to provide a PR for this.

Ah, thanks: I remember @FrankMittelbach doing something, but perhaps it wasn't comprehensive

**Comment by muzimuzhi** [comment]
> I remember @FrankMittelbach doing something, but perhaps it wasn't comprehensive

Yes it was #971.
