### ISSUE TITLE
[expl3] `log-functions` seems always to be `true`

### ISSUE THREAD

**Issue by Mo-Gul** [latex3/latex3#978]
If I read the manual right stating `log-functions=false` should suppress (some) messages in the LOG. But it seems also stating `log-functions=false` adds a lot more messages to the LOG. This yields the same result as stating `log-functions` only or `log-functions=true`.

```latex
\documentclass{article}
\usepackage[log-functions=false]{expl3}
\begin{document}
    test
\end{document}
```

I have compiled with `LuaHBTeX, Version 1.14.0 (MiKTeX 21.8) (format=lualatex 2021.8.8)` and `expl3 2021-07-12 L3 programming layer (loader)`.

**Comment by eg9** [comment]
The value you pass to `log-functions` is completely ignored, so specifying one of
```
\usepackage[log-functions]{expl3}
\usepackage[log-functions=true]{expl3}
\usepackage[log-functions=false]{expl3}
\usepackage[log-functions=whatever]{expl3}
```
has exactly the same effect. Indeed the documentation doesn't mention possible values, nor says it's a boolean.

It could be argued that there should be `log-function .value_forbidden:n = true`.

**Comment by PhelypeOleinik** [comment]
It'd be better to implement it as a boolean key:
```latex
    log-functions .choice: ,
    log-functions / true .code:n =
      {
        \sys_load_debug:
        \debug_on:n { log-functions }
      } ,
    log-functions / false .code:n =
      {
        \__kernel_if_debug:TF
          { \debug_off:n { log-functions } }
      } ,
```

**Comment by mrpiggi** [comment]
Just guessing:
```
 \__kernel_if_debug:TF
          { }
          { \debug_off:n { log-functions } }
```

**Comment by eg9** [comment]
@PhelypeOleinik
I'm not sure; nowadays, `expl3` is only loaded if debug options are needed, so its options are “on” whenever specified. With the exception of `backend` that takes the driver as value.

**Comment by PhelypeOleinik** [comment]
> Just guessing:
> 
> ```
>  \__kernel_if_debug:TF
>           { }
>           { \debug_off:n { log-functions } }
> ```

Oops, sorry.  Actually the other way around. `\__kernel_if_debug:TF` returns true if `l3debug` is loaded, so you only `\debug_off:n` if that's true.  I fixed my comment

**Comment by PhelypeOleinik** [comment]
@eg9 Well, yes, we could change the documentation and say that `log-functions` only turns logging on, but to me the name `log-functions` calls for a true/false value, and it's no harm to support that...

**Comment by FrankMittelbach** [comment]
@PhelypeOleinik but you can't turn it off (as it is "off" by default) so supporting =false is rather pointless and as you see by the question, it makes people wonder what it does (like why isn't this changing anything?). I would correct the documentation, ie it is off by default and you can turn it on.

**Comment by PhelypeOleinik** [comment]
> but you can't turn it off

(nobody does that but) you can by doing `\sys_load_debug: \debug_on:n { log-functions }` then turning it off again by loading the package.  But that's just silly.  Agreed with changing the documentation
