### ISSUE TITLE
Rollback for LaTeX3

### ISSUE THREAD

**Issue by lvjr** [latex3/latex3#990]
I am still confused: there are rollback versions for LaTeX2e, and there are rollback versions for basic packages (`array`, `longtable`, etc), but there are no rollback versions for LaTeX3 as far as I know.

Now LaTeX3 is part of the kernel. I think it means it is not `Experimental LaTeX3 `(expl3) anymore. I am wondering if it is possible to provide rollback versions when some functions are removed?

**Comment by josephwright** [comment]
Following discussion within the team, we will be modifying the approach to deprecated functions. Whilst we will continue to encourage programmers to update following deprecation, we will not remove any stable functions from `l3kernel` in future. Rather, these will be marked as deprecated using the existing mechanism and then left unchanged. The main changes for this are in https://github.com/latex3/latex3/commit/b6f4de458a112d9250845190cc13be90a5c3f25d: other changes may yet be needed to finalise this.

**Comment by lvjr** [comment]
Good news. Thank you very much!
