### ISSUE TITLE
l3docstrip.dtx fails to compile through latexmk

### ISSUE THREAD

**Issue by atxy-blip** [latex3/latex3#992]
Lately I am working on a class of my own. The DocStrip file works just fine when compiling with xelatex, except that when I started to insert an index to the documentation `latexmk` simply fails to generate the doc. After a few attempts it turned out that the problem may lie in l3doc itself.

I tried to run the command `latexmk l3docstrip.dtx` with the raw file from l3kernal package (version 2021-08-27). However, it seems that there is something wrong with `makeindex` program, and the process stuck after messages like `! LaTeX Error: \verb ended by end of line.`.

For your information, I am currently running MiKTeX 21.8 on Windows with all packages updated. This error can be stably reproduced.

I am genuinely grateful for any help. Thanks for your great work anyway.

**Comment by josephwright** [comment]
Looks like https://tex.stackexchange.com/questions/610349/troubleshooting-printindex-printchanges/615290#615290: you need to be using the right style file.

**Comment by pablgonz** [comment]
@atxy-blip Try this in your `latexmkrc` file:

```raw
$makeindex = "makeindex %O -s gind.ist -o %D %S";
add_cus_dep('glo','gls',0,'makeindex');
sub makeindex {
  if ( $silent ) {
    system( "makeindex -q -s gglo.ist -o \"$_[0].gls\" \"$_[0].glo\"" );
  }
  else {
    system( "makeindex -s gglo.ist -o \"$_[0].gls\" \"$_[0].glo\"" );
  };
}
$makeindex_silent_switch = "-q";
```

**Comment by atxy-blip** [comment]
Thanks very much for your timely support! These solutions works perfectly!

Please forgive me for such ignorance Orz
