### ISSUE TITLE
new key property .code:nn

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex3#995]
There is already a `.code:n` property. The new property should be

```
⟨key ⟩ .code:nn = {⟨code ⟩}
Stores the ⟨code⟩ for execution when ⟨key⟩ is used. The ⟨code⟩ can include two parameters
(#1), which will be the given ⟨key⟩ and (#2) which will be the given ⟨value⟩.
```

this is interesting in at least 2 situations:

```
\keys_define:nn { mymodule }
      {
        key1 .code:nn = \mySharedCommand{#1}{#2},
        key2 .code:nn =  \mySharedCommand{#1}{#2}
      }
```
and
```
  \keys_define:nn { mymodule }
    {
      unknown .code:nn = \myCommand{#1}{#2},
  }
```

**Comment by zauguin** [comment]
First, I don't really see the motivation here:

For you first situation, the current version
```
\keys_define:nn { mymodule }
      {
        key1 .code:n = \mySharedCommand:nn{key1}{#1},
        key2 .code:n =  \mySharedCommand:nn{key2}{#1}
      }
```
is not significantly longer.

For the second one we already have
```
  \keys_define:nn { mymodule }
    {
      unknown .code:n = \myCommand:Vn \l_keys_key_str {#1},
  }
```

The only advantage I see in having `#1` and `#2` is that it would be a bit shorter, but this comes at the cost of having a IMO much less intuitive user interface. Especially for the first version, I would never have guessed that `#1` is just repeating the thing at the beginning of the line. (I think it looks like a shorter way to define a key accepting two arguments.)

Beside that the interface is inconsistent with other `.something:nn` keys: `.code:nn` would not define a key definition accepting two arguments, but would accept two arguments itself. Therefore it would be used like 
```
key .code:nn = { \my_command:n {#1} }{I have no idea what this argument would do}
```

**Comment by jlaurens** [comment]
Good points
