### ISSUE TITLE
l3regex documentation: improvements and question

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex3#996]
In interface3.pdf

## escaping `^`
page 48, near the top, the second bullet : it would be advisable to include `\^` as another example of escaped characters because `^` is frequently used in math mode. That would practically exclude things like `\cU(^)` which do not behave like`(\cU^)` together with similar regular expressions.

## about "next object"
page 51 midway, the explanation for `\cX` reads `Applies to the next object, which can be a character, character property, class, or group,`

1. Escape character sequence should also be mentioned
2. character, class and group are well defined but what is exactly a character property? Is it related to unicode character properties ?
3. Considering that `\cO(abc)` can be used in the replacement text as well, it should be noticed that in the regex it has the "side effect" of capturing a group. BTW, pointing out this difference would also emphasize the fact that a regex group is not a TeX group.

**Comment by blefloch** [comment]
Yes, character property means Unicode property, and it is not implemented, so I've deleted that and made the other changes you suggest.
